alicloud/data_source_alicloud_nas_lifecycle_policies.go, alicloud/data_source_alicloud_nas_lifecycle_policies_test.go, alicloud/provider.go, alicloud/resource_alicloud_nas_lifecycle_policy.go, alicloud/resource_alicloud_nas_lifecycle_policy_test.go, alicloud/service_alicloud_nas.go, website/alicloud.erb, website/docs/d/nas_lifecycle_policies.html.markdown, website/docs/r/nas_lifecycle_policy.html.markdown
New Resource `alicloud_nas_lifecycle_policy`;
New Datasource `alicloud_nas_lifecycle_policies`
=> New Resource `alicloud_nas_lifecycle_policy`; New Datasource `alicloud_nas_lifecycle_policies`

alicloud/data_source_alicloud_instances.go, alicloud/data_source_alicloud_vpc_bgp_networks.go, alicloud/data_source_alicloud_vpc_bgp_networks_test.go, alicloud/provider.go, alicloud/resource_alicloud_rds_upgrade_db_instance.go, alicloud/resource_alicloud_vpc_bgp_network.go, alicloud/resource_alicloud_vpc_bgp_network_test.go, alicloud/service_alicloud_vpc.go, website/alicloud.erb, website/docs/d/vpc_bgp_networks.html.markdown, website/docs/r/vpc_bgp_network.html.markdown
New Resource `alicloud_vpc_bgp_network`;
New Datasource `alicloud_vpc_bgp_networks`
=> New Resource `alicloud_vpc_bgp_network`; New Datasource `alicloud_vpc_bgp_networks`

alicloud/data_source_alicloud_nas_data_flows.go, alicloud/data_source_alicloud_nas_data_flows_test.go, alicloud/provider.go, alicloud/resource_alicloud_cen_transit_router_route_table_association_test.go, alicloud/resource_alicloud_cen_transit_router_route_table_propagation_test.go, alicloud/resource_alicloud_cen_transit_router_route_table_test.go, alicloud/resource_alicloud_nas_data_flow.go, alicloud/resource_alicloud_nas_data_flow_test.go, alicloud/resource_alicloud_nas_mount_target.go, alicloud/service_alicloud_nas.go, scripts/schema_test.go, website/alicloud.erb, website/docs/d/nas_data_flows.html.markdown, website/docs/r/nas_data_flow.html.markdown, website/docs/r/nas_mount_target.html.markdown
New Resource `alicloud_nas_data_flow`
New Datasource `alicloud_nas_data_flows`
=> New Resource `alicloud_nas_data_flow`; New Datasource `alicloud_nas_data_flows`

alicloud/data_source_alicloud_slb_zones.go, alicloud/data_source_alicloud_slb_zones_test.go, website/docs/d/slb_zones.html.markdown
=> datasource/alicloud_slb_zones: Supports new output parameters address_type and address_ip_version

alicloud/resource_alicloud_nas_lifecycle_policy.go, alicloud/resource_alicloud_nas_lifecycle_policy_test.go
testcase: Adds new unit test case for resource
`alicloud_nas_lifecycle_policy`
=> testcase: Adds new unit test case for resource `alicloud_nas_lifecycle_policy`

alicloud/data_source_alicloud_ecs_storage_capacity_units.go, alicloud/data_source_alicloud_ecs_storage_capacity_units_test.go, alicloud/data_source_alicloud_security_groups.go, alicloud/provider.go, alicloud/resource_alicloud_ecs_storage_capacity_unit.go, alicloud/resource_alicloud_ecs_storage_capacity_unit_test.go, alicloud/resource_alicloud_nas_lifecycle_policy_test.go, alicloud/service_alicloud_ecs.go, website/alicloud.erb, website/docs/d/ecs_storage_capacity_units.html.markdown, website/docs/r/ecs_storage_capacity_unit.html.markdown
New Datasource `alicloud_ecs_storage_capacity_units`
=> New Resource `alicloud_ecs_storage_capacity_unit` New Datasource `alicloud_ecs_storage_capacity_units`

alicloud/data_source_alicloud_dbfs_snapshots.go, alicloud/data_source_alicloud_dbfs_snapshots_test.go, alicloud/provider.go, alicloud/resource_alicloud_dbfs_instance.go, alicloud/resource_alicloud_dbfs_instance_attachment.go, alicloud/resource_alicloud_dbfs_instance_attachment_test.go, alicloud/resource_alicloud_dbfs_instance_test.go, alicloud/resource_alicloud_dbfs_snapshot.go, alicloud/resource_alicloud_dbfs_snapshot_test.go, alicloud/service_alicloud_dbfs.go, website/alicloud.erb, website/docs/d/dbfs_snapshots.html.markdown, website/docs/r/dbfs_instance.html.markdown, website/docs/r/dbfs_instance_attachment.html.markdown, website/docs/r/dbfs_snapshot.html.markdown
New Resource `alicloud_dbfs_snapshot`;
New Datasource `alicloud_dbfs_snapshots`;
New Resource `alicloud_dbfs_instance_attachment`
=> New Resource `alicloud_dbfs_snapshot`; New Datasource `alicloud_dbfs_snapshots`; New Resource `alicloud_dbfs_instance_attachment`

alicloud/data_source_alicloud_msc_sub_contact_verification_message.go, alicloud/data_source_alicloud_msc_sub_contact_verification_message_test.go, alicloud/provider.go, website/alicloud.erb, website/docs/d/msc_sub_contact_verification_message.html.markdown, website/docs/r/msc_sub_contact.html.markdown
New Datasource `alicloud_msc_sub_contact_verification_message`
=> New Datasource `alicloud_msc_sub_contact_verification_message`

alicloud/resource_alicloud_alikafka_consumer_group.go, alicloud/resource_alicloud_alikafka_consumer_group_test.go, alicloud/service_alicloud_alikafka.go, website/docs/r/alikafka_consumer_group.html.markdown
…upport for new parameter `description`.
=> resource/alicloud_alikafka_consumer_group: change sdk to common api;Support for new parameter `description`.

alicloud/data_source_alicloud_dts_migration_jobs.go, alicloud/data_source_alicloud_dts_migration_jobs_test.go, alicloud/provider.go, alicloud/resource_alicloud_dts_migration_instance.go, alicloud/resource_alicloud_dts_migration_instance_test.go, alicloud/resource_alicloud_dts_migration_job.go, alicloud/resource_alicloud_dts_migration_job_test.go, alicloud/service_alicloud_dts.go, website/alicloud.erb, website/docs/d/dts_migration_jobs.html.markdown, website/docs/r/dts_migration_instance.html.markdown, website/docs/r/dts_migration_job.html.markdown
New Datasource `alicloud_dts_migration_jobs`
New Resource `alicloud_dts_migration_instance`
=> New Resource `alicloud_dts_migration_job` New Datasource `alicloud_dts_migration_jobs` New Resource `alicloud_dts_migration_instance`

alicloud/connectivity/regions.go, alicloud/data_source_alicloud_mse_gateways.go, alicloud/data_source_alicloud_mse_gateways_test.go, alicloud/provider.go, alicloud/resource_alicloud_mse_gateway.go, alicloud/resource_alicloud_mse_gateway_test.go, alicloud/service_alicloud_mse.go, website/alicloud.erb, website/docs/d/mse_gateways.html.markdown, website/docs/r/mse_gateway.html.markdown
New Resource `alicloud_mse_gateway`;
New Datasource `alicloud_mse_gateways`
=> New Resource `alicloud_mse_gateway`; New Datasource `alicloud_mse_gateways`

alicloud/provider.go, alicloud/resource_alicloud_dbfs_service_linked_role.go, alicloud/resource_alicloud_dbfs_service_linked_role_test.go, alicloud/service_alicloud_dbfs.go, website/alicloud.erb, website/docs/r/dbfs_service_linked_role.html.markdown
New Resource `alicloud_dbfs_service_linked_role`
=> New Resource `alicloud_dbfs_service_linked_role`

alicloud/data_source_alicloud_mongodb_sharding_network_private_addresses.go, alicloud/data_source_alicloud_mongodb_sharding_network_private_addresses_test.go, alicloud/provider.go, alicloud/resource_alicloud_mongodb_sharding_network_private_address.go, alicloud/resource_alicloud_mongodb_sharding_network_private_address_test.go, alicloud/service_alicloud_mongodb.go, website/alicloud.erb, website/docs/d/mongodb_sharding_network_private_addresses.html.markdown, website/docs/r/mongodb_sharding_network_private_address.html.markdown, website/docs/r/mongodb_sharding_network_public_address.html.markdown
New Resource `alicloud_mongodb_sharding_network_private_address`;
New Datasource `alicloud_mongodb_sharding_network_private_addresses`
=> New Resource `alicloud_mongodb_sharding_network_private_address`;New Datasource `alicloud_mongodb_sharding_network_private_addresses`

alicloud/data_source_alicloud_slb_zones.go, alicloud/data_source_alicloud_slb_zones_test.go, alicloud/service_alicloud_rds.go, website/docs/d/slb_zones.html.markdown
=> datasource/alicloud_slb_zones: Adds new parameter master_zone_id and slave_zone_id; Deprecates tehe output slb_slave_zone_ids

CHANGELOG.md, alicloud/provider.go, alicloud/resource_alicloud_ess_alb_server_group_attachment.go, alicloud/resource_alicloud_ess_alb_server_group_attachment_test.go, alicloud/service_alicloud_ess.go, website/docs/r/ess_alb_server_group_attachment.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEssAlbServerGroups_basic -timeout=300m
=== RUN   TestAccAlicloudEssAlbServerGroups_basic
--- PASS: TestAccAlicloudEssAlbServerGroups_basic (49.36s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  51.119s
=> **New Resource:** `alicloud_ess_alb_server_group_attachment`

alicloud/resource_alicloud_cs_kubernetes_node_pool.go, alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go, go.mod, go.sum, vendor/github.com/denverdino/aliyungo/cs/node_pool.go, vendor/modules.txt, website/docs/r/cs_kubernetes_node_pool.html.markdown
resource/alicloud_cs_kubernetes_node_pool: support to specify desired node size for node pool.
=> resource/alicloud_cs_kubernetes_node_pool: support to specify desired node size for node pool

alicloud/connectivity/regions.go, alicloud/data_source_alicloud_dcdn_ipa_domains.go, alicloud/data_source_alicloud_dcdn_ipa_domains_test.go, alicloud/provider.go, alicloud/resource_alicloud_dcdn_ipa_domain.go, alicloud/resource_alicloud_dcdn_ipa_domain_test.go, alicloud/service_alicloud_dcdn.go, website/alicloud.erb, website/docs/d/dcdn_ipa_domains.html.markdown, website/docs/r/dcdn_ipa_domain.html.markdown
New Resource `alicloud_dcdn_ipa_domain`;
New Datasource `alicloud_dcdn_ipa_domains`
=> New Resource `alicloud_dcdn_ipa_domain`; New Datasource `alicloud_dcdn_ipa_domains`

alicloud/data_source_alicloud_ecp_instance_types_test.go, alicloud/data_source_alicloud_ecp_instances_test.go, alicloud/data_source_alicloud_ecp_zones_test.go, website/docs/d/ecp_instances.html.markdown
testcase: Improves the provider testcase when changing the supported regions
=> testcase: Improves the provider testcase when changing the supported regions

alicloud/common.go, alicloud/resource_alicloud_nat_gateway.go
=> resource/alicloud_nat_gateway: fixes the TaskConflict error when there are multi nat gateways to create

alicloud/common.go, alicloud/data_source_alicloud_amqp_virtual_hosts_test.go, alicloud/data_source_alicloud_ecs_dedicated_hosts_test.go, alicloud/data_source_alicloud_rdc_organizations_test.go, alicloud/data_source_alicloud_sddp_data_limits.go, alicloud/data_source_alicloud_sddp_data_limits_test.go, alicloud/data_source_alicloud_simple_application_server_custom_images_test.go, alicloud/data_source_alicloud_slb_load_balancers_test.go, alicloud/provider.go, alicloud/resource_alicloud_event_bridge_event_bus_test.go, alicloud/resource_alicloud_sddp_data_limit.go, alicloud/resource_alicloud_sddp_data_limit_test.go, alicloud/service_alicloud_sddp.go, website/alicloud.erb, website/docs/d/sddp_data_limits.html.markdown, website/docs/r/sddp_data_limit.html.markdown
New Datasource `alicloud_sddp_data_limits`
=> New Resource `alicloud_sddp_data_limit` New Datasource `alicloud_sddp_data_limits`

alicloud/resource_alicloud_ram_role.go, website/docs/r/ram_role.html.markdown
=> resource/alicloud_ram_role: supports setting timeouts when creating and deleting

alicloud/resource_alicloud_ram_role.go
=> resource/alicloud_ram_role: Fixes the Throttling.User error on ListPoliciesForRole

alicloud/data_source_alicloud_ecs_image_components.go, alicloud/data_source_alicloud_ecs_image_components_test.go, alicloud/provider.go, alicloud/resource_alicloud_ecs_image_component.go, alicloud/resource_alicloud_ecs_image_component_test.go, alicloud/service_alicloud_ecs.go, website/alicloud.erb, website/docs/d/ecs_image_components.html.markdown, website/docs/r/ecs_image_component.html.markdown
New Resource `alicloud_ecs_image_component`;
New Datasource `alicloud_ecs_image_components`
=> New Resource `alicloud_ecs_image_component`; New Datasource `alicloud_ecs_image_components`

alicloud/resource_alicloud_datahub_project.go
=> resource/alicloud_datahub_project: Fix the updating project comment diff error

alicloud/data_source_alicloud_sae_application_scaling_rules.go, alicloud/data_source_alicloud_sae_application_scaling_rules_test.go, alicloud/provider.go, alicloud/resource_alicloud_sae_application_scaling_rule.go, alicloud/resource_alicloud_sae_application_scaling_rule_test.go, alicloud/service_alicloud_sae.go, website/alicloud.erb, website/docs/d/sae_application_scaling_rules.html.markdown, website/docs/r/sae_application_scaling_rule.html.markdown
New Resource `alicloud_sea_application_scaling_rule`;
New Datasource `alicloud_sea_application_scaling_rules`
=> New Resource `alicloud_sea_application_scaling_rule`; New Datasource `alicloud_sea_application_scaling_rules`

CHANGELOG.md, alicloud/resource_alicloud_ess_scaling_group.go, alicloud/resource_alicloud_ess_scaling_group_test.go, alicloud/resource_alicloud_vswitch_test.go, ci/pipeline-cn.yml, ci/pipeline.yml, website/docs/r/ess_scaling_group.html.markdown
TF_ACC=1 go te
st ./alicloud -v -run=TestAccAlicloudEssScalingGroup_withLaunchTemplateId -timeout=300m
go: downloading github.com/denverdino/aliyungo v0.0.0-20220218034049-d2eb7f483ee8
=== RUN   TestAccAlicloudEssScalingGroup_withLaunchTemplateId
--- PASS: TestAccAlicloudEssScalingGroup_withLaunchTemplateId (55.38s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  57.324s
=>  resource/alicloud_ess_scaling_group: new parameter launch_template_version

alicloud/resource_alicloud_alikafka_sasl_user.go, alicloud/resource_alicloud_alikafka_sasl_user_test.go, alicloud/service_alicloud_alikafka.go, website/docs/r/alikafka_sasl_user.html.markdown
=> resource/alicloud_alikafka_sasl_user: change sdk to common api;Support for new parameter `type`.

alicloud/data_source_alicloud_cloud_firewall_instances.go, alicloud/resource_alicloud_cloud_firewall_instance.go, alicloud/service_alicloud_arms.go, alicloud/service_alicloud_bss_open_api.go, website/docs/r/cloud_firewall_instance.html.markdown
=> resource/cloud_firewall_instance: Add Support for the international site.

alicloud/data_source_alicloud_sae_grey_tag_routes.go, alicloud/data_source_alicloud_sae_grey_tag_routes_test.go, alicloud/provider.go, alicloud/resource_alicloud_sae_grey_tag_route.go, alicloud/resource_alicloud_sae_grey_tag_route_test.go, alicloud/service_alicloud_arms.go, alicloud/service_alicloud_sae.go, website/alicloud.erb, website/docs/d/sae_grey_tag_routes.html.markdown, website/docs/r/sae_grey_tag_route.html.markdown
New Datasource `alicloud_sae_grey_tag_routes`
=> New Resource `alicloud_sae_grey_tag_route` New Datasource `alicloud_sae_grey_tag_routes`

alicloud/resource_alicloud_vpn_gateway.go, alicloud/resource_alicloud_vpn_gateway_test.go, alicloud/service_alicloud_arms.go, alicloud/service_alicloud_vpc.go, website/docs/r/vpn_gateway.html.markdown
…ew parameters `vpn_type`, `auto_pay`, `tags`.
=> resource/alicloud_vpn_gateway: change sdk to common api;Support for new parameters `auto_pay`, `tags`.

alicloud/resource_alicloud_vpn_customer_gateway.go, alicloud/resource_alicloud_vpn_customer_gateway_test.go, alicloud/service_alicloud_vpc.go, website/docs/r/vpn_customer_gateway.html.markdown
=> resource/alicloud_vpn_customer_gateway: change sdk to common api;Support for new parameter `asn`.

alicloud/data_source_alicloud_vpc_nat_ips_test.go, alicloud/resource_alicloud_express_connect_virtual_border_router.go, alicloud/resource_alicloud_router_interface.go, alicloud/resource_alicloud_vpc_nat_ip_test.go, alicloud/service_alicloud_ecs.go
=> resource/resource_alicloud_express_connect_virtual_border_router: Fixes the DependencyViolation.BgpGroup error when deleting the resource

alicloud/data_source_alicloud_ecs_dedicated_hosts_test.go, alicloud/data_source_alicloud_images_test.go, alicloud/data_source_alicloud_instances_test.go, alicloud/resource_alicloud_ecs_dedicated_host_test.go, alicloud/resource_alicloud_ecs_disk.go, alicloud/resource_alicloud_ecs_network_interface.go, alicloud/resource_alicloud_instance.go, alicloud/resource_alicloud_instance_test.go
=> resource/alicloud_instance: Adds checking empty before setting period to avoid a invalid value 0

alicloud/data_source_alicloud_ecs_dedicated_hosts_test.go, alicloud/data_source_alicloud_images.go, alicloud/data_source_alicloud_rds_accounts_test.go, alicloud/provider_test.go, alicloud/resource_alicloud_ecs_disk.go, alicloud/resource_alicloud_ecs_disk_test.go, alicloud/resource_alicloud_instance_test.go, alicloud/service_alicloud_ecs.go, website/docs/r/ecs_disk.html.markdown
=> resource/alicloud_ecs_disk: Fixes the DiskNotPortable error while modifying disk payment type

alicloud/provider_test.go, alicloud/resource_alicloud_event_bridge_rule.go, alicloud/resource_alicloud_event_bridge_rule_test.go, alicloud/resource_alicloud_hbase_instance.go, website/docs/r/event_bridge_rule.html.markdown
=> resource/alicloud_event_bridge_rule: Fixes the diff error which caused by system default value

alicloud/data_source_alicloud_cms_monitor_group_instances_test.go, alicloud/data_source_alicloud_slb_backend_servers_test.go, alicloud/data_source_alicloud_slb_listeners_test.go, alicloud/data_source_alicloud_slb_load_balancers_test.go, alicloud/data_source_alicloud_slb_rules_test.go, alicloud/data_source_alicloud_slb_server_groups_test.go, alicloud/resource_alicloud_cms_metric_rule_template_test.go, alicloud/resource_alicloud_cms_monitor_group_instances_test.go, alicloud/resource_alicloud_slb_attachment_test.go, alicloud/resource_alicloud_slb_backend_server_test.go, alicloud/resource_alicloud_slb_load_balancer_test.go, alicloud/resource_alicloud_slb_rule_test.go, alicloud/resource_alicloud_slb_server_group_test.go
=> testcase: Improves the slb resources testcase

alicloud/data_source_alicloud_ecs_snapshot_groups.go, alicloud/data_source_alicloud_ecs_snapshot_groups_test.go, alicloud/provider.go, alicloud/resource_alicloud_ecs_snapshot_group.go, alicloud/resource_alicloud_ecs_snapshot_group_test.go, alicloud/service_alicloud_ecs.go, website/alicloud.erb, website/docs/d/ecs_snapshot_groups.html.markdown, website/docs/r/ecs_snapshot_group.html.markdown
New Resource `alicloud_ecs_snapshot_group`;
New Datasource `alicloud_ecs_snapshot_groups`
=> New Resource `alicloud_ecs_snapshot_group`; New Datasource `alicloud_ecs_snapshot_groups`

alicloud/resource_alicloud_mongodb_audit_policy.go, alicloud/resource_alicloud_mongodb_instance_test.go, alicloud/resource_alicloud_mongodb_serverless_instance_test.go, alicloud/resource_alicloud_mongodb_sharding_instance_test.go, alicloud/service_alicloud_mongodb.go
=> resource/alicloud_mongodb_instance: Adds retry for invoking DescribeDBInstanceAttribute and ResetPassword

alicloud/resource_alicloud_mongodb_audit_policy.go, alicloud/resource_alicloud_slb_backend_server_test.go, ci/pipeline.yml
=> resource/alicoud_mongodb_audit_policy: Fixes the OperationDenied.DBInstanceStatus error when creating or updating this resource

alicloud/resource_alicloud_mongodb_sharding_instance.go, website/docs/r/hbase_instance.html.markdown, website/docs/r/mongodb_sharding_instance.html.markdown
=> resource/alicloud_mongodb_sharding_instance: Supports to update attribute tde_status

alicloud/resource_alicloud_bastionhost_instance_test.go, alicloud/resource_alicloud_lindorm_instance.go, alicloud/resource_alicloud_lindorm_instance_test.go, alicloud/resource_alicloud_pvtz_rule_attachment_test.go, alicloud/resource_alicloud_yundun_dbaudit_instance_test.go, website/docs/r/lindorm_instance.html.markdown
=> resource/alicloud_lindorm_instance: Enlarges the its default creating timeout

alicloud/resource_alicloud_bastionhost_instance.go, alicloud/resource_alicloud_bastionhost_instance_test.go, ci/pipeline.yml, website/docs/r/bastionhost_instance.html.markdown
=> resource/alicloud_bastionhost_instance: Updates the attribute security_group_ids type to set from list

alicloud/resource_alicloud_dcdn_domain.go, alicloud/resource_alicloud_dcdn_domain_test.go
=> resource/alicloud_dcdn_domain: Fixes the wait timeout error when offline the domain

alicloud/data_source_alicloud_dcdn_domains_test.go, alicloud/resource_alicloud_alikafka_instance.go, alicloud/resource_alicloud_alikafka_instance_test.go, website/docs/r/alikafka_instance.html.markdown
=> resource/alicloud_alikafka_instance: Supports to update attribute deploy_type

alicloud/resource_alicloud_msc_sub_subscription.go
…g of `CreateSubscriptionItem`
=> resource/alicloud_msc_sub_subscription: Optimize the handling of creating return values

alicloud/resource_alicloud_vpn_route_entry.go, alicloud/service_alicloud_vpc.go, website/docs/r/vpn_route_entry.html.markdown
…or new parameters  `route_entry_type`, `status`.
=> resource/alicloud_vpn_route_entry: change sdk to common api;Support for new parameters  `route_entry_type`, `status`.

alicloud/data_source_alicloud_cen_transit_router_vpc_attachments_test.go, alicloud/data_source_alicloud_dms_enterprise_instances_test.go, alicloud/data_source_alicloud_dms_enterprise_users_test.go, alicloud/data_source_alicloud_dms_user_tenants.go, alicloud/data_source_alicloud_dms_user_tenants_test.go, alicloud/data_source_alicloud_eais_instances_test.go, alicloud/provider.go, alicloud/resource_alicloud_ddoscoo_instance_test.go, alicloud/resource_alicloud_dms_enterprise_instance_test.go, alicloud/resource_alicloud_drds_instance.go, alicloud/resource_alicloud_eais_instance_test.go, ci/pipeline.yml, website/docs/d/dms_user_tenants.html.markdown
=> New Datasource: alicloud_dms_user_tenants; Improves the dms testcases; Improves the eais testcase

alicloud/resource_alicloud_nas_file_system.go
=> reource/alicloud_nas_file_system: Fixes the retry implementation bug to fix Throttling.Api error

alicloud/resource_alicloud_drds_instance.go
=> resource/alicloud_drds_instance: Fixes the InternalError by adding retry implementation

alicloud/data_source_alicloud_yundun_dbaudit_instances_test.go, alicloud/resource_alicloud_yundun_dbaudit_instance_test.go, ci/pipeline.yml
=> testcase: Improve the yundun dbaudit testcases

alicloud/data_source_alicloud_sddp_rules_test.go, alicloud/resource_alicloud_actiontrail_history_delivery_job_test.go, alicloud/resource_alicloud_adb_db_cluster_test.go, alicloud/resource_alicloud_alb_listener_test.go, alicloud/resource_alicloud_rds_account.go, alicloud/service_alicloud_common_test.go
=> reource/alicloud_rds_account: Fixes the retry implementation bug to fix Throttling error; Improves the several testcases

alicloud/connectivity/client.go, alicloud/connectivity/regions.go, alicloud/data_source_alicloud_eipanycast_anycast_eip_addresses_test.go, alicloud/data_source_alicloud_simple_application_server_custom_images_test.go, alicloud/resource_alicloud_auto_provisioning_group_test.go, alicloud/resource_alicloud_eipanycast_anycast_eip_address_attachment_test.go, alicloud/resource_alicloud_eipanycast_anycast_eip_address_test.go
=> resource/alicloud_eipanycast_address_attachment: Fixes the InvalidRegionId error when descring eipanycast endpoint

alicloud/data_source_alicloud_bastionhost_host_accounts_test.go, alicloud/data_source_alicloud_bastionhost_host_groups_test.go, alicloud/data_source_alicloud_bastionhost_hosts_test.go, alicloud/data_source_alicloud_bastionhost_instances.go, alicloud/data_source_alicloud_bastionhost_user_groups_test.go, alicloud/data_source_alicloud_bastionhost_users_test.go, alicloud/resource_alicloud_bastionhost_host_account_test.go, alicloud/resource_alicloud_bastionhost_host_account_user_attachment_test.go, alicloud/resource_alicloud_bastionhost_host_account_user_group_attachment_test.go, alicloud/resource_alicloud_bastionhost_host_attachment_test.go, alicloud/resource_alicloud_bastionhost_host_group_account_user_attachment_test.go, alicloud/resource_alicloud_bastionhost_host_group_account_user_group_attachment_test.go, alicloud/resource_alicloud_bastionhost_host_group_test.go, alicloud/resource_alicloud_bastionhost_host_test.go, alicloud/resource_alicloud_bastionhost_user_attachment_test.go, alicloud/resource_alicloud_bastionhost_user_group_test.go, alicloud/resource_alicloud_bastionhost_user_test.go
=> datasource/alicloud_bastionhost_instances: Fiexes the Throttling.User error by adding retry implementation

alicloud/provider.go, alicloud/resource_alicloud_alb_listener.go, alicloud/resource_alicloud_alb_listener_additional_certificate_attachment.go, alicloud/resource_alicloud_alb_listener_additional_certificate_attachment_test.go, alicloud/resource_alicloud_alb_listener_test.go, alicloud/service_alicloud_alb.go, website/alicloud.erb, website/docs/r/alb_listener.html.markdown, website/docs/r/alb_listener_additional_certificate_attachment.html.markdown, website/docs/r/alikafka_instance.html.markdown
resource/alb_listener: Optimize `XForward` field
=> New Resource `alb_listener_additional_certificate_attachment` resource/alb_listener: Optimize `XForward` field

alicloud/data_source_alicloud_msc_sub_webhooks_test.go, alicloud/resource_alicloud_alb_listener_additional_certificate_attachment_test.go, alicloud/resource_alicloud_alb_listener_test.go, alicloud/resource_alicloud_msc_sub_webhook_test.go
…rtificate_attachment: Fix test case bugs
=> resource/alicloud_msc_sub_webhook,alicloud_alb_listener_additional_certificate_attachment: Fix test case bugs

alicloud/connectivity/regions.go, alicloud/data_source_alicloud_bastionhost_instances.go, alicloud/data_source_alicloud_cddc_dedicated_host_accounts_test.go, alicloud/data_source_alicloud_cddc_dedicated_host_groups.go, alicloud/data_source_alicloud_cddc_dedicated_host_groups_test.go, alicloud/data_source_alicloud_cddc_dedicated_hosts_test.go, alicloud/data_source_alicloud_slb_zones.go, alicloud/resource_alicloud_cddc_dedicated_host_account.go, alicloud/resource_alicloud_cddc_dedicated_host_account_test.go, alicloud/resource_alicloud_cddc_dedicated_host_group.go, alicloud/resource_alicloud_cddc_dedicated_host_group_test.go, alicloud/resource_alicloud_cddc_dedicated_host_test.go, alicloud/resource_alicloud_cdn_domain_config_test.go, alicloud/resource_alicloud_log_ingestion.go, alicloud/service_alicloud_cddc.go, website/docs/d/cddc_dedicated_host_groups.html.markdown, website/docs/r/cddc_dedicated_host_group.html.markdown
=> resource/alicloud_cddc_dedicated_host_account: Adds wait after creating the resource to avoid notfounderror; Improves the testcases

alicloud/data_source_alicloud_simple_application_server_instances_test.go, alicloud/data_source_alicloud_simple_application_server_plans.go, alicloud/data_source_alicloud_simple_application_server_plans_test.go, alicloud/data_source_alicloud_slb_zones.go, alicloud/resource_alicloud_cen_route_entry_test.go, alicloud/resource_alicloud_msc_sub_subscription.go, website/docs/r/bastionhost_instance.html.markdown, website/docs/r/msc_sub_subscription.html.markdown
=> resource/alicloud_msc_sub_subscription: Update contact_ids type to a set to avoid potential diff error

alicloud/resource_alicloud_cen_instance_test.go, alicloud/resource_alicloud_cen_route_map.go, alicloud/resource_alicloud_cen_route_map_test.go, alicloud/resource_alicloud_cen_transit_router_route_table.go, alicloud/resource_alicloud_cen_transit_router_route_table_association.go, alicloud/resource_alicloud_cen_transit_router_route_table_propagation.go, website/docs/r/cen_transit_router_route_table_association.html.markdown, website/docs/r/cen_transit_router_route_table_propagation.html.markdown
=> resource/alicloud_cen_route_map: Fixes the MissingParameter error because of missing DestinationCidrBlocks when invoking ModifyCenRouteMap

alicloud/data_source_alicloud_cr_ee_namespaces.go, alicloud/data_source_alicloud_cr_ee_namespaces_test.go, alicloud/data_source_alicloud_ddoscoo_ports_test.go, alicloud/data_source_alicloud_drds_instances_test.go, alicloud/resource_alicloud_cr_chart_repository_test.go, alicloud/resource_alicloud_ddoscoo_port_test.go, alicloud/service_alicloud_cr_ee.go, website/docs/d/cr_ee_namespaces.html.markdown
=> datasource/alicloud_cr_ee_namespace: Adds two outputs namespace_name and namespace_id; Improves the ids values

alicloud/resource_alicloud_polardb_endpoint.go, website/docs/r/polardb_endpoint.html.markdown
resource/alicloud_polardb_endpoint: Add support for output parameters `db_endpoint_id`.
=> resource/alicloud_polardb_endpoint: Add support for output parameters `db_endpoint_id`.

alicloud/resource_alicloud_mongodb_audit_policy.go, alicloud/resource_alicloud_mongodb_audit_policy_test.go, website/docs/r/mongodb_audit_policy.html.markdown
resource/alicloud_mongodb_audit_policy:Fix test cases; supports timeouts setting.
=> resource/alicloud_mongodb_audit_policy:Fix test cases; supports timeouts setting.

alicloud/resource_alicloud_cen_instance_test.go, alicloud/resource_alicloud_cen_route_map.go, alicloud/resource_alicloud_express_connect_physical_connection_test.go, alicloud/resource_alicloud_vpc_bgp_group_test.go, alicloud/resource_alicloud_vpc_bgp_network_test.go, alicloud/resource_alicloud_vpc_bgp_peer_test.go
=> resource/alicloud_cen_route_map: Fixes the InternalError when creating this resource

alicloud/data_source_alicloud_ga_ip_sets_test.go, alicloud/resource_alicloud_ga_ip_set.go
=> resource/alicloud_ga_ip_set: Fixes the MissingIpSetIds error while deleting this resource

alicloud/data_source_alicloud_ga_accelerators_test.go, alicloud/data_source_alicloud_ga_endpoint_groups_test.go, alicloud/resource_alicloud_ga_additional_certificate.go, alicloud/resource_alicloud_ga_additional_certificate_test.go, alicloud/resource_alicloud_mhub_app_test.go, website/docs/r/ga_additional_certificate.html.markdown
=> resource/alicloud_ga_additional_certificate: Waiting the accelerator and listener to be active after creating or deleting additional certificate

alicloud/data_source_alicloud_vpn_connections_test.go, alicloud/data_source_alicloud_vpn_customer_gateways_test.go, alicloud/data_source_alicloud_vpn_gateways_test.go, alicloud/data_source_alicloud_vpn_ipsec_servers_test.go, alicloud/resource_alicloud_datahub_project_test.go, alicloud/resource_alicloud_datahub_topic_test.go, alicloud/resource_alicloud_ddoscoo_instance.go, alicloud/resource_alicloud_ddoscoo_instance_test.go, alicloud/resource_alicloud_ecd_simple_office_site_test.go, alicloud/resource_alicloud_mhub_product_test.go, alicloud/resource_alicloud_vpn_connection_test.go, alicloud/resource_alicloud_vpn_customer_gateway_test.go, alicloud/resource_alicloud_vpn_gateway_test.go, alicloud/resource_alicloud_vpn_ipsec_server_test.go, alicloud/resource_alicloud_vpn_route_entry_test.go, alicloud/service_alicloud_cas.go, alicloud/service_alicloud_ddoscoo.go, ci/pipeline.yml
=> resource/alicloud_ddoscoo_instance: Fixes the Throttling.User error while invoking the DescribeInstanceSpecs

alicloud/resource_alicloud_ecd_simple_office_site.go, alicloud/resource_alicloud_ecd_simple_office_site_test.go
=> resource/alicloud_ecd_simple_office_site: Fixes the DesktopAccessTypeNotChanged when invoking the ModifyOfficeSiteAttribute

alicloud/resource_alicloud_cen_instance.go
=> resource/alicloud_cen_instance: Fixes the InvalidOperation.CenInstanceStatus error while deleting the resource

alicloud/data_source_alicloud_vpcs_test.go, alicloud/resource_alicloud_vpc.go, alicloud/service_alicloud_vpc.go, website/docs/r/vpc.html.markdown
=> datasource/alicloud_vpcs: Fixes the vpc is not found because of it does not return system route table

alicloud/data_source_alicloud_cen_private_zones_test.go, alicloud/resource_alicloud_cen_instance_attachment.go, alicloud/resource_alicloud_event_bridge_event_source_test.go
=> resource/alicloud_cen_instance_attachment: Fixes the InstanceStatus.NotSupport error while invoking DetachCenChildInstance

alicloud/data_source_alicloud_cassandra_backup_plans_test.go, alicloud/data_source_alicloud_cassandra_clusters_test.go, alicloud/data_source_alicloud_cassandra_data_centers_test.go, alicloud/data_source_alicloud_cassandra_zones_test.go, alicloud/data_source_alicloud_cddc_dedicated_host_groups_test.go, alicloud/resource_alicloud_cassandra_backup_plan_test.go, alicloud/resource_alicloud_cassandra_cluster_test.go, alicloud/resource_alicloud_cassandra_data_center_test.go, alicloud/resource_alicloud_dbfs_instance.go, website/docs/r/dbfs_instance.html.markdown
=> resource/alicloud_dbfs_instance: Enlarges the delete default timeout

alicloud/data_source_alicloud_cddc_dedicated_host_groups_test.go, alicloud/resource_alicloud_cddc_dedicated_host_group_test.go, website/docs/r/cddc_dedicated_host_group.html.markdown
=> docs: Adds a note for resource/alicloud_cddc_dedicated_host_group to mark sqlServer does not support setting disk_allocation_ratio

alicloud/data_source_alicloud_vpn_route_entries.go, alicloud/data_source_alicloud_vpn_route_entries_test.go, alicloud/provider.go, alicloud/resource_alicloud_vpn_pbr_route_entry.go, alicloud/resource_alicloud_vpn_pbr_route_entry_test.go, alicloud/service_alicloud_vpc.go, website/alicloud.erb, website/docs/d/vpn_pbr_route_entries.html.markdown, website/docs/r/vpn_pbr_route_entry.html.markdown
New Datasource `alicloud_vpn_pbr_route_entries`
=> New Resource `alicloud_vpn_pbr_route_entry` New Datasource `alicloud_vpn_pbr_route_entries`

alicloud/data_source_alicloud_cddc_dedicated_hosts_test.go, alicloud/data_source_alicloud_dts_consumer_channels_test.go, alicloud/data_source_alicloud_dts_migration_jobs_test.go, alicloud/data_source_alicloud_dts_subscription_jobs_test.go, alicloud/data_source_alicloud_dts_synchronization_jobs_test.go, alicloud/resource_alicloud_cddc_dedicated_host_test.go, alicloud/resource_alicloud_dts_consumer_channel_test.go, alicloud/resource_alicloud_dts_job_monitor_rule.go, alicloud/resource_alicloud_dts_job_monitor_rule_test.go, alicloud/resource_alicloud_dts_migration_instance_test.go, alicloud/resource_alicloud_dts_subscription_job.go, alicloud/resource_alicloud_dts_subscription_job_test.go, alicloud/resource_alicloud_dts_synchronization_instance_test.go, alicloud/resource_alicloud_dts_synchronization_job_test.go, alicloud/service_alicloud_rds.go, website/docs/r/dts_subscription_job.html.markdown
=> resource/alicloud_dts_job_monitor_rule: Removes the attribute phone Computed setting

alicloud/service_alicloud_yundun_bastionhost.go
=> resource/alicloud_yundun_bastionhost: Fixes the InvalidApi error while invoking DescribeInstanceAttribute

alicloud/data_source_alicloud_cdn_real_time_log_deliveries_test.go, alicloud/data_source_alicloud_cdn_service_test.go, alicloud/resource_alicloud_cdn_domain_config_test.go, alicloud/resource_alicloud_cdn_domain_new_test.go, alicloud/resource_alicloud_cdn_domain_test.go, alicloud/resource_alicloud_cen_route_entry_test.go, alicloud/resource_alicloud_cloud_storage_gateway_express_sync_share_attachment_test.go, ci/pipeline.yml
=> testcase: Improves the cen and cloud_storage_gateway_express_sync_share_attachment testcases

alicloud/resource_alicloud_cms_monitor_group_instances_test.go, alicloud/service_alicloud_cms.go
…ge turning of query interface data
=> resource/alicloud_cms_monitor_group_instances: Fix the problem of page turning of query interface data

alicloud/resource_alicloud_alb_load_balancer.go, alicloud/service_alicloud_alb.go
=> resource/alicloud_alb_load_balancer: Fixes the updating load_balancer_edition not effect bug

alicloud/data_source_alicloud_cs_serverless_kubernetes_clusters.go, alicloud/data_source_alicloud_cs_serverless_kubernetes_clusters_test.go, alicloud/resource_alicloud_cs_serverless_kubernetes.go, alicloud/resource_alicloud_cs_serverless_kubernetes_test.go, go.mod, go.sum, scripts/schema_test.go, vendor/github.com/denverdino/aliyungo/common/client.go, vendor/github.com/denverdino/aliyungo/cs/clusters.go, vendor/github.com/denverdino/aliyungo/cs/kubernets_cluster.go, vendor/github.com/denverdino/aliyungo/cs/serverless.go, vendor/modules.txt, website/docs/r/cs_serverless_kubernetes.html.markdown
resource/alicloud_cs_serverless_kubernetes:
1. Support for creating professional serverless cluster.
2. Modify the snat parameters passed when creating serverless cluster.
datasource/data_source_alicloud_cs_serverless_kubernetes_clusters:
1. Optimized filter conditions for return values
=> resource/alicloud_cs_serverless_kubernetes: Support for creating professional serverless cluster

alicloud/provider.go, alicloud/resource_alicloud_slb_acl.go, alicloud/resource_alicloud_slb_acl_entry_attachment.go, alicloud/resource_alicloud_slb_acl_entry_attachment_test.go, alicloud/service_alicloud_slb.go, website/alicloud.erb, website/docs/r/slb_acl.html.markdown, website/docs/r/slb_acl_entry_attachment.html.markdown
New Resource alicloud_slb_acl_entry_attachment
=> New Resource alicloud_slb_acl_entry_attachment

alicloud/resource_alicloud_fc_function_test.go, alicloud/resource_alicloud_kvstore_connection.go, scripts/schema_test.go, website/docs/r/kvstore_connection.html.markdown
=> resource/alicloud_kvstore_connection: Enlarges the creating default timeout

alicloud/resource_alicloud_cloud_storage_gateway_gateway_file_share_test.go
=> testcase: Improve the resource alicloud_cloud_storage_gateway_gateway_file_share unit testcase

alicloud/provider.go, alicloud/resource_alicloud_log_resource.go, alicloud/resource_alicloud_log_resource_record.go, alicloud/resource_alicloud_log_resource_record_test.go, alicloud/resource_alicloud_log_resource_test.go, alicloud/service_alicloud_log.go, website/alicloud.erb, website/docs/r/log_resource.html.markdown, website/docs/r/log_resource_record.html.markdown
sls的资源类数据管理，resource：表格定义，resource_record：表格内容
=> New Resource `alicloud_log_resource` and  `alicloud_log_resource_record`

alicloud/resource_alicloud_mongodb_audit_policy.go, website/docs/r/mongodb_audit_policy.html.markdown
=> resource/alicloud_mongodb_audit_policy: Enlarges the creating and updating default timeout

alicloud/data_source_alicloud_ecs_image_pipelines.go, alicloud/data_source_alicloud_ecs_image_pipelines_test.go, alicloud/data_source_alicloud_instance_types.go, alicloud/data_source_alicloud_instance_types_test.go, alicloud/provider.go, alicloud/resource_alicloud_ecs_image_pipeline.go, alicloud/resource_alicloud_ecs_image_pipeline_test.go, alicloud/service_alicloud_ecs.go, website/alicloud.erb, website/docs/d/ecs_image_pipelines.html.markdown, website/docs/d/instance_types.html.markdown, website/docs/r/ecs_image_pipeline.html.markdown
New Resource `alicloud_ecs_image_pipeline`;
New Datasource `alicloud_ecs_image_pipelines`;
New Datasource `alicloud_ecs_image_support_instance_types`.
=> New Resource `alicloud_ecs_image_pipeline`; New Datasource `alicloud_ecs_image_pipelines`; New Datasource `alicloud_ecs_image_support_instance_types`.

alicloud/provider.go, alicloud/resource_alicloud_slb_listener.go, alicloud/resource_alicloud_slb_server_group.go, alicloud/resource_alicloud_slb_server_group_server_attachment.go, alicloud/resource_alicloud_slb_server_group_server_attachment_test.go, alicloud/service_alicloud_slb.go, scripts/schema_test.go, website/alicloud.erb, website/docs/r/log_etl.html.markdown, website/docs/r/slb_listener.html.markdown, website/docs/r/slb_server_group.html.markdown, website/docs/r/slb_server_group_server_attachment.html.markdown
New Resource `alicloud_slb_server_group_server_attachment`
=> New Resource `alicloud_slb_server_group_server_attachment`

alicloud/resource_alicloud_slb_rule.go, alicloud/service_alicloud_slb.go, website/docs/r/slb_rule.html.markdown
resource/alicloud_slb_rule: Updates its dependence SDK. supports delete timeouts setting.
=> resource/alicloud_slb_rule: Updates its dependence SDK. supports delete timeouts setting.

alicloud/resource_alicloud_ga_listener.go
resource/alicloud_ga_listener: Optimize the update logic for `certificates` attributes.
=> resource/alicloud_ga_listener: Optimize the update logic for `certificates` attributes.

alicloud/resource_alicloud_cms_alarm.go, alicloud/resource_alicloud_cms_alarm_test.go, alicloud/service_alicloud_cms.go, website/docs/r/cms_alarm.html.markdown
resource/alicloud_cms_alarm: supports timeouts setting. Updates its dependence SDK.
=> resource/alicloud_cms_alarm: supports timeouts setting. Updates its dependence SDK.

alicloud/data_source_alicloud_ddoscoo_instances.go
datasource/alicloud_ddoscoo_instances: Updates its dependence SDK.
=> datasource/alicloud_ddoscoo_instances: Updates its dependence SDK.

alicloud/provider.go, alicloud/resource_alicloud_alb_listener.go, alicloud/resource_alicloud_alb_listener_acl_attachment.go, alicloud/resource_alicloud_alb_listener_acl_attachment_test.go, alicloud/service_alicloud_alb.go, website/alicloud.erb, website/docs/r/alb_listener.html.markdown, website/docs/r/alb_listener_acl_attachment.html.markdown
New Resource `alicloud_alb_listener_acl_attachment`.
=> New Resource `alicloud_alb_listener_acl_attachment`.

alicloud/resource_alicloud_ddoscoo_scheduler_rule.go, alicloud/resource_alicloud_ddoscoo_scheduler_rule_test.go, alicloud/service_alicloud_ddoscoo.go, website/docs/r/ddoscoo_scheduler_rule.html.markdown
resource/alicloud_ddoscoo_instances: Updates its dependence SDK. Optimize documentation.
=> resource/alicloud_ddoscoo_instances: Updates its dependence SDK. Optimize documentation.

alicloud/data_source_alicloud_emr_main_versions.go, alicloud/service_alicloud_emr.go
Datasource/emr_main_versions: Updates its dependence SDK.
=> datasource/emr_main_versions: Updates its dependence SDK.

alicloud/connectivity/client.go, alicloud/resource_alicloud_ess_scalinggroup_vserver_groups.go, website/docs/r/ess_scalinggroup_vserver_groups.html.markdown
=> resource/alicloud_ess_scalinggroup_vserver_groups : Updates its dependence SDK

alicloud/data_source_alicloud_kvstore_instances.go, alicloud/data_source_alicloud_kvstore_instances_test.go, alicloud/resource_alicloud_hbr_ots_backup_plan_test.go, alicloud/service_alicloud_r_kvstore.go
datasource/alicloud_kvstore_instances: Updates its dependence SDK.
=> datasource/alicloud_kvstore_instances: Updates its dependence SDK.

alicloud/data_source_alicloud_kvstore_instances.go
=> datasource/alicloud_kvstore_instances: Fix `auto_renew` return value is incorrect

alicloud/data_source_alicloud_mse_clusters_test.go, alicloud/resource_alicloud_mse_cluster.go, alicloud/resource_alicloud_mse_cluster_test.go, alicloud/service_alicloud_mse.go, website/docs/r/mse_cluster.html.markdown
=> resource/alicloud_mse_cluster: Improves the throwing error message implementation while invoking the OpenAPI

alicloud/resource_alicloud_kvstore_instance.go, scripts/schema_test.go, website/docs/r/kvstore_instance.html.markdown
=> resource/alicloud_kvstore_instance: Added error retry code `Task.Conflict`

alicloud/data_source_alicloud_bastionhost_instances.go, alicloud/resource_alicloud_cen_instance_test.go, alicloud/resource_alicloud_cen_transit_router_vbr_attachment.go, alicloud/resource_alicloud_cen_transit_router_vbr_attachment_test.go, alicloud/resource_alicloud_cms_alarm_contact_group.go, alicloud/resource_alicloud_cms_group_metric_rule_test.go, website/docs/r/cen_transit_router_vbr_attachment.html.markdown
=> resource/alicloud_cen_transit_vbr_atachment: Enlarges the default timeout for creating, updateing and deleting

alicloud/resource_alicloud_log_dashboard.go, alicloud/resource_alicloud_log_dashboard_test.go, alicloud/service_alicloud_log.go, website/docs/r/log_dashboard.html.markdown
使用SDK中的Create/UpdateDashboardString替换Create/UpdateDashboard用法
支持更灵活的dashboard结构
=> `resource/alicloud_log_dashboard`: update dashboard to support action in char_list

alicloud/resource_alicloud_cms_alarm.go
resource/alicloud_cms_alarm :  Fixes the empty pointer error
=> resource/alicloud_cms_alarm :  Fixes the empty pointer error

alicloud/resource_alicloud_instance.go, alicloud/resource_alicloud_instance_test.go, scripts/schema_test.go, website/docs/r/instance.html.markdown
resource/alicloud_instance: Support field `operator_type`.
=> resource/alicloud_instance: Support field `operator_type`.

alicloud/service_alicloud_r_kvstore.go
=> resource/alicloud_r_kvstore: Filter out the security ip generated by the system

alicloud/resource_alicloud_ess_alb_server_group_attachment.go, alicloud/resource_alicloud_ess_alb_server_group_attachment_test.go
=== RUN   TestAccAlicloudEssAlbServerGroupAttachment_basic
--- PASS: TestAccAlicloudEssAlbServerGroupAttachment_basic (184.04s)
=== RUN   TestAccAlicloudEssAlbServerGroupAttachment_nonForceAttach
--- PASS: TestAccAlicloudEssAlbServerGroupAttachment_nonForceAttach (68.81s)
PASS
ok  	github.com/aliyun/terraform-provider-alicloud/alicloud	255.948s
=> resource/alicloud_ess_alb_server_group_attachment: Fixes the resource not found error

alicloud/data_source_alicloud_waf_certificates_test.go, alicloud/data_source_alicloud_waf_domains_test.go, alicloud/data_source_alicloud_waf_instances_test.go, alicloud/resource_alicloud_express_connect_virtual_border_router.go, alicloud/resource_alicloud_waf_certificate_test.go, alicloud/resource_alicloud_waf_domain_test.go, alicloud/resource_alicloud_waf_instance_test.go
=> resource/alicloud_express_connect_virtual_border_router: Adds retry stragety for error code TaskConflict

alicloud/data_source_alicloud_mse_znodes_test.go, alicloud/resource_alicloud_mse_znode_test.go, alicloud/resource_alicloud_oss_bucket_replication_test.go, alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_cluster_test.go, alicloud/resource_alicloud_polardb_endpoint_test.go, alicloud/resource_alicloud_route_entry_test.go, alicloud/resource_alicloud_sae_load_balancer_internet.go, alicloud/resource_alicloud_vpc_flow_log_test.go, alicloud/service_alicloud_polardb.go, website/docs/r/polardb_cluster.html.markdown
=> resource/alicloud_polardb_cluster: Improves setting the attribute db_cluster_ip_array

alicloud/connectivity/regions.go, alicloud/data_source_alicloud_fc_custom_domains_test.go, alicloud/resource_alicloud_ess_eci_scaling_configuration.go, alicloud/resource_alicloud_fc_custom_domain_test.go, alicloud/resource_alicloud_fc_function_test.go, alicloud/resource_alicloud_sae_load_balancer_internet_test.go
=> testcase: Improves the fc resources testcases

alicloud/data_source_alicloud_ecd_commands_test.go, alicloud/resource_alicloud_fnf_execution_test.go, alicloud/resource_alicloud_oos_application_group.go, alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_cluster_test.go, alicloud/service_alicloud_ons.go, alicloud/service_alicloud_polardb.go
=> resource/alicloud_polardb_cluster: Fixes updating the attribute db_cluster_ip_array is not working bug

alicloud/data_source_alicloud_fc_custom_domains_test.go, alicloud/data_source_alicloud_ga_forwarding_rules_test.go, alicloud/resource_alicloud_ecs_network_interface_test.go, alicloud/resource_alicloud_ga_bandwidth_package_attachment.go, alicloud/resource_alicloud_ga_forwarding_rule_test.go, alicloud/resource_alicloud_ons_topic_test.go, alicloud/resource_alicloud_vpn_gateway_test.go, website/docs/r/ga_bandwidth_package_attachment.html.markdown
=> resource/alicloud_ga_bandwidth_package_attachment: Enlarges the default timeout for creating and deleting

alicloud/provider.go, alicloud/resource_alicloud_cdn_fc_trigger.go, alicloud/resource_alicloud_cdn_fc_trigger_test.go, alicloud/service_alicloud_cdn.go, website/alicloud.erb, website/docs/r/adb_cluster.html.markdown, website/docs/r/cdn_fc_trigger.html.markdown
New Resource `alicloud_cdn_fc_trigger`.
=> New Resource `alicloud_cdn_fc_trigger`.

alicloud/data_source_alicloud_fc_custom_domains_test.go, alicloud/resource_alicloud_cms_alarm.go
resource/alicloud_cms_alarm :  Fixes the empty pointer error
=>  resource/alicloud_cms_alarm :  Fixes the empty pointer error

alicloud/resource_alicloud_vpc_flow_log.go
=> resource/alicloud_vpc_flow_log: Adds retry stragety for error code `OperationConflict`

alicloud/provider.go, alicloud/resource_alicloud_bastionhost_host_account_share_key_attachment.go, alicloud/resource_alicloud_bastionhost_host_account_share_key_attachment_test.go, alicloud/service_alicloud_yundun_bastionhost.go, website/alicloud.erb, website/docs/r/bastionhost_host_account_share_key_attachment.html.markdown
New Resource `alicloud_bastionhost_host_account_share_key_attachment`
=> New Resource `alicloud_bastionhost_host_account_share_key_attachment`

alicloud/connectivity/regions.go
=> Supports new region ap-southeast-7

alicloud/data_source_alicloud_cs_kubernetes_addon_metadata.go, alicloud/data_source_alicloud_cs_kubernetes_addon_metadata_test.go, alicloud/data_source_alicloud_cs_kubernetes_addons.go, alicloud/provider.go, alicloud/resource_alicloud_cs_kubernetes_addon.go, alicloud/service_alicloud_cs.go, go.sum, website/alicloud.erb, website/docs/d/cs_kubernetes_addon_metadata.html.markdown, website/docs/d/cs_kubernetes_addons.html.markdown, website/docs/r/cs_kubernetes_addon.html.markdown
1. datasource/alicloud_cs_kubernetes_addon_metadata: Add new data source alicloud_cs_kubernetes_addon_metadata.
2. datasource/alicloud_cs_kubernetes_addons: Add new return field config.
3. resource/alicloud_cs_kubernetes_addon: Support to modify the custom configuration of the kubernetes cluster addon.
=> resource/alicloud_cs_kubernetes_addon: Support to modify the custom configuration of the kubernetes cluster addon

alicloud/provider.go, alicloud/resource_alicloud_alb_acl.go, alicloud/resource_alicloud_alb_acl_entry_attachment.go, alicloud/resource_alicloud_alb_acl_entry_attachment_test.go, alicloud/service_alicloud_alb.go, website/alicloud.erb, website/docs/r/alb_acl.html.markdown, website/docs/r/alb_acl_entry_attachment.html.markdown
New Resource `alb_acl_entry_attachment`
=> New Resource `alb_acl_entry_attachment`

alicloud/connectivity/regions.go, alicloud/resource_alicloud_cs_kubernetes_node_pool.go, alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go, go.mod, go.sum, vendor/github.com/denverdino/aliyungo/cs/node_pool.go, vendor/modules.txt, website/docs/r/cs_kubernetes_node_pool.html.markdown
resource/alicloud_cs_kubernetes_node_pool: ACK nodepool support system disk BYOK
=> resource/alicloud_cs_kubernetes_node_pool: ACK nodepool support system disk BYOK

alicloud/resource_alicloud_slb_acl.go, alicloud/resource_alicloud_slb_acl_test.go
resource/alicloud_slb_acl: Fix bugs that cannot create ipv6.
=> resource/alicloud_slb_acl: Fix bugs that cannot create ipv6.

alicloud/data_source_alicloud_mse_engine_namespaces.go, alicloud/data_source_alicloud_mse_engine_namespaces_test.go, alicloud/provider.go, alicloud/resource_alicloud_alb_acl_entry_attachment.go, alicloud/resource_alicloud_hbr_replication_vault_test.go, alicloud/resource_alicloud_mongodb_sharding_network_public_address_test.go, alicloud/resource_alicloud_msc_sub_contact.go, alicloud/resource_alicloud_msc_sub_contact_test.go, alicloud/resource_alicloud_msc_sub_subscription_test.go, alicloud/resource_alicloud_msc_sub_webhook.go, alicloud/resource_alicloud_msc_sub_webhook_test.go, alicloud/resource_alicloud_mse_engine_namespace.go, alicloud/resource_alicloud_mse_engine_namespace_test.go, alicloud/service_alicloud_mse.go, website/alicloud.erb, website/docs/d/mse_engine_namespaces.html.markdown, website/docs/r/mse_engine_namespace.html.markdown
New Resource `alicloud_mse_engine_namespace`;
New Datasource `alicloud_mse_engine_namespaces`;
=> New Resource `alicloud_mse_engine_namespace`; New Datasource `alicloud_mse_engine_namespaces`;

alicloud/resource_alicloud_network_acl.go
should not be passed when the request UpdateEgressAclEntries parameters NetworkAclEntryName and Description are empty
=> resource/alicloud_network_acl: request UpdateEgressAclEntries parameter error

alicloud/resource_alicloud_fc_function_async_invoke_config.go, alicloud/resource_alicloud_fc_function_async_invoke_config_test.go, go.mod, go.sum, vendor/github.com/aliyun/fc-go-sdk/.travis.yml, vendor/github.com/aliyun/fc-go-sdk/README.md, vendor/github.com/aliyun/fc-go-sdk/async_config.go, vendor/github.com/aliyun/fc-go-sdk/client.go, vendor/github.com/aliyun/fc-go-sdk/const.go, vendor/github.com/aliyun/fc-go-sdk/function.go, vendor/github.com/aliyun/fc-go-sdk/glide.lock, vendor/github.com/aliyun/fc-go-sdk/glide.yaml, vendor/github.com/aliyun/fc-go-sdk/layers.go, vendor/github.com/aliyun/fc-go-sdk/service.go, vendor/github.com/aliyun/fc-go-sdk/setup.sh, vendor/github.com/aliyun/fc-go-sdk/stateful_async_invocation.go, vendor/modules.txt, website/docs/r/fc_function_async_invoke_config.html.markdown
resource/alicloud_fc_function_async_invoke_config:add field statefulInvocation and update docs
=> resource/alicloud_fc_function_async_invoke_config:add field statefulInvocation and update docs

alicloud/data_source_alicloud_ram_roles.go, alicloud/data_source_alicloud_sae_applications.go, alicloud/data_source_alicloud_sae_applications_test.go, alicloud/resource_alicloud_ecs_network_interface_permission.go, alicloud/resource_alicloud_ess_suspend_process.go, alicloud/resource_alicloud_ons_topic_test.go, alicloud/resource_alicloud_privatelink_vpc_endpoint_connection_test.go, alicloud/resource_alicloud_privatelink_vpc_endpoint_service_resource_test.go, alicloud/resource_alicloud_sae_application.go, alicloud/resource_alicloud_sae_application_test.go, alicloud/service_alicloud_sae.go, website/docs/d/sae_applications.html.markdown, website/docs/r/sae_application.html.markdown
resource/alicloud_sae_application: Add support for new parameter tags.
=> resource/alicloud_sae_application: Add support for new parameter tags.

alicloud/data_source_alicloud_ram_roles.go, alicloud/resource_alicloud_ecs_network_interface_permission.go, alicloud/resource_alicloud_ess_suspend_process.go, alicloud/resource_alicloud_ons_topic_test.go, alicloud/resource_alicloud_privatelink_vpc_endpoint_connection_test.go, alicloud/resource_alicloud_privatelink_vpc_endpoint_service_resource_test.go, alicloud/resource_alicloud_slb_backend_server.go, website/docs/r/slb_backend_server.html.markdown
resource/alicloud_slb_backend_server: Fix bugs that do not carry serverIp when updating.
=> resource/alicloud_slb_backend_server: Fix bugs that do not carry serverIp when updating.

alicloud/data_source_alicloud_ga_accelerator_spare_ip_attachments.go, alicloud/data_source_alicloud_ga_accelerator_spare_ip_attachments_test.go, alicloud/provider.go, alicloud/resource_alicloud_ga_accelerator_spare_ip_attachment.go, alicloud/resource_alicloud_ga_accelerator_spare_ip_attachment_test.go, alicloud/resource_alicloud_quick_bi_user_test.go, alicloud/resource_alicloud_quotas_quota_alarm_test.go, alicloud/resource_alicloud_quotas_quota_application_test.go, alicloud/resource_alicloud_rdc_organization_test.go, alicloud/resource_alicloud_rds_parameter_group_test.go, alicloud/resource_alicloud_resource_manager_account_test.go, alicloud/service_alicloud_ga.go, website/alicloud.erb, website/docs/d/ga_accelerator_spare_ip_attachments.html.markdown, website/docs/r/ga_accelerator_spare_ip_attachment.html.markdown
New Resource `alicloud_ga_accelerator_spare_ip_attachment`;
New Datasource `alicloud_ga_accelerator_spare_ip_attachments`;
=> New Resource `alicloud_ga_accelerator_spare_ip_attachment`; New Datasource `alicloud_ga_accelerator_spare_ip_attachments`;

alicloud/resource_alicloud_sae_application.go, alicloud/resource_alicloud_sae_application_scaling_rule.go, website/docs/r/sae_application_scaling_rule.html.markdown
resource/alicloud_sae_application_scaling_rule: Fix `scaling_rule_timer.schedules` have default values.
=> resource/alicloud_sae_application_scaling_rule: Fix `scaling_rule_timer.schedules` have default values.

alicloud/resource_alicloud_cen_route_map.go, alicloud/resource_alicloud_cen_route_map_test.go, website/docs/r/cen_route_map.html.markdown
resource/alicloud_cen_route_map: Add support for new parameter transit_router_route_table_id.
=> resource/alicloud_cen_route_map: Add support for new parameter transit_router_route_table_id.

website/docs/r/cs_kubernetes_node_pool.html.markdown
resource/alicloud_cs_kubernetes_node_pool:update nodepool document
=> resource/alicloud_cs_kubernetes_node_pool:update nodepool document

alicloud/data_source_alicloud_ecs_invocations.go, alicloud/data_source_alicloud_ecs_invocations_test.go, alicloud/provider.go, alicloud/resource_alicloud_ecs_invocation.go, alicloud/resource_alicloud_ecs_invocation_test.go, alicloud/service_alicloud_ecs.go, website/alicloud.erb, website/docs/d/ecs_invocations.html.markdown, website/docs/r/ecs_invocation.html.markdown
New Resource `alicloud_ecs_invocation`;
New Datasource `alicloud_ecs_invocations`;
=> New Resource `alicloud_ecs_invocation`; New Datasource `alicloud_ecs_invocations`;

alicloud/data_source_alicloud_cen_transit_router_vpc_attachments.go, alicloud/data_source_alicloud_cen_transit_router_vpc_attachments_test.go, alicloud/resource_alicloud_brain_industrial_pid_organization_test.go, alicloud/resource_alicloud_brain_industrial_pid_project_test.go, alicloud/resource_alicloud_cassandra_backup_plan_test.go, alicloud/resource_alicloud_cen_transit_router_vpc_attachment.go, alicloud/resource_alicloud_cen_transit_router_vpc_attachment_test.go, alicloud/resource_alicloud_resource_manager_role_test.go, alicloud/resource_alicloud_resource_manager_shared_resource_test.go, website/docs/d/cen_transit_router_vpc_attachments.html.markdown, website/docs/r/cen_transit_router_vpc_attachment.html.markdown
resource/alicloud_cen_transit_router_vpc_attachment: Add support for new parameter `payment_type`.
=> resource/alicloud_cen_transit_router_vpc_attachment: Add support for new parameter `payment_type`.

alicloud/connectivity/client.go, alicloud/connectivity/config.go, alicloud/data_source_alicloud_smartag_flow_logs.go, alicloud/data_source_alicloud_smartag_flow_logs_test.go, alicloud/provider.go, alicloud/resource_alicloud_smartag_flow_log.go, alicloud/resource_alicloud_smartag_flow_log_test.go, alicloud/service_alicloud_sag.go, website/alicloud.erb, website/docs/d/smartag_flow_logs.html.markdown, website/docs/r/smartag_flow_log.html.markdown
New Resource `alicloud_smartag_flow_log`;
New Datasource `alicloud_smartag_flow_logs`;
=> New Resource `alicloud_smartag_flow_log`; New Datasource `alicloud_smartag_flow_logs`;

alicloud/data_source_alicloud_ecd_snapshots.go, alicloud/data_source_alicloud_ecd_snapshots_test.go, alicloud/provider.go, alicloud/resource_alicloud_ecd_snapshot.go, alicloud/resource_alicloud_ecd_snapshot_test.go, alicloud/service_alicloud_ecd.go, website/alicloud.erb, website/docs/d/ecd_snapshots.html.markdown, website/docs/r/ecd_snapshot.html.markdown
New Datasource `alicloud_ecd_snapshots`
=> New Resource `alicloud_ecd_snapshot` New Datasource `alicloud_ecd_snapshots`

alicloud/common.go, alicloud/resource_alicloud_bastionhost_instance.go, alicloud/resource_alicloud_bastionhost_instance_test.go, alicloud/service_alicloud_yundun_bastionhost.go, website/docs/r/alb_listener.html.markdown, website/docs/r/bastionhost_instance.html.markdown
resource/alicloud_bastionhost_instance: Support for new parameters `ad_auth_server` and `ldap_auth_server`.
=> resource/alicloud_bastionhost_instance: Support for new parameters `ad_auth_server` and `ldap_auth_server`.

alicloud/resource_alicloud_msc_sub_contact.go
resource/alicloud_msc_sub_contact: fix email regex.
=> resource/alicloud_msc_sub_contact: fix email regex.

alicloud/resource_alicloud_ecd_user.go
resource/alicloud_ecd_user: Fix error setting default password
=> resource/alicloud_ecd_user: Fix error setting default password

alicloud/resource_alicloud_click_house_account.go, alicloud/resource_alicloud_click_house_account_test.go, website/docs/r/click_house_account.html.markdown
resource/alicloud_click_house_account: Fix the value range of the `dml_authority` attribute.
=> resource/alicloud_click_house_account: Fix the value range of the `dml_authority` attribute.

alicloud/resource_alicloud_ga_bandwidth_package.go, alicloud/service_alicloud_ga.go, website/docs/r/ga_bandwidth_package.html.markdown
resource/alicloud_ga_bandwidth_package: Add support for new parameter `auto_renew`, `auto_renew_duration` and `renewal_status`.
=> resource/alicloud_ga_bandwidth_package: Add support for new parameter `auto_renew_duration` and `renewal_status`.

alicloud/resource_alicloud_slb_listener.go, website/docs/r/slb_listener.html.markdown
resource/alicloud_slb_listener: Fix errors bandwidth missing Computed
=> resource/alicloud_slb_listener: Fix errors bandwidth missing Computed

alicloud/data_source_alicloud_smartag_flow_logs_test.go, alicloud/resource_alicloud_smartag_flow_log_test.go
resource/alicloud_smartag_flow_log_test: fix ci test error.
=> resource/alicloud_smartag_flow_log_test: fix ci test error.

alicloud/data_source_alicloud_cs_kubernetes_metadata_test.go, alicloud/data_source_alicloud_cs_kubernetes_metadatda.go, alicloud/provider.go, website/alicloud.erb, website/docs/d/cs_kubernetes_version.html.markdown
New Data Source: data_source_alicloud_cs_kubernetes_metadatda
=> New Data Source: data_source_alicloud_cs_kubernetes_metadatda

alicloud/resource_alicloud_polardb_backup_policy.go, alicloud/resource_alicloud_polardb_backup_policy_test.go, alicloud/resource_alicloud_polardb_cluster.go, alicloud/service_alicloud_polardb.go, website/docs/r/polardb_backup_policy.html.markdown, website/docs/r/polardb_cluster.html.markdown
The retention policy for the backup sets when you delete the cluster
=> resource/alicloud_polardb_backup_policy: Adds new attribute backup_retention_policy_on_cluster_deletion

alicloud/data_source_alicloud_ecd_desktop_types.go, alicloud/data_source_alicloud_ecd_desktop_types_test.go, alicloud/provider.go, website/alicloud.erb, website/docs/d/ecd_desktop_types.html.markdown
New Datasource `alicloud_ecd_desktop_types`;
=> New Datasource `alicloud_ecd_desktop_types`;

alicloud/data_source_alicloud_ons_topics_test.go, alicloud/resource_alicloud_ons_topic.go, alicloud/resource_alicloud_ons_topic_test.go, website/docs/r/ons_topic.html.markdown
resource/alicloud_ons_topic: `perm` attribute no longer supports updates.
=> resource/alicloud_ons_topic: `perm` attribute no longer supports updates.

alicloud/resource_alicloud_eci_container_group.go, alicloud/resource_alicloud_eci_container_group_test.go, website/docs/r/eci_container_group.html.markdown
resource_alicloud_eci_container_group: Add support for new parameter `auto_create_eip`, `eip_bandwidth`, `eip_instance_id`;
=> resource_alicloud_eci_container_group: Add support for new parameter `auto_create_eip`, `eip_bandwidth`, `eip_instance_id`;

alicloud/data_source_alicloud_config_deliveries.go, alicloud/data_source_alicloud_config_deliveries_test.go, alicloud/provider.go, alicloud/resource_alicloud_config_delivery.go, alicloud/resource_alicloud_config_delivery_test.go, alicloud/service_alicloud_config.go, website/alicloud.erb, website/docs/d/config_deliveries.html.markdown, website/docs/r/config_delivery.html.markdown, website/docs/r/config_delivery_channel.html.markdown
New Resource `alicloud_config_delivery`;
New Datasource `alicloud_config_deliveries`;
=> New Resource `alicloud_config_delivery`;New Datasource `alicloud_config_deliveries`;

alicloud/resource_alicloud_scdn_domain.go, alicloud/resource_alicloud_scdn_domain_test.go, website/docs/r/scdn_domain.html.markdown
resource/alicloud_scdn_domain: Field `biz_name` has been deprecated from provider.
=> resource/alicloud_scdn_domain: Field `biz_name` has been deprecated from provider.

alicloud/data_source_alicloud_cms_namespaces.go, alicloud/data_source_alicloud_cms_namespaces_test.go, alicloud/provider.go, alicloud/resource_alicloud_cms_namespace.go, alicloud/resource_alicloud_cms_namespace_test.go, alicloud/service_alicloud_cms.go, website/alicloud.erb, website/docs/d/cms_namespaces.html.markdown, website/docs/r/cms_namespace.html.markdown
New Resource `alicloud_cms_namespace`;
New Datasource `alicloud_cms_namespaces`;
=> New Resource `alicloud_cms_namespace`; New Datasource `alicloud_cms_namespaces`;

alicloud/resource_alicloud_mongodb_sharding_network_private_address.go
…y stragety for error code 'OperationDenied.DBInstanceStatus'.
=> resource/alicloud_mongodb_sharding_network_private_address:Added retry stragety for error code 'OperationDenied.DBInstanceStatus'.

alicloud/connectivity/regions.go, alicloud/resource_alicloud_graph_database_db_instance.go, alicloud/resource_alicloud_graph_database_db_instance_test.go, website/docs/r/graph_database_db_instance.html.markdown
resource/alicloud_graph_database_db_instance: Add support for new parameter `vpc_id`, `vswitch_id` and `zone_id`.
=> resource/alicloud_graph_database_db_instance: Add support for new parameter `vpc_id`, `vswitch_id` and `zone_id`.

alicloud/data_source_alicloud_cms_sls_groups.go, alicloud/data_source_alicloud_cms_sls_groups_test.go, alicloud/provider.go, alicloud/resource_alicloud_cms_sls_group.go, alicloud/resource_alicloud_cms_sls_group_test.go, alicloud/service_alicloud_cms.go, website/alicloud.erb, website/docs/d/cms_sls_groups.html.markdown, website/docs/r/cms_sls_group.html.markdown
New Resource `alicloud_cms_sls_group`;
New Datasource `alicloud_cms_sls_groups`;
=> New Resource `alicloud_cms_sls_group`;New Datasource `alicloud_cms_sls_groups`;

alicloud/data_source_alicloud_config_aggregate_deliveries.go, alicloud/data_source_alicloud_config_aggregate_deliveries_test.go, alicloud/provider.go, alicloud/resource_alicloud_config_aggregate_delivery.go, alicloud/resource_alicloud_config_aggregate_delivery_test.go, alicloud/service_alicloud_config.go, website/alicloud.erb, website/docs/d/config_aggregate_deliveries.html.markdown, website/docs/r/config_aggregate_delivery.html.markdown
New Resource `alicloud_config_aggregate_delivery`;
New Datasource `alicloud_config_aggregate_deliveries`;
=> New Resource `alicloud_config_aggregate_delivery`; New Datasource `alicloud_config_aggregate_deliveries`;

alicloud/resource_alicloud_vpn_connection.go
resource/alicloud_vpn_connection: Fix attribute `ike_config` update error.
=> resource/alicloud_vpn_connection: Fix attribute `ike_config` update error.

alicloud/data_source_alicloud_emr_main_versions.go, alicloud/resource_alicloud_emr_cluster.go, alicloud/resource_alicloud_emr_cluster_test.go, website/docs/r/emr_cluster.html.markdown
=> resource/alicloud_emr_cluster: support bootstrap action specify execution strategy

alicloud/resource_alicloud_mse_cluster.go, alicloud/resource_alicloud_mse_cluster_test.go, website/docs/r/mse_cluster.html.markdown
resource_alicloud_mse_cluster: Modify the parameter `pub_network_flow` as required; Adds DiffSuppressFunc for `acl_entry_list`.
=> resource_alicloud_mse_cluster: Modify the parameter `pub_network_flow` as required; Adds DiffSuppressFunc for 'acl_entry_list'.

alicloud/resource_alicloud_hbr_vault.go, alicloud/resource_alicloud_hbr_vault_test.go, website/docs/r/hbr_vault.html.markdown
… `encrypt_type` and `kms_key_id`
=> resource/resource_alicloud_hbr_vault: Added support for new parameter `encrypt_type` and `kms_key_id`

website/docs/r/cs_kubernetes_node_pool.html.markdown
=> doc/alicloud_cs_kubernetes_node_pool: fix import doc error

alicloud/validators.go, alicloud/validators_test.go
resource/alicloud_ots_instance: fix validate ots instance name
相关测试：
=== RUN   TestValidateOTSInstanceName
--- PASS: TestValidateOTSInstanceName (0.00s)
=> resource/alicloud_ots_instance: fix validate ots instance name

alicloud/connectivity/client.go, alicloud/connectivity/config.go, alicloud/connectivity/regions.go, alicloud/data_source_alicloud_ehpc_clusters.go, alicloud/data_source_alicloud_ehpc_clusters_test.go, alicloud/provider.go, alicloud/resource_alicloud_ehpc_cluster.go, alicloud/resource_alicloud_ehpc_cluster_test.go, alicloud/service_alicloud_ehpc.go, website/alicloud.erb, website/docs/d/ehpc_clusters.html.markdown, website/docs/r/ehpc_cluster.html.markdown
New Resource `alicloud_ehpc_cluster`;
New Datasource `alicloud_ehpc_clusters`;
=> New Resource `alicloud_ehpc_cluster`; New Datasource `alicloud_ehpc_clusters`;

alicloud/data_source_alicloud_cen_traffic_marking_policies.go, alicloud/data_source_alicloud_cen_traffic_marking_policies_test.go, alicloud/provider.go, alicloud/resource_alicloud_cen_traffic_marking_policy.go, alicloud/resource_alicloud_cen_traffic_marking_policy_test.go, alicloud/service_alicloud_cbn.go, website/alicloud.erb, website/docs/d/cen_traffic_marking_policies.html.markdown, website/docs/r/cen_traffic_marking_policy.html.markdown
New Resource `alicloud_cen_traffic_marking_policy`;
New Datasource `alicloud_cen_traffic_marking_policies`;
=> New Resource `alicloud_cen_traffic_marking_policy`;New Datasource `alicloud_cen_traffic_marking_policies`;

alicloud/common.go, alicloud/data_source_alicloud_cdn_blocked_regions.go, alicloud/provider.go, alicloud/resource_alicloud_cen_traffic_marking_policy.go, alicloud/resource_alicloud_ecs_disk.go, alicloud/resource_alicloud_ecs_instance_set.go, alicloud/resource_alicloud_ecs_instance_set_test.go, alicloud/resource_alicloud_ram_role_policy_attachment.go, alicloud/service_alicloud_ecs.go, scripts/schema_test.go, website/alicloud.erb, website/docs/r/ecs_disk.html.markdown, website/docs/r/ecs_instance_set.html.markdown
New Resource `alicloud_ecs_instance_set`
=> New Resource `alicloud_ecs_instance_set`

alicloud/data_source_alicloud_cs_kubernetes_addon_metadata_test.go, alicloud/data_source_alicloud_cs_kubernetes_version_test.go, alicloud/data_source_alicloud_cs_serverless_kubernetes_clusters_test.go, alicloud/resource_alicloud_cs_autoscaling_config_test.go, alicloud/resource_alicloud_cs_kubernetes_addon_test.go, alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go, alicloud/resource_alicloud_cs_kubernetes_permissions_test.go, alicloud/resource_alicloud_cs_kubernetes_test.go, alicloud/resource_alicloud_cs_managed_kubernetes_test.go
本地测试all pass
下周会跟进ci账号的测试情况，再做修改
增加了一些test case
=> testcase: fixes the kubernetes resource's testcase error

alicloud/data_source_alicloud_ecd_ram_directories.go, alicloud/data_source_alicloud_ecd_ram_directories_test.go, alicloud/data_source_alicloud_ecd_zones.go, alicloud/data_source_alicloud_ecd_zones_test.go, alicloud/provider.go, alicloud/resource_alicloud_ecd_ram_directory.go, alicloud/resource_alicloud_ecd_ram_directory_test.go, alicloud/service_alicloud_ecd.go, website/alicloud.erb, website/docs/d/ecd_ram_directories.html.markdown, website/docs/d/ecd_zones.html.markdown, website/docs/r/ecd_ram_directory.html.markdown
New Resource `alicloud_ecd_ram_directory`;
New Datasource `alicloud_ecd_ram_directories`;
New Datasource `alicloud_ecd_zones`;
=> New Resource `alicloud_ecd_ram_directory`; New Datasource `alicloud_ecd_ram_directories`; New Datasource `alicloud_ecd_zones`;

alicloud/diff_suppress_funcs.go, alicloud/resource_alicloud_security_group_rule.go, alicloud/resource_alicloud_security_group_rule_test.go, alicloud/service_alicloud_ecs.go, website/docs/r/security_group_rule.html.markdown
resource/alicloud_security_group_rule: Add support for new parameter `ipv6_cidr_ip`.
=> resource/alicloud_security_group_rule: Add support for new parameter `ipv6_cidr_ip`.

alicloud/data_source_alicloud_alikafka_instances.go
=> datasource/alicloud_alikafka_instances: Fixes the paid_type incorrect value when it is PrePaid

alicloud/resource_alicloud_common_bandwidth_package.go, alicloud/resource_alicloud_common_bandwidth_package_test.go, alicloud/resource_alicloud_service_mesh_user_permission.go, alicloud/resource_alicloud_service_mesh_user_permission_test.go, website/docs/r/common_bandwidth_package.html.markdown
=> resource/alicloud_common_bandwidth_package: support for `PayByDominantTraffic`.

alicloud/data_source_alicloud_ecd_custom_properties.go, alicloud/data_source_alicloud_ecd_custom_properties_test.go, alicloud/provider.go, alicloud/resource_alicloud_ecd_custom_property.go, alicloud/resource_alicloud_ecd_custom_property_test.go, alicloud/service_alicloud_eds_user.go, website/alicloud.erb, website/docs/d/ecd_custom_properties.html.markdown, website/docs/r/ecd_custom_property.html.markdown
New Resource `alicloud_ecd_custom_property`;
New Datasource `alicloud_ecd_custom_properties`;
=> New Resource `alicloud_ecd_custom_property`; New Datasource `alicloud_ecd_custom_properties`;

alicloud/resource_alicloud_log_alert.go, alicloud/resource_alicloud_log_alert_test.go, website/docs/r/log_alert.html.markdown
support more schedule for alert with `schedule`
=> resource/resource_alicloud_log_alert: Replace `schedule_type`, `schedule_intervsl` with `schedule`

alicloud/data_source_alicloud_ecd_ad_connector_office_sites.go, alicloud/data_source_alicloud_ecd_ad_connector_office_sites_test.go, alicloud/provider.go, alicloud/resource_alicloud_db_instance_test.go, alicloud/resource_alicloud_ecd_ad_connector_office_site.go, alicloud/resource_alicloud_ecd_ad_connector_office_site_test.go, alicloud/service_alicloud_ecd.go, website/alicloud.erb, website/docs/d/ecd_ad_connector_office_sites.html.markdown, website/docs/r/ecd_ad_connector_directory.html.markdown, website/docs/r/ecd_ad_connector_office_site.html.markdown
New Resource `alicloud_ecd_ad_connector_office_site`;
New Datasource `alicloud_ecd_ad_connector_office_sites`;
=> New Resource `alicloud_ecd_ad_connector_office_site`;New Datasource `alicloud_ecd_ad_connector_office_sites`;

alicloud/resource_alicloud_cs_kubernetes_node_pool.go, alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go
Fix #5145 .
And add testcase for AliyunLinux3.
=> resource/alicloud_cs_node_pool: fix image_type export error

alicloud/resource_alicloud_eci_container_group.go, alicloud/resource_alicloud_eci_container_group_test.go, website/docs/r/eci_container_group.html.markdown
resource/alicloud_eci_container_group: Delete default values for `memory` and `cpu`.
=> resource/alicloud_eci_container_group: Delete default values for `memory` and `cpu`.

alicloud/resource_alicloud_mse_cluster.go, alicloud/resource_alicloud_mse_cluster_test.go, website/docs/r/mse_cluster.html.markdown
resource/alicloud_mse_cluster: Add support for new parameter `mse_version`.
=> resource/alicloud_mse_cluster: Add support for new parameter `mse_version`.

alicloud/data_source_alicloud_cms_hybrid_monitor_datas.go, alicloud/data_source_alicloud_cms_hybrid_monitor_datas_test.go, alicloud/provider.go, website/alicloud.erb, website/docs/d/cms_hybrid_monitor_datas.html.markdown
New Datasource `alicloud_cms_hybrid_monitor_datas`;
=> New Datasource `alicloud_cms_hybrid_monitor_datas`;

alicloud/common.go, alicloud/resource_alicloud_cs_kubernetes.go, alicloud/resource_alicloud_cs_kubernetes_node_pool.go, alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go, alicloud/resource_alicloud_cs_managed_kubernetes.go, go.mod, go.sum, scripts/schema_test.go, vendor/github.com/denverdino/aliyungo/cs/kubernets_cluster.go, vendor/modules.txt, website/docs/r/cs_edge_kubernetes.html.markdown, website/docs/r/cs_kubernetes.html.markdown, website/docs/r/cs_kubernetes_node_pool.html.markdown, website/docs/r/cs_managed_kubernetes.html.markdown, website/docs/r/cs_serverless_kubernetes.html.markdown
1. resource/alicloud_cs_managed_kubernetes: Cluster parameter adjustment, discarding node-related parameters.
2. resource/alicloud_cs_kubernetes_node_pool: Add rds whitelist control.
=> resource/alicloud_cs_managed_kubernetes: Cluster parameter adjustment, discarding node-related parameters

alicloud/service_alicloud_ecs.go
=> resource/alicloud_instance: Fixes the describing system disk failed when setting the resource_group_id

alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_cluster_test.go, website/docs/r/polardb_cluster.html.markdown
resource/alicloud_polardb_cluster: Adds new attribute sub_category
=> resource/alicloud_polardb_cluster: Adds new attribute sub_category

alicloud/resource_alicloud_cs_kubernetes.go, alicloud/resource_alicloud_cs_kubernetes_node_pool.go, go.mod, go.sum, vendor/github.com/denverdino/aliyungo/cs/node_pool.go, vendor/modules.txt, website/docs/r/cs_kubernetes_node_pool.html.markdown
=> resource/alicloud_cs_kubernetes_node_pool: update sdk and optimize resource update logic

alicloud/connectivity/regions.go, alicloud/data_source_alicloud_cloud_firewall_address_books.go, alicloud/data_source_alicloud_cloud_firewall_address_books_test.go, alicloud/provider.go, alicloud/resource_alicloud_cloud_firewall_address_book.go, alicloud/resource_alicloud_cloud_firewall_address_book_test.go, alicloud/service_alicloud_cloudfw.go, alicloud/service_alicloud_hitsdb.go, website/alicloud.erb, website/docs/d/cloud_firewall_address_books.html.markdown, website/docs/r/cloud_firewall_address_book.html.markdown
New DataSource `alicloud_cloud_firewall_address_books`
=> New Resource `alicloud_cloud_firewall_address_book` New DataSource `alicloud_cloud_firewall_address_books`

alicloud/resource_alicloud_actiontrail_trail.go, website/docs/r/actiontrail_trail.html.markdown
resource/alicloud_actiontrail_trail: Remove restrictions on `trail_region` attributes, removes the default value and adds computed
=> resource/alicloud_actiontrail_trail: Remove restrictions on `trail_region` attributes, removes the default value and adds computed

alicloud/common.go, alicloud/connectivity/client.go, alicloud/connectivity/config.go, alicloud/connectivity/regions.go, alicloud/provider.go, alicloud/resource_alicloud_sms_short_url.go, alicloud/resource_alicloud_sms_short_url_test.go, alicloud/service_alicloud_dysmsapi.go, website/alicloud.erb, website/docs/r/sms_short_url.html.markdown
New Resource `alicloud_sms_short_url`;
=> New Resource `alicloud_sms_short_url`;

alicloud/data_source_alicloud_cs_managed_kubernetes_clusters.go, alicloud/data_source_alicloud_hbr_hana_instances.go, alicloud/data_source_alicloud_hbr_hana_instances_test.go, alicloud/provider.go, alicloud/resource_alicloud_ehpc_cluster_test.go, alicloud/resource_alicloud_hbr_hana_instance.go, alicloud/resource_alicloud_hbr_hana_instance_test.go, alicloud/service_alicloud_hbr.go, website/alicloud.erb, website/docs/d/hbr_hana_instances.html.markdown, website/docs/r/hbr_hana_instance.html.markdown
New Resource `alicloud_hbr_hana_instance`;
New Datasource `alicloud_hbr_hana_instances`;
=> New Resource `alicloud_hbr_hana_instance`;New Datasource `alicloud_hbr_hana_instances`;

alicloud/resource_alicloud_adb_db_cluster.go, alicloud/resource_alicloud_adb_db_cluster_test.go, website/docs/r/adb_db_cluster.html.markdown
resource_alicloud_adb_db_cluster: Support for new parameters `vpc_id`, Optimize `elastic_io_resource` attribute configuration logic.
=> resource_alicloud_adb_db_cluster: Support for new parameters `vpc_id`, Optimize `elastic_io_resource` attribute configuration logic.

alicloud/connectivity/regions.go, alicloud/data_source_alicloud_cms_hybrid_monitor_sls_tasks.go, alicloud/data_source_alicloud_cms_hybrid_monitor_sls_tasks_test.go, alicloud/provider.go, alicloud/resource_alicloud_cms_hybrid_monitor_sls_task.go, alicloud/resource_alicloud_cms_hybrid_monitor_sls_task_test.go, alicloud/service_alicloud_cms.go, website/alicloud.erb, website/docs/d/cms_hybrid_monitor_sls_tasks.html.markdown, website/docs/r/cms_hybrid_monitor_sls_task.html.markdown
New Resource `alicloud_cms_hybrid_monitor_sls_task`;
New Datasource `alicloud_cms_hybrid_monitor_sls_tasks`;
=> New Resource `alicloud_cms_hybrid_monitor_sls_task`; New Datasource `alicloud_cms_hybrid_monitor_sls_tasks`;

alicloud/resource_alicloud_alb_rule.go, alicloud/resource_alicloud_alb_rule_test.go, alicloud/resource_alicloud_lindorm_instance_test.go, alicloud/resource_alicloud_sms_short_url.go, website/docs/r/alb_rule.html.markdown
resource/alicloud_alb_rule: support for `server_group_sticky_session`
=> resource/alicloud_alb_rule: support for `server_group_sticky_session`

alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_cluster_test.go, alicloud/service_alicloud_polardb.go, website/docs/r/polardb_cluster.html.markdown
resource/alicloud_polardb_cluster: Adds new attribute creation_category and creation_option
=> resource/alicloud_polardb_cluster: Adds new attribute creation_category and creation_option

alicloud/data_source_alicloud_hbr_hana_backup_plans.go, alicloud/data_source_alicloud_hbr_hana_backup_plans_test.go, alicloud/provider.go, alicloud/resource_alicloud_hbr_hana_backup_plan.go, alicloud/resource_alicloud_hbr_hana_backup_plan_test.go, alicloud/service_alicloud_hbr.go, website/alicloud.erb, website/docs/d/hbr_hana_backup_plans.html.markdown, website/docs/r/hbr_hana_backup_plan.html.markdown
New Resource `alicloud_hbr_hana_backup_plan`;
New Datasource `alicloud_hbr_hana_backup_plans`;
=> New Resource `alicloud_hbr_hana_backup_plan`; New Datasource `alicloud_hbr_hana_backup_plans`;

alicloud/common.go, alicloud/data_source_alicloud_cms_hybrid_monitor_fc_tasks.go, alicloud/data_source_alicloud_cms_hybrid_monitor_fc_tasks_test.go, alicloud/provider.go, alicloud/resource_alicloud_cms_hybrid_monitor_fc_task.go, alicloud/resource_alicloud_cms_hybrid_monitor_fc_task_test.go, alicloud/service_alicloud_cms.go, website/alicloud.erb, website/docs/d/cms_hybrid_monitor_fc_tasks.html.markdown, website/docs/r/cms_hybrid_monitor_fc_task.html.markdown
New Resource `alicloud_cms_hybrid_monitor_fc_task`;
New Datasource `alicloud_cms_hybrid_monitor_fc_tasks`;
=> New Resource `alicloud_cms_hybrid_monitor_fc_task`; New Datasource `alicloud_cms_hybrid_monitor_fc_tasks`;

website/docs/d/cms_hybrid_monitor_datas.html.markdown
docs/alicloud_cms_hybrid_monitor_datas: Optimize document format.
=> docs/alicloud_cms_hybrid_monitor_datas: Optimize document format.

website/docs/r/ecs_activation.html.markdown
docs/alicloud_ecs_activation: Optimize document format.
=> docs/alicloud_ecs_activation: Optimize document format.

alicloud/resource_alicloud_log_store.go, go.mod, go.sum, website/docs/r/log_store.html.markdown
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudLogStore_basic -timeout=300m
=== RUN   TestAccAlicloudLogStore_basic
--- PASS: TestAccAlicloudLogStore_basic (82.76s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  82.864s
=> `resource/resource_alicloud_log_store`: support metric store

alicloud/resource_alicloud_cms_alarm.go, alicloud/resource_alicloud_cms_alarm_test.go, website/docs/r/cms_alarm.html.markdown
resource_alicloud_cms_alarm: Adds new attribute `prometheus`.
=> resource_alicloud_cms_alarm: Adds new attribute `prometheus`.

alicloud/resource_alicloud_cms_alarm.go, website/docs/r/cms_alarm.html.markdown
=> resource/alicloud_cms_alarm: Removes the useless error and improves its docs

alicloud/resource_alicloud_direct_mail_receivers_test.go, alicloud/resource_alicloud_direct_mail_tag_test.go, alicloud/resource_alicloud_vpc_nat_ip.go, website/docs/r/vpc_nat_ip.html.markdown
resource/alicloud_vpc_nat_ip: Optimizing attribute definition
=> resource/alicloud_vpc_nat_ip: Optimizing attribute definition

alicloud/resource_alicloud_adb_db_cluster.go, ci/pipeline.yml
=> resource/alicloud_adb_db_cluster: Improves its waiting time after invoking the create api

website/docs/r/route_entry.html.markdown
ref: https://www.alibabacloud.com/help/en/virtual-private-cloud/latest/createrouteentry
=> doc/route_entry: add VpcPeer to acceptable values for nexthop_type

alicloud/data_source_alicloud_hbr_backup_jobs.go, alicloud/data_source_alicloud_hbr_backup_jobs_test.go, alicloud/data_source_alicloud_hbr_ecs_backup_clients_test.go, alicloud/data_source_alicloud_hbr_ecs_backup_plans_test.go, alicloud/data_source_alicloud_hbr_hana_instances_test.go, alicloud/data_source_alicloud_hbr_ots_snapshots_test.go, alicloud/data_source_alicloud_hbr_restore_jobs_test.go, alicloud/data_source_alicloud_hbr_server_backup_plans_test.go, alicloud/data_source_alicloud_hbr_snapshots_test.go, alicloud/resource_alicloud_direct_mail_receivers_test.go, alicloud/resource_alicloud_direct_mail_tag_test.go
testcase: fix hbr test case errors.
=> testcase: fix hbr test case errors.

alicloud/resource_alicloud_cms_alarm.go, alicloud/resource_alicloud_cms_alarm_test.go, website/docs/r/cms_alarm.html.markdown
resource_alicloud_cms_alarm: Removed the field 'prometheus' forceNew and supports modifying it online.
=> resource_alicloud_cms_alarm: Removed the field 'prometheus' forceNew and supports modifying it online.

alicloud/connectivity/client.go, alicloud/provider.go, alicloud/resource_alicloud_direct_mail_receivers_test.go, alicloud/resource_alicloud_direct_mail_tag_test.go, alicloud/resource_alicloud_fc_layer_version.go, alicloud/resource_alicloud_fc_layer_version_test.go, alicloud/service_alicloud_fc_open.go, go.sum, website/alicloud.erb, website/docs/r/fc_layer_version.html.markdown
=> New Resource `alicloud_fc_layer_version`

alicloud/resource_alicloud_cms_alarm.go, alicloud/resource_alicloud_cms_alarm_test.go, website/docs/r/cms_alarm.html.markdown
resource_alicloud_cms_alarm: Adds new attribute `tags`.
=> resource_alicloud_cms_alarm: Adds new attribute `tags`.

alicloud/connectivity/client.go, alicloud/connectivity/regions.go, alicloud/data_source_alicloud_ddosbgp_ips.go, alicloud/data_source_alicloud_ddosbgp_ips_test.go, alicloud/provider.go, alicloud/resource_alicloud_ddosbgp_ip.go, alicloud/resource_alicloud_ddosbgp_ip_test.go, alicloud/service_alicloud_ddosbgp.go, website/alicloud.erb, website/docs/d/ddosbgp_ips.html.markdown, website/docs/r/ddosbgp_ip.html.markdown
New Resource `alicloud_ddos_bgp_ip`;
New Datasource `alicloud_ddos_bgp_ips`;
=> New Resource `alicloud_ddos_bgp_ip`; New Datasource `alicloud_ddos_bgp_ips`;

alicloud/resource_alicloud_cs_kubernetes_node_pool.go, alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go, go.mod, go.sum, vendor/github.com/alibabacloud-go/cs-20151215/v3/client/client.go, vendor/github.com/alibabacloud-go/tea-utils/service/service.go, vendor/github.com/clbanning/mxj/v2/xml.go, vendor/github.com/denverdino/aliyungo/cs/node_pool.go, vendor/modules.txt, website/docs/r/cs_kubernetes_node_pool.html.markdown
=== RUN   TestAccAlicloudCSKubernetesNodePool_basic
--- PASS: TestAccAlicloudCSKubernetesNodePool_basic (768.87s)
=> resource/alicloud_cs_kubernetes_node_pool: support customized kubelet params

alicloud/resource_alicloud_ecs_disk.go, alicloud/resource_alicloud_ecs_disk_test.go
=> resource/alicloud_ecs_disk: Fixes the size diff bug when setting snapshot_id

alicloud/resource_alicloud_oos_execution.go, website/docs/r/oos_execution.html.markdown
resource/alicloud_oos_execution: Remove the status wait after the resource is created.
=> resource/alicloud_oos_execution: Remove the status wait after the resource is created.

alicloud/data_source_alicloud_resource_manager_delegated_administrators.go, alicloud/data_source_alicloud_resource_manager_delegated_administrators_test.go, alicloud/provider.go, alicloud/resource_alicloud_resource_manager_delegated_administrator.go, alicloud/resource_alicloud_resource_manager_delegated_administrator_test.go, alicloud/service_alicloud_resource_manager.go, website/alicloud.erb, website/docs/d/resource_manager_delegated_administrators.html.markdown, website/docs/r/resource_manager_delegated_administrator.html.markdown
New Resource `alicloud_resource_manager_delegated_administrator`;
New Datasource `alicloud_resource_manager_delegated_administrators`;
=> New Resource `alicloud_resource_manager_delegated_administrator`; New Datasource `alicloud_resource_manager_delegated_administrators`;

alicloud/data_source_alicloud_vpc_ipv4_gateways.go, alicloud/data_source_alicloud_vpc_ipv4_gateways_test.go, alicloud/provider.go, alicloud/resource_alicloud_vpc_ipv4_gateway.go, alicloud/resource_alicloud_vpc_ipv4_gateway_test.go, alicloud/service_alicloud_vpc.go, website/alicloud.erb, website/docs/d/vpc_ipv4_gateways.html.markdown, website/docs/r/vpc_ipv4_gateway.html.markdown
New Resource `alicloud_vpc_ipv4_gateway`;
New Datasource `alicloud_vpc_ipv4_gateways`;
=> New Resource `alicloud_vpc_ipv4_gateway`; New Datasource `alicloud_vpc_ipv4_gateways`;

alicloud/service_alicloud_ecs.go
resource/alicloud_instance: Fixed the issue of updating VSwitch timeout
=> resource/alicloud_instance: Fixed the issue of updating VSwitch timeout

alicloud/connectivity/client.go, alicloud/data_source_alicloud_api_gateway_backends.go, alicloud/data_source_alicloud_api_gateway_backends_test.go, alicloud/provider.go, alicloud/resource_alicloud_api_gateway_backend.go, alicloud/resource_alicloud_api_gateway_backend_test.go, alicloud/service_alicloud_api_gateway.go, website/alicloud.erb, website/docs/d/api_gateway_backends.html.markdown, website/docs/r/api_gateway_backend.html.markdown
datasouece/alicloud_api_gateway_backends
=> resource/alicloud_api_gateway_backend datasouece/alicloud_api_gateway_backends

alicloud/resource_alicloud_vpc_ipv4_gateway.go, alicloud/resource_alicloud_vpc_ipv4_gateway_test.go, alicloud/service_alicloud_vpc.go
resource/alicloud_vpc_ipv4_gateway: After creation and deletion, the new status waits for judgment.
=> resource/alicloud_vpc_ipv4_gateway: After creation and deletion, the new status waits for judgment.

alicloud/data_source_alicloud_polardb_global_database_networks.go, alicloud/data_source_alicloud_vpc_prefix_lists.go, alicloud/data_source_alicloud_vpc_prefix_lists_test.go, alicloud/provider.go, alicloud/resource_alicloud_polardb_global_database_network.go, alicloud/resource_alicloud_polardb_global_database_network_test.go, alicloud/resource_alicloud_vpc_prefix_list.go, alicloud/resource_alicloud_vpc_prefix_list_test.go, alicloud/service_alicloud_polardb.go, alicloud/service_alicloud_vpc.go, website/alicloud.erb, website/docs/d/eip_addresses.html.markdown, website/docs/d/vpc_prefix_lists.html.markdown, website/docs/r/vpc_prefix_list.html.markdown
New Resource `alicloud_vpc_prefix_list`; 
New Datasource `alicloud_vpc_prefix_lists`;
=> New Resource `alicloud_vpc_prefix_list`; New Datasource `alicloud_vpc_prefix_lists`;

website/docs/r/cms_namespace.html.markdown
doc/cms_namespace: fix example error.
=> doc/cms_namespace: fix example error.

alicloud/resource_alicloud_lindorm_instance.go
=> resource/lindorm_instace: Removes the useless updateing after creating a new resource

alicloud/resource_alicloud_ecs_instance_set.go, alicloud/resource_alicloud_ecs_instance_set_test.go
resource/alicloud_ecs_instance_set: Fix state wait logic error after creation, fix test case.
=> resource/alicloud_ecs_instance_set: Fix state wait logic error after creation, fix test case.

alicloud/resource_alicloud_cr_endpoint_acl_policy.go, alicloud/resource_alicloud_cr_endpoint_acl_policy_test.go
resource/alicloud_cr_endpoint_acl_policy: Add the second check of the request.
=> resource/alicloud_cr_endpoint_acl_policy: Add the second check of the request.

alicloud/data_source_alicloud_cms_event_rules.go, alicloud/resource_alicloud_cms_event_rule.go, alicloud/resource_alicloud_cms_event_rule_test.go, alicloud/resource_alicloud_lindorm_instance.go, website/docs/r/lindorm_instance.html.markdown
…_ssd_pro `, `local_hdd_pro` to field `disk_category`.
=> resource/alicloud_lindorm_instance: Add new enumeration values `local_ssd_pro `, `local_hdd_pro` to field `disk_category`.

alicloud/resource_alicloud_slb_load_balancer.go, website/docs/r/slb_load_balancer.html.markdown
=> resource/alicloud_slb_load_balancer: Enlarges the attribute bandwidth maximum value to 5120

alicloud/data_source_alicloud_ddosbgp_instances.go, alicloud/data_source_alicloud_ddosbgp_instances_test.go, alicloud/data_source_alicloud_polardb_global_database_networks.go, alicloud/resource_alicloud_ddosbgp_instance.go, alicloud/resource_alicloud_ddosbgp_instance_test.go, alicloud/resource_alicloud_polardb_global_database_network.go, alicloud/resource_alicloud_polardb_global_database_network_test.go, alicloud/service_alicloud_ddosbgp.go, alicloud/service_alicloud_polardb.go, website/docs/d/ddosbgp_instances.html.markdown, website/docs/r/ddosbgp_instance.html.markdown
resource/alicloud_ddosbgp_instance: Adds new attribute `normal_bandwidth`.
=> resource/alicloud_ddosbgp_instance: Adds new attribute `normal_bandwidth`, Remove Api of Destroyed Resources.

alicloud/connectivity/client.go, alicloud/connectivity/config.go, alicloud/provider.go, alicloud/resource_alicloud_lindorm_instance.go, website/docs/index.html.markdown
resource/alicloud_lindorm_instance: Set the user-defined retry time
=> resource/alicloud_lindorm_instance: Set the user-defined retry time

alicloud/service_alicloud_vpc.go
=> resource/alicloud_eip_association: Fixed problem with tag 'throttling.user'

alicloud/data_source_alicloud_cms_event_rules.go, alicloud/resource_alicloud_cms_event_rule.go, alicloud/resource_alicloud_cms_event_rule_test.go, alicloud/resource_alicloud_kms_key.go, alicloud/resource_alicloud_kms_key_test.go, alicloud/resource_alicloud_kms_secret.go, alicloud/resource_alicloud_kms_secret_test.go, website/docs/r/kms_key.html.markdown, website/docs/r/kms_secret.html.markdown
resource/alicloud_kms_secret: support for `dkms_instance_id`
=> resource/alicloud_kms_key: support for `dkms_instance_id` resource/alicloud_kms_secret: support for `dkms_instance_id`

alicloud/provider.go, alicloud/resource_alicloud_ddos_basic_defense_threshold.go, alicloud/resource_alicloud_ddos_basic_threshold.go, alicloud/resource_alicloud_ddos_basic_threshold_test.go, alicloud/service_alicloud_antiddos_public.go, website/alicloud.erb, website/docs/r/ddos_basic_threshold.html.markdown
New Resource `alicloud_ddos_basic_threshold`;
=> New Resource `alicloud_ddos_basic_threshold`;

alicloud/resource_alicloud_cs_kubernetes.go
worker_nodes和worker_number字段增强，适配无节点池老版本集群，增强默认节点池判断逻辑
=> resource/alicloud_cs_managed_kubernetes: field `worker_number` and `worker_nodes` enhancement for outdated version cluster

alicloud/connectivity/regions.go, alicloud/data_source_alicloud_cen_transit_router_vpn_attachments.go, alicloud/data_source_alicloud_cen_transit_router_vpn_attachments_test.go, alicloud/provider.go, alicloud/resource_alicloud_cen_transit_router_vpn_attachment.go, alicloud/resource_alicloud_cen_transit_router_vpn_attachment_test.go, alicloud/resource_alicloud_graph_database_db_instance_test.go, alicloud/resource_alicloud_rds_account_test.go, alicloud/resource_alicloud_ros_stack_group_test.go, alicloud/service_alicloud_cbn.go, website/alicloud.erb, website/docs/d/cen_transit_router_vpn_attachments.html.markdown, website/docs/r/cen_transit_router_vpn_attachment.html.markdown, website/docs/r/fc_service.html.markdown
New Resource `alicloud_cen_transit_router_vpn_attachment`;
New Datasource `alicloud_cen_transit_router_vpn_attachments`;
=> New Resource `alicloud_cen_transit_router_vpn_attachment`; New Datasource `alicloud_cen_transit_router_vpn_attachments`;

alicloud/data_source_alicloud_mse_clusters_test.go, alicloud/data_source_alicloud_mse_znodes_test.go, alicloud/resource_alicloud_ddos_basic_threshold.go, alicloud/resource_alicloud_mse_cluster.go, alicloud/resource_alicloud_mse_cluster_test.go, alicloud/resource_alicloud_mse_engine_namespace_test.go, alicloud/resource_alicloud_mse_znode_test.go, alicloud/resource_alicloud_polardb_parameter_group.go, alicloud/resource_alicloud_polardb_parameter_group_test.go, website/docs/r/mse_cluster.html.markdown
=> resource/alicloud_mse_cluster: Supports new attribute connection_type and request_pars

alicloud/data_source_alicloud_vpn_gateway_vco_routes.go, alicloud/data_source_alicloud_vpn_gateway_vco_routes_test.go, alicloud/provider.go, alicloud/resource_alicloud_vpn_gateway_vco_route.go, alicloud/resource_alicloud_vpn_gateway_vco_route_test.go, alicloud/service_alicloud_vpc.go, website/alicloud.erb, website/docs/d/vpn_gateway_vco_routes.html.markdown, website/docs/r/vpn_gateway_vco_route.html.markdown
New Resource `alicloud_vpn_gateway_vco_route`; 
New Datasource `alicloud_vpn_gateway_vco_routes`;
=> New Resource `alicloud_vpn_gateway_vco_route`; New Datasource `alicloud_vpn_gateway_vco_routes`;

alicloud/resource_alicloud_oss_bucket.go, alicloud/resource_alicloud_oss_bucket_test.go
resource/alicloud_oss_bucket: Adjust to configure Acl during creation.
=> resource/alicloud_oss_bucket: Adjust to configure Acl during creation.

alicloud/data_source_alicloud_dcdn_waf_policies.go, alicloud/data_source_alicloud_dcdn_waf_policies_test.go, alicloud/data_source_alicloud_polardb_parameter_groups.go, alicloud/provider.go, alicloud/resource_alicloud_dcdn_waf_policy.go, alicloud/resource_alicloud_dcdn_waf_policy_test.go, alicloud/service_alicloud_dcdn.go, website/alicloud.erb, website/docs/d/dcdn_waf_policies.html.markdown, website/docs/r/dcdn_waf_policy.html.markdown
New Resource `alicloud_dcdn_waf_policy`;
New Datasource `alicloud_dcdn_waf_policies`;
=> New Resource `alicloud_dcdn_waf_policy`; New Datasource `alicloud_dcdn_waf_policies`;

alicloud/connectivity/client.go, alicloud/connectivity/config.go, alicloud/data_source_alicloud_vpc_peerings.go, alicloud/data_source_alicloud_vpc_peerings_test.go, alicloud/provider.go, alicloud/resource_alicloud_vpc_peering.go, alicloud/resource_alicloud_vpc_peering_test.go, alicloud/service_alicloud_vpc_peer.go, website/alicloud.erb, website/docs/d/vpc_peerings.html.markdown, website/docs/r/vpc_peering.html.markdown
New Resource `alicloud_vpc_peering`;
New Datasource `alicloud_vpc_peerings`;
=> New Resource `alicloud_vpc_peering`; New Datasource `alicloud_vpc_peerings`;

alicloud/resource_alicloud_service_mesh_service_mesh.go, website/docs/r/service_mesh_service_mesh.html.markdown
…eList` to avoid resource recreated.
=> resource/alicloud_service_mesh_service_mesh: Change `TypeSet` to `TypeList` to avoid resource recreated.

alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_cluster_test.go
=> resource/alicloud_polardb_cluster: Fixes the setting attribute zone_id failed error

alicloud/data_source_alicloud_ecs_activations_test.go, alicloud/data_source_alicloud_ecs_invocations_test.go, alicloud/data_source_alicloud_ecs_network_interface_permissions_test.go, alicloud/resource_alicloud_graph_database_db_instance.go, ci/pipeline.yml, website/docs/r/graph_database_db_instance.html.markdown
=> resource/alicloud_graph_database_db_instance: Enlarges the creating and deleting default timeout

alicloud/resource_alicloud_route_table.go
=> resource/alicloud_route_table: Add retry code `IncorrectStatus.cbnStatus`

alicloud/connectivity/client.go, alicloud/connectivity/config.go, alicloud/data_source_alicloud_dbs_backup_plans.go, alicloud/data_source_alicloud_dbs_backup_plans_test.go, alicloud/provider.go, alicloud/resource_alicloud_dbs_backup_plan.go, alicloud/resource_alicloud_dbs_backup_plan_test.go, alicloud/service_alicloud_dbs.go, website/alicloud.erb, website/docs/d/dbs_backup_plans.html.markdown, website/docs/r/dbs_backup_plan.html.markdown
New Resource `alicloud_dbs_backup_plan`;
New Datasource `alicloud_dbs_backup_plans`;
=> New Resource `alicloud_dbs_backup_plan`; New Datasource `alicloud_dbs_backup_plans`;

alicloud/resource_alicloud_express_connect_physical_connection.go, website/docs/r/express_connect_physical_connection.html.markdown
…100GBase-LR` and `40GBase-LR`
=> reource/alicloud_express_connect_physical_connection: supported for `100GBase-LR` and `40GBase-LR`

alicloud/data_source_alicloud_dcdn_waf_domains.go, alicloud/data_source_alicloud_dcdn_waf_domains_test.go, alicloud/data_source_alicloud_ram_policy_document_test.go, alicloud/provider.go, alicloud/resource_alicloud_dcdn_waf_domain.go, alicloud/resource_alicloud_dcdn_waf_domain_test.go, alicloud/service_alicloud_dcdn.go, website/alicloud.erb, website/docs/d/dcdn_waf_domains.html.markdown, website/docs/r/dcdn_waf_domain.html.markdown
New Resource `alicloud_dcdn_waf_domain`;
New Datasource `alicloud_dcdn_waf_domains`;
=> New Resource `alicloud_dcdn_waf_domain`; New Datasource `alicloud_dcdn_waf_domains`;

alicloud/resource_alicloud_dcdn_waf_domain_test.go
resource/alicloud_dcdn_waf_domain: fix test case TestAccAlicloudDCDNWafDomain_basic1.
=> resource/alicloud_dcdn_waf_domain: fix test case TestAccAlicloudDCDNWafDomain_basic1.

alicloud/data_source_alicloud_api_gateway_log_configs.go, alicloud/provider.go, alicloud/resource_alicloud_api_gateway_log_config.go, alicloud/resource_alicloud_api_gateway_log_config_test.go, alicloud/resource_alicloud_vpc.go, alicloud/resource_alicloud_vpc_ipv4_cidr_block.go, alicloud/resource_alicloud_vpc_ipv4_cidr_block_test.go, alicloud/service_alicloud_vpc.go, website/alicloud.erb, website/docs/r/vpc.html.markdown, website/docs/r/vpc_ipv4_cidr_block.html.markdown
New Resource `alicloud_vpc_ipv4_cidr_block`;
resource/alicloud_vpc: Field 'secondary_cidr_blocks' has been deprecated
=> New Resource `alicloud_vpc_ipv4_cidr_block`;

alicloud/data_source_alicloud_api_gateway_log_configs.go, alicloud/resource_alicloud_api_gateway_log_config.go, alicloud/resource_alicloud_api_gateway_log_config_test.go, alicloud/resource_alicloud_ecs_instance_set.go
=> resource/alicloud_ecs_instance_set: Save the instance ids when an error occurs.

alicloud/resource_alicloud_fc_trigger.go, alicloud/service_alicloud_fc.go
=> resource/alicloud_fc_trigger: Fixes the panic error when validating the config

alicloud/resource_alicloud_privatelink_vpc_endpoint.go
=> resource/alicloud_privatelink_vpc_endpoint: Fixes the panic error when setting security_groups

alicloud/resource_alicloud_cms_alarm.go
=> resource/alicloud_cms_alarm: Fixes the panic error when setting prometheus

alicloud/resource_alicloud_elasticsearch_instance.go, alicloud/service_alicloud_common_test.go, alicloud/service_alicloud_elasticsearch.go
… retry;Reduce StateChangeConf delay time to 60*time.Second
=> resource/alicloud_elasticsearch_instance: Add DescribeInstance action retry;Reduce StateChangeConf delay time to 60*time.Second

alicloud/resource_alicloud_nas_file_system.go, alicloud/resource_alicloud_nas_file_system_test.go
=> resource/alicloud_nas_file_system: Supporting to update attribute capacity

alicloud/resource_alicloud_vpc.go, website/docs/r/vpc.html.markdown
=> resource/alicloud_vpc: Removes the forceNew for dry_run

alicloud/provider.go, alicloud/resource_alicloud_nas_smb_acl_attachment.go, alicloud/resource_alicloud_nas_smb_acl_attachment_test.go, alicloud/service_alicloud_nas.go, examples/nas-smb-acl/README.md, examples/nas-smb-acl/main.tf, examples/nas-smb-acl/outputs.tf, examples/nas-smb-acl/versions.tf, website/docs/r/nas_smb_acl_attachment.html.markdown
testing report:
1. alicloud_nas_access_rule support `filesystem_type` and Ipv6
Resource：
Data：
Terraform：
2. New Resource `alicloud_nas_smb_acl_attachment`
Resource：
Terraform：
=> New Resource `alicloud_nas_smb_acl_attachment`

alicloud/resource_alicloud_dns_record.go
resource/alicloud_dns_record: Add retryable error content to dns record creation, modification, and deletion.
=> resource/alicloud_dns_record: Add retryable error content to dns record creation, modification, and deletion.

alicloud/provider.go, alicloud/resource_alicloud_dcdn_waf_policy_domain_attachment.go, alicloud/resource_alicloud_dcdn_waf_policy_domain_attachment_test.go, alicloud/service_alicloud_dcdn.go, website/alicloud.erb, website/docs/r/dcdn_waf_policy_domain_attachment.html.markdown
New Resource `alicloud_dcdn_waf_policy_domain_attachment`;
=> New Resource `alicloud_dcdn_waf_policy_domain_attachment`;

website/docs/d/vpn_gateway_vco_routes.html.markdown, website/docs/d/vpn_gateway_vpn_attachments.html.markdown, website/docs/r/cen_transit_router_route_table_association.html.markdown, website/docs/r/cen_transit_router_route_table_propagation.html.markdown, website/docs/r/cen_transit_router_vpc_attachment.html.markdown, website/docs/r/vpn_gateway_vco_route.html.markdown
doc/cen_transit_router_vpc_attachment: fix doc example.
doc/vpn_gateway_vco_route: Adjust doc subcategory.
=> doc/cen_transit_router_vpc_attachment: fix doc example. doc/vpn_gateway_vco_route: Adjust doc subcategory.

alicloud/connectivity/client.go, alicloud/connectivity/config.go, alicloud/data_source_alicloud_nlb_server_groups.go, alicloud/data_source_alicloud_nlb_server_groups_test.go, alicloud/data_source_alicloud_vpc_public_ip_address_pools.go, alicloud/provider.go, alicloud/resource_alicloud_nlb_server_group.go, alicloud/resource_alicloud_nlb_server_group_test.go, alicloud/resource_alicloud_vpc_public_ip_address_pool.go, alicloud/service_alicloud_nlb.go, website/alicloud.erb, website/docs/d/nlb_server_groups.html.markdown, website/docs/r/nlb_server_group.html.markdown
New Resource `alicloud_nlb_server_group`;
New Datasource `alicloud_nlb_server_groups`;
=> New Resource `alicloud_nlb_server_group`; New Datasource `alicloud_nlb_server_groups`;

alicloud/resource_alicloud_vpn_gateway_vpn_attachment.go, website/docs/r/vpn_gateway_vpn_attachment.html.markdown
resource/alicloud_vpn_gateway_vpn_attachment: Add new attribute `internet_ip`.
=> resource/alicloud_vpn_gateway_vpn_attachment: Add new attribute `internet_ip`.

alicloud/connectivity/client.go, alicloud/connectivity/config.go, alicloud/data_source_alicloud_vpc_peer_connections.go, alicloud/data_source_alicloud_vpc_peer_connections_test.go, alicloud/provider.go, alicloud/resource_alicloud_dcdn_waf_policy_domain_attachment_test.go, alicloud/resource_alicloud_scdn_domain_config_test.go, alicloud/resource_alicloud_sddp_instance_test.go, alicloud/resource_alicloud_slb_acl_test.go, alicloud/resource_alicloud_vpc_peer_connection.go, alicloud/resource_alicloud_vpc_peer_connection_test.go, alicloud/service_alicloud_vpc_peer.go, website/alicloud.erb, website/docs/d/vpc_peer_connections.html.markdown, website/docs/r/vpc_peer_connection.html.markdown
New Resource `alicloud_vpc_peer_connection`;
New Datasource `alicloud_vpc_peer_connections`;
=> New Resource `alicloud_vpc_peer_connection`; New Datasource `alicloud_vpc_peer_connections`;

website/docs/d/polardb_node_classes.html.markdown
doc/polardb_node_classes: Optimize test cases in documentation.
=> doc/polardb_node_classes: Optimize test cases in documentation.

alicloud/alicloud_sweeper_test.go, alicloud/connectivity/client.go, alicloud/connectivity/config.go, alicloud/connectivity/endpoint.go, alicloud/provider.go
client: Replace raw map with sync Map
=> client: Replace raw map with sync Map

alicloud/connectivity/client.go, alicloud/connectivity/config.go, alicloud/connectivity/regions.go, alicloud/data_source_alicloud_ebs_disk_replica_groups.go, alicloud/data_source_alicloud_ebs_disk_replica_groups_test.go, alicloud/data_source_alicloud_ebs_regions.go, alicloud/data_source_alicloud_ebs_regions_test.go, alicloud/provider.go, alicloud/resource_alicloud_ebs_disk_replica_group.go, alicloud/resource_alicloud_ebs_disk_replica_group_test.go, alicloud/resource_alicloud_ga_access_log.go, alicloud/service_alicloud_ebs.go, website/alicloud.erb, website/docs/d/ebs_disk_replica_groups.html.markdown, website/docs/d/ebs_regions.html.markdown, website/docs/r/ebs_disk_replica_group.html.markdown
New Datasource `alicloud_ebs_regions`
New Datasource `alicloud_ebs_disk_replica_groups`
=> New Resource `alicloud_ebs_disk_replica_group` New Datasource `alicloud_ebs_regions` New Datasource `alicloud_ebs_disk_replica_groups`

alicloud/data_source_alicloud_nlb_security_policies.go, alicloud/data_source_alicloud_nlb_security_policies_test.go, alicloud/provider.go, alicloud/resource_alicloud_nlb_security_policy.go, alicloud/resource_alicloud_nlb_security_policy_test.go, alicloud/service_alicloud_nlb.go, website/alicloud.erb, website/docs/d/nlb_security_policies.html.markdown, website/docs/r/nlb_security_policy.html.markdown
New Resource `alicloud_nlb_security_policy`;
New Datasource `alicloud_nlb_security_policies`;
=> New Resource `alicloud_nlb_security_policy`; New Datasource `alicloud_nlb_security_policies`;

alicloud/data_source_alicloud_ebs_regions_test.go, alicloud/resource_alicloud_ebs_disk_replica_group_test.go
testcases: Fix ci test error for ebs
=> testcases: Fix ci test error for ebs

alicloud/connectivity/regions.go, alicloud/provider.go, alicloud/resource_alicloud_vod_editing_project.go, alicloud/resource_alicloud_vod_editing_project_test.go, alicloud/service_alicloud_vod.go, website/alicloud.erb, website/docs/r/vod_editing_project.html.markdown
New Resource `alicloud_vod_editing_project`;
=> New Resource `alicloud_vod_editing_project`;

alicloud/resource_alicloud_log_oss_export.go, alicloud/resource_alicloud_log_oss_export_test.go, go.mod, go.sum, vendor/github.com/aliyun/aliyun-log-go-sdk/client_alert.go, vendor/modules.txt
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudLogOssExport -timeout=30m
=== RUN   TestAccAlicloudLogOssExport_basic
--- PASS: TestAccAlicloudLogOssExport_basic (73.80s)
=== RUN   TestAccAlicloudLogOssExport_parquest
--- PASS: TestAccAlicloudLogOssExport_parquest (73.42s)
=== RUN   TestAccAlicloudLogOssExport_csv
--- PASS: TestAccAlicloudLogOssExport_csv (73.28s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  220.595s
=> testcases: Fix `resource/alicloud_log_oss_export_test` error 

alicloud/connectivity/client.go
resource/alicloud_vpc_peer_connection: fix Vpcpeer endpoint.
=> resource/alicloud_vpc_peer_connection: fix Vpcpeer endpoint.

alicloud/data_source_alicloud_ebs_regions_test.go, alicloud/resource_alicloud_bastionhost_instance.go, alicloud/resource_alicloud_bastionhost_instance_test.go, alicloud/resource_alicloud_nlb_security_policy.go, alicloud/service_alicloud_yundun_bastionhost.go, website/docs/r/bastionhost_instance.html.markdown
resource/alicloud_bastionhost_instance: support for `payment_type`, `renewal_status` `renew_period`.
=> resource/alicloud_bastionhost_instance: support for `renewal_status` `renew_period`.

alicloud/data_source_alicloud_slb_listeners.go, alicloud/data_source_alicloud_slb_listeners_test.go, alicloud/resource_alicloud_slb_listener.go, alicloud/resource_alicloud_slb_listener_test.go, website/docs/d/slb_listeners.html.markdown, website/docs/r/slb_listener.html.markdown
resource/alicloud_slb_listener: Adds new attribute `proxy_protocol_v2_enabled`
=> resource/alicloud_slb_listener: Adds new attribute `proxy_protocol_v2_enabled`

alicloud/provider.go, alicloud/resource_alicloud_cen_transit_router_grant_attachment.go, alicloud/resource_alicloud_cen_transit_router_grant_attachment_test.go, alicloud/service_alicloud_cbn.go, website/alicloud.erb, website/docs/r/cen_transit_router_grant_attachment.html.markdown
New Resource: `alicloud_cen_transit_router_grant_attachment`
=> New Resource: `alicloud_cen_transit_router_grant_attachment`

alicloud/resource_alicloud_adb_db_cluster.go, alicloud/resource_alicloud_adb_db_cluster_test.go, website/docs/r/adb_db_cluster.html.markdown
=> resource/alicloud_adb_db_cluster: Supporting to modify db_node_class and db_node_storage at the same time

alicloud/resource_alicloud_cs_kubernetes.go, alicloud/resource_alicloud_cs_serverless_kubernetes.go
resource/alicloud_cs_kubernetes: Failed to get cluster kubeconfig, do not block cluster operation.
=> resource/alicloud_cs_kubernetes: Failed to get cluster kubeconfig, do not block cluster operation

alicloud/data_source_alicloud_cs_cluster_credential.go, alicloud/data_source_alicloud_cs_cluster_credential_test.go, alicloud/data_source_alicloud_cs_kubernetes_clusters.go, alicloud/data_source_alicloud_cs_managed_kubernetes_clusters.go, alicloud/data_source_alicloud_cs_serverless_kubernetes_clusters.go, alicloud/errors.go, alicloud/provider.go, alicloud/resource_alicloud_cs_edge_kubernetes.go, alicloud/resource_alicloud_cs_kubernetes.go, alicloud/resource_alicloud_cs_managed_kubernetes.go, alicloud/resource_alicloud_cs_serverless_kubernetes.go, alicloud/service_alicloud_cs.go, website/alicloud.erb, website/docs/d/cs_cluster_credential.html.markdown, website/docs/d/cs_kubernetes_clusters.html.markdown, website/docs/d/cs_managed_kubernetes_clusters.html.markdown, website/docs/d/cs_serverless_kubernetes_clusters.html.markdown, website/docs/r/cs_edge_kubernetes.html.markdown, website/docs/r/cs_kubernetes.html.markdown, website/docs/r/cs_managed_kubernetes.html.markdown, website/docs/r/cs_serverless_kubernetes.html.markdown
new datasource: alicloud_cs_cluster_credential
=> new datasource: alicloud_cs_cluster_credential

alicloud/connectivity/regions.go, alicloud/data_source_alicloud_api_gateway_plugins.go, alicloud/data_source_alicloud_api_gateway_plugins_test.go, alicloud/provider.go, alicloud/resource_alicloud_api_gateway_plugin.go, alicloud/resource_alicloud_api_gateway_plugin_test.go, alicloud/service_alicloud_cloud_api.go, website/alicloud.erb, website/docs/d/api_gateway_plugins.html.markdown, website/docs/r/api_gateway_plugin.html.markdown
New Resource `alicloud_api_gateway_plugin`;
New Datasource `alicloud_api_gateway_plugins`;
=> New Resource `alicloud_api_gateway_plugin`; New Datasource `alicloud_api_gateway_plugins`;

alicloud/resource_alicloud_vpn_gateway_vpn_attachment.go
resource_alicloud_vpn_gateway_vpn_attachment: Corrected field ike_config.local_id, ike_config.remote_id to Computed
=> resource_alicloud_vpn_gateway_vpn_attachment: Corrected field ike_config.local_id, ike_config.remote_id to Computed

alicloud/data_source_alicloud_api_gateway_models.go, alicloud/data_source_alicloud_cs_cluster_credential_test.go, alicloud/data_source_alicloud_cs_kubernetes_clusters.go, alicloud/data_source_alicloud_cs_managed_kubernetes_clusters.go, alicloud/data_source_alicloud_cs_serverless_kubernetes_clusters.go, alicloud/data_source_alicloud_gpdb_instances_test.go, alicloud/data_source_alicloud_message_service_queues.go, alicloud/data_source_alicloud_message_service_subscriptions.go, alicloud/data_source_alicloud_message_service_topics.go, alicloud/data_source_alicloud_resource_manager_account_deletion_check_task.go, alicloud/resource_alicloud_api_gateway_model.go, alicloud/resource_alicloud_api_gateway_model_test.go, alicloud/resource_alicloud_ess_alb_server_group_attachment.go, alicloud/resource_alicloud_gpdb_instance.go, alicloud/resource_alicloud_gpdb_instance_test.go, alicloud/resource_alicloud_lindorm_instance.go, alicloud/resource_alicloud_message_service_queue.go, alicloud/resource_alicloud_message_service_subscription.go, alicloud/resource_alicloud_message_service_subscription_test.go, alicloud/resource_alicloud_message_service_topic.go, website/docs/r/lindorm_instance.html.markdown
=> resource/alicloud_lindorm_instance: Remove the discarded fields `core_num` and `core_spec`

alicloud/provider.go
=> provider: Supports new environment parameter ALIBABACLOUD_ACCESS_KEY_SECRET and ALIBABACLOUD_ACCESS_KEY_ID

alicloud/data_source_alicloud_sae_applications.go, alicloud/resource_alicloud_sae_application.go, alicloud/resource_alicloud_sae_application_test.go, website/docs/d/sae_applications.html.markdown, website/docs/r/sae_application.html.markdown
resource/alicloud_sae_application: Support new attribute `acr_instance_id`, `acr_assume_role_arn`.
=> resource/alicloud_sae_application: Support new attribute `acr_instance_id`, `acr_assume_role_arn`.

alicloud/connectivity/regions.go, alicloud/data_source_alicloud_cen_transit_router_prefix_list_associations.go, alicloud/data_source_alicloud_gpdb_db_instance_plans.go, alicloud/data_source_alicloud_gpdb_db_instance_plans_test.go, alicloud/data_source_alicloud_vpc_public_ip_address_pool_cidr_blocks.go, alicloud/data_source_alicloud_vpc_public_ip_address_pool_cidr_blocks_test.go, alicloud/provider.go, alicloud/resource_alicloud_cen_transit_router_prefix_list_association.go, alicloud/resource_alicloud_gpdb_db_instance_plan.go, alicloud/resource_alicloud_gpdb_db_instance_plan_test.go, alicloud/resource_alicloud_vpc_public_ip_address_pool_cidr_block.go, alicloud/resource_alicloud_vpc_public_ip_address_pool_cidr_block_test.go, alicloud/service_alicloud_gpdb.go, website/alicloud.erb, website/docs/d/gpdb_db_instance_plans.html.markdown, website/docs/d/gpdb_instances.html.markdown, website/docs/r/gpdb_db_instance_plan.html.markdown
New Resource `alicloud_gpdb_db_instance_plan`;
New Datasource `alicloud_gpdb_db_instance_plans`;
=> New Resource `alicloud_gpdb_db_instance_plan`; New Datasource `alicloud_gpdb_db_instance_plans`;

alicloud/resource_alicloud_instance.go, alicloud/resource_alicloud_instance_test.go, website/docs/guides/getting-account.html.md
resource/alicloud_instance: Supports attribute `system_disk_name`, `system_disk_description` import and update.
=> resource/alicloud_instance: Supports attribute `system_disk_name`, `system_disk_description` import and update.

alicloud/resource_alicloud_rds_upgrade_db_instance.go
=> resource/alicloud_rds_upgrade_db_instance:Repair pg major version upgrade

alicloud/resource_alicloud_instance_test.go
resource/alicloud_instance_test: fix test case TestAccAlicloudECSInstanceTypeUpdate and TestAccAlicloudECSInstancSecondaryIps.
=> resource/alicloud_instance_test: fix test case TestAccAlicloudECSInstanceTypeUpdate and TestAccAlicloudECSInstancSecondaryIps.

alicloud/common.go, alicloud/connectivity/regions.go, alicloud/data_source_alicloud_adb_db_cluster_lake_versions.go, alicloud/data_source_alicloud_adb_db_cluster_lake_versions_test.go, alicloud/provider.go, alicloud/resource_alicloud_adb_db_cluster_lake_version.go, alicloud/resource_alicloud_adb_db_cluster_lake_version_test.go, alicloud/resource_alicloud_cms_group_metric_rule.go, alicloud/service_alicloud_adb.go, website/alicloud.erb, website/docs/d/adb_db_cluster_lake_versions.html.markdown, website/docs/d/adb_db_clusters.html.markdown, website/docs/r/adb_db_cluster_lake_version.html.markdown
New Resource `alicloud_adb_db_cluster_lake_version`;
New Datasource `alicloud_adb_db_cluster_lake_versions`;
=> New Resource `alicloud_adb_db_cluster_lake_version`; New Datasource `alicloud_adb_db_cluster_lake_versions`;

alicloud/resource_alicloud_express_connect_virtual_border_router.go, alicloud/service_alicloud_vpc.go, website/docs/r/express_connect_virtual_border_router.html.markdown
[…attribute include_cross_account_vbr](resource:resource_alicloud_express_connect_virtual_border_router add attribute include_cross_account_vbr)
=> resource:resource_alicloud_express_connect_virtual_border_router add attribute include_cross_account_vbr

alicloud/data_source_alicloud_nlb_listeners.go, alicloud/data_source_alicloud_nlb_listeners_test.go, alicloud/provider.go, alicloud/resource_alicloud_nlb_listener.go, alicloud/resource_alicloud_nlb_listener_test.go, alicloud/resource_alicloud_nlb_load_balancer_test.go, alicloud/resource_alicloud_nlb_server_group.go, alicloud/service_alicloud_nlb.go, website/alicloud.erb, website/docs/d/nlb_listeners.html.markdown, website/docs/r/nlb_listener.html.markdown
New Resource `alicloud_nlb_listener`;
New Datasource `alicloud_nlb_listeners`;
=> New Resource `alicloud_nlb_listener`; New Datasource `alicloud_nlb_listeners`;

alicloud/resource_alicloud_nlb_server_group_test.go
resource/alicloud_nlb_server_group: fix test case TestAccAlicloudNLBServerGroup_basic1.
=> resource/alicloud_nlb_server_group: fix test case TestAccAlicloudNLBServerGroup_basic1.

alicloud/resource_alicloud_db_instance.go
resource/alicloud_db_instance: Increase status wait when updating payment type.
=> resource/alicloud_db_instance: Increase status wait when updating payment type.

website/docs/r/cloud_sso_group.html.markdown, website/docs/r/instance.html.markdown
docs: Remove incorrect area restriction description.
=> docs: Remove incorrect area restriction description.

alicloud/data_source_alicloud_nlb_server_group_server_attachments.go, alicloud/data_source_alicloud_nlb_server_group_server_attachments_test.go, alicloud/data_source_alicloud_service_mesh_extension_providers.go, alicloud/provider.go, alicloud/resource_alicloud_nlb_server_group_server_attachment.go, alicloud/resource_alicloud_nlb_server_group_server_attachment_test.go, alicloud/resource_alicloud_service_mesh_extension_provider.go, alicloud/service_alicloud_nlb.go, website/alicloud.erb, website/docs/d/nlb_server_group_server_attachments.html.markdown, website/docs/r/nlb_server_group_server_attachment.html.markdown
New Resource `alicloud_nlb_server_group_server_attachment`;
New Datasource `alicloud_nlb_server_group_server_attachments`;
=> New Resource `alicloud_nlb_server_group_server_attachment`; New Datasource `alicloud_nlb_server_group_server_attachments`;

alicloud/data_source_alicloud_service_mesh_extension_providers.go, alicloud/resource_alicloud_instance.go, alicloud/resource_alicloud_instance_test.go, alicloud/resource_alicloud_service_mesh_extension_provider.go, alicloud/service_alicloud_ecs.go, website/docs/r/instance.html.markdown
resource/alicloud_instance: Support new attribute `http_tokens`, `http_endpoint`, `http_put_response_hop_limit`.
=> resource/alicloud_instance: Support new attribute `http_tokens`, `http_endpoint`, `http_put_response_hop_limit`.

alicloud/resource_alicloud_log_project.go, alicloud/resource_alicloud_log_project_test.go, alicloud/service_alicloud_log.go, go.mod, go.sum, website/docs/r/log_project.html.markdown
=> resource/alicloud_log_project: Support new attribute `policy`.

alicloud/resource_alicloud_cs_kubernetes.go, alicloud/resource_alicloud_cs_kubernetes_addon.go, alicloud/resource_alicloud_cs_kubernetes_node_pool.go, alicloud/resource_alicloud_cs_managed_kubernetes.go, alicloud/service_alicloud_cs.go, website/docs/r/cs_kubernetes.html.markdown, website/docs/r/cs_kubernetes_node_pool.html.markdown, website/docs/r/cs_managed_kubernetes.html.markdown
1. Optimize components uninstall logic.
2. Adjust the scaling logic of the node pool to prevent the inconsistency between the nodecount and the desiredsize after the pop-up node fails for some reasons.
3. Optimize documents.
=> resource/alicloud_cs_kubernetes_addon: Optimize components uninstall logic

alicloud/resource_alicloud_slb_load_balancer.go, website/docs/r/slb_load_balancer.html.markdown
…no longer alias of payment_type.
=> resource/alicloud_slb_load_balance: Attribute instance_charge_type is no longer alias of payment_type.

alicloud/data_source_alicloud_instances_test.go, alicloud/service_alicloud_common_test.go
data_source/alicloud_instances_test: fix test case TestAccAlicloudECSInstancesDataSourceBasic
=> data_source/alicloud_instances_test: fix test case TestAccAlicloudECSInstancesDataSourceBasic

alicloud/resource_alicloud_ecs_network_interface.go, alicloud/resource_alicloud_ecs_network_interface_test.go, alicloud/service_alicloud_ecs.go, website/docs/r/ecs_network_interface.html.markdown
resource/alicloud_ecs_network_interface: Support new attribute `ipv6_address_count` and `ipv6_addresses`.
=> resource/alicloud_ecs_network_interface: Support new attribute `ipv6_address_count` and `ipv6_addresses`.

alicloud/resource_alicloud_alb_server_group.go, alicloud/resource_alicloud_alb_server_group_test.go, website/docs/r/alb_server_group.html.markdown
resource/alicloud_alb_server_group: Support new attribute `server_group_type`.
=> resource/alicloud_alb_server_group: Support new attribute `server_group_type`.

alicloud/resource_alicloud_vpn_gateway.go, website/docs/r/vpn_gateway.html.markdown
=> resource/alicloud_vpn_gateway: Add default value for network_type and fix document

alicloud/resource_alicloud_ess_scheduled_task.go, alicloud/resource_alicloud_ess_scheduled_task_test.go
=> resource/alicloud_ess_scheduled_task: max_value & min_value support set zero value

alicloud/resource_alicloud_drds_instance.go, alicloud/resource_alicloud_kvstore_instance.go
=> resource/alicloud_drds_instance: Fixes the InternalError error; resource/alicloud_kvstore_instance: Corrects the creating timeout to 20min

alicloud/data_source_alicloud_rds_cross_regions.go, alicloud/data_source_alicloud_vpn_gateways.go, alicloud/resource_alicloud_db_instance.go, alicloud/resource_alicloud_rds_clone_db_instance.go, alicloud/resource_alicloud_rds_upgrade_db_instance.go, alicloud/service_alicloud_rds.go
=> resource/alicloud_db_instance: Adds checking connection string to meet some instance class without connection issue

alicloud/resource_alicloud_vpn_gateway_vco_route.go
resource/alicloud_vpn_gateway_vco_route: Add retry error code.
=> resource/alicloud_vpn_gateway_vco_route: Add retry error code.

alicloud/resource_alicloud_alb_load_balancer.go, alicloud/resource_alicloud_alb_load_balancer_test.go, website/docs/r/alb_load_balancer.html.markdown
resource/alicloud_alb_load_balancer: Support new attribute `address_ip_version`; Add optional `StandardWithWaf` for `load_balancer_edition`.
=> resource/alicloud_alb_load_balancer: Support new attribute `address_ip_version`; Add optional `StandardWithWaf` for `load_balancer_edition`.

alicloud/resource_alicloud_vpn_connection.go
resource/alicloud_vpn_connection: Add retry error code.
=> resource/alicloud_vpn_connection: Add retry error code.

website/docs/r/slb_server_group_server_attachment.html.markdown
=> docs/alicloud_slb_server_group_attachment: Adds notes to avoid conflict error

alicloud/data_source_alicloud_cms_metric_rule_black_lists.go, alicloud/data_source_alicloud_cms_metric_rule_black_lists_test.go, alicloud/provider.go, alicloud/resource_alicloud_cms_metric_rule_black_list.go, alicloud/resource_alicloud_cms_metric_rule_black_list_test.go, alicloud/service_alicloud_cms.go, website/alicloud.erb, website/docs/d/cms_metric_rule_black_lists.html.markdown, website/docs/r/cms_metric_rule_black_list.html.markdown
New Resource `alicloud_cms_metric_rule_black_list`; New Datasource `alicloud_cms_metric_rule_black_lists`
=> New Resource `alicloud_cms_metric_rule_black_list`; New Datasource `alicloud_cms_metric_rule_black_lists`

alicloud/data_source_alicloud_cloud_firewall_vpc_firewall_cens.go, alicloud/data_source_alicloud_cloud_firewall_vpc_firewall_cens_test.go, alicloud/provider.go, alicloud/resource_alicloud_cloud_firewall_vpc_firewall_cen.go, alicloud/resource_alicloud_cloud_firewall_vpc_firewall_cen_test.go, alicloud/service_alicloud_cloudfw.go, website/alicloud.erb, website/docs/d/cloud_firewall_vpc_firewall_cens.html.markdown, website/docs/r/cloud_firewall_vpc_firewall_cen.html.markdown
New Resource `alicloud_cloud_firewall_vpc_firewall_cen`; New Datasource `alicloud_cloud_firewall_vpc_firewall_cens`
=> New Resource `alicloud_cloud_firewall_vpc_firewall_cen`; New Datasource `alicloud_cloud_firewall_vpc_firewall_cens`

alicloud/connectivity/client.go, alicloud/connectivity/regions.go, alicloud/data_source_alicloud_cloud_firewall_vpc_firewalls.go, alicloud/data_source_alicloud_cloud_firewall_vpc_firewalls_test.go, alicloud/provider.go, alicloud/resource_alicloud_cloud_firewall_vpc_firewall.go, alicloud/resource_alicloud_cloud_firewall_vpc_firewall_test.go, alicloud/service_alicloud_cloudfw.go, website/alicloud.erb, website/docs/d/cloud_firewall_vpc_firewalls.html.markdown, website/docs/r/cloud_firewall_vpc_firewall.html.markdown
New Resource `alicloud_cloud_firewall_vpc_firewall`; New Datasource `alicloud_cloud_firewall_vpc_firewalls`
=> New Resource `alicloud_cloud_firewall_vpc_firewall`; New Datasource `alicloud_cloud_firewall_vpc_firewalls`

alicloud/resource_alicloud_alb_rule.go, alicloud/resource_alicloud_alb_rule_test.go, website/docs/r/alb_rule.html.markdown
resource/alicloud_alb_rule: Fix errors when the `weight` attribute is not configured.
=> resource/alicloud_alb_rule: Fix errors when the `weight` attribute is not configured.

alicloud/resource_alicloud_security_group_rule.go, website/docs/r/security_group_rule.html.markdown
resource_alicloud_security_group_rule: The 'ForceNew' attribute of input parameter 'prefix_list_id' is set 'True'
=> resource_alicloud_security_group_rule: The 'ForceNew' attribute of input parameter 'prefix_list_id' is set 'True'

alicloud/resource_alicloud_lindorm_instance.go, go.sum
=> resource/alicloud_lindorm_instance: Fixes the instance_storage parsing bug when upgrading its value

alicloud/data_source_alicloud_cloud_firewall_vpc_firewall_cens_test.go, alicloud/data_source_alicloud_ga_basic_accelerate_ip_endpoint_relations.go, alicloud/data_source_alicloud_ga_basic_accelerate_ip_endpoint_relations_test.go, alicloud/data_source_alicloud_ga_basic_accelerate_ips.go, alicloud/data_source_alicloud_ga_basic_endpoints_test.go, alicloud/resource_alicloud_ga_basic_accelerate_ip.go, alicloud/resource_alicloud_ga_basic_accelerate_ip_endpoint_relation.go, alicloud/resource_alicloud_ga_basic_accelerate_ip_endpoint_relation_test.go, alicloud/resource_alicloud_ga_basic_endpoint_test.go, alicloud/resource_alicloud_lindorm_instance.go
=> resource/alicloud_lindorm_instance: Fixes the MissingUpgradeType error when updating the resource

alicloud/data_source_alicloud_vpn_gateways.go
=> datasource/alicloud_vpn_gateways: Fixes the nil pointer error when setting end_time

alicloud/resource_alicloud_resource_manager_account.go, website/docs/r/resource_manager_account.html.markdown
=> resource/alicloud_resource_manager_account: Improves the deleting action by setting deleting to success stauts

alicloud/resource_alicloud_express_connect_virtual_border_router.go, website/docs/r/cen_transit_router_vbr_attachment.html.markdown, website/docs/r/ess_attachment.html.markdown, website/docs/r/ram_role_attachment.html.markdown, website/docs/r/slb_attachment.html.markdown
=> resource/alicloud_express_connect_virtual_border_router: setting the attribute bandwidth to computed

alicloud/resource_alicloud_dcdn_domain.go, alicloud/resource_alicloud_ecs_network_interface_test.go, alicloud/resource_alicloud_hbase_instance_test.go, alicloud/service_alicloud_eipanycast.go
=> resource/alicloud_dcdn_domain: Fixes the CertName.MissingParameter error when updating the certificate

alicloud/resource_alicloud_slb_load_balancer.go, alicloud/resource_alicloud_slb_load_balancer_test.go, website/docs/r/slb_load_balancer.html.markdown
=> resource/alicloud_slb_load_balancer: Fixes the attribute instance_charge_type diff error

alicloud/resource_alicloud_lindorm_instance.go, website/docs/r/lindorm_instance.html.markdown
=> resource/alicloud_lindorm_instance: Removes the some attributes' enums limitation

alicloud/data_source_alicloud_ga_basic_endpoints.go, alicloud/data_source_alicloud_threat_detection_web_lock_configs.go, alicloud/data_source_alicloud_threat_detection_web_lock_configs_test.go, alicloud/provider.go, alicloud/resource_alicloud_common_bandwidth_package_attachment.go, alicloud/resource_alicloud_ga_basic_endpoint.go, alicloud/resource_alicloud_threat_detection_web_lock_config.go, alicloud/resource_alicloud_threat_detection_web_lock_config_test.go, alicloud/service_alicloud_sas.go, website/docs/d/threat_detection_web_lock_configs.html.markdown, website/docs/r/threat_detection_web_lock_config.html.markdown
New Resource `alicloud_threat_detection_web_lock_config`;
New Datasource `alicloud_threat_detection_web_lock_configs`;
=> New Resource `alicloud_threat_detection_web_lock_config`; New Datasource `alicloud_threat_detection_web_lock_configs`;

alicloud/connectivity/regions.go, alicloud/data_source_alicloud_dms_enterprise_proxy_accesses.go, alicloud/data_source_alicloud_dms_enterprise_proxy_accesses_test.go, alicloud/provider.go, alicloud/resource_alicloud_dms_enterprise_proxy_access.go, alicloud/resource_alicloud_dms_enterprise_proxy_access_test.go, alicloud/service_alicloud_dms_enterprise.go, website/docs/d/dms_enterprise_proxy_accesses.html.markdown, website/docs/r/dms_enterprise_proxy_access.html.markdown
New Resource `alicloud_dms_enterprise_proxy_access`; New Datasource `alicloud_dms_enterprise_proxy_accesses`
=> New Resource `alicloud_dms_enterprise_proxy_access`; New Datasource `alicloud_dms_enterprise_proxy_accesses`

alicloud/data_source_alicloud_amqp_static_accounts.go, alicloud/data_source_alicloud_amqp_static_accounts_test.go, alicloud/provider.go, alicloud/resource_alicloud_amqp_static_account.go, alicloud/resource_alicloud_amqp_static_account_test.go, alicloud/service_alicloud_amqp_open.go, website/docs/d/amqp_static_accounts.html.markdown, website/docs/r/amqp_static_account.html.markdown
New Resource `alicloud_amqp_static_account`; New Datasource `alicloud_amqp_static_accounts`
=> New Resource `alicloud_amqp_static_account`; New Datasource `alicloud_amqp_static_accounts`

alicloud/connectivity/regions.go, alicloud/data_source_alicloud_adb_resource_groups.go, alicloud/data_source_alicloud_adb_resource_groups_test.go, alicloud/provider.go, alicloud/resource_alicloud_adb_resource_group.go, alicloud/resource_alicloud_adb_resource_group_test.go, alicloud/service_alicloud_adb.go, website/docs/d/adb_resource_groups.html.markdown, website/docs/r/adb_resource_group.html.markdown
New Resource `alicloud_adb_resource_group`; New Datasource `alicloud_adb_resource_groups`
=> New Resource `alicloud_adb_resource_group`; New Datasource `alicloud_adb_resource_groups`

alicloud/data_source_alicloud_dms_enterprise_proxy_accesses_test.go, alicloud/resource_alicloud_ecs_network_interface_attachment.go, alicloud/resource_alicloud_eip_association_test.go, alicloud/resource_alicloud_route_entry_test.go, alicloud/resource_alicloud_slb_attachment_test.go, alicloud/resource_alicloud_slb_backend_server_test.go, alicloud/resource_alicloud_slb_master_slave_server_group_test.go, alicloud/resource_alicloud_slb_rule.go, alicloud/resource_alicloud_slb_server_group_test.go, website/docs/r/slb_master_slave_server_group.html.markdown
=> resource/alicloud_slb_rule: Fixes the ServiceIsConfiguring error when creating the resource

alicloud/resource_alicloud_ess_eci_scaling_configuration.go
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEssEciScalingConfigurationBasic -timeout=300m
=== RUN   TestAccAlicloudEssEciScalingConfigurationBasic
--- PASS: TestAccAlicloudEssEciScalingConfigurationBasic (51.29s)
PASS
ok  	github.com/aliyun/terraform-provider-alicloud/alicloud	53.283s
=> - resource/alicloud_ess_eci_scaling_configuration: fix default integer value of livenessProbe and readinessProbe.

alicloud/data_source_alicloud_adb_resource_groups_test.go, alicloud/data_source_alicloud_amqp_static_accounts_test.go, alicloud/data_source_alicloud_dms_enterprise_databases.go, alicloud/data_source_alicloud_threat_detection_backup_policies.go, alicloud/data_source_alicloud_threat_detection_honeypot_nodes.go, alicloud/data_source_alicloud_threat_detection_honeypot_nodes_test.go, alicloud/data_source_alicloud_threat_detection_vul_whitelists.go, alicloud/provider.go, alicloud/resource_alicloud_rds_instance_cross_backup_policy.go, alicloud/resource_alicloud_threat_detection_backup_policy.go, alicloud/resource_alicloud_threat_detection_honeypot_node.go, alicloud/resource_alicloud_threat_detection_honeypot_node_test.go, alicloud/resource_alicloud_threat_detection_vul_whitelist.go, alicloud/service_alicloud_threat_detection.go, website/docs/d/threat_detection_honeypot_nodes.html.markdown, website/docs/r/threat_detection_honeypot_node.html.markdown
New Resource `alicloud_threat_detection_honeypot_node`;
New Datasource `alicloud_threat_detection_honeypot_nodes`;
=> New Resource `alicloud_threat_detection_honeypot_node`; New Datasource `alicloud_threat_detection_honeypot_nodes`;

alicloud/resource_alicloud_security_group.go, alicloud/resource_alicloud_slb_server_group_server_attachment.go, website/docs/r/slb_domain_extension.html.markdown
=> resource/alicloud_slb_server_group_server_attachment: Fixes the ServiceIsConfiguring error when creating the resource

alicloud/data_source_alicloud_threat_detection_baseline_strategies.go, alicloud/data_source_alicloud_threat_detection_baseline_strategies_test.go, alicloud/provider.go, alicloud/resource_alicloud_threat_detection_baseline_strategy.go, alicloud/resource_alicloud_threat_detection_baseline_strategy_test.go, alicloud/service_alicloud_sas.go, website/docs/d/threat_detection_baseline_strategies.html.markdown, website/docs/r/threat_detection_baseline_strategy.html.markdown
New Resource `alicloud_threat_detection_baseline_strategy`; New Datasource `alicloud_threat_detection_baseline_strategies`;
=> New Resource `alicloud_threat_detection_baseline_strategy`; New Datasource `alicloud_threat_detection_baseline_strategies`;

alicloud/data_source_alicloud_cen_inter_region_traffic_qos_policies.go, alicloud/data_source_alicloud_cen_inter_region_traffic_qos_policies_test.go, alicloud/data_source_alicloud_cen_transit_router_multicast_domains.go, alicloud/data_source_alicloud_cen_transit_router_multicast_domains_test.go, alicloud/data_source_alicloud_threat_detection_assets.go, alicloud/data_source_alicloud_threat_detection_assets_test.go, alicloud/provider.go, alicloud/resource_alicloud_cen_inter_region_traffic_qos_policy.go, alicloud/resource_alicloud_cen_inter_region_traffic_qos_policy_test.go, alicloud/resource_alicloud_cen_transit_router_multicast_domain.go, alicloud/service_alicloud_threat_detection.go, website/docs/d/threat_detection_assets.html.markdown
New Datasource `alicloud_threat_detection_assets`;
=> New Datasource `alicloud_threat_detection_assets`;

alicloud/data_source_alicloud_threat_detection_anti_brute_force_rules.go, alicloud/data_source_alicloud_threat_detection_anti_brute_force_rules_test.go, alicloud/provider.go, alicloud/resource_alicloud_threat_detection_anti_brute_force_rule.go, alicloud/resource_alicloud_threat_detection_anti_brute_force_rule_test.go, alicloud/service_alicloud_sas.go, website/docs/d/threat_detection_anti_brute_force_rules.html.markdown, website/docs/r/threat_detection_anti_brute_force_rule.html.markdown
New Resource `alicloud_threat_detection_anti_brute_force_rule`; New Datasource `alicloud_threat_detection_anti_brute_force_rules`;
=> New Resource `alicloud_threat_detection_anti_brute_force_rule`; New Datasource `alicloud_threat_detection_anti_brute_force_rules`;

alicloud/resource_alicloud_alikafka_instance.go, alicloud/resource_alicloud_alikafka_instance_test.go, alicloud/service_alicloud_alikafka.go, website/docs/r/alikafka_instance.html.markdown
resource/alicloud_alikafka_instance: Support new attribute `selected_zones`.
=> resource/alicloud_alikafka_instance: Support new attribute `selected_zones`.

alicloud/resource_alicloud_instance.go, website/docs/r/instance.html.markdown
=> resource/alicloud_instance: Adds new valid value Not-applicable for attribute stopped_mode

alicloud/data_source_alicloud_threat_detection_honeypot_probes.go, alicloud/data_source_alicloud_threat_detection_honeypot_probes_test.go, alicloud/provider.go, alicloud/resource_alicloud_threat_detection_honeypot_probe.go, alicloud/resource_alicloud_threat_detection_honeypot_probe_test.go, alicloud/service_alicloud_sas.go, website/docs/d/threat_detection_honeypot_probes.html.markdown, website/docs/r/threat_detection_honeypot_probe.html.markdown
New Resource `alicloud_threat_detection_honeypot_probe`; New Datasource `alicloud_threat_detection_honeypot_probes`;
=> New Resource `alicloud_threat_detection_honeypot_probe`; New Datasource `alicloud_threat_detection_honeypot_probes`;

alicloud/data_source_alicloud_ecs_capacity_reservations.go, alicloud/data_source_alicloud_ecs_capacity_reservations_test.go, alicloud/provider.go, alicloud/resource_alicloud_ecs_capacity_reservation.go, alicloud/resource_alicloud_ecs_capacity_reservation_test.go, alicloud/service_alicloud_ecs.go, website/alicloud.erb, website/docs/d/ecs_capacity_reservations.html.markdown, website/docs/r/ecs_capacity_reservation.html.markdown
New Resource `alicloud_ecs_capacity_reservation`;
New Datasource `alicloud_ecs_capacity_reservations`;
=> New Resource `alicloud_ecs_capacity_reservation`; New Datasource `alicloud_ecs_capacity_reservations`;

alicloud/connectivity/regions.go, alicloud/data_source_alicloud_cen_transit_router_multicast_domain_members.go, alicloud/data_source_alicloud_cen_transit_router_multicast_domain_members_test.go, alicloud/provider.go, alicloud/resource_alicloud_cen_transit_router_multicast_domain_member.go, alicloud/resource_alicloud_cen_transit_router_multicast_domain_member_test.go, alicloud/service_alicloud_cbn.go, website/alicloud.erb, website/docs/d/cen_transit_router_multicast_domain_members.html.markdown, website/docs/r/cen_transit_router_multicast_domain_member.html.markdown
New Resource `alicloud_cen_transit_router_multicast_domain_member`; New Datasource `alicloud_cen_transit_router_multicast_domain_members`;
=> New Resource `alicloud_cen_transit_router_multicast_domain_member`; New Datasource `alicloud_cen_transit_router_multicast_domain_members`;

alicloud/data_source_alicloud_cen_inter_region_traffic_qos_queues.go, alicloud/data_source_alicloud_cen_inter_region_traffic_qos_queues_test.go, alicloud/provider.go, alicloud/resource_alicloud_cen_inter_region_traffic_qos_queue.go, alicloud/resource_alicloud_cen_inter_region_traffic_qos_queue_test.go, alicloud/service_alicloud_cbn.go, website/alicloud.erb, website/docs/d/cen_inter_region_traffic_qos_queues.html.markdown, website/docs/r/cen_inter_region_traffic_qos_queue.html.markdown
=> New resource alicloud_cen_inter_region_traffic_qos_queue and its datasource.

alicloud/connectivity/regions.go, alicloud/data_source_alicloud_cen_child_instance_route_entry_to_attachments.go, alicloud/data_source_alicloud_cen_child_instance_route_entry_to_attachments_test.go, alicloud/provider.go, alicloud/resource_alicloud_cen_child_instance_route_entry_to_attachment.go, alicloud/resource_alicloud_cen_child_instance_route_entry_to_attachment_test.go, alicloud/service_alicloud_cbn.go, website/alicloud.erb, website/docs/d/cen_child_instance_route_entry_to_attachments.html.markdown, website/docs/r/cen_child_instance_route_entry_to_attachment.html.markdown
New Resource `alicloud_cen_child_instance_route_entry_to_attachment`; New Datasource `alicloud_cen_child_instance_route_entry_to_attachments`
=> New Resource `alicloud_cen_child_instance_route_entry_to_attachment`; New Datasource `alicloud_cen_child_instance_route_entry_to_attachments`

alicloud/data_source_alicloud_threat_detection_honeypot_presets.go, alicloud/data_source_alicloud_threat_detection_honeypot_presets_test.go, alicloud/provider.go, alicloud/resource_alicloud_threat_detection_honeypot_preset.go, alicloud/resource_alicloud_threat_detection_honeypot_preset_test.go, alicloud/service_alicloud_threat_detection.go, website/docs/d/threat_detection_honeypot_presets.html.markdown, website/docs/r/threat_detection_honeypot_preset.html.markdown
New Resource `alicloud_threat_detection_honeypot_preset`;
New Datasource `alicloud_threat_detection_honeypot_presets`;
=> New Resource `alicloud_threat_detection_honeypot_preset`; New Datasource `alicloud_threat_detection_honeypot_presets`;

alicloud/data_source_alicloud_cen_child_instance_route_entry_to_attachments_test.go, alicloud/resource_alicloud_cen_child_instance_route_entry_to_attachment_test.go, alicloud/service_alicloud_cbn.go
resource/alicloud_cen_child_instance_route_entry_to_attachment: Repair the error reported by CI test
=> resource/alicloud_cen_child_instance_route_entry_to_attachment: Repair the error reported by CI test

alicloud/data_source_alicloud_bss_open_api_pricing_modules.go, alicloud/data_source_alicloud_bss_open_api_pricing_modules_test.go, alicloud/data_source_alicloud_bss_open_api_products.go, alicloud/data_source_alicloud_bss_open_api_products_test.go, alicloud/provider.go, website/docs/d/bss_openapi_pricing_modules.html.markdown, website/docs/d/bss_openapi_products.html.markdown
New Datasource `alicloud_bss_openapi_products`; New Datasource `alicloud_bss_openapi_pricing_modules`;
=>  New Datasource `alicloud_bss_openapi_products`; New Datasource `alicloud_bss_openapi_pricing_modules`;

alicloud/resource_alicloud_slb_load_balancer.go, alicloud/resource_alicloud_slb_load_balancer_test.go
=> resource/alicloud_slb_load_balancer: Fixes the ShareSlbHaltSales error when creating PayByCLUC balancer

alicloud/resource_alicloud_dms_enterprise_instance_test.go, alicloud/resource_alicloud_express_connect_virtual_border_router_test.go, alicloud/service_alicloud_common_test.go
=> test: Improves the testing framework to support setting non-string value and additional attributes

alicloud/data_source_alicloud_cen_transit_router_multicast_domain_peer_members_test.go, alicloud/resource_alicloud_graph_database_db_instance.go
=> resource/alicloud_graph_database_db_instance: Fixes the IncorrectDBInstanceState when ModifyDBInstanceAccessWhiteList

GNUmakefile, alicloud/resource_alicloud_db_instance.go
=> resource/alicloud_db_instance: Removes the validateFunc for attribute connection_string_prefix

alicloud/connectivity/client.go, alicloud/connectivity/regions.go, alicloud/data_source_alicloud_maxcompute_projects.go, alicloud/data_source_alicloud_maxcompute_projects_test.go, alicloud/provider.go, alicloud/resource_alicloud_maxcompute_project.go, alicloud/resource_alicloud_maxcompute_project_test.go, alicloud/service_alicloud_maxcompute.go, website/docs/d/maxcompute_projects.html.markdown, website/docs/r/maxcompute_project.html.markdown
New Datasource `alicloud_maxcompute_projects`; resource/alicloud_maxcompute_project: Upgrade to a new version of OpenAPI
=>  New Datasource `alicloud_maxcompute_projects`; resource/alicloud_maxcompute_project: Upgrade to a new version of OpenAPI

alicloud/data_source_alicloud_cen_child_instance_route_entry_to_attachments_test.go, alicloud/data_source_alicloud_cen_transit_router_multicast_domain_associations.go, alicloud/data_source_alicloud_cen_transit_router_multicast_domain_members_test.go, alicloud/data_source_alicloud_ecs_elasticity_assurances.go, alicloud/data_source_alicloud_ecs_elasticity_assurances_test.go, alicloud/data_source_alicloud_threat_detection_honey_pots.go, alicloud/data_source_alicloud_threat_detection_honeypot_probes.go, alicloud/data_source_alicloud_threat_detection_log_shipper.go, alicloud/provider.go, alicloud/resource_alicloud_cen_transit_router_multicast_domain_association.go, alicloud/resource_alicloud_cen_transit_router_multicast_domain_peer_member_test.go, alicloud/resource_alicloud_ecs_elasticity_assurance.go, alicloud/resource_alicloud_ecs_elasticity_assurance_test.go, alicloud/resource_alicloud_threat_detection_honeypot_preset.go, alicloud/service_alicloud_common_test.go, alicloud/service_alicloud_ecs.go, website/docs/d/ecs_elasticity_assurances.html.markdown, website/docs/r/ecs_elasticity_assurance.html.markdown
New Resource `alicloud_ecs_elasticity_assurance`; 
New Datasource `alicloud_ecs_elasticity_assurances`;
=> New Resource `alicloud_ecs_elasticity_assurance`; New Datasource `alicloud_ecs_elasticity_assurances`;

alicloud/data_source_alicloud_oos_patch_baselines.go, alicloud/resource_alicloud_oos_patch_baseline.go, website/docs/d/oos_patch_baselines.html.markdown, website/docs/r/oos_patch_baseline.html.markdown
=> resource/alicloud_oos_patch_baseline: Update attribute operation_system valid value Centos to CentOS

alicloud/resource_alicloud_slb_load_balancer.go
=> resource/alicloud_slb_load_balancer: Supports valid value locked for attribute status

alicloud/resource_alicloud_image_import.go, website/docs/r/image_import.html.markdown
=> resource/alicloud_image_import: Fixes the Creating broken error when waiting the resource is available

alicloud/data_source_alicloud_oos_patch_baselines_test.go, alicloud/resource_alicloud_oos_patch_baseline_test.go
=> testcase: Improves the resource oos_patch_baseline testcases

alicloud/data_source_alicloud_db_instance_class_infos.go, alicloud/data_source_alicloud_db_instance_class_infos_test.go, alicloud/provider.go, website/docs/d/db_instance_class_infos.html.markdown
Query details of all specification for RDS instance
=> New Datasource data_source_alicloud_db_instance_class_infos ; Query details of all specification for RDS instance

alicloud/resource_alicloud_click_house_db_cluster.go, alicloud/resource_alicloud_click_house_db_cluster_test.go, website/docs/r/click_house_db_cluster.html.markdown
=> resource/alicloud_click_house_db_cluster: Add new attributes connection_string and  port

alicloud/data_source_alicloud_drds_instances.go, alicloud/data_source_alicloud_drds_instances_test.go, alicloud/resource_alicloud_drds_instance.go, alicloud/resource_alicloud_drds_instance_test.go, website/docs/d/drds_instances.html.markdown, website/docs/r/adb_db_cluster.html.markdown, website/docs/r/drds_instance.html.markdown
=> resource/alicloud_drds_instance: Add new attributes connection_string  and port

alicloud/data_source_alicloud_db_instance_class_infos.go, alicloud/data_source_alicloud_db_instance_class_infos_test.go, alicloud/resource_alicloud_graph_database_db_instance.go, alicloud/resource_alicloud_graph_database_db_instance_test.go, website/docs/r/graph_database_db_instance.html.markdown
=> resource/alicloud_graph_database_db_instance: Add new attributes connection_string and port

CHANGELOG.md, website/docs/d/alb_ascripts.html.markdown, website/docs/d/cen_inter_region_traffic_qos_queues.html.markdown, website/docs/d/cen_transit_router_multicast_domain_members.html.markdown, website/docs/d/cen_transit_router_multicast_domain_peer_members.html.markdown, website/docs/d/cen_transit_router_multicast_domain_sources.html.markdown, website/docs/r/adb_resource_group.html.markdown, website/docs/r/alb_ascript.html.markdown, website/docs/r/cen_inter_region_traffic_qos_queue.html.markdown, website/docs/r/cen_transit_router_multicast_domain_member.html.markdown, website/docs/r/cen_transit_router_multicast_domain_peer_member.html.markdown, website/docs/r/cen_transit_router_multicast_domain_source.html.markdown
docs: fix link; 
changeLog: Optimize content.
=> docs: fix link;  changeLog: Optimize content.

alicloud/data_source_alicloud_ebs_dedicated_block_storage_clusters_test.go, alicloud/data_source_alicloud_express_connect_virtual_physical_connections.go, alicloud/data_source_alicloud_express_connect_virtual_physical_connections_test.go, alicloud/data_source_alicloud_service_catalog_launch_options.go, alicloud/data_source_alicloud_service_catalog_product_as_end_users.go, alicloud/data_source_alicloud_service_catalog_product_as_end_users_test.go, alicloud/data_source_alicloud_service_catalog_product_versions_test.go, alicloud/data_source_alicloud_service_catalog_provisioned_products_test.go, alicloud/provider.go, alicloud/provider_test.go, alicloud/resource_alicloud_express_connect_virtual_physical_connection.go, alicloud/resource_alicloud_express_connect_virtual_physical_connection_test.go, alicloud/resource_alicloud_maxcompute_project.go, alicloud/service_alicloud_express_connect.go, website/docs/d/express_connect_virtual_physical_connections.html.markdown, website/docs/r/express_connect_virtual_physical_connection.html.markdown, website/docs/r/maxcompute_project.html.markdown
New Resource `alicloud_express_connect_virtual_physical_connection`;
New Datasource `alicloud_express_connect_virtual_physical_connections`;
=> New Resource `alicloud_express_connect_virtual_physical_connection`; New Datasource `alicloud_express_connect_virtual_physical_connections`;

website/docs/r/slb_load_balancer.html.markdown
doc/slb_load_balancer: fix content.
=> doc/slb_load_balancer: fix content.

alicloud/resource_alicloud_gpdb_elastic_instance.go, alicloud/resource_alicloud_gpdb_elastic_instance_test.go, alicloud/resource_alicloud_gpdb_instance.go, alicloud/resource_alicloud_gpdb_instance_test.go, website/docs/d/gpdb_instances.html.markdown, website/docs/r/gpdb_elastic_instance.html.markdown, website/docs/r/gpdb_instance.html.markdown
=> resource/alicloud_gpdb_instance: Add new attributes connection_string and port

alicloud/data_source_alicloud_event_bridge_service.go, alicloud/data_source_alicloud_express_connect_grant_rule_to_cens.go, alicloud/data_source_alicloud_express_connect_vbr_pconn_associations.go, alicloud/data_source_alicloud_express_connect_vbr_pconn_associations_test.go, alicloud/provider.go, alicloud/resource_alicloud_express_connect_grant_rule_to_cen.go, alicloud/resource_alicloud_express_connect_vbr_pconn_association.go, alicloud/resource_alicloud_express_connect_vbr_pconn_association_test.go, alicloud/service_alicloud_express_connect.go, website/docs/d/express_connect_vbr_pconn_associations.html.markdown, website/docs/r/express_connect_vbr_pconn_association.html.markdown
New Resource `alicloud_express_connect_vbr_pconn_association`;
New Datasource `alicloud_express_connect_vbr_pconn_associations`;
=> New Resource `alicloud_express_connect_vbr_pconn_association`; New Datasource `alicloud_express_connect_vbr_pconn_associations`;

alicloud/data_source_alicloud_instance_keywords.go, alicloud/data_source_alicloud_instance_keywords_test.go, alicloud/resource_alicloud_cr_namespace_test.go, alicloud/resource_alicloud_db_instance.go, alicloud/resource_alicloud_db_instance_test.go
=> resource/alicloud_db_instance: Fixes the InvalidStorage.Malformed error when updating the db_instance_storage_type

alicloud/resource_alicloud_alikafka_instance.go, alicloud/resource_alicloud_alikafka_instance_allowed_ip_attachment_test.go, alicloud/resource_alicloud_alikafka_instance_test.go, alicloud/service_alicloud_alikafka.go, website/docs/r/alikafka_instance.html.markdown
resource/alicloud_alikafka_instance: Support to upgrade prepaid instances.
=> resource/alicloud_alikafka_instance: Support to upgrade prepaid instances.

alicloud/resource_alicloud_elasticsearch_instance.go, alicloud/resource_alicloud_elasticsearch_instance_test.go, website/docs/r/elasticsearch_instance.html.markdown
=> resource/alicloud_elasticsearch_instance: Supports two attribute public_domain and public_port

alicloud/data_source_alicloud_event_bridge_service.go
=> datasource/alicloud_eventbridge_service: Adds retry policy when checking status is UP

alicloud/data_source_alicloud_ga_domains.go, alicloud/data_source_alicloud_ga_domains_test.go, alicloud/provider.go, alicloud/resource_alicloud_ebs_disk_replica_pair_test.go, alicloud/resource_alicloud_ga_domain.go, alicloud/resource_alicloud_ga_domain_test.go, alicloud/service_alicloud_ga.go, website/docs/d/ga_domains.html.markdown, website/docs/r/ga_domain.html.markdown
New Resource `alicloud_ga_domain`;
New Datasource `alicloud_ga_domains`;
=> New Resource `alicloud_ga_domain`; New Datasource `alicloud_ga_domains`;

alicloud/resource_alicloud_vpc_peer_connection_accepter.go
resource/alicloud_vpc_peer_connection_accepter: Add retry error code.
=> resource/alicloud_vpc_peer_connection_accepter: Add retry error code.

alicloud/resource_alicloud_log_project.go, alicloud/resource_alicloud_log_project_test.go, alicloud/service_alicloud_log.go, go.mod, go.sum, vendor/github.com/aliyun/aliyun-log-go-sdk/client_interface.go, vendor/github.com/aliyun/aliyun-log-go-sdk/client_project_policy.go, vendor/github.com/aliyun/aliyun-log-go-sdk/log_store.go, vendor/github.com/aliyun/aliyun-log-go-sdk/model.go, vendor/github.com/aliyun/aliyun-log-go-sdk/token_auto_update_client.go, vendor/modules.txt, website/docs/r/log_project.html.markdown
`resource/alicloud_log_project`: Support new attribute `policy`
=> `resource/alicloud_log_project`: Support new attribute `policy`

GNUmakefile, alicloud/resource_alicloud_ecs_network_interface.go
=> resource/alicloud_ecs_network_interface: Removes the limitation for private ip count

alicloud/resource_alicloud_nat_gateway.go
=> resource/alicloud_nat_gateway: Checking the status to be Available after invoking ModifyNatGatewayAttribute

alicloud/resource_alicloud_vpc_dhcp_options_set.go
resource/alicloud_vpc_dhcp_options_set: Fix UpdateDhcpOptionsSetAttribute operation status value verification.
=> resource/alicloud_vpc_dhcp_options_set: Fix UpdateDhcpOptionsSetAttribute operation status value verification.

alicloud/data_source_alicloud_log_projects.go, alicloud/data_source_alicloud_log_projects_test.go, website/docs/d/log_projects.html.markdown
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudLogProjectsDataSource -timeout=300m
=== RUN   TestAccAlicloudLogProjectsDataSource
--- PASS: TestAccAlicloudLogProjectsDataSource (31.69s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  32.852s
=> `datasource/alicloud_log_projects` add attribute `policy`

alicloud/resource_alicloud_event_bridge_rule.go
resource/alicloud_event_bridge_rule: Fix the problem that push_retry_strategy does not take effect when creating.
=> resource/alicloud_event_bridge_rule: Fix the problem that push_retry_strategy does not take effect when creating.

alicloud/data_source_alicloud_ga_custom_routing_endpoint_group_destinations.go, alicloud/data_source_alicloud_ga_custom_routing_endpoint_traffic_policies.go, alicloud/data_source_alicloud_ga_custom_routing_endpoints.go, alicloud/data_source_alicloud_ga_custom_routing_port_mappings.go, alicloud/data_source_alicloud_service_catalog_end_user_products.go, alicloud/data_source_alicloud_service_catalog_end_user_products_test.go, alicloud/provider.go, alicloud/resource_alicloud_dcdn_kv_namespace.go, alicloud/resource_alicloud_dcdn_kv_namespace_test.go, alicloud/resource_alicloud_ga_custom_routing_endpoint.go, alicloud/resource_alicloud_ga_custom_routing_endpoint_group.go, alicloud/resource_alicloud_ga_custom_routing_endpoint_group_destination.go, alicloud/resource_alicloud_ga_custom_routing_endpoint_traffic_policy.go, alicloud/service_alicloud_dcdn.go, website/docs/r/dcdn_kv_namespace.html.markdown
New Resource `alicloud_dcdn_kv_namespace`;
=> New Resource `alicloud_dcdn_kv_namespace`;

alicloud/data_source_alicloud_dcdn_kv_account.go, alicloud/data_source_alicloud_rds_collation_time_zones.go, alicloud/data_source_alicloud_rds_collation_time_zones_test.go, alicloud/provider.go, alicloud/resource_alicloud_dcdn_kv.go, alicloud/resource_alicloud_dcdn_kv_test.go, alicloud/service_alicloud_dcdn.go, website/docs/r/dcdn_kv.html.markdown
New Resource `alicloud_dcdn_kv`;
=> New Resource `alicloud_dcdn_kv`;

alicloud/data_source_alicloud_dts_instances.go, alicloud/data_source_alicloud_dts_instances_test.go, alicloud/provider.go, alicloud/resource_alicloud_dcdn_kv_namespace.go, alicloud/resource_alicloud_dts_instance.go, alicloud/resource_alicloud_dts_instance_test.go, alicloud/resource_alicloud_dts_subscription_job.go, alicloud/service_alicloud_dts.go, website/docs/d/dts_instances.html.markdown, website/docs/r/dts_instance.html.markdown, website/docs/r/dts_subscription_job.html.markdown
New Datasource `alicloud_dts_instances`;
New Resource `alicloud_dts_instance`;
=> New Datasource `alicloud_dts_instances`; New Resource `alicloud_dts_instance`;

alicloud/data_source_alicloud_bss_open_api_pricing_modules.go, alicloud/data_source_alicloud_threat_detection_instances.go, alicloud/data_source_alicloud_threat_detection_instances_test.go, alicloud/provider.go, alicloud/resource_alicloud_threat_detection_instance.go, alicloud/resource_alicloud_threat_detection_instance_test.go, alicloud/service_alicloud_threat_detection.go, website/docs/d/bss_open_api_pricing_modules.html.markdown, website/docs/d/threat_detection_instances.html.markdown, website/docs/r/threat_detection_instance.html.markdown
New Resource `alicloud_threat_detection_instance`; 
New Datasource `alicloud_threat_detection_instances`;
=> New Resource `alicloud_threat_detection_instance`; New Datasource `alicloud_threat_detection_instances`;

website/docs/r/dcdn_kv.html.markdown, website/docs/r/dcdn_kv_namespace.html.markdown
doc/dcdn_kv: Optimize content.
doc/dcdn_kv_namespace: Optimize content.
=> doc/dcdn_kv: Optimize content. doc/dcdn_kv_namespace: Optimize content.

website/docs/r/nlb_security_policy.html.markdown
doc/nlb_security_policy: Optimize content.
=> doc/nlb_security_policy: Optimize content.

alicloud/resource_alicloud_ram_policy.go
resource/alicloud_ram_policy: Fix errors that failed assertions.
=> resource/alicloud_ram_policy: Fix errors that failed assertions.

alicloud/diff_suppress_funcs.go, alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_cluster_test.go, alicloud/service_alicloud_polardb.go, website/docs/r/polardb_cluster.html.markdown
resource/alicloud_polardb_cluster: polardb support encryption with CMK
=> resource/alicloud_polardb_cluster: polardb support encryption with CMK

alicloud/data_source_alicloud_cr_vpc_endpoint_linked_vpcs.go, alicloud/data_source_alicloud_hbr_hana_backup_clients.go, alicloud/data_source_alicloud_rds_character_set_names.go, alicloud/data_source_alicloud_rds_character_set_names_test.go, alicloud/data_source_alicloud_waf_domains.go, alicloud/data_source_alicloud_wafv3_instances.go, alicloud/data_source_alicloud_wafv3_instances_test.go, alicloud/provider.go, alicloud/resource_alicloud_dcdn_kv.go, alicloud/resource_alicloud_ess_scaling_configuration.go, alicloud/resource_alicloud_hbr_server_backup_plan.go, alicloud/resource_alicloud_waf_certificate.go, alicloud/resource_alicloud_waf_certificate_test.go, alicloud/resource_alicloud_waf_domain.go, alicloud/resource_alicloud_waf_domain_test.go, alicloud/resource_alicloud_waf_instance.go, alicloud/resource_alicloud_waf_instance_test.go, alicloud/resource_alicloud_waf_protection_module.go, alicloud/resource_alicloud_waf_protection_module_test.go, alicloud/resource_alicloud_wafv3_instance.go, alicloud/resource_alicloud_wafv3_instance_test.go, alicloud/service_alicloud_waf_openapi.go, website/docs/d/wafv3_instances.html.markdown, website/docs/r/waf_certificate.html.markdown, website/docs/r/wafv3_instance.html.markdown
New Resource `alicloud_wafv3_instance`; 
New Datasource `alicloud_wafv3_instances`;
=> New Resource `alicloud_wafv3_instance`; New Datasource `alicloud_wafv3_instances`;

alicloud/data_source_alicloud_wafv3_domains.go, alicloud/data_source_alicloud_wafv3_domains_test.go, alicloud/provider.go, alicloud/resource_alicloud_instance.go, alicloud/resource_alicloud_waf_domain.go, alicloud/resource_alicloud_wafv3_domain.go, alicloud/resource_alicloud_wafv3_domain_test.go, alicloud/service_alicloud_waf_openapi.go, website/docs/d/wafv3_domains.html.markdown, website/docs/r/instance.html.markdown, website/docs/r/wafv3_domain.html.markdown
New Datasource `alicloud_wafv3_domains`; 
New Resource `alicloud_wafv3_domain`;
=> New Datasource `alicloud_wafv3_domains`; New Resource `alicloud_wafv3_domain`;

alicloud/data_source_alicloud_emrv2_clusters_test.go, alicloud/data_source_alicloud_wafv3_domains.go, alicloud/data_source_alicloud_wafv3_domains_test.go, alicloud/provider.go, alicloud/resource_alicloud_emrv2_cluster_test.go, alicloud/resource_alicloud_instance.go, alicloud/resource_alicloud_waf_domain.go, alicloud/resource_alicloud_wafv3_domain.go, alicloud/resource_alicloud_wafv3_domain_test.go, alicloud/service_alicloud_waf_openapi.go, website/docs/d/wafv3_domains.html.markdown, website/docs/r/wafv3_domain.html.markdown
New Resource `alicloud_wafv3_domain`;
New Datasource `alicloud_wafv3_domains`;
=> New Resource `alicloud_wafv3_domain`; New Datasource `alicloud_wafv3_domains`;

alicloud/resource_alicloud_common_bandwidth_package_attachment.go, alicloud/resource_alicloud_common_bandwidth_package_attachment_test.go, website/docs/r/common_bandwidth_package_attachment.html.markdown
resource/alicloud_common_bandwidth_package_attachment: Support new attribute `cancel_common_bandwidth_package_ip_bandwidth `.
=> resource/alicloud_common_bandwidth_package_attachment: Support new attribute `cancel_common_bandwidth_package_ip_bandwidth `.

CHANGELOG.md, website/docs/r/router_interface.html.markdown
doc/router_interface: Optimize content.
CHANGELOG: Optimize content.
=> doc/router_interface: Optimize content. CHANGELOG: Optimize content.

alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_endpoint.go, alicloud/resource_alicloud_polardb_endpoint_test.go, alicloud/service_alicloud_polardb.go, website/docs/r/polardb_endpoint.html.markdown
resource/alicloud_polardb_endpoint: polardb support endpoint db_endpoint_description
=> resource/alicloud_polardb_endpoint: polardb support endpoint db_endpoint_description

alicloud/resource_alicloud_instance.go, alicloud/resource_alicloud_instance_test.go, website/docs/r/instance.html.markdown
resource/alicloud_instance: Support new attribute `dedicated_host_id`.
=> resource/alicloud_instance: Support new attribute `dedicated_host_id`.

alicloud/connectivity/client.go, alicloud/connectivity/config.go, alicloud/connectivity/regions.go, alicloud/data_source_alicloud_eflo_vpds.go, alicloud/data_source_alicloud_eflo_vpds_test.go, alicloud/provider.go, alicloud/resource_alicloud_eflo_vpd.go, alicloud/resource_alicloud_eflo_vpd_test.go, alicloud/service_alicloud_eflo.go, website/docs/d/eflo_vpds.html.markdown, website/docs/r/eflo_vpd.html.markdown
New Datasource `alicloud_eflo_vpds`;
New Resource `alicloud_eflo_vpd`;
=> New Datasource `alicloud_eflo_vpds`; New Resource `alicloud_eflo_vpd`;

alicloud/data_source_alicloud_dcdn_waf_rules.go, alicloud/data_source_alicloud_dcdn_waf_rules_test.go, alicloud/provider.go, alicloud/resource_alicloud_dcdn_waf_policy.go, alicloud/resource_alicloud_dcdn_waf_rule.go, alicloud/resource_alicloud_dcdn_waf_rule_test.go, alicloud/service_alicloud_dcdn.go, website/docs/d/dcdn_waf_rules.html.markdown, website/docs/r/dcdn_waf_policy.html.markdown, website/docs/r/dcdn_waf_rule.html.markdown
New Resource `alicloud_dcdn_waf_rule`;
New Datasource `alicloud_dcdn_waf_rules`;
=> New Resource `alicloud_dcdn_waf_rule`; New Datasource `alicloud_dcdn_waf_rules`;

alicloud/resource_alicloud_resource_manager_resource_directory.go, alicloud/resource_alicloud_resource_manager_resource_directory_test.go, website/docs/r/dns_record.html.markdown, website/docs/r/resource_manager_resource_directory.html.markdown
resource/alicloud_resource_manager_resource_directory: Support new attribute `member_deletion_status`.
=> resource/alicloud_resource_manager_resource_directory: Support new attribute `member_deletion_status`.

alicloud/resource_alicloud_instance.go, alicloud/resource_alicloud_instance_test.go, website/docs/r/instance.html.markdown
=> resource/alicloud_instance: Fixes the user data diff error when using base64 encoding

alicloud/connectivity/regions.go, alicloud/data_source_alicloud_actiontrail_global_events_storage_region.go, alicloud/data_source_alicloud_actiontrail_global_events_storage_region_test.go, alicloud/data_source_alicloud_eflo_vpds_test.go, alicloud/provider.go, alicloud/resource_alicloud_actiontrail_global_events_storage_region.go, alicloud/resource_alicloud_actiontrail_global_events_storage_region_test.go, alicloud/resource_alicloud_drds_instance.go, alicloud/resource_alicloud_resource_manager_resource_directory_test.go, alicloud/service_alicloud_actiontrail.go, website/docs/d/actiontrail_global_events_storage_region.html.markdown, website/docs/r/actiontrail_global_events_storage_region.html.markdown
New Datasource `alicloud_actiontrail_global_events_storage_region`;
New Resource `alicloud_actiontrail_global_events_storage_region`;
=> New Datasource `alicloud_actiontrail_global_events_storage_region`; New Resource `alicloud_actiontrail_global_events_storage_region`;

alicloud/data_source_alicloud_vpn_connections.go, alicloud/data_source_alicloud_vpn_connections_test.go, website/docs/d/vpn_connections.html.markdown, website/docs/r/vpn_connection.html.markdown
datasource/alicloud_vpn_connections: Supports new output `enable_dpd` and `enable_nat_traversal`.
=> datasource/alicloud_vpn_connections: Supports new output `enable_dpd` and `enable_nat_traversal`.

alicloud/resource_alicloud_hbase_instance.go, website/docs/r/hbase_instance.html.markdown
- cold_storage_size max size from 1000000 to 100000000
=> resource/alicloud_hbase_instance: Enlarges the cold_storage_size max value to 100000000

alicloud/data_source_alicloud_hbase_instances_test.go, alicloud/resource_alicloud_hbase_instance_test.go, examples/hbase/variables.tf, website/docs/d/hbase_instances.html.markdown, website/docs/r/hbase_instance.html.markdown
- run test,  hbase.sn1.large -> hbase.sn2.2xlarge
=> testcase: Improves the resource alicloud_hbase_instance testcases

alicloud/resource_alicloud_ecs_disk.go, alicloud/resource_alicloud_ecs_disk_attachment.go, website/docs/r/ecs_disk_attachment.html.markdown
=> resource/alicloud_ecs_disk: Remvoes the waiting after creating; resource/alicloud_ecs_disk_attachment: Shortens the pending time after creating

alicloud/resource_alicloud_oss_bucket_object.go, alicloud/resource_alicloud_oss_bucket_object_test.go, website/docs/r/oss_bucket_object.html.markdown
=> resource/alicloud_oss_bucket_object: Remvoes the server_side_encrypt on argument default value.

website/docs/index.html.markdown
doc/index: Optimize `endpoints` attribute description.
=> doc/index: Optimize `endpoints` attribute description.

alicloud/resource_alicloud_bastionhost_instance.go, alicloud/service_alicloud_bss_open_api.go, alicloud/service_alicloud_yundun_bastionhost.go, scripts/schema_test.go
=> resource/alicloud_bastionhost_instance: Fixes the bastion host not found error when using intrenational account

alicloud/data_source_alicloud_arms_prometheis.go, alicloud/provider.go, alicloud/resource_alicloud_arms_prometheus_test.go, alicloud/resource_alicloud_cen_transit_route_table_aggregation.go, alicloud/resource_alicloud_oos_default_patch_baseline.go, alicloud/resource_alicloud_oos_default_patch_baseline_test.go, alicloud/resource_alicloud_oos_patch_baseline.go, alicloud/resource_alicloud_security_group_rule.go, alicloud/service_alicloud_oos.go, website/docs/r/oos_default_patch_baseline.html.markdown
New Resource `alicloud_oos_default_patch_baseline`;
=> New Resource `alicloud_oos_default_patch_baseline`;

alicloud/resource_alicloud_ram_policy.go, scripts/integration.go
=> resource/alicloud_ram_policy: Fixes the nil pointer error when getting policy versions

website/docs/r/amqp_instance.html.markdown
=> docs/alicloud_amqp_instance: Removes the note for no supporting international account

alicloud/connectivity/client.go, alicloud/connectivity/config.go, alicloud/connectivity/regions.go, alicloud/data_source_alicloud_ocean_base_instances.go, alicloud/data_source_alicloud_ocean_base_instances_test.go, alicloud/provider.go, alicloud/resource_alicloud_ocean_base_instance.go, alicloud/resource_alicloud_ocean_base_instance_test.go, alicloud/service_alicloud_ocean_base_pro.go, website/docs/d/ocean_base_instances.html.markdown, website/docs/r/ocean_base_instance.html.markdown
New Resource `alicloud_ocean_base_instance`;
New Datasource `alicloud_ocean_base_instances`;
=> New Resource `alicloud_ocean_base_instance`; New Datasource `alicloud_ocean_base_instances`;

.github/workflows/acctest-terraform-basic.yml, alicloud/data_source_alicloud_amqp_instances.go, alicloud/resource_alicloud_alidns_instance.go, alicloud/resource_alicloud_alidns_instance_test.go, alicloud/resource_alicloud_amqp_instance.go, alicloud/resource_alicloud_amqp_instance_test.go, alicloud/resource_alicloud_bastionhost_instance.go, alicloud/resource_alicloud_bastionhost_instance_test.go, alicloud/service_alicloud_alidns.go, alicloud/service_alicloud_bss_open_api.go, website/docs/r/alidns_instance.html.markdown
=> resource/alicloud_alidns_instance: Fixes the NotApplicable error when operating the resource using international account

alicloud/data_source_alicloud_polardb_accounts_test.go, alicloud/data_source_alicloud_polardb_clusters_test.go, alicloud/data_source_alicloud_polardb_databases_test.go, alicloud/data_source_alicloud_polardb_endpoints_test.go, alicloud/data_source_alicloud_polardb_global_database_networks_test.go, alicloud/data_source_alicloud_polardb_node_classes.go, alicloud/data_source_alicloud_polardb_node_classes_test.go, alicloud/resource_alicloud_polardb_account_privilege_test.go, alicloud/resource_alicloud_polardb_account_test.go, alicloud/resource_alicloud_polardb_backup_policy_test.go, alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_cluster_test.go, alicloud/resource_alicloud_polardb_database_test.go, alicloud/resource_alicloud_polardb_endpoint_address_test.go, alicloud/resource_alicloud_polardb_global_database_network_test.go, alicloud/service_alicloud_polardb.go, website/docs/r/polardb_cluster.html.markdown
resource/alicloud_polardb_cluster: polardb support cluster category SENormal
=> resource/alicloud_polardb_cluster: polardb support cluster category SENormal

alicloud/resource_alicloud_eip_address.go, alicloud/resource_alicloud_eip_association.go, alicloud/resource_alicloud_eip_association_test.go, alicloud/resource_alicloud_vpc_ipv4_gateway.go, alicloud/service_alicloud_vpc.go, website/docs/r/eip_association.html.markdown, website/docs/r/vpc_ipv4_gateway.html.markdown
resource/alicloud_eip_association: Adds new attribute vpc_id.
=> resource/alicloud_eip_association: Adds new attribute vpc_id.

alicloud/connectivity/client.go, alicloud/connectivity/config.go, alicloud/connectivity/regions.go, alicloud/data_source_alicloud_chatbot_agents.go, alicloud/data_source_alicloud_chatbot_agents_test.go, alicloud/provider.go, alicloud/resource_alicloud_chatbot_publish_task.go, alicloud/resource_alicloud_chatbot_publish_task_test.go, alicloud/resource_alicloud_tag_policy_test.go, alicloud/service_alicloud_chatbot.go, scripts/integration.go, website/docs/d/chatbot_agents.html.markdown, website/docs/r/actiontrail_global_events_storage_region.html.markdown, website/docs/r/chatbot_publish_task.html.markdown
New Resource `alicloud_chatbot_publish_task`;
New Datasource `alicloud_chatbot_agents`;
=> New Resource `alicloud_chatbot_publish_task`; New Datasource `alicloud_chatbot_agents`;

alicloud/resource_alicloud_mongodb_instance.go, alicloud/resource_alicloud_mongodb_instance_test.go, alicloud/resource_alicloud_ocean_base_instance_test.go, alicloud/resource_alicloud_tag_policy_test.go, alicloud/service_alicloud_mongodb.go, scripts/integration.go, website/docs/r/mongodb_instance.html.markdown
resource/alicloud_mongodb_instance: Adds new attribute `parameters`.
=> resource/alicloud_mongodb_instance: Adds new attribute `parameters`.

alicloud/data_source_alicloud_service_catalog_portfolios.go, alicloud/data_source_alicloud_service_catalog_portfolios_test.go, alicloud/provider.go, alicloud/resource_alicloud_service_catalog_portfolio.go, alicloud/resource_alicloud_service_catalog_portfolio_test.go, alicloud/service_alicloud_servicecatalog.go, website/docs/d/service_catalog_portfolios.html.markdown, website/docs/r/service_catalog_portfolio.html.markdown
New Datasource `alicloud_service_catalog_portfolios`;
New Resource `alicloud_service_catalog_portfolio`;
=> New Datasource `alicloud_service_catalog_portfolios`; New Resource `alicloud_service_catalog_portfolio`;

alicloud/resource_alicloud_emrv2_cluster.go, alicloud/resource_alicloud_emrv2_cluster_test.go, alicloud/service_alicloud_common_test.go, website/docs/d/emr_clusters.html.markdown, website/docs/r/emr_cluster.html.markdown, website/docs/r/emrv2_cluster.html.markdown
=> resource/alicloud_emrv2_cluster: supported emr cluster data disk encrypted

alicloud/data_source_alicloud_eflo_subnets.go, alicloud/data_source_alicloud_eflo_subnets_test.go, alicloud/provider.go, alicloud/resource_alicloud_eflo_subnet.go, alicloud/resource_alicloud_eflo_subnet_test.go, alicloud/service_alicloud_eflo.go, website/docs/d/eflo_subnets.html.markdown, website/docs/r/eflo_subnet.html.markdown
New Datasource `alicloud_eflo_subnets`;
New Resource `alicloud_eflo_subnet`;
=> New Datasource `alicloud_eflo_subnets`; New Resource `alicloud_eflo_subnet`;

alicloud/connectivity/regions.go, alicloud/diff_suppress_funcs.go, alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_cluster_test.go, alicloud/service_alicloud_polardb.go, website/docs/r/polardb_cluster.html.markdown
resource/alicloud_polardb_cluster: polardb support cluster serverless
=> resource/alicloud_polardb_cluster: polardb support cluster serverless

alicloud/resource_alicloud_nlb_listener.go, alicloud/service_alicloud_common_test.go, scripts/integration.go, website/docs/r/nlb_listener.html.markdown
=> resource/alicloud_nlb_listener: Removes the limition for attribute security_policy_id and supports setting custom security policies

alicloud/service_alicloud_pvtz.go
=> resource/alicloud_pvtz_zone_record: Fixes the panic error when record id value out of range

alicloud/resource_alicloud_cloud_firewall_instance.go, website/docs/r/cloud_firewall_instance.html.markdown
=> resource/alicloud_cloud_firewall_instance: Attribute period supports setting 1 and 3

alicloud/provider.go, alicloud/resource_alicloud_alb_rule.go, alicloud/resource_alicloud_cen_traffic_marking_policy.go, alicloud/resource_alicloud_nlb_server_group.go, alicloud/resource_alicloud_ram_account_password_policy.go, alicloud/resource_alicloud_vpc.go, alicloud/validators.go, alicloud/validators_test.go
=> validation: Adds env variable TF_SKIP_RESOURCE_SCHEMA_VALIDATION to support skip resource attribute limitation

alicloud/resource_alicloud_db_instance.go, alicloud/resource_alicloud_db_instance_test.go
=> resource/alicloud_db_instance: Improves the limition for attribute validation

alicloud/resource_alicloud_forward_entry.go
=> resource/alicloud_forward_entry: Fixes the TaskConflict error when creating the resource

alicloud/provider.go, alicloud/resource_alicloud_vpc_ipv4_gateway.go, alicloud/resource_alicloud_vpc_ipv4_gateway_test.go, alicloud/service_alicloud_vpc_v2.go, website/docs/r/vpc_ipv4_gateway.html.markdown
=> resource/alicloud_vpc_ipv4_gateway: Adds new attribute resource_group_id, tags, create_time, ipv4_gateway_id, ipv4_gateway_route_table_id.

alicloud/service_alicloud_rds.go
…InstanceEndpoints interface error code
=> resource/alicloud_rds_db_instance_endpoint_address:fix the DescribeDBInstanceEndpoints interface error code

alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_cluster_test.go, website/docs/r/polardb_cluster.html.markdown
…type、from_time_service、planned_start_time、planned_end_timeq
=> resource/alicloud_polardb_cluster: Adds new attribute upgrade_type, from_time_service, planned_start_time and planned_end_time

.github/workflows/pull_requests.yml
=> ci: checking the pull-requests title whether contains all of added and modified files

alicloud/connectivity/regions.go, alicloud/resource_alicloud_polardb_backup_policy.go, alicloud/resource_alicloud_polardb_backup_policy_test.go, alicloud/service_alicloud_polardb.go, website/docs/r/polardb_backup_policy.html.markdown
resource/alicloud_polardb_backup_policy: polardb support backup policy
=> resource/alicloud_polardb_backup_policy: polardb support backup policy

alicloud/resource_alicloud_common_bandwidth_package.go, alicloud/resource_alicloud_common_bandwidth_package_test.go, website/docs/r/common_bandwidth_package.html.markdown
=> resource/alicloud_common_bandwidth_package: Reset the default value to PayByTraffic

alicloud/resource_alicloud_resource_manager_account.go
=> resource/alicloud_resource_manager_account: Fixes the ConcurrentCallNotSupported error when creating it

alicloud/data_source_alicloud_rds_slots.go, alicloud/resource_alicloud_db_instance.go, alicloud/resource_alicloud_rds_ddr_instance.go, alicloud/service_alicloud_rds.go, website/docs/d/rds_slots.html.markdown, website/docs/r/db_instance.html.markdown, website/docs/r/rds_ddr_instance.html.markdown
…ce: add retry.resource/alicloud_rds_ddr_instance: add retry.
=> data-source/alicloud_rds_slots: add retry;resource/alicloud_db_instance: add retry;resource/alicloud_rds_ddr_instance: add retry.

alicloud/resource_alicloud_lindorm_instance.go, website/docs/r/lindorm_instance.html.markdown
=> resource/alicloud_lindorm_instance: Enlarges the cold_storage max value to 1000000

alicloud/resource_alicloud_rds_account.go, alicloud/resource_alicloud_rds_backup.go, alicloud/resource_alicloud_rds_clone_db_instance.go
resource/alicloud_rds_clone_db_instance: add retry; resource/alicloud_rds_account: add retry; resource/alicloud_rds_backup: add retry.
=> resource/alicloud_rds_clone_db_instance: add retry; resource/alicloud_rds_account: add retry; resource/alicloud_rds_backup: add retry.

alicloud/provider.go, website/docs/index.html.markdown
=> provider: enlarges the configure parameter configuration_source value  length to 128

alicloud/resource_alicloud_ess_scaling_configuration.go, alicloud/resource_alicloud_ess_scaling_configuration_test.go, ci/pull-request.yml, website/docs/r/ess_scaling_configuration.html.markdown
=> resource/alicloud_ess_scaling_configuration: fixes the ServiceUnavailable error when updating the data_disk

alicloud/resource_alicloud_db_database.go, alicloud/resource_alicloud_rds_db_proxy.go, alicloud/resource_alicloud_rds_db_proxy_test.go, alicloud/resource_alicloud_rds_upgrade_db_instance.go, alicloud/resource_alicloud_rds_upgrade_db_instance_test.go, alicloud/service_alicloud_rds.go, website/docs/r/rds_db_proxy.html.markdown, website/docs/r/rds_upgrade_db_instance.html.markdown
resource/alicloud_db_database: add retry; resource/alicloud_rds_upgrade_db_instance: add retry; resource/alicloud_rds_db_proxy: add retry and fix bug.
=> resource/alicloud_db_database: add retry; resource/alicloud_rds_upgrade_db_instance: add retry; resource/alicloud_rds_db_proxy: add retry and fix bug.

alicloud/common.go, alicloud/resource_alicloud_lindorm_instance.go, alicloud/resource_alicloud_lindorm_instance_test.go, scripts/consistency_check.go
=> resource/alicloud_lindorm_instance: fixes the panic error caused by no setting instance_storage

alicloud/resource_alicloud_polardb_backup_policy.go
resource/alicloud_polardb_backup_policy: support bug fixed
=> resource/alicloud_polardb_backup_policy: fix updating attribute data_level1_backup_retention_period does not work bug

alicloud/resource_alicloud_bastionhost_instance.go, website/docs/r/bastionhost_instance.html.markdown
=> resource/alicloud_bastionhost_instance: Fixes the ResourceNotFound error when using international account

alicloud/resource_alicloud_rds_upgrade_db_instance.go, alicloud/resource_alicloud_rds_upgrade_db_instance_test.go
resource/alicloud_rds_upgrade_db_instance: fixes bugs in enabling SSL and modifying resource groups
=> resource/alicloud_rds_upgrade_db_instance: fixes bugs in enabling SSL and modifying resource groups

alicloud/resource_alicloud_adb_db_cluster.go, alicloud/service_alicloud_adb.go
=> resource/alicloud_adb_db_cluster: Improves the setting db_cluster_version by api DescribeDBClusterAttribute

alicloud/resource_alicloud_db_instance.go, alicloud/resource_alicloud_db_instance_test.go, website/docs/r/db_instance.html.markdown
resource/alicloud_db_instance: fixes serverless enable disable delete protection
=> resource/alicloud_db_instance: fixes serverless enable disable delete protection

alicloud/resource_alicloud_db_instance.go, alicloud/resource_alicloud_db_instance_test.go
resource/alicloud_db_instance: fixes setting table name case sensitive field db_is_ignore_case invalid
=> resource/alicloud_db_instance: fixes setting table name case sensitive field db_is_ignore_case invalid

alicloud/provider.go, alicloud/resource_alicloud_eipanycast_anycast_eip_address.go, alicloud/resource_alicloud_eipanycast_anycast_eip_address_test.go, alicloud/service_alicloud_eipanycast_v2.go, website/docs/r/eipanycast_anycast_eip_address.html.markdown
=> resource/alicloud_eipanycast_anycast_eip_address: add new attributes: tags, create_time.

alicloud/resource_alicloud_oss_bucket.go, website/docs/r/oss_bucket.html.markdown
optional required. 2.fix oss_bucket.html.markdown  warning.``
=> resource/alicloud_oss_bucket: corrects the transitions.storage_class to required

alicloud/common.go, alicloud/provider.go, alicloud/resource_alicloud_ecs_network_interface_test.go, alicloud/resource_alicloud_ecs_snapshot_test.go, alicloud/resource_alicloud_instance.go, alicloud/resource_alicloud_instance_test.go, alicloud/resource_alicloud_pvtz_zone_test.go, alicloud/validators.go, alicloud/validators_test.go, ci/sweeper.yml, website/docs/r/instance.html.markdown
=> resource/alicloud_instance: Fixes the attribute auto_release_time inconsistent issue, and Improves the user_data setting

alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_cluster_test.go, alicloud/service_alicloud_polardb.go, website/docs/r/polardb_cluster.html.markdown
=> resource/alicloud_polardb_cluster: poladb db support upgrad minor version

alicloud/resource_alicloud_nas_mount_target.go, alicloud/resource_alicloud_nas_mount_target_test.go, examples/nas-mount-target/main.tf, website/docs/r/nas_mount_target.html.markdown
resource_alicloud_nas_mount_target_test.go
测试通用型NAS -- TestAccAlicloudNASMountTarget_basic
测试极速型NAS -- TestAccAlicloudNasExtremeMountTarget_basic
Terrform 命令验证
terraform init
terraform plan
terraform apply
terraform destroy
=> resource/alicloud_nas_mount_target: add parameter vpc_id, network_type for completing the API parameters.

website/docs/r/fc_service.html.markdown, website/docs/r/fcv2_function.html.markdown
Add log index for fc service/function guide doc
=> docs: add log index for fc service/function doc

.github/workflows/acctest-terraform-lint.yml.yml, GNUmakefile, alicloud/connectivity/client.go, alicloud/errors.go, alicloud/provider.go, alicloud/resource_alicloud_resource_manager_service_linked_role.go, alicloud/resource_alicloud_resource_manager_service_linked_role_test.go, alicloud/service_alicloud_cs.go, alicloud/service_alicloud_ram.go, alicloud/service_alicloud_resource_manager.go, go.sum
=> resource/alicloud_resource_manager_service_linked_role: Waiting for the resource deleting finished

alicloud/data_source_alicloud_cdn_service.go
=> data-source/alicloud_cdn_service: Fixes the CdnServiceNotFoundError error

.github/workflows/document-example.yml, ci/tasks/docs-example-provider.tf, ci/tasks/docs-example.sh, ci/tasks/docs-example.yml, scripts/docs_example_check.go
Added file： .github/workflows/document-example.yml,ci/tasks/docs-example.sh,ci/tasks/docs-example-provider.tf,scripts/docs_example_check.go,ci/tasks/docs-example.yml
=> ci: Adds the docs example checks

alicloud/provider.go, alicloud/resource_alicloud_common_bandwidth_package_attachment.go, alicloud/resource_alicloud_common_bandwidth_package_attachment_test.go, alicloud/service_alicloud_cbwp_v2.go, alicloud/service_alicloud_vpc.go, website/docs/r/common_bandwidth_package_attachment.html.markdown
=> resource/alicloud_common_bandwidth_package_attachment: Improves the resource creating and avoid happened IpInstanceId.AlreadyInBandwidthPackage error

alicloud/data_source_alicloud_fc_service.go, website/docs/d/fc_service.html.markdown
=> data-source/alicloud_fc_service: Improves the response checking when the account is opened

alicloud/resource_alicloud_ess_scalinggroup_vserver_groups.go
=> resource/alicloud_ess_scalinggroup: Fixes the BackendServer.configuring error when attaching vserver groups

alicloud/resource_alicloud_dts_synchronization_job.go, alicloud/resource_alicloud_dts_synchronization_job_test.go, website/docs/r/dts_synchronization_job.html.markdown
=> resource/alicloud_dts_synchronization_job: Fixes the DTS.Msg.OperationDenied.JobStatusModifying error when updating it

alicloud/provider.go, alicloud/resource_alicloud_slb_listener.go, alicloud/resource_alicloud_slb_listener_test.go, website/docs/d/kvstore_permission.html.markdown, website/docs/r/slb_listener.html.markdown
=> resource/alicloud_slb_listener: Fixes the VServerGroupId does not exist error when updating listener attribute

alicloud/resource_alicloud_kvstore_instance.go
=> resource/alicloud_kvstore_instance: Ignores the period diff when payment type is PostPaid

alicloud/resource_alicloud_db_backup_policy.go, alicloud/resource_alicloud_db_backup_policy_test.go
resource/alicloud_db_backup_policy: Fixed setting for turning off log backup
=> resource/alicloud_db_backup_policy: Fixed setting for turning off log backup

alicloud/errors.go, alicloud/resource_alicloud_cs_kubernetes_node_pool.go, alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go, alicloud/service_alicloud_cs.go, website/docs/r/cs_kubernetes_node_pool.html.markdown
=> resource/alicloud_cs_kubernetes_node_pool: Improves the resource not found checking for the error code ErrorClusterNotFound

alicloud/connectivity/regions.go, alicloud/resource_alicloud_log_store.go, alicloud/resource_alicloud_log_store_test.go, website/docs/r/log_store.html.markdown
`resource/alicloud_log_store` make `mode` changable
=> resource/alicloud_log_store: make  attribute mode changable

alicloud/provider.go, alicloud/resource_alicloud_db_instance.go, alicloud/resource_alicloud_db_instance_test.go, website/docs/r/db_instance.html.markdown
=> resource/alicloud_db_instance: Ignore ssl_action setting for serverless instance

alicloud/resource_alicloud_instance.go, alicloud/resource_alicloud_instance_test.go
=> resource/alicloud_instance: Fixes the InvalidParameter error when modifying the instance auto_renew attribute

alicloud/data_source_alicloud_cs_kubernetes_addons.go, alicloud/resource_alicloud_cs_kubernetes_addon.go, alicloud/service_alicloud_cs.go, website/docs/d/cs_kubernetes_addons.html.markdown
resource/alicloud_cs_kubernetes_addon: Fix addon resource status check bug.
data-source/alicloud_cs_kubernetes_addons: Sort results.
=>  resource/alicloud_cs_kubernetes_addon: Fix addon resource status check bug; data-source/alicloud_cs_kubernetes_addons: Sort results.

alicloud/diff_suppress_funcs.go, alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_cluster_test.go, alicloud/service_alicloud_polardb.go, website/docs/r/polardb_cluster.html.markdown
=> resource/alicloud_polardb_cluster: modify support setting lower_case_table_names parameter is zero

alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_cluster_test.go, website/docs/r/polardb_cluster.html.markdown
resource/alicloud_polardb_cluster: modify  support hot_replica_mode;alicloud/resource_alicloud_polardb_cluster_test: modify support hot_replica_mode
=> resource/alicloud_polardb_cluster: modify  support hot_replica_mode;alicloud/resource_alicloud_polardb_cluster_test: modify support hot_replica_mode

alicloud/resource_alicloud_cms_site_monitor_test.go, website/docs/r/cms_site_monitor.html.markdown
=> docs/alicloud_cms_site_monitor: Imporves the example by adding options_json parameter

alicloud/connectivity/regions.go, alicloud/resource_alicloud_ecs_network_interface.go, alicloud/resource_alicloud_ecs_network_interface_test.go, alicloud/service_alicloud_ecs.go, website/docs/r/ecs_network_interface.html.markdown
resource/alicloud_ecs_network_interface: Add ipv4 prefix
=> resource/alicloud_ecs_network_interface: Add ipv4 prefix

alicloud/resource_alicloud_polardb_cluster.go
resource/alicloud_polardb_cluster: Add maintain_time check and modification cluster protection lock
=> resource/alicloud_polardb_cluster: Add maintain_time check, modification cluster protection lock

alicloud/resource_alicloud_polardb_cluster.go
resource/alicloud_polardb_cluster: modify tde and connection_string bug fixed
=> resource/alicloud_polardb_cluster: modify tde and connection_string bug fixed

alicloud/resource_alicloud_polardb_backup_policy.go, alicloud/resource_alicloud_polardb_backup_policy_test.go, website/docs/r/polardb_backup_policy.html.markdown
resource/alicloud_polardb_backup_policy: Data_level1_backup_retention_period support 3-30
=> resource/alicloud_polardb_backup_policy: Data_level1_backup_retention_period support 3-30

alicloud/resource_alicloud_cs_kubernetes_permissions.go, alicloud/resource_alicloud_cs_kubernetes_permissions_test.go, website/docs/r/cs_kubernetes_permissions.html.markdown
This reverts commit 0b7da5a874cdbcde996f4030f6581f37b422703e.
=> Revert "resource/alicloud_cs_kubernetes_permissions: fix create, read, update, delete bug; support import"

website/docs/r/rds_upgrade_db_instance.html.markdown
=> docs: fix the docs example

alicloud/resource_alicloud_eci_container_group.go, alicloud/resource_alicloud_eci_container_group_test.go, website/docs/r/eci_container_group.html.markdown
resource/alicloud_eci_container_group: add termination_grace_period_seconds; add containers.lifecycle_pre_stop_handler_exec
=> resource/alicloud_eci_container_group: add termination_grace_period_seconds; add containers.lifecycle_pre_stop_handler_exec

alicloud/resource_alicloud_ess_eci_scaling_configuration.go, alicloud/resource_alicloud_ess_eci_scaling_configuration_test.go, website/docs/r/ess_eci_scaling_configuration.html.markdown
=> resource/alicloud_ess_eci_scaling_configuration: Add lifecycle_pre_stop_handler_execs

alicloud/resource_alicloud_eci_container_group.go, alicloud/resource_alicloud_eci_container_group_test.go, website/docs/r/eci_container_group.html.markdown
=> resource/alicloud_eci_container_group: add spot_strategy; add spot_price_limit

alicloud/diff_suppress_funcs.go, alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_cluster_test.go, alicloud/service_alicloud_common_test.go, alicloud/service_alicloud_polardb.go, website/docs/r/polardb_cluster.html.markdown
PolarDB MySQL supports specifying the small version for upgrade through Terraform
=> resource/alicloud_polardb_cluster: specify minor version upgrade

alicloud/resource_alicloud_ess_eci_scaling_configuration.go, alicloud/resource_alicloud_ess_eci_scaling_configuration_test.go, website/docs/r/ess_eci_scaling_configuration.html.markdown
…ne_seconds and container_group_name constriction
=> resource/alicloud_ess_eci_scaling_configuration: update active_deadline_seconds and container_group_name constriction

alicloud/resource_alicloud_eci_container_group.go, alicloud/resource_alicloud_eci_container_group_test.go
=> resource/alicloud_eci_container_group: fix auto_match_image_cache

alicloud/resource_alicloud_db_instance.go
resource/alicloud_db_instance: Fix RDS operation timeout.
=> resource/alicloud_db_instance: Fix RDS operation timeout.

alicloud/resource_alicloud_oss_bucket_replication.go, alicloud/resource_alicloud_oss_bucket_replication_test.go, website/docs/r/oss_bucket_replication.html.markdown
=> resource/alicloud_oss_bucket_replication: Fix rule-id bug.

alicloud/resource_alicloud_polardb_cluster.go, alicloud/service_alicloud_polardb.go
resource/alicloud_polardb_cluster: modify the upgrade_type wait cluster maxscale proxy status
=> resource/alicloud_polardb_cluster: modify the upgrade_type wait cluster maxscale proxy status

alicloud/resource_alicloud_ess_attachment.go, alicloud/resource_alicloud_ess_attachment_test.go, website/docs/r/ess_attachment.html.markdown
…e_hook and load_balancer_weights
=>  resource/alicloud_ess_attachment: add attribute of entrusted lifecycle_hook and load_balancer_weights

alicloud/resource_alicloud_ess_scaling_configuration.go, alicloud/resource_alicloud_ess_scaling_configuration_test.go, website/docs/r/ess_scaling_configuration.html.markdown
…e excluded_instance_types and architectures attributes of instance_pattern_info
=> resource/alicloud_ess_scaling_configuration: add burstable_performance excluded_instance_types and architectures attributes of instance_pattern_info

alicloud/data_source_alicloud_cs_cluster_credential.go, alicloud/data_source_alicloud_cs_cluster_credential_test.go, alicloud/data_source_alicloud_cs_edge_kubernetes_clusters_test.go, alicloud/data_source_alicloud_cs_kubernetes_addon_metadata_test.go, alicloud/data_source_alicloud_cs_kubernetes_addons_test.go, alicloud/data_source_alicloud_cs_kubernetes_clusters_test.go, alicloud/data_source_alicloud_cs_kubernetes_permissions.go, alicloud/data_source_alicloud_cs_kubernetes_permissions_test.go, alicloud/data_source_alicloud_cs_kubernetes_version.go, alicloud/data_source_alicloud_cs_kubernetes_version_test.go, alicloud/data_source_alicloud_cs_managed_kubernetes_clusters_test.go, alicloud/data_source_alicloud_cs_serverless_kubernetes_clusters_test.go, alicloud/resource_alicloud_cs_autoscaling_config.go, alicloud/resource_alicloud_cs_kubernetes.go, alicloud/resource_alicloud_cs_kubernetes_addon_test.go, alicloud/resource_alicloud_cs_managed_kubernetes.go, alicloud/resource_alicloud_cs_serverless_kubernetes.go, alicloud/service_alicloud_cs.go, website/docs/d/cs_kubernetes_addon_metadata.html.markdown
Update inlcudes:
- data-source/alicloud_cs_cluster_credential: add retry; fix tests
- data-source/alicloud_cs_edge_kubernetes_clusters: add retry; fix tests
- data-source/alicloud_cs_kubernetes_addon_metadata: add retry; fix tests
- data-source/alicloud_cs_kubernetes_addons: add retry; fix tests
- data-source/alicloud_cs_kubernetes_clusters: add retry; fix tests
- data-source/alicloud_cs_kubernetes_permissions: add retry; fix tests
- data-source/alicloud_cs_kubernetes_version: add retry; fix tests
- data-source/alicloud_cs_managed_kubernetes_clusters: add retry; fix tests
- data-source/alicloud_cs_serverless_kubernetes_clusters: add retry; fix tests
- resource/alicloud_cs_autoscaling_config: add retry
- resource/alicloud_cs_edge_kubernetes: add retry
- resource/alicloud_cs_kubernetes: add …
=> resource/alicloud_cs_*: add retry for general error scenario; data-source/alicloud_cs_*: add retry for general error scenario and fix testcases.

alicloud/resource_alicloud_cs_kubernetes_permissions.go
=> resource/alicloud_cs_kubernetes_permissions: modify sdk

alicloud/resource_alicloud_ess_eci_scaling_configuration.go, alicloud/resource_alicloud_ess_eci_scaling_configuration_test.go, website/docs/r/ess_eci_scaling_configuration.html.markdown
=> resource/alicloud_ess_eci_scaling_configuration: add instance_types.

alicloud/resource_alicloud_click_house_account.go, alicloud/resource_alicloud_click_house_account_test.go, website/docs/d/click_house_accounts.html.markdown, website/docs/r/click_house_account.html.markdown
resource/alicloud_click_house_account: Added support for creating super account.
=> resource/alicloud_click_house_account: Added support for creating super account.

alicloud/resource_alicloud_ess_alb_server_group_attachment.go, alicloud/resource_alicloud_ess_alb_server_group_attachment_test.go
=> resource/alicloud_ess_alb_server_group_attachment: add destory retry and fault tolerance.

alicloud/resource_alicloud_click_house_db_cluster.go, alicloud/resource_alicloud_click_house_db_cluster_test.go, website/docs/r/click_house_db_cluster.html.markdown
resource/alicloud_click_house_db_cluster: Added support for cluster version 23.8, added support for in-place cluster storage upgrade.
=> resource/alicloud_click_house_db_cluster: Added support for cluster version 23.8, added support for in-place cluster storage upgrade.

alicloud/resource_alicloud_ess_scaling_group.go
=> resource/alicloud_ess_scaling_group: add destroy retry and fault tolerance.

alicloud/resource_alicloud_cs_kubernetes_permissions.go
deal throttling error: Throttling.User
=> resource/alicloud_cs_kubernetes_permissions: add throttling retry

alicloud/resource_alicloud_emrv2_cluster.go, website/docs/r/emrv2_cluster.html.markdown
=> resource/alicloud_emrv2_cluster: Fixed bootstrap_scripts out of order

alicloud/extension_ess.go, alicloud/resource_alicloud_ess_scaling_group.go, alicloud/resource_alicloud_ess_scaling_group_test.go, alicloud/service_alicloud_ess.go, website/docs/r/ess_scaling_group.html.markdown
…_group_id and disable group retry fault tolerance.
=> resource/alicloud_ess_scaling_group: add alb_server_group &  resource_group_id and disable group retry fault tolerance.

alicloud/resource_alicloud_polardb_cluster.go
resource/alicloud_polardb_cluster: bug fixed the serverless_steady_switch order.
=> resource/alicloud_polardb_cluster: bug fixed the serverless_steady_switch order.

alicloud/resource_alicloud_click_house_db_cluster.go, alicloud/resource_alicloud_click_house_db_cluster_test.go, alicloud/service_alicloud_clickhouse.go, website/docs/r/click_house_db_cluster.html.markdown
resource/alicloud_click_house_db_cluster: Added support for cluster auto renew.
=> resource/alicloud_click_house_db_cluster: Added support for cluster auto renew.

alicloud/resource_alicloud_ess_scaling_group.go, alicloud/resource_alicloud_ess_scaling_group_test.go, website/docs/r/ess_scaling_group.html.markdown
…ocation_strategy  and spot_allocation_strategy.
=> resource/alicloud_ess_scaling_group: support composable and add az_balance,allocation_strategy  and spot_allocation_strategy.

alicloud/resource_alicloud_click_house_db_cluster.go, alicloud/resource_alicloud_click_house_db_cluster_test.go
resource/alicloud_click_house_db_cluster: Added support for in-place cluster node group and class upgrade.
=> resource/alicloud_click_house_db_cluster: Added support for in-place cluster node group and class upgrade.

alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_cluster_test.go, alicloud/service_alicloud_polardb.go
create dbCluster reduce time consumption
=> resource/alicloud_polardb_cluster: create dbCluster reduce time consumption

alicloud/resource_alicloud_ess_scaling_group.go, alicloud/resource_alicloud_ess_scaling_group_test.go, website/docs/r/ess_scaling_group.html.markdown
=> resource/alicloud_ess_scaling_group: add scaling_policy and max_instance_lifetime

website/docs/r/ess_eci_scaling_configuration.html.markdown, website/docs/r/ess_scaling_group.html.markdown
…d cpu_options_core available version.
=> docs: update scaling_policy,max_instance_lifetime,cpu_options_core and cpu_options_core available version.

alicloud/resource_alicloud_emrv2_cluster.go, alicloud/resource_alicloud_emrv2_cluster_test.go, alicloud/service_alicloud_emr.go, website/docs/r/emrv2_cluster.html.markdown
=> resource/alicloud_emrv2_cluster: supported create auto scaling policies when create emr cluster

alicloud/data_source_alicloud_cen_transit_router_service.go, website/docs/d/cen_transit_router_service.html.markdown
=> data-source/alicloud_cen_transit_router_service: Fixes the error Forbbiden.TransitRouterServiceNotOpen

alicloud/resource_alicloud_ess_eci_scaling_configuration.go
… and cpu_options_threads_per_core is zero.
=> resource/alicloud_ess_eci_scaling_configuration: Fix cpu_options_core and cpu_options_threads_per_core is zero.

alicloud/resource_alicloud_ess_scaling_group.go, alicloud/resource_alicloud_ess_scaling_group_test.go, website/docs/r/ess_scaling_group.html.markdown
=> resource/alicloud_ess_scaling_group: support health_check_types and instance_id

website/docs/r/cms_alarm.html.markdown
Added an update to clarify the description for the targets parameter.
=> docs: Imporved targets parameter description for cms_alarm.

alicloud/resource_alicloud_click_house_db_cluster.go, alicloud/resource_alicloud_click_house_db_cluster_test.go, website/docs/r/click_house_db_cluster.html.markdown
resource/alicloud_click_house_db_cluster: Added support for creating multi-zone DBCluster.
=> resource/alicloud_click_house_db_cluster: Added support for creating multi-zone DBCluster.

alicloud/provider.go, website/docs/index.html.markdown
=> provider: standardizs environment variable names, including credentials and region

alicloud/resource_alicloud_elasticsearch_instance.go, alicloud/resource_alicloud_elasticsearch_instance_test.go, alicloud/service_alicloud_common_test.go, alicloud/service_alicloud_elasticsearch.go, examples/elasticsearch/main.tf, examples/elasticsearch/variables.tf, website/docs/r/elasticsearch_instance.html.markdown
elasticsearch support warm node and kibana private network
=> resource/alicloud_elasticsearch_instance: elasticsearch support warm node and kibana private network

website/docs/r/elasticsearch_instance.html.markdown
Update elasticsearch document for warm node
=> docs: Update elasticsearch document for warm node 

alicloud/diff_suppress_funcs.go, website/docs/r/polardb_cluster.html.markdown
resource/alicloud_polardb_cluster: modified support pg serverless; docs: modified polardb_cluster parameters.
=> docs: modified polardb_cluster support pg serverless.

alicloud/resource_alicloud_db_instance.go
=> resource/alicloud_db_instance: Fix set server_cert and client_ca_cert is sensitive

alicloud/service_alicloud_polardb.go
resource/alicloud_polardb_cluster: upd loose_polar_log_bin compatible with mysql5.6
=> alicloud/service_alicloud_polardb: modified loose_polar_log_bin compatible with mysql5.6

alicloud/data_source_alicloud_emrv2_clusters.go, alicloud/resource_alicloud_emrv2_cluster.go, website/docs/d/emrv2_clusters.html.markdown, website/docs/r/emrv2_cluster.html.markdown
…icloud_emrv2_cluster: supported auto renew with resize emr cluster
=> data-source/alicloud_emrv2_clusters: fix wrong value ids; resource/alicloud_emrv2_cluster: supported auto renew with resize emr cluster

alicloud/resource_alicloud_polardb_cluster.go
resource/alicloud_polardb_cluster: improve add retry etc.
=> resource/alicloud_polardb_cluster: improve add retry etc.

alicloud/resource_alicloud_emrv2_cluster.go, website/docs/r/emrv2_cluster.html.markdown
resource/alicloud_emrv2_cluster: Fixed increase emr cluster with auto renew
=> resource/alicloud_emrv2_cluster: Fixed increase emr cluster with auto renew

alicloud/resource_alicloud_service_mesh_service_mesh.go, alicloud/resource_alicloud_service_mesh_service_mesh_test.go, alicloud/service_alicloud_service_mesh_v2.go, website/docs/r/service_mesh_service_mesh.html.markdown
This PR supplies new attributes about Kiali Conguration in resource/alicloud_service_mesh_service_mesh, along with its tests.
=> resource/alicloud_service_mesh_service_mesh: Add attributes related to Kiali

alicloud/data_source_alicloud_mse_engine_namespaces.go, website/docs/d/mse_engine_namespaces.html.markdown
data-source/alicloud_mse_engine_namespaces
=> data-source/alicloud_mse_engine_namespaces: recover cluster_id forcenew.

alicloud/diff_suppress_funcs.go, alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_cluster_test.go, website/docs/r/polardb_cluster.html.markdown
resource/alicloud_polardb_cluster: modified support compress_storage; resource/alicloud_polardb_cluster_test: modified support compress_storage; docs: modified support compress_storage.
=> resource/alicloud_polardb_cluster: modified support compress_storage

alicloud/diff_suppress_funcs.go, alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_cluster_test.go, alicloud/service_alicloud_polardb.go, website/docs/r/polardb_cluster.html.markdown
resource/alicloud_polardb_cluster: modified support loose_xengine etc; resource/alicloud_polardb_cluster_test: modified support loose_xengine etc; docs: support loose_xengine etc.
=> resource/alicloud_polardb_cluster: modified support loose_xengine and loose_xengine_use_memory_pct.

website/docs/r/eci_container_group.html.markdown
docs: Add dns policy version info
=> docs: Add dns policy version info for eci_container_group.

alicloud/resource_alicloud_ess_alb_server_group_attachment_test.go
…stAccAliCloudEssAlbServerGroupAttachment_nonForceAttach testcase
=> testcase: fix TestAccAliCloudEssAlbServerGroupAttachment_basic and TestAccAliCloudEssAlbServerGroupAttachment_nonForceAttach testcase

alicloud/data_source_alicloud_kms_secrets.go, alicloud/data_source_alicloud_kms_secrets_test.go, website/docs/d/kms_secrets.html.markdown
=> data-source/alicloud_kms_secrets: Improves the fetching secrets tags by setting tags or fetch_tags

alicloud/resource_alicloud_ess_scaling_group.go, alicloud/resource_alicloud_ess_scaling_group_test.go, website/docs/r/ess_scaling_group.html.markdown
…_id, update health_check_type values range and supplement instance_id
=> resource/alicloud_ess_scaling_group: add attribute of container_group_id, update health_check_type values range and supplement instance_id

alicloud/resource_alicloud_polardb_account_privilege_test.go, alicloud/resource_alicloud_polardb_backup_policy_test.go
testcase: fix testcase for resource/alicloud_polardb_backup_policy, resource/alicloud_polardb_account_priviledge.
=> testcase: fix testcase for resource/alicloud_polardb_backup_policy, resource/alicloud_polardb_account_priviledge.

alicloud/resource_alicloud_ess_scaling_configuration.go, alicloud/resource_alicloud_ess_scaling_configuration_test.go, website/docs/r/ess_scaling_configuration.html.markdown
=> resource/alicloud_ess_scaling_configuration: update internet_max_bandwidth_in can modify.

alicloud/resource_alicloud_ess_eci_scaling_configuration.go, website/docs/r/ess_eci_scaling_configuration.html.markdown
=> resource/alicloud_ess_eci_scaling_configuration: update container_group_name constraint.

alicloud/resource_alicloud_ess_scaling_configuration.go, alicloud/resource_alicloud_ess_scaling_configuration_test.go, website/docs/r/ess_scaling_configuration.html.markdown
=> resource/alicloud_ess_scaling_configuration: add attribute network_interfaces

alicloud/resource_alicloud_ess_scaling_configuration.go, alicloud/resource_alicloud_ess_scaling_configuration_test.go
=> resource/alicloud_ess_scaling_configuration: update internet_max_bandwidth_in import

alicloud/resource_alicloud_ess_scaling_rule.go, alicloud/resource_alicloud_ess_scaling_rule_test.go, alicloud/service_alicloud_ess.go
resource/alicloud_ess_scaling_rule: optimize query rule
=>  resource/alicloud_ess_scaling_rule: optimize query rule

.gitignore, website/docs/r/cdn_domain_new.html.markdown, website/docs/r/dcdn_domain.html.markdown
=> docs: Improves docs of resource alicloud_dcdn_domain and alicloud_cdn_domain_new

alicloud/resource_alicloud_polardb_cluster_endpoint.go, website/docs/d/polardb_clusters.html.markdown, website/docs/r/polardb_cluster.html.markdown
resource/alicloud_polardb_cluster_endpoint: modify retry; docs: Improves description for cluster.
=> resource/alicloud_polardb_cluster_endpoint: modify retry; docs: Improves description for cluster.

alicloud/resource_alicloud_ess_scaling_group.go, alicloud/resource_alicloud_ess_scaling_group_test.go, website/docs/r/ess_scaling_group.html.markdown
=> resource/alicloud_ess_scaling_group: add attribute of stop_instance_timeout.

alicloud/connectivity/regions.go, alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_cluster_test.go, website/docs/r/polardb_cluster.html.markdown
resource/alicloud_polardb_cluster: support strictConsistency.
=> resource/alicloud_polardb_cluster: added support strict_consistency.

alicloud/resource_alicloud_oos_execution.go, alicloud/service_alicloud_oos.go
=> resource/alicloud_oos_execution: Ensure the resource status is success after creating it

alicloud/connectivity/client.go, alicloud/data_source_alicloud_ddoscoo_domain_resources.go, alicloud/data_source_alicloud_ddoscoo_domain_resources_test.go, alicloud/data_source_alicloud_ddoscoo_instances.go, alicloud/data_source_alicloud_ddoscoo_instances_test.go, alicloud/data_source_alicloud_ddoscoo_ports.go, alicloud/data_source_alicloud_ddoscoo_ports_test.go, alicloud/resource_alicloud_ddoscoo_domain_resource.go, alicloud/resource_alicloud_ddoscoo_domain_resource_test.go, alicloud/resource_alicloud_ddoscoo_instance.go, alicloud/resource_alicloud_ddoscoo_instance_test.go, alicloud/resource_alicloud_ddoscoo_port.go, alicloud/resource_alicloud_ddoscoo_scheduler_rule.go, alicloud/resource_alicloud_ddoscoo_scheduler_rule_test.go, alicloud/service_alicloud_ddos_coo_v2.go, alicloud/service_alicloud_ddoscoo.go, website/docs/d/ddoscoo_domain_resources.html.markdown, website/docs/d/ddoscoo_ports.html.markdown, website/docs/r/ddoscoo_instance.html.markdown
=> DdosCoo: Improves the invoking ddoscoo api method and supports refreshing credential automatically

alicloud/connectivity/endpoint.go, alicloud/resource_alicloud_live_caster.go, alicloud/service_alicloud_live_v2.go
=> Live: Improves the invoking live api method and supports refreshing credential automatically

alicloud/data_source_alicloud_ess_scaling_configurations.go, alicloud/data_source_alicloud_ess_scaling_configurations_test.go, alicloud/service_alicloud_ess.go, website/docs/d/ess_scaling_configurations.html.markdown
=> data-source/alicloud_ess_scaling_configurations: support attribute of instance_pattern_info.

alicloud/connectivity/client.go, alicloud/data_source_alicloud_adb_db_cluster_lake_versions.go, alicloud/data_source_alicloud_adb_db_cluster_lake_versions_test.go, alicloud/data_source_alicloud_adb_db_clusters.go, alicloud/data_source_alicloud_adb_db_clusters_test.go, alicloud/data_source_alicloud_adb_resource_groups.go, alicloud/resource_alicloud_adb_db_cluster.go, alicloud/resource_alicloud_adb_db_cluster_lake_version.go, alicloud/resource_alicloud_adb_db_cluster_test.go, alicloud/resource_alicloud_adb_lake_account.go, alicloud/resource_alicloud_adb_resource_group.go, alicloud/service_alicloud_adb.go, alicloud/service_alicloud_adb_v2.go, website/docs/d/adb_db_cluster_lake_versions.html.markdown, website/docs/d/adb_db_clusters.html.markdown, website/docs/r/adb_db_cluster.html.markdown
=> ADB: Improves the invoking adb api method and supports refreshing credential automatically

website/docs/r/sae_application.html.markdown
=> docs: improves the description of the resource aliclodu_sae_application argument sls_configs

website/docs/r/sls_collection_policy.html.markdown
=> docs: Corrects the product introduce link of resource alicloud_sls_collection_policy

alicloud/resource_alicloud_dcdn_waf_rule.go, alicloud/resource_alicloud_dcdn_waf_rule_test.go, website/docs/r/dcdn_waf_rule.html.markdown
=> resource/alicloud_dcdn_waf_rule: Fixes the panic error when rateLimit is nil

alicloud/resource_alicloud_dcdn_domain.go, alicloud/resource_alicloud_dcdn_domain_test.go
=> resource/alicloud_dcdn_domain: Fixes the updating arguement scope does not working error

website/docs/r/oss_bucket_policy.html.markdown, website/docs/r/oss_bucket_referer.html.markdown
=> docs: Removes the useless example code

alicloud/data_source_alicloud_vpcs.go, alicloud/data_source_alicloud_vpcs_test.go, website/docs/d/vpcs.html.markdown
=> data-source/alicloud_vpcs: Adds new attribute dhcp_options_set_id, dhcp_options_set_status and dns_hostname_status

alicloud/resource_alicloud_cloud_monitor_service_enterprise_public.go, alicloud/resource_alicloud_cloud_monitor_service_enterprise_public_test.go, alicloud/service_alicloud_cloud_monitor_service_v2.go
=> resource/alicloud_cloud_monitor_service_enterprise_public: Fixes the InvalidParameter when creating it

alicloud/connectivity/client.go, alicloud/data_source_alicloud_cloud_firewall_instances.go, alicloud/resource_alicloud_cloud_monitor_service_enterprise_public.go, alicloud/service_alicloud_bss_open_api.go, alicloud/service_alicloud_cloud_monitor_service_v2.go
=> client: Adds new method IsInternationalAccount used to invoking bss openapi

alicloud/data_source_alicloud_event_bridge_service.go, alicloud/service_alicloud_cloud_monitor_service_v2.go
=> data-source/alicloud_event_bridge_service: Improves the invoking bss openapi method

website/docs/r/cms_alarm.html.markdown
=> docs: Improves the argument targets description of resource alicloud_cms_alarm

alicloud/connectivity/endpoint.go, alicloud/resource_alicloud_amqp_instance.go, alicloud/resource_alicloud_amqp_instance_test.go, alicloud/service_alicloud_amqp_v2.go, website/docs/r/amqp_instance.html.markdown
=> resource/alicloud_amqp_instance: Improves the invoking api method and supports refreshing credential automatically

alicloud/resource_alicloud_cloud_monitor_service_basic_public.go, alicloud/resource_alicloud_cloud_monitor_service_enterprise_public.go
=> resource/alicloud_cloud_monitor_service_basic_public: Supports international account

website/docs/d/event_bridge_service.html.markdown
=> docs: Removes the useless note of data-source/alicloud_event_bridge_service

alicloud/service_alicloud_elasticsearch.go
=> resource/alicloud_elasticsearch_instance: Fixes the renew issue on international account

alicloud/resource_alicloud_cr_ee_instance.go, alicloud/resource_alicloud_cr_ee_instance_test.go, alicloud/service_alicloud_cr_v2.go
=> resource/alicloud_cr_ee_instance: Improves the invoking api method and supports refreshing credential automatically

alicloud/resource_alicloud_ddoscoo_instance.go
=> resource/alicloud_ddoscoo_instance: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_kms_instances_test.go, alicloud/resource_alicloud_cr_ee_instance_test.go, alicloud/resource_alicloud_esa_rate_plan_instance.go, website/docs/d/kms_instances.html.markdown
=> resource/alicloud_esa_rate_plan_instance: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/resource_alicloud_rocketmq_instance.go, alicloud/service_alicloud_bss_open_api.go, alicloud/service_alicloud_rocketmq_v2.go
=> resource/alicloud_rocketmq_instance: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/resource_alicloud_aligreen_audit_callback.go, alicloud/resource_alicloud_aligreen_biz_type.go, alicloud/resource_alicloud_aligreen_callback.go, alicloud/resource_alicloud_aligreen_image_lib.go, alicloud/resource_alicloud_aligreen_keyword_lib.go, alicloud/resource_alicloud_aligreen_oss_stock_task.go, alicloud/service_alicloud_aligreen_v2.go
=> Aligreen:  Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/resource_alicloud_express_connect_router_express_connect_router.go, alicloud/resource_alicloud_express_connect_router_grant_association.go, alicloud/resource_alicloud_express_connect_router_tr_association.go, alicloud/resource_alicloud_express_connect_router_vbr_child_instance.go, alicloud/resource_alicloud_express_connect_router_vpc_association.go, alicloud/service_alicloud_express_connect_router_v2.go
=> ExpressConnectRouter:  Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_cen_flowlogs.go, alicloud/resource_alicloud_cen_flowlog.go, alicloud/resource_alicloud_cen_traffic_marking_policy.go, alicloud/resource_alicloud_cen_transit_router_ecr_attachment.go, alicloud/resource_alicloud_cen_transit_router_multicast_domain.go, alicloud/resource_alicloud_cen_transit_router_peer_attachment.go, alicloud/resource_alicloud_cen_transit_router_vpc_attachment.go, alicloud/service_alicloud_cen_v2.go
=> Cen:  Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/resource_alicloud_dfs_access_group.go, alicloud/resource_alicloud_dfs_access_rule.go, alicloud/resource_alicloud_dfs_file_system.go, alicloud/resource_alicloud_dfs_mount_point.go, alicloud/resource_alicloud_dfs_vsc_mount_point.go, alicloud/service_alicloud_dfs_v2.go
=> DFS:  Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_vpn_gateway_zones.go, alicloud/resource_alicloud_vpn_connection.go, alicloud/resource_alicloud_vpn_connection_test.go, alicloud/resource_alicloud_vpn_customer_gateway.go, alicloud/resource_alicloud_vpn_gateway.go, alicloud/service_alicloud_vpn_gateway_v2.go
=> VpnGateway: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/resource_alicloud_common_bandwidth_package.go, alicloud/resource_alicloud_common_bandwidth_package_attachment.go, alicloud/service_alicloud_cbwp_v2.go
=> CBWP: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_enhanced_nat_available_zones.go, alicloud/data_source_alicloud_forward_entries.go, alicloud/data_source_alicloud_forward_entries_test.go, alicloud/data_source_alicloud_nat_gateways.go, alicloud/data_source_alicloud_route_tables.go, alicloud/data_source_alicloud_snat_entries.go, alicloud/resource_alicloud_forward_entry.go, alicloud/resource_alicloud_nat_gateway.go, alicloud/resource_alicloud_nat_gateway_test.go, alicloud/resource_alicloud_route_table.go, alicloud/resource_alicloud_route_table_attachment.go, alicloud/resource_alicloud_route_table_test.go, alicloud/resource_alicloud_snat_entry.go, alicloud/service_alicloud_nat_gateway_v2.go, website/docs/d/enhanced_nat_available_zones.html.markdown, website/docs/d/forward_entries.html.markdown, website/docs/d/nat_gateways.html.markdown, website/docs/d/snat_entries.html.markdown, website/docs/r/forward_entry.html.markdown
=> NatGateway: Improves the invoking api method and supports refreshing  credential automatically

alicloud/data_source_alicloud_havips.go, alicloud/resource_alicloud_havip.go, alicloud/resource_alicloud_havip_attachment.go, alicloud/resource_alicloud_havip_attachment_test.go, alicloud/resource_alicloud_havip_test.go, alicloud/resource_alicloud_vpc_ha_vip.go, alicloud/service_alicloud_vpc_v2.go
=> HaVip: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_vpc_ipv4_gateways.go, alicloud/data_source_alicloud_vpc_ipv6_addresses.go, alicloud/data_source_alicloud_vpc_ipv6_egress_rules.go, alicloud/data_source_alicloud_vpc_ipv6_gateways.go, alicloud/data_source_alicloud_vpc_ipv6_internet_bandwidths.go, alicloud/resource_alicloud_vpc_ipv4_cidr_block.go, alicloud/resource_alicloud_vpc_ipv4_gateway.go, alicloud/resource_alicloud_vpc_ipv4_gateway_test.go, alicloud/resource_alicloud_vpc_ipv6_address.go, alicloud/resource_alicloud_vpc_ipv6_egress_rule.go, alicloud/resource_alicloud_vpc_ipv6_gateway.go, alicloud/resource_alicloud_vpc_ipv6_gateway_test.go, alicloud/resource_alicloud_vpc_ipv6_internet_bandwidth.go
=> VpcIpv4&Ipv6Resources: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_polardb_global_database_networks.go, alicloud/data_source_alicloud_polardb_parameter_groups.go, alicloud/resource_alicloud_polardb_backup_policy.go, alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_global_database_network.go, alicloud/resource_alicloud_polardb_global_database_network_test.go, alicloud/resource_alicloud_polardb_parameter_group.go, alicloud/resource_alicloud_polardb_parameter_group_test.go, alicloud/service_alicloud_polardb.go
=> PolarDB: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/resource_alicloud_drds_polardbx_instance.go, alicloud/service_alicloud_drds_v2.go
=> DRDS: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_ocean_base_instances.go, alicloud/resource_alicloud_ocean_base_instance.go, alicloud/service_alicloud_ocean_base_pro.go, alicloud/service_alicloud_ocean_base_v2.go
=> OceanBase: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/connectivity/endpoint.go, alicloud/data_source_alicloud_dts_consumer_channels.go, alicloud/data_source_alicloud_dts_instances.go, alicloud/data_source_alicloud_dts_migration_jobs.go, alicloud/data_source_alicloud_dts_subscription_jobs.go, alicloud/data_source_alicloud_dts_synchronization_jobs.go, alicloud/resource_alicloud_dts_consumer_channel.go, alicloud/resource_alicloud_dts_instance.go, alicloud/resource_alicloud_dts_job_monitor_rule.go, alicloud/resource_alicloud_dts_migration_instance.go, alicloud/resource_alicloud_dts_migration_job.go, alicloud/resource_alicloud_dts_migration_job_test.go, alicloud/resource_alicloud_dts_subscription_job.go, alicloud/resource_alicloud_dts_subscription_job_test.go, alicloud/resource_alicloud_dts_synchronization_instance.go, alicloud/resource_alicloud_dts_synchronization_job.go, alicloud/service_alicloud_dts.go
=> Dts: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_lindorm_instances.go, alicloud/data_source_alicloud_tsdb_instances.go, alicloud/data_source_alicloud_tsdb_zones.go, alicloud/resource_alicloud_lindorm_instance.go, alicloud/resource_alicloud_lindorm_instance_test.go, alicloud/resource_alicloud_tsdb_instance.go, alicloud/resource_alicloud_tsdb_instance_test.go, alicloud/service_alicloud_hbase.go, alicloud/service_alicloud_hitsdb.go
=> Lindorm: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_dbfs_auto_snap_shot_policies.go, alicloud/data_source_alicloud_dbfs_instances.go, alicloud/data_source_alicloud_dbfs_snapshots.go, alicloud/resource_alicloud_dbfs_auto_snap_shot_policy.go, alicloud/resource_alicloud_dbfs_instance.go, alicloud/resource_alicloud_dbfs_instance_attachment.go, alicloud/resource_alicloud_dbfs_instance_test.go, alicloud/resource_alicloud_dbfs_service_linked_role.go, alicloud/resource_alicloud_dbfs_snapshot.go, alicloud/resource_alicloud_dbfs_snapshot_test.go, alicloud/service_alicloud_dbfs.go, alicloud/service_alicloud_dbfs_v2.go
=> DBFS: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_eais_instances.go, alicloud/resource_alicloud_eais_instance.go, alicloud/resource_alicloud_eais_instance_test.go, alicloud/service_alicloud_eais.go
=> Eais: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/connectivity/endpoint.go, alicloud/data_source_alicloud_database_gateway_gateways.go, alicloud/resource_alicloud_database_gateway_gateway.go, alicloud/resource_alicloud_database_gateway_gateway_test.go, alicloud/service_alicloud_dg.go
=> DatabaseGateway: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/resource_alicloud_das_switch_das_pro.go, alicloud/resource_alicloud_das_switch_das_pro_test.go, alicloud/service_alicloud_das.go
=> DAS: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_cloudauth_face_configs.go, alicloud/resource_alicloud_cloudauth_face_config.go, alicloud/service_alicloud_cloudauth.go
=> Cloudauth: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_imp_app_templates.go, alicloud/resource_alicloud_imp_app_template.go, alicloud/service_alicloud_imp.go
=> IMP: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_mhub_apps.go, alicloud/data_source_alicloud_mhub_products.go, alicloud/resource_alicloud_mhub_app.go, alicloud/resource_alicloud_mhub_app_test.go, alicloud/resource_alicloud_mhub_product.go, alicloud/resource_alicloud_mhub_product_test.go, alicloud/service_alicloud_mhub.go
=> Mhub: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/connectivity/endpoint.go, alicloud/data_source_alicloud_ros_change_sets.go, alicloud/data_source_alicloud_ros_regions.go, alicloud/data_source_alicloud_ros_stack_groups.go, alicloud/data_source_alicloud_ros_stack_instances.go, alicloud/data_source_alicloud_ros_stacks.go, alicloud/data_source_alicloud_ros_template_scratches.go, alicloud/data_source_alicloud_ros_templates.go, alicloud/resource_alicloud_ros_change_set.go, alicloud/resource_alicloud_ros_stack.go, alicloud/resource_alicloud_ros_stack_group.go, alicloud/resource_alicloud_ros_stack_group_test.go, alicloud/resource_alicloud_ros_stack_instance.go, alicloud/resource_alicloud_ros_stack_test.go, alicloud/resource_alicloud_ros_template.go, alicloud/resource_alicloud_ros_template_scratch.go, alicloud/resource_alicloud_ros_template_scratch_test.go, alicloud/resource_alicloud_ros_template_test.go, alicloud/service_alicloud_ros.go
=> Ros: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_pvtz_endpoints.go, alicloud/data_source_alicloud_pvtz_resolver_zones.go, alicloud/data_source_alicloud_pvtz_rules.go, alicloud/data_source_alicloud_pvtz_zone_records.go, alicloud/data_source_alicloud_pvtz_zones.go, alicloud/resource_alicloud_pvtz_endpoint.go, alicloud/resource_alicloud_pvtz_endpoint_test.go, alicloud/resource_alicloud_pvtz_rule.go, alicloud/resource_alicloud_pvtz_rule_attachment.go, alicloud/resource_alicloud_pvtz_user_vpc_authorization.go, alicloud/resource_alicloud_pvtz_zone.go, alicloud/resource_alicloud_pvtz_zone_attachment.go, alicloud/resource_alicloud_pvtz_zone_record.go, alicloud/resource_alicloud_pvtz_zone_test.go, alicloud/service_alicloud_pvtz.go
=> PVTZ: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_resource_manager_resource_shares.go, alicloud/data_source_alicloud_resource_manager_shared_resources.go, alicloud/data_source_alicloud_resource_manager_shared_targets.go, alicloud/resource_alicloud_resource_manager_resource_share.go, alicloud/resource_alicloud_resource_manager_shared_resource.go, alicloud/resource_alicloud_resource_manager_shared_target.go, alicloud/service_alicloud_resourcesharing.go
=> ResourceSharing: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_maxcompute_projects.go, alicloud/resource_alicloud_max_compute_quota_plan.go, alicloud/resource_alicloud_max_compute_quota_schedule.go, alicloud/resource_alicloud_max_compute_role.go, alicloud/resource_alicloud_max_compute_role_user_attachment.go, alicloud/resource_alicloud_max_compute_tunnel_quota_timer.go, alicloud/resource_alicloud_maxcompute_project.go, alicloud/service_alicloud_max_compute_v2.go, alicloud/service_alicloud_maxcompute.go
=> MaxCompute: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_eci_container_groups.go, alicloud/data_source_alicloud_eci_virtual_nodes.go, alicloud/data_source_alicloud_eci_zones.go, alicloud/resource_alicloud_eci_container_group.go, alicloud/resource_alicloud_eci_container_group_test.go, alicloud/resource_alicloud_eci_virtual_node.go, alicloud/resource_alicloud_eci_virtual_node_test.go, alicloud/service_alicloud_eci.go
=> ECI: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_mse_clusters.go, alicloud/data_source_alicloud_mse_engine_namespaces.go, alicloud/data_source_alicloud_mse_gateways.go, alicloud/data_source_alicloud_mse_nacos_configs.go, alicloud/data_source_alicloud_mse_znodes.go, alicloud/resource_alicloud_mse_cluster.go, alicloud/resource_alicloud_mse_cluster_test.go, alicloud/resource_alicloud_mse_engine_namespace.go, alicloud/resource_alicloud_mse_gateway.go, alicloud/resource_alicloud_mse_gateway_test.go, alicloud/resource_alicloud_mse_nacos_config.go, alicloud/resource_alicloud_mse_znode.go, alicloud/service_alicloud_mse.go
=> Mse: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_brain_industrial_pid_loops.go, alicloud/data_source_alicloud_brain_industrial_pid_organizations.go, alicloud/data_source_alicloud_brain_industrial_pid_projects.go, alicloud/data_source_alicloud_brain_industrial_service.go, alicloud/resource_alicloud_brain_industrial_pid_loop.go, alicloud/resource_alicloud_brain_industrial_pid_organization.go, alicloud/resource_alicloud_brain_industrial_pid_organization_test.go, alicloud/resource_alicloud_brain_industrial_pid_project.go, alicloud/resource_alicloud_brain_industrial_pid_project_test.go, alicloud/service_alicloud_brain_industrial.go
=> BrainIndustrial: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_ram_saml_providers.go, alicloud/resource_alicloud_ims_oidc_provider.go, alicloud/resource_alicloud_ram_saml_provider.go, alicloud/resource_alicloud_ram_security_preference.go, alicloud/service_alicloud_ims.go, alicloud/service_alicloud_ims_v2.go, alicloud/service_alicloud_ram.go
=> IMS: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_oos_application_groups.go, alicloud/data_source_alicloud_oos_applications.go, alicloud/data_source_alicloud_oos_executions.go, alicloud/data_source_alicloud_oos_parameters.go, alicloud/data_source_alicloud_oos_patch_baselines.go, alicloud/data_source_alicloud_oos_secret_parameters.go, alicloud/data_source_alicloud_oos_state_configurations.go, alicloud/data_source_alicloud_oos_templates.go, alicloud/resource_alicloud_oos_application.go, alicloud/resource_alicloud_oos_application_group.go, alicloud/resource_alicloud_oos_application_test.go, alicloud/resource_alicloud_oos_default_patch_baseline.go, alicloud/resource_alicloud_oos_execution.go, alicloud/resource_alicloud_oos_execution_test.go, alicloud/resource_alicloud_oos_parameter.go, alicloud/resource_alicloud_oos_parameter_test.go, alicloud/resource_alicloud_oos_patch_baseline.go, alicloud/resource_alicloud_oos_patch_baseline_test.go, alicloud/resource_alicloud_oos_secret_parameter.go, alicloud/resource_alicloud_oos_secret_parameter_test.go, alicloud/resource_alicloud_oos_service_setting.go, alicloud/resource_alicloud_oos_state_configuration.go, alicloud/resource_alicloud_oos_state_configuration_test.go, alicloud/resource_alicloud_oos_template.go, alicloud/resource_alicloud_oos_template_test.go, alicloud/service_alicloud_oos.go, alicloud/service_alicloud_oos_v2.go
=> OOS: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_cloud_storage_gateway_express_syncs.go, alicloud/data_source_alicloud_cloud_storage_gateway_gateway_block_volumes.go, alicloud/data_source_alicloud_cloud_storage_gateway_gateway_cache_disks.go, alicloud/data_source_alicloud_cloud_storage_gateway_gateway_file_shares.go, alicloud/data_source_alicloud_cloud_storage_gateway_gateway_smb_users.go, alicloud/data_source_alicloud_cloud_storage_gateway_gateways.go, alicloud/data_source_alicloud_cloud_storage_gateway_stocks.go, alicloud/data_source_alicloud_cloud_storage_gateway_storage_bundles.go, alicloud/resource_alicloud_cloud_storage_gateway_express_sync.go, alicloud/resource_alicloud_cloud_storage_gateway_express_sync_share_attachment.go, alicloud/resource_alicloud_cloud_storage_gateway_express_sync_test.go, alicloud/resource_alicloud_cloud_storage_gateway_gateway.go, alicloud/resource_alicloud_cloud_storage_gateway_gateway_block_volume.go, alicloud/resource_alicloud_cloud_storage_gateway_gateway_cache_disk.go, alicloud/resource_alicloud_cloud_storage_gateway_gateway_file_share.go, alicloud/resource_alicloud_cloud_storage_gateway_gateway_logging.go, alicloud/resource_alicloud_cloud_storage_gateway_gateway_smb_user.go, alicloud/resource_alicloud_cloud_storage_gateway_storage_bundle.go, alicloud/service_alicloud_sgw.go
=> CloudStorageGateway: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_nas_access_groups.go, alicloud/data_source_alicloud_nas_access_rules.go, alicloud/data_source_alicloud_nas_auto_snapshot_policies.go, alicloud/data_source_alicloud_nas_data_flows.go, alicloud/data_source_alicloud_nas_file_systems.go, alicloud/data_source_alicloud_nas_filesets.go, alicloud/data_source_alicloud_nas_lifecycle_policies.go, alicloud/data_source_alicloud_nas_mount_targets.go, alicloud/data_source_alicloud_nas_protocols.go, alicloud/data_source_alicloud_nas_snapshots.go, alicloud/data_source_alicloud_nas_zones.go, alicloud/resource_alicloud_nas_access_group.go, alicloud/resource_alicloud_nas_access_group_test.go, alicloud/resource_alicloud_nas_access_point.go, alicloud/resource_alicloud_nas_access_rule.go, alicloud/resource_alicloud_nas_auto_snapshot_policy.go, alicloud/resource_alicloud_nas_auto_snapshot_policy_test.go, alicloud/resource_alicloud_nas_data_flow.go, alicloud/resource_alicloud_nas_file_system.go, alicloud/resource_alicloud_nas_file_system_test.go, alicloud/resource_alicloud_nas_fileset.go, alicloud/resource_alicloud_nas_lifecycle_policy.go, alicloud/resource_alicloud_nas_mount_target.go, alicloud/resource_alicloud_nas_recycle_bin.go, alicloud/resource_alicloud_nas_smb_acl_attachment.go, alicloud/resource_alicloud_nas_snapshot.go, alicloud/service_alicloud_nas.go, alicloud/service_alicloud_nas_v2.go
=> Nas: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_dms_enterprise_databases.go, alicloud/data_source_alicloud_dms_enterprise_instances.go, alicloud/data_source_alicloud_dms_enterprise_logic_databases.go, alicloud/data_source_alicloud_dms_enterprise_proxies.go, alicloud/data_source_alicloud_dms_enterprise_proxy_accesses.go, alicloud/data_source_alicloud_dms_enterprise_users.go, alicloud/data_source_alicloud_dms_user_tenants.go, alicloud/resource_alicloud_dms_enterprise_authority_template.go, alicloud/resource_alicloud_dms_enterprise_instance.go, alicloud/resource_alicloud_dms_enterprise_instance_test.go, alicloud/resource_alicloud_dms_enterprise_logic_database.go, alicloud/resource_alicloud_dms_enterprise_proxy.go, alicloud/resource_alicloud_dms_enterprise_proxy_access.go, alicloud/resource_alicloud_dms_enterprise_user.go, alicloud/resource_alicloud_dms_enterprise_user_test.go, alicloud/service_alicloud_dms_enterprise.go, alicloud/service_alicloud_dms_enterprise_v2.go
=> DmsEnterprise: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_slb_ca_certificates.go, alicloud/data_source_alicloud_slb_load_balancers.go, alicloud/data_source_alicloud_slb_tls_cipher_policies.go, alicloud/resource_alicloud_slb_acl.go, alicloud/resource_alicloud_slb_acl_entry_attachment.go, alicloud/resource_alicloud_slb_acl_test.go, alicloud/resource_alicloud_slb_ca_certificate.go, alicloud/resource_alicloud_slb_ca_certificate_test.go, alicloud/resource_alicloud_slb_load_balancer.go, alicloud/resource_alicloud_slb_load_balancer_test.go, alicloud/resource_alicloud_slb_rule.go, alicloud/resource_alicloud_slb_server_group_server_attachment.go, alicloud/resource_alicloud_slb_tls_cipher_policy.go, alicloud/resource_alicloud_slb_tls_cipher_policy_test.go, alicloud/service_alicloud_common_test.go, alicloud/service_alicloud_slb.go
=> Slb: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_alidns_access_strategies.go, alicloud/data_source_alicloud_alidns_address_pools.go, alicloud/data_source_alicloud_alidns_custom_lines.go, alicloud/data_source_alicloud_alidns_gtm_instances.go, alicloud/data_source_alicloud_alidns_instances.go, alicloud/resource_alicloud_alidns_access_strategy.go, alicloud/resource_alicloud_alidns_address_pool.go, alicloud/resource_alicloud_alidns_custom_line.go, alicloud/resource_alicloud_alidns_monitor_config.go, alicloud/service_alicloud_alidns.go
=> Alidns: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_direct_mail_domains.go, alicloud/data_source_alicloud_direct_mail_mail_addresses.go, alicloud/data_source_alicloud_direct_mail_receiverses.go, alicloud/data_source_alicloud_direct_mail_tags.go, alicloud/resource_alicloud_direct_mail_domain.go, alicloud/resource_alicloud_direct_mail_domain_test.go, alicloud/resource_alicloud_direct_mail_mail_address.go, alicloud/resource_alicloud_direct_mail_mail_address_test.go, alicloud/resource_alicloud_direct_mail_receivers.go, alicloud/resource_alicloud_direct_mail_receivers_test.go, alicloud/resource_alicloud_direct_mail_tag.go, alicloud/resource_alicloud_direct_mail_tag_test.go, alicloud/service_alicloud_dm.go
=> Directmail: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_cassandra_backup_plans.go, alicloud/resource_alicloud_cassandra_backup_plan.go, alicloud/service_alicloud_cassandra.go
=> Cassandra: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_amqp_bindings.go, alicloud/data_source_alicloud_amqp_exchanges.go, alicloud/data_source_alicloud_amqp_instances.go, alicloud/data_source_alicloud_amqp_queues.go, alicloud/data_source_alicloud_amqp_static_accounts.go, alicloud/data_source_alicloud_amqp_virtual_hosts.go, alicloud/resource_alicloud_amqp_binding.go, alicloud/resource_alicloud_amqp_exchange.go, alicloud/resource_alicloud_amqp_queue.go, alicloud/resource_alicloud_amqp_static_account.go, alicloud/resource_alicloud_amqp_virtual_host.go, alicloud/resource_alicloud_amqp_virtual_host_test.go, alicloud/service_alicloud_amqp_open.go
=> Amqp: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_kms_aliases.go, alicloud/data_source_alicloud_kms_ciphertext.go, alicloud/data_source_alicloud_kms_key_versions.go, alicloud/data_source_alicloud_kms_keys.go, alicloud/data_source_alicloud_kms_plaintext.go, alicloud/data_source_alicloud_kms_secret_versions.go, alicloud/data_source_alicloud_kms_secrets.go, alicloud/data_source_alicloud_kms_service.go, alicloud/resource_alicloud_db_instance.go, alicloud/resource_alicloud_kms_alias.go, alicloud/resource_alicloud_kms_alias_test.go, alicloud/resource_alicloud_kms_application_access_point.go, alicloud/resource_alicloud_kms_ciphertext.go, alicloud/resource_alicloud_kms_client_key.go, alicloud/resource_alicloud_kms_key.go, alicloud/resource_alicloud_kms_key_test.go, alicloud/resource_alicloud_kms_key_version.go, alicloud/resource_alicloud_kms_network_rule.go, alicloud/resource_alicloud_kms_policy.go, alicloud/resource_alicloud_kms_secret.go, alicloud/resource_alicloud_kms_secret_test.go, alicloud/service_alicloud_kms.go, alicloud/service_alicloud_kms_v2.go, alicloud/service_alicloud_rds.go
=> Kms: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_scdn_domains.go, alicloud/resource_alicloud_scdn_domain.go, alicloud/resource_alicloud_scdn_domain_config.go, alicloud/resource_alicloud_scdn_domain_test.go, alicloud/service_alicloud_scdn.go
=> Scdn: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_data_works_folders.go, alicloud/resource_alicloud_data_works_data_source.go, alicloud/resource_alicloud_data_works_data_source_shared_rule.go, alicloud/resource_alicloud_data_works_data_source_shared_rule_test.go, alicloud/resource_alicloud_data_works_data_source_test.go, alicloud/resource_alicloud_data_works_di_alarm_rule.go, alicloud/resource_alicloud_data_works_di_alarm_rule_test.go, alicloud/resource_alicloud_data_works_di_job.go, alicloud/resource_alicloud_data_works_di_job_test.go, alicloud/resource_alicloud_data_works_dw_resource_group.go, alicloud/resource_alicloud_data_works_folder.go, alicloud/resource_alicloud_data_works_network.go, alicloud/resource_alicloud_data_works_project.go, alicloud/resource_alicloud_data_works_project_member.go, alicloud/service_alicloud_data_works_v2.go, alicloud/service_alicloud_dataworks_public.go
=> Dataworks: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_cdn_blocked_regions.go, alicloud/data_source_alicloud_cdn_ip_info.go, alicloud/data_source_alicloud_cdn_real_time_log_deliveries.go, alicloud/resource_alicloud_cdn_domain_config.go, alicloud/resource_alicloud_cdn_domain_new.go, alicloud/resource_alicloud_cdn_fc_trigger.go, alicloud/resource_alicloud_cdn_real_time_log_delivery.go, alicloud/service_alicloud_cdn.go, alicloud/service_alicloud_cdn_v2.go
=> Cdn: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_dfs_access_groups.go, alicloud/data_source_alicloud_dfs_access_rules.go, alicloud/data_source_alicloud_dfs_file_systems.go, alicloud/data_source_alicloud_dfs_mount_points.go, alicloud/data_source_alicloud_dfs_zones.go, alicloud/resource_alicloud_dfs_access_group_test.go, alicloud/resource_alicloud_dfs_file_system_test.go, alicloud/service_alicloud_dfs.go
=> DFS: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_iot_device_groups.go, alicloud/data_source_alicloud_iot_service.go, alicloud/resource_alicloud_iot_device_group.go, alicloud/resource_alicloud_iot_device_group_test.go, alicloud/service_alicloud_iot.go
=> iot: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_imm_projects.go, alicloud/resource_alicloud_imm_project.go, alicloud/resource_alicloud_imm_project_test.go, alicloud/service_alicloud_imm.go
=> imm: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_ens_key_pairs.go, alicloud/resource_alicloud_ens_disk.go, alicloud/resource_alicloud_ens_disk_instance_attachment.go, alicloud/resource_alicloud_ens_eip.go, alicloud/resource_alicloud_ens_eip_instance_attachment.go, alicloud/resource_alicloud_ens_image.go, alicloud/resource_alicloud_ens_instance.go, alicloud/resource_alicloud_ens_instance_security_group_attachment.go, alicloud/resource_alicloud_ens_key_pair.go, alicloud/resource_alicloud_ens_load_balancer.go, alicloud/resource_alicloud_ens_nat_gateway.go, alicloud/resource_alicloud_ens_network.go, alicloud/resource_alicloud_ens_security_group.go, alicloud/resource_alicloud_ens_snapshot.go, alicloud/resource_alicloud_ens_vswitch.go, alicloud/service_alicloud_ens.go, alicloud/service_alicloud_ens_v2.go
=> ENS: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_ehpc_clusters.go, alicloud/data_source_alicloud_ehpc_job_templates.go, alicloud/resource_alicloud_ehpc_cluster.go, alicloud/resource_alicloud_ehpc_cluster_test.go, alicloud/resource_alicloud_ehpc_job_template.go, alicloud/service_alicloud_ehpc.go
=> EHPC: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_rdc_organizations.go, alicloud/resource_alicloud_rdc_organization.go, alicloud/resource_alicloud_rdc_organization_test.go, alicloud/service_alicloud_devops_rdc.go
=> DevopsRdc: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_simple_application_server_custom_images.go, alicloud/data_source_alicloud_simple_application_server_disks.go, alicloud/data_source_alicloud_simple_application_server_firewall_rules.go, alicloud/data_source_alicloud_simple_application_server_images.go, alicloud/data_source_alicloud_simple_application_server_instances.go, alicloud/data_source_alicloud_simple_application_server_plans.go, alicloud/data_source_alicloud_simple_application_server_snapshots.go, alicloud/resource_alicloud_simple_application_server_custom_image.go, alicloud/resource_alicloud_simple_application_server_firewall_rule.go, alicloud/resource_alicloud_simple_application_server_instance.go, alicloud/resource_alicloud_simple_application_server_snapshot.go, alicloud/service_alicloud_swas_open.go
=> SimpleApplicationServer: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/endpoint.go, alicloud/data_source_alicloud_quick_bi_users.go, alicloud/resource_alicloud_quick_bi_user.go, alicloud/resource_alicloud_quick_bi_user_test.go, alicloud/service_alicloud_quickbi_public.go
=> quickbi: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_vod_domains.go, alicloud/resource_alicloud_vod_domain.go, alicloud/resource_alicloud_vod_editing_project.go, alicloud/service_alicloud_vod.go
=> VOD: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_video_surveillance_system_groups.go, alicloud/data_source_alicloud_vs_service.go, alicloud/resource_alicloud_video_surveillance_system_group.go, alicloud/service_alicloud_vs.go
=> vs: Improves the invoking api method and supports refreshing credential automatically

alicloud/resource_alicloud_ack_one_cluster.go, alicloud/resource_alicloud_ack_one_cluster_test.go, website/docs/r/ack_one_cluster.html.markdown
Support update argocd_enabled feature for resource alicloud_ack_one_cluster.
=> resource/alicloud_ack_one_cluster: support update argocd_enabled feature

website/docs/r/ack_one_cluster.html.markdown
Add available notes for argocd_enabled parameter
=> docs: add available note for argocd_enabled parameter

alicloud/data_source_alicloud_cr_chains.go, alicloud/data_source_alicloud_cr_chains_test.go, alicloud/data_source_alicloud_cr_chart_namespaces.go, alicloud/data_source_alicloud_cr_chart_repositories.go, alicloud/data_source_alicloud_cr_endpoint_acl_policies.go, alicloud/data_source_alicloud_cr_endpoint_acl_service.go, alicloud/data_source_alicloud_cr_vpc_endpoint_linked_vpcs.go, alicloud/resource_alicloud_cr_chain.go, alicloud/resource_alicloud_cr_chain_test.go, alicloud/resource_alicloud_cr_chart_namespace.go, alicloud/resource_alicloud_cr_chart_repository.go, alicloud/resource_alicloud_cr_ee_sync_rule.go, alicloud/resource_alicloud_cr_endpoint_acl_policy.go, alicloud/resource_alicloud_cr_vpc_endpoint_linked_vpc.go, alicloud/service_alicloud_cr.go, alicloud/service_alicloud_cr_v2.go
=> CR: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_maxcompute_projects.go, alicloud/data_source_alicloud_open_search_app_groups.go, alicloud/data_source_alicloud_sae_grey_tag_routes.go, alicloud/data_source_alicloud_sae_instance_specifications.go, alicloud/resource_alicloud_open_search_app_group.go, alicloud/resource_alicloud_open_search_app_group_test.go, alicloud/resource_alicloud_rocketmq_instance.go, alicloud/resource_alicloud_sae_grey_tag_route.go, alicloud/service_alicloud_max_compute_v2.go, alicloud/service_alicloud_maxcompute.go, alicloud/service_alicloud_open_search.go, alicloud/service_alicloud_rocketmq_v2.go, alicloud/service_alicloud_sae.go
=> OpenSearch: Improves the invoking api method and supports refreshing credential automatically

alicloud/provider.go, alicloud/resource_alicloud_ack_one_membership_attachment.go, alicloud/resource_alicloud_ack_one_membership_attachment_test.go, alicloud/service_alicloud_ack_one_v2.go, website/docs/r/ack_one_membership_attachment.html.markdown
Support AttachClusterToHub and DetachClusterFromHub for terraform integrations.
=> New Resource: alicloud_ack_one_membership_attachment

alicloud/resource_alicloud_ddos_basic_defense_threshold.go, alicloud/resource_alicloud_ddos_basic_threshold.go, alicloud/service_alicloud_antiddos_public.go
=> DdosBasic: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_smartag_flow_logs.go, alicloud/data_source_alicloud_smartag_flow_logs_test.go, alicloud/resource_alicloud_smartag_flow_log.go, alicloud/resource_alicloud_smartag_flow_log_test.go, alicloud/service_alicloud_sag.go
=> Smartag: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_edas_namespaces.go, alicloud/resource_alicloud_edas_namespace.go, alicloud/resource_alicloud_edas_namespace_test.go, alicloud/service_alicloud_edas.go
=> Edas: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_alikafka_instances.go, alicloud/data_source_alicloud_alikafka_topics.go, alicloud/resource_alicloud_alikafka_consumer_group.go, alicloud/resource_alicloud_alikafka_instance.go, alicloud/resource_alicloud_alikafka_instance_allowed_ip_attachment.go, alicloud/resource_alicloud_alikafka_sasl_user.go, alicloud/service_alicloud_alikafka.go
=> Alikafka: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_service_mesh_extension_providers.go, alicloud/data_source_alicloud_service_mesh_service_meshes.go, alicloud/data_source_alicloud_service_mesh_versions.go, alicloud/resource_alicloud_service_mesh_extension_provider.go, alicloud/resource_alicloud_service_mesh_service_mesh.go, alicloud/resource_alicloud_service_mesh_service_mesh_test.go, alicloud/resource_alicloud_service_mesh_user_permission.go, alicloud/service_alicloud_service_mesh_v2.go, alicloud/service_alicloud_servicemesh.go, website/docs/r/service_mesh_service_mesh.html.markdown
=> ServiceMesh: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_ess_scaling_groups.go, alicloud/data_source_alicloud_ess_scaling_rules.go, alicloud/resource_alicloud_ess_eci_scaling_configuration.go, alicloud/resource_alicloud_ess_eci_scaling_configuration_test.go, alicloud/resource_alicloud_ess_notification.go, alicloud/resource_alicloud_ess_scaling_configuration.go, alicloud/resource_alicloud_ess_scaling_group.go, alicloud/resource_alicloud_ess_scalinggroup_vserver_groups.go, alicloud/service_alicloud_ess.go
=> ESS: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/endpoint.go, alicloud/data_source_alicloud_ddosbgp_instances.go, alicloud/data_source_alicloud_ddosbgp_ips.go, alicloud/resource_alicloud_ddos_bgp_policy.go, alicloud/resource_alicloud_ddos_bgp_policy_test.go, alicloud/resource_alicloud_ddosbgp_ip.go, alicloud/service_alicloud_common_test.go, alicloud/service_alicloud_ddos_bgp_v2.go, alicloud/service_alicloud_ddosbgp.go
=> DdosBgp: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/connectivity/endpoint.go, alicloud/data_source_alicloud_api_gateway_backends.go, alicloud/data_source_alicloud_api_gateway_log_configs.go, alicloud/data_source_alicloud_api_gateway_models.go, alicloud/data_source_alicloud_api_gateway_plugins.go, alicloud/provider.go, alicloud/resource_alicloud_api_gateway_access_control_list.go, alicloud/resource_alicloud_api_gateway_acl_entry_attachment.go, alicloud/resource_alicloud_api_gateway_backend.go, alicloud/resource_alicloud_api_gateway_instance.go, alicloud/resource_alicloud_api_gateway_instance_acl_attachment.go, alicloud/resource_alicloud_api_gateway_log_config.go, alicloud/resource_alicloud_api_gateway_log_config_test.go, alicloud/resource_alicloud_api_gateway_model.go, alicloud/resource_alicloud_api_gateway_plugin.go, alicloud/resource_alicloud_api_gateway_plugin_attachment.go, alicloud/resource_alicloud_api_gateway_plugin_test.go, alicloud/service_alicloud_api_gateway.go, alicloud/service_alicloud_api_gateway_v2.go, alicloud/service_alicloud_cloud_api.go
=> ApiGateway: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_dbs_backup_plans.go, alicloud/data_source_alicloud_dbs_backup_plans_test.go, alicloud/resource_alicloud_dbs_backup_plan.go, alicloud/resource_alicloud_dbs_backup_plan_test.go, alicloud/service_alicloud_dbs.go
=> DBS: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_nlb_listeners.go, alicloud/data_source_alicloud_nlb_load_balancers.go, alicloud/data_source_alicloud_nlb_security_policies.go, alicloud/data_source_alicloud_nlb_server_group_server_attachments.go, alicloud/data_source_alicloud_nlb_server_groups.go, alicloud/data_source_alicloud_nlb_zones.go, alicloud/resource_alicloud_nlb_listener.go, alicloud/resource_alicloud_nlb_listener_additional_certificate_attachment.go, alicloud/resource_alicloud_nlb_load_balancer.go, alicloud/resource_alicloud_nlb_load_balancer_security_group_attachment.go, alicloud/resource_alicloud_nlb_load_balancer_test.go, alicloud/resource_alicloud_nlb_loadbalancer_common_bandwidth_package_attachment.go, alicloud/resource_alicloud_nlb_security_policy.go, alicloud/resource_alicloud_nlb_security_policy_test.go, alicloud/resource_alicloud_nlb_server_group.go, alicloud/resource_alicloud_nlb_server_group_server_attachment.go, alicloud/resource_alicloud_nlb_server_group_server_attachment_test.go, alicloud/resource_alicloud_nlb_server_group_test.go, alicloud/service_alicloud_nlb.go, alicloud/service_alicloud_nlb_v2.go
=> Nlb: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_ebs_dedicated_block_storage_clusters.go, alicloud/data_source_alicloud_ebs_disk_replica_groups.go, alicloud/data_source_alicloud_ebs_disk_replica_pairs.go, alicloud/data_source_alicloud_ebs_regions.go, alicloud/resource_alicloud_ebs_dedicated_block_storage_cluster.go, alicloud/resource_alicloud_ebs_disk_replica_group.go, alicloud/resource_alicloud_ebs_disk_replica_group_test.go, alicloud/resource_alicloud_ebs_disk_replica_pair.go, alicloud/resource_alicloud_ebs_enterprise_snapshot_policy.go, alicloud/resource_alicloud_ebs_enterprise_snapshot_policy_attachment.go, alicloud/resource_alicloud_ebs_replica_group_drill.go, alicloud/resource_alicloud_ebs_replica_pair_drill.go, alicloud/resource_alicloud_ebs_solution_instance.go, alicloud/service_alicloud_ebs.go, alicloud/service_alicloud_ebs_v2.go
=> Ebs: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_message_service_queues.go, alicloud/data_source_alicloud_message_service_subscriptions.go, alicloud/data_source_alicloud_message_service_topics.go, alicloud/resource_alicloud_message_service_queue.go, alicloud/resource_alicloud_message_service_queue_test.go, alicloud/resource_alicloud_message_service_subscription.go, alicloud/resource_alicloud_message_service_topic.go, alicloud/resource_alicloud_message_service_topic_test.go, alicloud/service_alicloud_message_service_v2.go, alicloud/service_alicloud_mns_open.go
=> MNS: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_service_catalog_end_user_products.go, alicloud/data_source_alicloud_service_catalog_launch_options.go, alicloud/data_source_alicloud_service_catalog_portfolios.go, alicloud/data_source_alicloud_service_catalog_product_as_end_users.go, alicloud/data_source_alicloud_service_catalog_product_versions.go, alicloud/data_source_alicloud_service_catalog_provisioned_products.go, alicloud/resource_alicloud_service_catalog_portfolio.go, alicloud/resource_alicloud_service_catalog_principal_portfolio_association.go, alicloud/resource_alicloud_service_catalog_product.go, alicloud/resource_alicloud_service_catalog_product_portfolio_association.go, alicloud/resource_alicloud_service_catalog_product_version.go, alicloud/resource_alicloud_service_catalog_provisioned_product.go, alicloud/service_alicloud_service_catalog_v2.go, alicloud/service_alicloud_servicecatalog.go
=> ServiceCatalog: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/connectivity/endpoint.go, alicloud/connectivity/helper.go, alicloud/provider.go, alicloud/resource_alicloud_fc_layer_version.go, alicloud/resource_alicloud_fcv2_function.go, alicloud/resource_alicloud_fcv2_function_test.go, alicloud/resource_alicloud_fcv3_alias.go, alicloud/resource_alicloud_fcv3_async_invoke_config.go, alicloud/resource_alicloud_fcv3_concurrency_config.go, alicloud/resource_alicloud_fcv3_custom_domain.go, alicloud/resource_alicloud_fcv3_function.go, alicloud/resource_alicloud_fcv3_function_version.go, alicloud/resource_alicloud_fcv3_layer_version.go, alicloud/resource_alicloud_fcv3_provision_config.go, alicloud/resource_alicloud_fcv3_trigger.go, alicloud/resource_alicloud_fcv3_trigger_test.go, alicloud/resource_alicloud_fcv3_vpc_binding.go, alicloud/service_alicloud_fc_open.go, alicloud/service_alicloud_fcv2_v2.go, alicloud/service_alicloud_fcv3_v2.go
=> FC: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/connectivity/endpoint.go, alicloud/provider.go, alicloud/resource_alicloud_apig_environment.go, alicloud/resource_alicloud_apig_gateway.go, alicloud/resource_alicloud_apig_http_api.go, alicloud/service_alicloud_apig_v2.go
=> ApiG: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_vpc_ipam_ipam_pool_allocations.go, alicloud/data_source_alicloud_vpc_ipam_ipam_pool_cidrs.go, alicloud/data_source_alicloud_vpc_ipam_ipam_pools.go, alicloud/data_source_alicloud_vpc_ipam_ipam_scopes.go, alicloud/data_source_alicloud_vpc_ipam_ipams.go, alicloud/resource_alicloud_vpc_ipam_ipam.go, alicloud/resource_alicloud_vpc_ipam_ipam_pool.go, alicloud/resource_alicloud_vpc_ipam_ipam_pool_allocation.go, alicloud/resource_alicloud_vpc_ipam_ipam_pool_cidr.go, alicloud/resource_alicloud_vpc_ipam_ipam_scope.go, alicloud/resource_alicloud_vpc_ipam_service.go, alicloud/service_alicloud_vpc_ipam_v2.go
=> VpcIpam: Improves the invoking api method and supports refreshing credential automatically

alicloud/data_source_alicloud_gwlb_zones.go, alicloud/resource_alicloud_gwlb_listener.go, alicloud/resource_alicloud_gwlb_load_balancer.go, alicloud/resource_alicloud_gwlb_server_group.go, alicloud/service_alicloud_gwlb_v2.go
=> Gwlb: Improves the invoking api method and supports refreshing credential automatically

alicloud/resource_alicloud_esa_http_request_header_modification_rule.go, alicloud/resource_alicloud_esa_http_response_header_modification_rule.go, alicloud/resource_alicloud_esa_list.go, alicloud/resource_alicloud_esa_page.go, alicloud/resource_alicloud_esa_record.go, alicloud/resource_alicloud_esa_redirect_rule.go, alicloud/resource_alicloud_esa_rewrite_url_rule.go, alicloud/service_alicloud_esa_v2.go
=> ESA: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_chatbot_agents.go, alicloud/resource_alicloud_chatbot_publish_task.go, alicloud/service_alicloud_chatbot.go
=> Chatbot: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/resource_alicloud_pai_service.go, alicloud/resource_alicloud_pai_service_test.go, alicloud/resource_alicloud_pai_workspace_code_source.go, alicloud/resource_alicloud_pai_workspace_dataset.go, alicloud/resource_alicloud_pai_workspace_datasetversion.go, alicloud/resource_alicloud_pai_workspace_experiment.go, alicloud/resource_alicloud_pai_workspace_run.go, alicloud/resource_alicloud_pai_workspace_workspace.go, alicloud/service_alicloud_pai_v2.go, alicloud/service_alicloud_pai_workspace_v2.go
=> Pai: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_compute_nest_service_instances.go, alicloud/resource_alicloud_compute_nest_service_instance.go, alicloud/service_alicloud_compute_nest.go
=> ComputeNest: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/resource_alicloud_rocketmq_consumer_group.go, alicloud/resource_alicloud_rocketmq_instance_test.go, alicloud/resource_alicloud_rocketmq_topic.go, alicloud/service_alicloud_rocketmq_v2.go
=> RocketMQ: Improves the invoking api method and supports refreshing credential automatically

website/docs/r/nlb_server_group.html.markdown
=> docs: Updates the resource alicloud_nlb_server_group attribute preserve_client_ip_enabled default to true in docs

alicloud/connectivity/client.go, alicloud/data_source_alicloud_cms_alarm_contact_groups.go, alicloud/data_source_alicloud_ddosbgp_instances.go, alicloud/data_source_alicloud_edas_applications.go, alicloud/data_source_alicloud_ess_alarms.go, alicloud/data_source_alicloud_hbase_instance_types.go, alicloud/data_source_alicloud_images.go, alicloud/data_source_alicloud_instance_type_families.go, alicloud/data_source_alicloud_kvstore_zones.go, alicloud/data_source_alicloud_polardb_zones.go, alicloud/data_source_alicloud_route_entries.go, alicloud/data_source_alicloud_slb_zones.go, alicloud/resource_alicloud_ddoscoo_instance.go, alicloud/service_alicloud_ddoscoo.go
=> client: more product client supports refresh credentials automatically and improves the getting endpoint method

alicloud/connectivity/client.go, alicloud/resource_alicloud_ack_one_cluster.go, alicloud/resource_alicloud_ack_one_membership_attachment.go, alicloud/service_alicloud_ack_one_v2.go
=> AckOne: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/resource_alicloud_hologram_instance.go, alicloud/service_alicloud_hologram_v2.go
=> Hologram: Improves the invoking api method and supports refreshing credential automatically

website/docs/r/ack_one_membership_attachment.html.markdown
Modify available version info of ack one membership attachment
=> docs: modify available version info of membership attachment

alicloud/connectivity/client.go, alicloud/connectivity/endpoint.go, alicloud/resource_alicloud_yundun_dbaudit_instance.go, alicloud/resource_alicloud_yundun_dbaudit_instance_test.go, alicloud/service_alicloud_yundun_dbaudit.go
=> resource/alicloud_yundun_dbaudit_instance: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/connectivity/endpoint.go, alicloud/data_source_alicloud_mongodb_accounts.go, alicloud/data_source_alicloud_mongodb_serverless_instances.go, alicloud/data_source_alicloud_mongodb_sharding_network_private_addresses.go, alicloud/data_source_alicloud_mongodb_sharding_network_public_addresses.go, alicloud/resource_alicloud_mongodb_account.go, alicloud/resource_alicloud_mongodb_audit_policy.go, alicloud/resource_alicloud_mongodb_instance.go, alicloud/resource_alicloud_mongodb_instance_test.go, alicloud/resource_alicloud_mongodb_private_srv_network_address.go, alicloud/resource_alicloud_mongodb_serverless_instance.go, alicloud/resource_alicloud_mongodb_sharding_instance.go, alicloud/resource_alicloud_mongodb_sharding_instance_test.go, alicloud/resource_alicloud_mongodb_sharding_network_private_address.go, alicloud/resource_alicloud_mongodb_sharding_network_public_address.go, alicloud/service_alicloud_mongodb.go, alicloud/service_alicloud_mongodb_v2.go
=> MongoDB: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_emr_clusters.go, alicloud/data_source_alicloud_emr_main_versions.go, alicloud/data_source_alicloud_emrv2_clusters.go, alicloud/resource_alicloud_emr_cluster.go, alicloud/resource_alicloud_emrv2_cluster.go, alicloud/resource_alicloud_emrv2_cluster_test.go, alicloud/service_alicloud_emr.go
=> Emr: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/resource_alicloud_elasticsearch_instance.go, alicloud/service_alicloud_elasticsearch.go
=> ElasticSearch: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/data_source_alicloud_gpdb_accounts.go, alicloud/data_source_alicloud_gpdb_data_backups.go, alicloud/data_source_alicloud_gpdb_db_instance_plans.go, alicloud/data_source_alicloud_gpdb_instances.go, alicloud/data_source_alicloud_gpdb_log_backups.go, alicloud/resource_alicloud_gpdb_account.go, alicloud/resource_alicloud_gpdb_backup_policy.go, alicloud/resource_alicloud_gpdb_database.go, alicloud/resource_alicloud_gpdb_db_instance_ip_array.go, alicloud/resource_alicloud_gpdb_db_instance_plan.go, alicloud/resource_alicloud_gpdb_db_resource_group.go, alicloud/resource_alicloud_gpdb_elastic_instance.go, alicloud/resource_alicloud_gpdb_external_data_service.go, alicloud/resource_alicloud_gpdb_hadoop_data_source.go, alicloud/resource_alicloud_gpdb_instance.go, alicloud/resource_alicloud_gpdb_instance_test.go, alicloud/resource_alicloud_gpdb_jdbc_data_source.go, alicloud/resource_alicloud_gpdb_remote_adb_data_source.go, alicloud/resource_alicloud_gpdb_streaming_data_service.go, alicloud/resource_alicloud_gpdb_streaming_data_source.go, alicloud/resource_alicloud_gpdb_streaming_job.go, alicloud/service_alicloud_gpdb.go, alicloud/service_alicloud_gpdb_v2.go
=> GPDB: Improves the invoking api method and supports refreshing credential automatically

alicloud/resource_alicloud_db_instance.go, website/docs/r/db_instance.html.markdown
=> resource/alicloud_db_instance: sql_collector_config_value insert diffSuppressFunc

alicloud/data_source_alicloud_emrv2_cluster_instances.go, alicloud/data_source_alicloud_emrv2_cluster_instances_test.go, alicloud/provider.go, alicloud/service_alicloud_emr.go, website/docs/d/emrv2_cluster_instances.html.markdown
New Data Source: alicloud_emrv2_cluster_instances
=> New Data Source: alicloud_emrv2_cluster_instances

alicloud/resource_alicloud_emrv2_cluster.go, alicloud/resource_alicloud_emrv2_cluster_test.go, alicloud/service_alicloud_emr.go, website/docs/r/emrv2_cluster.html.markdown
resource/alicloud_emrv2_cluster: add node attributes:system_disk_encrypted and system_disk_kms_key_id
=> resource/alicloud_emrv2_cluster: add node attributes:system_disk_encrypted and system_disk_kms_key_id

website/docs/r/nlb_server_group.html.markdown
=> docs: corrects the resource alicloud_nlb_server_group argument preserve_client_ip_enabled default, and add a note

alicloud/connectivity/client.go, alicloud/connectivity/endpoint.go, alicloud/data_source_alicloud_cloud_control_prices.go, alicloud/data_source_alicloud_cloud_control_products.go, alicloud/data_source_alicloud_cloud_control_resource_types.go, alicloud/resource_alicloud_cloud_control_resource.go, alicloud/resource_alicloud_cloud_control_resource_test.go, alicloud/service_alicloud_cloud_control_v2.go
=> CloudControl: Improves the invoking api method and supports refreshing credential automatically

alicloud/connectivity/client.go, alicloud/connectivity/endpoint.go, alicloud/data_source_alicloud_bp_studio_applications.go, alicloud/data_source_alicloud_bp_studio_applications_test.go, alicloud/resource_alicloud_bp_studio_application.go, alicloud/resource_alicloud_bp_studio_application_test.go, alicloud/service_alicloud_bp_studio.go
=> BPStudio: Improves the invoking api method and supports refreshing credential automatically

alicloud/provider.go, website/docs/index.html.markdown
=> provider: argument oidc_token supports environment variable ALIBABA_CLOUD_OIDC_TOKEN

alicloud/alicloud_sweeper_test.go, alicloud/common.go, alicloud/connectivity/client.go, alicloud/connectivity/config.go, alicloud/resource_alicloud_oss_access_point.go, alicloud/resource_alicloud_oss_account_public_access_block.go, alicloud/resource_alicloud_oss_bucket_access_monitor.go, alicloud/resource_alicloud_oss_bucket_acl.go, alicloud/resource_alicloud_oss_bucket_cname.go, alicloud/resource_alicloud_oss_bucket_cname_test.go, alicloud/resource_alicloud_oss_bucket_cname_token.go, alicloud/resource_alicloud_oss_bucket_cors.go, alicloud/resource_alicloud_oss_bucket_data_redundancy_transition.go, alicloud/resource_alicloud_oss_bucket_https_config.go, alicloud/resource_alicloud_oss_bucket_logging.go, alicloud/resource_alicloud_oss_bucket_meta_query.go, alicloud/resource_alicloud_oss_bucket_policy.go, alicloud/resource_alicloud_oss_bucket_public_access_block.go, alicloud/resource_alicloud_oss_bucket_referer.go, alicloud/resource_alicloud_oss_bucket_request_payment.go, alicloud/resource_alicloud_oss_bucket_server_side_encryption.go, alicloud/resource_alicloud_oss_bucket_transfer_acceleration.go, alicloud/resource_alicloud_oss_bucket_user_defined_log_fields.go, alicloud/resource_alicloud_oss_bucket_versioning.go, alicloud/resource_alicloud_oss_bucket_website.go, alicloud/resource_alicloud_oss_bucket_worm.go, alicloud/service_alicloud_oss_v2.go, website/docs/r/oss_access_point.html.markdown
=> Oss: Improves the invoking api method and supports refreshing credential automatically

alicloud/common.go, alicloud/connectivity/client.go, alicloud/data_source_alicloud_log_alert_resource.go, alicloud/resource_alicloud_log_project.go, alicloud/resource_alicloud_log_store.go, alicloud/resource_alicloud_sls_alert.go, alicloud/resource_alicloud_sls_collection_policy.go, alicloud/resource_alicloud_sls_oss_export_sink.go, alicloud/resource_alicloud_sls_scheduled_sql.go, alicloud/service_alicloud_sls_v2.go
=> Sls: Improves the invoking api method and supports refreshing credential automatically

alicloud/resource_alicloud_ess_scheduled_task.go, alicloud/resource_alicloud_ess_scheduled_task_test.go
resource/alicloud_ess_scheduled_task: fix desired_capacity set zero.
=> resource/alicloud_ess_scheduled_task: fix desired_capacity set zero.

alicloud/common.go, alicloud/connectivity/client.go, alicloud/data_source_alicloud_quotas_quota_alarms.go, alicloud/data_source_alicloud_quotas_quota_applications.go, alicloud/data_source_alicloud_quotas_quota_applications_test.go, alicloud/data_source_alicloud_quotas_quotas.go, alicloud/data_source_alicloud_quotas_template_applications.go, alicloud/resource_alicloud_quotas_quota_alarm.go, alicloud/resource_alicloud_quotas_quota_application.go, alicloud/resource_alicloud_quotas_template_applications.go, alicloud/resource_alicloud_quotas_template_applications_test.go, alicloud/resource_alicloud_quotas_template_quota.go, alicloud/service_alicloud_quotas.go, alicloud/service_alicloud_quotas_v2.go
=> Quotas: Improves the invoking api method and supports refreshing credential automatically

alicloud/resource_alicloud_ros_stack.go, alicloud/service_alicloud_ros.go
=> resource/alicloud_ros_stack: Fixes the Throttling.User error when refreshing the resource state

alicloud/connectivity/client.go, alicloud/resource_alicloud_cdn_domain_new.go
=> resource/alicloud_cdn_domain_new: Fixes the SSLPri.MissingParameter error when updateing the certificate_config

alicloud/resource_alicloud_oos_execution.go
=> resource/alicloud_oos_execution: Improves the waiting status(Success, Failed, Cancelled, Skipped) after creating the resource

alicloud/resource_alicloud_ess_scaling_rule.go, alicloud/resource_alicloud_ess_scaling_rule_test.go, alicloud/service_alicloud_ess.go, website/docs/r/ess_scaling_rule.html.markdown
…namespace, hybrid_metrics and metric_type.
=> resource/alicloud_ess_scaling_rule: add attributef of hybrid_monitor_namespace, hybrid_metrics and metric_type.

alicloud/resource_alicloud_alikafka_sasl_acl.go, alicloud/resource_alicloud_alikafka_sasl_acl_test.go, alicloud/service_alicloud_alikafka.go
=> resource/alicloud_alikafka_sasl_acl: Fixes the resource not error when the user_name is *

alicloud/resource_alicloud_api_gateway_instance.go, website/docs/r/api_gateway_instance.html.markdown
resource/alicloud_api_gateway_instance: Fixed error when ingress_vpc_id is not set
=> resource/alicloud_api_gateway_instance: Fixed error when ingress_vpc_id is not set

alicloud/resource_alicloud_api_gateway_group.go, alicloud/resource_alicloud_api_gateway_group_test.go, website/docs/r/api_gateway_group.html.markdown
resource/alicloud_api_gateway_group: Supports enable vpc intranet domain.
=> resource/alicloud_api_gateway_group: Supports enable vpc intranet domain.

alicloud/data_source_alicloud_threat_detection_assets.go, website/docs/d/threat_detection_assets.html.markdown
=> data-source/alicloud_threat_detection_assets: Adds more attributes for instance and cluster

alicloud/connectivity/regions.go, alicloud/diff_suppress_funcs.go, alicloud/resource_alicloud_polardb_cluster.go, alicloud/resource_alicloud_polardb_cluster_test.go, alicloud/service_alicloud_polardb.go, website/docs/r/polardb_cluster.html.markdown
resource/alicloud_polardb_cluster: support hot_standby_cluster equal and standby_az
=> resource/alicloud_polardb_cluster: support hot_standby_cluster equal and standby_az

alicloud/resource_alicloud_elasticsearch_instance.go, alicloud/resource_alicloud_elasticsearch_instance_test.go, website/docs/r/elasticsearch_instance.html.markdown
=> resource/alicloud_elasticsearch_instance: bugfix the API setRenewalInstance 

alicloud/resource_alicloud_dts_instance.go, alicloud/resource_alicloud_dts_synchronization_instance.go, alicloud/resource_alicloud_dts_synchronization_job.go, alicloud/resource_alicloud_dts_synchronization_job_test.go
resource/alicloud_dts_synchronization_instance: support more values for instance_class enum
=>  resource/alicloud_dts_synchronization_instance: support more values for instance_class enum

alicloud/resource_alicloud_rds_clone_db_instance.go, alicloud/resource_alicloud_rds_clone_db_instance_test.go, website/docs/r/rds_clone_db_instance.html.markdown
=> resource/alicloud_rds_clone_db_instance: db_instance_storage_type insert general_essd

alicloud/service_alicloud_polardb.go
resource/alicloud_polardb_cluster: fix ip array diff crash issue
=> resource/alicloud_polardb_cluster: fix ip array diff crash issue

alicloud/resource_alicloud_click_house_db_cluster.go, alicloud/resource_alicloud_click_house_db_cluster_test.go
resource/alicloud_click_house_db_cluster: add support for cluster version 25.3.
=> resource/alicloud_click_house_db_cluster: add support for cluster version 25.3.

alicloud/resource_alicloud_emrv2_cluster.go, alicloud/resource_alicloud_emrv2_cluster_test.go
=> resource/alicloud_emrv2_cluster: Optimize the emr cluster bootstrap scripts management
