aliyun/terraform-provider-alicloud

- CHANGELOG.md
The PR modify CHANGELOG for releasing version 1.0.0
> change log for release 1.0.0

- CHANGELOG.md
> change CHANGELOG

- README.md
- alicloud/resource_alicloud_instance.go
The PR removes diffsuppress function to avoid needless  error.
> remove diff for avoid error

- CHANGELOG.md
- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_instance.go
The PR fix a bug that creating 'prepaid' rds instnace.
> fix creating rds Prepaid instance failed error

- CHANGELOG.md
- alicloud/config.go
- alicloud/errors.go
- alicloud/resource_alicloud_dns_record.go
The PR fix a oss service bug that can't retrieve endpoint using region id.
> fix getting OSS endpoint failed error

- CHANGELOG.md
- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_instance.go
- alicloud/resource_alicloud_instance_test.go
- alicloud/validators.go
- website/docs/r/instance.html.markdown
This PR can support to create spot instance in alicloud.
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudInstance_spot -timeout 120m
=== RUN   TestAccAlicloudInstance_spot
--- PASS: TestAccAlicloudInstance_spot (125.01s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  125.045s
> support spot instance

- CHANGELOG.md
- alicloud/errors.go
- alicloud/import_alicloud_slb_rule_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_slb_rule.go
- alicloud/resource_alicloud_slb_rule_test.go
- alicloud/resource_alicloud_slb_server_group.go
- alicloud/service_alicloud_slb.go
- website/docs/r/slb_rule.html.markdown
- website/docs/r/slb_server_group.html.markdown
The PR provides a new resource alicloud_slb_rule that can add a forwarding rule in the specified listener for one load balancer.
The result of running test case as following:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlbRule -timeout 120m
=== RUN   TestAccAlicloudSlbRule_import
--- PASS: TestAccAlicloudSlbRule_import (132.88s)
=== RUN   TestAccAlicloudSlbRule_basic
--- PASS: TestAccAlicloudSlbRule_basic (130.92s)
=== RUN   TestAccAlicloudSlbRule_url
--- PASS: TestAccAlicloudSlbRule_url (137.20s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  401.044s
> new resource alicloud_slb_rule

- CHANGELOG.md
- vendor/github.com/denverdino/aliyungo/cs/client.go
- vendor/github.com/denverdino/aliyungo/cs/signature.go
- vendor/vendor.json
- website/docs/r/instance.html.markdown
The PR fixes a bug that creating cluster container failed result from SDK error.
> fix creating cluster container failed bug

- CHANGELOG.md
- alicloud/diff_suppress_funcs.go
- alicloud/errors.go
- alicloud/resource_alicloud_container_cluster.go
- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_db_instance_test.go
- alicloud/validators.go
- vendor/github.com/denverdino/aliyungo/rds/instances.go
- vendor/vendor.json
- website/docs/r/container_cluster.html.markdown
- website/docs/r/db_instance.html.markdown
This PR add a rule to avoid container cluster cidr block conflicts with vswitch's.
> Avoid container cluster cidr block conflicts with vswitch

- CHANGELOG.md
- alicloud/config.go
- alicloud/errors.go
- alicloud/extension_kms.go
- alicloud/import_alicloud_kms_key_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_kms_key.go
- alicloud/resource_alicloud_kms_key_test.go
- alicloud/validators.go
- vendor/github.com/denverdino/aliyungo/kms/client.go
- vendor/github.com/denverdino/aliyungo/kms/decrypt.go
- vendor/github.com/denverdino/aliyungo/kms/encrypt.go
- vendor/github.com/denverdino/aliyungo/kms/keys.go
- vendor/github.com/denverdino/aliyungo/kms/regions.go
- vendor/vendor.json
- website/alicloud.erb
- website/docs/r/kms_key.html.markdown
The PR adds a new resource alicloud_kms_key.
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudKmsKey -timeout 120m
=== RUN   TestAccAlicloudKmsKey_import
--- PASS: TestAccAlicloudKmsKey_import (12.63s)
=== RUN   TestAccAlicloudKmsKey_basic
--- PASS: TestAccAlicloudKmsKey_basic (19.77s)
PASS
ok    github.com/alibaba/terraform-provider/alicloud  32.465s
> add new resource alicloud_kms_key

- CHANGELOG.md
- alicloud/errors.go
- alicloud/resource_alicloud_eip_association.go
- alicloud/resource_alicloud_eip_association_test.go
- alicloud/resource_alicloud_nat_gateway.go
- vendor/github.com/denverdino/aliyungo/ecs/networks.go
- vendor/github.com/denverdino/aliyungo/ess/group.go
- vendor/vendor.json
- website/docs/r/eip_association.html.markdown
The PR has supported to associate EIP with SLB and Nat Gateway.
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEIPAssociation_natgateway -timeout 120m
=== RUN   TestAccAlicloudEIPAssociation_natgateway
--- PASS: TestAccAlicloudEIPAssociation_natgateway (52.30s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  52.337s
> Support to associate EIP with SLB and Nat Gateway

- CHANGELOG.md
- alicloud/errors.go
- alicloud/resource_alicloud_eip_association.go
- alicloud/resource_alicloud_ess_scalingconfiguration.go
- alicloud/resource_alicloud_nat_gateway.go
- alicloud/resource_alicloud_slb_attachment.go
- alicloud/resource_alicloud_vpc.go
- alicloud/resource_alicloud_vswitch.go
- vendor/github.com/denverdino/aliyungo/ess/configuration.go
- vendor/vendor.json
- website/docs/r/ess_scaling_configuration.html.markdown
- website/docs/r/nat_gateway.html.markdown
The PR supports to set internet_max_bandwidth_out is 0 for ESS configuration.
The PR has a pre-pr #102
> Support to set internet_max_bandwidth_out is 0 for ESS configuration 

- CHANGELOG.md
- alicloud/resource_alicloud_ess_scalingconfiguration.go
- alicloud/resource_alicloud_ess_scalingconfiguration_test.go
- vendor/github.com/denverdino/aliyungo/ess/configuration.go
- vendor/vendor.json
- website/docs/r/ess_scaling_configuration.html.markdown
The pr supports to  set instance_name for ESS scaling configuration.
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEssScalingConfiguration_enable -timeout 120m
=== RUN   TestAccAlicloudEssScalingConfiguration_enable
--- PASS: TestAccAlicloudEssScalingConfiguration_enable (144.56s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  144.602s
> Support setting instance_name for ESS scaling configuration

- .travis.yml
- CHANGELOG.md
- README.md
The PR modify go version to 1.9 and prepare for the new sdk.
> Support golang version 1.9

- CHANGELOG.md
- alicloud/common.go
- alicloud/data_source_alicloud_zones.go
- alicloud/data_source_alicloud_zones_test.go
- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_db_instance_test.go
- website/docs/d/zones.html.markdown
- website/docs/r/db_instance.html.markdown
The PR support to create rds in the multiple zone.
The pr has a pre pr #119 
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDBInstance_multiAZ -timeout 120m
=== RUN   TestAccAlicloudDBInstance_multiAZ
--- PASS: TestAccAlicloudDBInstance_multiAZ (365.58s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  365.621s
>  DB instance supports multiple zone

- CHANGELOG.md
- alicloud/service_alicloud_rds.go
The PR fixes a bug that db instance is not found when allocating a public connection for it.
> Fix not found db instance bug when allocating connection

- website/docs/r/cs_kubernetes.html.markdown
Fixes a typo of Kubernetes in the documentation
> fix misspelling of Kubernetes

- CHANGELOG.md
- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_swarm.go
- alicloud/service_alicloud_ecs.go
- website/docs/r/cs_kubernetes.html.markdown
- website/docs/r/cs_swarm.html.markdown
The pr add field 'is_outdated' for cs_swarm and cs_kubernetes and allow container creating outdated instance type.
>  Add is_outdated for cs_swarm and cs_kubernetes

- CHANGELOG.md
- alicloud/errors.go
- alicloud/extension_rds.go
- alicloud/import_alicloud_cs_swarm_test.go
- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_swarm.go
- alicloud/resource_alicloud_cs_swarm_test.go
- alicloud/resource_alicloud_db_database.go
- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_vpc.go
- alicloud/service_alicloud_ecs.go
- alicloud/service_alicloud_vpc.go
- alicloud/validators.go
- website/docs/r/cs_kubernetes.html.markdown
- website/docs/r/cs_swarm.html.markdown
- website/docs/r/db_database.html.markdown
The PR modifies swarm ID location and to avoid repeating  to create a swarm cluster.
The PR has a pre-PR: #133 
The result of running test case as following:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCSSwarm -timeout=120m
=== RUN   TestAccAlicloudCSSwarm_importBasic
--- PASS: TestAccAlicloudCSSwarm_importBasic (378.17s)
--- PASS: TestAccAlicloudCSSwarm_vpc (406.28s)
--- PASS: TestAccAlicloudCSSwarm_update (671.97s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  1456.478s
>  Set swarm ID before waiting its status

- CHANGELOG.md
- alicloud/import_alicloud_cs_kubernetes_test.go
- alicloud/import_alicloud_cs_swarm_test.go
- alicloud/resource_alicloud_cs_application.go
- alicloud/resource_alicloud_cs_application_test.go
- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_kubernetes_test.go
- alicloud/resource_alicloud_cs_swarm.go
- alicloud/resource_alicloud_cs_swarm_test.go
- alicloud/service_alicloud_ecs.go
- vendor/github.com/denverdino/aliyungo/cdn/client.go
- vendor/github.com/denverdino/aliyungo/cdn/refresh.go
- vendor/github.com/denverdino/aliyungo/cdn/types.go
- vendor/github.com/denverdino/aliyungo/cs/client.go
- vendor/github.com/denverdino/aliyungo/cs/clusters.go
- vendor/github.com/denverdino/aliyungo/cs/projects.go
- vendor/github.com/denverdino/aliyungo/cs/projects_client.go
- vendor/github.com/denverdino/aliyungo/cs/signature.go
- vendor/github.com/denverdino/aliyungo/dns/client.go
- vendor/github.com/denverdino/aliyungo/ecs/router_interface.go
- vendor/github.com/denverdino/aliyungo/ess/configuration.go
- vendor/github.com/denverdino/aliyungo/ess/group.go
- vendor/github.com/denverdino/aliyungo/rds/instances.go
- vendor/github.com/denverdino/aliyungo/slb/loadbalancers.go
- vendor/vendor.json
- website/docs/r/cs_kubernetes.html.markdown
- website/docs/r/cs_swarm.html.markdown
This PR aims to output container cluster swarm and kubernetes's nodes information and other more attribution.
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCSSwarm -timeout=1m
=== RUN   TestAccAlicloudCSSwarm_importBasic
--- PASS: TestAccAlicloudCSSwarm_importBasic (393.42s)
--- PASS: TestAccAlicloudCSSwarm_vpc (398.40s)
--- PASS: TestAccAlicloudCSSwarm_update (672.22s)
PASS
> Output swarm and kubernetes's nodes information and other attribution

- CHANGELOG.md
- alicloud/import_alicloud_cs_kubernetes_test.go
- alicloud/import_alicloud_cs_swarm_test.go
- alicloud/resource_alicloud_cs_application.go
- alicloud/resource_alicloud_cs_application_test.go
- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_kubernetes_test.go
- alicloud/resource_alicloud_cs_swarm.go
- alicloud/resource_alicloud_cs_swarm_test.go
- alicloud/service_alicloud_ecs.go
- vendor/github.com/denverdino/aliyungo/cdn/client.go
- vendor/github.com/denverdino/aliyungo/cdn/refresh.go
- vendor/github.com/denverdino/aliyungo/cdn/types.go
- vendor/github.com/denverdino/aliyungo/cs/client.go
- vendor/github.com/denverdino/aliyungo/cs/clusters.go
- vendor/github.com/denverdino/aliyungo/cs/projects.go
- vendor/github.com/denverdino/aliyungo/cs/projects_client.go
- vendor/github.com/denverdino/aliyungo/cs/signature.go
- vendor/github.com/denverdino/aliyungo/dns/client.go
- vendor/github.com/denverdino/aliyungo/ecs/router_interface.go
- vendor/github.com/denverdino/aliyungo/ess/configuration.go
- vendor/github.com/denverdino/aliyungo/ess/group.go
- vendor/github.com/denverdino/aliyungo/rds/instances.go
- vendor/github.com/denverdino/aliyungo/slb/loadbalancers.go
- vendor/vendor.json
- website/docs/r/cs_kubernetes.html.markdown
- website/docs/r/cs_swarm.html.markdown
The pr support to release eip after deploying swarm cluster.
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCSSwarm -timeout=120m
=== RUN   TestAccAlicloudCSSwarm_importBasic
--- PASS: TestAccAlicloudCSSwarm_importBasic (385.18s)
--- PASS: TestAccAlicloudCSSwarm_vpc (386.47s)
--- PASS: TestAccAlicloudCSSwarm_update (668.66s)
PASS
ok  	github.com/alibaba/terraform-provider/alicloud	1440.353s
> Support to release eip after deploying swarm cluster

- CHANGELOG.md
- alicloud/data_source_alicloud_db_instances.go
- alicloud/diff_suppress_funcs.go
- alicloud/extension_ecs.go
- alicloud/resource_alicloud_instance.go
- alicloud/service_alicloud_ecs.go
- alicloud/validators.go
- vendor/github.com/denverdino/aliyungo/ecs/instances.go
- vendor/vendor.json
- website/docs/r/cs_kubernetes.html.markdown
- website/docs/r/db_database.html.markdown
- website/docs/r/instance.html.markdown
- website/docs/r/slb_listener.html.markdown
This PR amis to support to set auto renew for prepaid ECS instance.
> Support to set auto renew for ECS instance

- CHANGELOG.md
- alicloud/common.go
- alicloud/data_source_alicloud_common.go
- alicloud/extension_ecs.go
- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_kubernetes_test.go
- alicloud/service_alicloud_ecs.go
- examples/kubernetes-wordpress/LICENSE
- examples/kubernetes-wordpress/README.md
- examples/kubernetes-wordpress/localvolumes.tf
- examples/kubernetes-wordpress/mysql.tf
- examples/kubernetes-wordpress/outputs.tf
- examples/kubernetes-wordpress/variables.tf
- examples/kubernetes-wordpress/wordpress.tf
- vendor/github.com/denverdino/aliyungo/cs/client.go
- vendor/github.com/denverdino/aliyungo/cs/clusters.go
- vendor/github.com/denverdino/aliyungo/cs/registry.go
- vendor/vendor.json
- website/docs/r/cs_kubernetes.html.markdown
The PR add a function that resource cs_kubernetes can support output worker nodes and master nodes.
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCSKubernetes -timeout=120m
=== RUN   TestAccAlicloudCSKubernetes_import
--- PASS: TestAccAlicloudCSKubernetes_import (1339.70s)
=== RUN   TestAccAlicloudCSKubernetes_basic
--- PASS: TestAccAlicloudCSKubernetes_basic (1267.74s)
=== RUN   TestAccAlicloudCSKubernetes_autoVpc
--- PASS: TestAccAlicloudCSKubernetes_autoVpc (1360.68s)
PASS
ok	github.com/alibaba/terraform-provider/alicloud	3968.590s
>  cs_kubernetes supports output worker nodes and master nodes

- CHANGELOG.md
- alicloud/errors.go
- alicloud/import_alicloud_log_machine_group_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_log_machine_group.go
- alicloud/resource_alicloud_log_machine_group_test.go
- alicloud/service_alicloud_log.go
- website/alicloud.erb
- website/docs/r/log_machine_group.html.markdown
- website/docs/r/log_store.html.markdown
- website/docs/r/log_store_index.html.markdown
The result of running test as follows:
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudLogMachineGroup_ -timeout=120m
--- PASS: TestAccAlicloudLogMachineGroup_import (4.45s)
--- PASS: TestAccAlicloudLogMachineGroup_ip (3.22s)
--- PASS: TestAccAlicloudLogMachineGroup_userdefined (12.10s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  19.831s
```
> new resource alicloud_log_machine_group

- CHANGELOG.md
- alicloud/import_alicloud_log_machine_group_test.go
- alicloud/import_alicloud_log_store_index_test.go
- alicloud/resource_alicloud_log_machine_group_test.go
- alicloud/resource_alicloud_log_store_index_test.go
- alicloud/resource_alicloud_log_store_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudLog -timeout=600m
--- PASS: TestAccAlicloudLogMachineGroup_import (29.72s)
=== RUN   TestAccAlicloudLogProject_import
--- PASS: TestAccAlicloudLogProject_import (29.59s)
=== RUN   TestAccAlicloudLogStoreIndex_importFull
--- PASS: TestAccAlicloudLogStoreIndex_importFull (12.59s)
=== RUN   TestAccAlicloudLogStoreIndex_importField
--- PASS: TestAccAlicloudLogStoreIndex_importField (20.30s)
=== RUN   TestAccAlicloudLogStore_import
--- PASS: TestAccAlicloudLogStore_import (19.98s)
--- PASS: TestAccAlicloudLogMachineGroup_ip (10.27s)
--- PASS: TestAccAlicloudLogMachineGroup_userdefined (11.72s)
=== …
```
> Improve log resource test case

- CHANGELOG.md
- alicloud/import_alicloud_log_machine_group_test.go
- alicloud/import_alicloud_log_store_index_test.go
- alicloud/import_alicloud_nat_gateway_test.go
- alicloud/resource_alicloud_log_machine_group_test.go
- alicloud/resource_alicloud_log_store_index_test.go
- alicloud/resource_alicloud_log_store_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudNat -timeout=600m
--- PASS: TestAccAlicloudNatGateway_importSpec (21.88s)
=== RUN   TestAccAlicloudNatGateway_basic
--- PASS: TestAccAlicloudNatGateway_basic (22.23s)
=== RUN   TestAccAlicloudNatGateway_specification
--- PASS: TestAccAlicloudNatGateway_specification (27.02s)
PASS
ok  	github.com/alibaba/terraform-provider/alicloud	71.172s
```
>  Improve Nat gateway resource test case

- CHANGELOG.md
- alicloud/import_alicloud_log_machine_group_test.go
- alicloud/import_alicloud_log_store_index_test.go
- alicloud/import_alicloud_nat_gateway_test.go
- alicloud/import_alicloud_ots_table_test.go
- alicloud/resource_alicloud_log_machine_group_test.go
- alicloud/resource_alicloud_log_store_index_test.go
- alicloud/resource_alicloud_log_store_test.go
- alicloud/resource_alicloud_ots_table_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudOts -timeout=600m
=== RUN   TestAccAlicloudOtsTable_Basic
--- PASS: TestAccAlicloudOtsTable_Basic (2.77s)
PASS
ok  	github.com/alibaba/terraform-provider/alicloud	2.822s
```
>  Improve ots table resource test case

- CHANGELOG.md
- alicloud/data_source_alicloud_dns_domains_test.go
- alicloud/data_source_alicloud_dns_groups_test.go
- alicloud/errors.go
- alicloud/import_alicloud_log_machine_group_test.go
- alicloud/import_alicloud_log_store_index_test.go
- alicloud/import_alicloud_nat_gateway_test.go
- alicloud/import_alicloud_ots_table_test.go
- alicloud/import_alicloud_vroute_entry_test.go
- alicloud/resource_alicloud_dns_record_test.go
- alicloud/resource_alicloud_dns_test.go
- alicloud/resource_alicloud_log_machine_group_test.go
- alicloud/resource_alicloud_log_store_index_test.go
- alicloud/resource_alicloud_log_store_test.go
- alicloud/resource_alicloud_oss_bucket_object_test.go
- alicloud/resource_alicloud_oss_bucket_test.go
- alicloud/resource_alicloud_ots_table_test.go
- alicloud/resource_alicloud_router_interface_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRout -timeout=600m
--- PASS: TestAccAlicloudRouteEntry_importBasic (108.82s)
--- PASS: TestAccAlicloudRouterInterface_basic (15.82s)
--- PASS: TestAccAlicloudRouteEntry_Basic (120.02s)
--- PASS: TestAccAlicloudRouteEntry_RouteInterface (33.43s)
PASS
ok  	github.com/alibaba/terraform-provider/alicloud	278.147s
```
> Improve route and router interface resource test case

- CHANGELOG.md
- alicloud/data_source_alicloud_dns_domains_test.go
- alicloud/data_source_alicloud_dns_groups_test.go
- alicloud/errors.go
- alicloud/import_alicloud_cms_alarm_test.go
- alicloud/import_alicloud_log_machine_group_test.go
- alicloud/import_alicloud_log_store_index_test.go
- alicloud/import_alicloud_nat_gateway_test.go
- alicloud/import_alicloud_ots_table_test.go
- alicloud/import_alicloud_vroute_entry_test.go
- alicloud/resource_alicloud_cms_alarm.go
- alicloud/resource_alicloud_cms_alarm_test.go
- alicloud/resource_alicloud_dns_record_test.go
- alicloud/resource_alicloud_dns_test.go
- alicloud/resource_alicloud_log_machine_group_test.go
- alicloud/resource_alicloud_log_store_index_test.go
- alicloud/resource_alicloud_log_store_test.go
- alicloud/resource_alicloud_oss_bucket_object_test.go
- alicloud/resource_alicloud_oss_bucket_test.go
- alicloud/resource_alicloud_ots_table_test.go
- alicloud/resource_alicloud_router_interface_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCms -timeout=600m
=== RUN   TestAccAlicloudCmsAlarm_import
--- PASS: TestAccAlicloudCmsAlarm_import (3.35s)
=== RUN   TestAccAlicloudCmsAlarm_basic
--- PASS: TestAccAlicloudCmsAlarm_basic (2.86s)
=== RUN   TestAccAlicloudCmsAlarm_update
--- PASS: TestAccAlicloudCmsAlarm_update (5.09s)
=== RUN   TestAccAlicloudCmsAlarm_disable
--- PASS: TestAccAlicloudCmsAlarm_disable (3.02s)
PASS
ok  	github.com/alibaba/terraform-provider/alicloud	14.368s
```
> Improve cloud monitor resource test case

- .travis.yml
- CHANGELOG.md
> Update Go version to 1.10.1 to match new sdk

- CHANGELOG.md
- alicloud/config.go
- alicloud/diff_suppress_funcs.go
- alicloud/extension_slb.go
- alicloud/resource_alicloud_slb_listener.go
- alicloud/service_alicloud_common.go
- alicloud/service_alicloud_slb.go
The result of running test cases:
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlb -timeout=240m
=== RUN   TestAccAlicloudSlbAttachment_import
--- PASS: TestAccAlicloudSlbAttachment_import (169.03s)
--- PASS: TestAccAlicloudSlbListener_importHttp (15.25s)
--- PASS: TestAccAlicloudSlbListener_importTcp (29.35s)
--- PASS: TestAccAlicloudSlbListener_importUdp (15.63s)
=== RUN   TestAccAlicloudSlbRule_import
--- PASS: TestAccAlicloudSlbRule_import (147.74s)
=== RUN   TestAccAlicloudSlbServerGroup_import
--- PASS: TestAccAlicloudSlbServerGroup_import (159.84s)
=== RUN   TestAccAlicloudSlb_importBandwidth
--- PASS: …
```
> Fix creating slb listener in international region failed error

- CHANGELOG.md
- alicloud/common.go
- alicloud/config.go
- alicloud/data_source_alicloud_vpcs.go
- alicloud/data_source_alicloud_vpcs_test.go
- alicloud/diff_suppress_funcs.go
- alicloud/extension_slb.go
- alicloud/extension_vpc.go
- alicloud/import_alicloud_router_interface_connection_test.go
- alicloud/import_alicloud_router_interface_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_fc_function.go
- alicloud/resource_alicloud_fc_function_test.go
- alicloud/resource_alicloud_fc_trigger.go
- alicloud/resource_alicloud_fc_trigger_test.go
- alicloud/resource_alicloud_router_interface.go
- alicloud/resource_alicloud_router_interface_connection.go
- alicloud/resource_alicloud_router_interface_connection_test.go
- alicloud/resource_alicloud_router_interface_test.go
- alicloud/resource_alicloud_slb_listener.go
- alicloud/service_alicloud_common.go
- alicloud/service_alicloud_slb.go
- alicloud/service_alicloud_vpc.go
- website/alicloud.erb
- website/docs/r/fc_function.html.markdown
- website/docs/r/fc_service.html.markdown
- website/docs/r/fc_trigger.html.markdown
- website/docs/r/router_interface.html.markdown
- website/docs/r/router_interface_connection.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudFCTrigger -timeout=240m
=== RUN   TestAccAlicloudFCTrigger_log
--- PASS: TestAccAlicloudFCTrigger_log (21.24s)
PASS
ok  	github.com/alibaba/terraform-provider/alicloud	21.294s
```
> Fix resource alicloud_fc_trigger "source_arn" inputting empty error

- CHANGELOG.md
- alicloud/resource_alicloud_slb_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlb_spec -timeout=240m
=== RUN   TestAccAlicloudSlb_spec
--- PASS: TestAccAlicloudSlb_spec (33.80s)
PASS
ok  	github.com/alibaba/terraform-provider/alicloud	33.861s
```
> Improve SLB instance test case

- CHANGELOG.md
- alicloud/errors.go
- alicloud/resource_alicloud_router_interface.go
- alicloud/resource_alicloud_router_interface_connection.go
- alicloud/resource_alicloud_router_interface_connection_test.go
- alicloud/resource_alicloud_slb_test.go
The runing test case result as follows:
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRouterInterfaceConnection_basic -timeout=240m
--- PASS: TestAccAlicloudRouterInterfaceConnection_basic (116.52s)
PASS
ok  	github.com/alibaba/terraform-provider/alicloud	116.581s
```
> Fix router interface connection error and deleting error

- alicloud/errors.go
- alicloud/provider.go
- alicloud/resource_alicloud_vpn_gateway.go
- alicloud/resource_alicloud_vpn_gateway_test.go
- alicloud/service_alicloud_vpn_gateway.go
- alicloud/validators.go
- website/alicloud.erb
- website/docs/r/vpn_gateway.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudVpnGateway -timeout=300m
=== RUN TestAccAlicloudVpnGateway_basic
--- PASS: TestAccAlicloudVpnGateway_basic (248.66s)
=== RUN TestAccAlicloudVpnGateway_update
--- PASS: TestAccAlicloudVpnGateway_update (230.99s)
PASS
ok github.com/terraform-providers/terraform-provider-alicloud/alicloud	479.708s
> Add AliCloud VPN gateway resource

- alicloud/provider.go
- alicloud/resource_alicloud_vpn_customer_gateway.go
- alicloud/resource_alicloud_vpn_customer_gateway_test.go
- alicloud/service_alicloud_vpn_gateway.go
- website/alicloud.erb
- website/docs/r/vpn_customer_gateway.html.markdown
- website/docs/r/vpn_gateway.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudVpnCus -timeout=300m
=== RUN   TestAccAlicloudVpnCustomerGateway_basic
--- PASS: TestAccAlicloudVpnCustomerGateway_basic (7.26s)
=== RUN   TestAccAlicloudVpnCustomerGateway_update
--- PASS: TestAccAlicloudVpnCustomerGateway_update (8.56s)
=== RUN   TestAccAlicloudVpnCustomerGateway_updateIp
--- PASS: TestAccAlicloudVpnCustomerGateway_updateIp (13.66s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	29.527s
> Add AliCloud VPN customer gateway resource

- alicloud/extension_vpn.go
- alicloud/provider.go
- alicloud/resource_alicloud_vpn_connection.go
- alicloud/resource_alicloud_vpn_connection_test.go
- alicloud/service_alicloud_vpn_gateway.go
- website/alicloud.erb
- website/docs/r/vpn_connection.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudVpnConnection  -timeout=300m
=== RUN   TestAccAlicloudVpnConnection_basic
--- PASS: TestAccAlicloudVpnConnection_basic (244.75s)
=== RUN   TestAccAlicloudVpnConnection_update
--- PASS: TestAccAlicloudVpnConnection_update (263.31s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	508.125s
> Add AliCloud VPN connection resource

- CHANGELOG.md
- alicloud/resource_alicloud_ess_scalingconfiguration.go
- alicloud/resource_alicloud_ess_scalingconfiguration_test.go
$ TF_ACC=true go test -v -run TestAccAlicloudEssScalingConfiguration_basic
--- PASS: TestAccAlicloudEssScalingConfiguration_basic (67.21s)
PASS
ok  	github.com/alibaba/terraform-provider/alicloud	67.251s
> Base64 encode ESS scaling config user_data

- CHANGELOG.md
- alicloud/data_source_alicloud_account.go
- alicloud/data_source_alicloud_account_test.go
- alicloud/data_source_alicloud_dns_domains_test.go
- alicloud/data_source_alicloud_dns_records_test.go
- alicloud/import_alicloud_dns_record_test.go
- alicloud/import_alicloud_dns_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_dns_record_test.go
- alicloud/resource_alicloud_dns_test.go
- website/alicloud.erb
- website/docs/d/account.html.markdown
Test Results
```
/usr/local/go/bin/go tool test2json -t /private/var/folders/v1/jvjz3zmn64q0j34yc9m9n4w00000gn/T/___non_verbose_tests -test.v -test.run ^TestAccAlicloudAccountDataSource_basic$ #gosetup
=== RUN   TestAccAlicloudAccountDataSource_basic
--- PASS: TestAccAlicloudAccountDataSource_basic (14.74s)
PASS
```
> Create a new data source alicloud_account

- CHANGELOG.md
- alicloud/data_source_alicloud_account.go
- alicloud/data_source_alicloud_account_test.go
- alicloud/data_source_alicloud_dns_domains_test.go
- alicloud/data_source_alicloud_dns_records_test.go
- alicloud/data_source_alicloud_slbs.go
- alicloud/data_source_alicloud_slbs_test.go
- alicloud/import_alicloud_dns_record_test.go
- alicloud/import_alicloud_dns_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_dns_record_test.go
- alicloud/resource_alicloud_dns_test.go
- alicloud/resource_alicloud_fc_trigger_test.go
- website/alicloud.erb
- website/docs/d/account.html.markdown
- website/docs/d/slbs.html.markdown
Test results
```
/usr/local/go/bin/go tool test2json -t /private/var/folders/v1/jvjz3zmn64q0j34yc9m9n4w00000gn/T/___non_verbose_tests -test.v -test.run ^TestAccAlicloudSlbsDataSource #gosetup
=== RUN   TestAccAlicloudSlbsDataSource_basic
--- PASS: TestAccAlicloudSlbsDataSource_basic (59.40s)
=== RUN   TestAccAlicloudSlbsDataSource_filterByIds
--- PASS: TestAccAlicloudSlbsDataSource_filterByIds (53.51s)
=== RUN   TestAccAlicloudSlbsDataSource_filterByAllFields
--- PASS: TestAccAlicloudSlbsDataSource_filterByAllFields (51.80s)
PASS
```
>  Add new datasource alicloud_slbs

- CHANGELOG.md
- alicloud/data_source_alicloud_account.go
- alicloud/data_source_alicloud_account_test.go
- alicloud/data_source_alicloud_dns_domains_test.go
- alicloud/data_source_alicloud_dns_records_test.go
- alicloud/data_source_alicloud_slb_attachments.go
- alicloud/data_source_alicloud_slb_attachments_test.go
- alicloud/data_source_alicloud_slb_listeners.go
- alicloud/data_source_alicloud_slb_listeners_test.go
- alicloud/data_source_alicloud_slbs.go
- alicloud/data_source_alicloud_slbs_test.go
- alicloud/import_alicloud_dns_record_test.go
- alicloud/import_alicloud_dns_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_dns_record_test.go
- alicloud/resource_alicloud_dns_test.go
- alicloud/resource_alicloud_fc_trigger_test.go
- website/alicloud.erb
- website/docs/d/account.html.markdown
- website/docs/d/slb_attachments.html.markdown
- website/docs/d/slb_listeners.html.markdown
- website/docs/d/slbs.html.markdown
Test results
```
/usr/local/go/bin/go tool test2json -t /private/var/folders/v1/jvjz3zmn64q0j34yc9m9n4w00000gn/T/___non_verbose_tests -test.v -test.run ^TestAccAlicloudSlbListenersDataSource #gosetup
--- PASS: TestAccAlicloudSlbListenersDataSource_http (75.11s)
=== RUN   TestAccAlicloudSlbListenersDataSource_tcp
--- PASS: TestAccAlicloudSlbListenersDataSource_tcp (68.66s)
=== RUN   TestAccAlicloudSlbListenersDataSource_udp
--- PASS: TestAccAlicloudSlbListenersDataSource_udp (68.00s)
PASS
```
>  Add a new datasource slb_listeners

- CHANGELOG.md
- alicloud/data_source_alicloud_account.go
- alicloud/data_source_alicloud_account_test.go
- alicloud/data_source_alicloud_dns_domains_test.go
- alicloud/data_source_alicloud_dns_records_test.go
- alicloud/data_source_alicloud_slb_attachments.go
- alicloud/data_source_alicloud_slb_attachments_test.go
- alicloud/data_source_alicloud_slbs.go
- alicloud/data_source_alicloud_slbs_test.go
- alicloud/import_alicloud_dns_record_test.go
- alicloud/import_alicloud_dns_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_dns_record_test.go
- alicloud/resource_alicloud_dns_test.go
- alicloud/resource_alicloud_fc_trigger_test.go
- website/alicloud.erb
- website/docs/d/account.html.markdown
- website/docs/d/slb_attachments.html.markdown
- website/docs/d/slbs.html.markdown
Test results
```
/usr/local/go/bin/go tool test2json -t /private/var/folders/v1/jvjz3zmn64q0j34yc9m9n4w00000gn/T/___non_verbose_tests -test.v -test.run ^TestAccAlicloudSlbAttachmentsDataSource #gosetup
=== RUN   TestAccAlicloudSlbAttachmentsDataSource_basic
2018/09/05 18:40:53 [ERROR] DescribeTags for image got error: &alicloud.ProviderError{errorCode:"Instance.Notfound", message:"Describe image tag by id ubuntu_16_0402_64_20G_alibase_20180409.vhd got an error."}
2018/09/05 18:43:11 [ERROR] DescribeTags for image got error: …
```
>  Add a new datasource slb_attachments

- CHANGELOG.md
- alicloud/data_source_alicloud_disks.go
- alicloud/data_source_alicloud_disks_test.go
- alicloud/data_source_alicloud_fc_services.go
- alicloud/data_source_alicloud_fc_services_test.go
- alicloud/data_source_alicloud_oss_buckets.go
- alicloud/data_source_alicloud_oss_buckets_test.go
- alicloud/provider.go
- examples/kubernetes/main.tf
- examples/kubernetes/outputs.tf
- examples/kubernetes/variables.tf
- website/alicloud.erb
- website/docs/d/disks.html.markdown
- website/docs/d/fc_services.html.markdown
- website/docs/d/oss_buckets.html.markdown
Create the data source alicloud_fc_services.
Test results:
```
/usr/local/go/bin/go test -c -i -v -sweep=eu-central-1 -o /private/var/folders/v1/jvjz3zmn64q0j34yc9m9n4w00000gn/T/___Test_in_Frankfurt__non_verbose_ github.com/alibaba/terraform-provider/alicloud #gosetup
/usr/local/go/bin/go tool test2json -t /private/var/folders/v1/jvjz3zmn64q0j34yc9m9n4w00000gn/T/___Test_in_Frankfurt__non_verbose_ -test.v -test.run ^TestAccAlicloudFcServicesDataSource_basic$ #gosetup
=== RUN   TestAccAlicloudFcServicesDataSource_basic
--- PASS: TestAccAlicloudFcServicesDataSource_basic (97.77s)
PASS
```
> Add a new datasource fc_services

- CHANGELOG.md
- alicloud/data_source_alicloud_disks.go
- alicloud/data_source_alicloud_disks_test.go
- alicloud/data_source_alicloud_fc_functions.go
- alicloud/data_source_alicloud_fc_functions_test.go
- alicloud/data_source_alicloud_fc_services.go
- alicloud/data_source_alicloud_fc_services_test.go
- alicloud/data_source_alicloud_oss_buckets.go
- alicloud/data_source_alicloud_oss_buckets_test.go
- alicloud/provider.go
- examples/kubernetes/main.tf
- examples/kubernetes/outputs.tf
- examples/kubernetes/variables.tf
- website/alicloud.erb
- website/docs/d/disks.html.markdown
- website/docs/d/fc_functions.html.markdown
- website/docs/d/fc_services.html.markdown
- website/docs/d/oss_buckets.html.markdown
Create the datasource alicloud_fc_functions.
Test results:
```
/usr/local/go/bin/go test -c -i -v -sweep=eu-central-1 -o /private/var/folders/v1/jvjz3zmn64q0j34yc9m9n4w00000gn/T/___Test_in_Frankfurt__non_verbose_ github.com/alibaba/terraform-provider/alicloud #gosetup
/usr/local/go/bin/go tool test2json -t /private/var/folders/v1/jvjz3zmn64q0j34yc9m9n4w00000gn/T/___Test_in_Frankfurt__non_verbose_ -test.v -test.run ^TestAccAlicloudFcFunctionsDataSource_basic$ #gosetup
=== RUN   TestAccAlicloudFcFunctionsDataSource_basic
--- PASS: TestAccAlicloudFcFunctionsDataSource_basic (34.68s)
PASS
```
>  Add a new datasource fc_functions

- CHANGELOG.md
- alicloud/data_source_alicloud_disks.go
- alicloud/data_source_alicloud_disks_test.go
- alicloud/data_source_alicloud_fc_functions.go
- alicloud/data_source_alicloud_fc_functions_test.go
- alicloud/data_source_alicloud_fc_services.go
- alicloud/data_source_alicloud_fc_services_test.go
- alicloud/data_source_alicloud_fc_triggers.go
- alicloud/data_source_alicloud_fc_triggers_test.go
- alicloud/data_source_alicloud_oss_bucket_objects.go
- alicloud/data_source_alicloud_oss_bucket_objects_test.go
- alicloud/data_source_alicloud_oss_buckets.go
- alicloud/data_source_alicloud_oss_buckets_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_oss_bucket_object.go
- examples/kubernetes/main.tf
- examples/kubernetes/outputs.tf
- examples/kubernetes/variables.tf
- website/alicloud.erb
- website/docs/d/disks.html.markdown
- website/docs/d/fc_functions.html.markdown
- website/docs/d/fc_services.html.markdown
- website/docs/d/fc_triggers.html.markdown
- website/docs/d/oss_bucket_objects.html.markdown
- website/docs/d/oss_buckets.html.markdown
- website/docs/r/oss_bucket.html.markdown
- website/docs/r/oss_bucket_object.html.markdown
Create the datasource alicloud_fc_triggers.
Test results:
```
/usr/local/go/bin/go test -c -i -v -sweep=eu-central-1 -o /private/var/folders/v1/jvjz3zmn64q0j34yc9m9n4w00000gn/T/___Test_in_Frankfurt__non_verbose_ github.com/alibaba/terraform-provider/alicloud #gosetup
/usr/local/go/bin/go tool test2json -t /private/var/folders/v1/jvjz3zmn64q0j34yc9m9n4w00000gn/T/___Test_in_Frankfurt__non_verbose_ -test.v -test.run ^TestAccAlicloudFcTriggersDataSource_basic$ #gosetup
=== RUN   TestAccAlicloudFcTriggersDataSource_basic
--- PASS: TestAccAlicloudFcTriggersDataSource_basic (92.30s)
PASS
```
> Add a new datasource fc_triggers

- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_kubernetes_test.go
- vendor/github.com/denverdino/aliyungo/cs/clusters.go
- vendor/vendor.json
- website/docs/r/cs_kubernetes.html.markdown
I added `worker_data_disk_category` and `worker_data_disk_size`.
> add worker_data_disk_category and worker_data_disk_size to kubernetes creation

- alicloud/provider.go
- alicloud/resource_alicloud_vroute_table.go
- alicloud/resource_alicloud_vroute_table_test.go
- alicloud/service_alicloud_route_table.go
- website/alicloud.erb
- website/docs/r/route_table.html.markdown
MacBook-Pro-2:terraform-provider-alicloud$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRouteTable -timeout=60m
=== RUN   TestAccAlicloudRouteTable_basic
--- PASS: TestAccAlicloudRouteTable_basic (20.56s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	20.614s
> Add AliCloud Route Table resource

- alicloud/resource_alicloud_vroute_table.go
- alicloud/resource_alicloud_vroute_table_test.go
- website/alicloud.erb
- website/docs/r/route_table.html.markdown
MacBook-Pro-2:terraform-provider-alicloud$ TF_ACC=1 go test ./alicloud -v  -sweep=cn-shanghai -sweep-run=alicloud_route_table
2018/09/27 15:52:38 [DEBUG] Running Sweepers for region (cn-shanghai):
2018/09/27 15:52:38 [DEBUG] Instantiate OSS client using endpoint: "http://oss-cn-shanghai.aliyuncs.com"
2018/09/27 15:52:38 [INFO] Skipping Route Table:  (vtb-uf6au6p3zojrqxcdknoip)
2018/09/27 15:52:38 [INFO] Skipping Route Table: test_route_table (vtb-uf6497zbabsljg8bnq38h)
2018/09/27 15:52:38 [INFO] Skipping Route Table:  (vtb-uf63dylm2mkpj5ojnn7x1)
2018/09/27 15:52:38 [INFO] Skipping Route Table:  (vtb-uf66gujs6rmz2fe6k13rq)
2018/09/27 15:52:38 [INFO] Skipping Route Table: test_route_table (vtb-uf65idn5hlj5ym8swkkq1)
2018/09/27 15:52:38 [INFO] Skipping Route Table: …
> Update AliCloud Route Table resource

- alicloud/common.go
- alicloud/data_source_alicloud_vpn_gateways.go
- alicloud/data_source_alicloud_vpn_gateways_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/vpn_gateways.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudVpnsDataSource_b  1 Support AliCloud datasource vpn_gateways
asic  -timeout=300m
=== RUN   TestAccAlicloudVpnsDataSource_basic
--- PASS: TestAccAlicloudVpnsDataSource_basic (235.47s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	235.522s
> Support AliCloud datasource vpn_gateways

- alicloud/data_source_alicloud_mns_queue.go
- alicloud/data_source_alicloud_mns_queue_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/mns_queues.html.markdown
=== RUN   TestAccAlicloudMNSQueueDataSource
queues: [map[name:tf-testAccMNSQueueConfig1 delay_seconds:60478 maximum_message_size:12357 message_retention_period:256000 visibility_timeouts:30 polling_wait_seconds:3 id:tf-testAccMNSQueueConfig1]]
queues: [map[visibility_timeouts:30 polling_wait_seconds:3 id:tf-testAccMNSQueueConfig1 name:tf-testAccMNSQueueConfig1 delay_seconds:60478 maximum_message_size:12357 message_retention_period:256000]]
queues: [map[message_retention_period:256000 visibility_timeouts:30 polling_wait_seconds:3 id:tf-testAccMNSQueueConfig1 name:tf-testAccMNSQueueConfig1 delay_seconds:60478 maximum_message_size:12357]]
--- PASS: TestAccAlicloudMNSQueueDataSource (3.27s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	3.314s
> add datasources mns queues

- alicloud/data_source_alicloud_mns_topic.go
- alicloud/data_source_alicloud_mns_topic_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/mns_queues.html.markdown
- website/docs/d/mns_topics.html.markdown
=== RUN   TestAccAlicloudMNSTopicDataSource
--- PASS: TestAccAlicloudMNSTopicDataSource (3.45s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	(cached)
> add topic datasource

- alicloud/resource_alicloud_mns_queue_test.go
- alicloud/resource_alicloud_mns_topic_test.go
2018/10/10 19:26:45 Sweeper Tests ran:
- alicloud_mns_topic
- alicloud_mns_queue
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	1.380s
> modify the sweeptest nameprefix

- alicloud/resource_alicloud_mns_queue_test.go
- alicloud/resource_alicloud_mns_topic_test.go
2018/10/10 20:19:24 Sweeper Tests ran:
- alicloud_mns_topic
- alicloud_mns_queue
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	2.574s
> modify the mns err info

- vendor/github.com/denverdino/aliyungo/cs/clusters.go
- vendor/vendor.json
`new_nat_gateway` was ignored when disable `new_nat_gateway`, fixed this in aliyungo.
See pr at https://github.com/denverdino/aliyungo/pull/313
This fixes https://github.com/alibaba/terraform-provider/issues/723 and https://github.com/alibaba/terraform-provider/issues/707.
> fix kubernetes's new_nat_gateway issue

- alicloud/resource_alicloud_cen_instance.go
- alicloud/resource_alicloud_cen_instance_attachment.go
- alicloud/service_alicloud_cen.go
change child instance type Vbr to VBR and replace some const variables
> change child instance type Vbr to VBR and replace some const variables

- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_slb_listener.go
- alicloud/resource_alicloud_slb_listener_test.go
- examples/slb/README.md
- examples/slb/main.tf
- examples/slb/outputs.tf
- website/docs/r/slb_listener.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlbListener -timeout=300m
--- PASS: TestAccAlicloudSlbListenersDataSource_http (37.85s)
=== RUN   TestAccAlicloudSlbListenersDataSource_tcp
--- PASS: TestAccAlicloudSlbListenersDataSource_tcp (32.91s)
=== RUN   TestAccAlicloudSlbListenersDataSource_udp
--- PASS: TestAccAlicloudSlbListenersDataSource_udp (36.42s)
--- PASS: TestAccAlicloudSlbListener_importHttp (14.38s)
--- PASS: TestAccAlicloudSlbListener_importTcp (13.94s)
--- PASS: TestAccAlicloudSlbListener_importUdp (14.85s)
--- PASS: …
> resource alicloud_slb_listener support acl.

- alicloud/import_alicloud_router_interface_test.go
- alicloud/resource_alicloud_router_interface.go
- alicloud/resource_alicloud_router_interface_connection_test.go
- alicloud/resource_alicloud_router_interface_test.go
- alicloud/service_alicloud_vpc.go
- alicloud/validators.go
- website/docs/r/router_interface.html.markdown
MacBook-Pro-2:terraform-provider-alicloud$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRouterInterface -timeout=300m
=== RUN   TestAccAlicloudRouterInterfacesDataSource_oneRouter
--- PASS: TestAccAlicloudRouterInterfacesDataSource_oneRouter (19.43s)
=== RUN   TestAccAlicloudRouterInterfacesDataSource_twoRouters
--- PASS: TestAccAlicloudRouterInterfacesDataSource_twoRouters (94.13s)
=== RUN   TestAccAlicloudRouterInterface_import
--- PASS: TestAccAlicloudRouterInterface_import (19.30s)
--- PASS: TestAccAlicloudRouterInterfaceConnection_basic (92.69s)
--- PASS: TestAccAlicloudRouterInterface_basic (18.40s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud …
> Update AliCloud Router Interface resource

- alicloud/common.go
- alicloud/import_alicloud_common_bandwidth_package_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_common_bandwidth_package.go
- alicloud/resource_alicloud_common_bandwidth_package_test.go
- alicloud/service_alicloud_common_bandwidth_package.go
- alicloud/validators.go
- website/alicloud.erb
- website/docs/r/common_bandwidth_package.html.markdown
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCommonBandwidthPackage -timeout=60m
=== RUN   TestAccAlicloudCommonBandwidthPackage_importBasic
--- PASS: TestAccAlicloudCommonBandwidthPackage_importBasic (9.71s)
=== RUN   TestAccAlicloudCommonBandwidthPackage_basic
--- PASS: TestAccAlicloudCommonBandwidthPackage_basic (9.31s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	19.066s
> Add AliCloud Common Bandwidth Package resource

- alicloud/resource_alicloud_security_group.go
- alicloud/resource_alicloud_security_group_test.go
TF_DEBUG=debug TF_ACC=1 go  test -v -run=TestAccAlicloudSecurityGroup_
=== RUN   TestAccAlicloudSecurityGroup_importBasic
--- PASS: TestAccAlicloudSecurityGroup_importBasic (3.00s)
=== RUN   TestAccAlicloudSecurityGroup_importWithVpc
--- PASS: TestAccAlicloudSecurityGroup_importWithVpc (10.73s)
=== RUN   TestAccAlicloudSecurityGroup_basic
--- PASS: TestAccAlicloudSecurityGroup_basic (2.70s)
=== RUN   TestAccAlicloudSecurityGroup_withVpc
--- PASS: TestAccAlicloudSecurityGroup_withVpc (10.42s)
=== RUN   TestAccAlicloudSecurityGroup_tags
--- PASS: TestAccAlicloudSecurityGroup_tags (16.06s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	43.004s
> fix the bug of sg inner_access, #766

- alicloud/service_alicloud_ecs.go
> remove unreachable line

- alicloud/errors.go
- alicloud/resource_alicloud_instance.go
- alicloud/resource_alicloud_instance_test.go
- examples/ecs/main.tf
- website/docs/r/instance.html.markdown
TF_DEBUG=debug TF_ACC=1 go  test -v -run=TestAccAlicloudInstanceSecurityEnhancementStrategy_update
=== RUN   TestAccAlicloudInstanceSecurityEnhancementStrategy_update
--- PASS: TestAccAlicloudInstanceSecurityEnhancementStrategy_update (272.63s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     272.678s
TF_DEBUG=debug TF_ACC=1 go  test -v -run=TestAccAlicloudInstance_dataDisk
=== RUN   TestAccAlicloudInstance_dataDisk
--- PASS: TestAccAlicloudInstance_dataDisk (107.06s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     107.117s
> Support creating data disk with instance

- alicloud/resource_alicloud_instance.go
Cancel the limit of the system disk size.
> cancel the limit of system disk size

- website/docs/d/network_interfaces.html.markdown
- website/docs/r/network_interface.html.markdown
- website/docs/r/network_interface_attachment.html.markdown
> fix error about the docs format

- alicloud/resource_alicloud_disk.go
- alicloud/resource_alicloud_disk_test.go
- website/docs/r/disk.html.markdown
- website/docs/r/instance.html.markdown
TF_DEBUG=debug TF_ACC=1 go  test -v -run=TestAccAlicloudDisk_basic
=== RUN   TestAccAlicloudDisk_basic
--- PASS: TestAccAlicloudDisk_basic (67.74s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	67.795s
> support disk resize

- alicloud/errors.go
- alicloud/extension_api_gateway.go
- alicloud/resource_alicloud_api_gateway_api.go
- alicloud/resource_alicloud_api_gateway_app_attachment.go
- alicloud/service_alicloud_api_gateway.go
- examples/api-gateway-api/main.tf
- website/docs/r/api_gateway_api.html.markdown
ali-1c36bbec7887:terraform-provider-alicloud lenny$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudApigatewayApi_basic -timeout=300m=== RUN TestAccAlicloudApigatewayApi_basic947d99eea60e49fca192a1d4417baade:b4526c88251245e9bb1e32b5eb29f8b6--- PASS: TestAccAlicloudApigatewayApi_basic (2.82s)PASSok github.com/terraform-providers/terraform-provider-alicloud/alicloud	2.877s
> update api resource that support to deploy api

- alicloud/connectivity/client.go
Change-Id: I21652a5677568da82b5dee2309629b0afa237094
> fix datahub bug when visit region of ap-southeast-1

- website/docs/r/network_interface_attachment.html.markdown
> fix an docs error.

- alicloud/resource_alicloud_cen_bandwidth_package_test.go
- alicloud/resource_alicloud_cen_instance_test.go
Fix the sweeper test for CEN and CEN bandwidth package
> Fix the sweeper test for CEN and CEN bandwidth package

- alicloud/resource_alicloud_instance_test.go
TF_DEBUG=debug TF_ACC=1 go test  -v -run=TestAccAlicloudInstance_dataDisk
=== RUN   TestAccAlicloudInstance_dataDisk
--- PASS: TestAccAlicloudInstance_dataDisk (180.56s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     180.623s
> fix a bug of instance testcase

- alicloud/data_source_alicloud_instance_types.go
- alicloud/resource_alicloud_network_interface_attachment_test.go
- website/docs/d/instance_types.html.markdown
TF_DEBUG=debug TF_ACC=1 go test  -v -run=TestAccAlicloudNetworkInterfaceAttachmentWithMultiEni
=== RUN   TestAccAlicloudNetworkInterfaceAttachmentWithMultiEni
--- PASS: TestAccAlicloudNetworkInterfaceAttachmentWithMultiEni (205.91s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     205.962s
> support eni amount in data source instance types

- alicloud/resource_alicloud_slb.go
- alicloud/resource_alicloud_slb_test.go
- alicloud/service_alicloud_slb.go
- alicloud/validators.go
- examples/slb/main.tf
- examples/slb/outputs.tf
- website/docs/r/slb.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlb_ -timeout=300m count=1
=== RUN   TestAccAlicloudSlb_import
--- PASS: TestAccAlicloudSlb_import (31.26s)
=== RUN   TestAccAlicloudSlb_paybybandwidth
--- PASS: TestAccAlicloudSlb_paybybandwidth (6.36s)
=== RUN   TestAccAlicloudSlb_vpc
--- PASS: TestAccAlicloudSlb_vpc (26.79s)
=== RUN   TestAccAlicloudSlb_spec
--- PASS: TestAccAlicloudSlb_spec (32.02s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	96.487s
> resouce alicloud_slb support tags.

- alicloud/data_source_alicloud_slbs.go
- alicloud/data_source_alicloud_slbs_test.go
- alicloud/validators.go
- examples/slb/main.tf
- website/docs/d/slbs.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlbsDataSource -timeout=300m count=1
=== RUN   TestAccAlicloudSlbsDataSource_basic
--- PASS: TestAccAlicloudSlbsDataSource_basic (62.75s)
=== RUN   TestAccAlicloudSlbsDataSource_filterByIds
--- PASS: TestAccAlicloudSlbsDataSource_filterByIds (27.86s)
=== RUN   TestAccAlicloudSlbsDataSource_filterByAllFields
--- PASS: TestAccAlicloudSlbsDataSource_filterByAllFields (30.75s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	121.425s
> datasource alicloud_slbs support tags.

- CHANGELOG.md
- alicloud/resource_alicloud_db_instance.go
- website/docs/r/db_instance.html.markdown
Fix the issue https://github.com/terraform-providers/terraform-provider-alicloud/issues/494
> Remove DB instance engine_version limitation

- alicloud/extension_slb.go
- alicloud/resource_alicloud_slb_listener.go
- alicloud/resource_alicloud_slb_listener_test.go
- website/docs/r/slb_listener.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlbListener -timeout=300m count=1
--- PASS: TestAccAlicloudSlbListenersDataSource_http (34.61s)
=== RUN   TestAccAlicloudSlbListenersDataSource_https
--- PASS: TestAccAlicloudSlbListenersDataSource_https (15.77s)
=== RUN   TestAccAlicloudSlbListenersDataSource_tcp
--- PASS: TestAccAlicloudSlbListenersDataSource_tcp (28.85s)
=== RUN   TestAccAlicloudSlbListenersDataSource_udp
--- PASS: TestAccAlicloudSlbListenersDataSource_udp (30.42s)
--- PASS: TestAccAlicloudSlbListener_importHttp (10.81s)
=== RUN   TestAccAlicloudSlbListener_importHttps
--- PASS: TestAccAlicloudSlbListener_importHttps (12.52s)
=== RUN …
> fix tls_cipher_policy update bug for resource alicloud_slb_listener.

- CHANGELOG.md
- alicloud/data_source_alicloud_disks_test.go
- alicloud/data_source_alicloud_instances_test.go
- alicloud/import_alicloud_instance_test.go
- alicloud/resource_alicloud_disk_attachment_test.go
- alicloud/resource_alicloud_instance_test.go
- alicloud/resource_alicloud_vswitch_test.go
- alicloud/service_alicloud_common_test.go
- examples/slb/main.tf
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudInstance -timeout=120m
--- PASS: TestAccAlicloudInstanceTypesDataSource_basic (2.54s)
=== RUN   TestAccAlicloudInstanceTypesDataSource_gpu
--- PASS: TestAccAlicloudInstanceTypesDataSource_gpu (1.64s)
=== RUN   TestAccAlicloudInstanceTypesDataSource_empty
--- PASS: TestAccAlicloudInstanceTypesDataSource_empty (0.96s)
=== RUN   TestAccAlicloudInstancesDataSource_basic
--- PASS: TestAccAlicloudInstancesDataSource_basic (131.81s)
=== RUN   TestAccAlicloudInstancesDataSource_tags
--- PASS: TestAccAlicloudInstancesDataSource_tags (132.49s)
=== RUN   TestAccAlicloudInstancesDataSource_empty
--- PASS: TestAccAlicloudInstancesDataSource_empty (0.76s)
=== RUN …
```
> Improve ecs instance and disk testcase with common case

- CHANGELOG.md
- alicloud/import_alicloud_datahub_project_test.go
- alicloud/import_alicloud_datahub_subscription_test.go
- alicloud/import_alicloud_datahub_topic_test.go
- alicloud/resource_alicloud_datahub_project_test.go
- alicloud/resource_alicloud_datahub_subscription_test.go
- alicloud/resource_alicloud_datahub_topic_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDatahub -timeout=120m
=== RUN   TestAccAlicloudDatahubProject_import
--- PASS: TestAccAlicloudDatahubProject_import (0.34s)
=== RUN   TestAccAlicloudDatahubSubscription_importBasic
--- PASS: TestAccAlicloudDatahubSubscription_importBasic (0.36s)
=== RUN   TestAccAlicloudDatahubTopic_importBasic
--- PASS: TestAccAlicloudDatahubTopic_importBasic (0.82s)
=== RUN   TestAccAlicloudDatahubProject_Basic
--- PASS: TestAccAlicloudDatahubProject_Basic (0.21s)
=== RUN   TestAccAlicloudDatahubProject_Update
--- PASS: TestAccAlicloudDatahubProject_Update (0.36s)
=== RUN   TestAccAlicloudDatahubSubscription_Basic
--- PASS: TestAccAlicloudDatahubSubscription_Basic (0.36s)
=== RUN   TestAccAlicloudDatahubSubscription_Update
--- PASS: …
```
> Improve datahub project testcase

- alicloud/resource_alicloud_ess_scalingconfiguration.go
- alicloud/resource_alicloud_ess_scalingconfiguration_test.go
- website/docs/r/ess_scaling_configuration.html.markdown
--- PASS: TestAccAlicloudEssScalingConfiguration_basic (73.10s)
--- PASS: TestAccAlicloudEssScalingConfiguration_multiConfig (94.43s)
=== RUN   TestAccAlicloudEssScalingConfiguration_active
--- Pass: TestAccAlicloudEssScalingConfiguration_active (75.74s)
=== RUN   TestAccAlicloudEssScalingConfiguration_disable
--- PASS: TestAccAlicloudEssScalingConfiguration_disable (63.42s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	306.754s
> fixes #549

- CHANGELOG.md
- alicloud/errors.go
- alicloud/import_alicloud_db_account_privilege_test.go
- alicloud/import_alicloud_db_account_test.go
- alicloud/import_alicloud_db_backup_policy_test.go
- alicloud/import_alicloud_db_connection_test.go
- alicloud/import_alicloud_db_database_test.go
- alicloud/import_alicloud_db_instance_test.go
- alicloud/resource_alicloud_db_account_privilege_test.go
- alicloud/resource_alicloud_db_account_test.go
- alicloud/resource_alicloud_db_backup_policy.go
- alicloud/resource_alicloud_db_backup_policy_test.go
- alicloud/resource_alicloud_db_connection_test.go
- alicloud/resource_alicloud_db_database_test.go
- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_db_instance_test.go
- alicloud/service_alicloud_common_test.go
- alicloud/service_alicloud_rds.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDB -timeout=240m
=== RUN   TestAccAlicloudDBInstancesDataSource
--- PASS: TestAccAlicloudDBInstancesDataSource (332.90s)
=== RUN   TestAccAlicloudDBInstancesDataSourceEmpty
--- PASS: TestAccAlicloudDBInstancesDataSourceEmpty (12.27s)
=== RUN   TestAccAlicloudDBAccountPrivilege_import
--- PASS: TestAccAlicloudDBAccountPrivilege_import (495.33s)
--- PASS: TestAccAlicloudDBAccount_import (509.25s)
=== RUN   TestAccAlicloudDBBackupPolicy_import
--- PASS: TestAccAlicloudDBBackupPolicy_import (514.62s)
=== RUN   TestAccAlicloudDBConnection_import
--- PASS: TestAccAlicloudDBConnection_import (558.39s)
=== RUN   TestAccAlicloudDBDatabase_import
--- PASS: TestAccAlicloudDBDatabase_import (483.03s)
=== …
```
> Fix alicloud rds related IncorrectStatus bug

- CHANGELOG.md
- alicloud/resource_alicloud_ram_role_attachment_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRamRoleAttachment_basic  -timeout=240m
=== RUN   TestAccAlicloudRamRoleAttachment_basic
--- PASS: TestAccAlicloudRamRoleAttachment_basic (351.17s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	351.231s
```
> Improve ram_role_attachment testcase

- alicloud/resource_alicloud_vpn_gateway.go
- alicloud/validators.go
- website/docs/r/vpn_gateway.html.markdown
TF_DEBUG=debug TF_ACC=1 go test -v -run=TestAccAlicloudVpnGateway_basic --timeout=600m
=== RUN   TestAccAlicloudVpnGateway_basic
--- PASS: TestAccAlicloudVpnGateway_basic (255.12s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	255.163s
> VPN gateway support 200/500/1000M bandwidth

- CHANGELOG.md
- alicloud/errors.go
- alicloud/import_alicloud_log_machine_group_test.go
- alicloud/import_alicloud_log_project_test.go
- alicloud/import_alicloud_log_store_index_test.go
- alicloud/import_alicloud_log_store_test.go
- alicloud/resource_alicloud_log_machine_group.go
- alicloud/resource_alicloud_log_machine_group_test.go
- alicloud/resource_alicloud_log_project.go
- alicloud/resource_alicloud_log_project_test.go
- alicloud/resource_alicloud_log_store.go
- alicloud/resource_alicloud_log_store_index.go
- alicloud/resource_alicloud_log_store_index_test.go
- alicloud/resource_alicloud_log_store_test.go
- alicloud/service_alicloud_log.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudLog  -timeout=240m
--- PASS: TestAccAlicloudLogMachineGroup_import (13.52s)
=== RUN   TestAccAlicloudLogProject_import
--- PASS: TestAccAlicloudLogProject_import (8.47s)
=== RUN   TestAccAlicloudLogStoreIndex_importFull
--- PASS: TestAccAlicloudLogStoreIndex_importFull (23.68s)
=== RUN   TestAccAlicloudLogStoreIndex_importField
--- PASS: TestAccAlicloudLogStoreIndex_importField (22.51s)
=== RUN   TestAccAlicloudLogStore_import
--- PASS: TestAccAlicloudLogStore_import (18.21s)
--- PASS: TestAccAlicloudLogMachineGroup_ip (19.73s)
--- PASS: TestAccAlicloudLogMachineGroup_userdefined (14.02s)
=== …
```
> Fix log service timeout error

- CHANGELOG.md
- alicloud/import_alicloud_ess_attachment_test.go
- alicloud/resource_alicloud_ess_attachment_test.go
- alicloud/resource_alicloud_ess_scalingconfiguration_test.go
- alicloud/service_alicloud_common_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEssAttachment_basic  -timeout=240m
=== RUN   TestAccAlicloudEssAttachment_basic
--- PASS: TestAccAlicloudEssAttachment_basic (186.22s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	186.275s
```
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEssScalingConfiguration -timeout=240m
--- PASS: TestAccAlicloudEssScalingConfiguration_basic (41.63s)
=== RUN   TestAccAlicloudEssScalingConfiguration_SystemDisk
--- PASS: TestAccAlicloudEssScalingConfiguration_SystemDisk (40.59s)
--- PASS: TestAccAlicloudEssScalingConfiguration_multiConfig (49.47s)
=== RUN …
```
> Improve ess configuration testcase

- CHANGELOG.md
- alicloud/import_alicloud_ess_alarm_test.go
- alicloud/import_alicloud_ess_lifecycle_hook_test.go
- alicloud/import_alicloud_ess_scalinggroup_test.go
- alicloud/import_alicloud_ess_schedule_test.go
- alicloud/resource_alicloud_ess_alarm_test.go
- alicloud/resource_alicloud_ess_lifecyclehook.go
- alicloud/resource_alicloud_ess_lifecyclehook_test.go
- alicloud/resource_alicloud_ess_scalinggroup_test.go
- alicloud/resource_alicloud_ess_scalingrule_test.go
- alicloud/resource_alicloud_ess_schedule_test.go
- alicloud/service_alicloud_ess.go
- website/docs/r/ess_scaling_lifecycle_hook.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEss -timeout=240m
=== RUN   TestAccAlicloudEssAlarm_import
--- PASS: TestAccAlicloudEssAlarm_import (47.64s)
--- PASS: TestAccAlicloudEssAttachment_import (156.02s)
=== RUN   TestAccAlicloudEssLifecycleHook_import
--- PASS: TestAccAlicloudEssLifecycleHook_import (41.96s)
--- PASS: TestAccAlicloudEssScalingGroup_importBasic (166.36s)
--- PASS: TestAccAlicloudEssSchedule_importBasic (38.70s)
--- PASS: TestAccAlicloudEssAlarm_basic (46.32s)
=== RUN   TestAccAlicloudEssAlarm_with_dimension
--- PASS: TestAccAlicloudEssAlarm_with_dimension (45.61s)
=== RUN …
```
> Support update ess lifecycle hook name and improve ess testcase by random name

- alicloud/connectivity/regions.go
- alicloud/import_alicloud_cs_kubernetes_test.go
- alicloud/import_alicloud_cs_managed_kubernetes_test.go
- alicloud/resource_alicloud_cs_application_test.go
- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_kubernetes_test.go
- alicloud/resource_alicloud_cs_managed_kubernetes.go
- alicloud/resource_alicloud_cs_managed_kubernetes_test.go
- alicloud/resource_alicloud_cs_swarm_test.go
This should fix tons of CI issues.
> add region checks to kubernetes, multiaz kubernetes, swarm clusters

- CHANGELOG.md
- alicloud/connectivity/client.go
- alicloud/data_source_alicloud_mns_queues_test.go
- alicloud/data_source_alicloud_mns_topic_subscriptions_test.go
- alicloud/data_source_alicloud_mns_topics_test.go
- alicloud/import_alicloud_mns_queue_test.go
- alicloud/import_alicloud_mns_topic_subscription_test.go
- alicloud/import_alicloud_mns_topic_test.go
- alicloud/resource_alicloud_mns_queue_test.go
- alicloud/resource_alicloud_mns_topic_subscription_test.go
- alicloud/resource_alicloud_mns_topic_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudMns  -timeout=240m
=== RUN   TestAccAlicloudMnsQueueDataSource
--- PASS: TestAccAlicloudMnsQueueDataSource (3.49s)
=== RUN   TestAccAlicloudMnsQueueDataSourceEmpty
--- PASS: TestAccAlicloudMnsQueueDataSourceEmpty (0.83s)
=== RUN   TestAccAlicloudMnsTopicSubscriptionDataSource
--- PASS: TestAccAlicloudMnsTopicSubscriptionDataSource (1.39s)
=== RUN   TestAccAlicloudMnsTopicSubscriptionDataSourceEmpty
--- PASS: TestAccAlicloudMnsTopicSubscriptionDataSourceEmpty (1.34s)
=== RUN   TestAccAlicloudMnsTopicDataSource
--- PASS: TestAccAlicloudMnsTopicDataSource (0.86s)
=== RUN   TestAccAlicloudMnsTopicDataSourceEmpty
--- PASS: TestAccAlicloudMnsTopicDataSourceEmpty (0.80s)
=== RUN   TestAccAlicloudMnsQueue_importBasic
--- PASS: …
```
>  Support mns client https

- CHANGELOG.md
- alicloud/connectivity/client.go
- alicloud/resource_alicloud_security_group_rule.go
- alicloud/service_alicloud_slb.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/config.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests/acs_request.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests/common_request.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests/roa_request.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests/rpc_request.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests/types.go
- vendor/vendor.json
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudInstance -timeout=240m
--- PASS: TestAccAlicloudInstanceTypesDataSource_basic (29.25s)
=== RUN   TestAccAlicloudInstanceTypesDataSource_gpu
--- PASS: TestAccAlicloudInstanceTypesDataSource_gpu (4.47s)
=== RUN   TestAccAlicloudInstanceTypesDataSource_empty
--- PASS: TestAccAlicloudInstanceTypesDataSource_empty (8.02s)
=== RUN   TestAccAlicloudInstancesDataSource_basic
--- PASS: TestAccAlicloudInstancesDataSource_basic (204.93s)
=== RUN   TestAccAlicloudInstancesDataSource_tags
--- PASS: TestAccAlicloudInstancesDataSource_tags (207.28s)
=== RUN   TestAccAlicloudInstancesDataSource_empty
--- PASS: TestAccAlicloudInstancesDataSource_empty (7.08s)
=== RUN …
```
> Support https for services client using official sdk

- CHANGELOG.md
- alicloud/connectivity/client.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudLog -timeout=240m
--- PASS: TestAccAlicloudLogMachineGroup_import (18.50s)
=== RUN   TestAccAlicloudLogProject_import
--- PASS: TestAccAlicloudLogProject_import (13.07s)
=== RUN   TestAccAlicloudLogStoreIndex_importFull
--- PASS: TestAccAlicloudLogStoreIndex_importFull (34.91s)
=== RUN   TestAccAlicloudLogStoreIndex_importField
--- PASS: TestAccAlicloudLogStoreIndex_importField (34.14s)
=== RUN   TestAccAlicloudLogStore_import
--- PASS: TestAccAlicloudLogStore_import (23.78s)
--- PASS: TestAccAlicloudLogMachineGroup_ip (20.70s)
--- PASS: TestAccAlicloudLogMachineGroup_userdefined (21.49s)
=== …
```
> Support https for log client

- CHANGELOG.md
- alicloud/import_alicloud_db_account_test.go
- alicloud/resource_alicloud_db_account_test.go
- website/docs/r/db_account.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDBAccount_ -timeout=300m
--- PASS: TestAccAlicloudDBAccount_import (841.96s)
=== RUN   TestAccAlicloudDBAccount_mysql
--- PASS: TestAccAlicloudDBAccount_mysql (812.61s)
PASS
ok	github.com/terraform-providers/terraform-provider-alicloud/alicloud	2323.015s
```
> Improve db_account testcase and its docs

- CHANGELOG.md
- alicloud/data_source_alicloud_pvtz_zone_records_test.go
- alicloud/data_source_alicloud_pvtz_zones_test.go
- alicloud/import_alicloud_pvtz_zone_attachment_test.go
- alicloud/import_alicloud_pvtz_zone_record_test.go
- alicloud/import_alicloud_pvtz_zone_test.go
- alicloud/resource_alicloud_pvtz_zone_attachment_test.go
- alicloud/resource_alicloud_pvtz_zone_record_test.go
- alicloud/resource_alicloud_pvtz_zone_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudPvtz -timeout=120m
--- PASS: TestAccAlicloudPvtzZoneRecordsDataSource_basic (4.45s)
--- PASS: TestAccAlicloudPvtzZoneRecordsDataSource_empty (1.93s)
=== RUN   TestAccAlicloudPvtzZonesDataSource_basic
--- PASS: TestAccAlicloudPvtzZonesDataSource_basic (3.35s)
=== RUN   TestAccAlicloudPvtzZonesDataSource_empty
--- PASS: TestAccAlicloudPvtzZonesDataSource_empty (0.77s)
--- PASS: TestAccAlicloudPvtzZoneAttachment_importBasic (29.00s)
--- PASS: TestAccAlicloudPvtzZoneRecord_importBasic (2.96s)
=== RUN …
```
> Improve pvtz_zone testcase by using rand

- alicloud/resource_alicloud_cs_swarm.go
- alicloud/resource_alicloud_cs_swarm_test.go
See https://partners-intl.aliyun.com/help/doc-detail/25995.htm for details on zero-node cluster.
Unit-Test Output:
--- PASS: TestAccAlicloudCSSwarm_vpc (575.64s)
=== RUN   TestAccAlicloudCSSwarm_vpc_zero_node
--- PASS: TestAccAlicloudCSSwarm_vpc_zero_node (326.74s)
=== RUN   TestAccAlicloudCSSwarm_vpc_noslb
--- PASS: TestAccAlicloudCSSwarm_vpc_noslb (571.62s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	1474.059s
> support for zero node clusters in swarm container service

- CHANGELOG.md
- alicloud/import_alicloud_cs_application_test.go
- alicloud/import_alicloud_cs_swarm_test.go
- alicloud/resource_alicloud_cs_application.go
- alicloud/resource_alicloud_cs_kubernetes_test.go
- alicloud/resource_alicloud_cs_managed_kubernetes.go
- alicloud/resource_alicloud_cs_swarm.go
- alicloud/resource_alicloud_cs_swarm_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCSApplication_import -timeout=300m
=== RUN   TestAccAlicloudCSApplication_import
--- PASS: TestAccAlicloudCSApplication_import (460.28s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	460.339s
```
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCSSwarm_update -timeout=300m
--- PASS: TestAccAlicloudCSSwarm_update (737.03s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	737.087s
```
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCSManagedKubernetes_import -timeout=300m
=== RUN   TestAccAlicloudCSManagedKubernetes_import
--- PASS: TestAccAlicloudCSManagedKubernetes_import (814.17s)
PASS
ok …
```
> Fix cs cluster not found error and improve its testcase

- CHANGELOG.md
- alicloud/tags.go
- website/docs/r/ess_scaling_configuration.html.markdown
- website/docs/r/instance.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEssAttachment  -timeout=240m
--- PASS: TestAccAlicloudEssAttachment_import (168.51s)
=== RUN   TestAccAlicloudEssAttachment_basic
--- PASS: TestAccAlicloudEssAttachment_basic (184.65s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	353.216
```
> Fix ecs and ess tags read bug with ignore system tag

- CHANGELOG.md
- alicloud/errors.go
- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_managed_kubernetes.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCSKubernetes -timeout=240m
=== RUN   TestAccAlicloudCSKubernetes_import
--- PASS: TestAccAlicloudCSKubernetes_import (1379.52s)
=== RUN   TestAccAlicloudCSKubernetes_basic
--- PASS: TestAccAlicloudCSKubernetes_basic (1348.36s)
=== RUN   TestAccAlicloudCSKubernetes_autoVpc
--- PASS: TestAccAlicloudCSKubernetes_autoVpc (1363.63s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	4091.570s
```
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCSManaged -timeout=240m
=== RUN   TestAccAlicloudCSManagedKubernetes_import
--- PASS: TestAccAlicloudCSManagedKubernetes_import (806.82s)
=== RUN   TestAccAlicloudCSManagedKubernetes_basic
--- PASS: TestAccAlicloudCSManagedKubernetes_basic (740.00s)
=== RUN …
```
> Fix cs_kubernetes setting int value error

- CHANGELOG.md
- alicloud/resource_alicloud_instance_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudInstanceChargeType_post2Pre -timeout=240m
=== RUN   TestAccAlicloudInstanceChargeType_post2Pre
--- PASS: TestAccAlicloudInstanceChargeType_post2Pre (461.18s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	461.225s
```
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudInstance_spot -timeout=240m
=== RUN   TestAccAlicloudInstance_spot
--- PASS: TestAccAlicloudInstance_spot (201.72s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	201.770s
```
> Improve ecs instance testcases

- CHANGELOG.md
- alicloud/data_source_alicloud_kvstore_instances_test.go
- alicloud/resource_alicloud_kvstore_backup_policy_test.go
- alicloud/resource_alicloud_kvstore_instance_test.go
- alicloud/service_alicloud_common_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudKVStore -timeout=240m
=== RUN   TestAccAlicloudKVStoreInstancesDataSource
--- PASS: TestAccAlicloudKVStoreInstancesDataSource (236.09s)
=== RUN   TestAccAlicloudKVStoreInstancesDataSourceEmpty
--- PASS: TestAccAlicloudKVStoreInstancesDataSourceEmpty (1.29s)
=== RUN   TestAccAlicloudKVStoreRedisBackupPolicy_import
--- PASS: TestAccAlicloudKVStoreRedisBackupPolicy_import (223.06s)
=== RUN   TestAccAlicloudKVStoreMemcacheBackupPolicy_import
--- PASS: TestAccAlicloudKVStoreMemcacheBackupPolicy_import (254.29s)
=== RUN   TestAccAlicloudKVStoreRedisInstance_import
--- PASS: TestAccAlicloudKVStoreRedisInstance_import (296.08s)
=== RUN   TestAccAlicloudKVStoreMemcacheInstance_import
--- PASS: TestAccAlicloudKVStoreMemcacheInstance_import …
```
> Improve redis and memcache instance testcases

- alicloud/data_source_alicloud_disks_test.go
- alicloud/resource_alicloud_disk.go
- alicloud/resource_alicloud_disk_test.go
prefected disk testcases and code format
```
> go test ./alicloud -v -run=TestAccAlicloudDisk_ -timeout=1440m
=== RUN   TestAccAlicloudDisk_importBasic
--- PASS: TestAccAlicloudDisk_importBasic (71.86s)
=== RUN   TestAccAlicloudDisk_importWithTags
--- PASS: TestAccAlicloudDisk_importWithTags (71.36s)
=== RUN   TestAccAlicloudDisk_Resize
--- PASS: TestAccAlicloudDisk_Resize (65.86s)
=== RUN   TestAccAlicloudDisk_Multi
--- PASS: TestAccAlicloudDisk_Multi (75.55s)
=== RUN   TestAccAlicloudDisk_withTags
--- PASS: TestAccAlicloudDisk_withTags (69.01s)
=== RUN   TestAccAlicloudDisk_encrypted
--- PASS: TestAccAlicloudDisk_encrypted (72.39s)
=== RUN   TestAccAlicloudDisk_ModifyDiskAttribute
--- PASS: TestAccAlicloudDisk_ModifyDiskAttribute (64.55s)
PASS
ok …
```
> prefected disk testcases 

- CHANGELOG.md
- alicloud/data_source_alicloud_slb_server_groups_test.go
- alicloud/errors.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlbServerGroupsDataSource -timeout=240m
=== RUN   TestAccAlicloudSlbServerGroupsDataSource_basic
--- PASS: TestAccAlicloudSlbServerGroupsDataSource_basic (268.46s)
=== RUN   TestAccAlicloudSlbServerGroupsDataSource_empty
--- PASS: TestAccAlicloudSlbServerGroupsDataSource_empty (116.35s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	384.857s
```
> Modify the slb sever group testcase name

- CHANGELOG.md
- alicloud/errors.go
- alicloud/resource_alicloud_pvtz_zone.go
- alicloud/resource_alicloud_pvtz_zone_attachment.go
- alicloud/resource_alicloud_pvtz_zone_attachment_test.go
- alicloud/resource_alicloud_pvtz_zone_record.go
- alicloud/service_alicloud_pvtz.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudPvtz -timeout=240m
--- PASS: TestAccAlicloudPvtzZoneRecordsDataSource_basic (4.66s)
--- PASS: TestAccAlicloudPvtzZoneRecordsDataSource_empty (1.94s)
=== RUN   TestAccAlicloudPvtzZonesDataSource_basic
--- PASS: TestAccAlicloudPvtzZonesDataSource_basic (3.63s)
=== RUN   TestAccAlicloudPvtzZonesDataSource_empty
--- PASS: TestAccAlicloudPvtzZonesDataSource_empty (0.80s)
--- PASS: TestAccAlicloudPvtzZoneAttachment_importBasic (39.00s)
--- PASS: TestAccAlicloudPvtzZoneRecord_importBasic (3.17s)
=== RUN …
```
> Fix pvtz 'Zone.VpcExists' error

- CHANGELOG.md
- alicloud/resource_alicloud_pvtz_zone_attachment_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudPvtzZoneAttachment -timeout=240m
--- PASS: TestAccAlicloudPvtzZoneAttachment_importBasic (41.52s)
=== RUN   TestAccAlicloudPvtzZoneAttachment_Basic
--- PASS: TestAccAlicloudPvtzZoneAttachment_Basic (33.94s)
=== RUN   TestAccAlicloudPvtzZoneAttachment_update
--- PASS: TestAccAlicloudPvtzZoneAttachment_update (63.87s)
=== RUN   TestAccAlicloudPvtzZoneAttachment_multi
--- PASS: TestAccAlicloudPvtzZoneAttachment_multi (46.26s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	185.657s
```
> Improve pvtz attachment testcase

- CHANGELOG.md
- alicloud/resource_alicloud_datahub_topic.go
- alicloud/resource_alicloud_datahub_topic_test.go
- website/docs/r/datahub_topic.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDatahubTopic_Update -timeout=240m
=== RUN   TestAccAlicloudDatahubTopic_Update
--- PASS: TestAccAlicloudDatahubTopic_Update (2.41s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	2.467s
```
> Add notes for datahub and improve its testcase

- CHANGELOG.md
- alicloud/resource_alicloud_cdn_domain_test.go
- alicloud/resource_alicloud_instance_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCdn -timeout=240m
=== RUN   TestAccAlicloudCdnDomain_basic
--- PASS: TestAccAlicloudCdnDomain_basic (83.27s)
=== RUN   TestAccAlicloudCdnDomain_domestic
--- PASS: TestAccAlicloudCdnDomain_domestic (406.24s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	489.554s
```
> Improve cdn testcase

- alicloud/provider.go
- alicloud/resource_alicloud_logtail_attachment.go
- alicloud/resource_alicloud_logtail_attachment_test.go
- alicloud/resource_alicloud_logtail_config.go
- alicloud/service_alicloud_log.go
- website/alicloud.erb
- website/docs/r/logtail_attachment.html.markdown
=== RUN   TestAccAlicloudLogtailAttachment_basic
--- PASS: TestAccAlicloudLogtailAttachment_basic (10.04s)
=== RUN   TestAccAlicloudLogtailAttachment_MultipleGroup
--- PASS: TestAccAlicloudLogtailAttachment_MultipleGroup (13.28s)
=== RUN   TestAccAlicloudLogtailAttachment_MultipleConfig
--- PASS: TestAccAlicloudLogtailAttachment_MultipleConfig (14.18s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	37.572s
> add new resource logtail addachment

- CHANGELOG.md
- alicloud/resource_alicloud_forward.go
- alicloud/service_alicloud_vpc.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudForward -timeout=240m
=== RUN   TestAccAlicloudForward_basic
--- PASS: TestAccAlicloudForward_basic (58.31s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	58.373s
```
> Fix forward entry UnknownError error

- CHANGELOG.md
- alicloud/errors.go
- alicloud/resource_alicloud_forward.go
- alicloud/resource_alicloud_logtail_attachment.go
- alicloud/resource_alicloud_logtail_attachment_test.go
- alicloud/resource_alicloud_snat.go
- alicloud/service_alicloud_vpc.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSnat -timeout=240m
=== RUN   TestAccAlicloudSnat_basic
--- PASS: TestAccAlicloudSnat_basic (54.74s)
=== RUN   TestAccAlicloudSnat_multi
--- PASS: TestAccAlicloudSnat_multi (84.04s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	138.834s
```
> Fix snat entry IncorretSnatEntryStatus error when deleting

- CHANGELOG.md
- alicloud/data_source_alicloud_disks.go
- alicloud/data_source_alicloud_security_group_rules.go
- alicloud/data_source_alicloud_security_groups.go
- alicloud/data_source_alicloud_vswitches.go
- alicloud/resource_alicloud_disk.go
- alicloud/resource_alicloud_security_group.go
- alicloud/resource_alicloud_security_group_rule.go
- alicloud/resource_alicloud_vswitch.go
=== RUN   TestAccAlicloudVSwitchesDataSource
--- PASS: TestAccAlicloudVSwitchesDataSource (27.59s)
=== RUN   TestAccAlicloudVSwitchesDataSource_Name_Regex
--- PASS: TestAccAlicloudVSwitchesDataSource_Name_Regex (22.19s)
=== RUN   TestAccAlicloudVSwitchesDataSource_vpcid
--- PASS: TestAccAlicloudVSwitchesDataSource_vpcid (25.56s)
=== RUN   TestAccAlicloudVSwitchesDataSource_Zone_ID
--- PASS: TestAccAlicloudVSwitchesDataSource_Zone_ID (20.97s)
=== RUN   TestAccAlicloudVSwitchesDataSourceEmpty
--- PASS: TestAccAlicloudVSwitchesDataSourceEmpty (1.59s)
=== RUN   TestAccAlicloudVSwitch_Update
--- PASS: TestAccAlicloudVSwitch_Update (27.65s)
=== RUN   TestAccAlicloudVSwitch_multi
--- PASS: TestAccAlicloudVSwitch_multi (23.13s)
PASS
ok …
> Apply wraperror to security_group, security_group_rule, vswitch, disk

- alicloud/resource_alicloud_log_project.go
- alicloud/resource_alicloud_log_project_test.go
- alicloud/resource_alicloud_logtail_attachment_test.go
- website/docs/r/log_project.html.markdown
add test case for log project update
update log project error
fix log project docs
> fix resource log project descrition forcenew

- CHANGELOG.md
- alicloud/data_source_alicloud_instance_types.go
- alicloud/data_source_alicloud_instance_types_test.go
- alicloud/resource_alicloud_cs_kubernetes_test.go
- alicloud/resource_alicloud_cs_managed_kubernetes_test.go
- website/docs/d/instance_types.html.markdown
- website/docs/r/cs_kubernetes.html.markdown
- website/docs/r/cs_managed_kubernetes.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCSManaged -timeout=600m
=== RUN   TestAccAlicloudCSManagedKubernetes_import
--- PASS: TestAccAlicloudCSManagedKubernetes_import (769.94s)
=== RUN   TestAccAlicloudCSManagedKubernetes_basic
--- PASS: TestAccAlicloudCSManagedKubernetes_basic (749.70s)
=== RUN   TestAccAlicloudCSManagedKubernetes_autoVpc
--- PASS: TestAccAlicloudCSManagedKubernetes_autoVpc (716.77s)
=== RUN   TestAccAlicloudCSManagedKubernetes_update
--- PASS: TestAccAlicloudCSManagedKubernetes_update (1034.62s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	3271.104s
```
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCSKubernetes -timeout=600m
=== RUN   TestAccAlicloudCSKubernetes_import
--- PASS: TestAccAlicloudCSKubernetes_import …
```
> Add note for kubernetes resource and improve its testcase

- CHANGELOG.md
- alicloud/import_alicloud_elasticsearch_test.go
- alicloud/resource_alicloud_elasticsearch_instance.go
- alicloud/resource_alicloud_elasticsearch_instance_test.go
- alicloud/service_alicloud_elasticsearch.go
- website/docs/r/logtail_attachment.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudElasticsearch -timeout=600m
=== RUN   TestAccAlicloudElasticsearchInstance_import
--- PASS: TestAccAlicloudElasticsearchInstance_import (646.71s)
=== RUN   TestAccAlicloudElasticsearchInstance_basic
--- PASS: TestAccAlicloudElasticsearchInstance_basic (594.38s)
=== RUN   TestAccAlicloudElasticsearchInstance_master_and_whitelist
--- PASS: TestAccAlicloudElasticsearchInstance_master_and_whitelist (2197.09s)
=== RUN   TestAccAlicloudElasticsearchInstance_upgrade
--- PASS: TestAccAlicloudElasticsearchInstance_upgrade (3913.87s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	7352.105s
```
> Wrap resource elasticserarch_instance's error

- alicloud/resource_alicloud_instance.go
- alicloud/service_alicloud_ecs.go
=== RUN   TestAccAlicloudInstancePrivateIp_update
--- PASS: TestAccAlicloudInstancePrivateIp_update (227.97s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	228.033s
> check vpc attributes changed

- alicloud/resource_alicloud_route_entry.go
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRouteEntry -timeout=300m
--- PASS: TestAccAlicloudRouteEntry_importBasic (147.60s)
--- PASS: TestAccAlicloudRouteEntry_Basic (152.09s)
--- PASS: TestAccAlicloudRouteEntry_RouteInterface (26.84s)
=== RUN   TestAccAlicloudRouteEntry_NatGateway
--- PASS: TestAccAlicloudRouteEntry_NatGateway (40.19s)
=== RUN   TestAccAlicloudRouteEntry_Concurrence
--- PASS: TestAccAlicloudRouteEntry_Concurrence (74.28s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	441.064s
> Router Entry Token Bugfix

- alicloud/resource_alicloud_nat_gateway.go
- alicloud/resource_alicloud_nat_gateway_test.go
```
> go test ./alicloud -v -run=TestAccAlicloudNatGateway_ -timeout=1440m
--- PASS: TestAccAlicloudNatGateway_importSpec (29.81s)
=== RUN   TestAccAlicloudNatGateway_update
--- PASS: TestAccAlicloudNatGateway_update (32.74s)
=== RUN   TestAccAlicloudNatGateway_specification
--- PASS: TestAccAlicloudNatGateway_specification (31.68s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     97.237s
```
> Improve nat_gateway testcases

- alicloud/resource_alicloud_eip_association_test.go
```
go test ./alicloud -v -run=TestAccAlicloudEIPAssociation -timeout=1440m
--- PASS: TestAccAlicloudEIPAssociation (178.83s)
=== RUN   TestAccAlicloudEIPAssociation_slb
--- PASS: TestAccAlicloudEIPAssociation_slb (42.64s)
=== RUN   TestAccAlicloudEIPAssociation_nat
--- PASS: TestAccAlicloudEIPAssociation_nat (36.02s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     260.303s
```
> Improve eip_association testcases

- alicloud/resource_alicloud_forward_test.go
- alicloud/resource_alicloud_snat.go
- alicloud/resource_alicloud_snat_test.go
forward:
```
> go test ./alicloud -v -run=TestAccAlicloudForward_basic -timeout=1440m
=== RUN   TestAccAlicloudForward_basic
--- PASS: TestAccAlicloudForward_basic (53.67s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     57.082s
```
snat
```
> go test ./alicloud -v -run=TestAccAlicloudSnat_ -timeout=1440m
=== RUN   TestAccAlicloudSnat_basic
--- PASS: TestAccAlicloudSnat_basic (51.70s)
=== RUN   TestAccAlicloudSnat_multi
--- PASS: TestAccAlicloudSnat_multi (72.87s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     127.550s
```
> Improve snat and forward testcases

- alicloud/resource_alicloud_logtail_config.go
This PR is used to solve the problem that the configuration created with terraform cannot collect logs！
> fix sls logtail config collection error

- alicloud/resource_alicloud_instance.go
- alicloud/resource_alicloud_instance_test.go
- website/docs/r/instance.html.markdown
TF_DEBUG=debug TF_ACC=1 go test  -v -run=TestAccAlicloudInstance_deletionProtection --timeout=600m
=== RUN   TestAccAlicloudInstance_deletionProtection
--- PASS: TestAccAlicloudInstance_deletionProtection (127.76s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	127.817s
> support update deletion_protection option

- alicloud/errors.go
- alicloud/service_alicloud_elasticsearch.go
Fixed bug of error code when timeout for upgrading instance
> fix(error) Fixed bug of error code when timeout for upgrade instance

- alicloud/data_source_alicloud_cen_region_route_entries_test.go
- alicloud/data_source_alicloud_cen_route_entries_test.go
- alicloud/resource_alicloud_cen_route_entry_test.go
- examples/cen/main.tf
- website/docs/r/cen_route_entry.html.markdown
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCenRouteEntry_basic
=== RUN   TestAccAlicloudCenRouteEntry_basic
--- PASS: TestAccAlicloudCenRouteEntry_basic (159.17s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     159.253s
> cen child instance attach after vsw created

- alicloud/resource_alicloud_pvtz_zone_record.go
- alicloud/resource_alicloud_pvtz_zone_record_test.go
- website/docs/r/pvtz_zone_record.html.markdown
=== RUN   TestAccAlicloudPvtzZoneRecord_updateAll
--- PASS: TestAccAlicloudPvtzZoneRecord_updateAll (77.87s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     77.897s
> ForceNew for resource record and zone id updates for pvtz record

- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_db_instance_test.go
- alicloud/service_alicloud_rds.go
- alicloud/validators.go
- examples/rds/main.tf
- examples/rds/variables.tf
- website/docs/r/db_instance.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDBInstance_tags -timeout=300m
=== RUN   TestAccAlicloudDBInstance_tags
--- PASS: TestAccAlicloudDBInstance_tags (57.83s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	57.889s
> rds support op tags

- alicloud/resource_alicloud_db_instance.go
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDBInstance_tags -timeout=300m
=== RUN   TestAccAlicloudDBInstance_tags
--- PASS: TestAccAlicloudDBInstance_tags (119.72s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	119.786s
> fix first create db with tags

- CHANGELOG.md
- alicloud/provider.go
- alicloud/resource_alicloud_cdn_domain_config.go
- alicloud/resource_alicloud_cdn_domain_config_test.go
- alicloud/resource_alicloud_cdn_domain_new.go
- alicloud/service_alicloud_cdn.go
- website/alicloud.erb
- website/docs/r/cdn_domain_config.html.markdown
=== RUN   TestAccAlicloudCdnDomainConfig_basic
--- PASS: TestAccAlicloudCdnDomainConfig_basic (104.62s)
=== RUN   TestAccAlicloudCdnDomainConfig_other
--- PASS: TestAccAlicloudCdnDomainConfig_other (97.96s)
PASS
> new resource cdn_domain_config

- alicloud/provider.go
- alicloud/resource_alicloud_nas_access_group_test.go
- alicloud/resource_alicloud_nas_access_rule.go
- alicloud/resource_alicloud_nas_access_rule_test.go
- alicloud/service_alicloud_nas.go
- examples/nas-access-rule/README.md
- examples/nas-access-rule/main.tf
- examples/nas-access-rule/outputs.tf
- website/alicloud.erb
- website/docs/index.html.markdown
- website/docs/r/nas_access_rule.html.markdown
=== RUN   TestAccAlicloudNas_AccessRule_basic
--- PASS: TestAccAlicloudNas_AccessRule_basic (1.74s)
=== RUN   TestAccAlicloudNas_AccessRule_update
--- PASS: TestAccAlicloudNas_AccessRule_update (2.31s)
PASS
> feat(nas): add resource access rules

- CHANGELOG.md
- alicloud/data_source_alicloud_vpn_connections_test.go
- alicloud/data_source_alicloud_vpn_gateways_test.go
- alicloud/resource_alicloud_cr_namespace_test.go
- alicloud/resource_alicloud_drds_instance_test.go
- alicloud/resource_alicloud_nas_access_rule_test.go
- alicloud/resource_alicloud_slb_test.go
- alicloud/resource_alicloud_ssl_vpn_client_cert_test.go
- alicloud/resource_alicloud_ssl_vpn_server_test.go
- alicloud/resource_alicloud_vpc_test.go
- alicloud/resource_alicloud_vpn_connection_test.go
- alicloud/resource_alicloud_vpn_gateway_test.go
- alicloud/resource_alicloud_vswitch_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudVpn -timeout=240m
=== RUN   TestAccAlicloudVpnConnectionsDataSource_basic
--- PASS: TestAccAlicloudVpnConnectionsDataSource_basic (194.43s)
=== RUN   TestAccAlicloudVpnConnectionsDataSource_empty
--- PASS: TestAccAlicloudVpnConnectionsDataSource_empty (1.45s)
=== RUN   TestAccAlicloudVpnCgwsDataSource_basic
--- PASS: TestAccAlicloudVpnCgwsDataSource_basic (9.97s)
=== RUN   TestAccAlicloudVpnCgwsDataSource_empty
--- PASS: TestAccAlicloudVpnCgwsDataSource_empty (2.02s)
=== RUN   TestAccAlicloudVpnsDataSource_basic
--- PASS: TestAccAlicloudVpnsDataSource_basic (198.88s)
=== RUN   TestAccAlicloudVpnsDataSource_empty
--- PASS: TestAccAlicloudVpnsDataSource_empty (1.22s)
=== RUN   TestAccAlicloudVpnConnection_basic
--- PASS: …
```
> Improve vpn_gateway testcases and some sweeper test

- alicloud/errors.go
- alicloud/import_alicloud_nas_access_group_test.go
- alicloud/import_alicloud_nas_access_rule_test.go
- alicloud/import_alicloud_nas_file_system_test.go
- alicloud/import_alicloud_nas_mount_target_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_kms_key_test.go
- alicloud/resource_alicloud_nas_access_group.go
- alicloud/resource_alicloud_nas_access_group_test.go
- alicloud/resource_alicloud_nas_file_system_test.go
- alicloud/resource_alicloud_nas_mount_target.go
- alicloud/resource_alicloud_nas_mount_target_test.go
- alicloud/service_alicloud_nas.go
- examples/nas-mount-target/README.md
- examples/nas-mount-target/main.tf
- examples/nas-mount-target/outputs.tf
- website/alicloud.erb
- website/docs/r/nas_access_rule.html.markdown
- website/docs/r/nas_mount_target.html.markdown
=== RUN   TestAccAlicloudNas_MountTarget_basic
--- PASS: TestAccAlicloudNas_MountTarget_basic (6.63s)
=== RUN   TestAccAlicloudNas_MountTarget_update
--- PASS: TestAccAlicloudNas_MountTarget_update (11.23s)
PASS
> feat(nas): add resource mount targets

- alicloud/connectivity/regions.go
- alicloud/import_alicloud_nas_mount_target_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_nas_mount_target_test.go
- website/docs/r/nas_mount_target.html.markdown
=== RUN   TestAccAlicloudNas_MountTarget_basic
--- PASS: TestAccAlicloudNas_MountTarget_basic (7.83s)
=== RUN   TestAccAlicloudNas_MountTarget_Vpc_basic
--- PASS: TestAccAlicloudNas_MountTarget_Vpc_basic (31.47s)
=== RUN   TestAccAlicloudNas_MountTarget_update
--- PASS: TestAccAlicloudNas_MountTarget_update (38.63s)
PASS
> fix(nas): fix resource mount target tests

- alicloud/resource_alicloud_slb.go
- alicloud/resource_alicloud_slb_test.go
- website/docs/r/slb.html.markdown
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlb_paybybandwidth -timeout=300m
=== RUN   TestAccAlicloudSlb_paybybandwidth
--- PASS: TestAccAlicloudSlb_paybybandwidth (5.76s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	5.821s
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlb_vpc -timeout=300m
=== RUN   TestAccAlicloudSlb_vpc
--- PASS: TestAccAlicloudSlb_vpc (29.99s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	30.050s
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlb_spec -timeout=300m
=== RUN   TestAccAlicloudSlb_spec
--- PASS: TestAccAlicloudSlb_spec (39.49s) …
> Add Load Balancer PrePaid

- CHANGELOG.md
- alicloud/common.go
- alicloud/resource_alicloud_cen_bandwidth_package.go
- alicloud/resource_alicloud_cen_instance.go
- alicloud/resource_alicloud_common_bandwidth_package.go
- alicloud/resource_alicloud_db_readonly_instance.go
- alicloud/resource_alicloud_disk.go
- alicloud/resource_alicloud_drds_instance.go
- alicloud/resource_alicloud_eip.go
- alicloud/resource_alicloud_havip.go
- alicloud/resource_alicloud_instance.go
- alicloud/resource_alicloud_kvstore_instance.go
- alicloud/resource_alicloud_nas_access_group_test.go
- alicloud/resource_alicloud_nas_file_system_test.go
- alicloud/resource_alicloud_nas_mount_target_test.go
- alicloud/resource_alicloud_nat_gateway.go
- alicloud/resource_alicloud_route_entry.go
- alicloud/resource_alicloud_route_table.go
- alicloud/resource_alicloud_router_interface.go
- alicloud/resource_alicloud_security_group.go
- alicloud/resource_alicloud_slb.go
- alicloud/resource_alicloud_ssl_vpn_client_cert.go
- alicloud/resource_alicloud_ssl_vpn_server.go
- alicloud/resource_alicloud_vpc.go
- alicloud/resource_alicloud_vpn_connection.go
- alicloud/resource_alicloud_vpn_customer_gateway.go
- alicloud/resource_alicloud_vswitch.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSslVpn -timeout=240m
=== RUN   TestAccAlicloudSslVpnClientCert_basic
--- PASS: TestAccAlicloudSslVpnClientCert_basic (233.54s)
=== RUN   TestAccAlicloudSslVpnClientCert_update
--- PASS: TestAccAlicloudSslVpnClientCert_update (207.70s)
=== RUN   TestAccAlicloudSslVpnServer_basic
--- PASS: TestAccAlicloudSslVpnServer_basic (187.90s)
=== RUN   TestAccAlicloudSslVpnServer_update_single_subnet
--- PASS: TestAccAlicloudSslVpnServer_update_single_subnet (187.80s)
=== RUN   TestAccAlicloudSslVpnServer_update
--- PASS: TestAccAlicloudSslVpnServer_update (214.89s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	1031.878s
```
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudVpn -timeout=240m
=== RUN …
```
> Add client token for vpn services

- alicloud/data_source_alicloud_drds_instances.go
- alicloud/data_source_alicloud_drds_instances_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/drds_instances.html.markdown
> add drds support data

- alicloud/data_source_alicloud_drds_instances_test.go
- alicloud/import_alicloud_drds_instance_test.go
- alicloud/resource_alicloud_drds_instance_test.go
- website/docs/r/drds_instance.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDRDSInstancesDataSource -timeout=240m
=== RUN   TestAccAlicloudDRDSInstancesDataSourceNameRegex
--- PASS: TestAccAlicloudDRDSInstancesDataSourceNameRegex (184.97s)
=== RUN   TestAccAlicloudDRDSInstancesDataSourceIds
--- PASS: TestAccAlicloudDRDSInstancesDataSourceIds (256.01s)
=== RUN   TestAccAlicloudDRDSInstancesDataSourceAll
--- PASS: TestAccAlicloudDRDSInstancesDataSourceAll (200.93s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	642.005s
```
> Improve drds instances testcases

- CHANGELOG.md
- alicloud/extension_pvtz.go
- alicloud/import_alicloud_dns_record_test.go
- alicloud/import_alicloud_dns_test.go
- alicloud/resource_alicloud_dns.go
- alicloud/resource_alicloud_dns_group.go
- alicloud/resource_alicloud_dns_group_test.go
- alicloud/resource_alicloud_dns_record.go
- alicloud/resource_alicloud_dns_record_test.go
- alicloud/resource_alicloud_dns_test.go
- alicloud/validators.go
- website/docs/r/dns_record.html.markdown
1.adjust dns resource test case；
2.modify some dns resource update function
> add dns test case

- alicloud/data_source_alicloud_cr_namespaces_test.go
- alicloud/data_source_alicloud_cr_repos.go
- alicloud/data_source_alicloud_cr_repos_test.go
- alicloud/provider.go
- alicloud/service_alicloud_cr.go
- website/alicloud.erb
- website/docs/d/cr_namespaces.html.markdown
- website/docs/d/cr_repos.html.markdown
- website/docs/r/cr_namespace.html.markdown
- website/docs/r/cr_repo.html.markdown
> add cr_repos data source

- CHANGELOG.md
- alicloud/common.go
- alicloud/data_source_alicloud_zones.go
- alicloud/errors.go
- alicloud/resource_alicloud_cms_alarm_test.go
- alicloud/resource_alicloud_security_group.go
- alicloud/service_alicloud_ecs.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSecurityGroup_inner_access -timeout=240m
=== RUN   TestAccAlicloudSecurityGroup_inner_access
--- PASS: TestAccAlicloudSecurityGroup_inner_access (918.89s)
=== RUN   TestAccAlicloudSecurityGroup_inner_access_2
--- PASS: TestAccAlicloudSecurityGroup_inner_access_2 (616.86s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	1535.814s
```
> Remove ModifySecurityGroupPolicy waiting and backend has fixed it

- alicloud/resource_alicloud_slb.go
- alicloud/resource_alicloud_slb_test.go
- website/docs/r/slb.html.markdown
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlb_pay_type -timeout=300m
=== RUN   TestAccAlicloudSlb_pay_type
--- PASS: TestAccAlicloudSlb_pay_type (3.97s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	(cached)
> Slb Add Master Zone Id

- CHANGELOG.md
- alicloud/data_source_alicloud_actiontrail.go
- alicloud/data_source_alicloud_cr_namespaces_test.go
- alicloud/data_source_alicloud_cr_repos_test.go
- alicloud/data_source_alicloud_zones.go
- alicloud/import_alicloud_cr_namespace_test.go
- alicloud/import_alicloud_cr_repo_test.go
- alicloud/resource_alicloud_instance_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlb_pay_type -timeout=240m
=== RUN   TestAccAlicloudSlb_pay_type
--- PASS: TestAccAlicloudSlb_pay_type (11.84s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	11.899s
```
> Sort slb slave zone ids to avoid needless error

- alicloud/resource_alicloud_cen_bandwidth_package.go
- website/docs/r/cen_bandwidth_package.html.markdown
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCenBandwidth
--- PASS: TestAccAlicloudCenBandwidthLimitsDataSource_instance_id (64.83s)
=== RUN   TestAccAlicloudCenBandwidthLimitsDataSource_empty
--- PASS: TestAccAlicloudCenBandwidthLimitsDataSource_empty (0.69s)
=== RUN   TestAccAlicloudCenBandwidthPackagesDataSource_instance_id
--- PASS: TestAccAlicloudCenBandwidthPackagesDataSource_instance_id (12.57s)
=== RUN   TestAccAlicloudCenBandwidthPackagesDataSource_bandwidth_package_nameRegex
--- PASS: TestAccAlicloudCenBandwidthPackagesDataSource_bandwidth_package_nameRegex (10.37s)
=== RUN   TestAccAlicloudCenBandwidthPackagesDataSource_multi_bandwith_packages
--- PASS: …
> switch the region id if needed

- alicloud/resource_alicloud_kvstore_instance.go
- website/docs/r/kvstore_instance.html.markdown
add kv-store auto-renewal option
> support kv-store auto renewal option

- CHANGELOG.md
- alicloud/data_source_alicloud_fc_functions.go
- alicloud/data_source_alicloud_fc_functions_test.go
- alicloud/resource_alicloud_fc_function.go
- alicloud/resource_alicloud_fc_function_test.go
- alicloud/service_alicloud_fc.go
=== RUN   TestAccAlicloudFCFunction_basic
--- PASS: TestAccAlicloudFCFunction_basic (44.01s)
PASS
=== RUN   TestAccAlicloudFcFunctionsDataSource_basic
--- PASS: TestAccAlicloudFcFunctionsDataSource_basic (4.67s)
=== RUN   TestAccAlicloudFcFunctionsDataSource_empty
--- PASS: TestAccAlicloudFcFunctionsDataSource_empty (0.66s)
PASS
> fc_function add new schema environment_variables

- CHANGELOG.md
- alicloud/data_source_alicloud_route_tables_test.go
- alicloud/import_alicloud_snat_entry_test.go
- alicloud/resource_alicloud_snat.go
- alicloud/resource_alicloud_snat_test.go
- alicloud/service_alicloud_vpc.go
- website/docs/r/snat.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSnat -timeout=240m
=== RUN   TestAccAlicloudSnat_basic
--- PASS: TestAccAlicloudSnat_basic (110.91s)
=== RUN   TestAccAlicloudSnat_multi
--- PASS: TestAccAlicloudSnat_multi (226.77s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	337.741s
```
> Resource snat entry update id and support import

- website/docs/r/cs_kubernetes.html.markdown
cidr /24 in example may cause problem, change to /16.
> fix default pod_cidr in k8s docs

- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_db_instance_test.go
- alicloud/service_alicloud_rds.go
- website/docs/r/db_instance.html.markdown
hi, add RDS security group support
--- PASS: TestAccAlicloudDBInstance_securityGroup (94.86s)
PASS
> add RDS security group support

- alicloud/resource_alicloud_instance.go
env TF_DEBUG=debug TF_ACC=1 go test  -v -run=TestAccAlicloudInstance_update --timeout=600m
=== RUN   TestAccAlicloudInstance_update
--- PASS: TestAccAlicloudInstance_update (239.53s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	239.584s
> modify stop instance timeout to 5min

- alicloud/common.go
- alicloud/errors.go
- alicloud/import_alicloud_cen_instance_grant_test.go
- alicloud/provider.go
- alicloud/provider_test.go
- alicloud/resource_alicloud_cen_instance_attachment.go
- alicloud/resource_alicloud_cen_instance_grant.go
- alicloud/resource_alicloud_cen_instance_grant_test.go
- alicloud/service_alicloud_cen.go
- alicloud/service_alicloud_vpc.go
- website/alicloud.erb
- website/docs/r/cen_instance_grant.html.markdown
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCenInstanceGrant
=== RUN   TestAccAlicloudCenInstanceGrant_basic
--- PASS: TestAccAlicloudCenInstanceGrant_basic (18.90s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     18.967s
> resource cen instance grant

- alicloud/resource_alicloud_instance.go
env TF_DEBUG=debug TF_ACC=1 go test  -v -run=TestAccAlicloudInstanceType_update --timeout=600m
=== RUN   TestAccAlicloudInstanceType_update
--- PASS: TestAccAlicloudInstanceType_update (152.29s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	152.359s
> prepaid instance support modify attribute

- alicloud/connectivity/regions.go
- alicloud/resource_alicloud_ddoscoo_instance_test.go
> add ddoscoo test region skip code

- alicloud/extension_slb.go
- alicloud/resource_alicloud_slb_listener_test.go
- alicloud/validators.go
- website/docs/r/slb_listener.html.markdown
Fix slb listener unsupport rr scheduler bugs
> slb create listener with rr scheduler

- alicloud/data_source_alicloud_ddoscoo_instances.go
- alicloud/data_source_alicloud_ddoscoo_instances_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_ddoscoo_instance_test.go
- website/alicloud.erb
- website/docs/d/ddoscoo_instances.html.markdown
> add ddoscoo data source code and docs

- alicloud/data_source_alicloud_ess_scalingconfigurations.go
- alicloud/data_source_alicloud_ess_scalingconfigurations_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/ess_scaling_configurations.html.markdown
=== RUN   TestAccAlicloudEssScalingconfigurationsDataSource_ids
--- PASS: TestAccAlicloudEssScalingconfigurationsDataSource_ids (38.65s)
=== RUN   TestAccAlicloudEssScalingconfigurationsDataSource_name_regex
--- PASS: TestAccAlicloudEssScalingconfigurationsDataSource_name_regex (45.75s)
=== RUN   TestAccAlicloudEssScalingconfigurationsDataSource_scaling_group_id
--- PASS: TestAccAlicloudEssScalingconfigurationsDataSource_scaling_group_id (34.42s)
=== RUN   TestAccAlicloudEssScalingconfigurationsDataSource_combined
--- PASS: TestAccAlicloudEssScalingconfigurationsDataSource_combined (38.27s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     (cached)
> support data source alicloud_ess_scaling_configurations

- alicloud/data_source_alicloud_ess_scalingrules.go
- alicloud/data_source_alicloud_ess_scalingrules_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/ess_scaling_rules.html.markdown
- website/docs/r/ess_scaling_rule.html.markdown
loud -v -run=TestAccAlicloudEssScalingrulesDataSource -timeout=300m
=== RUN   TestAccAlicloudEssScalingrulesDataSource_scaling_group_id
--- PASS: TestAccAlicloudEssScalingrulesDataSource_scaling_group_id (37.58s)
=== RUN   TestAccAlicloudEssScalingrulesDataSource_type
--- PASS: TestAccAlicloudEssScalingrulesDataSource_type (40.01s)
=== RUN   TestAccAlicloudEssScalingrulesDataSource_name_regex
--- PASS: TestAccAlicloudEssScalingrulesDataSource_name_regex (35.74s)
=== RUN   TestAccAlicloudEssScalingrulesDataSource_combined
--- PASS: TestAccAlicloudEssScalingrulesDataSource_combined (38.82s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     152.229s
> support data source alicloud_ess_scaling_rules

- alicloud/resource_alicloud_instance.go
- alicloud/resource_alicloud_instance_test.go
env TF_DEBUG=debug TF_ACC=1 go test  -v -run=TestAccAlicloudInstanceTypePrepaid_update --timeout=600m
=== RUN   TestAccAlicloudInstanceTypePrepaid_update
--- PASS: TestAccAlicloudInstanceTypePrepaid_update (468.91s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	468.961s
> support changing prepaid instance type

- alicloud/resource_alicloud_nat_gateway.go
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudNatGateway -timeout=300m
=== RUN   TestAccAlicloudNatGatewaysDataSourceBasic
--- PASS: TestAccAlicloudNatGatewaysDataSourceBasic (20.93s)
=== RUN   TestAccAlicloudNatGatewaysDataSourceNameRegex
--- PASS: TestAccAlicloudNatGatewaysDataSourceNameRegex (29.14s)
=== RUN   TestAccAlicloudNatGatewaysDataSourceIds
--- PASS: TestAccAlicloudNatGatewaysDataSourceIds (30.71s)
=== RUN   TestAccAlicloudNatGatewaysDataSourceVpcId
--- PASS: TestAccAlicloudNatGatewaysDataSourceVpcId (19.44s)
--- PASS: TestAccAlicloudNatGateway_importSpec (33.74s)
=== RUN   TestAccAlicloudNatGateway_update
--- PASS: TestAccAlicloudNatGateway_update (45.93s)
=== RUN …
> Update Nat Gateway Token

- alicloud/data_source_alicloud_ssl_vpn_client_certs.go
- alicloud/data_source_alicloud_ssl_vpn_client_certs_test.go
- alicloud/data_source_alicloud_ssl_vpn_servers.go
- alicloud/data_source_alicloud_ssl_vpn_servers_test.go
- alicloud/data_source_alicloud_vpn_connections.go
- alicloud/data_source_alicloud_vpn_connections_test.go
- alicloud/data_source_alicloud_vpn_customer_gateways_test.go
- alicloud/data_source_alicloud_vpn_gateways.go
- alicloud/data_source_alicloud_vpn_gateways_test.go
- alicloud/import_alicloud_ssl_vpn_client_certs_test.go
- alicloud/import_alicloud_ssl_vpn_servers_test.go
- alicloud/import_alicloud_vpn_connections_test.go
- alicloud/import_alicloud_vpn_customer_gateways_test.go
- alicloud/import_alicloud_vpn_gateway_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_ssl_vpn_client_cert.go
- alicloud/resource_alicloud_ssl_vpn_server.go
- alicloud/resource_alicloud_ssl_vpn_server_test.go
- alicloud/resource_alicloud_vpn_connection.go
- alicloud/resource_alicloud_vpn_customer_gateway.go
- alicloud/resource_alicloud_vpn_gateway.go
- website/alicloud.erb
- website/docs/d/ssl_vpn_client_certs.html.markdown
- website/docs/d/ssl_vpn_servers.html.markdown
- website/docs/r/ssl_vpn_client_cert.html.markdown
- website/docs/r/ssl_vpn_server.html.markdown
- website/docs/r/vpn_connection.html.markdown
- website/docs/r/vpn_customer_gateway.html.markdown
- website/docs/r/vpn_gateway.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudVpnsDataSource -timeout=300m
=== RUN   TestAccAlicloudVpnsDataSource_basic
--- PASS: TestAccAlicloudVpnsDataSource_basic (172.34s)
=== RUN   TestAccAlicloudVpnsDataSource_empty
--- PASS: TestAccAlicloudVpnsDataSource_empty (0.75s)
PASS
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudVpnGateway -timeout=300m
=== RUN   TestAccAlicloudVpnGateway_importBasic
--- PASS: TestAccAlicloudVpnGateway_importBasic (173.71s)
=== RUN   TestAccAlicloudVpnGateway_basic
--- PASS: TestAccAlicloudVpnGateway_basic (171.85s)
=== RUN   TestAccAlicloudVpnGateway_update
--- PASS: TestAccAlicloudVpnGateway_update (174.89s)
PASS
```
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudVpnCgwsDataSource -timeout=300m
=== RUN …
```
> add data_source and doc of ssl_vpn

- alicloud/common.go
- alicloud/errors.go
- alicloud/import_alicloud_snapshot_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_snapshot.go
- alicloud/resource_alicloud_snapshot_test.go
- alicloud/service_alicloud_ecs.go
- website/alicloud.erb
- website/docs/r/snapshot.html.markdown
TF_DEBUG=debug TF_ACC=1 go test  -v -run=TestAccAlicloudSnapshot --timeout=600m
=== RUN   TestAccAlicloudSnapshot_importBasic
--- PASS: TestAccAlicloudSnapshot_importBasic (212.79s)
=== RUN   TestAccAlicloudSnapshot_basic
--- PASS: TestAccAlicloudSnapshot_basic (241.29s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	454.131s
> support snapshot

- alicloud/data_source_alicloud_snapshots.go
- alicloud/data_source_alicloud_snapshots_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/snapshots.html.markdown
TF_DEBUG=debug TF_ACC=1 go test  -v -run=TestAccAlicloudSnapshotsDataSource_basic --timeout=600m
=== RUN   TestAccAlicloudSnapshotsDataSource_basic
--- PASS: TestAccAlicloudSnapshotsDataSource_basic (239.65s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	239.723s
> support snapshot datasource

- website/docs/r/ram_role.html.markdown
- website/docs/r/ram_role_attachment.html.markdown
修改了如下文件：
1.ram_role_attachment.html.markdown
补充Example Usage
2.ram_role.html.markdown
修改了role name值不正确
> update RAM website document

- website/docs/d/cen_bandwidth_limits.html.markdown
Update cen data source document
> Update cen data source document

- alicloud/data_source_alicloud_ess_scalinggroups.go
- alicloud/data_source_alicloud_ots_instance_attachments.go
- alicloud/data_source_alicloud_ots_instance_attachments_test.go
- alicloud/data_source_alicloud_ots_tables.go
- alicloud/data_source_alicloud_ots_tables_test.go
- alicloud/data_source_alicloud_security_groups_test.go
- alicloud/data_source_alicloud_snapshots.go
- alicloud/data_source_alicloud_snapshots_test.go
- alicloud/service_alicloud_ess.go
--- PASS: TestAccAlicloudEssAttachment_import (158.63s)
=== RUN   TestAccAlicloudEssAttachment_basic
--- PASS: TestAccAlicloudEssAttachment_basic (162.58s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     321.287s
> bugfix: ess go sdk compatibility

- alicloud/errors.go
- alicloud/resource_alicloud_nat_gateway.go
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudNatGateway -timeout=300m
=== RUN   TestAccAlicloudNatGatewaysDataSourceBasic
--- PASS: TestAccAlicloudNatGatewaysDataSourceBasic (21.16s)
=== RUN   TestAccAlicloudNatGatewaysDataSourceNameRegex
--- PASS: TestAccAlicloudNatGatewaysDataSourceNameRegex (22.38s)
=== RUN   TestAccAlicloudNatGatewaysDataSourceIds
--- PASS: TestAccAlicloudNatGatewaysDataSourceIds (22.73s)
=== RUN   TestAccAlicloudNatGatewaysDataSourceVpcId
--- PASS: TestAccAlicloudNatGatewaysDataSourceVpcId (18.38s)
--- PASS: TestAccAlicloudNatGateway_importSpec (29.02s)
=== RUN   TestAccAlicloudNatGateway_update
--- PASS: TestAccAlicloudNatGateway_update (39.63s)
=== RUN …
> Update Nat Gateway Resource

- alicloud/import_alicloud_mongodb_instance_test.go
- alicloud/resource_alicloud_mongodb_instance.go
- alicloud/resource_alicloud_mongodb_instance_test.go
improve mongodb testcase
test result:
=== RUN   TestAccAlicloudMongoDBInstance_import
--- PASS: TestAccAlicloudMongoDBInstance_import (392.21s)
=== RUN   TestAccAlicloudMongoDBInstance_classic
--- PASS: TestAccAlicloudMongoDBInstance_classic (640.36s)
=== RUN   TestAccAlicloudMongoDBInstance_vpc
--- PASS: TestAccAlicloudMongoDBInstance_vpc (699.40s)
=== RUN   TestAccAlicloudMongoDBInstance_multiAZ
--- PASS: TestAccAlicloudMongoDBInstance_multiAZ (1118.28s)
=== RUN   TestAccAlicloudMongoDBInstance_multi_instance
--- PASS: TestAccAlicloudMongoDBInstance_multi_instance (1064.34s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     3914.639s
> improve mongodb testcase

- alicloud/import_alicloud_launch_template_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_launch_template.go
- alicloud/resource_alicloud_launch_template_test.go
- alicloud/service_alicloud_ecs.go
- alicloud/validators.go
- website/alicloud.erb
- website/docs/r/launch_template.html.markdown
TF_DEBUG=debug TF_ACC=1 go test  -v -run=TestAccAlicloudLaunchTemplate --timeout=600m
=== RUN   TestAccAlicloudLaunchTemplate_importBasic
--- PASS: TestAccAlicloudLaunchTemplate_importBasic (2.20s)
=== RUN   TestAccAlicloudLaunchTemplate_basic
--- PASS: TestAccAlicloudLaunchTemplate_basic (4.93s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	7.186s
> support launch template

- README.md
- alicloud/data_source_alicloud_network_interfaces_test.go
- alicloud/diff_suppress_funcs.go
- alicloud/import_alicloud_cms_alarm_test.go
- alicloud/import_alicloud_key_pair_test.go
- alicloud/import_alicloud_network_interface_test.go
- alicloud/provider_test.go
- alicloud/resource_alicloud_cms_alarm.go
- alicloud/resource_alicloud_cms_alarm_test.go
- alicloud/resource_alicloud_key_pair_test.go
- alicloud/resource_alicloud_launch_template.go
- alicloud/resource_alicloud_launch_template_test.go
- alicloud/resource_alicloud_network_interface_attachment_test.go
- alicloud/resource_alicloud_network_interface_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCms -timeout=240m
=== RUN   TestAccAlicloudCmsAlarm_import
--- PASS: TestAccAlicloudCmsAlarm_import (1.83s)
=== RUN   TestAccAlicloudCmsAlarm_basic
--- PASS: TestAccAlicloudCmsAlarm_basic (1.80s)
=== RUN   TestAccAlicloudCmsAlarm_update
--- PASS: TestAccAlicloudCmsAlarm_update (3.21s)
=== RUN   TestAccAlicloudCmsAlarm_disable
--- PASS: TestAccAlicloudCmsAlarm_disable (1.55s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	8.462s
```
> fix cms diff bug and improve its testcases

- alicloud/data_source_alicloud_db_instances.go
- alicloud/data_source_alicloud_db_instances_test.go
fixed rds datasource readOnlyInstanceIDs bug and improve test case
test result:
2019/04/26 17:01:39 
--- PASS: TestAccAlicloudDBInstancesDataSource (119.83s)
PASS
> fixed rds datasource readOnlyInstanceIDs bug and improve test case

- alicloud/data_source_alicloud_nas_protocols.go
- alicloud/data_source_alicloud_nas_protocols_test.go
- alicloud/provider.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/nas/describe_zones.go
- vendor/vendor.json
- website/alicloud.erb
- website/docs/d/nas_protocols.html.markdown
=== RUN   TestAccAlicloudNasZonesDataSourceZoneId
--- PASS: TestAccAlicloudNasZonesDataSourceZoneId (0.31s)
=== RUN   TestAccAlicloudNasZonesDataSourceType
--- PASS: TestAccAlicloudNasZonesDataSourceType (0.18s)
=== RUN   TestAccAlicloudNasZonesDataSourceAll
--- PASS: TestAccAlicloudNasZonesDataSourceAll (0.18s)
PASS
> feat(nas): add datasource describe_zones

- alicloud/data_source_alicloud_slb_attachments.go
- alicloud/data_source_alicloud_slb_listeners.go
- alicloud/data_source_alicloud_slb_rules.go
- alicloud/data_source_alicloud_slb_server_groups.go
修复目前slb部分Data Sources不支持output_file:
1.1.2.  alicloud_slb_attachments
1.1.3.  alicloud_slb_listeners
1.1.4.  alicloud_slb_rules
1.1.5.  alicloud_slb_server_groups
> fix not support outputfile

- website/docs/r/forward.html.markdown
- website/docs/r/route_entry.html.markdown
update route_entry and forward_entry document
> update route_entry and forward_entry document

- alicloud/resource_alicloud_mongodb_instance.go
- alicloud/resource_alicloud_mongodb_instance_test.go
- alicloud/service_alicloud_mongodb.go
- website/docs/r/mongodb_instance.html.markdown
add mongodb backup policy support, test case, document
--- PASS: TestAccAlicloudMongoDBBackupPolicy_base (320.72s)
PASS
> add mongodb backup policy support, test case, document

- alicloud/resource_alicloud_route_entry.go
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRouteEntry -timeout=300m
--- PASS: TestAccAlicloudRouteEntry_importBasic (135.38s)
--- PASS: TestAccAlicloudRouteEntry_Basic (140.61s)
--- PASS: TestAccAlicloudRouteEntry_RouteInterface (22.08s)
=== RUN   TestAccAlicloudRouteEntry_NatGateway
--- PASS: TestAccAlicloudRouteEntry_NatGateway (36.59s)
=== RUN   TestAccAlicloudRouteEntry_Concurrence
--- PASS: TestAccAlicloudRouteEntry_Concurrence (61.30s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	396.008s
> Update Route Entry Resource

- alicloud/extension_ess.go
- alicloud/resource_alicloud_ess_alarm.go
- alicloud/service_alicloud_ess.go
=== RUN   TestAccAlicloudEssAlarm_import
--- PASS: TestAccAlicloudEssAlarm_import (31.57s)
--- PASS: TestAccAlicloudEssAlarm_basic (33.92s)
=== RUN   TestAccAlicloudEssAlarm_with_dimension
--- PASS: TestAccAlicloudEssAlarm_with_dimension (35.09s)
=== RUN   TestAccAlicloudEssAlarm_update
--- PASS: TestAccAlicloudEssAlarm_update (37.52s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     138.164s
> bugfix: ess alarm apply重复创建

- alicloud/import_alicloud_slb_test.go
- alicloud/resource_alicloud_slb.go
- alicloud/resource_alicloud_slb_test.go
修复slb specifiaction 校验逻辑
=== RUN   TestAccAlicloudSlb_classictest
--- PASS: TestAccAlicloudSlb_classictest (23.25s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     23.299s
> slb instance support updating specification

- alicloud/data_source_alicloud_nas_file_systems_test.go
- alicloud/data_source_alicloud_nas_protocols.go
- alicloud/resource_alicloud_nas_file_system_test.go
=== RUN   TestAccAlicloudNas_FileSystem_basic
--- PASS: TestAccAlicloudNas_FileSystem_basic (1.16s)
=== RUN   TestAccAlicloudNas_FileSystem_update
--- PASS: TestAccAlicloudNas_FileSystem_update (1.80s)
=== RUN   TestAccAlicloudNas_FileSystem_multi
--- PASS: TestAccAlicloudNas_FileSystem_multi (2.09s)
PASS
> fix(nas): refactor testcases

- alicloud/common.go
- alicloud/data_source_alicloud_zones.go
- alicloud/data_source_alicloud_zones_test.go
- website/docs/d/zones.html.markdown
=== RUN   TestAccAlicloudSlb_pay_type
--- PASS: TestAccAlicloudSlb_pay_type (8.64s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     8.688s
=== RUN   TestAccAlicloudZonesDataSource_slb
--- PASS: TestAccAlicloudZonesDataSource_slb (3.91s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     3.962s
> fix slb resource limit error

- alicloud/resource_alicloud_nat_gateway.go
- alicloud/resource_alicloud_nat_gateway_test.go
- website/docs/r/nat_gateway.html.markdown
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudNatGateway -timeout=300m
=== RUN   TestAccAlicloudNatGatewaysDataSourceBasic
--- PASS: TestAccAlicloudNatGatewaysDataSourceBasic (25.65s)
=== RUN   TestAccAlicloudNatGatewaysDataSourceNameRegex
--- PASS: TestAccAlicloudNatGatewaysDataSourceNameRegex (31.60s)
=== RUN   TestAccAlicloudNatGatewaysDataSourceIds
--- PASS: TestAccAlicloudNatGatewaysDataSourceIds (31.06s)
=== RUN   TestAccAlicloudNatGatewaysDataSourceVpcId
--- PASS: TestAccAlicloudNatGatewaysDataSourceVpcId (17.92s)
--- PASS: TestAccAlicloudNatGateway_importSpec (29.56s)
=== RUN   TestAccAlicloudNatGateway_update
--- PASS: TestAccAlicloudNatGateway_update (48.29s)
=== RUN …
> Update Nat Gateway PrePaid

- alicloud/resource_alicloud_eip_association.go
- alicloud/resource_alicloud_eip_association_test.go
- website/docs/r/eip_association.html.markdown
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEip -timeout=300m
=== RUN   TestAccAlicloudEipsDataSourceBasic
--- PASS: TestAccAlicloudEipsDataSourceBasic (9.62s)
=== RUN   TestAccAlicloudEip_importBasic
--- PASS: TestAccAlicloudEip_importBasic (4.77s)
=== RUN   TestAccAlicloudEipAssociationBasic
--- PASS: TestAccAlicloudEipAssociationBasic (183.65s)
=== RUN   TestAccAlicloudEipAssociationMulti
--- PASS: TestAccAlicloudEipAssociationMulti (195.33s)
=== RUN   TestAccAlicloudEipAssociationEni
--- PASS: TestAccAlicloudEipAssociationEni (38.99s)
=== RUN   TestAccAlicloudEipBasic_PayByBandwidth
--- PASS: TestAccAlicloudEipBasic_PayByBandwidth (5.51s)
=== RUN   TestAccAlicloudEipBasic_PayByTraffic
--- PASS: …
> Update Eip Association Resource

- alicloud/data_source_alicloud_db_instance_classes.go
- alicloud/data_source_alicloud_db_instance_classes_test.go
- alicloud/data_source_alicloud_db_instance_engines.go
- alicloud/data_source_alicloud_db_instance_engines_test.go
- alicloud/provider.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/rds/struct_available_zone.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/rds/struct_supported_categorys.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/rds/struct_supported_engine_versions.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/rds/struct_supported_engines.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/rds/struct_supported_storage_types.go
- vendor/vendor.json
- website/alicloud.erb
- website/docs/d/db_instance_classes.html.markdown
- website/docs/d/db_instance_engines.html.markdown
add db instance engines and db instance classes data source support
> add db instance engines and db instance classes data source support

- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_managed_kubernetes.go
Fix #1190 
Signed-off-by: Aylei <rayingecho@gmail.com>
> Handle alicloud_cs_*_kubernetes resource NotFound error properly

- alicloud/service_alicloud_nas.go
Fix DescribeNasMountTarget & DescribeNasAccessRule in case there are more than one item
> fix(nas): describe mount target & access rule

- alicloud/service_alicloud_slb.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/create_load_balancer.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/create_load_balancer_http_listener.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/create_load_balancer_https_listener.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/create_load_balancer_tcp_listener.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/describe_load_balancer_attribute.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/describe_load_balancer_http_listener_attribute.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/describe_load_balancer_https_listener_attribute.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/describe_load_balancer_tcp_listener_attribute.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/describe_rule_attribute.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/set_load_balancer_http_listener_attribute.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/set_load_balancer_https_listener_attribute.go
- vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/set_load_balancer_tcp_listener_attribute.go
- vendor/vendor.json
> update slb sdk

- alicloud/data_source_alicloud_elasticsearch_instances.go
- alicloud/data_source_alicloud_elasticsearch_instances_test.go
- alicloud/diff_suppress_funcs.go
- alicloud/extension_elasticsearch.go
- alicloud/resource_alicloud_elasticsearch_instance.go
- website/docs/d/elasticsearch.html.markdown
- website/docs/r/elasticsearch.html.markdown
Added es version 6.7 supported and fixed bug of version different update.
> docs(version) Added 6.7 supported and fixed bug of version difference.

- alicloud/data_source_alicloud_gpdb_instances.go
- alicloud/data_source_alicloud_gpdb_instances_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/gpdb_instances.html.markdown
=== RUN   TestAccAlicloudGpdbInstancesDataSource
--- PASS: TestAccAlicloudGpdbInstancesDataSource (815.55s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     815.611s
> terraform support gpdb data source

- alicloud/resource_alicloud_eip.go
- alicloud/resource_alicloud_eip_test.go
- website/docs/r/eip.html.markdown
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEip -timeout=300m
=== RUN   TestAccAlicloudEipsDataSourceBasic
--- PASS: TestAccAlicloudEipsDataSourceBasic (6.91s)
=== RUN   TestAccAlicloudEip_importBasic
--- PASS: TestAccAlicloudEip_importBasic (1.92s)
=== RUN   TestAccAlicloudEipAssociationBasic
--- PASS: TestAccAlicloudEipAssociationBasic (159.29s)
=== RUN   TestAccAlicloudEipAssociationMulti
--- PASS: TestAccAlicloudEipAssociationMulti (165.49s)
=== RUN   TestAccAlicloudEipAssociationEni
--- PASS: TestAccAlicloudEipAssociationEni (37.04s)
=== RUN   TestAccAlicloudEipBasic_PayByBandwidth
--- PASS: TestAccAlicloudEipBasic_PayByBandwidth (4.50s)
=== RUN   TestAccAlicloudEipBasic_PayByTraffic
--- PASS: …
> Update Eip Resource Isp Field

- alicloud/errors.go
=== RUN   TestAccAlicloudNas_MountTarget_update
--- PASS: TestAccAlicloudNas_MountTarget_update (38.54s)
=== RUN   TestAccAlicloudNas_MountTarget_updateT
--- PASS: TestAccAlicloudNas_MountTarget_updateT (49.85s)
PASS
> feat(nas): fix error report

- alicloud/provider.go
- alicloud/resource_alicloud_gpdb_connection.go
- alicloud/resource_alicloud_gpdb_connection_test.go
- alicloud/service_alicloud_gpdb.go
- website/alicloud.erb
- website/docs/r/gpdb_connection.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudGpdbConnectionUpdate -timeout=300m
=== RUN   TestAccAlicloudGpdbConnectionUpdate
--- PASS: TestAccAlicloudGpdbConnectionUpdate (1131.58s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     1131.631s
> gpdb connection resource

- alicloud/resource_alicloud_ess_alarm.go
- alicloud/resource_alicloud_ess_alarm_test.go
- website/docs/r/ess_alarm.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEssAlarm -timeout=300m 
--- PASS: TestAccAlicloudEssAlarm_basic (141.60s)
=== RUN   TestAccAlicloudEssAlarm_multi
--- PASS: TestAccAlicloudEssAlarm_multi (59.46s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     201.128s
> feature: support enable/disable action for resource alicloud_ess_alarm.

- website/docs/r/log_store.html.markdown
- website/docs/r/logtail_config.html.markdown
> fix sls-logconfig config_name field to name

- alicloud/common.go
- alicloud/errors.go
- alicloud/resource_alicloud_cen_bandwidth_limit.go
- alicloud/resource_alicloud_cen_instance.go
- alicloud/resource_alicloud_elasticsearch_instance.go
- alicloud/resource_alicloud_instance.go
- alicloud/service_alicloud_api_gateway.go
- alicloud/service_alicloud_elasticsearch.go
Add function BuildStateConf for common timeouts setting.
> Add function BuildStateConf for common timeouts setting.

- alicloud/extension_ess.go
- alicloud/resource_alicloud_ess_scalinggroup.go
--- PASS: TestAccAlicloudEssScalingGroup_basic (74.74s)
--- PASS: TestAccAlicloudEssScalingGroup_vpc (65.26s)
--- PASS: TestAccAlicloudEssScalingGroup_slb (101.97s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     242.030s
> bugfix: modify ess loadbalancers batch size

- CHANGELOG.md
- alicloud/data_source_alicloud_cs_kubernetes_clusters_test.go
- alicloud/data_source_alicloud_cs_managed_kubernetes_clusters_test.go
- alicloud/data_source_alicloud_ddoscoo_instances_test.go
- alicloud/resource_alicloud_cas_certificate.go
- alicloud/resource_alicloud_cs_kubernetes_test.go
- alicloud/resource_alicloud_cs_managed_kubernetes_test.go
- alicloud/resource_alicloud_ddoscoo_instance_test.go
- alicloud/resource_alicloud_mongodb_sharding_instance_test.go
- examples/ddoscoo/main.tf
- website/docs/r/ddoscoo_instance.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCasCertificate -timeout=240m
=== RUN   TestAccAlicloudCasCertificatesDataSource_certificates
--- PASS: TestAccAlicloudCasCertificatesDataSource_certificates (2.26s)
=== RUN   TestAccAlicloudCasCertificate_basic
--- PASS: TestAccAlicloudCasCertificate_basic (2.08s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	4.394s
```
> Fix alicloud_cas_certificate setId bug

- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_slb.go
- alicloud/resource_alicloud_slb_test.go
- website/docs/r/slb.html.markdown
=== RUN   TestAccAlicloudSlb_delete_protection_test
--- PASS: TestAccAlicloudSlb_delete_protection_test (31.83s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     31.888s
> improve(slb):support slb instance delete protection

- alicloud/data_source_alicloud_db_instance_engines.go
- alicloud/data_source_alicloud_kvstore_instance_classes.go
- alicloud/data_source_alicloud_kvstore_instance_classes_test.go
- alicloud/data_source_alicloud_kvstore_instance_engines.go
- alicloud/data_source_alicloud_kvstore_instance_engines_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/kvstore_instance_engines.html.markdown
现在接口还不支持返回memcache, 加了memcache的测试用例就报错了
> feature: add data source kvstore instance engines

- alicloud/resource_alicloud_kvstore_instance.go
> fix(kvstore): kvstore_instance PostPaid to PrePaid error

- alicloud/resource_alicloud_disk.go
- website/docs/r/disk.html.markdown
terraform apply
Error: alicloud_disk.disk: "encrypted": conflicts with snapshot_id ("s-xxxxxxxxxxxxxxxxxx")
Error: alicloud_disk.disk: "snapshot_id": conflicts with encrypted (true)
> improve(disk): the snapshot_id conflicts with encrypted

- alicloud/data_source_alicloud_db_instance_classes.go
- alicloud/data_source_alicloud_db_instance_classes_test.go
- website/docs/d/db_instance_classes.html.markdown
> improve(db_instance_classes): add new parameter db_instance_class

- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_slb_rule.go
- alicloud/resource_alicloud_slb_rule_test.go
- examples/slb-rule/main.tf
- website/docs/r/slb_rule.html.markdown
=== RUN   TestAccAlicloudSlbRuleUpdate
--- PASS: TestAccAlicloudSlbRuleUpdate (389.02s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     389.072s
> improve(slb_rule): support health check config

- alicloud/resource_alicloud_db_backup_policy_test.go
- website/docs/r/db_backup_policy.html.markdown
> fix(db_backup_policy): pg10 of category 'basic' modify log_backup error

- alicloud/extension_slb.go
- alicloud/resource_alicloud_slb_server_group.go
- alicloud/resource_alicloud_slb_server_group_test.go
- examples/slb-server-group/main.tf
- website/docs/r/slb_server_group.html.markdown
=== RUN   TestAccAlicloudSlbServerGroup_vpc
--- PASS: TestAccAlicloudSlbServerGroup_vpc (165.91s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     165.976s
> improve(slb_vserver_group): support attaching eni

- alicloud/resource_alicloud_slb_rule.go
=== RUN   TestAccAlicloudSlbRuleUpdate
--- PASS: TestAccAlicloudSlbRuleUpdate (246.41s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     246.479s
> fix(slb_rule): fix testcase bug

- alicloud/resource_alicloud_db_instance.go
- website/docs/r/db_instance.html.markdown
> improve(rds): resource db_instance support update for instance_charge_type

- alicloud/data_source_alicloud_mongodb_instances_test.go
- alicloud/resource_alicloud_db_readonly_instance.go
> fix(db_readonly_instance): add retryable error content in instance spec modification and deletion

- alicloud/data_source_alicloud_ons_instances.go
- alicloud/data_source_alicloud_ons_instances_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_ons_instance.go
- alicloud/resource_alicloud_ons_instance_test.go
- website/alicloud.erb
- website/docs/d/ons_instances.html.markdown
add new data source: ons instances
> feat(ons_instances): new datasource alicloud_ons_instances

- alicloud/resource_alicloud_kms_key.go
- alicloud/resource_alicloud_kms_key_test.go
- alicloud/service_alicloud_kms.go
- website/docs/r/kms_key.html.markdown
> improve(kms_key): modify the param `description` to forcenew

- website/docs/d/mns_queues.html.markdown
improve(mns):modified mns_queues.html
> improve(mns):modified mns_queues.html

- alicloud/resource_alicloud_db_backup_policy_test.go
- alicloud/resource_alicloud_db_instance_test.go
> fix(db_backup_policy): resource db_backup_policy testcase use datasource db_instance_classes

- alicloud/resource_alicloud_ots_table.go
- website/docs/r/ots_table.html.markdown
> fix(ots_table): fix setting deviation_cell_version_in_sec error

- alicloud/errors.go
- alicloud/extension_ecs.go
- alicloud/resource_alicloud_disk.go
- alicloud/resource_alicloud_disk_attachment_test.go
env TF_DEBUG=debug TF_ACC=1 go test  -v -run=TestAccAlicloudDiskAttachment --timeout=600m
=== RUN   TestAccAlicloudDiskAttachment
--- PASS: TestAccAlicloudDiskAttachment (191.71s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     191.757s
env TF_DEBUG=debug TF_ACC=1 go test  -v -run=TestAccAlicloudDisk_basic --timeout=600m
=== RUN   TestAccAlicloudDisk_basic
--- PASS: TestAccAlicloudDisk_basic (68.13s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     68.174s
> support online resize

- alicloud/data_source_alicloud_dns_groups.go
- alicloud/data_source_alicloud_dns_groups_test.go
- website/docs/d/dns_groups.html.markdown
> improve(dns_groups): Added ids filter and added names to datasource attributes.

- alicloud/extension_slb.go
- alicloud/resource_alicloud_slb_server_group.go
- alicloud/resource_alicloud_slb_server_group_test.go
- examples/slb-server-group/main.tf
=== RUN   TestAccAlicloudSlbServerGroup_vpc
--- PASS: TestAccAlicloudSlbServerGroup_vpc (518.26s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     518.322s
> fix(slb_server_group): fix  the maximum number of backend servers added to a slb_server_group

- alicloud/resource_alicloud_eip_association.go
- alicloud/resource_alicloud_eip_association_test.go
- website/docs/r/eip_association.html.markdown
$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEipAssociationEni -timeout=300s
=== RUN   TestAccAlicloudEipAssociationEni
--- PASS: TestAccAlicloudEipAssociationEni (43.04s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     43.066s
> 增加PrivateIPAddress字段，修改markdown中内容

- CHANGELOG.md
- alicloud/extension_ess.go
- alicloud/resource_alicloud_ess_scalinggroup.go
- alicloud/resource_alicloud_ess_scalinggroup_test.go
- website/docs/r/ess_scaling_group.html.markdown
--- PASS: TestAccAlicloudEssScalingconfigurationsDataSource (75.33s)
--- PASS: TestAccAlicloudEssScalinggroupsDataSource (53.64s)
--- PASS: TestAccAlicloudEssScalingrulesDataSource (76.42s)
--- PASS: TestAccAlicloudEssAlarm_basic (126.11s)
=== RUN   TestAccAlicloudEssAlarm_multi
--- PASS: TestAccAlicloudEssAlarm_multi (56.45s)
=== RUN   TestAccAlicloudEssAttachment_update
--- PASS: TestAccAlicloudEssAttachment_update (142.52s)
=== RUN   TestAccAlicloudEssLifecycleHook_basic
--- PASS: TestAccAlicloudEssLifecycleHook_basic (69.25s)
=== RUN   TestAccAlicloudEssScalingConfigurationUpdate
--- …
> Support multi_az_policy of 'COST_OPTIMIZED'

- alicloud/resource_alicloud_security_group_rule.go
- alicloud/resource_alicloud_security_group_rule_test.go
- website/docs/r/security_group_rule.html.markdown
env TF_DEBUG=debug TF_ACC=1 go test  -v -run=TestAccAlicloudSecurityGroupRuleBasic --timeout=600m
=== RUN   TestAccAlicloudSecurityGroupRuleBasic
--- PASS: TestAccAlicloudSecurityGroupRuleBasic (18.19s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     18.238s
> support sg description

- alicloud/resource_alicloud_network_interface.go
- website/docs/r/network_interface.html.markdown
> support mac address

- CHANGELOG.md
- alicloud/errors.go
- alicloud/provider.go
- alicloud/resource_alicloud_ess_notification.go
- alicloud/resource_alicloud_ess_notification_test.go
- alicloud/service_alicloud_ess.go
- website/alicloud.erb
- website/docs/r/ess_notification.html.markdown
=== RUN   TestAccAlicloudEssNotification_basic
--- PASS: TestAccAlicloudEssNotification_basic (73.40s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     73.461s
> Support new resource: alicloud_ess_notification

- alicloud/service_alicloud_ess.go
=== RUN   TestAccAlicloudEssNotification_basic
--- PASS: TestAccAlicloudEssNotification_basic (68.99s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     69.053s
> bugfix：throw notFoundError when scalingGroup is not found.

- alicloud/resource_alicloud_route_entry.go
- alicloud/resource_alicloud_route_entry_test.go
- website/docs/r/route_entry.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRouteEntry -timeout=300m
=== RUN   TestAccAlicloudRouteEntryInstance
--- PASS: TestAccAlicloudRouteEntryInstance (139.57s)
=== RUN   TestAccAlicloudRouteEntryInterface
--- PASS: TestAccAlicloudRouteEntryInterface (32.55s)
=== RUN   TestAccAlicloudRouteEntryNatGateway
--- PASS: TestAccAlicloudRouteEntryNatGateway (46.19s)
=== RUN   TestAccAlicloudRouteEntryMulti
--- PASS: TestAccAlicloudRouteEntryMulti (70.79s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	289.106s
> Update RouteEntry Resource RouteEntryName Field

- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_db_instance.go
> improve(rds): fix db_instance apply error after import

- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_slb.go
- alicloud/resource_alicloud_slb_attachment_test.go
- alicloud/resource_alicloud_slb_test.go
- alicloud/service_alicloud_common_test.go
- website/docs/r/slb.html.markdown
=== RUN   TestAccAlicloudSlb_classictest
--- PASS: TestAccAlicloudSlb_classictest (26.90s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud 
=== RUN   TestAccAlicloudSlb_vpctest
--- PASS: TestAccAlicloudSlb_vpctest (55.05s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     55.108s
=== RUN   TestAccAlicloudSlb_vpcmulti
--- PASS: TestAccAlicloudSlb_vpcmulti (71.09s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     71.147s
> Improve(slb):slb support set AddressIpVersion

- CHANGELOG.md
- alicloud/resource_alicloud_ess_alarm.go
- alicloud/resource_alicloud_ess_alarm_test.go
- website/docs/r/ess_alarm.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEss -timeout=300m
--- PASS: TestAccAlicloudEssScalingconfigurationsDataSource (70.79s)
--- PASS: TestAccAlicloudEssScalinggroupsDataSource (57.22s)
--- PASS: TestAccAlicloudEssScalingrulesDataSource (92.45s)
--- PASS: TestAccAlicloudEssAlarm_basic (162.06s)
=== RUN   TestAccAlicloudEssAlarm_multi
--- PASS: TestAccAlicloudEssAlarm_multi (68.04s)
=== RUN   TestAccAlicloudEssAttachment_update
--- PASS: TestAccAlicloudEssAttachment_update (133.28s)
=== RUN   TestAccAlicloudEssLifecycleHook_basic
--- PASS: TestAccAlicloudEssLifecycleHook_basic …
> bugfix: resourceAlicloudEssAlarm's param scaling_group_id support

- alicloud/data_source_alicloud_ddosbgp_instances_test.go
- alicloud/resource_alicloud_ddosbgp_instance.go
- alicloud/resource_alicloud_ddosbgp_instance_test.go
- examples/ddosbgp/variables.tf
- website/docs/r/ddosbgp_instance.html.markdown
update ddosbgp instance default period to 12,and add bandwidth value 201,and update testcase.
> Update the default period of the ddosbgp instance to 12, add the bandwidth value 201, and update the test case.

- alicloud/resource_alicloud_emr_cluster_test.go
- alicloud/service_alicloud_common_test.go
Create the new vswitch_id and security_group when creating cluster.
> improve emr test case

- alicloud/common.go
- alicloud/resource_alicloud_slb_listener.go
- alicloud/resource_alicloud_slb_listener_test.go
- alicloud/service_alicloud_common_test.go
- alicloud/service_alicloud_slb.go
- website/docs/r/slb_listener.html.markdown
=== RUN   TestAccAlicloudSlbListener_http_basic
--- PASS: TestAccAlicloudSlbListener_http_basic (74.76s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     74.819s
=== RUN   TestAccCheckSlbListenerForward
--- PASS: TestAccCheckSlbListenerForward (18.21s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     18.278s
=== RUN   TestAccAlicloudSlbListener_https_update
--- PASS: TestAccAlicloudSlbListener_https_update (69.56s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     69.627s
=== RUN   TestAccAlicloudSlbListener_tcp_basic
--- PASS: TestAccAlicloudSlbListener_tcp_basic (49.62s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     49.688s
=== RUN …
> impove(slb_listener) slb listener support same port.

- go.mod
--- PASS: TestAccAlicloudOtsTablesDataSource_basic (522.36s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     522.445s
--- PASS: TestAccAlicloudOtsTable_basic (529.28s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     529.367s
--- PASS: TestAccAlicloudOtsTable_highPerformance (516.19s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     516.283s
> update tablestore package

- alicloud/extension_ecs.go
- alicloud/resource_alicloud_instance.go
- alicloud/resource_alicloud_instance_test.go
- website/docs/r/instance.html.markdown
This PR added credit_specification to ECS instance resource
> Added credit_specification to ECS instance resource

- alicloud/resource_alicloud_slb_acl_test.go
> improve(slb): updated slb acl testcase.

- alicloud/resource_alicloud_slb_ca_certificate_test.go
updated slb slb_attachment testcase
> improve(slb): updated slb ca_certificate testcase. 

- alicloud/resource_alicloud_slb_attachment_test.go
> improve(slb): updated slb slb_attachment testcase.

- alicloud/resource_alicloud_slb_server_certificate_test.go
improve(slb): updated slb serverCertificate testcase.
> improve(slb): updated slb serverCertificate testcase.

- CHANGELOG.md
- alicloud/extension_ess.go
- alicloud/resource_alicloud_ess_scalingrule.go
- alicloud/resource_alicloud_ess_scalingrule_test.go
- website/docs/r/ess_scaling_rule.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEss -timeout=300m
--- PASS: TestAccAlicloudEssScalingconfigurationsDataSource (79.86s)
--- PASS: TestAccAlicloudEssScalinggroupsDataSource (62.71s)
--- PASS: TestAccAlicloudEssScalingrulesDataSource (106.96s)
--- PASS: TestAccAlicloudEssAlarm_basic (181.80s)
=== RUN   TestAccAlicloudEssAlarm_multi
--- PASS: TestAccAlicloudEssAlarm_multi (68.69s)
=== RUN   TestAccAlicloudEssAttachment_update
--- PASS: TestAccAlicloudEssAttachment_update (124.18s)
=== RUN   TestAccAlicloudEssLifecycleHook_basic
--- PASS: TestAccAlicloudEssLifecycleHook_basic …
> Improve(alicloud_ess_scaling_rule): support TargetTrackingScalingRule and StepScalingRule

- alicloud/data_source_alicloud_cs_managed_kubernetes_clusters_test.go
- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_managed_kubernetes_test.go
fix issue https://github.com/terraform-providers/terraform-provider-alicloud/issues/1207
> fix (cs) : log_config support create new project

- alicloud/data_source_alicloud_common_bandwidth_package_test.go
- alicloud/data_source_alicloud_common_bandwidth_packages.go
- alicloud/resource_alicloud_common_bandwidth_package.go
- alicloud/resource_alicloud_common_bandwidth_package_test.go
- website/docs/d/common_bandwidth_packages.html.markdown
- website/docs/r/common_bandwidth_package.html.markdown
add resource_group_id to common_bandwidth_package(resource and data_source) and revise corresponding docs
> Add resource_group_id to common_bandwidth_package(resource&data_source)

- alicloud/resource_alicloud_slb_rule_test.go
improve(slb): updated slb rule testcase.
> improve(slb): updated slb rule testcase. 

- CHANGELOG.md
- alicloud/resource_alicloud_common_bandwidth_package.go
> fix(common_bandwidth_package): fix common bandwidth package resource_group_id forcenew bug

- alicloud/resource_alicloud_slb_server_group_test.go
improve(slb): updated slb server_group testcase.
> improve(slb): updated slb server_group testcase.

- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_cs_serverless_kubernetes_clusters.go
- alicloud/data_source_alicloud_cs_serverless_kubernetes_clusters_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cs_serverless_kubernetes.go
- alicloud/resource_alicloud_cs_serverless_kubernetes_test.go
- alicloud/service_alicloud_cs.go
- examples/serverless-kubernetes/README.md
- examples/serverless-kubernetes/main.tf
- examples/serverless-kubernetes/outputs.tf
- examples/serverless-kubernetes/variables.tf
- go.mod
- go.sum
- vendor/github.com/denverdino/aliyungo/cs/clusters.go
- vendor/github.com/denverdino/aliyungo/cs/serverless.go
- vendor/modules.txt
- website/alicloud.erb
- website/docs/d/cs_serverless_kubernetes_clusters.html.markdown
- website/docs/r/cs_serverless_kubernetes.html.markdown
fix typo 
The correct is serverless,not serveless
> rename cs_serveless_kubernetes to cs_serverless_kubernetes

- alicloud/connectivity/client.go
- alicloud/data_source_alicloud_zones.go
- ci/pipeline.yml
- website/docs/r/ess_scaling_configuration.html.markdown
> improve(zones): using describeAvailableResource instead of DescribeZones for RKvstore

- CHANGELOG.md
- alicloud/data_source_alicloud_alikafka_consumer_groups_test.go
- alicloud/data_source_alicloud_alikafka_topics_test.go
- alicloud/data_source_alicloud_file_crc64_checksum.go
- alicloud/data_source_alicloud_file_crc64_checksum_test.go
- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_alikafka_consumer_group_test.go
- alicloud/resource_alicloud_alikafka_topic_test.go
- ci/configure
- ci/pipeline.yml
- ci/tasks/run.sh
- ci/tasks/run.yml
- website/docs/r/alikafka_consumer_group.html.markdown
- website/docs/r/alikafka_instance.html.markdown
- website/docs/r/alikafka_topic.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlb -timeout=1200m
=== RUN   TestAccAlicloudSlbAclsDataSource_basic
--- PASS: TestAccAlicloudSlbAclsDataSource_basic (6.29s)
=== RUN   TestAccAlicloudSlbAttachmentsDataSource_basic
--- PASS: TestAccAlicloudSlbAttachmentsDataSource_basic (119.96s)
=== RUN   TestAccAlicloudSlbBackendServersDataSource_basic
--- PASS: TestAccAlicloudSlbBackendServersDataSource_basic (120.79s)
=== RUN   TestAccAlicloudSlbCACertificatesDataSource_basic
--- PASS: TestAccAlicloudSlbCACertificatesDataSource_basic (5.92s)
=== RUN   TestAccAlicloudSlbListenersDataSourceUpdate_http
--- PASS: TestAccAlicloudSlbListenersDataSourceUpdate_http (45.69s)
=== RUN   TestAccAlicloudSlbListenersDataSource_https
--- PASS: TestAccAlicloudSlbListenersDataSource_https (20.25s) …
```
> fix(slb): address_type diff bug

- CHANGELOG.md
- alicloud/data_source_alicloud_slb_listeners.go
- alicloud/data_source_alicloud_slb_listeners_test.go
- alicloud/resource_alicloud_slb_listener.go
- alicloud/resource_alicloud_slb_listener_test.go
- website/docs/r/slb_listener.html.markdown
> improve(slb_listener): deprecate ssl_certificate_id and use server_certificate_id instead

- alicloud/data_source_alicloud_db_instances.go
- alicloud/data_source_alicloud_db_instances_test.go
- website/docs/d/db_instances.html.markdown
--- PASS: TestAccAlicloudDBInstancesDataSource (482.44s)
PASS
> improve(db_instances):update tags type from string to map

- alicloud/data_source_alicloud_sag_acls.go
- alicloud/data_source_alicloud_sag_acls_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_sag_acl.go
- alicloud/resource_alicloud_sag_acl_rule.go
- alicloud/resource_alicloud_sag_acl_rule_test.go
- alicloud/resource_alicloud_sag_acl_test.go
- alicloud/service_alicloud_sag.go
- examples/sag_acl/main.tf
- examples/sag_acl/versions.tf
- examples/sag_acl_rule/main.tf
- examples/sag_acl_rule/versions.tf
- website/alicloud.erb
- website/docs/d/sag_acls.html.markdown
- website/docs/r/sag_acl.html.markdown
- website/docs/r/sag_acl_rule.html.markdown
> add sag_acl and sag_acl_rule

- alicloud/data_source_alicloud_db_instance_classes.go
- alicloud/resource_alicloud_db_database.go
- examples/rds/main.tf
- examples/rds/variables.tf
- website/docs/d/db_instance_classes.html.markdown
- website/docs/d/db_instances.html.markdown
- website/docs/r/db_account.html.markdown
- website/docs/r/db_database.html.markdown
> add ids for db_instance_classess and remove limitation for db_database resource

- CHANGELOG.md
- alicloud/extension_ess.go
- alicloud/resource_alicloud_ess_scheduled_task.go
- website/alicloud.erb
- website/docs/index.html.markdown
- website/docs/r/ess_scheduled_task.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEssScheduled -timeout=1200m
=== RUN   TestAccAlicloudEssScheduledTask_basic
--- PASS: TestAccAlicloudEssScheduledTask_basic (102.03s)
=== RUN   TestAccAlicloudEssScheduledTask_multi
--- PASS: TestAccAlicloudEssScheduledTask_multi (45.68s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     147.828s
```
> alicloud_ess_scheduled_task supports Cron type

- alicloud/provider.go
- alicloud/provider_test.go
- alicloud/resource_alicloud_sag_snat_entry.go
- alicloud/resource_alicloud_sag_snat_entry_test.go
- alicloud/service_alicloud_sag.go
- examples/sag_snat_entry/main.tf
- examples/sag_snat_entry/versions.tf
- website/alicloud.erb
- website/docs/r/sag_snat_entry.html.markdown
> add sag_snat

- website/alicloud.erb
> change sideBar

- alicloud/extension_rds.go
- website/docs/r/db_database.html.markdown
fix(resource_alicloud_db_database):fix api rds resource bug
> improve(resource_alicloud_db_database): support Mohawk_100_BIN

- website/docs/d/db_instances.html.markdown
- website/docs/r/db_backup_policy.html.markdown
perf(alicloud_db_backup_policy,db_instances):perf rds document desc
> perf(alicloud_db_backup_policy,db_instances):perf rds document desc

- alicloud/service_alicloud_rds.go
> improve(rds): fix for hidden dts ip list

- alicloud/data_source_alicloud_kvstore_instance_engines.go
```
$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudKVStoreInstanceEngines -timeout=1200m
=== RUN   TestAccAlicloudKVStoreInstanceEngines
--- PASS: TestAccAlicloudKVStoreInstanceEngines (71.35s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     71.415s
```
> improve(kvstore_instance_engines): improve its code

- alicloud/data_source_alicloud_zones.go
- alicloud/resource_alicloud_db_backup_policy_test.go
- website/docs/r/db_backup_policy.html.markdown
> improve(zones): use describeAvailableResource API to get rds available zones

- alicloud/resource_alicloud_oss_bucket.go
- alicloud/resource_alicloud_oss_bucket_test.go
- website/docs/r/oss_bucket.html.markdown
> improve(oss): add transitions to life-cycle

- alicloud/extension_ess.go
- alicloud/resource_alicloud_ess_alarm.go
- alicloud/resource_alicloud_ess_attachment.go
- alicloud/resource_alicloud_ess_scalingconfiguration.go
- alicloud/resource_alicloud_ess_scalingrule.go
- alicloud/resource_alicloud_ess_scalingrule_test.go
- alicloud/resource_alicloud_ess_scheduled_task.go
- website/docs/d/ess_scaling_configurations.html.markdown
- website/docs/r/ess_alarm.html.markdown
- website/docs/r/ess_notification.html.markdown
- website/docs/r/ess_scaling_configuration.html.markdown
- website/docs/r/ess_scaling_group.html.markdown
- website/docs/r/ess_scaling_lifecycle_hook.html.markdown
- website/docs/r/ess_scaling_rule.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEss -timeout=300m
--- PASS: TestAccAlicloudEssScalingconfigurationsDataSource (76.42s)
--- PASS: TestAccAlicloudEssScalinggroupsDataSource (62.44s)
--- PASS: TestAccAlicloudEssScalingrulesDataSource (103.34s)
=== RUN   TestAccAlicloudEssAlarmBasic
--- PASS: TestAccAlicloudEssAlarmBasic (168.94s)
=== RUN   TestAccAlicloudEssAlarmMulti
--- PASS: TestAccAlicloudEssAlarmMulti (65.92s)
=== RUN   TestAccAlicloudEssAttachment_update
--- PASS: TestAccAlicloudEssAttachment_update (121.00s)
=== RUN   TestAccAlicloudEssLifecycleHookBasic
--- PASS: TestAccAlicloudEssLifecycleHookBasic …
> - fix(autoscaling): fix autoscaling bugs.

- alicloud/resource_alicloud_pvtz_zone_attachment.go
- alicloud/resource_alicloud_pvtz_zone_attachment_test.go
- website/docs/r/pvtz_zone_attachment.html.markdown
> improve(pvtz_zone_attachment):make pvtz_zone_attachment support different region vpc

- CHANGELOG.md
- alicloud/resource_alicloud_db_backup_policy.go
- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_db_instance_test.go
- alicloud/service_alicloud_rds.go
- website/docs/r/db_instance.html.markdown
> improve(db_instance): add new field auto_upgrade_minor_version to set minor version

- alicloud/resource_alicloud_ess_scalinggroup.go
--- PASS: TestAccAlicloudEssScalingGroup_basic (87.27s)
=== RUN   TestAccAlicloudEssScalingGroup_costoptimized
--- PASS: TestAccAlicloudEssScalingGroup_costoptimized (63.15s)
--- PASS: TestAccAlicloudEssScalingGroup_vpc (82.10s)
--- PASS: TestAccAlicloudEssScalingGroup_slb (120.13s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     352.708s
> fix(ess): modify the type of  from Set to List.

- alicloud/resource_alicloud_mongodb_instance.go
- website/docs/r/mongodb_instance.html.markdown
> improve(mongodb): feature mongodb support postpaid to prepaid

- website/docs/r/cs_managed_kubernetes.html.markdown
> fix managedkubernetes demo

- CHANGELOG.md
- alicloud/connectivity/client.go
- alicloud/resource_alicloud_pvtz_zone_attachment.go
- alicloud/resource_alicloud_pvtz_zone_attachment_test.go
- website/docs/r/pvtz_zone_attachment.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudPvtzZoneAttachment -timeout=1200m
=== RUN   TestAccAlicloudPvtzZoneAttachment_basic
--- PASS: TestAccAlicloudPvtzZoneAttachment_basic (92.40s)
=== RUN   TestAccAlicloudPvtzZoneAttachment_multi
--- PASS: TestAccAlicloudPvtzZoneAttachment_multi (35.37s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     127.884s
```
> fix(pvtz_attachment): fix vpc_ids diff error

- alicloud/diff_suppress_funcs.go
- alicloud/provider.go
- alicloud/resource_alicloud_sag_dnat_entry.go
- alicloud/resource_alicloud_sag_dnat_entry_test.go
- examples/sag_dnat_entry/main.tf
- examples/sag_dnat_entry/versions.tf
- website/alicloud.erb
- website/docs/r/sag_dnat_entry.html.markdown
> add sag_dnat

- website/docs/r/sag_dnat_entry.html.markdown
> improve(sag_dnat_entry): modify docs "add subcategory"

- alicloud/provider.go
- alicloud/resource_alicloud_cloud_connect_network_grant.go
- alicloud/resource_alicloud_cloud_connect_network_grant_test.go
- examples/cloud_connect_network_grant/main.tf
- examples/cloud_connect_network_grant/versions.tf
- website/alicloud.erb
- website/docs/r/cloud_connect_network_grant.html.markdown
improve(cloud_connect_network_grant): add cloud_connect_network_grant
> improve(cloud_connect_network_grant): add cloud_connect_network_grant

- alicloud/provider.go
- alicloud/resource_alicloud_cloud_connect_network_attachment.go
- alicloud/resource_alicloud_cloud_connect_network_attachment_test.go
- alicloud/service_alicloud_sag.go
- examples/cloud_connect_network_attachment/main.tf
- examples/cloud_connect_network_attachment/versions.tf
- website/alicloud.erb
- website/docs/r/cloud_connect_network_attachment.html.markdown
improve(cloud_connect_network_attachment): add resource
> improve(cloud_connect_network_attachment): add resource

- alicloud/resource_alicloud_pvtz_zone_record.go
fixes #1935
This PR allows setting SRV dns records in `alicloud_pvtz_zone_record`.
> fix(pvtz_zone_record): allow SRV records

- alicloud/data_source_alicloud_db_instance_classes_test.go
- alicloud/data_source_alicloud_instance_types_test.go
- alicloud/data_source_alicloud_kvstore_instance_classes_test.go
> improve(datasources): remove sorted_by testcase results from some internal limitation

- alicloud/resource_alicloud_alikafka_instance_test.go
Fix bug in when doing alikafka instance multi acc test.
> Fix bug in when doing alikafka instance multi acc test.

- alicloud/diff_suppress_funcs.go
- alicloud/provider.go
- alicloud/provider_test.go
- alicloud/resource_alicloud_sag_client_user.go
- alicloud/resource_alicloud_sag_client_user_test.go
- examples/sag_client_user/main.tf
- examples/sag_client_user/versions.tf
- website/alicloud.erb
- website/docs/r/sag_client_user.html.markdown
> improve(sag_client_user): add sag_client_user

- alicloud/resource_alicloud_slb_server_group.go
> improve(slb_server_group): set servers to computed and avoid diff when using ess_scaling_vserver_group

- alicloud/provider.go
- alicloud/provider_test.go
- alicloud/resource_alicloud_reserved_instance.go
- alicloud/resource_alicloud_reserved_instance_test.go
- alicloud/service_alicloud_ecs.go
- website/alicloud.erb
- website/docs/r/reserved_instance.html.markdown
add resource purchase_reserved_instances_offering
> add resource purchase_reserved_instances_offering

- website/docs/r/mongodb_instance.html.markdown
documenting change from https://github.com/terraform-providers/terraform-provider-alicloud/pull/1929
> documenting the replica_set_name attribute in mongodb

- alicloud/provider.go
- alicloud/resource_alicloud_polardb_backup_policy.go
- alicloud/resource_alicloud_polardb_backup_policy_test.go
- website/alicloud.erb
- website/docs/r/polardb_backup_policy.html.markdown
> improve(polardb): feature polardb support backup policy

- alicloud/provider.go
- alicloud/resource_alicloud_polardb_database.go
- alicloud/resource_alicloud_polardb_database_test.go
- website/alicloud.erb
- website/docs/r/polardb_database.html.markdown
> improve(polardb): feature polardb support database

- alicloud/provider.go
- alicloud/resource_alicloud_kvstore_account.go
- alicloud/resource_alicloud_kvstore_account_test.go
- alicloud/service_alicloud_kvstore.go
- examples/kvstore/main.tf
- website/alicloud.erb
- website/docs/r/kvstore_account.html.markdown
feature kvstore support account creation
> create account for kvstore

- alicloud/common.go
- alicloud/data_source_alicloud_key_pairs.go
- alicloud/data_source_alicloud_key_pairs_test.go
- alicloud/data_source_alicloud_slb_acls.go
- alicloud/data_source_alicloud_slb_acls_test.go
- alicloud/data_source_alicloud_slb_ca_certificates.go
- alicloud/data_source_alicloud_slb_ca_certificates_test.go
- alicloud/data_source_alicloud_slb_server_certificates.go
- alicloud/data_source_alicloud_slb_server_certificates_test.go
- alicloud/resource_alicloud_key_pair.go
- alicloud/resource_alicloud_key_pair_test.go
- alicloud/resource_alicloud_slb_acl.go
- alicloud/resource_alicloud_slb_acl_test.go
- alicloud/resource_alicloud_slb_ca_certificate.go
- alicloud/resource_alicloud_slb_ca_certificate_test.go
- alicloud/resource_alicloud_slb_server_certificate.go
- alicloud/resource_alicloud_slb_server_certificate_test.go
- alicloud/service_alicloud_slb.go
- alicloud/tags.go
- website/docs/d/key_pairs.html.markdown
- website/docs/d/mongodb_instances.html.markdown
- website/docs/d/slb_acls.html.markdown
- website/docs/d/slb_ca_certificates.html.markdown
- website/docs/d/slb_server_certificates.html.markdown
- website/docs/r/key_pair.html.markdown
- website/docs/r/mongodb_instance.html.markdown
- website/docs/r/slb_acl.html.markdown
- website/docs/r/slb_ca_certificate.html.markdown
- website/docs/r/slb_server_certificate.html.markdown
> add missing tags for acl, keypair  and so n

- alicloud/provider.go
- alicloud/resource_alicloud_copy_images.go
- alicloud/resource_alicloud_copy_images_test.go
- alicloud/resource_alicloud_image.go
- alicloud/resource_alicloud_image_test.go
- alicloud/service_alicloud_ecs.go
- website/alicloud.erb
- website/docs/r/copy_image.html.markdown
- website/docs/r/image.html.markdown
> add copy image

- alicloud/resource_alicloud_kvstore_account.go
- alicloud/resource_alicloud_kvstore_account_test.go
- website/docs/r/kvstore_account.html.markdown
> add argument 'account_privilege' for kvstore account

- alicloud/provider.go
- alicloud/resource_alicloud_polardb_account.go
- alicloud/resource_alicloud_polardb_account_test.go
- website/alicloud.erb
- website/docs/r/polardb_account.html.markdown
- website/docs/r/polardb_backup_policy.html.markdown
- website/docs/r/polardb_cluster.html.markdown
- website/docs/r/polardb_database.html.markdown
> improve(polardb): feature polardb support account

- alicloud/provider.go
- alicloud/resource_alicloud_polardb_account_privilege.go
- alicloud/resource_alicloud_polardb_account_privilege_test.go
- website/alicloud.erb
- website/docs/r/polardb_account_privilege.html.markdown
> improve(polardb): feature polardb support account privilege

- alicloud/resource_alicloud_kvstore_account.go
- website/docs/r/kvstore_account.html.markdown
> remove type 'Super' for kvstore

- alicloud/data_source_alicloud_yundun_bastionhost_instances.go
- alicloud/data_source_alicloud_yundun_bastionhost_instances_test.go
- alicloud/data_source_alicloud_yundun_dbaudit_instances.go
- alicloud/data_source_alicloud_yundun_dbaudit_instances_test.go
- alicloud/resource_alicloud_yundun_bastionhost_instance.go
- alicloud/resource_alicloud_yundun_bastionhost_instance_test.go
- alicloud/resource_alicloud_yundun_dbaudit_instance.go
- alicloud/resource_alicloud_yundun_dbaudit_instance_test.go
- alicloud/service_alicloud_yundun_bastionhost.go
- alicloud/service_alicloud_yundun_dbaudit.go
- website/docs/d/yundun_bastionhost_instances.html.markdown
- website/docs/d/yundun_dbaudit_instances.html.markdown
- website/docs/r/yundun_bastionhost_instance.html.markdown
- website/docs/r/yundun_dbaudit_instance.html.markdown
feat(alicloud/yundun_bastionhost): Cloud Bastionhost resource supports period
feat(alicloud/yundun_dbaudit): Add support for Cloud Bastionhost
feat(alicloud/yundun_dbaudit): Cloud DBAudit resource supports period
fix(alicloud/docs/yundun_bastionhost): fix documents bug
> feat(alicloud/yundun_bastionhost): Add support for Cloud Bastionhost

- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_db_backup_policy.go
- alicloud/resource_alicloud_db_backup_policy_test.go
- alicloud/service_alicloud_rds.go
- website/docs/r/db_backup_policy.html.markdown
> improve(rds): fix rds resource alicloud_db_backup_policy`s log_backup bug

- alicloud/data_source_alicloud_slb_acls.go
- alicloud/data_source_alicloud_slb_acls_test.go
- alicloud/resource_alicloud_cdn_domain_new.go
- alicloud/resource_alicloud_cdn_domain_new_test.go
- alicloud/resource_alicloud_slb_acl.go
- alicloud/resource_alicloud_slb_acl_test.go
- website/docs/d/slb_acls.html.markdown
- website/docs/r/cdn_domain_new.html.markdown
- website/docs/r/slb_acl.html.markdown
> add resource group id

- alicloud/data_source_alicloud_polardb_endpoints.go
- alicloud/data_source_alicloud_polardb_endpoints_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_polardb_endpoint_address.go
- alicloud/resource_alicloud_polardb_endpoint_address_test.go
- alicloud/service_alicloud_polardb.go
- website/alicloud.erb
- website/docs/d/polardb_endpoints.html.markdown
- website/docs/r/polardb_endpoint_address.html.markdown
> improve(polardb): feature polardb support connection

- alicloud/resource_alicloud_alikafka_sasl_acl.go
- alicloud/resource_alicloud_alikafka_sasl_user.go
- website/docs/r/alikafka_sasl_acl.html.markdown
- website/docs/r/alikafka_sasl_user.html.markdown
Implement update method for sasl user
> Implement update method for sasl user

- website/docs/d/ess_scaling_configurations.html.markdown
- website/docs/d/ess_scaling_groups.html.markdown
- website/docs/d/ess_scaling_rules.html.markdown
ess-rules/groups/configrution three markdown files different with codes
> ess-rules/groups/configrution three markdown files different with codes

- alicloud/resource_alicloud_slb_server_certificate.go
update server_certificaimprove(slb): update slb_server_certificate
> improve(slb): update slb_server_certificate

- CHANGELOG.md
- alicloud/resource_alicloud_db_instance_test.go
- alicloud/resource_alicloud_security_group.go
> fix(security_group): fix enterprise sg does not support inner access policy from issue #1961 @yongzhang

- alicloud/data_source_alicloud_instances.go
- alicloud/data_source_alicloud_instances_test.go
> improve(instances): improve its efficiency when fetching its disk mappings

- CHANGELOG.md
- alicloud/resource_alicloud_pvtz_zone.go
- alicloud/resource_alicloud_pvtz_zone_test.go
- website/docs/r/pvtz_zone.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudPvtzZone_basic -timeout=120m
=== RUN   TestAccAlicloudPvtzZone_basic
--- PASS: TestAccAlicloudPvtzZone_basic (9.59s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     9.686s
````
> improve(pvtz): supports proxy_pattern, user_client_ip and lang

- CHANGELOG.md
- alicloud/data_source_alicloud_instance_types.go
- website/docs/d/instance_types.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudInstanceTypesDataSource_basic -timeout=120m 
--- PASS: TestAccAlicloudInstanceTypesDataSource_basic (4.00s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     4.086s
```
> fix(instance_types): resolve a bug results from the filed spelling error

- website/docs/r/cen_instance.html.markdown
fix:cen_instance.html.markdown(modify docs of name & description)
> fix:cen_instance.html.markdown(modify docs of name & description)

- alicloud/data_source_alicloud_kvstore_instance_classes.go
- alicloud/data_source_alicloud_kvstore_instance_classes_test.go
- alicloud/data_source_alicloud_kvstore_instance_engines.go
- alicloud/data_source_alicloud_kvstore_instance_engines_test.go
- website/docs/d/kvstore_instance_classes.html.markdown
- website/docs/d/kvstore_instance_engines.html.markdown
> improve(kvstore_instance_classes): add validateFunc for engine

- website/docs/r/cen_instance_grant.html.markdown
modify:cen_instance_grant.html.markdown("alicloud_cen_instance_grant.foo")
> modify:cen_instance_grant.html.markdown("alicloud_cen_instance_grant.foo")

- alicloud/connectivity/regions.go
- alicloud/resource_alicloud_slb_listener.go
- alicloud/resource_alicloud_slb_listener_test.go
- website/docs/r/slb_listener.html.markdown
improve(slb) update slb_listener add health_check_method
> improve(slb) update slb_listener add health_check_method

- alicloud/resource_alicloud_instance.go
- alicloud/tags.go
> fix(instance): resolve the untag bug

- alicloud/provider.go
Fixes https://github.com/terraform-providers/terraform-provider-alicloud/issues/2166
This fix lets you overwrite sts endpoint by setting the domain of the STS client accordingly.
> fixed regional sts endpoint

- alicloud/resource_alicloud_snat_entry_test.go
update snat-entry testcase to avoid whitelist problem when ecs not in vswitch
> update SnatEntry test case

- alicloud/resource_alicloud_polardb_cluster.go
- alicloud/resource_alicloud_polardb_cluster_test.go
- website/docs/r/polardb_cluster.html.markdown
> improve(polardb): fix update polardb cluster db_node_class will delete instance

- alicloud/extension_cms.go
- alicloud/provider.go
- alicloud/resource_alicloud_cms_site_monitor.go
- alicloud/resource_alicloud_cms_site_monitor_test.go
- alicloud/service_alicloud_cms.go
- go.sum
- website/docs/r/cms_sitemonitor.markdown 
PLease note that ErrorCodeMaximum is not documented but a valid option for SiteMonitor.
Also please note that this requires Go SDK version >=  v1.60.384
The change is already implemented in PR https://github.com/terraform-providers/terraform-provider-alicloud/pull/2190
> added new resoure provider for cms sitemonitor

- alicloud/resource_alicloud_mongodb_instance.go
- alicloud/resource_alicloud_mongodb_instance_test.go
- alicloud/service_alicloud_mongodb.go
- website/docs/r/mongodb_instance.html.markdown
> mongodb support TDE

- alicloud/resource_alicloud_cen_instance_attachment.go
fix(cen):modify resource_alicloud_cen_instance_attachment
> fix(cen):modify resource_alicloud_cen_instance_attachment

- alicloud/data_source_alicloud_adb_clusters.go
- alicloud/data_source_alicloud_adb_clusters_test.go
- alicloud/resource_alicloud_adb_account_test.go
- alicloud/resource_alicloud_adb_backup_policy_test.go
- alicloud/resource_alicloud_adb_cluster.go
- alicloud/resource_alicloud_adb_cluster_test.go
- alicloud/service_alicloud_adb.go
- alicloud/service_alicloud_common_test.go
- examples/adb/main.tf
- website/docs/r/adb_account.html.markdown
- website/docs/r/adb_backup_policy.html.markdown
- website/docs/r/adb_cluster.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudAdb -timeout=1200m
=== RUN   TestAccAlicloudAdbClustersDataSource
--- PASS: TestAccAlicloudAdbClustersDataSource (2165.13s)
=== RUN   TestAccAlicloudAdbAccount_update_forSuper
--- PASS: TestAccAlicloudAdbAccount_update_forSuper (1357.13s)
=== RUN   TestAccAlicloudAdbBackupPolicy
--- PASS: TestAccAlicloudAdbBackupPolicy (1463.14s)
=== RUN   TestAccAlicloudAdbCluster
--- PASS: TestAccAlicloudAdbCluster (1802.16s)
=== RUN   TestAccAlicloudAdbClusterMulti
--- PASS: TestAccAlicloudAdbClusterMulti (1519.21s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	8306.833s
> fix adb ci bug

- alicloud/data_source_alicloud_polardb_zones.go
- alicloud/data_source_alicloud_zones.go
> fix polardb data source zones

- alicloud/resource_alicloud_mongodb_sharding_instance.go
- alicloud/resource_alicloud_mongodb_sharding_instance_test.go
- website/docs/r/mongodb_sharding_instance.html.markdown
> add security group id and TDE for mongodb sharding

- alicloud/resource_alicloud_ess_scalinggroup.go
- alicloud/resource_alicloud_ess_scalinggroup_test.go
- website/docs/r/ess_scaling_group.html.markdown
support parameter DesiredCapacity
> support parameter DesiredCapacity

- alicloud/resource_alicloud_cen_instance_grant.go
fix(cen):modify resource_alicloud_cen_instance_grant
> fix(cen):modify resource_alicloud_cen_instance_grant

- alicloud/service_alicloud_cs.go
- website/docs/r/cs_managed_kubernetes.html.markdown
* change autoscaler tag from `k8s.io/cluster-autoscaler=true` to `k8s.aliyun.com`
* refactor managed kubernetes docs
> change default autoscaler tag and refactor docs of managed kubernetes

- alicloud/resource_alicloud_db_instance.go
> fix create rds instance bug

- alicloud/resource_alicloud_db_instance.go
- alicloud/service_alicloud_rds.go
resource_alicloud_db_instance fix
> fix(db_instance): resolve deleting db instance bug

- alicloud/resource_alicloud_alikafka_consumer_group.go
- alicloud/resource_alicloud_alikafka_instance.go
- alicloud/resource_alicloud_alikafka_sasl_acl.go
- alicloud/resource_alicloud_alikafka_sasl_user.go
- alicloud/service_alicloud_alikafka.go
optimize retryable request for alikafka
> optimize retryable request for alikafka

- alicloud/data_source_alicloud_instance_types.go
- alicloud/data_source_alicloud_zones.go
- alicloud/resource_alicloud_cs_swarm.go
- alicloud/resource_alicloud_ess_scalingconfiguration.go
- alicloud/resource_alicloud_instance.go
- alicloud/service_alicloud_ecs.go
> remove checking instance type before creating ecs instance ang ess configuration

- alicloud/provider.go
- alicloud/resource_alicloud_polardb_endpoint.go
- alicloud/resource_alicloud_polardb_endpoint_test.go
- alicloud/service_alicloud_polardb.go
- website/alicloud.erb
- website/docs/r/polardb_endpoint.html.markdown
> add resource polardb endpoint

- alicloud/service_alicloud_alikafka.go
> Fix assign variable bug

- alicloud/common.go
- alicloud/service_alicloud_emr.go
> update emr tag resourceType from instance to cluster

- alicloud/resource_alicloud_adb_account.go
- alicloud/resource_alicloud_adb_account_test.go
- website/docs/d/adb_clusters.html.markdown
- website/docs/r/adb_account.html.markdown
- website/docs/r/adb_backup_policy.html.markdown
- website/docs/r/adb_cluster.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudAdb -timeout=1200m
=== RUN   TestAccAlicloudAdbClustersDataSource
--- PASS: TestAccAlicloudAdbClustersDataSource (1331.92s)
=== RUN   TestAccAlicloudAdbAccount_update_forSuper
--- PASS: TestAccAlicloudAdbAccount_update_forSuper (1348.93s)
=== RUN   TestAccAlicloudAdbBackupPolicy
--- PASS: TestAccAlicloudAdbBackupPolicy (1304.07s)
=== RUN   TestAccAlicloudAdbCluster
--- PASS: TestAccAlicloudAdbCluster (3838.30s)
=== RUN   TestAccAlicloudAdbClusterMulti
--- PASS: TestAccAlicloudAdbClusterMulti (1450.65s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	9273.946s
> fix adb account & documents bug

- alicloud/data_source_alicloud_polardb_node_classes.go
- alicloud/data_source_alicloud_polardb_node_classes_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/polardb_node_classes.html.markdown
> add new data source polardb instance classes

- alicloud/resource_alicloud_adb_backup_policy.go
- alicloud/resource_alicloud_adb_cluster.go
- website/docs/r/adb_backup_policy.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudAdb -timeout=1200m
=== RUN TestAccAlicloudAdbClustersDataSource
--- PASS: TestAccAlicloudAdbClustersDataSource (1331.92s)
=== RUN TestAccAlicloudAdbAccount_update_forSuper
--- PASS: TestAccAlicloudAdbAccount_update_forSuper (1348.93s)
=== RUN TestAccAlicloudAdbBackupPolicy
--- PASS: TestAccAlicloudAdbBackupPolicy (1304.07s)
=== RUN TestAccAlicloudAdbCluster
--- PASS: TestAccAlicloudAdbCluster (3838.30s)
=== RUN TestAccAlicloudAdbClusterMulti
--- PASS: TestAccAlicloudAdbClusterMulti (1450.65s)
PASS
ok github.com/terraform-providers/terraform-provider-alicloud/alicloud 9273.946s
> fix adb documents bug

- alicloud/provider.go
- alicloud/resource_alicloud_adb_connection.go
- alicloud/resource_alicloud_adb_connection_test.go
- website/alicloud.erb
- website/docs/d/adb_clusters.html.markdown
- website/docs/d/adb_zones.html.markdown
- website/docs/r/adb_account.html.markdown
- website/docs/r/adb_backup_policy.html.markdown
- website/docs/r/adb_cluster.html.markdown
- website/docs/r/adb_connection.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudAdbConnectionConfig -timeout=1200m
=== RUN   TestAccAlicloudAdbConnectionConfig
--- PASS: TestAccAlicloudAdbConnectionConfig (1341.30s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	1341.355s
> add adb connection resource

- alicloud/data_source_alicloud_adb_clusters_test.go
- alicloud/resource_alicloud_adb_account_test.go
- alicloud/resource_alicloud_adb_backup_policy_test.go
- alicloud/resource_alicloud_adb_cluster_test.go
- alicloud/resource_alicloud_adb_connection_test.go
add pre check for default VPC & vSwitch
> fix adb test

- alicloud/common.go
> Let WriteFile return write/delete errors

- alicloud/common.go
Fixes a regression introduced by #2408 and makes the function less destructive.
> Fix regression in writeToFile

- alicloud/provider.go
- alicloud/resource_alicloud_cen_route_map.go
- alicloud/resource_alicloud_cen_route_map_test.go
- alicloud/service_alicloud_cbn.go
- website/alicloud.erb
- website/docs/r/cen_route_map.html.markdown
add a new resource cen_route_map
> add a new resource cen_route_map

- website/docs/r/instance.html.markdown
> fix_markdown_slb_vpc

- website/docs/r/instance.html.markdown
> fix_markdown_instance

- alicloud/provider.go
- alicloud/resource_alicloud_cen_private_zone.go
- alicloud/resource_alicloud_cen_private_zone_test.go
- alicloud/service_alicloud_cbn.go
- website/alicloud.erb
- website/docs/r/cen_private_zone.html.markdown
add a new resource alicloud_cen_private_zone
> add a new resource alicloud_cen_private_zone

- alicloud/resource_alicloud_cs_kubernetes_autoscaler.go
Fix when the configmap has been not created before.
> fix autoscaler configmap update

- website/docs/r/key_pair_attachment.html.markdown
fix_markdown_key_pair_attachment
> fix_markdown_key_pair_attachment

- alicloud/resource_alicloud_cs_kubernetes_autoscaler.go
- alicloud/resource_alicloud_instance.go
- alicloud/tags.go
> fix_tag_validation

- alicloud/data_source_alicloud_key_pairs.go
> fix_finger_print

- alicloud/resource_alicloud_polardb_cluster.go
- alicloud/resource_alicloud_polardb_cluster_test.go
- website/docs/r/polardb_cluster.html.markdown
> fix polardb connection string output bug

- website/docs/r/network_interface_attachment.html.markdown
fix_markdown_alicloud_network_interface_attachment
> fix_markdown_alicloud_network_interface_attachment

- website/docs/d/instance_type_families.html.markdown
fix_markdown_instance_type_families
> fix_markdown_instance_type_families

- website/docs/d/network_interfaces.html.markdown
fix_markdown_network_interfaces
> fix_markdown_network_interfaces

- alicloud/resource_alicloud_kms_key.go
- alicloud/resource_alicloud_kms_key_test.go
- alicloud/service_alicloud_kms.go
- website/docs/r/reserved_instance.html.markdown
fix_markdown_reserved_instance
> fix_markdown_reserved_instance

- website/docs/r/disk_attachment.html.markdown
> fix_markdown_disk_attachment

- website/docs/r/image_import.html.markdown
> fix_markdown_image_import

- alicloud/resource_alicloud_elasticsearch_instance.go
- alicloud/resource_alicloud_elasticsearch_instance_test.go
- examples/elasticsearch/main.tf
- examples/elasticsearch/variables.tf
- website/docs/r/elasticsearch.html.markdown
Added new features:
Supported the data node disk encrypted.
> Added new feature of encrypting data node disk

- website/docs/r/ess_scalinggroup_vserver_groups.markdown
fix_markdown_ess_scalinggroup_vserver_groups
> fix_markdown_ess_scalinggroup_vserver_groups

- website/docs/r/ess_scaling_group.html.markdown
> fix_markdown_ess_scalinggroup

- website/docs/r/disk.html.markdown
> fix_markdown_disk

- website/docs/r/ess_scaling_configuration.html.markdown
> improve_user_experience

- alicloud/common.go
- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_elasticsearch_instance.go
- alicloud/resource_alicloud_elasticsearch_instance_test.go
- alicloud/service_alicloud_elasticsearch.go
- website/docs/r/elasticsearch.html.markdown
1. basic
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudElasticsearchInstance_basic -timeout=300m
=== RUN   TestAccAlicloudElasticsearchInstance_basic
--- PASS: TestAccAlicloudElasticsearchInstance_basic (5960.88s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	5960.987s
> improve(elasticsearch): resource support to open or close network, and modify the kibana whitelist in private network

- website/docs/r/image.html.markdown
- website/docs/r/image_copy.html.markdown
- website/docs/r/image_export.html.markdown
- website/docs/r/image_import.html.markdown
- website/docs/r/image_share_permission.html.markdown
> fix_markdown_image_s

- alicloud/resource_alicloud_cen_instance_attachment.go
- alicloud/service_alicloud_cen.go
modify cen_instance_attachment
> modify cen_instance_attachment

- alicloud/provider.go
- alicloud/provider_test.go
- alicloud/resource_alicloud_cen_vbr_health_check.go
- alicloud/resource_alicloud_cen_vbr_health_check_test.go
- alicloud/service_alicloud_cbn.go
- website/alicloud.erb
- website/docs/r/cen_vbr_health_check.html.markdown
add a new resource alicloud_cen_vbr_health_check
> add a new resource alicloud_cen_vbr_health_check

- alicloud/data_source_alicloud_cassandra_clusters.go
- alicloud/data_source_alicloud_cassandra_clusters_test.go
- alicloud/data_source_alicloud_cassandra_data_centers.go
- alicloud/data_source_alicloud_cassandra_data_centers_test.go
- alicloud/data_source_alicloud_cassandra_zones.go
- alicloud/data_source_alicloud_cassandra_zones_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/cassandra_clusters.html.markdown
- website/docs/d/cassandra_data_centers.html.markdown
- website/docs/d/cassandra_zones.html.markdown
> cassandra data source

- alicloud/resource_alicloud_launch_template.go
- website/docs/r/launch_template.html.markdown
> fix_markdown_launch_template

- website/docs/r/ess_notification.html.markdown
> fix_markdown_ess_notification

- alicloud/resource_alicloud_disk.go
- alicloud/resource_alicloud_disk_test.go
- website/docs/r/disk.html.markdown
> fix_kms_ecs_disk

- alicloud/resource_alicloud_ess_scheduled_task.go
- alicloud/resource_alicloud_ess_scheduled_task_test.go
- website/docs/r/ess_scheduled_task.html.markdown
> fix_ess_scheduled_task

- alicloud/resource_alicloud_instance.go
- alicloud/resource_alicloud_instance_test.go
- website/docs/r/instance.html.markdown
> fix_instance

- website/docs/r/ess_scheduled_task.html.markdown
fix_markdown_ess_scheduled_task
> fix_markdown_ess_scheduled_task

- alicloud/resource_alicloud_common_bandwidth_package.go
- website/docs/r/common_bandwidth_package.html.markdown
> add isp support to cbwp

- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_drds_instances.go
- alicloud/data_source_alicloud_drds_instances_test.go
- alicloud/resource_alicloud_drds_instance.go
- alicloud/resource_alicloud_drds_instance_test.go
- alicloud/service_alicloud_drds.go
- website/docs/d/drds_instances.html.markdown
- website/docs/r/drds_instance.html.markdown
> drds support internation

- alicloud/data_source_alicloud_nat_gateways.go
- alicloud/resource_alicloud_ess_scalingconfiguration.go
- alicloud/resource_alicloud_ess_scalingconfiguration_test.go
- alicloud/service_alicloud_ess.go
- website/docs/r/ess_scaling_configuration.html.markdown
> Fix ess kms disk

- alicloud/connectivity/client.go
- alicloud/connectivity/endpoint.go
- alicloud/data_source_alicloud_nat_gateways.go
- alicloud/resource_alicloud_nas_access_group.go
- alicloud/resource_alicloud_nas_access_group_test.go
- alicloud/service_alicloud_nas.go
- website/docs/r/nas_access_group.html.markdown
* support new argument for "file_system_type"
* compatible with old argument
> upgrade resource of Nas AccessGroup

- alicloud/provider.go
- alicloud/resource_alicloud_edas_k8s_cluster.go
- alicloud/resource_alicloud_edas_k8s_cluster_test.go
- alicloud/service_alicloud_edas.go
- website/alicloud.erb
- website/docs/r/edas_k8s_cluster.html.markdown
Add support for edas k8s cluster.
> edas k8s cluster

- alicloud/extension_slb.go
- alicloud/resource_alicloud_slb_backend_server.go
- alicloud/resource_alicloud_slb_backend_server_test.go
- examples/slb-backend-server/main.tf
- website/docs/r/slb_backend_server.html.markdown
improve(slb) update slb_backend_server add parameter server_ip
> improve(slb) update slb_backend_server add parameter server_ip

- website/docs/r/snapshot_policy.html.markdown
> fix_markdown_snapshot_policy

- website/docs/r/auto_provisioning_group.html.markdown
fix_markdown_auto_provisioning_group
> fix_markdown_auto_provisioning_group

- website/docs/d/slb_backend_servers.html.markdown
improve(slb) update doc alicloud_slb_backend_servers
> improve(slb) update doc alicloud_slb_backend_servers

- website/docs/d/security_group_rules.html.markdown
fix_markdown_security_group_rules
> fix_markdown_security_group_rules

- alicloud/resource_alicloud_adb_cluster.go
- alicloud/resource_alicloud_adb_cluster_test.go
- website/docs/r/adb_cluster.html.markdown
> ADB MySQL output output connection string after creation

- alicloud/service_alicloud_vpc.go
update: fix dnat query errror by only use forwardTableId
> update: fix dnat query errror by only use forwardTableId

- alicloud/data_source_alicloud_waf_domains.go
- alicloud/data_source_alicloud_waf_domains_test.go
- alicloud/data_source_alicloud_waf_instances.go
- alicloud/data_source_alicloud_waf_instances_test.go
- alicloud/resource_alicloud_dms_enterprise_instance_test.go
- alicloud/resource_alicloud_waf_domain.go
- alicloud/resource_alicloud_waf_domain_test.go
- alicloud/resource_alicloud_waf_instance.go
- alicloud/resource_alicloud_waf_instance_test.go
- alicloud/service_alicloud_waf_openapi.go
- website/docs/d/waf_domains.html.markdown
- website/docs/d/waf_instances.html.markdown
- website/docs/r/waf_domain.html.markdown
* upgrade datasource of domain
> waf domain support setting resource_group_id and more attributes

- alicloud/resource_alicloud_polardb_cluster.go
- alicloud/resource_alicloud_polardb_cluster_test.go
- website/docs/r/polardb_cluster.html.markdown
> PolarDB support add or remove read-only nodes

- alicloud/resource_alicloud_disk.go
- alicloud/resource_alicloud_disk_test.go
- website/docs/r/disk.html.markdown
> resource alicloud_disk supports setting performance_level

- alicloud/data_source_alicloud_images.go
- alicloud/data_source_alicloud_images_test.go
- website/docs/d/images.html.markdown
> improve(alicloud_images): supports more filters

- website/docs/r/ess_scaling_rule.html.markdown
> improve resource alicloud_ess_scaling_rule docs

- alicloud/resource_alicloud_polardb_cluster.go
- alicloud/resource_alicloud_polardb_cluster_test.go
- website/docs/r/polardb_cluster.html.markdown
> PolarDB cluster support setting resource_group_id

- alicloud/resource_alicloud_db_instance.go
> fix: db instance delay set is 30s

- alicloud/data_source_alicloud_elasticsearch_instances_test.go
- alicloud/service_alicloud_elasticsearch.go
- alicloud/tags.go
* filter alicloud specific tag for elasticsearch
> fix elasticsearch_instance return redundant tags issue

- alicloud/data_source_alicloud_cen_instance_attachments.go
- alicloud/data_source_alicloud_cen_instance_attachments_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cen_instance_attachment.go
- alicloud/resource_alicloud_cen_instance_attachment_test.go
- alicloud/service_alicloud_cbn.go
- website/alicloud.erb
- website/docs/d/cen_instance_attachments.html.markdown
- website/docs/r/cen_instance_attachment.html.markdown
* support datasource for CEN Instance Attachment
> upgrade resource alicloud_cen_instance_attachment and add its datasource 

- alicloud/resource_alicloud_auto_provisioning_group.go
- alicloud/service_alicloud_ecs.go
> fix_auto_provisioning_group

- alicloud/resource_alicloud_oss_bucket_object_test.go
- alicloud/resource_alicloud_ram_access_key.go
- alicloud/resource_alicloud_ram_access_key_test.go
- website/docs/r/ram_access_key.html.markdown
> feature(alicloud_ram_access_key): support outputting secret when pgp_key is not set

- alicloud/resource_alicloud_log_dashboard.go
**What it does**
- implement DiffSuppressFunc to compare chart list semantically
- JSON fields are unordered after marshaling, we cann't compare the raw string
- dashboard_name and char_list fields must be passed to the UPDATE API every time even if they are not changed
- if we omit dashboard_name if it's not changed, it will be updated to dashboard id
- chart_list is required field (the update request will fail)
> bugfix: implement DiffSuppressFunc for chart list of log dashboard and pass required fields on update

- alicloud/resource_alicloud_cs_kubernetes_node_pool.go
node pools don't support resource group
> remove resource_group_id from resource cs_kubernetes_node_pool

- alicloud/data_source_alicloud_kvstore_instances.go
- alicloud/data_source_alicloud_kvstore_instances_test.go
- alicloud/resource_alicloud_kvstore_instance.go
- alicloud/resource_alicloud_kvstore_instance_test.go
- alicloud/service_alicloud_r_kvstore.go
- website/docs/d/kvstore_instances.html.markdown
- website/docs/r/kvstore_instance.html.markdown
> Support multiple security_group_id and Set connection_domain as output param

- alicloud/resource_alicloud_ess_scalinggroup.go
- alicloud/resource_alicloud_ess_scalinggroup_test.go
- website/docs/r/ess_scaling_group.html.markdown
fix_scalingGroupDeletionProtection
> fix_scalingGroupDeletionProtection

- alicloud/data_source_alicloud_adb_clusters.go
- alicloud/data_source_alicloud_adb_clusters_test.go
- alicloud/resource_alicloud_adb_connection.go
- website/docs/d/adb_clusters.html.markdown
- website/docs/r/adb_connection.html.markdown
> Resource alicloud_adb_clusters add optional paramter: status and improve validation of resource alicloud_adb_connection's parameter connection_prefix

- alicloud/resource_alicloud_polardb_endpoint_address.go
- website/docs/d/polardb_node_classes.html.markdown
- website/docs/r/polardb_database.html.markdown
- website/docs/r/polardb_endpoint_address.html.markdown
> improve validation of resource alicloud_polardb_endpoint_address's parameter connection_prefix

- alicloud/service_alicloud_log.go
> Increase sls retry type

- alicloud/resource_alicloud_kvstore_instance.go
> resource/alicloud_kvstore_instance: Add constant auto_pay for kvstore api ModifyInstanceSpec

- alicloud/resource_alicloud_db_backup_policy_test.go
- alicloud/service_alicloud_common_test.go
> resource/alicloud_db_instance: Improve its testcase by adding timeouts for vswitch

- alicloud/resource_alicloud_elasticsearch_instance.go
- website/docs/r/elasticsearch.html.markdown
> resource/alicloud_elasticsearch_instance: fix schema details for 'description' and 'zone_count'.

- alicloud/resource_alicloud_db_readonly_instance.go
- website/docs/r/db_readonly_instance.html.markdown
> resource/alicloud_readonly_instance: Enlarging the createing timeout to 60min

- alicloud/resource_alicloud_db_readwrite_splitting_connection.go
- alicloud/service_alicloud_rds.go
find bug when import  rds_db_readwrite_splitting_connection
after fixed:
result of Acceptance Test:
> fix:get db readwrite splitting connection

- alicloud/resource_alicloud_elasticsearch_instance.go
Fixed bug of converting charge_tyep to Prepaid
> Fixed bug of converting charge_tyep to Prepaid

- alicloud/data_source_alicloud_kvstore_zones.go
- alicloud/resource_alicloud_kvstore_instance.go
- alicloud/resource_alicloud_kvstore_instance_test.go
- website/docs/r/kvstore_instance.html.markdown
> resource/alicloud_kvstore_instance: Support modify private connection string

- alicloud/resource_alicloud_mongodb_sharding_instance.go
- alicloud/resource_alicloud_mongodb_sharding_instance_test.go
> resource/mongodb_sharding_instance: add tags argument

- alicloud/resource_alicloud_hbase_instance.go
- alicloud/resource_alicloud_hbase_instance_test.go
- alicloud/service_alicloud_hbase.go
- examples/hbase/main.tf
- examples/hbase/variables.tf
- vendor/modules.txt
- website/docs/d/hbase_instances.html.markdown
- website/docs/r/hbase_instance.html.markdown
hbase/hbaseue
1. ip white/ security group
2. modify instnace type
3. conn addrs
4. account/password
> resource/alicloud_hbase_instance: supports more resource attributes

- alicloud/resource_alicloud_ess_scalinggroup_vserver_groups.go
如果想要伸缩组绑定一个同时创建的LB的虚拟服务器组且不要默认服务器组，在alicloud_ess_scaling_group中不指定loadbalancer_ids只在alicloud_ess_scalinggroup_vserver_groups中关联伸缩组ID和负载均衡ID。则vgroup并不会等待LB的状态，则会在apply的时候报错。现增加了一个与alicloud_ess_scaling_group中类似的等待LB状态激活。
> make sure LB is active before creating vgroups

- alicloud/resource_alicloud_instance.go
> resource/alicloud_instance: fix the period diff error when auto_renew is true

- alicloud/resource_alicloud_kvstore_instance.go
- website/docs/r/kvstore_instance.html.markdown
…e for the update of param private_connection_prefix.
>  resource/alicloud_kvstore_instance: Add a restriction !d.IsNewResource for the update of param private_connection_prefix.

- alicloud/resource_alicloud_hbase_instance.go
- website/docs/r/hbase_instance.html.markdown
- core_disk_type -> Optional
- update disk size delay 2 min
> resource/alicloud_hbase_instance: change core_disk_instance to optional

- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_managed_kubernetes.go
fix:
- v1.103.2 upgrade error
- connections return error
> BugFix: v1.103.2 upgrade error, connections return error

- alicloud/data_source_alicloud_hbase_instances_test.go
- alicloud/resource_alicloud_hbase_instance.go
- alicloud/resource_alicloud_hbase_instance_test.go
- examples/hbase/main.tf
- examples/hbase/variables.tf
- website/docs/r/hbase_instance.html.markdown
1、support cloud_essd_pl1
2、support PostPaid -> PrePaid
3、immediate_delete_flag
4、fix duration=12
> resource/alicloud_hbase_cluster: support new field immediate_delete_flag and cloud_essd

- website/docs/r/elasticsearch.html.markdown
> Modify the Supported value of the  attribute in the alicloud_elasticsearch_instance.

- alicloud/resource_alicloud_instance.go
fix ecs disk performance tf plan bug。
#3135
> resource/alicloud_instance: fix ecs disk performance tf plan bug

- alicloud/data_source_alicloud_resource_manager_shared_resources.go
- alicloud/data_source_alicloud_resource_manager_shared_resources_test.go
- alicloud/data_source_alicloud_resource_manager_shared_targets.go
- alicloud/data_source_alicloud_resource_manager_shared_targets_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_resource_manager_shared_resource.go
- alicloud/resource_alicloud_resource_manager_shared_resource_test.go
- alicloud/resource_alicloud_resource_manager_shared_target.go
- alicloud/resource_alicloud_resource_manager_shared_target_test.go
- alicloud/service_alicloud_resourcesharing.go
- website/alicloud.erb
- website/docs/d/resource_manager_shared_resources.html.markdown
- website/docs/d/resource_manager_shared_targets.html.markdown
- website/docs/r/resource_manager_shared_resource.html.markdown
- website/docs/r/resource_manager_shared_target.html.markdown
2. Add resource and datasource for Resource Manager Shared Target
> Add resource and datasource for Resource Manager Shared Resource and Shared Target

- alicloud/resource_alicloud_db_account_privilege.go
> resource/alicloud_db_account_privilege: add retry for error InvalidDBNotFound

- alicloud/resource_alicloud_db_account_privilege.go
- alicloud/service_alicloud_rds.go
> resource/alicloud_db_account_privilege: fix deleting other privileges bug

- alicloud/resource_alicloud_db_instance.go
Bugfix: ModifyDBInstanceTDE add  EncryptionKey
> https://help.aliyun.com/document_detail/26256.html?spm=a2c4g.11186623.6.1791.45959e05qfIAJA
> mysql ModifyDBInstanceTDE support custom EncryptionKey

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/data_source_alicloud_tsdb_instances.go
- alicloud/data_source_alicloud_tsdb_instances_test.go
- alicloud/data_source_alicloud_tsdb_zones.go
- alicloud/data_source_alicloud_tsdb_zones_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_tsdb_instance.go
- alicloud/resource_alicloud_tsdb_instance_test.go
- alicloud/service_alicloud_hitsdb.go
- alicloud/service_alicloud_vpc.go
- website/alicloud.erb
- website/docs/d/ga_accelerators.html.markdown
- website/docs/d/ga_listeners.html.markdown
- website/docs/d/tsdb_instances.html.markdown
- website/docs/d/tsdb_zones.html.markdown
- website/docs/r/ga_accelerator.html.markdown
- website/docs/r/ga_listener.html.markdown
- website/docs/r/tsdb_instance.html.markdown
2. Add datasource for TSDB Zones
> 1. Add resource and datasource for TSDB instance 2. Add datasource for TSDB Zones

- alicloud/resource_alicloud_emr_cluster.go
- alicloud/resource_alicloud_emr_cluster_test.go
- alicloud/service_alicloud_common_test.go
- website/docs/r/emr_cluster.html.markdown
> support emr importer feature and optimized test case

- alicloud/data_source_alicloud_brain_industrial_pid_projects.go
- alicloud/data_source_alicloud_brain_industrial_pid_projects_test.go
- alicloud/resource_alicloud_brain_industrial_pid_project.go
- alicloud/resource_alicloud_brain_industrial_pid_project_test.go
- website/docs/d/brain_industrial_pid_projects.html.markdown
- website/docs/r/brain_industrial_pid_project.html.markdown
> resource/alicloud_brain_industrial_pid_project: fix name spelling mistake

- alicloud/resource_alicloud_ecs_auto_snapshot_policy_test.go
> ecs/alicloud_ecs_auto_snapshot_policy_test: Add regionId for ecs auto snap policy sweeper.

- alicloud/resource_alicloud_cs_kubernetes.go
- website/docs/r/cs_kubernetes.html.markdown
- website/docs/r/cs_kubernetes_node_pool.html.markdown
- website/docs/r/cs_managed_kubernetes.html.markdown
fix bug: create dedicated cluster crash in v1.117.0
> Bugfix: CSK create dedicated cluster crash in v1.117.0

- alicloud/data_source_alicloud_mns_service_test.go
- alicloud/data_source_alicloud_nas_file_systems_test.go
- alicloud/resource_alicloud_nas_mount_target_test.go
- ci/pipeline.yml
> testcase: Improves the mns and nas filesystem testcase by skipping needless cases

- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_fc_custom_domain_test.go
- alicloud/resource_alicloud_ros_stack_group_test.go
- ci/pipeline.yml
- ci/tasks/run.sh
…when the cluster state is failed
> resource/alicloud_cs_kubernetes: Fixes GetClusterConfig failed error when the cluster state is failed

- alicloud/service_alicloud_ecs.go
> Fix DescribeKeyPairAttachment #3338

- alicloud/resource_alicloud_mongodb_instance.go
- website/docs/r/mongodb_instance.html.markdown
> resource/alicloud_mongodb_instance: Removes the field  tde_status forceNew and supports modifying it online

- alicloud/connectivity/client.go
- ci/pipeline.yml
> resource/alicloud_eip_assocition: Enlarges the client connection timeout to avoid connecting failed

- alicloud/resource_alicloud_eip_association.go
> resource/alicloud_eip_association: Enlarges the deletion timeout to avoid deleting it failed

- alicloud/data_source_alicloud_ess_scalingrules_test.go
- alicloud/data_source_alicloud_network_interfaces_test.go
- alicloud/data_source_alicloud_route_entries_test.go
- alicloud/data_source_alicloud_slb_attachments_test.go
- alicloud/data_source_alicloud_slb_backend_servers_test.go
- alicloud/data_source_alicloud_slb_master_slave_server_groups_test.go
- alicloud/data_source_alicloud_slb_rules_test.go
- alicloud/data_source_alicloud_slb_server_groups_test.go
- alicloud/resource_alicloud_api_gateway_vpc_access_test.go
- alicloud/resource_alicloud_eip_association_test.go
- alicloud/resource_alicloud_havip_attachment_test.go
- alicloud/resource_alicloud_image_copy_test.go
- alicloud/resource_alicloud_image_export_test.go
- alicloud/resource_alicloud_image_test.go
- alicloud/resource_alicloud_instance_test.go
- alicloud/resource_alicloud_key_pair_attachment_test.go
- alicloud/resource_alicloud_launch_template_test.go
- alicloud/resource_alicloud_network_interface_attachment_test.go
- alicloud/resource_alicloud_slb_attachment_test.go
- alicloud/resource_alicloud_slb_backend_server_test.go
- alicloud/resource_alicloud_slb_master_slave_server_group_test.go
- alicloud/resource_alicloud_slb_rule_test.go
- alicloud/resource_alicloud_slb_server_group_test.go
- alicloud/service_alicloud_common_test.go
> testcase: Modify the image name_regex to ^ubuntu to avoid the needless test failed

- alicloud/errors.go
- alicloud/resource_alicloud_eip_association_test.go
- alicloud/resource_alicloud_security_group_rule_test.go
- alicloud/service_alicloud_vpc.go
- website/docs/r/disk_attachment.html.markdown
- website/docs/r/eip_association.html.markdown
> resource/alicloud_eip_association: Fixes the connection timeout when getting Eip resource

- alicloud/resource_alicloud_alikafka_instance.go
- alicloud/resource_alicloud_dms_enterprise_user_test.go
- alicloud/resource_alicloud_polardb_cluster_test.go
- alicloud/service_alicloud_alikafka.go
- website/docs/r/vpc_flow_log.html.markdown
> resource/alicloud_alikafka_instance: Fixes creating error ONS_SYSTEM_ERROR and deleting timeout error

- alicloud/data_source_alicloud_resource_manager_resource_directories.go
- alicloud/data_source_alicloud_resource_manager_resource_directories_test.go
- alicloud/resource_alicloud_resource_manager_resource_directory.go
- alicloud/resource_alicloud_resource_manager_resource_directory_test.go
- alicloud/service_alicloud_resourcemanager.go
- website/docs/d/resource_manager_resource_directories.html.markdown
- website/docs/r/resource_manager_control_policy_attachment.html.markdown
- website/docs/r/resource_manager_resource_directory.html.markdown
> resource/alicloud_resource_resource_manager_resource_directory: Supports enable or disable control policy by attribute status

- alicloud/data_source_alicloud_havips.go
- alicloud/data_source_alicloud_havips_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_havip.go
- alicloud/resource_alicloud_havip_attachment_test.go
- alicloud/resource_alicloud_havip_test.go
- alicloud/service_alicloud_vpc.go
- website/alicloud.erb
- website/docs/d/havips.html.markdown
- website/docs/r/havip.html.markdown
> resource/alicloud_havip: Adds its datasource; adds new attributes havip_name and status; upgrades its dependence sdk

- alicloud/data_source_alicloud_instance_types.go
- alicloud/resource_alicloud_dms_enterprise_user_test.go
- alicloud/service_alicloud_ecs.go
- website/docs/d/instance_types.html.markdown
> datasource/alicloud_instance_types: Adds new attribute system_disk_category to filter instance types

- alicloud/resource_alicloud_polardb_endpoint.go
- alicloud/resource_alicloud_polardb_endpoint_test.go
- alicloud/service_alicloud_polardb.go
- website/docs/r/polardb_endpoint.html.markdown
> improve alicloud_polardb_endpoint to support enable ssl and manage private, cluster endpoint

- alicloud/errors.go
> errors.go: Improves the error matching function to avoid some useless error

- alicloud/data_source_alicloud_ecs_snapshots_test.go
- alicloud/data_source_alicloud_mongodb_instances_test.go
- alicloud/resource_alicloud_disk.go
- alicloud/resource_alicloud_disk_test.go
- alicloud/resource_alicloud_mongodb_instance_test.go
- alicloud/resource_alicloud_mongodb_sharding_instance_test.go
- ci/pipeline.yml
- website/docs/r/disk.html.markdown
> resource/alicloud_disk: Sets the attribute kms_key_id to forceNew results from there is no API can update it in local place

- alicloud/resource_alicloud_polardb_endpoint.go
- alicloud/resource_alicloud_polardb_endpoint_test.go
- alicloud/service_alicloud_polardb.go
- website/docs/r/polardb_endpoint.html.markdown
> resource/alicloud_polardb_endpoint: Supports new attributes ssl_enabled  and net_type

- alicloud/data_source_alicloud_nat_gateways.go
- alicloud/data_source_alicloud_snat_entries_test.go
- alicloud/resource_alicloud_cs_kubernetes_test.go
- alicloud/resource_alicloud_nat_gateway.go
- alicloud/resource_alicloud_snat_entry_test.go
- examples/build-lnmp/main.tf
- examples/vpc-snat/main.tf
- website/docs/d/snat_entries.html.markdown
- website/docs/r/nat_gateway.html.markdown
- website/docs/r/snat.html.markdown
> resource/nat_gateway: Recovers the snat_table_ids and forward_table_ids data type to fix the format error

- alicloud/resource_alicloud_cen_bandwidth_package.go
> resource/alicloud_cen_bandwidth_package: Fixes the parsing expire time failed error which only work in PrePaid

- alicloud/data_source_alicloud_cms_alarm_contacts_test.go
- alicloud/data_source_alicloud_cms_group_metric_rules_test.go
- alicloud/resource_alicloud_cms_alarm_contact_group_test.go
- alicloud/resource_alicloud_cms_alarm_contact_test.go
- website/docs/r/cms_alarm_contact.html.markdown
> docs & testcase/alicloud_cms_alarm_contact: Improves the docs and adds limitation descriptions for attribute name; Fixes the its testcase

- alicloud/data_source_alicloud_kms_secrets_test.go
- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_instance.go
- alicloud/resource_alicloud_instance_test.go
- alicloud/resource_alicloud_mongodb_sharding_instance_test.go
> resource/alicloud_instance: Deprecates the useless attribute internet_max_bandwidth_in

- alicloud/data_source_alicloud_nas_file_systems.go
- alicloud/resource_alicloud_nas_file_system.go
- alicloud/resource_alicloud_nas_file_system_test.go
- examples/nas-file-system/main.tf
- website/docs/d/nas_file_systems.html.markdown
- website/docs/r/nas_file_system.html.markdown
> resource/alicloud_nas_file_system: Adds new attribute encrypt_type and kms_key_id to support encrypt the resource data

- alicloud/resource_alicloud_sag_qos_car.go
- alicloud/resource_alicloud_sag_qos_policy.go
> resource/alicloud_sag_qos_car & alicloud_sag_qos_policy: Fixes the error ResourceInOperating in concurrent scenario

- alicloud/resource_alicloud_instance.go
- alicloud/service_alicloud_vpc.go
- website/docs/d/nas_file_systems.html.markdown
- website/docs/r/nas_file_system.html.markdown
- website/docs/r/oss_bucket.html.markdown
> resource/alicloud_network_acl: Fixes the Throttling error when describing the resources

- alicloud/resource_alicloud_dms_enterprise_user_test.go
- alicloud/resource_alicloud_mongodb_instance.go
> resource/alicloud_mongodb_instance: Fixes the InstanceStatusInvalid error when ModifySecurityGroupConfiguration

- alicloud/service_alicloud_cbn.go
- alicloud/service_alicloud_cen.go
> resource/alicloud_cen_xxx: Adds the retry strategy to fix the connection error when fetching the resources

- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_mongodb_sharding_instance.go
- alicloud/resource_alicloud_nat_gateway.go
- alicloud/resource_alicloud_nat_gateway_test.go
- alicloud/resource_alicloud_route_entry_test.go
- ci/pipeline.yml
> resource/alicloud_nat_gateway: Fixes the specification diff bug; Fixes the period diff bug

- alicloud/connectivity/endpoint.go
> locations: Fixes fetching endpoint failed error because of network connection failed

- alicloud/data_source_alicloud_cms_service.go
- ci/pipeline.yml
> datasource/alicloud_cms_service: Adds error code Has.effect.suit to avoid needless error when repeated opening

- alicloud/data_source_alicloud_nas_file_systems.go
- alicloud/resource_alicloud_nas_file_system.go
- alicloud/resource_alicloud_nas_file_system_test.go
- examples/nas-file-system/main.tf
- website/docs/d/nas_file_systems.html.markdown
- website/docs/r/nas_file_system.html.markdown
modify file encrypt, only common file encryption  without byok
> resource/alicloud_nas_file_system: Removes the attribute kms_key_id because of it does not support all of users

- CHANGELOG.md
- alicloud/resource_alicloud_adb_connection_test.go
- website/docs/r/adb_db_cluster.html.markdown
> testcase/alicloud_adb_connection: Fixes its testcase caused by missing mode

- ci/configure
- ci/pipeline-cn.yml
- ci/sync.yml
- ci/tasks/build-package.sh
- ci/tasks/build-package.yml
- ci/tasks/run.sh
> ci: Sync the provider repo to oss to avoid network faild when running in China

- ci/auto-trigger-cn.yml
- ci/auto-trigger.yml
- ci/configure
- ci/pipeline-cn.yml
- ci/pipeline.yml
- ci/tasks/build-package.sh
- ci/tasks/ci-test.sh
- ci/tasks/ci-test.yml
- ci/tasks/run.sh
> ci: improve ci testcase by adding point-to-point test when there is a merge

- alicloud/resource_alicloud_db_instance.go
Add 'SQLServer' in condition for get role arn when 'Encryption_key' is set.
> resource/alicloud_db_instance: Supports to encrypt the disk for MSSQL

- CHANGELOG.md
- alicloud/resource_alicloud_adb_db_cluster_test.go
- alicloud/resource_alicloud_polardb_cluster.go
- alicloud/resource_alicloud_polardb_cluster_test.go
- website/docs/r/polardb_cluster.html.markdown
> resource/alicloud_polardb_cluster: Improves the attribute tde_status using standard values

- ci/tasks/ci-test.sh
>  ci: Improves the ci test in parsing func methods

- alicloud/resource_alicloud_ess_scalingconfiguration_test.go
- alicloud/resource_alicloud_resource_manager_policy_test.go
> testcase: Improves the testcase of scaling configurations and manager policy

- alicloud/resource_alicloud_ess_scalingconfiguration_test.go
- alicloud/resource_alicloud_instance_test.go
- alicloud/resource_alicloud_mse_cluster_test.go
- alicloud/resource_alicloud_ros_stack_group_test.go
- alicloud/service_alicloud_common_test.go
> testcase: Improves resource alicloud_instance testcase for attribute data_disks

- alicloud/connectivity/client.go
- alicloud/data_source_alicloud_ddoscoo_domain_resources.go
- alicloud/data_source_alicloud_ddoscoo_domain_resources_test.go
- alicloud/data_source_alicloud_ddoscoo_ports.go
- alicloud/data_source_alicloud_ddoscoo_ports_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_ddoscoo_domain_resource.go
- alicloud/resource_alicloud_ddoscoo_domain_resource_test.go
- alicloud/resource_alicloud_ddoscoo_port.go
- alicloud/resource_alicloud_ddoscoo_port_test.go
- alicloud/service_alicloud_ddoscoo.go
- website/alicloud.erb
- website/docs/d/ddoscoo_domain_resources.html.markdown
- website/docs/d/ddoscoo_ports.html.markdown
- website/docs/r/ddoscoo_domain_resource.html.markdown
- website/docs/r/ddoscoo_port.html.markdown
* alicloud_ddoscoo_domain_resource
* alicloud_ddoscoo_port
>     Support new resource and datasoruce for Ddoscoo:       * alicloud_ddoscoo_domain_resource       * alicloud_ddoscoo_port

- alicloud/resource_alicloud_mongodb_instance.go
- ci/pipeline.yml
- ci/tasks/run.sh
> resource/alicloud_mongodb_instance: Fixes describeing tde status bug when db instance type is single

- alicloud/resource_alicloud_mongodb_instance.go
> resource/alicloud_mongodb_instance: Reset replicationFactor to replication_factor when setting iinto state

- alicloud/resource_alicloud_alikafka_topic.go
- website/docs/r/alikafka_consumer_group.html.markdown
- website/docs/r/alikafka_instance.html.markdown
- website/docs/r/alikafka_sasl_acl.html.markdown
- website/docs/r/alikafka_sasl_user.html.markdown
- website/docs/r/alikafka_topic.html.markdown
1. Modified the limit of topic partition
2. Updated the region information of kafka docs
> resource/alicloud_alikafka_topic: Enlarges the partition_num limitation to 360 and adds more supported regions statement in docs

- alicloud/data_source_alicloud_rds_accounts_test.go
- alicloud/resource_alicloud_slb_server_group.go
- ci/pipeline-cn.yml
- ci/tasks/run.sh
- ci/tasks/run.yml
> resource/alicloud_slb_server_group: Removes the attribute servers Computed to fix the diff bug when there is no any server ids

- alicloud/data_source_alicloud_ots_service.go
- alicloud/resource_alicloud_kms_key_test.go
- alicloud/resource_alicloud_mongodb_instance.go
> resource/alicloud_mongodb_instance: Fixes the parsing replication_factor error when it is empty

- alicloud/connectivity/client.go
- alicloud/resource_alicloud_elasticsearch_instance.go
- alicloud/resource_alicloud_elasticsearch_instance_test.go
- alicloud/service_alicloud_common_test.go
- alicloud/service_alicloud_elasticsearch.go
Change the request method of elasticsearch provider to common request;
Fix create ES instance error
> resource/alicloud_elasticsearch_instance: Upgrades its dependence sdk

- ci/pipeline-cn.yml
- ci/pipeline.yml
- ci/tasks/run.yml
> ci: Removes the usless jobs and change job task go verion to 12 to avoid download dependence always

- alicloud/connectivity/regions.go
- alicloud/resource_alicloud_cen_instance_attachment_test.go
- alicloud/resource_alicloud_network_acl_attachment_test.go
- alicloud/resource_alicloud_network_acl_test.go
- alicloud/resource_alicloud_security_group_test.go
- alicloud/resource_alicloud_vswitch_test.go
> testcase: Fixes the sweeper test error caused by new resource ecs_network_interface

- alicloud/connectivity/client.go
- alicloud/resource_alicloud_polardb_cluster.go
- alicloud/service_alicloud_polardb.go
- website/docs/r/polardb_cluster.html.markdown
1、polardb cluster supports transform pay_type
2、add modify db_node_class and renewal_status asynchronous waiting
3、add PrePaid cluster can not be release.
> resource/alicloud_polardb_cluster supports transform pay_type

- alicloud/common.go
- alicloud/data_source_alicloud_config_aggregate_compliance_packs.go
- alicloud/data_source_alicloud_config_aggregate_compliance_packs_test.go
- alicloud/data_source_alicloud_config_aggregate_config_rules.go
- alicloud/data_source_alicloud_config_aggregate_config_rules_test.go
- alicloud/data_source_alicloud_config_compliance_packs.go
- alicloud/data_source_alicloud_config_compliance_packs_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_config_aggregate_compliance_pack.go
- alicloud/resource_alicloud_config_aggregate_compliance_pack_test.go
- alicloud/resource_alicloud_config_aggregate_config_rule.go
- alicloud/resource_alicloud_config_aggregate_config_rule_test.go
- alicloud/resource_alicloud_config_aggregator_test.go
- alicloud/resource_alicloud_config_compliance_pack.go
- alicloud/resource_alicloud_config_compliance_pack_test.go
- alicloud/service_alicloud_config.go
- website/alicloud.erb
- website/docs/d/config_aggregate_compliance_packs.html.markdown
- website/docs/d/config_aggregate_config_rules.html.markdown
- website/docs/d/config_compliance_packs.html.markdown
- website/docs/r/config_aggregate_compliance_pack.html.markdown
- website/docs/r/config_aggregate_config_rule.html.markdown
- website/docs/r/config_compliance_pack.html.markdown
resource:
* alicloud_config_aggregate_config_rule
* alicloud_config_aggregate_compliance_pack
* alicloud_config_compliance_pack
datasource:
* alicloud_config_aggregate_config_rules
* alicloud_config_aggregate_compliance_packs
* alicloud_config_compliance_packs
> Support new resource and datasource for Config

- CHANGELOG.md
- alicloud/data_source_alicloud_kms_ciphertext_test.go
- alicloud/data_source_alicloud_kms_plaintext_test.go
- alicloud/resource_alicloud_db_instance_test.go
- alicloud/resource_alicloud_kms_alias_test.go
- alicloud/resource_alicloud_kms_ciphertext_test.go
- alicloud/resource_alicloud_kms_key.go
- ci/pipeline.yml
- ci/tasks/run.sh
- website/docs/r/ecs_disk.html.markdown
> resource/alicloud_kms_key: Adds limitation for pending_window_in_days when deprecating the deletion_window_in_days

- alicloud/resource_alicloud_network_acl.go
- alicloud/resource_alicloud_network_acl_attachment.go
- alicloud/resource_alicloud_network_acl_attachment_test.go
> resource/alicloud_network_acl: Fixes attributes diff caused by 'resouresource/alicloud_network_acl: Fixes attributes diff caused by 'resources'

- alicloud/resource_alicloud_slb_load_balancer.go
…ance failed caused by 'instance_charge_type'.
> resource/alicloud_slb_load_balancer: Fixes create the payasyougo instance failed caused by 'instance_charge_type'

- alicloud/resource_alicloud_api_gateway_api.go
> resource/alicloud_api_gateway_api: Fixes the bug( issues #2276) when setting the attribute `constant_parameters`

- alicloud/resource_alicloud_network_acl.go
- alicloud/resource_alicloud_network_acl_attachment_test.go
- website/docs/r/network_acl.html.markdown
- website/docs/r/network_acl_attachment.html.markdown
> resource/alicloud_network_acl: Fixes destory resource failed caused by 'resources'

- alicloud/resource_alicloud_log_etl.go
- website/docs/r/log_etl.html.markdown
修复了用户填写role_arn后无论是否填写ak都失败的bug
> resource/alicloud_log_etl: Fix ak and role_arn coexistence bug

- alicloud/data_source_alicloud_pvtz_zone_records.go
- alicloud/resource_alicloud_pvtz_zone_record.go
- alicloud/service_alicloud_pvtz.go
> resource/alicloud_pvtz_zone_record: Fixes the 'record_id' diff error caused by using the incorrect type

- website/docs/r/kvstore_instance.html.markdown
- website/docs/r/mse_cluster.html.markdown
> docs: add note for alicloud_kvstore_instance ssl_enable and correct the alicloud_mse_cluster net_type valid values

- alicloud/resource_alicloud_ecs_disk.go
- alicloud/resource_alicloud_ecs_disk_test.go
- alicloud/resource_alicloud_instance_test.go
- alicloud/resource_alicloud_kms_secret_test.go
> resource/alicloud_ecs_disk: Fixes the creating disk error cause by ModifyDiskChargeType; Fixes the diff bug when category is cloud_essd

- alicloud/resource_alicloud_kms_secret.go
> resource/alicloud_kms_secret: Fixes the Forbidden.ResourceNotFound error when deleting

- alicloud/resource_alicloud_network_acl.go
> resource/alicloud_network_acl: Fixes the entries sort error because of the sort means priority

- alicloud/errors.go
- alicloud/resource_alicloud_oos_template.go
- alicloud/service_alicloud_polardb.go
- alicloud/tags.go
> resource/alicloud_oos_template: Fixes the tags diff bug caused by without ingore system tags

- alicloud/resource_alicloud_db_readonly_instance.go
> resource/alicloud_db_readonly_instance: Fixes the OperationDenied.PrimaryDBInstanceStatus by adding retry when it happened

- alicloud/data_source_alicloud_oss_bucket_objects_test.go
- alicloud/resource_alicloud_oss_bucket_test.go
- alicloud/resource_alicloud_snat_entry_test.go
- alicloud/service_alicloud_rds.go
- ci/pipeline.yml
> resource/alicloud_db_instance: Fixes the OperationDenied.DBInstanceStatus error after modifying parameters; Improves some testcases

- alicloud/resource_alicloud_snat_entry.go
- alicloud/resource_alicloud_snat_entry_test.go
- alicloud/service_alicloud_vpc.go
> resource/alicloud_snat_entry: Fixes the UnknownError when creating a new snat entry by adding Idempotent and retry strategy

- alicloud/data_source_alicloud_resource_manager_accounts.go
- alicloud/data_source_alicloud_resource_manager_accounts_test.go
- alicloud/resource_alicloud_resource_manager_account.go
- alicloud/service_alicloud_resourcemanager.go
- website/docs/d/resource_manager_accounts.html.markdown
…led cause by 'payer_account_id'.
> resource/alicloud_resource_manager_account: Fixes import resoruce failed cause by 'payer_account_id'

- alicloud/resource_alicloud_mse_cluster.go
> resource/alicloud_mse_cluster: Corrects the attribute cluster_specification valid values

- alicloud/data_source_alicloud_kms_key_versions.go
- alicloud/resource_alicloud_kms_key_test.go
- alicloud/resource_alicloud_kms_key_version.go
- alicloud/resource_alicloud_kms_key_version_test.go
- alicloud/resource_alicloud_kms_secret_test.go
- alicloud/service_alicloud_kms.go
- website/docs/d/kms_key_versions.html.markdown
- website/docs/r/kms_key_version.html.markdown
> resource/alicloud_kms_key_version: Upgrades its dependence SDK; Removes the computed attribute creation_date

- alicloud/data_source_alicloud_kms_aliases_test.go
- alicloud/data_source_alicloud_kms_ciphertext.go
- alicloud/data_source_alicloud_kms_ciphertext_test.go
- alicloud/data_source_alicloud_kms_key_versions_test.go
- alicloud/data_source_alicloud_kms_plaintext_test.go
- alicloud/resource_alicloud_db_instance_test.go
- alicloud/resource_alicloud_ecs_disk_test.go
- alicloud/resource_alicloud_ess_scalingconfiguration_test.go
- alicloud/resource_alicloud_instance_test.go
- alicloud/resource_alicloud_kms_alias_test.go
- alicloud/resource_alicloud_kms_key_test.go
- alicloud/resource_alicloud_nas_file_system_test.go
>  resource/alicloud_kms_ciphertext: Upgrades its dependence sdk; Improves the kms key testcases

- alicloud/resource_alicloud_cr_ee_instance.go
> resource/alicloud_cr_ee_instance: Fixes the NotApplicable error for international site account

- alicloud/resource_alicloud_snat_entry.go
> resource/alicloud_snat_entry: Fixes the concurrence issue which throwing the error OperationFailed.Throttling

- alicloud/data_source_alicloud_eips.go
- alicloud/data_source_alicloud_eips_test.go
- alicloud/resource_alicloud_eip.go
- alicloud/resource_alicloud_eip_test.go
- website/docs/d/eips.html.markdown
- website/docs/r/eip.html.markdown
> resource/alicloud_eip: Adds new attribute deletion_protection to support deletion protection feature

- alicloud/resource_alicloud_nat_gateway.go
- alicloud/resource_alicloud_nat_gateway_test.go
- website/docs/r/nat_gateway.html.markdown
… to support deletion protection feature
> resource/alicloud_nat_gateway: Adds new attribute deletion_protection to support deletion protection feature

- alicloud/resource_alicloud_common_bandwidth_package.go
- alicloud/resource_alicloud_common_bandwidth_package_test.go
- website/docs/r/common_bandwidth_package.html.markdown
> resource/alicloud_common_bandwidth_package: Adds new attribute deletion_protection to support deletion protection feature

- alicloud/resource_alicloud_resource_manager_resource_directory.go
- website/docs/r/resource_manager_resource_directory.html.markdown
…or by 'status' when update provider.
> resource/alicloud_resource_manager_resource_directory: Fixed diff error by 'status' when update provider.

- alicloud/data_source_alicloud_resource_manager_accounts.go
- alicloud/data_source_alicloud_resource_manager_accounts_test.go
- website/docs/d/resource_manager_accounts.html.markdown
>  datasource/alicloud_resource_manager_accounts: Exports new attributes 'account_name'.

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/data_source_alicloud_direct_mail_receiverses.go
- alicloud/data_source_alicloud_direct_mail_receiverses_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_direct_mail_receivers.go
- alicloud/resource_alicloud_direct_mail_receivers_test.go
- alicloud/service_alicloud_dm.go
- website/alicloud.erb
- website/docs/d/direct_mail_receiverses.html.markdown
- website/docs/r/direct_mail_receivers.html.markdown
NewDataSource `alicloud_direct_mail_receiverses`
>  NewResource `alicloud_direct_mail_receivers`      NewDataSource `alicloud_direct_mail_receiverses`

- alicloud/resource_alicloud_ddoscoo_instance.go
- alicloud/resource_alicloud_ddoscoo_instance_test.go
- alicloud/service_alicloud_ddoscoo.go
- website/docs/r/ddoscoo_instance.html.markdown
Update DDOS supports international accounts to purchase domestic instances
> DDOS supports international accounts to purchase domestic instances

- alicloud/data_source_alicloud_log_projects.go
- alicloud/data_source_alicloud_log_projects_test.go
- alicloud/data_source_alicloud_log_stores.go
- alicloud/data_source_alicloud_log_stores_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_log_project.go
- alicloud/service_alicloud_log.go
- website/alicloud.erb
- website/docs/d/log_projects.html.markdown
- website/docs/d/log_stores.html.markdown
- website/docs/r/log_project.html.markdown
NewDataSource `alicloud_log_stores`
> NewDataSource `alicloud_log_projects`     NewDataSource `alicloud_log_stores`

- alicloud/resource_alicloud_polardb_cluster.go
- alicloud/service_alicloud_polardb.go
- website/docs/r/polardb_cluster.html.markdown
fixed first request modify tdestatus asynchronous timeout
> resource/alicloud_polardb_cluster: Enlarges the timeout after modifying the tde_status

- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_db_instance_test.go
- website/docs/r/db_instance.html.markdown
> resource/alicloud_db_instance:  Adds new attributes connection_string_prefix and port to support Modify db instance connection_string_prefix or port.

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/data_source_alicloud_event_bridge_event_buses.go
- alicloud/data_source_alicloud_event_bridge_event_buses_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_event_bridge_event_bus.go
- alicloud/resource_alicloud_event_bridge_event_bus_test.go
- alicloud/service_alicloud_eventbridge_share.go
- website/alicloud.erb
- website/docs/d/event_bridge_event_buses.html.markdown
- website/docs/r/event_bridge_event_bus.html.markdown
New DataSource `alicloud_event_bridge_event_buses`
>   New Resource `alicloud_event_bridge_event_bus`     New DataSource `alicloud_event_bridge_event_buses`

- alicloud/data_source_alicloud_event_bridge_schema_groups.go
- alicloud/data_source_alicloud_event_bridge_schema_groups_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_event_bridge_schema_group.go
- alicloud/resource_alicloud_event_bridge_schema_group_test.go
- alicloud/service_alicloud_eventbridge_share.go
- website/alicloud.erb
- website/docs/d/event_bridge_schema_groups.html.markdown
- website/docs/r/event_bridge_schema_group.html.markdown
NewDataSource `alicloud_event_bridge_schema_groups`
>  NewResource `alicloud_event_bridge_schema_group`  NewDataSource `alicloud_event_bridge_schema_groups`

- CHANGELOG.md
- alicloud/data_source_alicloud_amqp_virtual_hosts_test.go
- alicloud/resource_alicloud_mongodb_instance.go
> resource/alicloud_mongodb_instance: Fixes the ProxyError issue when invoking the DescribeMongoDBTDEInfo API

- CHANGELOG.md
- alicloud/resource_alicloud_mongodb_instance.go
- website/docs/r/mongodb_instance.html.markdown
> resource/alicloud_mongodb_instance: Fixes the setting replication_factor failed error

- CHANGELOG.md
- alicloud/resource_alicloud_mongodb_instance.go
- alicloud/resource_alicloud_mongodb_sharding_instance.go
- alicloud/resource_alicloud_mongodb_sharding_instance_test.go
- alicloud/service_alicloud_mongodb.go
- website/docs/r/mongodb_sharding_instance.html.markdown
> resource/alicloud_mongodb_sharding_instance: The attribute shard_list supports to set readonly_replicas

- alicloud/data_source_alicloud_amqp_queues.go
- alicloud/data_source_alicloud_amqp_queues_test.go
- alicloud/data_source_alicloud_amqp_virtual_hosts_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_amqp_queue.go
- alicloud/resource_alicloud_amqp_queue_test.go
- alicloud/service_alicloud_amqp_open.go
- website/alicloud.erb
- website/docs/d/amqp_queues.html.markdown
- website/docs/r/amqp_queue.html.markdown
> Adds a new resource alicloud_amqp_queue and its datasource alicloud_amqp_queues

- website/docs/r/gpdb_elastic_instance.html.markdown
Updated File :
- gpdb_elastic_instance.html.markdown
> doc/alicloud_gpdb_elastic_instance: Fixes some Example Usage Parameter 

- alicloud/data_source_alicloud_cen_transit_router_peer_attachments.go
- alicloud/data_source_alicloud_cen_transit_router_peer_attachments_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cassandra_backup_plan.go
- alicloud/resource_alicloud_cen_instance_test.go
- alicloud/resource_alicloud_cen_transit_router_peer_attachment.go
- alicloud/resource_alicloud_cen_transit_router_peer_attachment_test.go
- alicloud/resource_alicloud_route_table.go
- alicloud/service_alicloud_cbn.go
- website/alicloud.erb
- website/docs/d/cen_transit_router_peer_attachments.html.markdown
- website/docs/r/cen_transit_router_peer_attachment.html.markdown
NewDataSource `alicloud_cen_transit_router_peer_attachments`
>     NewResource `alicloud_cen_transit_router_peer_attachment`     NewDataSource `alicloud_cen_transit_router_peer_attachments`

- alicloud/connectivity/client.go
- alicloud/connectivity/endpoint.go
- alicloud/provider.go
- website/docs/index.html.markdown
> provider: Sets old sdk config EnableAsync to false; Close the location client after it invoked

- alicloud/data_source_alicloud_kvstore_instances.go
- alicloud/data_source_alicloud_kvstore_instances_test.go
- alicloud/resource_alicloud_kvstore_instance.go
- alicloud/resource_alicloud_kvstore_instance_test.go
- website/docs/d/kvstore_instances.html.markdown
- website/docs/r/kvstore_instance.html.markdown
> resource/alicloud_kvstore_instance: Adds new attribute secondary_zone_id to support secondary zone

- alicloud/resource_alicloud_db_instance.go
- alicloud/service_alicloud_rds.go
updated files:
- service_alicloud_rds.go
> resource/alicloud_db_instance: Checks db_instance's status before updating sql_collector_status attribute

- alicloud/data_source_alicloud_amqp_instances.go
- alicloud/resource_alicloud_amqp_instance.go
- alicloud/resource_alicloud_amqp_instance_test.go
- alicloud/resource_alicloud_cen_instance.go
- alicloud/service_alicloud_cbn.go
- website/docs/r/amqp_instance.html.markdown
> resource/alicloud_amqp_instance: Supports to modify the attribute storage_size

- alicloud/data_source_alicloud_amqp_queues.go
> datasource/alicloud_amqp_queues: Improves the setting attribute 'attributes'

- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_amqp_instance_test.go
- alicloud/resource_alicloud_cs_kubernetes_node_pool.go
- alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go
- alicloud/resource_alicloud_cs_kubernetes_permissions.go
1 fix grant permission error: ServiceUnavailable & ErrorJsonDecode
2 fix node pool UT
> resource/alicloud_cs_kubernetes_permissions: Fixes grant permission error

- alicloud/data_source_alicloud_event_bridge_rules.go
- alicloud/data_source_alicloud_event_bridge_rules_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_event_bridge_rule.go
- alicloud/resource_alicloud_event_bridge_rule_test.go
- alicloud/service_alicloud_eventbridge.go
- website/alicloud.erb
- website/docs/d/event_bridge_rules.html.markdown
- website/docs/r/event_bridge_rule.html.markdown
NewDataSource `alicloud_event_bridge_rules`
>    NewResoruce `alicloud_event_bridge_rule`     NewDataSource `alicloud_event_bridge_rules`

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/data_source_alicloud_cloud_firewall_control_policies.go
- alicloud/data_source_alicloud_cloud_firewall_control_policies_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cloud_firewall_control_policy.go
- alicloud/resource_alicloud_cloud_firewall_control_policy_test.go
- alicloud/service_alicloud_cloudfw.go
- website/alicloud.erb
- website/docs/d/cloud_firewall_control_policies.html.markdown
- website/docs/r/cloud_firewall_control_policy.html.markdown
New Resource alicloud_cloud_firewall_control_policy
New Data Resource alicloud_cloud_firewall_control_policies
> New Resource `alicloud_cloud_firewall_control_policy `  New Data Resource `alicloud_cloud_firewall_control_policies`

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/data_source_alicloud_sae_namespaces.go
- alicloud/data_source_alicloud_sae_namespaces_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_sae_namespace.go
- alicloud/resource_alicloud_sae_namespace_test.go
- alicloud/service_alicloud_sae.go
- website/alicloud.erb
- website/docs/d/sae_namespaces.html.markdown
- website/docs/r/sae_namespace.html.markdown
updated file:
- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/data_source_alicloud_sae_namespaces.go
- alicloud/data_source_alicloud_sae_namespaces_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_sae_namespace.go
- alicloud/resource_alicloud_sae_namespace_test.go
- alicloud/service_alicloud_sae.go
> New Resource:alicloud_sae_namespace and its Data Source

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_alb_security_policies.go
- alicloud/data_source_alicloud_alb_security_policies_test.go
- alicloud/data_source_alicloud_arms_alert_contacts_test.go
- alicloud/data_source_alicloud_sae_config_maps_test.go
- alicloud/data_source_alicloud_sae_namespaces_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_alb_security_policy.go
- alicloud/resource_alicloud_alb_security_policy_test.go
- alicloud/resource_alicloud_cloud_firewall_control_policy.go
- alicloud/resource_alicloud_sae_config_map.go
- alicloud/resource_alicloud_sae_config_map_test.go
- alicloud/resource_alicloud_sae_namespace.go
- alicloud/resource_alicloud_sae_namespace_test.go
- alicloud/service_alicloud_alb.go
- website/alicloud.erb
- website/docs/d/alb_security_policies.html.markdown
- website/docs/r/alb_security_policy.html.markdown
New Resource `alb_security_policy`
New DataSouece `alb_security_policies`
>     New Resource `alb_security_policy`     New DataSouece `alb_security_policies`

- alicloud/provider.go
- alicloud/resource_alicloud_cloud_firewall_control_policy_order.go
- alicloud/resource_alicloud_cloud_firewall_control_policy_order_test.go
- website/alicloud.erb
- website/docs/d/cloud_firewall_control_policies.html.markdown
- website/docs/r/cloud_firewall_control_policy.html.markdown
- website/docs/r/cloud_firewall_control_policy_order.html.markdown
New resource `alicloud_cloud_firewall_control_policy_order`
Optimization `alicloud_cloud_firewall_control_policy` DOC
> New resource `alicloud_cloud_firewall_control_policy_order` 

- alicloud/resource_alicloud_alidns_record.go
- alicloud/resource_alicloud_kvstore_audit_log_config_test.go
> resource/alicloud_alidns_record: Fixes the LastOperationNotFinished when creating several records one time

- alicloud/resource_alicloud_ess_attachment.go
- alicloud/service_alicloud_ess.go
> resource/alicloud_ess_attachment: Fixes the bug: call of reflect.Value.Set on zero Value

- alicloud/data_source_alicloud_alb_server_groups.go
- alicloud/data_source_alicloud_alb_server_groups_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_alb_server_group.go
- alicloud/resource_alicloud_alb_server_group_test.go
- alicloud/service_alicloud_alb.go
- website/alicloud.erb
- website/docs/d/alb_server_groups.html.markdown
- website/docs/r/alb_server_group.html.markdown
New Resource `alb_server_group`
New DataSource `alb_server_groups`
> New Resource `alb_server_group` New DataSource `alb_server_groups`

- alicloud/data_source_alicloud_event_bridge_rules_test.go
- alicloud/resource_alicloud_event_bridge_rule.go
- alicloud/resource_alicloud_event_bridge_rule_test.go
- alicloud/service_alicloud_eventbridge.go
- website/docs/r/event_bridge_rule.html.markdown
Fix `alicloud_event_bridge_rule` targets Parameters Bug And Update its Test Case
> resource/alicloud_event_bridge_rule: Fixes the targets parameters bug and update its testcase

- alicloud/data_source_alicloud_cr_ee_instances_test.go
- alicloud/data_source_alicloud_cr_ee_namespaces_test.go
- alicloud/data_source_alicloud_cr_ee_repos_test.go
- alicloud/data_source_alicloud_cr_ee_sync_rules_test.go
- alicloud/data_source_alicloud_express_connect_access_points_test.go
- alicloud/resource_alicloud_cr_ee_instance.go
- alicloud/resource_alicloud_cr_ee_instance_test.go
- alicloud/resource_alicloud_cr_ee_namespace_test.go
- alicloud/resource_alicloud_cr_ee_repo_test.go
- alicloud/resource_alicloud_cr_ee_sync_rule_test.go
- alicloud/resource_alicloud_dcdn_domain_config_test.go
- alicloud/service_alicloud_cr_ee.go
- website/docs/r/cr_ee_instance.html.markdown
- website/docs/r/kvstore_instance.html.markdown
> resource/alicloud_cr_ee_instance: Adds new attribute password to support reset instance login password

- alicloud/data_source_alicloud_cr_ee_instances.go
- alicloud/data_source_alicloud_cr_ee_instances_test.go
- website/docs/d/cr_ee_instances.html.markdown
> data/alicloud_cr_ee_instances: Outputs more attributes authorization_token and temp_username

- alicloud/resource_alicloud_actiontrail_trail.go
- fix update AT trail error: should pass OssWriteRoleArn while call UpdateTrail
> resource/alicloud_actiontrail_trail: Fixes the error when updating trail config oss_write_role_arn

- alicloud/data_source_alicloud_cr_ee_sync_rules.go
- alicloud/data_source_alicloud_cr_ee_sync_rules_test.go
- alicloud/resource_alicloud_cr_ee_instance.go
- alicloud/resource_alicloud_cr_ee_instance_test.go
- alicloud/resource_alicloud_cr_ee_namespace.go
- alicloud/resource_alicloud_cr_ee_namespace_test.go
- alicloud/resource_alicloud_cr_ee_repo.go
- alicloud/resource_alicloud_cr_ee_sync_rule.go
- alicloud/resource_alicloud_cr_ee_sync_rule_test.go
- alicloud/resource_alicloud_kvstore_instance_test.go
- alicloud/resource_alicloud_scdn_domain_config_test.go
- alicloud/service_alicloud_cr_ee.go
- website/docs/r/cr_ee_instance.html.markdown
> resource/alicloud_cr_ee_instance: Supports to set create timeout; testcase: Improves the alicloud_cr_ee_sync_rule testcases

- alicloud/data_source_alicloud_lindorm_instances.go
- alicloud/data_source_alicloud_lindorm_instances_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cr_ee_repo.go
- alicloud/resource_alicloud_lindorm_instance.go
- alicloud/resource_alicloud_lindorm_instance_test.go
- alicloud/service_alicloud_hitsdb.go
- website/alicloud.erb
- website/docs/d/lindorm_instances.html.markdown
- website/docs/r/lindorm_instance.html.markdown
New Resource `alicloud_lindorm_instance`
New DataSource `alicloud_lindorm_instances`
> New Resource `alicloud_lindorm_instance` New DataSource `alicloud_lindorm_instances`

- alicloud/data_source_alicloud_event_bridge_service.go
- alicloud/data_source_alicloud_express_connect_physical_connection_service.go
- alicloud/data_source_alicloud_express_connect_physical_connection_service_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cloud_storage_gateway_gateway.go
- alicloud/resource_alicloud_cloud_storage_gateway_gateway_test.go
- website/docs/d/express_connect_physical_connection_service.html.markdown
> Adds a new datasource alicloud_express_connect_physical_connection_service

- alicloud/data_source_alicloud_express_connect_physical_connection_test.go
- alicloud/data_source_alicloud_express_connect_physical_connections.go
- alicloud/data_source_alicloud_hbr_ecs_backup_clients_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_express_connect_physical_connection.go
- alicloud/resource_alicloud_express_connect_physical_connection_test.go
- alicloud/resource_alicloud_hbr_ecs_backup_client.go
- alicloud/resource_alicloud_hbr_ecs_backup_client_test.go
- alicloud/service_alicloud_vpc.go
- website/alicloud.erb
- website/docs/d/express_connect_physical_connections.html.markdown
- website/docs/r/express_connect_physical_connection.html.markdown
> Adds a new resource  alicloud_express_connect_physical_connection and its datasource

- alicloud/connectivity/endpoint.go
- alicloud/data_source_alicloud_edas_service.go
- alicloud/data_source_alicloud_fnf_service.go
- alicloud/data_source_alicloud_pvtz_service.go
- website/docs/d/event_bridge_service.html.markdown
> datasource: Fixes the NotApplicable when using the alicloud_pvtz_serivce, alicloud_fnf_service, and alicloud_edas_service

- alicloud/data_source_alicloud_alb_acls.go
- alicloud/data_source_alicloud_alb_acls_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_alb_acl.go
- alicloud/resource_alicloud_alb_acl_test.go
- alicloud/service_alicloud_alb.go
- website/alicloud.erb
- website/docs/d/alb_acls.html.markdown
- website/docs/r/alb_acl.html.markdown
NewResource `alicloud_alb_acl`
NewDataSource `alicloud_alb_acls`
> NewResource `alicloud_alb_acl` NewDataSource `alicloud_alb_acls`

- alicloud/resource_alicloud_arms_alert_contact.go
- ci/pipeline-cn.yml
- ci/pipeline.yml
> resource/alicloud_arms_contact: Fixes the ParameterMissing error when invoking UpdateAlertContact

- alicloud/resource_alicloud_bastionhost_instance.go
- alicloud/resource_alicloud_bastionhost_user.go
- alicloud/resource_alicloud_bastionhost_user_test.go
- alicloud/service_alicloud_yundun_bastionhost.go
- website/docs/r/bastionhost_instance.html.markdown
- website/docs/r/bastionhost_user.html.markdown
> resource/alicloud_bastionhost_instance: Enlarges the create timeout and improves its docs

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/data_source_alicloud_dfs_access_groups.go
- alicloud/data_source_alicloud_dfs_access_groups_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_dfs_access_group.go
- alicloud/resource_alicloud_dfs_access_group_test.go
- alicloud/service_alicloud_dfs.go
- website/alicloud.erb
- website/docs/d/dfs_access_groups.html.markdown
- website/docs/r/dfs_access_group.html.markdown
New Resource `alicloud_dfs_access_group` New DataSource `alicloud_dfs_access_groups`
> New Resource `alicloud_dfs_access_group` New DataSource `alicloud_dfs_access_groups`

- alicloud/service_alicloud_elasticsearch.go
- ci/pipeline-cn.yml
- ci/pipeline.yml
> resource/alicloud_elasticsearch_instance: Fixes the GetCustomerLabelFail error by adding retry

- alicloud/data_source_alicloud_sae_applications.go
- alicloud/data_source_alicloud_sae_applications_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_sae_application.go
- alicloud/resource_alicloud_sae_application_test.go
- alicloud/service_alicloud_sae.go
- website/alicloud.erb
- website/docs/d/sae_applications.html.markdown
- website/docs/r/sae_application.html.markdown
> New Resource alicloud_sae_application New Datasource alicloud_sae_applications

- alicloud/data_source_alicloud_alb_listeners_test.go
- alicloud/data_source_alicloud_alb_rules.go
- alicloud/data_source_alicloud_alb_rules_test.go
- alicloud/data_source_alicloud_hbr_restore_jobs_test.go
- alicloud/data_source_alicloud_hbr_snapshots_test.go
- alicloud/data_source_alicloud_sddp_configs.go
- alicloud/provider.go
- alicloud/resource_alicloud_alb_listener.go
- alicloud/resource_alicloud_alb_listener_test.go
- alicloud/resource_alicloud_alb_rule.go
- alicloud/resource_alicloud_alb_rule_test.go
- alicloud/service_alicloud_alb.go
- website/alicloud.erb
- website/docs/d/alb_rules.html.markdown
- website/docs/r/alb_rule.html.markdown
New Datasource `alicloud_alb_rules`
> New Resource `alicloud_alb_rule` New Datasource `alicloud_alb_rules`

- alicloud/resource_alicloud_slb_listener.go
> resource/alicloud_slb_listener: Supports to setting scheduler in the creating to fix it cannot modify

- alicloud/resource_alicloud_slb_listener.go
- website/docs/r/slb_listener.html.markdown
> resource/alicloud_slb_listener: Attribute scheduler support more values tch and qch

- alicloud/data_source_alicloud_alikafka_consumer_groups_test.go
- alicloud/data_source_alicloud_alikafka_instances_test.go
- alicloud/data_source_alicloud_alikafka_sasl_acls_test.go
- alicloud/data_source_alicloud_alikafka_sasl_users_test.go
- alicloud/data_source_alicloud_alikafka_topics_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_alikafka_consumer_group_test.go
- alicloud/resource_alicloud_alikafka_instance.go
- alicloud/resource_alicloud_alikafka_instance_test.go
- alicloud/resource_alicloud_alikafka_sasl_acl_test.go
- alicloud/resource_alicloud_alikafka_sasl_user_test.go
- alicloud/resource_alicloud_alikafka_topic_test.go
- website/docs/r/alikafka_instance.html.markdown
> resource/alicloud_alikafka_instance: Fixes the diff error caused by eip_max and security_group

- alicloud/data_source_alicloud_cms_metric_rule_templates.go
- alicloud/data_source_alicloud_cms_metric_rule_templates_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cms_metric_rule_template.go
- alicloud/resource_alicloud_cms_metric_rule_template_test.go
- alicloud/service_alicloud_cms.go
- website/alicloud.erb
- website/docs/d/cms_metric_rule_templates.html.markdown
- website/docs/r/cms_metric_rule_template.html.markdown
NewResource `alicloud_cms_metric_rule_template`  
NewDataSource `alicloud_cms_metric_rule_templates`
> NewResource `alicloud_cms_metric_rule_template` NewDataSource `alicloud_cms_metric_rule_templates`

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_imm_projects.go
- alicloud/data_source_alicloud_imm_projects_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_imm_project.go
- alicloud/resource_alicloud_imm_project_test.go
- alicloud/service_alicloud_imm.go
- website/alicloud.erb
- website/docs/d/imm_projects.html.markdown
- website/docs/r/imm_project.html.markdown
New Resource `alicloud_imm_project` New Datasource `alicloud_imm_projects`
> New Resource `alicloud_imm_project` New Datasource `alicloud_imm_projects`

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_click_house_db_clusters.go
- alicloud/data_source_alicloud_click_house_db_clusters_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_click_house_db_cluster.go
- alicloud/resource_alicloud_click_house_db_cluster_test.go
- alicloud/resource_alicloud_cms_metric_rule_template_test.go
- alicloud/service_alicloud_clickhouse.go
- website/alicloud.erb
- website/docs/d/click_house_db_clusters.html.markdown
- website/docs/r/click_house_db_cluster.html.markdown
> New Resource alicloud_click_house_db_cluster New Datasource alicloud_click_house_db_clusters

- alicloud/data_source_alicloud_cen_transit_router_peer_attachments_test.go
- alicloud/data_source_alicloud_vpc_dhcp_options_sets.go
- alicloud/data_source_alicloud_vpc_dhcp_options_sets_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cen_instance_test.go
- alicloud/resource_alicloud_cen_transit_router_peer_attachment_test.go
- alicloud/resource_alicloud_cen_transit_router_route_table_test.go
- alicloud/resource_alicloud_cen_transit_router_test.go
- alicloud/resource_alicloud_cen_transit_router_vbr_attachment_test.go
- alicloud/resource_alicloud_iot_device_group.go
- alicloud/resource_alicloud_vpc_dhcp_options_set.go
- alicloud/resource_alicloud_vpc_dhcp_options_set_test.go
- alicloud/service_alicloud_vpc.go
- website/alicloud.erb
- website/docs/d/vpc_dhcp_options_sets.html.markdown
- website/docs/r/vpc_dhcp_options_set.html.markdown
NewResource `alicloud_vpc_dhcp_options_set`
NewDataSource `alicloud_vpc_dhcp_options_sets`
> NewResource `alicloud_vpc_dhcp_options_set`  NewDataSource `alicloud_vpc_dhcp_options_sets`

- alicloud/data_source_alicloud_alb_health_check_templates.go
- alicloud/data_source_alicloud_alb_health_check_templates_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_alb_health_check_template.go
- alicloud/resource_alicloud_alb_health_check_template_test.go
- alicloud/service_alicloud_alb.go
- website/alicloud.erb
- website/docs/d/alb_health_check_templates.html.markdown
- website/docs/r/alb_health_check_template.html.markdown
New Resource `alicloud_alb_health_check_template` New DataSource `alicloud_alb_health_check_templates`
> New Resource `alicloud_alb_health_check_template` New DataSource `alicloud_alb_health_check_templates`

- alicloud/provider.go
- alicloud/service_alicloud_ram.go
> resource/alicloud_ram_user: Fixes the EntityNotExist.User error when getting user

- alicloud/data_source_alicloud_alb_health_check_templates_test.go
- alicloud/resource_alicloud_mongodb_instance.go
- alicloud/resource_alicloud_mongodb_instance_test.go
- alicloud/resource_alicloud_mongodb_sharding_instance.go
- alicloud/resource_alicloud_mongodb_sharding_instance_test.go
- alicloud/service_alicloud_mongodb.go
- website/docs/r/mongodb_instance.html.markdown
- website/docs/r/mongodb_sharding_instance.html.markdown
> resource/alicloud_mongodb_instance,alicloud_mongodb_sharding_instance: Adds new attribute order_type to support updating instance spec

- alicloud/data_source_alicloud_cdn_real_time_log_deliveries.go
- alicloud/data_source_alicloud_cdn_real_time_log_deliveries_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cdn_real_time_log_delivery.go
- alicloud/resource_alicloud_cdn_real_time_log_delivery_test.go
- alicloud/service_alicloud_cdn.go
- website/alicloud.erb
- website/docs/d/cdn_real_time_log_deliveries.html.markdown
- website/docs/r/cdn_real_time_log_delivery.html.markdown
New Resource `alicloud_cdn_real_time_log_delivery` New Datasource `alicloud_cdn_real_time_log_deliveries`
> New Resource `alicloud_cdn_real_time_log_delivery` New Datasource `alicloud_cdn_real_time_log_deliveries`

- alicloud/data_source_alicloud_click_house_accounts.go
- alicloud/data_source_alicloud_click_house_accounts_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_click_house_account.go
- alicloud/resource_alicloud_click_house_account_test.go
- alicloud/service_alicloud_clickhouse.go
- website/alicloud.erb
- website/docs/d/click_house_accounts.html.markdown
- website/docs/r/click_house_account.html.markdown
> New Resource alicloud_clisck_house_account New Datasource alicloud_click_house_accounts

- alicloud/resource_alicloud_alb_acl_test.go
- alicloud/resource_alicloud_alb_health_check_template_test.go
- alicloud/resource_alicloud_alb_listener_test.go
- alicloud/resource_alicloud_alb_load_balancer_test.go
- alicloud/resource_alicloud_alb_security_policy_test.go
- alicloud/resource_alicloud_alb_server_group_test.go
testcase/alb_load_balancer: add sweeper test
testcase/alb_server_group: add sweeper test
testcase/alb_security_policy: add sweeper test
testcase/alb_listener: change sweeper test
testcase/alb_acl: change sweeper test
> testcase/alb: add sweeper test 

- alicloud/data_source_alicloud_db_zones.go
- alicloud/data_source_alicloud_db_zones_test.go
- alicloud/resource_alicloud_direct_mail_mail_address.go
> datasource/alicloud_db_zones: Upgrades its dependence OpenAPI to DescribeAvailableZones

- alicloud/data_source_alicloud_db_instance_classes.go
- alicloud/data_source_alicloud_db_instance_classes_test.go
- alicloud/data_source_alicloud_db_instance_engines.go
- alicloud/data_source_alicloud_db_instance_engines_test.go
- alicloud/data_source_alicloud_db_zones.go
> datasource/alicloud_db_instance_classes: Upgrades its dependence OpenAPI to DescribeAvailableClasses

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_database_gateway_gateways.go
- alicloud/data_source_alicloud_database_gateway_gateways_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_database_gateway_gateway.go
- alicloud/resource_alicloud_database_gateway_gateway_test.go
- alicloud/resource_alicloud_dts_job_monitor_rule.go
- alicloud/service_alicloud_dg.go
- website/alicloud.erb
- website/docs/d/database_gateway_gateways.html.markdown
- website/docs/r/database_gateway_gateway.html.markdown
New DataSource `alicloud_database_gateway_gateways`
> New Resource `alicloud_database_gateway_gateway` New DataSource `alicloud_database_gateway_gateways`

- alicloud/resource_alicloud_fc_trigger.go
- alicloud/service_alicloud_fc.go
1. there is white space change in fc trigger even if the trigger config dose not change at all
> resource/alicloud_fc_trigger: Fixes fc trigger white space change error

- alicloud/resource_alicloud_amqp_instance.go
> resource/alicloud_bastionhost_instance: Improves the attribute value setting when invoking SetRenewal to update renewal attribute

- alicloud/data_source_alicloud_db_instances.go
- alicloud/service_alicloud_rds.go
- website/docs/d/db_instances.html.markdown
> datasource/alicloud_db_instances: Adds attribute enable_details to show extra parameter template.

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_cloud_sso_directories.go
- alicloud/data_source_alicloud_cloud_sso_directories_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cloud_sso_directory.go
- alicloud/resource_alicloud_cloud_sso_directory_test.go
- alicloud/service_alicloud_cloudsso.go
- website/alicloud.erb
- website/docs/d/cloud_sso_directories.html.markdown
- website/docs/r/cloud_sso_directory.html.markdown
NewResource `alicloud_cloud_sso_directory`
NewDataSource `alicloud_cloud_sso_directories`
> NewResource `alicloud_cloud_sso_directory` NewDataSource `alicloud_cloud_sso_directories`

- alicloud/data_source_alicloud_bastionhost_host_accounts.go
- alicloud/data_source_alicloud_bastionhost_host_accounts_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_bastionhost_host_account.go
- alicloud/resource_alicloud_bastionhost_host_account_test.go
- alicloud/resource_alicloud_slb_tls_cipher_policy_test.go
- alicloud/service_alicloud_yundun_bastionhost.go
- ci/pipeline.yml
- website/alicloud.erb
- website/docs/d/bastionhost_host_accounts.html.markdown
- website/docs/r/bastionhost_host_account.html.markdown
> Adds a new resource alicloud_bastionhost_host_account and datasource alicloud_bastionhost_host_accounts

- alicloud/connectivity/config.go
- alicloud/data_source_alicloud_waf_certificates.go
- alicloud/data_source_alicloud_waf_certificates_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_waf_certificate.go
- alicloud/resource_alicloud_waf_certificate_test.go
- alicloud/service_alicloud_waf_openapi.go
- website/alicloud.erb
- website/docs/d/waf_certificates.html.markdown
- website/docs/r/waf_certificate.html.markdown
> New Resource alicloud_waf_certificate New Datasource alicloud_waf_alicloud_waf_certificates

- alicloud/resource_alicloud_log_audit.go
- alicloud/resource_alicloud_log_audit_test.go
- website/docs/r/log_audit.html.markdown
log audit service of log_service support resource directory
> logservice audit support resource directory

- website/docs/r/cdn_domain_config.html.markdown
doc/alicloud_cdn_doamin_config: Optimize document format
> doc/alicloud_cdn_doamin_config: Optimize document format

- alicloud/provider.go
- alicloud/resource_alicloud_bastionhost_host_group_account_user_attachment.go
- alicloud/resource_alicloud_bastionhost_host_group_account_user_attachment_test.go
- alicloud/service_alicloud_yundun_bastionhost.go
- website/alicloud.erb
- website/docs/r/bastionhost_host_group_account_user_attachment.html.markdown
> Adds a new resource alicloud_bastionhost_host_group_account_user_attachment

- alicloud/data_source_alicloud_alb_listeners.go
- alicloud/data_source_alicloud_alb_listeners_test.go
- alicloud/resource_alicloud_alb_acl.go
- alicloud/resource_alicloud_alb_listener.go
- alicloud/resource_alicloud_alb_listener_test.go
- website/docs/d/alb_listeners.html.markdown
- website/docs/d/alb_load_balancers.html.markdown
- website/docs/r/alb_listener.html.markdown
- website/docs/r/alb_server_group.html.markdown
fix: `alb_listener` - add associate acls
> resource/alicloud_alb_listeners: Adds new attribute acl_config to set associate acls

- alicloud/resource_alicloud_nat_gateway.go
- alicloud/resource_alicloud_nat_gateway_test.go
- website/docs/r/nat_gateway.html.markdown
resource/alicloud_nat_gateway: Adds new attribute network_type to support create Vpc  NatGateway
> resource/alicloud_nat_gateway: Adds new attribute network_type to support create Vpc  NatGateway

- alicloud/data_source_alicloud_vpc_nat_ip_cidrs.go
- alicloud/data_source_alicloud_vpc_nat_ip_cidrs_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_vpc_nat_ip_cidr.go
- alicloud/resource_alicloud_vpc_nat_ip_cidr_test.go
- alicloud/service_alicloud_vpc.go
- website/alicloud.erb
- website/docs/d/vpc_nat_ip_cidrs.html.markdown
- website/docs/r/vpc_nat_ip_cidr.html.markdown
NewResource `alicloud_vpc_nat_ip_cidr` NewDataSource `alicloud_vpc_nat_ip_cidrs`
> NewResource `alicloud_vpc_nat_ip_cidr` NewDataSource `alicloud_vpc_nat_ip_cidrs`

- alicloud/data_source_alicloud_vpc_nat_ips.go
- alicloud/data_source_alicloud_vpc_nat_ips_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_vpc_nat_ip.go
- alicloud/resource_alicloud_vpc_nat_ip_test.go
- alicloud/service_alicloud_vpc.go
- website/alicloud.erb
- website/docs/d/vpc_nat_ips.html.markdown
- website/docs/r/vpc_nat_ip.html.markdown
NewResource `alicloud_vpc_nat_ip`
NewDataSource `alicloud_vpc_nat_ips`
> NewResource `alicloud_vpc_nat_ip` NewDataSource `alicloud_vpc_nat_ips`

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/data_source_alicloud_quick_bi_users.go
- alicloud/data_source_alicloud_quick_bi_users_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_quick_bi_user.go
- alicloud/resource_alicloud_quick_bi_user_test.go
- alicloud/service_alicloud_quickbi_public.go
- website/alicloud.erb
- website/docs/d/quick_bi_users.html.markdown
- website/docs/r/quick_bi_user.html.markdown
New Resource `alicloud_quick_bi_user` New DataSource `alicloud_quick_bi_users`
> New Resource `alicloud_quick_bi_user` New DataSource `alicloud_quick_bi_users`

- alicloud/common.go
- alicloud/data_source_alicloud_arms_dispatch_rules.go
- alicloud/data_source_alicloud_arms_dispatch_rules_test.go
- alicloud/data_source_alicloud_bastionhost_host_accounts_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_arms_dispatch_rule.go
- alicloud/resource_alicloud_arms_dispatch_rule_test.go
- alicloud/resource_alicloud_quick_bi_user_test.go
- alicloud/service_alicloud_arms.go
- website/alicloud.erb
- website/docs/d/arms_dispatch_rules.html.markdown
- website/docs/r/arms_dispatch_rule.html.markdown
> Adds a new resource alicloud_arms_dispatch_rule and datasource alicloud_arms_dispatch_rules

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_open_search_app_groups.go
- alicloud/data_source_alicloud_open_search_app_groups_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_open_search_app_group.go
- alicloud/resource_alicloud_open_search_app_group_test.go
- alicloud/service_alicloud_open_search.go
- website/alicloud.erb
- website/docs/d/open_search_app_groups.html.markdown
- website/docs/r/open_search_app_group.html.markdown
> New Resource alicloud_open_search_app_group  New Datasource alicloud_open_search_app_groups

- alicloud/resource_alicloud_cr_ee_instance.go
bug/alicloud_cr_ee_instance: Fix the problem of import failure in the international station
> resource/alicloud_cr_ee_instance: Fix the problem of import failure in the international station

- alicloud/data_source_alicloud_arms_dispatch_rules.go
- alicloud/resource_alicloud_arms_alert_contact_group_test.go
- alicloud/resource_alicloud_arms_alert_contact_test.go
- alicloud/resource_alicloud_image.go
- alicloud/resource_alicloud_image_copy.go
- alicloud/resource_alicloud_open_search_app_group.go
- website/docs/r/image_copy.html.markdown
> resource/alicloud_image: Adds new attribute delete_auto_snapshot to automatically delete dependence snapshots while deleting image

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_graph_database_db_instances.go
- alicloud/data_source_alicloud_graph_database_db_instances_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_graph_database_db_instance.go
- alicloud/resource_alicloud_graph_database_db_instance_test.go
- alicloud/service_alicloud_gdb.go
- website/alicloud.erb
- website/docs/d/graph_database_db_instances.html.markdown
- website/docs/r/graph_database_db_instance.html.markdown
NewResource `alicloud_graph_database_db_instance`
NewDataSource `alicloud_graph_database_db_instances`
> NewResource `alicloud_graph_database_db_instance`   NewDataSource `alicloud_graph_database_db_instances`

- alicloud/data_source_alicloud_arms_prometheus_alert_rules.go
- alicloud/data_source_alicloud_arms_prometheus_alert_rules_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_arms_alert_contact_test.go
- alicloud/resource_alicloud_arms_prometheus_alert_rule.go
- alicloud/resource_alicloud_arms_prometheus_alert_rule_test.go
- alicloud/service_alicloud_arms.go
- website/alicloud.erb
- website/docs/d/arms_prometheus_alert_rules.html.markdown
- website/docs/r/arms_prometheus_alert_rule.html.markdown
New Datasource `alicloud_arms_prometheus_alert_rules`
> New Resource `alicloud_arms_prometheus_alert_rule` New Datasource `alicloud_arms_prometheus_alert_rules`

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_dbfs_instances.go
- alicloud/data_source_alicloud_dbfs_instances_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_dbfs_instance.go
- alicloud/resource_alicloud_dbfs_instance_test.go
- alicloud/resource_alicloud_open_search_app_group_test.go
- alicloud/service_alicloud_dbfs.go
- website/alicloud.erb
- website/docs/d/dbfs_instances.html.markdown
- website/docs/r/dbfs_instance.html.markdown
New Datasource `alicloud_dbfs_instances`
> New Resource `alicloud_dbfs_instance` New Datasource `alicloud_dbfs_instances`

- website/alicloud.erb
- website/docs/d/common_bandwidth_packages.html.markdown
- website/docs/d/eipanycast_anycast_eip_addresses.html.markdown
- website/docs/r/common_bandwidth_package.html.markdown
- website/docs/r/common_bandwidth_package_attachment.html.markdown
- website/docs/r/eipanycast_anycast_eip_address.html.markdown
- website/docs/r/eipanycast_anycast_eip_address_attachment.html.markdown
doc/eipanycast_anycast_eip_address: Adjust document position
> doc/common_bandwidth_package: Adjust document position doc/eipanycast_anycast_eip_address: Adjust document position

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_eais_instances.go
- alicloud/data_source_alicloud_eais_instances_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_eais_instance.go
- alicloud/resource_alicloud_eais_instance_test.go
- alicloud/service_alicloud_eais.go
- website/alicloud.erb
- website/docs/d/eais_instances.html.markdown
- website/docs/r/eais_instance.html.markdown
New Datasource `alicloud_eais_instances`
> New Resource `alicloud_eais_instance` New Datasource `alicloud_eais_instances`

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_cloudauth_face_configs.go
- alicloud/data_source_alicloud_cloudauth_face_configs_test.go
- alicloud/data_source_alicloud_dbfs_instances_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cloudauth_face_config.go
- alicloud/resource_alicloud_cloudauth_face_config_test.go
- alicloud/resource_alicloud_dbfs_instance.go
- alicloud/resource_alicloud_dbfs_instance_test.go
- alicloud/service_alicloud_cloudauth.go
- alicloud/service_alicloud_dbfs.go
- website/alicloud.erb
- website/docs/d/cloudauth_face_configs.html.markdown
- website/docs/index.html.markdown
- website/docs/r/cloudauth_face_config.html.markdown
> New Resource alicloud_cloudauth_face_config  New Datasource alicloud_cloudauth_face_configs

- alicloud/data_source_alicloud_db_instances_test.go
- alicloud/data_source_alicloud_rds_accounts_test.go
- alicloud/resource_alicloud_rds_account.go
- alicloud/resource_alicloud_rds_parameter_group_test.go
> resource/alicloud_rds_account: Adds UnlockAccount action to fix the Lock error when deleting PostgreSQL database account

- alicloud/resource_alicloud_route_table.go
> resource/alicloud_route_table: Fixes the OperationConflict error when creating a new table

- alicloud/data_source_alicloud_cdn_real_time_log_deliveries_test.go
- alicloud/data_source_alicloud_db_instances_test.go
- alicloud/resource_alicloud_amqp_binding_test.go
- alicloud/resource_alicloud_db_backup_policy_test.go
- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_dfs_access_group_test.go
- alicloud/resource_alicloud_drds_instance_test.go
- alicloud/resource_alicloud_kvstore_instance_test.go
> resource/alicloud_db_instance: Sets the attribute zone_id_slave_a to computed to fix the diff error

- alicloud/provider.go
- alicloud/resource_alicloud_api_gateway_vpc_access_test.go
- alicloud/resource_alicloud_bastionhost_instance_test.go
- alicloud/resource_alicloud_drds_instance_test.go
- alicloud/resource_alicloud_elasticsearch_instance_test.go
- alicloud/resource_alicloud_ram_account_alias_test.go
- alicloud/resource_alicloud_ram_group_test.go
- alicloud/resource_alicloud_ram_policy_test.go
- alicloud/resource_alicloud_ram_role_test.go
- alicloud/resource_alicloud_yundun_dbaudit_instance_test.go
- website/docs/index.html.markdown
> provider: Enlarges the read_timeout and connect_timeout to 60s

- alicloud/connectivity/config.go
- go.mod
- go.sum
- vendor/github.com/alibabacloud-go/tea-roa/client/client.go
- vendor/github.com/alibabacloud-go/tea-rpc/client/client.go
- vendor/modules.txt
> sdk: Upgrades the sdk tea-rpc to 1.2.0 and tea-roa to 1.3.0 to support parameters SourceIp and SecureTransport

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/data_source_alicloud_imp_app_templates.go
- alicloud/data_source_alicloud_imp_app_templates_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_imp_app_template.go
- alicloud/resource_alicloud_imp_app_template_test.go
- alicloud/service_alicloud_imp.go
- ci/pipeline-cn.yml
- ci/pipeline.yml
- website/alicloud.erb
- website/docs/d/imp_app_templates.html.markdown
- website/docs/r/imp_app_template.html.markdown
> Adds a new resource alicloud_imp_app_template and datasource alicloud_imp_app_templates

- website/docs/r/cloud_firewall_control_policy_order.html.markdown
> Doc/cloud_firewall: fix typo in cloud firewall demo code

- alicloud/connectivity/regions.go
- alicloud/resource_alicloud_cs_edge_kubernetes.go
- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go
- alicloud/resource_alicloud_cs_kubernetes_test.go
- alicloud/resource_alicloud_cs_managed_kubernetes.go
- alicloud/resource_alicloud_cs_managed_kubernetes_test.go
- alicloud/resource_alicloud_db_readonly_instance_test.go
- alicloud/resource_alicloud_db_readwrite_splitting_connection_test.go
- alicloud/resource_alicloud_imp_app_template_test.go
> resource/alicloud_cs_edge_kubernetes: Fixes the diff error caused by attribute resource_group_id; Improves the some testcases

- alicloud/data_source_alicloud_cassandra_data_centers_test.go
- alicloud/data_source_alicloud_cen_region_route_entries_test.go
- alicloud/data_source_alicloud_cen_transit_router_route_entries_test.go
- alicloud/data_source_alicloud_cen_transit_router_route_table_propagations_test.go
- alicloud/data_source_alicloud_cen_vbr_health_checks_test.go
- alicloud/data_source_alicloud_cms_monitor_group_instances_test.go
- alicloud/provider_test.go
- alicloud/resource_alicloud_cs_serverless_kubernetes.go
> resource/alicloud_cs_serverless_kubernetes: Setting the attribute vswitch_ids after getting the resource

- alicloud/resource_alicloud_bastionhost_host_account_test.go
- alicloud/service_alicloud_yundun_bastionhost.go
> resource/alicloud_bastionhost_user_attachment: Fixes the Commodity.BizError.InvalidStatus error while deleting the resource

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/data_source_alicloud_mhub_products_test.go
- alicloud/data_source_alicloud_security_group_rules_test.go
- alicloud/data_source_alicloud_service_mesh_service_meshes.go
- alicloud/data_source_alicloud_service_mesh_service_meshes_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cen_transit_router_test.go
- alicloud/resource_alicloud_mhub_product_test.go
- alicloud/resource_alicloud_service_mesh_service_mesh.go
- alicloud/resource_alicloud_service_mesh_service_mesh_test.go
- alicloud/service_alicloud_servicemesh.go
- website/alicloud.erb
- website/docs/d/service_mesh_service_meshes.html.markdown
- website/docs/r/service_mesh_service_mesh.html.markdown
New Resource `alicloud_service_mesh_service_mesh`
New Datasource `alicloud_service_mesh_service_meshes`
> New Resource `alicloud_service_mesh_service_mesh` New Datasource `alicloud_service_mesh_service_meshes`

- alicloud/data_source_alicloud_cloud_sso_groups.go
- alicloud/data_source_alicloud_cloud_sso_groups_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cloud_sso_group.go
- alicloud/resource_alicloud_cloud_sso_group_test.go
- alicloud/service_alicloud_cloudsso.go
- website/alicloud.erb
- website/docs/d/cloud_sso_groups.html.markdown
- website/docs/r/cloud_sso_group.html.markdown
New Datasource `alicloud_cloud_sso_groups`
> New Resource `alicloud_cloud_sso_group` New Datasource `alicloud_cloud_sso_groups`

- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_kvstore_instance.go
> resource/alicloud_db_instance,alicloud_kvstore_instance: Improves the waiting time after modifying the security_ips

- alicloud/provider.go
- alicloud/resource_alicloud_waf_protection_module.go
- alicloud/resource_alicloud_waf_protection_module_test.go
- alicloud/service_alicloud_waf_openapi.go
- website/alicloud.erb
- website/docs/r/waf_protection_module.html.markdown
New Resource `alicloud_waf_protection_module`
> New Resource `alicloud_waf_protection_module`

- alicloud/data_source_alicloud_vpc_traffic_mirror_sessions.go
- alicloud/data_source_alicloud_vpc_traffic_mirror_sessions_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_vpc_traffic_mirror_session.go
- alicloud/resource_alicloud_vpc_traffic_mirror_session_test.go
- alicloud/service_alicloud_vpc.go
- website/alicloud.erb
- website/docs/d/vpc_traffic_mirror_sessions.html.markdown
- website/docs/r/vpc_traffic_mirror_session.html.markdown
New Resource `alicloud_vpc_traffic_mirror_session`
New Datasource `alicloud_vpc_traffic_mirror_sessions`
> New Resource `alicloud_vpc_traffic_mirror_session` New Datasource `alicloud_vpc_traffic_mirror_sessions`

- alicloud/connectivity/config.go
- alicloud/data_source_alicloud_gpdb_accounts.go
- alicloud/data_source_alicloud_gpdb_accounts_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_gpdb_account.go
- alicloud/resource_alicloud_gpdb_account_test.go
- alicloud/resource_alicloud_gpdb_elastic_instance_test.go
- alicloud/service_alicloud_gpdb.go
- website/alicloud.erb
- website/docs/d/gpdb_accounts.html.markdown
- website/docs/r/gpdb_account.html.markdown
New Datasource `alicloud_gpdb_accounts`
> New Resource `alicloud_gpdb_account` New Datasource `alicloud_gpdb_accounts`

- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_vpc_ipv6_gateways.go
- alicloud/data_source_alicloud_vpc_ipv6_gateways_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_vpc_ipv6_gateway.go
- alicloud/resource_alicloud_vpc_ipv6_gateway_test.go
- alicloud/service_alicloud_vpc.go
- website/alicloud.erb
- website/docs/d/vpc_ipv6_gateways.html.markdown
- website/docs/r/vpc_ipv6_gateway.html.markdown
New Resource `alicloud_vpc_ipv6_gateway` 
New Datasource `alicloud_vpc_ipv6_gateways`
> New Resource `alicloud_vpc_ipv6_gateway`   New Datasource `alicloud_vpc_ipv6_gateways`

- alicloud/data_source_alicloud_vpc_ipv6_addresses.go
- alicloud/data_source_alicloud_vpc_ipv6_addresses_test.go
- alicloud/data_source_alicloud_vpc_ipv6_egress_rules.go
- alicloud/data_source_alicloud_vpc_ipv6_egress_rules_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_vpc_ipv6_egress_rule.go
- alicloud/resource_alicloud_vpc_ipv6_egress_rule_test.go
- alicloud/service_alicloud_vpc.go
- website/alicloud.erb
- website/docs/d/vpc_ipv6_addresses.html.markdown
- website/docs/d/vpc_ipv6_egress_rules.html.markdown
- website/docs/r/vpc_ipv6_egress_rule.html.markdown
New Resource `alicloud_vpc_ipv6_egress_rule`
New Datasource `alicloud_vpc_ipv6_egress_rules`
New Datasource `alicloud_vpc_ipv6_addresses`
> New Resource `alicloud_vpc_ipv6_egress_rule` New Datasource `alicloud_vpc_ipv6_egress_rules` New Datasource `alicloud_vpc_ipv6_addresses`

- alicloud/resource_alicloud_ecs_network_interface.go
> resource/alicloud_ecs_network_interface: Add delete error retry code `InvalidOperation.Conflict`

- alicloud/resource_alicloud_cloud_storage_gateway_gateway_smb_user.go
- alicloud/service_alicloud_sgw.go
- ci/tasks/run.sh
> resource/alicloud_cloud_storage_gateway_gateway_smb_user: Adds waiting codes to wait the task is completed

- alicloud/data_source_alicloud_alb_server_groups.go
- alicloud/data_source_alicloud_alb_server_groups_test.go
- alicloud/data_source_alicloud_cms_dynamic_tag_groups_test.go
- website/docs/d/alb_server_groups.html.markdown
- website/docs/r/alb_server_group.html.markdown
> datasource/alicloud_alb_server_groups: Fix the issue of `enable_details` export error

- alicloud/data_source_alicloud_vpc_ipv6_internet_bandwidths.go
- alicloud/data_source_alicloud_vpc_ipv6_internet_bandwidths_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_vpc_ipv6_internet_bandwidth.go
- alicloud/resource_alicloud_vpc_ipv6_internet_bandwidth_test.go
- alicloud/service_alicloud_vpc.go
- website/alicloud.erb
- website/docs/d/vpc_ipv6_internet_bandwidths.html.markdown
- website/docs/r/vpc_ipv6_internet_bandwidth.html.markdown
New Resource `alicloud_vpc_ipv6_internet_bandwidth` 
New Datasource `alicloud_vpc_ipv6_internet_bandwidths`
> New Resource `alicloud_vpc_ipv6_internet_bandwidth` New Datasource `alicloud_vpc_ipv6_internet_bandwidths`

- alicloud/data_source_alicloud_simple_application_server_firewall_rules.go
- alicloud/data_source_alicloud_simple_application_server_firewall_rules_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_simple_application_server_firewall_rule.go
- alicloud/resource_alicloud_simple_application_server_firewall_rule_test.go
- alicloud/service_alicloud_swas_open.go
- website/alicloud.erb
- website/docs/d/simple_application_server_firewall_rules.html.markdown
- website/docs/r/simple_application_server_firewall_rule.html.markdown
New Resource `alicloud_simple_application_server_firewall_rule`
New Datasource `alicloud_simple_application_server_firewall_rules`
> New Resource `alicloud_simple_application_server_firewall_rule`    New Datasource `alicloud_simple_application_server_firewall_rules` 

- alicloud/resource_alicloud_cms_monitor_group_instances.go
- alicloud/service_alicloud_cms.go
… be imported when the number of instances exceeds 30
> bug/alicloud_cms_monitor_group_instances: Fix the problem that cannot be imported when the number of instances exceeds 30

- alicloud/data_source_alicloud_pvtz_endpoints.go
- alicloud/data_source_alicloud_pvtz_endpoints_test.go
- alicloud/data_source_alicloud_pvtz_resolver_zones.go
- alicloud/data_source_alicloud_pvtz_resolver_zones_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_pvtz_endpoint.go
- alicloud/resource_alicloud_pvtz_endpoint_test.go
- alicloud/service_alicloud_pvtz.go
- website/alicloud.erb
- website/docs/d/pvtz_endpoints.html.markdown
- website/docs/d/pvtz_resolver_zones.html.markdown
- website/docs/r/pvtz_endpoint.html.markdown
New Datasource `alicloud_pvtz_endpoints`
New Datasource `alicloud_pvtz_resolver_zones`
> New Resource `alicloud_pvtz_endpoint`    New Datasource `alicloud_pvtz_endpoints`     New Datasource `alicloud_pvtz_resolver_zones`

- alicloud/data_source_alicloud_pvtz_rules.go
- alicloud/data_source_alicloud_pvtz_rules_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_pvtz_rule.go
- alicloud/resource_alicloud_pvtz_rule_attachment.go
- alicloud/resource_alicloud_pvtz_rule_attachment_test.go
- alicloud/resource_alicloud_pvtz_rule_test.go
- alicloud/service_alicloud_pvtz.go
- website/alicloud.erb
- website/docs/d/pvtz_rules.html.markdown
- website/docs/r/pvtz_rule.html.markdown
- website/docs/r/pvtz_rule_attachment.html.markdown
New Resource `alicloud_pvtz_rule_attachment`
New Datasource `alicloud_pvtz_rules`
> New Resource `alicloud_pvtz_rule` New Resource `alicloud_pvtz_rule_attachment` New Datasource `alicloud_pvtz_rules`

- alicloud/data_source_alicloud_simple_application_server_custom_images.go
- alicloud/data_source_alicloud_simple_application_server_custom_images_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_simple_application_server_custom_image.go
- alicloud/resource_alicloud_simple_application_server_custom_image_test.go
- alicloud/service_alicloud_swas_open.go
- website/alicloud.erb
- website/docs/d/simple_application_server_custom_images.html.markdown
- website/docs/r/simple_application_server_custom_image.html.markdown
New Resource `alicloud_simple_application_server_custom_image`
New Datasource `alicloud_simple_application_server_custom_images`
> New Resource `alicloud_simple_application_server_custom_image`  New Datasource `alicloud_simple_application_server_custom_images`

- alicloud/common.go
- alicloud/data_source_alicloud_cloud_storage_gateway_stocks.go
- alicloud/data_source_alicloud_cloud_storage_gateway_stocks_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/cloud_storage_gateway_stocks.html.markdown
data_source_alicloud_cloud_storage_gateway_zones
> New Datadource `data_source_alicloud_cloud_storage_gateway_stocks`

- alicloud/data_source_alicloud_cloud_storage_gateway_gateway_cache_disks.go
- alicloud/data_source_alicloud_cloud_storage_gateway_gateway_cache_disks_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cloud_storage_gateway_gateway_cache_disk.go
- alicloud/resource_alicloud_cloud_storage_gateway_gateway_cache_disk_test.go
- alicloud/service_alicloud_sgw.go
- website/alicloud.erb
- website/docs/d/cloud_storage_gateway_gateway_cache_disks.html.markdown
- website/docs/r/cloud_storage_gateway_gateway_cache_disk.html.markdown
New Resource `alicloud_cloud_storage_gateway_gateway_cache_disk` 
New Datasource `alicloud_cloud_storage_gateway_gateway_cache_disks`
> New Resource `alicloud_cloud_storage_gateway_gateway_cache_disk` New Datasource `alicloud_cloud_storage_gateway_gateway_cache_disks`

- alicloud/provider.go
- alicloud/resource_alicloud_cloud_storage_gateway_gateway_logging.go
- alicloud/resource_alicloud_cloud_storage_gateway_gateway_logging_test.go
- alicloud/service_alicloud_sgw.go
- website/alicloud.erb
- website/docs/r/cloud_storage_gateway_gateway_logging.html.markdown
New Resource `alicloud_cloud_storage_gateway_gateway_logging`
> New Resource `alicloud_cloud_storage_gateway_gateway_logging`

- alicloud/data_source_alicloud_msc_sub_contacts.go
- alicloud/resource_alicloud_msc_sub_contact.go
- alicloud/resource_alicloud_msc_sub_contact_test.go
- website/docs/d/msc_sub_contacts.html.markdown
- website/docs/r/msc_sub_contact.html.markdown
resource/alicloud_msc_sub_contact: Support setting Chinese contact name,Change position to take Others to Other
> resource/alicloud_msc_sub_contact: Support setting Chinese contact name,Change `position` to take `Others` to `Other`

- alicloud/data_source_alicloud_cloud_storage_gateway_gateway_block_volumes.go
- alicloud/data_source_alicloud_cloud_storage_gateway_gateway_block_volumes_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cloud_storage_gateway_gateway_block_volume.go
- alicloud/resource_alicloud_cloud_storage_gateway_gateway_block_volume_test.go
- alicloud/resource_alicloud_ram_role.go
- alicloud/service_alicloud_sgw.go
- website/alicloud.erb
- website/docs/d/cloud_storage_gateway_gateway_block_volumes.html.markdown
- website/docs/r/cloud_storage_gateway_gateway_block_volume.html.markdown
New Datasource `alicloud_cloud_storage_gateway_gateway_block_volumes`
> New Resource `alicloud_cloud_storage_gateway_gateway_block_volume` New Datasource `alicloud_cloud_storage_gateway_gateway_block_volumes`

- alicloud/data_source_alicloud_direct_mail_tags.go
- alicloud/data_source_alicloud_direct_mail_tags_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_direct_mail_tag.go
- alicloud/resource_alicloud_direct_mail_tag_test.go
- alicloud/service_alicloud_dm.go
- website/alicloud.erb
- website/docs/d/direct_mail_tags.html.markdown
- website/docs/r/direct_mail_tag.html.markdown
New Resource `alicloud_direct_mail_tag`
New Datasource `alicloud_direct_mail_tags`
> New Resource `alicloud_direct_mail_tag`  New Datasource `alicloud_direct_mail_tags`

- alicloud/data_source_alicloud_cloud_storage_gateway_gateway_file_shares.go
- alicloud/data_source_alicloud_cloud_storage_gateway_gateway_file_shares_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cloud_storage_gateway_gateway_file_share.go
- alicloud/resource_alicloud_cloud_storage_gateway_gateway_file_share_test.go
- alicloud/service_alicloud_sgw.go
- website/alicloud.erb
- website/docs/d/cloud_storage_gateway_gateway_file_shares.html.markdown
- website/docs/r/cloud_storage_gateway_gateway_file_share.html.markdown
New Datasource `alicloud_cloud_storage_gateway_gateway_file_shares`
> New Resource `alicloud_cloud_storage_gateway_gateway_file_share` New Datasource `alicloud_cloud_storage_gateway_gateway_file_shares`

- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_slb_listener.go
> resource/alicloud_slb_listener: Fixes the importing diff error caused by delete_protection_validation and health_check_http_code default value

- alicloud/data_source_alicloud_click_house_db_clusters.go
- alicloud/data_source_alicloud_click_house_db_clusters_test.go
- alicloud/resource_alicloud_click_house_db_cluster.go
- alicloud/resource_alicloud_click_house_db_cluster_test.go
- alicloud/service_alicloud_clickhouse.go
- website/docs/d/click_house_db_clusters.html.markdown
- website/docs/r/click_house_db_cluster.html.markdown
resource/cloud_storage_gateway_gateway_file_share_test:  Add `db_cluster_access_white_list` attribute.
> resource/alicloud_click_house_db_cluster:  Add `db_cluster_access_white_list` attribute.

- alicloud/resource_alicloud_config_aggregate_config_rule.go
- alicloud/resource_alicloud_config_aggregate_config_rule_test.go
- alicloud/resource_alicloud_config_configuration_recorder.go
- alicloud/resource_alicloud_config_configuration_recorder_test.go
- alicloud/service_alicloud_config.go
- website/docs/r/config_aggregate_compliance_pack.html.markdown
- website/docs/r/config_aggregate_config_rule.html.markdown
- website/docs/r/config_aggregator.html.markdown
- website/docs/r/config_compliance_pack.html.markdown
- website/docs/r/config_configuration_recorder.html.markdown
- website/docs/r/config_delivery_channel.html.markdown
- website/docs/r/config_rule.html.markdown
resource/config_aggregate_config_rule: Support configuring the specified field
> resource/config_aggregate_config_rule: Support updating the filed status

- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_oos_applications.go
- alicloud/data_source_alicloud_oos_applications_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_oos_application.go
- alicloud/resource_alicloud_oos_application_test.go
- alicloud/service_alicloud_oos.go
- website/alicloud.erb
- website/docs/d/oos_applications.html.markdown
- website/docs/r/oos_application.html.markdown
New DataSource `alicloud_oos_applications`
> New Resource `alicloud_oos_application` New DataSource `alicloud_oos_applications`

- alicloud/data_source_alicloud_alb_security_policies.go
- alicloud/data_source_alicloud_alb_security_policies_test.go
data_source/alb_security_policies: Fixing query errors; Refine test cases.
> data_source/alb_security_policies: Fixing query errors; Refine test cases.

- alicloud/resource_alicloud_config_aggregate_compliance_pack.go
- alicloud/resource_alicloud_config_aggregate_compliance_pack_test.go
- website/docs/r/config_aggregate_compliance_pack.html.markdown
resource/config_aggregate_compliance_pack: Support updating the filed aggregate_compliance_pack_name
> resource/config_aggregate_compliance_pack: Support updating the filed aggregate_compliance_pack_name

- alicloud/resource_alicloud_instance.go
- alicloud/resource_alicloud_instance_test.go
- website/docs/r/instance.html.markdown
- website/docs/r/network_interface.html.markdown
resource/alicloud_instance: Support configuring the filed secondary_private_ip_address_count
> resource/alicloud_instance: Support configuring the filed secondary_private_ip_address_count

- alicloud/data_source_alicloud_eci_virtual_nodes.go
- alicloud/data_source_alicloud_eci_virtual_nodes_test.go
- alicloud/data_source_alicloud_eci_zones.go
- alicloud/data_source_alicloud_eci_zones_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_eci_virtual_node.go
- alicloud/resource_alicloud_eci_virtual_node_test.go
- alicloud/service_alicloud_eci.go
- website/alicloud.erb
- website/docs/d/eci_virtual_nodes.html.markdown
- website/docs/d/eci_zones.html.markdown
- website/docs/r/eci_virtual_node.html.markdown
New Datasource `alicloud_eci_virtual_nodes`
New Datasource `alicloud_eci_zones`
> New Resource `alicloud_eci_virtual_node` New Datasource `alicloud_eci_virtual_nodes` New Datasource `alicloud_eci_zones`

- alicloud/resource_alicloud_ecs_disk.go
- alicloud/resource_alicloud_ecs_disk_test.go
> resource/alicloud_ecs_disk: Fixes the InvalidParameter error when modifying the disk charge type

- alicloud/data_source_alicloud_ros_regions.go
- alicloud/data_source_alicloud_ros_regions_test.go
- alicloud/data_source_alicloud_ros_stack_instances.go
- alicloud/data_source_alicloud_ros_stack_instances_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_ros_stack_instance.go
- alicloud/resource_alicloud_ros_stack_instance_test.go
- alicloud/service_alicloud_ros.go
- website/alicloud.erb
- website/docs/d/ros_regions.html.markdown
- website/docs/d/ros_stack_instances.html.markdown
- website/docs/r/ros_stack_instance.html.markdown
New Resource `alicloud_ros_stack_instance` 
New Datasource `alicloud_ros_stack_instances`
> New Resource `alicloud_ros_stack_instance` New Datasource `alicloud_ros_stack_instances`

- alicloud/provider.go
- alicloud/service_alicloud_ecs.go
- website/docs/index.html.markdown
> provider: Adds TF_APPEND_USER_AGENT environment variables to support setting custom user-agent

- alicloud/resource_alicloud_polardb_cluster.go
- alicloud/service_alicloud_polardb.go
> resource/alicloud_polardb_db_instance: Fixes the setting security_ips  bug without filtering hidden values

- alicloud/resource_alicloud_pvtz_zone.go
- alicloud/resource_alicloud_pvtz_zone_test.go
- alicloud/service_alicloud_pvtz.go
- website/docs/r/pvtz_zone.html.markdown
resource/alicloud_pvtz_zone: Support updating the filed user_info and sync_status
> resource/alicloud_pvtz_zone: Support updating the filed user_info and sync_status

- alicloud/data_source_alicloud_ecs_dedicated_host_clusters.go
- alicloud/data_source_alicloud_ecs_dedicated_host_clusters_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_ecs_dedicated_host_cluster.go
- alicloud/resource_alicloud_ecs_dedicated_host_cluster_test.go
- alicloud/service_alicloud_ecs.go
- website/alicloud.erb
- website/docs/d/ecs_dedicated_host_clusters.html.markdown
- website/docs/r/ecs_dedicated_host_cluster.html.markdown
New Resource `alicloud_ecs_dedicated_host_cluster`
New Datasource `alicloud_ecs_dedicated_host_clusters`
> New Resource `alicloud_ecs_dedicated_host_cluster` New Datasource `alicloud_ecs_dedicated_host_clusters`

- alicloud/data_source_alicloud_oos_application_groups.go
- alicloud/data_source_alicloud_oos_application_groups_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_oos_application_group.go
- alicloud/resource_alicloud_oos_application_group_test.go
- alicloud/service_alicloud_oos.go
- website/alicloud.erb
- website/docs/d/oos_application_groups.html.markdown
- website/docs/r/oos_application_group.html.markdown
New Resource `alicloud_oos_application_group`
New Datasource `alicloud_oos_application_groups`
> New Resource `alicloud_oos_application_group` New Datasource `alicloud_oos_application_groups`

- alicloud/resource_alicloud_ga_accelerator.go
- alicloud/service_alicloud_ga.go
> resource/alicloud_ga_accelerator: Adds new attributes renewal_status and auto_renew_duration to supports auto renew

- alicloud/resource_alicloud_ga_bandwidth_package.go
- alicloud/resource_alicloud_ga_ip_set.go
- website/docs/r/ga_accelerator.html.markdown
> resource/alicloud_ga_bandwidth_package,alicloud_ga_ip_set: Fix the GreaterThanGa.IpSetBandwidth error

- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_dts_consumer_channels.go
- alicloud/data_source_alicloud_dts_consumer_channels_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_dts_consumer_channel.go
- alicloud/resource_alicloud_dts_consumer_channel_test.go
- alicloud/service_alicloud_dts.go
- website/alicloud.erb
- website/docs/d/dts_consumer_channels.html.markdown
- website/docs/r/dts_consumer_channel.html.markdown
New DataSource `alicloud_dts_consumer_channels`
> New Resource `alicloud_dts_consumer_channel` New DataSource `alicloud_dts_consumer_channels`

- alicloud/connectivity/client.go
- alicloud/resource_alicloud_ga_accelerator.go
> resource/alicloud_ga_accelerator: Fixes the InvalidRegionId error when getting the its endpoint

- alicloud/data_source_alicloud_oos_application_groups.go
- alicloud/data_source_alicloud_oos_application_groups_test.go
- website/docs/d/oos_application_groups.html.markdown
data_source/oos_application_groups_test: fix test case.
docs/oos_application_groups: add the `update_time` parameter.
> datasource/alicloud_oos_application_groups: Adds output variable `update_time`.

- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_oos_patch_baselines.go
- alicloud/data_source_alicloud_oos_patch_baselines_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_oos_patch_baseline.go
- alicloud/resource_alicloud_oos_patch_baseline_test.go
- alicloud/service_alicloud_oos.go
- website/alicloud.erb
- website/docs/d/oos_patch_baselines.html.markdown
- website/docs/r/oos_patch_baseline.html.markdown
New Resource `alicloud_oos_patch_baseline`
New Datasource `alicloud_oos_patch_baselines`
> New Resource `alicloud_oos_patch_baseline` New Datasource `alicloud_oos_patch_baselines`

- alicloud/resource_alicloud_cloud_sso_user.go
- website/docs/r/cloud_sso_directory.html.markdown
- website/docs/r/cloud_sso_user.html.markdown
doc/alicloud_cloud_sso_directory: Document optimization
> doc/alicloud_cloud_sso_user: Document optimization doc/alicloud_cloud_sso_directory: Document optimization

- alicloud/resource_alicloud_ram_user.go
Update the error message to be more clear and  grammatically correct
> resource/alicloud_ram_user: Update the error message

- alicloud/provider.go
- alicloud/resource_alicloud_oos_service_setting.go
- alicloud/resource_alicloud_oos_service_setting_test.go
- alicloud/service_alicloud_oos.go
- website/alicloud.erb
- website/docs/r/oos_service_setting.html.markdown
Mew Resource `alicloud_oos_service_setting`
> New Resource `alicloud_oos_service_setting`

- alicloud/data_source_alicloud_oos_parameters.go
- alicloud/data_source_alicloud_oos_parameters_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_oos_parameter.go
- alicloud/resource_alicloud_oos_parameter_test.go
- alicloud/service_alicloud_oos.go
- website/alicloud.erb
- website/docs/d/oos_parameters.html.markdown
- website/docs/r/oos_parameter.html.markdown
New Resource `alicloud_oos_parameter` New Datasource `alicloud_oos_parameters`
> New Resource `alicloud_oos_parameter` New Datasource `alicloud_oos_parameters`

- alicloud/data_source_alicloud_oos_state_configurations.go
- alicloud/data_source_alicloud_oos_state_configurations_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_oos_state_configuration.go
- alicloud/resource_alicloud_oos_state_configuration_test.go
- alicloud/service_alicloud_oos.go
- website/alicloud.erb
- website/docs/d/oos_state_configurations.html.markdown
- website/docs/r/oos_application.html.markdown
- website/docs/r/oos_state_configuration.html.markdown
New Datasource `alicloud_oos_state_configurations`
> New Resource `alicloud_oos_state_configuration` New Datasource `alicloud_oos_state_configurations`

- alicloud/data_source_alicloud_oos_secret_parameters.go
- alicloud/data_source_alicloud_oos_secret_parameters_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_oos_secret_parameter.go
- alicloud/resource_alicloud_oos_secret_parameter_test.go
- alicloud/service_alicloud_oos.go
- website/alicloud.erb
- website/docs/d/oos_secret_parameters.html.markdown
- website/docs/r/oos_secret_parameter.html.markdown
New Resource `alicloud_oos_secret_parameter` 
New Datasource `alicloud_oos_secret_parameters`
> New Resource `alicloud_oos_secret_parameter` New Datasource `alicloud_oos_secret_parameters`

- alicloud/resource_alicloud_amqp_instance.go
> resource/alicloud_amqp_instance: Supports create instance using international account

- alicloud/resource_alicloud_cloud_firewall_control_policy.go
- website/docs/r/cloud_firewall_control_policy.html.markdown
doc/alicloud_cloud_firewall_control_policy: document optimization
> doc/alicloud_cloud_firewall_control_policy: document optimization

- alicloud/data_source_alicloud_cloud_sso_service.go
- alicloud/data_source_alicloud_cloud_sso_service_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_vswitch_test.go
- website/alicloud.erb
- website/docs/d/cloud_sso_service.html.markdown
New Datasource `cloud_sso_service`
> New Datasource `cloud_sso_service`

- alicloud/provider.go
- alicloud/resource_alicloud_cloud_sso_access_assignment.go
- alicloud/resource_alicloud_cloud_sso_access_configuration.go
- alicloud/resource_alicloud_cloud_sso_access_configuration_provisioning.go
- alicloud/resource_alicloud_cloud_sso_access_configuration_provisioning_test.go
- alicloud/resource_alicloud_cloud_sso_directory.go
- alicloud/service_alicloud_cloudsso.go
- website/alicloud.erb
- website/docs/r/cloud_sso_access_assignment.html.markdown
- website/docs/r/cloud_sso_access_configuration_provisioning.html.markdown
New Resource `cloud_sso_access_configuration_provisioning`
> New Resource `cloud_sso_access_configuration_provisioning`

- alicloud/data_source_alicloud_mongodb_accounts.go
- alicloud/data_source_alicloud_mongodb_accounts_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_mongodb_account.go
- alicloud/resource_alicloud_mongodb_account_test.go
- alicloud/service_alicloud_mongodb.go
- website/alicloud.erb
- website/docs/d/mongodb_accounts.html.markdown
- website/docs/r/mongodb_account.html.markdown
New Resource `alicloud_mongodb_account`
New Datasource `alicloud_mongodb_accounts`
> New Resource `alicloud_mongodb_account` New Datasource `alicloud_mongodb_accounts`

- alicloud/provider.go
- alicloud/resource_alicloud_ecs_session_manager_status.go
- alicloud/resource_alicloud_ecs_session_manager_status_test.go
- alicloud/service_alicloud_ecs.go
- website/alicloud.erb
- website/docs/r/ecs_session_manager_status.html.markdown
New Resource `ecs_session_manager_status`
> New Resource `ecs_session_manager_status`

- alicloud/resource_alicloud_cr_endpoint_acl_policy.go
- scripts/schema_test.go
- website/docs/r/cr_endpoint_acl_policy.html.markdown
resource/alicloud_cr_endpoint_acl_policy : Added error retry code `SLB_SERVICE_ERROR`
> resource/alicloud_cr_endpoint_acl_policy : Added error retry code `SLB_SERVICE_ERROR`

- alicloud/data_source_alicloud_mongodb_sharding_network_public_addresses.go
- alicloud/data_source_alicloud_mongodb_sharding_network_public_addresses_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_mongodb_serverless_instance.go
- alicloud/resource_alicloud_mongodb_sharding_network_public_address.go
- alicloud/resource_alicloud_mongodb_sharding_network_public_address_test.go
- alicloud/resource_alicloud_rds_clone_db_instance.go
- alicloud/resource_alicloud_ros_stack_instance.go
- alicloud/service_alicloud_mongodb.go
- website/alicloud.erb
- website/docs/d/mongodb_sharding_network_public_addresses.html.markdown
- website/docs/r/mongodb_sharding_network_public_address.html.markdown
New Resource `alicloud_mongodb_sharding_network_public_address`
New Datasource `alicloud_mongodb_sharding_network_addresses`
> New Resource `alicloud_mongodb_sharding_network_public_address`; New Datasource `alicloud_mongodb_sharding_network_addresses`

- website/docs/r/cen_transit_router.html.markdown
doc/alicloud_cen_transit_router: Optimize document
> doc/alicloud_cen_transit_router: Optimize document

- alicloud/resource_alicloud_cr_chart_repository.go
- alicloud/resource_alicloud_slb_acl.go
- alicloud/resource_alicloud_slb_acl_test.go
- alicloud/service_alicloud_slb.go
resource/alicloud_slb_acl: Fixed the limit on the number of IP entries; Updates its dependence SDK.
> resource/alicloud_slb_acl: Fixed the limit on the number of IP entries; Updates its dependence SDK.

- alicloud/connectivity/config.go
- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_ga_acls.go
- alicloud/data_source_alicloud_ga_acls_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cr_chart_repository.go
- alicloud/resource_alicloud_ga_acl.go
- alicloud/resource_alicloud_ga_acl_attachment.go
- alicloud/resource_alicloud_ga_acl_attachment_test.go
- alicloud/resource_alicloud_ga_acl_test.go
- alicloud/service_alicloud_ga.go
- website/alicloud.erb
- website/docs/d/ga_acls.html.markdown
- website/docs/r/ga_acl.html.markdown
- website/docs/r/ga_acl_attachment.html.markdown
New Datasource `alicloud_ga_acls`
> New resource `alicloud_ga_acl` New Datasource `alicloud_ga_acls`  New Resource `alicloud_ga_acl_attachment`

- alicloud/resource_alicloud_cloud_sso_access_configuration.go
- alicloud/resource_alicloud_mongodb_account.go
- website/docs/r/cloud_sso_access_configuration.html.markdown
docs/cloud_sso_access_configuration: Optimize document;
resource/alicloud_cloud_sso_access_configuration: Add `timeouts` configuration;
resource/alicloud_mongodb_account: Fix errors about `timeouts`.
> docs/cloud_sso_access_configuration: Optimize document;

- alicloud/data_source_alicloud_ga_additional_certificates.go
- alicloud/data_source_alicloud_ga_additional_certificates_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_ga_additional_certificate.go
- alicloud/resource_alicloud_ga_additional_certificate_test.go
- alicloud/service_alicloud_ga.go
- website/alicloud.erb
- website/docs/d/ga_additional_certificates.html.markdown
- website/docs/r/ga_additional_certificate.html.markdown
New datasource `alicloud_ga_additional_certificates`
> New Resource `alicloud_ga_additional_certificate` New datasource `alicloud_ga_additional_certificates`

- alicloud/data_source_alicloud_cs_kubernetes_addons_test.go
- alicloud/resource_alicloud_cs_kubernetes_addon.go
- alicloud/resource_alicloud_cs_kubernetes_addon_test.go
- alicloud/service_alicloud_cs.go
fix bug in resource_alicloud_cs_kubernetes_addon_test.go and data_source_alicloud_cs_kubernetes_addons_test.go.
> testcase: Fixes the alicloud_cs_kubernetes_addon test case bug

- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_alidns_custom_lines.go
- alicloud/data_source_alicloud_alidns_custom_lines_test.go
- alicloud/data_source_alicloud_emr_main_versions.go
- alicloud/data_source_alicloud_ga_endpoint_groups_test.go
- alicloud/data_source_alicloud_ga_forwarding_rules_test.go
- alicloud/data_source_alicloud_ga_ip_sets_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_alidns_custom_line.go
- alicloud/resource_alicloud_alidns_custom_line_test.go
- alicloud/resource_alicloud_ga_accelerator_test.go
- alicloud/service_alicloud_alidns.go
- website/alicloud.erb
- website/docs/d/alidns_custom_lines.html.markdown
- website/docs/r/alidns_custom_line.html.markdown
New Datasource `alicloud_alidns_custom_lines`
> New Resource `alicloud_alidns_custom_line` New Datasource `alicloud_alidns_custom_lines`

- alicloud/connectivity/regions.go
- alicloud/provider.go
- alicloud/resource_alicloud_vpc_vbr_ha.go
- alicloud/resource_alicloud_vpc_vbr_ha_test.go
- alicloud/service_alicloud_vpc.go
- website/alicloud.erb
- website/docs/r/vpc_vbr_ha.html.markdown
New Resource `alicloud_vpc_vbr_ha`
> New Resource `alicloud_vpc_vbr_ha`

- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_ros_template_scratches.go
- alicloud/data_source_alicloud_ros_template_scratches_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_ros_template_scratch.go
- alicloud/resource_alicloud_ros_template_scratch_test.go
- alicloud/service_alicloud_ros.go
- website/alicloud.erb
- website/docs/d/ros_template_scratches.html.markdown
- website/docs/r/ros_template_scratch.html.markdown
New Resource `alicloud_ros_template_scratch`
New Datasource `alicloud_ros_template_scratches`
> New Resource `alicloud_ros_template_scratch`; New Datasource `alicloud_ros_template_scratches`

- alicloud/resource_alicloud_cloud_storage_gateway_gateway.go
- website/docs/d/cloud_storage_gateway_gateways.html.markdown
…_type` output parameter conversion
> datasource/alicloud_cloud_storage_gateway_gateways: Optimize `payment_type` output parameter conversion

- alicloud/resource_alicloud_gpdb_elastic_instance.go
- alicloud/service_alicloud_ga.go
- website/docs/d/actiontrails.html.markdown
- website/docs/r/actiontrail_trail.html.markdown
1. resource/ga_bandwidth_package_attachment: fix the attachment while the bandwidth package type is cross domain
2. resource/gpdb_elastic_instance: fix the reference of null pointer issue
> resource/ga_bandwidth_package_attachment: fix the attachment while the bandwidth package type is cross domain

- alicloud/data_source_alicloud_cen_transit_routers.go
- alicloud/data_source_alicloud_cen_transit_routers_test.go
- website/docs/d/cen_transit_routers.html.markdown
datasource/alicloud_cen_transit_routers: Modify the parameter `transit_router_id` to `Optional`
> datasource/alicloud_cen_transit_routers: Modify the parameter `transit_router_id` to `Optional` doc/cen_transit_routers: Optimize documentation

- alicloud/data_source_alicloud_alidns_gtm_instances.go
- alicloud/data_source_alicloud_alidns_gtm_instances_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_alidns_gtm_instance.go
- alicloud/resource_alicloud_alidns_gtm_instance_test.go
- alicloud/service_alicloud_alidns.go
- website/alicloud.erb
- website/docs/d/alidns_gtm_instances.html.markdown
- website/docs/r/alidns_gtm_instance.html.markdown
New Daatsource `alidns_gtm_instances`
> New Resource `alidns_gtm_instance` New Datasource `alidns_gtm_instances`

- alicloud/resource_alicloud_rds_account.go
- website/docs/r/rds_account.html.markdown
> resource/alicloud_rds_account: Fixes the OperationDenied.DBInstanceStatus when deleting rds account

- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_vpc_bgp_groups.go
- alicloud/data_source_alicloud_vpc_bgp_groups_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_havip_test.go
- alicloud/resource_alicloud_vpc_bgp_group.go
- alicloud/resource_alicloud_vpc_bgp_group_test.go
- alicloud/resource_alicloud_vpc_nat_ip_cidr_test.go
- alicloud/resource_alicloud_vpc_nat_ip_test.go
- alicloud/resource_alicloud_vpc_traffic_mirror_filter_egress_rule_test.go
- alicloud/resource_alicloud_vpc_traffic_mirror_filter_ingress_rule_test.go
- alicloud/resource_alicloud_vpc_traffic_mirror_filter_test.go
- alicloud/resource_alicloud_vpn_gateway.go
- alicloud/service_alicloud_vpc.go
- website/alicloud.erb
- website/docs/d/vpc_bgp_groups.html.markdown
- website/docs/r/rds_account.html.markdown
- website/docs/r/vpc_bgp_group.html.markdown
New Resource `alicloud_vpc_bgp_group`;
New dataSource `alicloud_vpc_bgp_groups`.
> New Resource `alicloud_vpc_bgp_group`; New dataSource `alicloud_vpc_bgp_groups`.

- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_nas_snapshots.go
- alicloud/data_source_alicloud_nas_snapshots_test.go
- alicloud/data_source_alicloud_nas_zones.go
- alicloud/data_source_alicloud_nas_zones_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_nas_snapshot.go
- alicloud/resource_alicloud_nas_snapshot_test.go
- alicloud/resource_alicloud_ram_security_preference_test.go
- alicloud/service_alicloud_nas.go
- website/alicloud.erb
- website/docs/d/nas_snapshots.html.markdown
- website/docs/d/nas_zones.html.markdown
- website/docs/r/nas_snapshot.html.markdown
New Datasource `alicloud_nas_snapshots`
datasource/alicloud_nas_zones: Add support for field `file_system_type`
> New Resource `alicloud_nas_snapshot` New Datasource `alicloud_nas_snapshots` datasource/alicloud_nas_zones: Add support for field `file_system_type`

- alicloud/common.go
- alicloud/data_source_alicloud_cloud_storage_gateway_storage_bundles.go
- alicloud/data_source_alicloud_cloud_storage_gateway_storage_bundles_test.go
> datasource/alicloud_cloud_storage_gateway_storage_bundles: Adds two internal parameters page_number and page_size to support paging

- alicloud/common.go
- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_hbr_replication_vault_regions.go
- alicloud/data_source_alicloud_hbr_replication_vault_regions_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_hbr_replication_vault.go
- alicloud/resource_alicloud_hbr_replication_vault_test.go
- alicloud/service_alicloud_hbr.go
- website/alicloud.erb
- website/docs/d/hbr_replication_vault_regions.html.markdown
- website/docs/r/hbr_replication_vault.html.markdown
New Datasource `hbr_replication_vault_regions`
> New Resource `alicloud_hbr_replication_vault` New Datasource `alicloud_hbr_replication_vault_regions`

- alicloud/common.go
- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_cloud_storage_gateway_gateways.go
- alicloud/data_source_alicloud_cloud_storage_gateway_gateways_test.go
> datasource/alicloud_cloud_storage_gateway_gateways: Adds two internal parameters page_number and page_size to support paging

- alicloud/data_source_alicloud_alidns_address_pools.go
- alicloud/data_source_alicloud_alidns_address_pools_test.go
- alicloud/data_source_alicloud_alidns_gtm_instances.go
- alicloud/provider.go
- alicloud/resource_alicloud_alidns_address_pool.go
- alicloud/resource_alicloud_alidns_address_pool_test.go
- alicloud/service_alicloud_alidns.go
- website/alicloud.erb
- website/docs/d/alidns_address_pools.html.markdown
- website/docs/r/alidns_address_pool.html.markdown
New Resource `alicloud_alidns_address_pool`;
New dataSource `alicloud_alidns_address_pools`
> New Resource `alicloud_alidns_address_pool`; New dataSource `alicloud_alidns_address_pools`

- alicloud/data_source_alicloud_alidns_access_strategies.go
- alicloud/data_source_alicloud_alidns_access_strategies_test.go
- alicloud/data_source_alicloud_alidns_address_pools_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_alidns_access_strategy.go
- alicloud/resource_alicloud_alidns_access_strategy_test.go
- alicloud/resource_alicloud_alidns_address_pool_test.go
- alicloud/service_alicloud_alidns.go
- website/alicloud.erb
- website/docs/d/alidns_access_strategies.html.markdown
- website/docs/r/alidns_access_strategy.html.markdown
- website/docs/r/alidns_address_pool.html.markdown
New Resource `alicloud_alidns_access_strategy`;
New dataSource `alicloud_alidns_access_strategies`
> New Resource `alicloud_alidns_access_strategy`; New dataSource `alicloud_alidns_access_strategies`

- alicloud/data_source_alicloud_hbr_replication_vault_regions_test.go
> datasource/alicloud_hbr_replication_vault_regions: Optimize test cases

- alicloud/provider.go
- alicloud/resource_alicloud_alidns_monitor_config.go
- alicloud/resource_alicloud_alidns_monitor_config_test.go
- alicloud/service_alicloud_alidns.go
- website/alicloud.erb
- website/docs/r/alidns_monitor_config.html.markdown
- website/docs/r/rds_account.html.markdown
New Resource `alicloud_alidns_monitor_config`
> New Resource `alicloud_alidns_monitor_config`

- alicloud/data_source_alicloud_vpc_bgp_peers.go
- alicloud/data_source_alicloud_vpc_bgp_peers_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_vpc_bgp_peer.go
- alicloud/resource_alicloud_vpc_bgp_peer_test.go
- alicloud/resource_alicloud_vpc_ipv6_egress_rule_test.go
- alicloud/resource_alicloud_vpc_ipv6_gateway_test.go
- alicloud/resource_alicloud_vpc_ipv6_internet_bandwidth_test.go
- alicloud/service_alicloud_vpc.go
- website/alicloud.erb
- website/docs/d/vpc_bgp_peers.html.markdown
- website/docs/r/vpc_bgp_peer.html.markdown
New Resource `alicloud_vpc_bgp_peer`;
New Datasource `alicloud_vpc_bgp_peers`
> New Resource `alicloud_vpc_bgp_peer`; New Datasource `alicloud_vpc_bgp_peers`

- alicloud/data_source_alicloud_nas_auto_snapshot_policies.go
- alicloud/data_source_alicloud_nas_auto_snapshot_policies_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_nas_auto_snapshot_policy.go
- alicloud/resource_alicloud_nas_auto_snapshot_policy_test.go
- alicloud/resource_alicloud_vpc_dhcp_options_set_attachment_test.go
- alicloud/service_alicloud_nas.go
- website/alicloud.erb
- website/docs/d/nas_auto_snapshot_policies.html.markdown
- website/docs/r/nas_auto_snapshot_policy.html.markdown
New Resource `alicloud_nas_auto_snapshot_policy`;
New Datasource `alicloud_nas_auto_snapshot_policies`
> New Resource `alicloud_nas_auto_snapshot_policy`; New Datasource `alicloud_nas_auto_snapshot_policies`
