aliyun/terraform-provider-alicloud

- alicloud/errors.go
- alicloud/resource_alicloud_disk_attachment.go
- alicloud/resource_alicloud_disk_attachment_test.go
This PR does the following work:
1. Fix alicloud_disk_attachment bug that when attaching multiple diskes, it will be failed and only attach one disk;
2. Set device_name as deprecated because of when attaching disk it will be allocated automatically by system.
The running results of test case as following:
TF_ACC=1 go test ./alicloud/ -v -run=TestAccAlicloudDisk -timeout 120m
=== RUN   TestAccAlicloudDiskAttachment
--- PASS: TestAccAlicloudDiskAttachment (117.73s)
=== RUN   TestAccAlicloudDiskMultiAttachment
--- PASS: TestAccAlicloudDiskMultiAttachment (269.15s)
=== RUN   TestAccAlicloudDisk_basic
--- PASS: TestAccAlicloudDisk_basic (64.18s)
=== RUN   TestAccAlicloudDisk_withTags
--- PASS: TestAccAlicloudDisk_withTags (63.69s)
PASS
ok …
> provider/alicloud: Fix attaching multiple disks bug and set disk-attachment's parameter 'device_name' as deprecated

- alicloud/resource_alicloud_db_instance.go
- alicloud/service_alicloud_rds.go
The PR fixes an rds error that after setting security_ips for rds instance, there is changes when running terraform plan every time.
The running results of rds test cases as following:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDBInstance -timeout=120m
=== RUN   TestAccAlicloudDBInstance_basic
--- PASS: TestAccAlicloudDBInstance_basic (438.04s)
=== RUN   TestAccAlicloudDBInstance_vpc
--- PASS: TestAccAlicloudDBInstance_vpc (424.95s)
=== RUN   TestAccAlicloudDBInstance_multiIZ
--- PASS: TestAccAlicloudDBInstance_multiIZ (444.45s)
=== RUN   TestAccAlicloudDBInstance_database
--- PASS: TestAccAlicloudDBInstance_database (694.01s)
=== RUN   TestAccAlicloudDBInstance_account
--- PASS: TestAccAlicloudDBInstance_account (641.79s)
=== RUN …
> alicloud/provider: Fix diff error about rds security_ips

- alicloud/resource_alicloud_security_group_rule.go
- alicloud/resource_alicloud_security_group_rule_test.go
The PR fixes the diff error when authorizing security group rules, and it results from security rule ID is not unique.
The running results of security group rules' testcase as following:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSecurityGroupRule -timeout 120m
--- PASS: TestAccAlicloudSecurityGroupRule_Ingress (5.76s)
--- PASS: TestAccAlicloudSecurityGroupRule_Egress (7.20s)
--- PASS: TestAccAlicloudSecurityGroupRule_EgressDefaultNicType (5.62s)
--- PASS: TestAccAlicloudSecurityGroupRule_Vpc_Ingress (11.94s)
=== RUN …
> alicloud/provider: Fix diff error when authorizing security group rules

- alicloud/import_alicloud_instance_test.go
- alicloud/resource_alicloud_instance.go
The PR add 'import resource' function for resource alicloud_instance.
The running results of instance's import testcase as following:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudInstance_import -timeout=120m
=== RUN   TestAccAlicloudInstance_importBasic
--- PASS: TestAccAlicloudInstance_importBasic (99.26s)
=== RUN   TestAccAlicloudInstance_importVpc
--- PASS: TestAccAlicloudInstance_importVpc (115.33s)
=== RUN   TestAccAlicloudInstance_importUserData
--- PASS: TestAccAlicloudInstance_importUserData (112.53s)
=== RUN   TestAccAlicloudInstance_importMultiSecurityGroup
--- PASS: TestAccAlicloudInstance_importMultiSecurityGroup (77.39s)
=== RUN   TestAccAlicloudInstance_importTags
--- PASS: TestAccAlicloudInstance_importTags (81.65s)
=== RUN   TestAccAlicloudInstance_importVpcRule
--- …
> alicloud/privider: Add 'Import' function for alicloud_instance

- alicloud/import_alicloud_ess_scalinggroup_test.go
- alicloud/resource_alicloud_ess_scalinggroup.go
The PR add 'import resource' function for resource alicloud_ess_scalinggroup.
The running results of ess scaling group's import testcase as following:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEssScalingGroup_import -timeout=120m
--- PASS: TestAccAlicloudEssScalingGroup_importBasic (12.25s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  12.283s
> alicloud/privider: Add 'Import' function for ess scaling group

- alicloud/import_alicloud_ess_schedule_test.go
- alicloud/resource_alicloud_ess_scalingrule.go
The PR add 'import resource' function for resource alicloud_ess_schedule.
The running results of ess schedule's import testcase as following:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEssSchedule_import -timeout=120m
--- PASS: TestAccAlicloudEssSchedule_importBasic (20.94s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  20.966s
> alicloud/privider: Add 'Import' function for ess schedule

- alicloud/import_alicloud_nat_gateway_test.go
- alicloud/resource_alicloud_nat_gateway.go
The PR add 'import resource' function for resource alicloud_nat_gateway.
The running results of nat gateway's import testcase as following:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudNatGateway_import -timeout=120m
=== RUN   TestAccAlicloudNatGateway_importBasic
--- PASS: TestAccAlicloudNatGateway_importBasic (61.35s)
--- PASS: TestAccAlicloudNatGateway_importSpec (47.83s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  109.232s
> alicloud/privider: Add 'Import' function for NAT gateway

- alicloud/common.go
- alicloud/data_source_alicloud_instance_types.go
- alicloud/errors.go
- alicloud/extension_ecs.go
- alicloud/resource_alicloud_ess_scalingconfiguration.go
- alicloud/resource_alicloud_instance.go
- alicloud/service_alicloud_ecs.go
- website/alicloud.erb
- website/docs/d/instance_types.html.markdown
- website/docs/r/ess_scaling_configuration.html.markdown
- website/docs/r/ess_scaling_group.html.markdown
- website/docs/r/instance.html.markdown
At present, alicloud will make a upgrade for instance type, and it will only support generation three instance types gradually. So the PR add function to filter all instance types in the current zones or region, and get the generation three instance types. If the instance type of users input doesn't fit it, there will output valid tips and choices.
Because all the launched ecs instances by using generation three instance type are IO optimized, the PR set the parameter 'io_optimized' as Deprecated.
In addition, the generation three instance types only support 'clould_ssd' and 'cloud_efficiency' disk, so the PR adds category limit for disk.
The PRs also change all instance_type's values to generation three's and remove 'io_optimized' from related test cases.
In addition, the PR removes …
> [IMPROVEMENT] Filter and get valid instance types and disk category

- alicloud/data_source_alicloud_common.go
- alicloud/data_source_alicloud_key_pairs.go
- alicloud/data_source_alicloud_key_pairs_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/key_pairs.html.markdown
This PR add a new alicloud data source key_pairs, and it can be used to show matching specified conditions key pairs infomation. The PR contains key_pair data source provider, testcase and introduction documents.
The running results of key pair's test cases as follows:
TF_ACC=1 go test -v ./alicloud -run=TestAccAlicloudKeyPairsDataSource -timeout=120m
=== RUN   TestAccAlicloudKeyPairsDataSource_basic
--- PASS: TestAccAlicloudKeyPairsDataSource_basic (1.37s)
PASS
ok    github.com/alibaba/terraform-provider/alicloud  1.395s
> [NEW DATASOURCE]  add new data source key_pairs

- alicloud/import_alicloud_vpc_test.go
- alicloud/resource_alicloud_vpc.go
- alicloud/resource_alicloud_vpc_test.go
- website/docs/r/vpc.html.markdown
The PR add 'import resource' function for resource alicloud_vpc and deprecate 'router_table_id' and add a new output field route_table_id
The running results of vpc's import testcase as following:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudVpc_ -timeout=120m
--- PASS: TestAccAlicloudVpc_importBasic (16.68s)
=== RUN   TestAccAlicloudVpc_basic
--- PASS: TestAccAlicloudVpc_basic (22.39s)
=== RUN   TestAccAlicloudVpc_update
--- PASS: TestAccAlicloudVpc_update (23.47s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  62.577s
> [IMPORT] Add Import function for VPC and modify a output field

- alicloud/errors.go
- alicloud/resource_alicloud_vroute_entry.go
- alicloud/resource_alicloud_vroute_entry_test.go
- website/docs/r/vroute_entry.html.markdown
The PR add 'import resource' function for resource alicloud_route_entry and deprecate 'router_id'.
This PR has a dependency on #32.
The running results of route entry's import testcase as following:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRoute -timeout=120m
--- PASS: TestAccAlicloudRouteEntry_importBasic (135.32s)
--- PASS: TestAccAlicloudRouteEntry_Basic (139.69s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  275.047s
> [IMPORT] Add Import function for route entry and deprecate router_id

- alicloud/errors.go
- alicloud/resource_alicloud_security_group_rule.go
The PR fix security group rule's diff bug by modifying 'DestCidrIp' to 'DestGroupId' when running read.
The running results of rule's import test cases as following:
TF_ACC=1 go test -v ./alicloud -run=TestAccAlicloudSecurityGroupRule -timeout=120m
--- PASS: TestAccAlicloudSecurityGroupRule_Ingress (10.57s)
--- PASS: TestAccAlicloudSecurityGroupRule_Egress (10.68s)
--- PASS: TestAccAlicloudSecurityGroupRule_EgressDefaultNicType (10.99s)
--- PASS: TestAccAlicloudSecurityGroupRule_Vpc_Ingress (23.87s)
=== RUN   TestAccAlicloudSecurityGroupRule_MissParameterSourceCidrIp
--- …
> [BUG] Fix security group rule bug

- alicloud/data_source_alicloud_vpcs.go
- alicloud/data_source_alicloud_vpcs_test.go
- website/alicloud.erb
- website/docs/d/vpcs.html.markdown
This PR add a new data source alicloud_vpcs and it can retrieving the all of vpcs belongs one account in the specified region.
The running results of alicloud_vpcs' test cases as follows:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudVpcsData -timeout=120m
=== RUN   TestAccAlicloudVpcsDataSource_cidr_block
--- PASS: TestAccAlicloudVpcsDataSource_cidr_block (15.40s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  15.425s
> [NEW DATASOURCE] add new data source alicloud_vpcs

- alicloud/resource_alicloud_security_group_rule.go
- website/docs/r/security_group_rule.html.markdown
The PR improves rule parameters setting about cidr_ip and source_security_group_id.
The running test as follows:
TF_ACC=1 go test -v ./alicloud -run=TestAccAlicloudSecurityGroupRule -timeout 120m
--- PASS: TestAccAlicloudSecurityGroupRule_Ingress (11.02s)
--- PASS: TestAccAlicloudSecurityGroupRule_Egress (10.97s)
--- PASS: TestAccAlicloudSecurityGroupRule_EgressDefaultNicType (11.73s)
--- PASS: TestAccAlicloudSecurityGroupRule_Vpc_Ingress (19.78s)
=== RUN   TestAccAlicloudSecurityGroupRule_MissParameterSourceCidrIp
--- PASS: …
> [IMPROVEMENT] improve rule about cidr and source security group id

- CHANGELOG.md
- alicloud/data_source_alicloud_dns_domains_test.go
- alicloud/data_source_alicloud_dns_groups_test.go
- alicloud/data_source_alicloud_dns_records.go
- alicloud/data_source_alicloud_dns_records_test.go
- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_dns_record.go
- alicloud/resource_alicloud_dns_record_test.go
- alicloud/resource_alicloud_ess_scalinggroup.go
- alicloud/resource_alicloud_vroute_entry.go
- vendor/github.com/denverdino/aliyungo/dns/AddDomainRecord.go
- vendor/github.com/denverdino/aliyungo/dns/DescribeDomainRecordInfoNew.go
- vendor/github.com/denverdino/aliyungo/ess/group.go
- vendor/vendor.json
The PR fixed dns_record sets priority failed bug.
$ TF_ACC=1 go test -v ./alicloud -run=TestAccAlicloudDnsRecord -timeout 120m
=== RUN   TestAccAlicloudDnsRecordsDataSource_host_record_regex
--- PASS: TestAccAlicloudDnsRecordsDataSource_host_record_regex (11.47s)
=== RUN   TestAccAlicloudDnsRecordsDataSource_type
--- PASS: TestAccAlicloudDnsRecordsDataSource_type (11.35s)
=== RUN   TestAccAlicloudDnsRecordsDataSource_value_regex
--- PASS: TestAccAlicloudDnsRecordsDataSource_value_regex (11.44s)
=== RUN   TestAccAlicloudDnsRecordsDataSource_line
--- PASS: TestAccAlicloudDnsRecordsDataSource_line (11.71s)
=== RUN   TestAccAlicloudDnsRecordsDataSource_status
--- PASS: TestAccAlicloudDnsRecordsDataSource_status (11.09s)
=== RUN …
> fix dns record priority bug

- CHANGELOG.md
- alicloud/data_source_alicloud_dns_domains_test.go
- alicloud/data_source_alicloud_dns_groups_test.go
- alicloud/data_source_alicloud_dns_records.go
- alicloud/data_source_alicloud_dns_records_test.go
- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_dns_record.go
- alicloud/resource_alicloud_dns_record_test.go
- alicloud/resource_alicloud_ess_scalinggroup.go
- alicloud/resource_alicloud_ess_scalinggroup_test.go
- alicloud/resource_alicloud_security_group.go
- alicloud/resource_alicloud_security_group_rule.go
- alicloud/resource_alicloud_slb.go
- alicloud/resource_alicloud_vroute_entry.go
- vendor/github.com/denverdino/aliyungo/dns/AddDomainRecord.go
- vendor/github.com/denverdino/aliyungo/dns/DescribeDomainRecordInfoNew.go
- vendor/github.com/denverdino/aliyungo/ess/group.go
- vendor/vendor.json
- website/docs/r/ess_scaling_group.html.markdown
The PR fixed ESS attachs SLB failed and security group not found error.
$ TF_ACC=1 go test -v ./alicloud -run=TestAccAlicloudEss -timeout 120m=== RUN   TestAccAlicloudEssScalingGroup_importBasic
--- PASS: TestAccAlicloudEssScalingGroup_importBasic (22.25s)
--- PASS: TestAccAlicloudEssSchedule_importBasic (12.28s)
--- PASS: TestAccAlicloudEssScalingConfiguration_basic (30.41s)
--- PASS: TestAccAlicloudEssScalingConfiguration_multiConfig (40.18s)
=== RUN   TestAccAlicloudEssScalingConfiguration_active
--- PASS: TestAccAlicloudEssScalingConfiguration_active (25.83s)
=== RUN …
> Fix ESS attachs SLB failed

- CHANGELOG.md
- alicloud/provider.go
The PR fix the field security_token bug and set it to 'Optional'.
> modify security_token to Optional

- CHANGELOG.md
- alicloud/extension_slb.go
- alicloud/import_alicloud_slb_attachment_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_slb.go
- alicloud/resource_alicloud_slb_attachment.go
- alicloud/resource_alicloud_slb_attachment_test.go
- website/alicloud.erb
- website/docs/r/slb_attachment.html.markdown
The PR add a field "weight" for resource alicloud_slb_attachment to improve it.
The running result of test cases as following:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlbAttachment -timeout 120m
=== RUN   TestAccAlicloudSlbAttachment_import
--- PASS: TestAccAlicloudSlbAttachment_import (137.53s)
=== RUN   TestAccAlicloudSlbAttachment_basic
--- PASS: TestAccAlicloudSlbAttachment_basic (131.95s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  269.517s
> add weight for slb_attachment

- CHANGELOG.md
- alicloud/diff_suppress_funcs.go
- alicloud/extension_ecs.go
- alicloud/resource_alicloud_security_group_rule.go
- alicloud/resource_alicloud_security_group_rule_test.go
- alicloud/validators.go
- website/docs/r/security_group_rule.html.markdown
The PR improves resource alicloud_secuity_group_rule to avoid needless error when creating security group rule.
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSecurityGroupRule -timeout 120m
--- PASS: TestAccAlicloudSecurityGroupRule_Ingress (18.25s)
--- PASS: TestAccAlicloudSecurityGroupRule_Egress (18.50s)
--- PASS: TestAccAlicloudSecurityGroupRule_EgressDefaultNicType (17.78s)
--- PASS: TestAccAlicloudSecurityGroupRule_Vpc_Ingress (25.76s)
=== RUN   TestAccAlicloudSecurityGroupRule_MissParameterSourceCidrIp
--- PASS: …
> Avoid needless error when creating security group rule

- CHANGELOG.md
- alicloud/errors.go
- alicloud/resource_alicloud_slb_attachment.go
The PR fixes a bug that deleting slb_attachment resource failed results from slb is stopping.
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlbAttachment -timeout 120m
=== RUN   TestAccAlicloudSlbAttachment_import
--- PASS: TestAccAlicloudSlbAttachment_import (137.44s)
=== RUN   TestAccAlicloudSlbAttachment_basic
--- PASS: TestAccAlicloudSlbAttachment_basic (144.63s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  282.103s
> fix deleting slb_attachment resource failed bug

- CHANGELOG.md
- alicloud/common.go
- alicloud/resource_alicloud_db_account.go
- alicloud/resource_alicloud_db_account_privilege.go
- alicloud/resource_alicloud_db_account_privilege_test.go
- alicloud/resource_alicloud_db_account_test.go
- alicloud/resource_alicloud_db_backup_policy.go
- alicloud/resource_alicloud_db_backup_policy_test.go
- alicloud/resource_alicloud_db_connection.go
- alicloud/resource_alicloud_db_connection_test.go
- alicloud/resource_alicloud_db_database.go
- alicloud/resource_alicloud_db_database_test.go
- alicloud/resource_alicloud_db_instance.go
- alicloud/service_alicloud_rds.go
- website/docs/r/db_connection.html.markdown
The PR fixes several rds bugs result from its id not found and its status is not correct.
TF_ACC=1 go test ./alicloud -v -run=TestAclicloudDB -timeout 120m
=== RUN   TestAccAlicloudDBAccountPrivilege_import
--- PASS: TestAccAlicloudDBAccountPrivilege_import (711.62s)
--- PASS: TestAccAlicloudDBAccount_import (621.34s)
=== RUN   TestAccAlicloudDBBackupPolicy_import
--- PASS: TestAccAlicloudDBBackupPolicy_import (541.98s)
=== RUN   TestAccAlicloudDBConnection_import
--- PASS: TestAccAlicloudDBConnection_import (517.14s)
=== RUN   TestAccAlicloudDBDatabase_import
--- PASS: TestAccAlicloudDBDatabase_import (550.41s)
=== RUN   TestAccAlicloudDBInstance_import
the result is …
> fix several bugs about db result from its status and id not found

- CHANGELOG.md
- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_slb.go
- alicloud/resource_alicloud_slb_test.go
- alicloud/validators.go
- vendor/github.com/denverdino/aliyungo/slb/loadbalancers.go
- vendor/vendor.json
- website/docs/r/slb.html.markdown
The PR adds a new field specification for alicloud_slb resource.
The result of running testcase as follows:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlb_spec -timeout 120m 
=== RUN   TestAccAlicloudSlb_spec
--- PASS: TestAccAlicloudSlb_spec (24.53s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  24.578s
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlb_import -timeout 120m
=== RUN   TestAccAlicloudSlb_importBandwidth
--- PASS: TestAccAlicloudSlb_importBandwidth (15.40s)
=== RUN   TestAccAlicloudSlb_importTraffic
--- PASS: TestAccAlicloudSlb_importTraffic (14.96s)
=== RUN   TestAccAlicloudSlb_importVpc
--- PASS: TestAccAlicloudSlb_importVpc (34.18s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  64.588s
> Add a new field specification for alicloud_slb

- CHANGELOG.md
- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_security_group_rule.go
- alicloud/resource_alicloud_security_group_rule_test.go
- website/docs/r/security_group_rule.html.markdown
The PR improves security group rule's port range for "-1/-1" when ip protocol is "all" or "gre" or "icmp".
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSecurityGroupRule -timeout 120m
--- PASS: TestAccAlicloudSecurityGroupRule_Ingress (16.58s)
--- PASS: TestAccAlicloudSecurityGroupRule_Egress (14.58s)
--- PASS: TestAccAlicloudSecurityGroupRule_EgressDefaultNicType (23.28s)
--- PASS: TestAccAlicloudSecurityGroupRule_Vpc_Ingress (23.70s)
=== RUN   TestAccAlicloudSecurityGroupRule_MissParameterSourceCidrIp
--- PASS: …
> Improve security group rule's port range for '-1/-1'

- CHANGELOG.md
- alicloud/resource_alicloud_ess_scalinggroup.go
- alicloud/resource_alicloud_slb.go
The PR fixes a error results from slb invalid status when launching ESS scaling group.
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEssScalingGroup_slb -timeout 120m
--- PASS: TestAccAlicloudEssScalingGroup_slb (150.28s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  150.325s
> fix slb invalid status error when launching ESS scaling group

- CHANGELOG.md
- alicloud/resource_alicloud_nat_gateway.go
- alicloud/resource_alicloud_nat_gateway_test.go
- alicloud/validators.go
- website/docs/r/nat_gateway.html.markdown
The PR deprecates nat gateway two fileds 'spec' and 'bandwidth_paclages'. 
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudNatGateway -timeout 120m
=== RUN   TestAccAlicloudNatGateway_importBasic
--- PASS: TestAccAlicloudNatGateway_importBasic (38.63s)
--- PASS: TestAccAlicloudNatGateway_importSpec (38.73s)
=== RUN   TestAccAlicloudNatGateway_basic
--- PASS: TestAccAlicloudNatGateway_basic (38.92s)
=== RUN   TestAccAlicloudNatGateway_specification
--- PASS: TestAccAlicloudNatGateway_specification (51.41s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  167.736s
> Deprecate nat gateway fileds spec and bandwidth_paclages

- CHANGELOG.md
- alicloud/errors.go
- alicloud/resource_alicloud_eip.go
- website/docs/r/eip.html.markdown
- website/docs/r/eip_association.html.markdown
The PR modify EIP default to PayByTraffic for international account results from international account only creates paybytraffic eip.
The result of running test case as following:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEIP -timeout 120m
--- PASS: TestAccAlicloudEIPAssociation (106.07s)
=== RUN   TestAccAlicloudEIPAssociation_natgateway
--- PASS: TestAccAlicloudEIPAssociation_natgateway (41.89s)
=== RUN   TestAccAlicloudEIP_basic
--- PASS: TestAccAlicloudEIP_basic (25.38s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  173.368s
> Modify EIP default to PayByTraffic for international account

- CHANGELOG.md
- alicloud/resource_alicloud_instance.go
- alicloud/resource_alicloud_instance_test.go
The PR fixes a bug that can't import instance 'role_name'.
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudInstance_ramrole -timeout 120m
=== RUN   TestAccAlicloudInstance_ramrole
--- PASS: TestAccAlicloudInstance_ramrole (139.66s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  139.703s
> fix a bug that can't import instance 'role_name'

- CHANGELOG.md
- alicloud/common.go
- alicloud/data_source_alicloud_vswitches.go
- alicloud/data_source_alicloud_vswitches_test.go
- alicloud/errors.go
- alicloud/provider.go
- alicloud/resource_alicloud_snat.go
- website/alicloud.erb
- website/docs/d/instances.html.markdown
- website/docs/d/vswitches.html.markdown
The PR support new dataSource alicloud_vswitches.
The PR has a pre-PR: #108 
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudVSwitchesDataSource -timeout 120m
=== RUN   TestAccAlicloudVSwitchesDataSource
--- PASS: TestAccAlicloudVSwitchesDataSource (38.61s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  38.649s
> New DataSource alicloud_vswitches

- CHANGELOG.md
- alicloud/data_source_alicloud_eips.go
- alicloud/data_source_alicloud_eips_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/eips.html.markdown
The PR adds a new datasource alicloud_eips.
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEipsDataSource -timeout 120m
=== RUN   TestAccAlicloudEipsDataSource
--- PASS: TestAccAlicloudEipsDataSource (18.89s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  18.928s
> new datasource alicloud_eips

- CHANGELOG.md
- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_instance.go
The PR fixes an error that creating Classic instance failed result in role_name.
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudInstance_ramrole -timeout 120m
=== RUN   TestAccAlicloudInstance_ramrole
--- PASS: TestAccAlicloudInstance_ramrole (178.55s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  178.591s
> Fix creating Classic instance failed result in role_name

- CHANGELOG.md
- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_instance.go
- alicloud/resource_alicloud_security_group.go
- alicloud/resource_alicloud_security_group_test.go
- vendor/github.com/denverdino/aliyungo/ecs/networks.go
- vendor/github.com/denverdino/aliyungo/ecs/security_groups.go
- vendor/github.com/denverdino/aliyungo/ess/group.go
- vendor/github.com/denverdino/aliyungo/rds/instances.go
- vendor/github.com/denverdino/aliyungo/slb/listeners.go
- vendor/github.com/denverdino/aliyungo/slb/loadbalancers.go
- vendor/vendor.json
- website/docs/r/security_group.html.markdown
The PR supports to segregate different ECS instance in which the same security group.
The PR has a pre-pr #111 .
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSecurityGroup -timeout 120m
=== RUN   TestAccAlicloudSecurityGroup_importBasic
--- PASS: TestAccAlicloudSecurityGroup_importBasic (33.26s)
=== RUN   TestAccAlicloudSecurityGroup_importWithVpc
--- PASS: TestAccAlicloudSecurityGroup_importWithVpc (43.95s)
--- PASS: TestAccAlicloudSecurityGroupRule_Ingress (36.68s)
--- PASS: TestAccAlicloudSecurityGroupRule_Egress (35.32s)
--- PASS: …
> Support inner network segregation in one security group

- CHANGELOG.md
- alicloud/common.go
- alicloud/data_source_alicloud_zones.go
- alicloud/data_source_alicloud_zones_test.go
- website/docs/d/zones.html.markdown
The pr support to retrieve multiple zone for launching rds.
The result of running test cases as following:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudZonesDataSource -timeout 120m
--- PASS: TestAccAlicloudZonesDataSource_basic (30.76s)
--- PASS: TestAccAlicloudZonesDataSource_filter (125.35s)
--- PASS: TestAccAlicloudZonesDataSource_unitRegion (44.74s)
--- PASS: TestAccAlicloudZonesDataSource_multiZone (30.19s)
PASS
ok    github.com/alibaba/terraform-provider/alicloud  231.091s
> Data source zones support to retrieve multiple zone

- CHANGELOG.md
- alicloud/errors.go
- alicloud/resource_alicloud_vpc.go
- alicloud/service_alicloud_vpc.go
This PR add one error code to fix vpc not found bug.
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudVpc -timeout=120m
=== RUN   TestAccAlicloudVpcsDataSource_cidr_block
--- PASS: TestAccAlicloudVpcsDataSource_cidr_block (21.92s)
--- PASS: TestAccAlicloudVpc_importBasic (18.51s)
=== RUN   TestAccAlicloudVpc_basic
--- PASS: TestAccAlicloudVpc_basic (17.39s)
=== RUN   TestAccAlicloudVpc_update
--- PASS: TestAccAlicloudVpc_update (27.34s)
=== RUN   TestAccAlicloudVpc_multi
--- PASS: TestAccAlicloudVpc_multi (12.50s)
PASS
ok    github.com/alibaba/terraform-provider/alicloud  97.703s
> Fix vpc not found when vpc has been deleted

- CHANGELOG.md
- alicloud/resource_alicloud_eip_association.go
This PR add eip unassociation retry times to adapt other resources are destroyed.
The running test case result as follows:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEIP -timeout=120m
--- PASS: TestAccAlicloudEIPAssociation (149.66s)
=== RUN   TestAccAlicloudEIPAssociation_natgateway
--- PASS: TestAccAlicloudEIPAssociation_natgateway (33.43s)
=== RUN   TestAccAlicloudEIP_basic
--- PASS: TestAccAlicloudEIP_basic (22.20s)
PASS
ok    github.com/alibaba/terraform-provider/alicloud  205.332s
> Add eip unassociation retry times to avoid needless error

- CHANGELOG.md
- alicloud/errors.go
- alicloud/resource_alicloud_vswitch.go
The PR fixes a error when creating multiple vswitches.
The result of running test case:
TF_ACC=1 go test -v ./alicloud -run=TestAccAlicloudVswitch
=== RUN   TestAccAlicloudVswitch_importBasic
--- PASS: TestAccAlicloudVswitch_importBasic (30.05s)
=== RUN   TestAccAlicloudVswitch_basic
--- PASS: TestAccAlicloudVswitch_basic (28.06s)
=== RUN   TestAccAlicloudVswitch_multi
--- PASS: TestAccAlicloudVswitch_multi (33.84s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  91.986s
> Fix creating vswitch error

- CHANGELOG.md
- alicloud/errors.go
- alicloud/resource_alicloud_slb_listener.go
- alicloud/resource_alicloud_vswitch.go
The PR fixes a bug that deleting a listener when there is backend server.
The result of running test cases:
TF_ACC=1 go test -v ./alicloud -run=TestAccAlicloudSlbListener
--- PASS: TestAccAlicloudSlbListener_importHttp (21.60s)
--- PASS: TestAccAlicloudSlbListener_importTcp (21.30s)
--- PASS: TestAccAlicloudSlbListener_importUdp (19.77s)
--- PASS: TestAccAlicloudSlbListener_http (18.97s)
=== RUN   TestAccAlicloudSlbListener_tcp
--- PASS: TestAccAlicloudSlbListener_tcp (19.19s)
=== RUN   TestAccAlicloudSlbListener_udp
--- PASS: TestAccAlicloudSlbListener_udp (21.06s)
PASS
ok …
> Fix deleting slb listener error

- CHANGELOG.md
- alicloud/resource_alicloud_instance.go
- alicloud/service_alicloud_vpc.go
The result of test case as follows:
TF_ACC=1 go test -v ./alicloud -run=TestAccAlicloudForward
=== RUN   TestAccAlicloudForward_basic
--- PASS: TestAccAlicloudForward_basic (47.23s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  47.273s
> Fix deleting forward table not found error

- CHANGELOG.md
- alicloud/resource_alicloud_cs_kubernetes.go
- website/docs/r/cs_kubernetes.html.markdown
The PR prolongs waiting time while creating kubernetes cluster and  avoids to get timeout error.
> Prolong waiting time for creating kubernetes cluster to avoid timeout

- CHANGELOG.md
- alicloud/errors.go
- alicloud/resource_alicloud_slb_attachment.go
- alicloud/resource_alicloud_slb_listener.go
This PR aims to fix  "OperationBusy" error while describe slb listener.
The result of test cases as follows:
TF_ACC=1 go test -v ./alicloud -run=TestAccAlicloudSlbListener 
--- PASS: TestAccAlicloudSlbListener_importHttp (14.87s)
--- PASS: TestAccAlicloudSlbListener_importTcp (15.96s)
--- PASS: TestAccAlicloudSlbListener_importUdp (18.79s)
--- PASS: TestAccAlicloudSlbListener_http (14.53s)
=== RUN   TestAccAlicloudSlbListener_tcp
--- PASS: TestAccAlicloudSlbListener_tcp (15.73s)
=== RUN   TestAccAlicloudSlbListener_udp
--- PASS: TestAccAlicloudSlbListener_udp (17.20s)
PASS
ok …
> Fix SLB listener "OperationBusy" error

- CHANGELOG.md
- alicloud/common.go
- alicloud/data_source_alicloud_instance_types.go
- alicloud/data_source_alicloud_zones.go
- alicloud/extension_ecs.go
- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_swarm.go
- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_ess_scalingconfiguration.go
- alicloud/resource_alicloud_instance.go
- alicloud/resource_alicloud_slb.go
- alicloud/service_alicloud_ecs.go
- alicloud/validators_test.go
- vendor/github.com/denverdino/aliyungo/ecs/instance_types.go
- vendor/github.com/denverdino/aliyungo/ecs/zones.go
- vendor/vendor.json
This PR uses a new API to get the latest instance types and to avoid some needless error.
The result of running the test cases as follows:
TF_ACC=1 go test -v ./alicloud -run=TestAccAlicloudZones
--- PASS: TestAccAlicloudZonesDataSource_basic (5.35s)
--- PASS: TestAccAlicloudZonesDataSource_filter (7.90s)
--- PASS: TestAccAlicloudZonesDataSource_unitRegion (30.46s)
--- PASS: TestAccAlicloudZonesDataSource_multiZone (3.80s)
PASS
ok    github.com/alibaba/terraform-provider/alicloud  47.553s
ali-186590ce6e87:terraform-provider heguimin$ TF_ACC=1 go test -v ./alicloud …
> Fix getting some instance types failed bug

- CHANGELOG.md
- alicloud/common.go
- alicloud/data_source_alicloud_instance_types.go
- alicloud/data_source_alicloud_zones.go
- alicloud/data_source_alicloud_zones_test.go
- alicloud/extension_ecs.go
- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_swarm.go
- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_ess_scalingconfiguration.go
- alicloud/resource_alicloud_instance.go
- alicloud/resource_alicloud_slb.go
- alicloud/service_alicloud_ecs.go
- alicloud/validators_test.go
- vendor/github.com/denverdino/aliyungo/ecs/instance_types.go
- vendor/github.com/denverdino/aliyungo/ecs/zones.go
- vendor/vendor.json
- website/docs/d/security_group_rules.html.markdown
- website/docs/d/zones.html.markdown
The PR adds three filter parameter to got specified availability zone.
TF_ACC=1 go test -v ./alicloud -run=TestAccAlicloudZones
--- PASS: TestAccAlicloudZonesDataSource_basic (8.07s)
--- PASS: TestAccAlicloudZonesDataSource_filter (7.72s)
--- PASS: TestAccAlicloudZonesDataSource_unitRegion (4.97s)
--- PASS: TestAccAlicloudZonesDataSource_multiZone (6.30s)
=== RUN   TestAccAlicloudZonesDataSource_chargeType
--- PASS: TestAccAlicloudZonesDataSource_chargeType (3.64s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  30.751s
> Add filter parameters for zones data source

- CHANGELOG.md
- alicloud/errors.go
- alicloud/import_alicloud_oss_bucket_test.go
- alicloud/resource_alicloud_oss_bucket.go
This PR fixes a diff error that while running oss bucket import test cases.
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudOssBucket -timeout=600m
=== RUN   TestAccAlicloudOssBucket_importBasic
--- PASS: TestAccAlicloudOssBucket_importBasic (6.07s)
=== RUN   TestAccAlicloudOssBucket_importCors
--- PASS: TestAccAlicloudOssBucket_importCors (7.08s)
=== RUN   TestAccAlicloudOssBucket_importWebsite
--- PASS: TestAccAlicloudOssBucket_importWebsite (5.52s)
=== RUN   TestAccAlicloudOssBucket_importLogging
--- PASS: TestAccAlicloudOssBucket_importLogging (8.13s)
=== RUN   TestAccAlicloudOssBucket_importReferer
--- PASS: TestAccAlicloudOssBucket_importReferer (4.90s)
=== RUN   TestAccAlicloudOssBucket_importLifecycle
--- PASS: …
```
> Fix Oss bucket diff error

- CHANGELOG.md
- alicloud/import_alicloud_log_machine_group_test.go
- alicloud/import_alicloud_log_store_index_test.go
- alicloud/import_alicloud_nat_gateway_test.go
- alicloud/import_alicloud_ots_table_test.go
- alicloud/resource_alicloud_log_machine_group_test.go
- alicloud/resource_alicloud_log_store_index_test.go
- alicloud/resource_alicloud_log_store_test.go
- alicloud/resource_alicloud_oss_bucket_object_test.go
- alicloud/resource_alicloud_oss_bucket_test.go
- alicloud/resource_alicloud_ots_table_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudOss -timeout=600m
=== RUN   TestAccAlicloudOssBucket_importBasic
--- PASS: TestAccAlicloudOssBucket_importBasic (5.17s)
=== RUN   TestAccAlicloudOssBucket_importCors
--- PASS: TestAccAlicloudOssBucket_importCors (4.59s)
=== RUN   TestAccAlicloudOssBucket_importWebsite
--- PASS: TestAccAlicloudOssBucket_importWebsite (4.63s)
=== RUN   TestAccAlicloudOssBucket_importLogging
--- PASS: TestAccAlicloudOssBucket_importLogging (8.48s)
=== RUN   TestAccAlicloudOssBucket_importReferer
--- PASS: TestAccAlicloudOssBucket_importReferer (4.53s)
=== RUN   TestAccAlicloudOssBucket_importLifecycle
--- PASS: TestAccAlicloudOssBucket_importLifecycle (5.33s)
=== RUN   TestAccAlicloudOssBucketObject_source
--- PASS: TestAccAlicloudOssBucketObject_source …
```
> Improve oss resource test case

- CHANGELOG.md
- alicloud/data_source_alicloud_dns_domains_test.go
- alicloud/data_source_alicloud_dns_groups_test.go
- alicloud/errors.go
- alicloud/import_alicloud_log_machine_group_test.go
- alicloud/import_alicloud_log_store_index_test.go
- alicloud/import_alicloud_nat_gateway_test.go
- alicloud/import_alicloud_ots_table_test.go
- alicloud/resource_alicloud_dns_record_test.go
- alicloud/resource_alicloud_dns_test.go
- alicloud/resource_alicloud_log_machine_group_test.go
- alicloud/resource_alicloud_log_store_index_test.go
- alicloud/resource_alicloud_log_store_test.go
- alicloud/resource_alicloud_oss_bucket_object_test.go
- alicloud/resource_alicloud_oss_bucket_test.go
- alicloud/resource_alicloud_ots_table_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDns -timeout=240m
=== RUN   TestAccAlicloudDnsDomainsDataSource_ali_domain
--- PASS: TestAccAlicloudDnsDomainsDataSource_ali_domain (2.59s)
=== RUN   TestAccAlicloudDnsDomainsDataSource_name_regex
--- PASS: TestAccAlicloudDnsDomainsDataSource_name_regex (3.61s)
=== RUN   TestAccAlicloudDnsGroupsDataSource_name_regex
--- PASS: TestAccAlicloudDnsGroupsDataSource_name_regex (2.87s)
=== RUN   TestAccAlicloudDnsRecordsDataSource_host_record_regex
--- PASS: TestAccAlicloudDnsRecordsDataSource_host_record_regex (3.46s)
=== RUN   TestAccAlicloudDnsRecordsDataSource_type
--- PASS: TestAccAlicloudDnsRecordsDataSource_type (2.90s)
=== RUN   TestAccAlicloudDnsRecordsDataSource_value_regex
--- PASS: TestAccAlicloudDnsRecordsDataSource_value_regex …
```
> Improve dns resource test case

- CHANGELOG.md
- alicloud/data_source_alicloud_ram_account_alias_test.go
- alicloud/data_source_alicloud_ram_groups_test.go
- alicloud/data_source_alicloud_ram_policies_test.go
- alicloud/data_source_alicloud_ram_roles_test.go
- alicloud/data_source_alicloud_ram_users_test.go
- alicloud/resource_alicloud_ram_access_key_test.go
- alicloud/resource_alicloud_ram_account_alias_test.go
- alicloud/resource_alicloud_ram_group_membership.go
- alicloud/resource_alicloud_ram_group_membership_test.go
- alicloud/resource_alicloud_ram_group_policy_attachment_test.go
- alicloud/resource_alicloud_ram_group_test.go
- alicloud/resource_alicloud_ram_login_profile_test.go
- alicloud/resource_alicloud_ram_policy_test.go
- alicloud/resource_alicloud_ram_role_attachment_test.go
- alicloud/resource_alicloud_ram_role_policy_attachment_test.go
- alicloud/resource_alicloud_ram_role_test.go
- alicloud/resource_alicloud_ram_user_policy_attachment.go
- alicloud/resource_alicloud_ram_user_policy_attachment_test.go
- alicloud/resource_alicloud_ram_user_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRam -timeout=240m
=== RUN   TestAccAlicloudRamAccountAliasDataSource_basic
--- PASS: TestAccAlicloudRamAccountAliasDataSource_basic (2.70s)
=== RUN   TestAccAlicloudRamGroupsDataSource_for_user
--- PASS: TestAccAlicloudRamGroupsDataSource_for_user (6.27s)
=== RUN   TestAccAlicloudRamGroupsDataSource_for_policy
--- PASS: TestAccAlicloudRamGroupsDataSource_for_policy (5.61s)
=== RUN   TestAccAlicloudRamGroupsDataSource_for_all
--- PASS: TestAccAlicloudRamGroupsDataSource_for_all (2.43s)
=== RUN   TestAccAlicloudRamGroupsDataSource_group_name_regex
--- PASS: TestAccAlicloudRamGroupsDataSource_group_name_regex (3.71s)
=== RUN   TestAccAlicloudRamPoliciesDataSource_for_group
--- PASS: TestAccAlicloudRamPoliciesDataSource_for_group (8.31s) …
```
> Improve ram resource test case 

- CHANGELOG.md
- alicloud/import_alicloud_security_group_test.go
- alicloud/resource_alicloud_security_group_rule_test.go
- alicloud/resource_alicloud_security_group_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSecurity -timeout=240m
=== RUN   TestAccAlicloudSecurityGroupRulesDataSource
--- PASS: TestAccAlicloudSecurityGroupRulesDataSource (13.80s)
=== RUN   TestAccAlicloudSecurityGroupsDataSource
--- PASS: TestAccAlicloudSecurityGroupsDataSource (7.73s)
=== RUN   TestAccAlicloudSecurityGroup_importBasic
--- PASS: TestAccAlicloudSecurityGroup_importBasic (3.30s)
=== RUN   TestAccAlicloudSecurityGroup_importWithVpc
--- PASS: TestAccAlicloudSecurityGroup_importWithVpc (13.93s)
--- PASS: TestAccAlicloudSecurityGroupRule_Ingress (8.50s)
--- PASS: TestAccAlicloudSecurityGroupRule_Egress (4.67s)
=== RUN …
```
> Improve security group resource test case

- CHANGELOG.md
- alicloud/resource_alicloud_instance.go
- alicloud/resource_alicloud_instance_test.go
- alicloud/resource_alicloud_key_pair_attachment.go
- alicloud/service_alicloud_ecs.go
The running test case as follows:
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudInstanceImage_update -timeout=240m
=== RUN   TestAccAlicloudInstanceImage_update
--- PASS: TestAccAlicloudInstanceImage_update (226.28s)
PASS
ok  	github.com/alibaba/terraform-provider/alicloud	226.337s
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudKeyPairAttachment -timeout=240m
=== RUN   TestAccAlicloudKeyPairAttachment_basic
--- PASS: TestAccAlicloudKeyPairAttachment_basic (144.68s)
PASS
ok  	github.com/alibaba/terraform-provider/alicloud	144.742s
```
> Fix losing key pair error after updating ecs instance

- CHANGELOG.md
- alicloud/resource_alicloud_slb_listener.go
- alicloud/resource_alicloud_slb_listener_test.go
- website/docs/r/slb_listener.html.markdown
The running test cases results as follows:
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlbListener -timeout=240m
--- PASS: TestAccAlicloudSlbListener_importHttp (16.29s)
--- PASS: TestAccAlicloudSlbListener_importTcp (14.94s)
--- PASS: TestAccAlicloudSlbListener_importUdp (17.16s)
--- PASS: TestAccAlicloudSlbListener_http (16.94s)
=== RUN   TestAccAlicloudSlbListener_tcp
--- PASS: TestAccAlicloudSlbListener_tcp (16.22s)
=== RUN   TestAccAlicloudSlbListener_udp
--- PASS: TestAccAlicloudSlbListener_udp (16.91s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	98.518s
```
> Resource alicloud_slb_listener supports new field 'gzip'

- CHANGELOG.md
- alicloud/resource_alicloud_slb_listener.go
- alicloud/resource_alicloud_slb_listener_test.go
- website/docs/r/slb_listener.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlbListener -timeout=240m
--- PASS: TestAccAlicloudSlbListener_importHttp (18.15s)
--- PASS: TestAccAlicloudSlbListener_importTcp (21.94s)
--- PASS: TestAccAlicloudSlbListener_importUdp (20.83s)
--- PASS: TestAccAlicloudSlbListener_http (17.11s)
=== RUN   TestAccAlicloudSlbListener_tcp
--- PASS: TestAccAlicloudSlbListener_tcp (17.96s)
=== RUN   TestAccAlicloudSlbListener_udp
--- PASS: TestAccAlicloudSlbListener_udp (17.69s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	113.746s …
```
> Resource alicloud_slb_listener supports new field 'x-forwarded-for'

- CHANGELOG.md
- alicloud/resource_alicloud_nat_gateway.go
- alicloud/resource_alicloud_slb_listener.go
- alicloud/resource_alicloud_slb_listener_test.go
- website/docs/r/nat_gateway.html.markdown
- website/docs/r/slb_listener.html.markdown
The running test cases result as follows: 
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudNat -timeout=240m
--- PASS: TestAccAlicloudNatGateway_importSpec (32.12s)
=== RUN   TestAccAlicloudNatGateway_specification
--- PASS: TestAccAlicloudNatGateway_specification (60.85s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	93.030s
```
> Recover nat gateway bandwidth pacakges to meet stock user requirements

- CHANGELOG.md
- alicloud/import_alicloud_ess_scalinggroup_test.go
- alicloud/resource_alicloud_ess_scalingconfiguration_test.go
- alicloud/resource_alicloud_ess_scalinggroup_test.go
- alicloud/resource_alicloud_ess_scalingrule_test.go
- alicloud/resource_alicloud_ess_schedule_test.go
- alicloud/resource_alicloud_nat_gateway.go
- alicloud/resource_alicloud_slb_listener.go
- alicloud/resource_alicloud_slb_listener_test.go
- website/docs/r/nat_gateway.html.markdown
- website/docs/r/slb_listener.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEss -timeout=240m
^[--- PASS: TestAccAlicloudEssAttachment_import (190.54s)
--- PASS: TestAccAlicloudEssScalingGroup_importBasic (57.14s)
--- PASS: TestAccAlicloudEssSchedule_importBasic (54.92s)
=== RUN   TestAccAlicloudEssAttachment_basic
--- PASS: TestAccAlicloudEssAttachment_basic (189.99s)
--- PASS: TestAccAlicloudEssScalingConfiguration_basic (27.81s)
--- PASS: TestAccAlicloudEssScalingConfiguration_multiConfig (52.09s)
=== …
```
> Improve ESS test cases results from some regions does support Classic Network

- CHANGELOG.md
- alicloud/diff_suppress_funcs.go
- alicloud/import_alicloud_ess_scalinggroup_test.go
- alicloud/resource_alicloud_eip_test.go
- alicloud/resource_alicloud_ess_scalingconfiguration_test.go
- alicloud/resource_alicloud_ess_scalinggroup_test.go
- alicloud/resource_alicloud_ess_scalingrule_test.go
- alicloud/resource_alicloud_ess_schedule_test.go
- alicloud/resource_alicloud_nat_gateway.go
- alicloud/resource_alicloud_slb_listener.go
- alicloud/resource_alicloud_slb_listener_test.go
- website/docs/r/nat_gateway.html.markdown
- website/docs/r/slb_listener.html.markdown
The results for running test cases:
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEIP -timeout=240m
=== RUN   TestAccAlicloudEIPsDataSource
--- PASS: TestAccAlicloudEIPsDataSource (13.91s)
=== RUN   TestAccAlicloudEIP_importBasic
--- PASS: TestAccAlicloudEIP_importBasic (12.90s)
--- PASS: TestAccAlicloudEIPAssociation (230.22s)
=== RUN   TestAccAlicloudEIPAssociation_slb
--- PASS: TestAccAlicloudEIPAssociation_slb (71.10s)
=== RUN   TestAccAlicloudEIP_basic
--- PASS: TestAccAlicloudEIP_basic (21.57s)
PASS
ok  	github.com/alibaba/terraform-provider/alicloud	349.764s
```
> Improve EIP test cases results from international regions does support PayByBandwidth

- CHANGELOG.md
- alicloud/diff_suppress_funcs.go
- alicloud/import_alicloud_slb_server_group_test.go
- alicloud/import_alicloud_slb_test.go
- alicloud/resource_alicloud_slb_server_group_test.go
- alicloud/resource_alicloud_slb_test.go
The results of running test cases as follows:
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlb -timeout=240m
=== RUN   TestAccAlicloudSlbAttachment_import
--- PASS: TestAccAlicloudSlbAttachment_import (198.69s)
--- PASS: TestAccAlicloudSlbListener_importHttp (30.90s)
--- PASS: TestAccAlicloudSlbListener_importTcp (27.64s)
--- PASS: TestAccAlicloudSlbListener_importUdp (27.46s)
=== RUN   TestAccAlicloudSlbRule_import
--- PASS: TestAccAlicloudSlbRule_import (194.66s)
=== RUN   TestAccAlicloudSlbServerGroup_import
--- PASS: TestAccAlicloudSlbServerGroup_import (192.60s)
=== RUN   TestAccAlicloudSlb_import
--- PASS: TestAccAlicloudSlb_import …
```
> Improve SLB test cases results from international regions does support PayByBandwidth and 'Guaranteed-performance' instance

- CHANGELOG.md
- alicloud/resource_alicloud_router_interface.go
- alicloud/resource_alicloud_router_interface_connection.go
- alicloud/resource_alicloud_router_interface_connection_test.go
- alicloud/resource_alicloud_router_interface_test.go
- alicloud/service_alicloud_vpc.go
- website/docs/r/router_interface.html.markdown
- website/docs/r/router_interface_connection.html.markdown
Before creating router interface connection resource, you must set account id by 'opposite_interface_owner_id' or 'account_id'.
The running test cases results as follows:
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRouterInterface -timeout=240m
=== RUN   TestAccAlicloudRouterInterfacesDataSource_oneRouter
--- PASS: TestAccAlicloudRouterInterfacesDataSource_oneRouter (37.76s)
=== RUN   TestAccAlicloudRouterInterfacesDataSource_twoRouters
--- PASS: TestAccAlicloudRouterInterfacesDataSource_twoRouters (103.99s)
=== RUN   TestAccAlicloudRouterInterface_import
--- PASS: TestAccAlicloudRouterInterface_import (34.50s)
--- PASS: TestAccAlicloudRouterInterfaceConnection_basic (80.72s) …
```
> Fix router interface connection error when 'opposite_interface_owner_id' is empty

- CHANGELOG.md
- alicloud/config.go
- website/docs/r/vroute_entry.html.markdown
Some region does not configure endpoint on location and there always happens some timeout error when getting oss location. This PR ignore the timeout error and set a default endpoint to fix this error.
The result of running oss test cases as follows:
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudOss -timeout=240m
=== RUN   TestAccAlicloudOssBucket_importBasic
--- PASS: TestAccAlicloudOssBucket_importBasic (121.79s)
=== RUN   TestAccAlicloudOssBucket_importCors
--- PASS: TestAccAlicloudOssBucket_importCors (187.92s)
=== RUN   TestAccAlicloudOssBucket_importWebsite
--- PASS: TestAccAlicloudOssBucket_importWebsite (196.04s)
=== RUN   TestAccAlicloudOssBucket_importLogging
--- PASS: TestAccAlicloudOssBucket_importLogging (56.32s)
=== RUN   TestAccAlicloudOssBucket_importReferer
--- …
```
> Fix getting oss endpoint timeout error

- CHANGELOG.md
- alicloud/data_source_alicloud_dns_domains_test.go
- alicloud/data_source_alicloud_dns_records_test.go
- alicloud/import_alicloud_dns_record_test.go
- alicloud/import_alicloud_dns_test.go
- alicloud/resource_alicloud_dns_record_test.go
- alicloud/resource_alicloud_dns_test.go
```
/usr/local/go/bin/go tool test2json -t /private/var/folders/v1/jvjz3zmn64q0j34yc9m9n4w00000gn/T/___non_verbose_tests -test.v -test.run ^TestAccAlicloudDns #gosetup
=== RUN   TestAccAlicloudDnsDomainsDataSource_ali_domain
--- PASS: TestAccAlicloudDnsDomainsDataSource_ali_domain (22.49s)
=== RUN   TestAccAlicloudDnsDomainsDataSource_name_regex
--- PASS: TestAccAlicloudDnsDomainsDataSource_name_regex (16.18s)
=== RUN   TestAccAlicloudDnsGroupsDataSource_name_regex
--- PASS: TestAccAlicloudDnsGroupsDataSource_name_regex (10.85s)
=== RUN …
```
> Fix DNS tests falied error

- CHANGELOG.md
- alicloud/data_source_alicloud_account.go
- alicloud/data_source_alicloud_account_test.go
- alicloud/data_source_alicloud_dns_domains_test.go
- alicloud/data_source_alicloud_dns_records_test.go
- alicloud/import_alicloud_dns_record_test.go
- alicloud/import_alicloud_dns_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_dns_record_test.go
- alicloud/resource_alicloud_dns_test.go
- alicloud/resource_alicloud_fc_trigger_test.go
- website/alicloud.erb
- website/docs/d/account.html.markdown
Test results
```
/usr/local/go/bin/go tool test2json -t /private/var/folders/v1/jvjz3zmn64q0j34yc9m9n4w00000gn/T/___non_verbose_tests -test.v -test.run ^TestAccAlicloudFCTrigger_log$ #gosetup
=== RUN   TestAccAlicloudFCTrigger_log
--- PASS: TestAccAlicloudFCTrigger_log (95.69s)
PASS
```
> Improve fc test case using new datasource alicloud_account

- alicloud/errors.go
- alicloud/import_alicloud_cen_instance_attachment_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cen_instance_attachment.go
- alicloud/resource_alicloud_cen_instance_attachment_test.go
- alicloud/service_alicloud_cen.go
- website/alicloud.erb
- website/docs/r/cen_instance_attachment.html.markdown
support the attachment of VPC and VBR.
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCenChildInstanceAttachment -timeout=300m
=== RUN   TestAccAlicloudCenChildInstanceAttachment_basic
--- PASS: TestAccAlicloudCenChildInstanceAttachment_basic (28.39s)
=== RUN   TestAccAlicloudCenChildInstanceAttachment_multi
--- PASS: TestAccAlicloudCenChildInstanceAttachment_multi (33.58s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	62.034s
> add resource CEN Child Instance Attachment

- alicloud/common.go
- alicloud/extension_ecs.go
- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_kubernetes_test.go
- vendor/github.com/denverdino/aliyungo/cs/clusters.go
- vendor/vendor.json
- website/docs/r/cs_kubernetes.html.markdown
I marked master_instance_type, worker_instance_type, worker_number, vswitch_id as deprecated, and added master_instance_types, worker_instance_types, worker_numbers, vswitch_ids.
When three values are specified in master_instance_types and in other three new arguments, it will create a MultiAZ cluster. If one value is specified, it will create normal single AZ cluster.
Not sure if it is good to make these two types in one terraform resource, any suggestions are welcomed.
> support multiaz kubernetes cluster

- alicloud/errors.go
- alicloud/import_alicloud_cen_bandwidth_package_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cen_bandwidth_package.go
- alicloud/resource_alicloud_cen_bandwidth_package_test.go
- alicloud/service_alicloud_cen.go
- website/alicloud.erb
- website/docs/r/cen_bandwidth_package.html.markdown
Resouece alicloud_cen_bandwidth_package support the creation, modification, destruction and import of the bandwidth package in a CEN. The acceptance test results are as below:
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCenBandwidthPackage -timeout=300m
=== RUN   TestAccAlicloudCenBandwidthPackage_importBasic
--- PASS: TestAccAlicloudCenBandwidthPackage_importBasic (11.78s)
=== RUN   TestAccAlicloudCenBandwidthPackage_basic
--- PASS: TestAccAlicloudCenBandwidthPackage_basic (10.93s)
=== RUN   TestAccAlicloudCenBandwidthPackage_update
--- PASS: TestAccAlicloudCenBandwidthPackage_update (21.68s)
=== RUN   TestAccAlicloudCenBandwidthPackage_muti
--- PASS: TestAccAlicloudCenBandwidthPackage_muti (11.38s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud
> Add resource CEN bandwidth package

- CHANGELOG.md
- alicloud/data_source_alicloud_disks.go
- alicloud/data_source_alicloud_disks_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/disks.html.markdown
New data source alicloud_disks.
Test results:
```
/usr/local/go/bin/go test -c -i -sweep=eu-central-1 -o /private/var/folders/v1/jvjz3zmn64q0j34yc9m9n4w00000gn/T/___non_verbose_tests github.com/alibaba/terraform-provider/alicloud #gosetup
/usr/local/go/bin/go tool test2json -t /private/var/folders/v1/jvjz3zmn64q0j34yc9m9n4w00000gn/T/___non_verbose_tests -test.v -test.run ^TestAccAlicloudDisksDataSource_ #gosetup
=== RUN   TestAccAlicloudDisksDataSource_basic
--- PASS: TestAccAlicloudDisksDataSource_basic (29.34s)
=== RUN   TestAccAlicloudDisksDataSource_filterByAllFields
--- PASS: TestAccAlicloudDisksDataSource_filterByAllFields (25.81s)
PASS
```
> add new data source alicloud_disks

- CHANGELOG.md
- alicloud/data_source_alicloud_disks.go
- alicloud/data_source_alicloud_disks_test.go
- alicloud/data_source_alicloud_oss_buckets.go
- alicloud/data_source_alicloud_oss_buckets_test.go
- alicloud/provider.go
- examples/kubernetes/main.tf
- examples/kubernetes/outputs.tf
- examples/kubernetes/variables.tf
- website/alicloud.erb
- website/docs/d/disks.html.markdown
- website/docs/d/oss_buckets.html.markdown
New data source alicloud_oss_buckets.
Test results:
```
/usr/local/go/bin/go test -c -i -v -sweep=cn-beijing -o /private/var/folders/v1/jvjz3zmn64q0j34yc9m9n4w00000gn/T/___Test_in_Beijing__non_verbose_ github.com/alibaba/terraform-provider/alicloud #gosetup
/usr/local/go/bin/go tool test2json -t /private/var/folders/v1/jvjz3zmn64q0j34yc9m9n4w00000gn/T/___Test_in_Beijing__non_verbose_ -test.v -test.run ^TestAccAlicloudOssBucketsDataSource_ #gosetup
--- PASS: TestAccAlicloudOssBucketsDataSource_basic (9.44s)
--- PASS: …
```
>  Add new datasource oss_buckets

- CHANGELOG.md
- alicloud/data_source_alicloud_disks.go
- alicloud/data_source_alicloud_disks_test.go
- alicloud/data_source_alicloud_fc_functions.go
- alicloud/data_source_alicloud_fc_functions_test.go
- alicloud/data_source_alicloud_fc_services.go
- alicloud/data_source_alicloud_fc_services_test.go
- alicloud/data_source_alicloud_oss_bucket_objects.go
- alicloud/data_source_alicloud_oss_bucket_objects_test.go
- alicloud/data_source_alicloud_oss_buckets.go
- alicloud/data_source_alicloud_oss_buckets_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_oss_bucket_object.go
- examples/kubernetes/main.tf
- examples/kubernetes/outputs.tf
- examples/kubernetes/variables.tf
- website/alicloud.erb
- website/docs/d/disks.html.markdown
- website/docs/d/fc_functions.html.markdown
- website/docs/d/fc_services.html.markdown
- website/docs/d/oss_bucket_objects.html.markdown
- website/docs/d/oss_buckets.html.markdown
- website/docs/r/oss_bucket.html.markdown
- website/docs/r/oss_bucket_object.html.markdown
Add a new data source alicloud_oss_bucket_objects.
Test results:
```
/usr/local/go/bin/go test -c -i -v -sweep=cn-beijing -o /private/var/folders/v1/jvjz3zmn64q0j34yc9m9n4w00000gn/T/___Test_in_Beijing__non_verbose_ github.com/alibaba/terraform-provider/alicloud #gosetup
/usr/local/go/bin/go tool test2json -t /private/var/folders/v1/jvjz3zmn64q0j34yc9m9n4w00000gn/T/___Test_in_Beijing__non_verbose_ -test.v -test.run ^TestAccAlicloudOssBucketObjectsDataSource_ #gosetup
--- PASS: TestAccAlicloudOssBucketObjectsDataSource_basic (8.85s)
=== RUN …
```
>  Add a new datasource oss_objects

- alicloud/import_alicloud_cen_bandwidth_limit_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cen_bandwidth_limit.go
- alicloud/resource_alicloud_cen_bandwidth_limit_test.go
- alicloud/service_alicloud_cen.go
- website/alicloud.erb
- website/docs/r/cen_bandwidth_limit.html.markdown
- website/docs/r/cen_bandwidth_package.html.markdown
- website/docs/r/cen_instance_attachment.html.markdown
Add resource cen_bandwidth_limit, which can be used to Set a cross-region interconnection bandwidth. The acceptance results are as below:
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCenBandwidthLimit
=== RUN   TestAccAlicloudCenBandwidthLimit_importBasic
--- PASS: TestAccAlicloudCenBandwidthLimit_importBasic (80.69s)
=== RUN   TestAccAlicloudCenBandwidthLimit_basic
--- PASS: TestAccAlicloudCenBandwidthLimit_basic (110.94s)
=== RUN   TestAccAlicloudCenBandwidthLimit_update
--- PASS: TestAccAlicloudCenBandwidthLimit_update (147.01s)
=== RUN   TestAccAlicloudCenBandwidthLimit_multi
--- PASS: TestAccAlicloudCenBandwidthLimit_multi (146.87s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     485.581s
> add cen bandwidth limit resource

- CHANGELOG.md
- alicloud/config.go
- alicloud/resource_alicloud_disk_attachment.go
- website/docs/d/images.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDiskAttachment -timeout=240m
=== RUN   TestAccAlicloudDiskAttachment
--- PASS: TestAccAlicloudDiskAttachment (171.28s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	171.332s
```
>  Add wait time to fix random detaching disk error

- alicloud/data_source_alicloud_cen_bandwidth_limits.go
- alicloud/data_source_alicloud_cen_bandwidth_limits_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/cen_bandwidth_limits.html.markdown
This data source provides CEN Inter Region Bandwidth Limits available to the user.
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCenBandwidthLimitsDataSource_instance_id -timeout=300m      
--- PASS: TestAccAlicloudCenBandwidthLimitsDataSource_instance_id (46.46s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	46.510s
> Feature: add cen bandwdith limits data source

- CHANGELOG.md
- alicloud/import_alicloud_cs_swarm_test.go
- alicloud/resource_alicloud_cs_swarm.go
- alicloud/resource_alicloud_cs_swarm_test.go
- website/docs/r/cs_swarm.html.markdown
```
go test -run TestAccAlicloudCSSwarm -v -timeout=120m                        
=== RUN   TestAccAlicloudCSSwarm_importBasic
--- PASS: TestAccAlicloudCSSwarm_importBasic (724.55s)
=== RUN   TestAccAlicloudCSSwarm_importBasicNoSlb
--- PASS: TestAccAlicloudCSSwarm_importBasicNoSlb (605.98s)
--- PASS: TestAccAlicloudCSSwarm_vpc (573.62s)
=== RUN   TestAccAlicloudCSSwarm_vpc_noslb
--- PASS: TestAccAlicloudCSSwarm_vpc_noslb (664.53s)
--- PASS: TestAccAlicloudCSSwarm_update (954.18s)
PASS
ok  	github.com/alibaba/terraform-provider/alicloud	3522.919s
```
> added need_slb attribute to cs swarm

- alicloud/errors.go
- alicloud/resource_alicloud_havip_attachment.go
- website/alicloud.erb
- website/docs/r/havip_attachment.html.markdown
- website/docs/r/route_table_attachment.html.markdown
MacBook-Pro-2:terraform-provider-alicloud$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudHaVipAttachment -timeout=300m
=== RUN   TestAccAlicloudHaVipAttachment_importBasic
--- PASS: TestAccAlicloudHaVipAttachment_importBasic (152.32s)
=== RUN   TestAccAlicloudHaVipAttachment_basic
--- PASS: TestAccAlicloudHaVipAttachment_basic (155.52s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	307.889s
> Hide AliCloud HaVip Attachment resource docs because of it is not public totally

- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_slb_listener.go
- alicloud/resource_alicloud_slb_listener_test.go
- examples/slb/README.md
- examples/slb/main.tf
- examples/slb/outputs.tf
- website/docs/r/slb_listener.html.markdown
…established_timeout for tcp listener connection  established idle timeout.  for issues/674.
https://github.com/alibaba/terraform-provider/issues/674
zhongbo.wzb@scala:~/go/src/github.com/terraform-providers/terraform-provider-alicloud% TF_ACC=1 go test ./alicloud -v  -sweep=cn-beijing -sweep-run=alicloud_slb_listener
2018/10/24 22:54:50 [DEBUG] Running Sweepers for region (cn-beijing):
2018/10/24 22:54:50 Sweeper Tests ran:
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	0.065s
zhongbo.wzb@scala:~/go/src/github.com/terraform-providers/terraform-provider-alicloud% TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlbListener -timeout=300m -count=1
^@^@--- PASS: TestAccAlicloudSlbListenersDataSource_http …
> resource alicloud_slb_listener tcp protocol support established_timeout parameter

- alicloud/data_source_alicloud_cen_instances_test.go
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCenInstancesDataSource_multi_cen_ids -timeout=300m   
=== RUN   TestAccAlicloudCenInstancesDataSource_multi_cen_ids
--- PASS: TestAccAlicloudCenInstancesDataSource_multi_cen_ids (11.45s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	11.515s
> Bugfix: set number of cen instances five for normal alicloud account testcases

- CHANGELOG.md
- alicloud/alicloud_sweeper_test.go
- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/connectivity/regions.go
- alicloud/provider.go
- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_swarm.go
After `export ALICLOUD_REGION=eu-west-1`, the result of running test cases as follows:
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudKms -timeout=120m
=== RUN   TestAccAlicloudKmsKeyDataSource_basic
--- PASS: TestAccAlicloudKmsKeyDataSource_basic (8.08s)
=== RUN   TestAccAlicloudKmsKey_import
--- PASS: TestAccAlicloudKmsKey_import (7.46s)
=== RUN   TestAccAlicloudKmsKey_basic
--- PASS: TestAccAlicloudKmsKey_basic (9.58s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     25.191s
```
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudVpc -timeout=120m
=== RUN   TestAccAlicloudVpcsDataSource_cidr_block
--- PASS: TestAccAlicloudVpcsDataSource_cidr_block (24.19s)
--- PASS: TestAccAlicloudVpc_importBasic …
```
> Add a new region eu-west-1

- alicloud/resource_alicloud_ess_scalinggroup.go
- website/docs/r/ess_scaling_group.html.markdown
Currently the max capacity of auto scaling in ALI cloud is 1000 but terraform still points to old capacity of 100. Changing it
> Increasing the min_size and max_size scaling group parameters to 1000

- alicloud/data_source_alicloud_api_gateway_apps_test.go
- alicloud/import_alicloud_api_gateway_app_test.go
- alicloud/resource_alicloud_api_gateway_app_attachment_test.go
- alicloud/resource_alicloud_api_gateway_app_test.go
ali-1c36bbec7887:terraform-provider-alicloud lenny$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudApigatewayApp -timeout=180m
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     (cached) [no tests to run]
> api gateway skip app relevant tests

- CHANGELOG.md
- alicloud/resource_alicloud_pvtz_zone_record.go
- alicloud/resource_alicloud_pvtz_zone_record_test.go
```
TF_ACC=1 go test ./alicloud -v  -run=TestAccAlicloudPvtzZoneRecord_ -timeout=120m
--- PASS: TestAccAlicloudPvtzZoneRecord_importBasic (1.63s)
--- PASS: TestAccAlicloudPvtzZoneRecord_Basic (1.63s)
--- PASS: TestAccAlicloudPvtzZoneRecord_updateRr (2.35s)
--- PASS: TestAccAlicloudPvtzZoneRecord_updateType (2.29s)
=== RUN   TestAccAlicloudPvtzZoneRecord_updateValue
--- PASS: TestAccAlicloudPvtzZoneRecord_updateValue (2.33s)
=== RUN   TestAccAlicloudPvtzZoneRecord_updatePriority
--- PASS: TestAccAlicloudPvtzZoneRecord_updatePriority (2.28s)
=== RUN …
```
> Fix pvtz_zone_record update bug

- CHANGELOG.md
- alicloud/extension_pvtz.go
- alicloud/resource_alicloud_pvtz_zone_record.go
- alicloud/resource_alicloud_pvtz_zone_record_test.go
- examples/pvtz/main.tf
- examples/pvtz/variables.tf
- website/docs/r/pvtz_zone_record.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudPvtzZoneRecord_ -timeout=120m
--- PASS: TestAccAlicloudPvtzZoneRecord_importBasic (2.91s)
--- PASS: TestAccAlicloudPvtzZoneRecord_Basic (1.61s)
--- PASS: TestAccAlicloudPvtzZoneRecord_updateRr (2.34s)
--- PASS: TestAccAlicloudPvtzZoneRecord_updateType (2.35s)
=== RUN   TestAccAlicloudPvtzZoneRecord_updateValue
--- PASS: TestAccAlicloudPvtzZoneRecord_updateValue (2.40s)
=== RUN   TestAccAlicloudPvtzZoneRecord_updatePriority
--- PASS: TestAccAlicloudPvtzZoneRecord_updatePriority (2.33s)
=== RUN   TestAccAlicloudPvtzZoneRecord_updateTTL
--- …
```
> Fix pvtz resource priority bug

- CHANGELOG.md
- alicloud/import_alicloud_security_group_test.go
- alicloud/resource_alicloud_security_group_rule_test.go
- alicloud/resource_alicloud_security_group_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSecurityGroup -timeout=120m
=== RUN   TestAccAlicloudSecurityGroupRulesDataSource
--- PASS: TestAccAlicloudSecurityGroupRulesDataSource (58.92s)
=== RUN   TestAccAlicloudSecurityGroupsDataSource
--- PASS: TestAccAlicloudSecurityGroupsDataSource (40.95s)
=== RUN   TestAccAlicloudSecurityGroupsDataSource_tags
--- PASS: TestAccAlicloudSecurityGroupsDataSource_tags (36.97s)
=== RUN   TestAccAlicloudSecurityGroup_importBasic
--- SKIP: TestAccAlicloudSecurityGroup_importBasic (0.00s)
provider_test.go:73: Skipping unsupported region ap-south-1. Supported regions: [cn-shenzhen cn-shanghai cn-beijing cn-qingdao cn-hangzhou cn-hongkong us-west-1 ap-southeast-1].
=== RUN   TestAccAlicloudSecurityGroup_importWithVpc
--- PASS: …
```
> Skip automatically the testcases which does not support classic regions

- CHANGELOG.md
- alicloud/resource_alicloud_snat.go
- alicloud/resource_alicloud_snat_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSnat_multi -timeout=120m
=== RUN   TestAccAlicloudSnat_multi
--- PASS: TestAccAlicloudSnat_multi (260.06s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     260.128s
```
> fix a snat_entry bug without set id to empty

- alicloud/service_alicloud_vpc.go
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRouterInterface -timeout=300m
=== RUN   TestAccAlicloudRouterInterfacesDataSource_oneRouter
--- PASS: TestAccAlicloudRouterInterfacesDataSource_oneRouter (11.84s)
=== RUN   TestAccAlicloudRouterInterfacesDataSource_twoRouters
--- PASS: TestAccAlicloudRouterInterfacesDataSource_twoRouters (81.11s)
=== RUN   TestAccAlicloudRouterInterface_import
--- PASS: TestAccAlicloudRouterInterface_import (16.31s)
--- PASS: TestAccAlicloudRouterInterfaceConnection_basic (80.58s)
--- PASS: TestAccAlicloudRouterInterface_basic (19.13s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/al …
> Fix router interface prepaid purchase

- alicloud/resource_alicloud_common_bandwidth_package_test.go
- alicloud/service_alicloud_vpc.go
- website/docs/r/common_bandwidth_package.html.markdown
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRouterInterface -timeout=300m
=== RUN TestAccAlicloudRouterInterfacesDataSource_oneRouter
--- PASS: TestAccAlicloudRouterInterfacesDataSource_oneRouter (11.84s)
=== RUN TestAccAlicloudRouterInterfacesDataSource_twoRouters
--- PASS: TestAccAlicloudRouterInterfacesDataSource_twoRouters (81.11s)
=== RUN TestAccAlicloudRouterInterface_import
--- PASS: TestAccAlicloudRouterInterface_import (16.31s)
=== RUN TestAccAlicloudRouterInterfaceConnection_basic
--- PASS: TestAccAlicloudRouterInterfaceConnection_basic (80.58s)
=== RUN TestAccAlicloudRouterInterface_basic
--- PASS: TestAccAlicloudRouterInterface_basic (19.13s)
PASS
ok github.com/terraform-providers/terraform-provider-alicloud/alicloud …
> Remove PayBy95 test case

- CHANGELOG.md
- alicloud/connectivity/regions.go
- website/docs/r/drds_instance.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDRDS -timeout=120m
=== RUN   TestAccAlicloudDRDSInstance_importBasic
--- SKIP: TestAccAlicloudDRDSInstance_importBasic (0.00s)
provider_test.go:75: Skipping unsupported region cn-hongkong. Unsupported regions: [cn-hongkong ap-southeast-1].
=== RUN   TestAccAlicloudDRDSInstance_importVpc
--- PASS: TestAccAlicloudDRDSInstance_importVpc (174.32s)
=== RUN   TestAccAlicloudDRDSInstance_Basic
--- SKIP: TestAccAlicloudDRDSInstance_Basic (0.00s)
provider_test.go:75: Skipping unsupported region cn-hongkong. Unsupported regions: [cn-hongkong ap-southeast-1].
=== RUN   TestAccAlicloudDRDSInstance_Vpc
--- PASS: TestAccAlicloudDRDSInstance_Vpc (120.82s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     295.209s …
```
> Update resource drds supported regions

- CHANGELOG.md
- alicloud/errors.go
- alicloud/extension_vpc.go
- alicloud/resource_alicloud_route_entry.go
- alicloud/resource_alicloud_route_entry_test.go
- alicloud/validators.go
- alicloud/validators_test.go
- website/alicloud.erb
- website/docs/r/route_entry.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRouteEntry -timeout=120m
--- PASS: TestAccAlicloudRouteEntry_importBasic (187.13s)
--- PASS: TestAccAlicloudRouteEntry_Basic (190.97s)
--- PASS: TestAccAlicloudRouteEntry_RouteInterface (71.02s)
=== RUN   TestAccAlicloudRouteEntry_Concurrence
--- PASS: TestAccAlicloudRouteEntry_Concurrence (110.13s)
ok
PASS    github.com/terraform-providers/terraform-provider-alicloud/alicloud     559.318s
```
> Fix route_entry concurrence bug and improve it testcases

- alicloud/resource_alicloud_slb_listener.go
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlbListener -timeout=300m count=1
--- PASS: TestAccAlicloudSlbListenersDataSource_http (34.24s)
=== RUN   TestAccAlicloudSlbListenersDataSource_https
--- PASS: TestAccAlicloudSlbListenersDataSource_https (15.09s)
=== RUN   TestAccAlicloudSlbListenersDataSource_tcp
--- PASS: TestAccAlicloudSlbListenersDataSource_tcp (32.13s)
=== RUN   TestAccAlicloudSlbListenersDataSource_udp
--- PASS: TestAccAlicloudSlbListenersDataSource_udp (35.64s)
--- PASS: TestAccAlicloudSlbListener_importHttp (16.62s)
=== RUN   TestAccAlicloudSlbListener_importHttps
--- PASS: TestAccAlicloudSlbListener_importHttps (15.00s)
=== RUN …
> fix listener deleted bug for resource alicloud_slb_listener.

- CHANGELOG.md
- alicloud/resource_alicloud_pvtz_zone_record.go
- alicloud/service_alicloud_pvtz.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudPvtzZoneRecord -timeout=120m
--- PASS: TestAccAlicloudPvtzZoneRecordsDataSource_basic (2.44s)
--- PASS: TestAccAlicloudPvtzZoneRecordsDataSource_empty (0.95s)
--- PASS: TestAccAlicloudPvtzZoneRecord_importBasic (1.60s)
--- PASS: TestAccAlicloudPvtzZoneRecord_Basic (1.56s)
--- PASS: TestAccAlicloudPvtzZoneRecord_updateRr (2.40s)
--- PASS: TestAccAlicloudPvtzZoneRecord_updateType (2.42s)
=== RUN …
```
> Fix pvtz_record describing bug

- CHANGELOG.md
- alicloud/resource_alicloud_datahub_project.go
- alicloud/resource_alicloud_datahub_subscription.go
- alicloud/resource_alicloud_datahub_topic.go
- alicloud/resource_alicloud_ram_group.go
- alicloud/resource_alicloud_ram_group_membership.go
- alicloud/resource_alicloud_ram_group_policy_attachment.go
- alicloud/resource_alicloud_ram_login_profile.go
- alicloud/resource_alicloud_ram_policy.go
- alicloud/resource_alicloud_ram_role.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDatahub -timeout=120m
=== RUN   TestAccAlicloudDatahubProject_import
--- PASS: TestAccAlicloudDatahubProject_import (1.38s)
=== RUN   TestAccAlicloudDatahubSubscription_importBasic
--- PASS: TestAccAlicloudDatahubSubscription_importBasic (1.89s)
=== RUN   TestAccAlicloudDatahubTopic_importBasic
--- PASS: TestAccAlicloudDatahubTopic_importBasic (1.48s)
=== RUN   TestAccAlicloudDatahubProject_Basic
--- PASS: TestAccAlicloudDatahubProject_Basic (1.05s)
=== RUN   TestAccAlicloudDatahubProject_Update
--- PASS: TestAccAlicloudDatahubProject_Update (1.76s)
=== RUN   TestAccAlicloudDatahubSubscription_Basic
--- PASS: TestAccAlicloudDatahubSubscription_Basic (1.71s)
=== RUN   TestAccAlicloudDatahubSubscription_Update
--- PASS: …
```
> Fix potential bugs of datahub and ram when the resource has been deleted

- CHANGELOG.md
- alicloud/resource_alicloud_oss_bucket.go
- alicloud/resource_alicloud_oss_bucket_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudOss -timeout=180m
--- PASS: TestAccAlicloudOssBucketObjectsDataSource_basic (4.39s)
=== RUN   TestAccAlicloudOssBucketObjectsDataSource_filterByPrefix
--- PASS: TestAccAlicloudOssBucketObjectsDataSource_filterByPrefix (5.00s)
=== RUN   TestAccAlicloudOssBucketObjectsDataSource_empty
--- PASS: TestAccAlicloudOssBucketObjectsDataSource_empty (3.44s)
--- PASS: TestAccAlicloudOssBucketsDataSource_basic (6.49s)
--- PASS: TestAccAlicloudOssBucketsDataSource_full (8.37s)
=== RUN   TestAccAlicloudOssBucketsDataSource_empty
--- PASS: TestAccAlicloudOssBucketsDataSource_empty (2.64s) …
```
> Fix oss bucket deleting failed error

- CHANGELOG.md
- alicloud/common.go
- alicloud/data_source_alicloud_zones.go
- website/docs/d/zones.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudZones -timeout=120m
--- PASS: TestAccAlicloudZonesDataSource_basic (2.07s)
--- PASS: TestAccAlicloudZonesDataSource_filter (4.05s)
--- PASS: TestAccAlicloudZonesDataSource_unitRegion (1.61s)
--- PASS: TestAccAlicloudZonesDataSource_multiZone (0.52s)
=== RUN   TestAccAlicloudZonesDataSource_chargeType
--- PASS: TestAccAlicloudZonesDataSource_chargeType (0.50s)
=== RUN   TestAccAlicloudZonesDataSource_empty
--- PASS: TestAccAlicloudZonesDataSource_empty (0.98s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud …
```
> Datasource alicloud_zones supports filter FunctionCompute

- CHANGELOG.md
- alicloud/import_alicloud_fc_service_test.go
- alicloud/resource_alicloud_fc_service_test.go
- alicloud/resource_alicloud_fc_trigger.go
- alicloud/resource_alicloud_fc_trigger_test.go
- alicloud/service_alicloud_fc.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudFC -timeout=120m
=== RUN   TestAccAlicloudFCFunction_import
--- PASS: TestAccAlicloudFCFunction_import (14.31s)
=== RUN   TestAccAlicloudFCService_import
--- PASS: TestAccAlicloudFCService_import (10.07s)
=== RUN   TestAccAlicloudFCTrigger_import
--- PASS: TestAccAlicloudFCTrigger_import (18.09s)
=== RUN   TestAccAlicloudFCFunction_basic
--- PASS: TestAccAlicloudFCFunction_basic (26.60s)
=== RUN   TestAccAlicloudFCService_basic
--- PASS: TestAccAlicloudFCService_basic (26.25s)
=== RUN   TestAccAlicloudFCService_update
--- PASS: TestAccAlicloudFCService_update (29.31s)
=== RUN   TestAccAlicloudFCTrigger_log
--- PASS: TestAccAlicloudFCTrigger_log (25.39s)
PASS
ok	github.com/terraform-providers/terraform-provider-alicloud/alicloud …
```
> Fix alicloud_fc_trigger's config diff bug

- alicloud/resource_alicloud_router_interface_test.go
- website/docs/r/router_interface.html.markdown
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRouterInterface -timeout=300m
=== RUN   TestAccAlicloudRouterInterfacesDataSource_oneRouter
--- PASS: TestAccAlicloudRouterInterfacesDataSource_oneRouter (16.39s)
=== RUN   TestAccAlicloudRouterInterfacesDataSource_twoRouters
--- PASS: TestAccAlicloudRouterInterfacesDataSource_twoRouters (96.20s)
=== RUN   TestAccAlicloudRouterInterface_import
--- PASS: TestAccAlicloudRouterInterface_import (16.16s)
--- PASS: TestAccAlicloudRouterInterfaceConnection_basic (83.83s)
--- PASS: TestAccAlicloudRouterInterface_basic (16.33s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/al …
> Modify router interface prepaid test case

- CHANGELOG.md
- alicloud/data_source_alicloud_dns_domains_test.go
- alicloud/resource_alicloud_ram_role_attachment_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDns -timeout=180m
=== RUN   TestAccAlicloudDnsDomainsDataSource_ali_domain
--- PASS: TestAccAlicloudDnsDomainsDataSource_ali_domain (6.17s)
=== RUN   TestAccAlicloudDnsDomainsDataSource_name_regex
--- PASS: TestAccAlicloudDnsDomainsDataSource_name_regex (4.00s)
=== RUN   TestAccAlicloudDnsDomainsDataSource_empty
--- PASS: TestAccAlicloudDnsDomainsDataSource_empty (1.18s)
=== RUN   TestAccAlicloudDnsGroupsDataSource_name_regex
--- PASS: TestAccAlicloudDnsGroupsDataSource_name_regex (0.49s)
=== RUN   TestAccAlicloudDnsGroupsDataSource_empty
--- PASS: TestAccAlicloudDnsGroupsDataSource_empty (0.51s)
=== RUN   TestAccAlicloudDnsRecordsDataSource_host_record_regex
--- PASS: TestAccAlicloudDnsRecordsDataSource_host_record_regex (3.31s)
=== …
```
> Improve dns_domains testcase

- CHANGELOG.md
- alicloud/connectivity/client.go
- alicloud/resource_alicloud_ess_scalinggroup.go
- alicloud/resource_alicloud_ess_schedule_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEssScalingGroup_importBasic  -timeout=240m
--- PASS: TestAccAlicloudEssScalingGroup_importBasic (160.02s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	160.088s
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEssSchedule_basic -timeout=180m
=== RUN   TestAccAlicloudEssSchedule_basic
--- PASS: TestAccAlicloudEssSchedule_basic (78.33s)
PASS
```
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	78.392s
> Fix ess_scaling_group import bugs and improve ess schedule testcase

- CHANGELOG.md
- alicloud.tf
- alicloud/connectivity/client.go
- alicloud/connectivity/regions.go
- alicloud/import_alicloud_ots_instance_test.go
- alicloud/import_alicloud_ots_table_test.go
- alicloud/resource_alicloud_ots_instance.go
- alicloud/resource_alicloud_ots_instance_attachment_test.go
- alicloud/resource_alicloud_ots_instance_test.go
- alicloud/resource_alicloud_ots_table.go
- alicloud/resource_alicloud_ots_table_test.go
- alicloud/service_alicloud_ots.go
- examples/ots-table/ots.json
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudOtsInstance  -timeout=240m
=== RUN   TestAccAlicloudOtsInstanceCapacity_import
--- PASS: TestAccAlicloudOtsInstanceCapacity_import (541.82s)
=== RUN   TestAccAlicloudOtsInstanceHighPerformance_import
--- SKIP: TestAccAlicloudOtsInstanceHighPerformance_import (0.00s)
provider_test.go:75: Skipping unsupported region ap-south-1. Unsupported regions: [cn-qingdao cn-zhangjiakou cn-huhehaote cn-hongkong ap-southeast-2 ap-southeast-5 ap-northeast-1 eu-central-1 me-east-1 ap-south-1].
=== RUN   TestAccAlicloudOtsInstanceCapacityAttachment
--- PASS: TestAccAlicloudOtsInstanceCapacityAttachment (583.12s)
=== RUN   TestAccAlicloudOtsInstanceHighPerformanceAttachment
--- SKIP: TestAccAlicloudOtsInstanceHighPerformanceAttachment (0.00s) …
```
> Add timeout and retry for tablestore client and Improve its testcases

- CHANGELOG.md
- alicloud/errors.go
- alicloud/resource_alicloud_kvstore_instance.go
- alicloud/resource_alicloud_ots_table.go
- alicloud/service_alicloud_ots.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudOtsTable -timeout=240m
=== RUN   TestAccAlicloudOtsTableCapacity_import
--- PASS: TestAccAlicloudOtsTableCapacity_import (500.92s)
=== RUN   TestAccAlicloudOtsTableHighPerformance_import
--- PASS: TestAccAlicloudOtsTableHighPerformance_import (515.30s)
=== RUN   TestAccAlicloudOtsTableStoreCapatity
--- PASS: TestAccAlicloudOtsTableStoreCapatity (504.65s)
=== RUN   TestAccAlicloudOtsTableStoreCapatity_updateMaxVersion
--- PASS: TestAccAlicloudOtsTableStoreCapatity_updateMaxVersion (524.51s)
=== RUN   TestAccAlicloudOtsTableStoreCapatity_updateTimeToLive
--- PASS: TestAccAlicloudOtsTableStoreCapatity_updateTimeToLive (507.53s)
=== RUN   TestAccAlicloudOtsTableStoreCapatity_updateAll
--- PASS: …
```
> Fix table store creating timeout error

- CHANGELOG.md
- alicloud/service_alicloud_ots.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudOtsTable  -timeout=240m
=== RUN   TestAccAlicloudOtsTableCapacity_import
--- PASS: TestAccAlicloudOtsTableCapacity_import (504.05s)
=== RUN   TestAccAlicloudOtsTableHighPerformance_import
--- SKIP: TestAccAlicloudOtsTableHighPerformance_import (0.00s)
provider_test.go:75: Skipping unsupported region ap-south-1. Unsupported regions: [cn-qingdao cn-zhangjiakou cn-huhehaote cn-hongkong ap-southeast-2 ap-southeast-5 ap-northeast-1 eu-central-1 me-east-1 ap-south-1].
=== RUN   TestAccAlicloudOtsTableStoreCapatity
--- PASS: TestAccAlicloudOtsTableStoreCapatity (504.51s)
=== RUN   TestAccAlicloudOtsTableStoreCapatity_updateMaxVersion
--- PASS: TestAccAlicloudOtsTableStoreCapatity_updateMaxVersion (528.94s)
=== RUN …
```
> Fix table store describing no such host error

- alicloud/connectivity/regions.go
- alicloud/resource_alicloud_network_interface_test.go
- website/docs/r/network_interface.html.markdown
env TF_DEBUG=debug TF_ACC=1 go test  -v -run=TestAccAlicloudNetworkInterface --timeout=600m
=== RUN   TestAccAlicloudNetworkInterfacesDataSourceBasic
--- PASS: TestAccAlicloudNetworkInterfacesDataSourceBasic (122.30s)
=== RUN   TestAccAlicloudNetworkInterfacesDataSourceWithId
--- PASS: TestAccAlicloudNetworkInterfacesDataSourceWithId (35.16s)
=== RUN   TestAccAlicloudNetworkInterfacesDataSourceWithAllFields
--- PASS: TestAccAlicloudNetworkInterfacesDataSourceWithAllFields (32.00s)
=== RUN   TestAccAlicloudNetworkInterfacesDataSourceEmpty
--- PASS: TestAccAlicloudNetworkInterfacesDataSourceEmpty (107.74s)
=== RUN   TestAccAlicloudNetworkInterfaceAttachment_importBasic
--- PASS: TestAccAlicloudNetworkInterfaceAttachment_importBasic (145.44s)
=== RUN …
> skip private ip test in some regions

- alicloud/connectivity/regions.go
- alicloud/import_alicloud_cs_managed_kubernetes_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_cs_managed_kubernetes.go
- alicloud/resource_alicloud_cs_managed_kubernetes_test.go
- website/alicloud.erb
- website/docs/r/cs_managed_kubernetes.html.markdown
* Managed Kubernetes Clusters have no masters, so there is no need to set master_instance_types, master_disk_category and other master-related arguments.
* Field `connections` is not applicable to Managed Kubernetes.
* Add NodeStableClusterState to cut time waiting for nodes when calling the read method. When cluster is in NodeStableClusterState, there is no node changes, so no need to poll the node api.
> Support managed kubernetes

- alicloud/resource_alicloud_instance.go
- alicloud/resource_alicloud_instance_test.go
TF_DEBUG=debug TF_ACC=1 go test  -v -run=TestAccAlicloudInstanceChargeType_ --timeout=600m
=== RUN   TestAccAlicloudInstanceChargeType_post2Pre
--- PASS: TestAccAlicloudInstanceChargeType_post2Pre (427.98s)
=== RUN   TestAccAlicloudInstanceChargeType_pre2Post
--- PASS: TestAccAlicloudInstanceChargeType_pre2Post (439.34s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	867.378s
> fix a bug about instance charge type change

- alicloud/resource_alicloud_kvstore_backup_policy.go
- website/docs/r/kvstore_backup_policy.html.markdown
If backup policy is updated there was an error since required parameters where not set.
Also fixed docs: backup policy input parameters have been aligned with resource provider names.
> fixed bug in backup policy update

- CHANGELOG.md
- alicloud/common.go
- alicloud/errors.go
- alicloud/resource_alicloud_pvtz_zone_record.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudPvtzZoneRecord -timeout=240m
--- PASS: TestAccAlicloudPvtzZoneRecordsDataSource_basic (6.10s)
--- PASS: TestAccAlicloudPvtzZoneRecordsDataSource_empty (2.37s)
--- PASS: TestAccAlicloudPvtzZoneRecord_importBasic (3.64s)
--- PASS: TestAccAlicloudPvtzZoneRecord_Basic (3.89s)
--- PASS: TestAccAlicloudPvtzZoneRecord_updateRr (6.00s)
--- PASS: TestAccAlicloudPvtzZoneRecord_updateType (5.88s)
=== RUN …
```
> Fix pvtz_record RecordInvalidConflict bug

- CHANGELOG.md
- alicloud/resource_alicloud_ots_table.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudOtsTableStore -timeout=240m
=== RUN   TestAccAlicloudOtsTableStoreCapatity
--- PASS: TestAccAlicloudOtsTableStoreCapatity (498.86s)
=== RUN   TestAccAlicloudOtsTableStoreCapatity_updateMaxVersion
--- PASS: TestAccAlicloudOtsTableStoreCapatity_updateMaxVersion (520.38s)
=== RUN   TestAccAlicloudOtsTableStoreCapatity_updateTimeToLive
--- PASS: TestAccAlicloudOtsTableStoreCapatity_updateTimeToLive (500.08s)
=== RUN   TestAccAlicloudOtsTableStoreCapatity_updateAll
--- PASS: TestAccAlicloudOtsTableStoreCapatity_updateAll (520.23s)
=== RUN   TestAccAlicloudOtsTableStoreHighPerformance
--- SKIP: TestAccAlicloudOtsTableStoreHighPerformance (0.00s)
provider_test.go:75: Skipping unsupported region ap-south-1. Unsupported regions: [cn-qingdao …
```
> Fix table store no such host error with deleting and updating

- CHANGELOG.md
- alicloud/connectivity/client.go
- alicloud/resource_alicloud_ram_group_test.go
- alicloud/resource_alicloud_ram_policy_test.go
```
TF_ACC=1 go test ./alicloud -v  -run=TestAccAlicloudRam -timeout=240m
=== RUN   TestAccAlicloudRamAccountAliasDataSource_basic
--- PASS: TestAccAlicloudRamAccountAliasDataSource_basic (3.10s)
=== RUN   TestAccAlicloudRamGroupsDataSource_for_user
--- PASS: TestAccAlicloudRamGroupsDataSource_for_user (11.58s)
=== RUN   TestAccAlicloudRamGroupsDataSource_for_policy
--- PASS: TestAccAlicloudRamGroupsDataSource_for_policy (12.68s)
=== RUN   TestAccAlicloudRamGroupsDataSource_for_all
--- PASS: TestAccAlicloudRamGroupsDataSource_for_all (2.83s)
=== RUN   TestAccAlicloudRamGroupsDataSource_group_name_regex
--- PASS: TestAccAlicloudRamGroupsDataSource_group_name_regex (5.49s)
=== RUN   TestAccAlicloudRamGroupsDataSource_Empty
--- PASS: TestAccAlicloudRamGroupsDataSource_Empty (2.93s)
=== RUN …
```
> Improve ram client endpoint

- CHANGELOG.md
- alicloud/resource_alicloud_kvstore_backup_policy_test.go
- alicloud/resource_alicloud_kvstore_instance.go
- alicloud/resource_alicloud_kvstore_instance_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudKVStoreRedisInstance_classic -timeout=240m
=== RUN   TestAccAlicloudKVStoreRedisInstance_classic
--- PASS: TestAccAlicloudKVStoreRedisInstance_classic (313.79s)
=== RUN   TestAccAlicloudKVStoreRedisInstance_classicUpdateSecurityIps
--- PASS: TestAccAlicloudKVStoreRedisInstance_classicUpdateSecurityIps (365.88s)
=== RUN   TestAccAlicloudKVStoreRedisInstance_classicUpdateClass
--- PASS: TestAccAlicloudKVStoreRedisInstance_classicUpdateClass (773.46s)
=== RUN   TestAccAlicloudKVStoreRedisInstance_classicUpdateAttr
--- PASS: TestAccAlicloudKVStoreRedisInstance_classicUpdateAttr (310.74s)
=== RUN   TestAccAlicloudKVStoreRedisInstance_classicUpdateAll
--- PASS: TestAccAlicloudKVStoreRedisInstance_classicUpdateAll (824.85s)
PASS
ok …
```
> Improve kvstore client token

- CHANGELOG.md
- alicloud/data_source_alicloud_cen_bandwidth_limits_test.go
- alicloud/data_source_alicloud_cen_region_route_entries_test.go
- alicloud/data_source_alicloud_cen_route_entries_test.go
- alicloud/import_alicloud_cen_bandwidth_limit_test.go
- alicloud/import_alicloud_cen_instance_attachment_test.go
- alicloud/import_alicloud_cen_route_entry_test.go
- alicloud/provider_test.go
- alicloud/resource_alicloud_cen_bandwidth_limit_test.go
- alicloud/resource_alicloud_cen_instance_attachment_test.go
- alicloud/resource_alicloud_cen_route_entry_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCen -timeout=240m
--- PASS: TestAccAlicloudCenBandwidthLimitsDataSource_instance_id (122.58s)
=== RUN   TestAccAlicloudCenBandwidthLimitsDataSource_empty
--- PASS: TestAccAlicloudCenBandwidthLimitsDataSource_empty (1.12s)
=== RUN   TestAccAlicloudCenBandwidthPackagesDataSource_instance_id
--- PASS: TestAccAlicloudCenBandwidthPackagesDataSource_instance_id (13.35s)
=== RUN   TestAccAlicloudCenBandwidthPackagesDataSource_bandwidth_package_nameRegex
--- PASS: TestAccAlicloudCenBandwidthPackagesDataSource_bandwidth_package_nameRegex (9.15s)
=== RUN   TestAccAlicloudCenBandwidthPackagesDataSource_multi_bandwith_packages
--- PASS: …
```
> Fix cen instance and bandwidth multi regions test case bug

- CHANGELOG.md
- alicloud/data_source_alicloud_ram_groups_test.go
- alicloud/data_source_alicloud_ram_policies_test.go
- alicloud/data_source_alicloud_ram_roles_test.go
- alicloud/data_source_alicloud_ram_users_test.go
- alicloud/import_alicloud_ram_group_test.go
- alicloud/import_alicloud_ram_login_profile_test.go
- alicloud/import_alicloud_ram_policy_test.go
- alicloud/import_alicloud_ram_role_test.go
- alicloud/import_alicloud_ram_user_test.go
- alicloud/resource_alicloud_cdn_domain_test.go
- alicloud/resource_alicloud_ess_schedule_test.go
- alicloud/resource_alicloud_instance_test.go
- alicloud/resource_alicloud_ram_access_key_test.go
- alicloud/resource_alicloud_ram_account_alias_test.go
- alicloud/resource_alicloud_ram_group_membership_test.go
- alicloud/resource_alicloud_ram_group_policy_attachment_test.go
- alicloud/resource_alicloud_ram_group_test.go
- alicloud/resource_alicloud_ram_login_profile_test.go
- alicloud/resource_alicloud_ram_policy_test.go
- alicloud/resource_alicloud_ram_role_attachment_test.go
- alicloud/resource_alicloud_ram_role_policy_attachment_test.go
- alicloud/resource_alicloud_ram_role_test.go
- alicloud/resource_alicloud_ram_user_policy_attachment_test.go
- alicloud/resource_alicloud_ram_user_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRam  -timeout=240m
=== RUN   TestAccAlicloudRamAccountAliasDataSource_basic
--- PASS: TestAccAlicloudRamAccountAliasDataSource_basic (3.34s)
=== RUN   TestAccAlicloudRamGroupsDataSource_for_user
--- PASS: TestAccAlicloudRamGroupsDataSource_for_user (9.74s)
=== RUN   TestAccAlicloudRamGroupsDataSource_for_policy
--- PASS: TestAccAlicloudRamGroupsDataSource_for_policy (9.68s)
=== RUN   TestAccAlicloudRamGroupsDataSource_for_all
--- PASS: TestAccAlicloudRamGroupsDataSource_for_all (1.98s)
=== RUN   TestAccAlicloudRamGroupsDataSource_group_name_regex
--- PASS: TestAccAlicloudRamGroupsDataSource_group_name_regex (3.40s)
=== RUN   TestAccAlicloudRamGroupsDataSource_Empty
--- PASS: TestAccAlicloudRamGroupsDataSource_Empty (1.59s)
=== RUN …
```
> Improve ram, ess schedule and cdn testcase

- CHANGELOG.md
- alicloud/data_source_alicloud_api_gateway_apis_test.go
- alicloud/data_source_alicloud_api_gateway_groups_test.go
- alicloud/import_alicloud_api_gateway_api_test.go
- alicloud/import_alicloud_api_gateway_group_test.go
- alicloud/resource_alicloud_api_gateway_api_test.go
- alicloud/resource_alicloud_api_gateway_group_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudApi -timeout=240m
=== RUN   TestAccAlicloudApigatewayApisDataSource_basic
--- PASS: TestAccAlicloudApigatewayApisDataSource_basic (19.24s)
=== RUN   TestAccAlicloudApigatewayApisDataSource_empty
--- PASS: TestAccAlicloudApigatewayApisDataSource_empty (7.61s)
=== RUN   TestAccAlicloudApigatewayAppsDataSource_empty
--- PASS: TestAccAlicloudApigatewayAppsDataSource_empty (3.10s)
=== RUN   TestAccAlicloudApigatewayGroupsDataSource_basic
--- PASS: TestAccAlicloudApigatewayGroupsDataSource_basic (7.44s)
=== RUN   TestAccAlicloudApigatewayGroupsDataSource_empty
--- PASS: TestAccAlicloudApigatewayGroupsDataSource_empty (3.03s)
=== RUN   TestAccAlicloudApigatewayApi_importBasic
--- PASS: TestAccAlicloudApigatewayApi_importBasic (17.85s)
=== …
```
> Improve apigateway testcase

- CHANGELOG.md
- alicloud/import_alicloud_ess_schedule_test.go
- alicloud/resource_alicloud_kvstore_instance_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEssSchedule -timeout=240m
--- PASS: TestAccAlicloudEssSchedule_importBasic (38.76s)
=== RUN   TestAccAlicloudEssSchedule_basic
--- PASS: TestAccAlicloudEssSchedule_basic (35.74s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	74.602s
```
> Improve kvstore and ess schedule testcase

- CHANGELOG.md
- alicloud/service_alicloud_ess.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEssScalingGroup  -timeout=240m
--- PASS: TestAccAlicloudEssScalingGroup_importBasic (193.57s)
--- PASS: TestAccAlicloudEssScalingGroup_basic (204.44s)
--- PASS: TestAccAlicloudEssScalingGroup_vpc (212.35s)
--- PASS: TestAccAlicloudEssScalingGroup_slb (216.53s)
=== RUN   TestAccAlicloudEssScalingGroup_slbempty
--- PASS: TestAccAlicloudEssScalingGroup_slbempty (187.45s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	1014.402s
```
> Fix deleting ess group timeout bug

- CHANGELOG.md
- alicloud/resource_alicloud_oss_bucket_object_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudOss  -timeout=240m
--- PASS: TestAccAlicloudOssBucketObjectsDataSource_basic (8.26s)
=== RUN   TestAccAlicloudOssBucketObjectsDataSource_filterByPrefix
--- PASS: TestAccAlicloudOssBucketObjectsDataSource_filterByPrefix (7.58s)
=== RUN   TestAccAlicloudOssBucketObjectsDataSource_empty
--- PASS: TestAccAlicloudOssBucketObjectsDataSource_empty (3.23s)
--- PASS: TestAccAlicloudOssBucketsDataSource_basic (6.28s)
--- PASS: TestAccAlicloudOssBucketsDataSource_full (7.69s)
=== RUN   TestAccAlicloudOssBucketsDataSource_empty
--- PASS: TestAccAlicloudOssBucketsDataSource_empty (2.27s) …
```
> Fix oss bucket object testcase destroy bug

- CHANGELOG.md
- alicloud/resource_alicloud_kvstore_instance.go
- alicloud/resource_alicloud_ots_instance.go
- website/docs/r/ots_instance.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudOtsInstance -timeout=240m
=== RUN   TestAccAlicloudOtsInstanceCapacity_import
--- PASS: TestAccAlicloudOtsInstanceCapacity_import (506.26s)
=== RUN   TestAccAlicloudOtsInstanceHighPerformance_import
--- SKIP: TestAccAlicloudOtsInstanceHighPerformance_import (0.00s)
provider_test.go:76: Skipping unsupported region ap-south-1. Unsupported regions: [cn-qingdao cn-zhangjiakou cn-huhehaote cn-hongkong ap-southeast-2 ap-southeast-5 ap-northeast-1 eu-central-1 me-east-1 ap-south-1].
=== RUN   TestAccAlicloudOtsInstanceCapacityAttachment
--- PASS: TestAccAlicloudOtsInstanceCapacityAttachment (547.18s)
=== RUN   TestAccAlicloudOtsInstanceHighPerformanceAttachment
--- SKIP: TestAccAlicloudOtsInstanceHighPerformanceAttachment (0.00s) …
```
> Fix ots instance description force new bug

- CHANGELOG.md
- alicloud/connectivity/client.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudOss -timeout=240m
--- PASS: TestAccAlicloudOssBucketObjectsDataSource_basic (8.56s)
=== RUN   TestAccAlicloudOssBucketObjectsDataSource_filterByPrefix
--- PASS: TestAccAlicloudOssBucketObjectsDataSource_filterByPrefix (8.68s)
=== RUN   TestAccAlicloudOssBucketObjectsDataSource_empty
--- PASS: TestAccAlicloudOssBucketObjectsDataSource_empty (7.31s)
--- PASS: TestAccAlicloudOssBucketsDataSource_basic (11.45s)
--- PASS: TestAccAlicloudOssBucketsDataSource_full (18.08s)
=== RUN   TestAccAlicloudOssBucketsDataSource_empty
--- PASS: TestAccAlicloudOssBucketsDataSource_empty (3.69s) …
```
>  Support oss client https

- CHANGELOG.md
- alicloud/data_source_alicloud_api_gateway_groups.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudApigatewayGroupsDataSource  -timeout=240m
=== RUN   TestAccAlicloudApigatewayGroupsDataSource_basic
--- PASS: TestAccAlicloudApigatewayGroupsDataSource_basic (13.43s)
=== RUN   TestAccAlicloudApigatewayGroupsDataSource_empty
--- PASS: TestAccAlicloudApigatewayGroupsDataSource_empty (7.62s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	21.109s
```
> Fix api gateway groups filter bug

- CHANGELOG.md
- alicloud/resource_alicloud_api_gateway_app_test.go
```
TF_ACC=1 go test ./alicloud -v  -sweep=cn-beijing -sweep-run=alicloud_api
2019/01/08 16:58:29 [DEBUG] Running Sweepers for region (cn-beijing):
2019/01/08 16:58:30 [INFO] Deleting App: 7512712
2019/01/08 16:58:30 [INFO] Deleting App: 7512711
2019/01/08 16:58:30 [INFO] Deleting App: 7512678
2019/01/08 16:58:30 [INFO] Deleting App: 7512673
2019/01/08 16:58:30 [INFO] Deleting App: 7512595
2019/01/08 16:58:31 [INFO] Deleting App: 7512594
2019/01/08 16:58:31 [INFO] Deleting App: 7512593
2019/01/08 16:58:31 [INFO] Deleting App: 7512556
2019/01/08 16:58:31 [INFO] Deleting App: 7512554
2019/01/08 16:58:31 [INFO] Deleting App: 7512494
2019/01/08 16:58:36 [DEBUG] Sweeper (alicloud_api_gateway_group) has dependency (alicloud_api_gateway_api), running..
2019/01/08 16:58:36 [DEBUG] Sweeper …
```
> Fix api gateway deleteing app bug

- website/docs/r/kvstore_instance.html.markdown
Attribute name is `connection_domain` not `connections_domain` - [code](https://github.com/terraform-providers/terraform-provider-alicloud/blob/38d3f2e2d5761022f607496576f50fcd12108ecc/alicloud/resource_alicloud_kvstore_instance.go#L85)
> Fix typo in docs

- alicloud/resource_alicloud_cdn_domain.go
- alicloud/resource_alicloud_cdn_domain_test.go
- website/docs/r/cdn_domain.html.markdown
This PR adds the ability to set a SSL certificate and enable HTTPs on the `alicloud_cdn_domain` resource. Previously it was not possible to enable SSL through terraform.
This is my first time both writing Go and working on a terraform provider, so apologies if the code is strange!
Fixes https://github.com/terraform-providers/terraform-provider-alicloud/issues/591
> Adding https_config options to the alicloud_cdn_domain resource

- CHANGELOG.md
- alicloud/common.go
- alicloud/errors.go
- alicloud/extension_pvtz.go
- alicloud/resource_alicloud_pvtz_zone.go
- alicloud/resource_alicloud_pvtz_zone_record.go
- alicloud/service_alicloud_pvtz.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudPvtz -timeout=120m
--- PASS: TestAccAlicloudPvtzZoneRecordsDataSource_basic (4.39s)
--- PASS: TestAccAlicloudPvtzZoneRecordsDataSource_empty (1.88s)
=== RUN   TestAccAlicloudPvtzZonesDataSource_basic
--- PASS: TestAccAlicloudPvtzZonesDataSource_basic (3.33s)
=== RUN   TestAccAlicloudPvtzZonesDataSource_empty
--- PASS: TestAccAlicloudPvtzZonesDataSource_empty (0.78s)
--- PASS: TestAccAlicloudPvtzZoneAttachment_importBasic (18.03s)
--- PASS: TestAccAlicloudPvtzZoneRecord_importBasic (2.95s)
=== RUN …
```
> Fix pvtz throttling user bug and add WrafError

- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_managed_kubernetes.go
When k8s clusters is in NodeStableClusterState, such as running, deleted, nodes will not change.
We should not poll nodes for 5 mins.
> do not poll nodes when k8s cluster is stable

- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_managed_kubernetes.go
- alicloud/validators.go
There are some cases when user specified `[""]` for vswitch_ids, which is definitely illegal.
This checker should avoid such cases.
> add vswitch id checker when creating k8s clusters

- CHANGELOG.md
- alicloud/resource_alicloud_route_entry.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRouteEntry -timeout=240m
--- PASS: TestAccAlicloudRouteEntry_importBasic (190.37s)
--- PASS: TestAccAlicloudRouteEntry_Basic (195.52s)
--- PASS: TestAccAlicloudRouteEntry_RouteInterface (52.33s)
=== RUN   TestAccAlicloudRouteEntry_Concurrence
--- PASS: TestAccAlicloudRouteEntry_Concurrence (101.98s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	540.244s
```
> Improve route entry retry strategy to avoid concurrence issue

- alicloud/data_source_alicloud_cen_bandwidth_packages_test.go
- alicloud/data_source_alicloud_cen_instances_test.go
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCenInstancesDataSource -timeout=300m
=== RUN   TestAccAlicloudCenInstancesDataSource_cen_id
--- PASS: TestAccAlicloudCenInstancesDataSource_cen_id (5.46s)
=== RUN   TestAccAlicloudCenInstancesDataSource_name_regex
--- PASS: TestAccAlicloudCenInstancesDataSource_name_regex (6.03s)
=== RUN   TestAccAlicloudCenInstancesDataSource_multi_cen_ids
--- PASS: TestAccAlicloudCenInstancesDataSource_multi_cen_ids (18.38s)
=== RUN   TestAccAlicloudCenInstancesDataSource_empty
--- PASS: TestAccAlicloudCenInstancesDataSource_empty (3.47s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	33.403s
> BugFix: rename cen instance to avoid mistake query.

- CHANGELOG.md
- alicloud/errors.go
- alicloud/extension_pvtz.go
- alicloud/resource_alicloud_cs_swarm_test.go
- alicloud/resource_alicloud_pvtz_zone.go
- alicloud/resource_alicloud_pvtz_zone_attachment.go
- alicloud/resource_alicloud_pvtz_zone_record.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudPvtz -timeout=120m
--- PASS: TestAccAlicloudPvtzZoneRecordsDataSource_basic (2.79s)
--- PASS: TestAccAlicloudPvtzZoneRecordsDataSource_empty (1.23s)
=== RUN   TestAccAlicloudPvtzZonesDataSource_basic
--- PASS: TestAccAlicloudPvtzZonesDataSource_basic (1.87s)
=== RUN   TestAccAlicloudPvtzZonesDataSource_empty
--- PASS: TestAccAlicloudPvtzZonesDataSource_empty (0.43s)
--- PASS: TestAccAlicloudPvtzZoneAttachment_importBasic (32.10s)
--- PASS: TestAccAlicloudPvtzZoneRecord_importBasic (1.75s)
=== RUN …
```
> Fix pvtz zone attaching vpc system busy error

- CHANGELOG.md
- alicloud/resource_alicloud_pvtz_zone_attachment_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudPvtzZoneAttachment_update -timeout=120m
=== RUN   TestAccAlicloudPvtzZoneAttachment_update
--- PASS: TestAccAlicloudPvtzZoneAttachment_update (72.38s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	72.423s
```
> Improve pvtz attachment test updating case

- CHANGELOG.md
- alicloud/data_source_alicloud_pvtz_zone_records.go
- alicloud/data_source_alicloud_pvtz_zones.go
- alicloud/errors.go
- alicloud/resource_alicloud_log_project.go
- alicloud/resource_alicloud_pvtz_zone.go
- alicloud/resource_alicloud_pvtz_zone_attachment.go
- alicloud/resource_alicloud_pvtz_zone_record.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudLog  -timeout=240m
--- PASS: TestAccAlicloudLogMachineGroup_import (4.00s)
=== RUN   TestAccAlicloudLogProject_import
--- PASS: TestAccAlicloudLogProject_import (2.89s)
=== RUN   TestAccAlicloudLogStoreIndex_importFull
--- PASS: TestAccAlicloudLogStoreIndex_importFull (6.20s)
=== RUN   TestAccAlicloudLogStoreIndex_importField
--- PASS: TestAccAlicloudLogStoreIndex_importField (6.26s)
=== RUN   TestAccAlicloudLogStore_import
--- PASS: TestAccAlicloudLogStore_import (5.06s)
--- PASS: TestAccAlicloudLogMachineGroup_ip (4.30s)
--- PASS: TestAccAlicloudLogMachineGroup_userdefined (4.16s)
=== RUN …
```
> Fix deleting log project requestTimeout error

- CHANGELOG.md
- alicloud/common.go
- alicloud/errors.go
- alicloud/resource_alicloud_slb.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSlb -timeout=240m
=== RUN   TestAccAlicloudSlbAclsDataSource_basic
--- PASS: TestAccAlicloudSlbAclsDataSource_basic (6.47s)
=== RUN   TestAccAlicloudSlbAclsDataSource_empty
--- PASS: TestAccAlicloudSlbAclsDataSource_empty (2.08s)
=== RUN   TestAccAlicloudSlbAttachmentsDataSource_basic
--- PASS: TestAccAlicloudSlbAttachmentsDataSource_basic (207.86s)
=== RUN   TestAccAlicloudSlbAttachmentsDataSource_empty
--- PASS: TestAccAlicloudSlbAttachmentsDataSource_empty (56.29s)
=== RUN   TestAccAlicloudSlbCACertificatesDataSource_basic
--- PASS: TestAccAlicloudSlbCACertificatesDataSource_basic (11.36s)
=== RUN   TestAccAlicloudSlbCACertificatesDataSource_empty
--- PASS: TestAccAlicloudSlbCACertificatesDataSource_empty (4.12s)
=== RUN …
```
> Fix slb OperationFailed.TokenIsProcessing error

- alicloud/resource_alicloud_cs_kubernetes.go
This can cause plugin crash when use PrePaid worker instances for MultiAZ clusters.
> fix k8s cluster worker_period_unit typo

- CHANGELOG.md
- alicloud/data_source_alicloud_pvtz_zone_records.go
- alicloud/data_source_alicloud_pvtz_zones.go
- alicloud/errors.go
- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_managed_kubernetes.go
- alicloud/resource_alicloud_instance_test.go
- alicloud/resource_alicloud_log_project.go
- alicloud/resource_alicloud_ots_table.go
- alicloud/resource_alicloud_pvtz_zone.go
- alicloud/resource_alicloud_pvtz_zone_attachment.go
- alicloud/resource_alicloud_pvtz_zone_record.go
- alicloud/resource_alicloud_ram_role.go
- alicloud/resource_alicloud_slb.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudInstance_ramrole -timeout=240m
=== RUN   TestAccAlicloudInstance_ramrole
--- PASS: TestAccAlicloudInstance_ramrole (128.89s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	128.935s
```
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRam -timeout=300m
=== RUN   TestAccAlicloudRamAccountAliasDataSource_basic
--- PASS: TestAccAlicloudRamAccountAliasDataSource_basic (0.81s)
=== RUN   TestAccAlicloudRamGroupsDataSource_for_user
--- PASS: TestAccAlicloudRamGroupsDataSource_for_user (3.54s)
=== RUN   TestAccAlicloudRamGroupsDataSource_for_policy
--- PASS: TestAccAlicloudRamGroupsDataSource_for_policy (3.45s)
=== RUN   TestAccAlicloudRamGroupsDataSource_for_all
--- PASS: …
```
> Fix deleting ram role error

- CHANGELOG.md
- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_db_instances_test.go
- alicloud/data_source_alicloud_kvstore_instances_test.go
- alicloud/import_alicloud_db_account_privilege_test.go
- alicloud/import_alicloud_db_account_test.go
- alicloud/import_alicloud_db_backup_policy_test.go
- alicloud/import_alicloud_db_connection_test.go
- alicloud/import_alicloud_db_database_test.go
- alicloud/import_alicloud_db_instance_test.go
- alicloud/import_alicloud_kvstore_backup_policy_test.go
- alicloud/import_alicloud_kvstore_instance_test.go
- alicloud/resource_alicloud_cs_kubernetes_test.go
- alicloud/resource_alicloud_db_account_privilege_test.go
- alicloud/resource_alicloud_db_account_test.go
- alicloud/resource_alicloud_db_backup_policy_test.go
- alicloud/resource_alicloud_db_connection_test.go
- alicloud/resource_alicloud_db_database_test.go
- alicloud/resource_alicloud_db_instance_test.go
- alicloud/resource_alicloud_kvstore_backup_policy_test.go
- alicloud/resource_alicloud_kvstore_instance_test.go
- alicloud/service_alicloud_common_test.go
- alicloud/service_alicloud_ecs.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDB -timeout=240m
=== RUN   TestAccAlicloudDBInstancesDataSource
--- PASS: TestAccAlicloudDBInstancesDataSource (92.26s)
=== RUN   TestAccAlicloudDBInstancesDataSourceEmpty
--- PASS: TestAccAlicloudDBInstancesDataSourceEmpty (2.48s)
=== RUN   TestAccAlicloudDBAccountPrivilege_import
--- PASS: TestAccAlicloudDBAccountPrivilege_import (262.29s)
--- PASS: TestAccAlicloudDBAccount_import (664.95s)
=== RUN   TestAccAlicloudDBBackupPolicy_import
--- PASS: TestAccAlicloudDBBackupPolicy_import (110.89s)
=== RUN   TestAccAlicloudDBConnection_import
--- PASS: TestAccAlicloudDBConnection_import (318.12s)
=== RUN   TestAccAlicloudDBDatabase_import
--- PASS: TestAccAlicloudDBDatabase_import (270.87s)
=== …
```
> Improve db instance's testcases

- CHANGELOG.md
- alicloud/data_source_alicloud_vpcs_test.go
- alicloud/resource_alicloud_vpc.go
- alicloud/resource_alicloud_vpc_test.go
```
> go test ./alicloud -v -run=TestAccCheckAlicloudVpcsDataSource_ -timeout=1440m
=== RUN   TestAccCheckAlicloudVpcsDataSource_Status
--- PASS: TestAccCheckAlicloudVpcsDataSource_Status (8.78s)
=== RUN   TestAccCheckAlicloudVpcsDataSource_Is_Default
--- PASS: TestAccCheckAlicloudVpcsDataSource_Is_Default (8.62s)
=== RUN   TestAccCheckAlicloudVpcsDataSource_VSwitch_ID
--- PASS: TestAccCheckAlicloudVpcsDataSource_VSwitch_ID (20.99s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     41.124s
```
```
> go test ./alicloud -v -run=TestAccAlicloudVpc_ -timeout=1440m
--- PASS: TestAccAlicloudVpc_importBasic (9.25s)
=== RUN   TestAccAlicloudVpc_basic
--- PASS: TestAccAlicloudVpc_basic (8.80s)
=== RUN …
```
> Improve vpc resource and data source testcases

- alicloud/data_source_alicloud_security_groups_test.go
- alicloud/resource_alicloud_security_group_test.go
go test -run=TestAccAlicloudSecurityGroupsDataSource -v  -timeout=1440m
=== RUN   TestAccAlicloudSecurityGroupsDataSource
--- PASS: TestAccAlicloudSecurityGroupsDataSource (12.82s)
=== RUN   TestAccAlicloudSecurityGroupsDataSource_vpc
--- PASS: TestAccAlicloudSecurityGroupsDataSource_vpc (15.85s)
=== RUN   TestAccAlicloudSecurityGroupsDataSource_tags
--- PASS: TestAccAlicloudSecurityGroupsDataSource_tags (13.00s)
=== RUN   TestAccAlicloudSecurityGroupsDataSource_empty
--- PASS: TestAccAlicloudSecurityGroupsDataSource_empty (0.66s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	42.401s
go test -run=TestAccAlicloudSecurityGroup -v  -timeout=1440m
=== RUN   TestAccAlicloudSecurityGroup_basic
--- PASS: TestAccAlicloudSecurityGroup_basic (6.19s)
=== RUN …
> fix data_source and resource ut of security_group

- CHANGELOG.md
- alicloud/data_source_alicloud_vswitches_test.go
- alicloud/resource_alicloud_vswitch_test.go
data_source:
```
go test ./alicloud -v -run=TestAccAlicloudVSwitchesDataSource_ -timeout=1440m
=== RUN   TestAccAlicloudVSwitchesDataSource_Name_Regex
--- PASS: TestAccAlicloudVSwitchesDataSource_Name_Regex (25.13s)
=== RUN   TestAccAlicloudVSwitchesDataSource_vpcid
--- PASS: TestAccAlicloudVSwitchesDataSource_vpcid (24.76s)
=== RUN   TestAccAlicloudVSwitchesDataSource_Zone_ID
--- PASS: TestAccAlicloudVSwitchesDataSource_Zone_ID (22.49s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     74.972
```
resource:
```
go test ./alicloud -v -run=TestAccAlicloudVSwitch_ -timeout=1440m
=== RUN   TestAccAlicloudVSwitch_Update
--- PASS: TestAccAlicloudVSwitch_Update (32.20s)
=== RUN   TestAccAlicloudVSwitch_multi
--- PASS: TestAccAlicloudVSwitch_multi (23.73s)
PASS …
```
> Improve vswitch resource and data source testcases

- CHANGELOG.md
- alicloud/data_source_alicloud_eips.go
- alicloud/data_source_alicloud_vpcs.go
- alicloud/errors.go
- alicloud/resource_alicloud_eip.go
- alicloud/resource_alicloud_eip_association.go
- alicloud/resource_alicloud_eip_association_test.go
- alicloud/resource_alicloud_eip_test.go
- alicloud/resource_alicloud_vpc.go
- alicloud/resource_alicloud_vpc_test.go
- alicloud/service_alicloud_vpc.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEIP -timeout=240m
=== RUN   TestAccAlicloudEIPsDataSource
--- PASS: TestAccAlicloudEIPsDataSource (8.33s)
=== RUN   TestAccAlicloudEIPsDataSourceEmpty
--- PASS: TestAccAlicloudEIPsDataSourceEmpty (1.80s)
=== RUN   TestAccAlicloudEIP_importBasic
--- PASS: TestAccAlicloudEIP_importBasic (4.63s)
--- PASS: TestAccAlicloudEIPAssociation (189.82s)
=== RUN   TestAccAlicloudEIPAssociation_slb
--- PASS: TestAccAlicloudEIPAssociation_slb (62.35s)
=== RUN   TestAccAlicloudEIP_basic
--- PASS: TestAccAlicloudEIP_basic (8.33s)
=== RUN   TestAccAlicloudEIP_paybybandwidth
--- PASS: TestAccAlicloudEIP_paybybandwidth (4.10s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	279.530s …
```
> Add wraperror and apply it to vpc and eip

- CHANGELOG.md
- alicloud/data_source_alicloud_vpcs.go
- alicloud/data_source_alicloud_vswitches.go
- alicloud/resource_alicloud_instance_test.go
- alicloud/resource_alicloud_logtail_config.go
- alicloud/resource_alicloud_logtail_config_test.go
- alicloud/resource_alicloud_vpc_test.go
- alicloud/resource_alicloud_vswitch_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudVpc -timeout=240m
=== RUN   TestAccAlicloudVpcsDataSource_cidr_block
--- PASS: TestAccAlicloudVpcsDataSource_cidr_block (19.09s)
=== RUN   TestAccAlicloudVpcsDataSource_empty
--- PASS: TestAccAlicloudVpcsDataSource_empty (4.76s)
--- PASS: TestAccAlicloudVpc_importBasic (19.68s)
=== RUN   TestAccAlicloudVpc_basic
--- PASS: TestAccAlicloudVpc_basic (19.09s)
=== RUN   TestAccAlicloudVpc_update
--- PASS: TestAccAlicloudVpc_update (63.16s)
=== RUN   TestAccAlicloudVpc_multi
--- PASS: TestAccAlicloudVpc_multi (42.22s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	168.112s
```
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudVSwitch -timeout=240m
=== RUN …
```
> Fix ServiceUnavailable error on VPC and VSW

- CHANGELOG.md
- alicloud/data_source_alicloud_kvstore_instances_test.go
- alicloud/errors.go
- alicloud/resource_alicloud_kvstore_backup_policy.go
- alicloud/resource_alicloud_kvstore_instance.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudKVStoreMemcacheBackupPolicy_vpc -timeout=240m
=== RUN   TestAccAlicloudKVStoreMemcacheBackupPolicy_vpc
--- PASS: TestAccAlicloudKVStoreMemcacheBackupPolicy_vpc (389.03s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	389.081s
```
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudKVStoreInstancesDataSource -timeout=240m
=== RUN   TestAccAlicloudKVStoreInstancesDataSource
--- PASS: TestAccAlicloudKVStoreInstancesDataSource (312.28s)
=== RUN   TestAccAlicloudKVStoreInstancesDataSourceEmpty
--- PASS: TestAccAlicloudKVStoreInstancesDataSourceEmpty (8.91s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	321.246s
```
```
TF_ACC=1 go test ./alicloud -v …
```
> Improve kvstore backup policy

- CHANGELOG.md
- alicloud/errors.go
- alicloud/resource_alicloud_kvstore_backup_policy.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudKVStoreRedisBackup -timeout=600m
=== RUN   TestAccAlicloudKVStoreRedisBackupPolicy_import
--- PASS: TestAccAlicloudKVStoreRedisBackupPolicy_import (256.32s)
=== RUN   TestAccAlicloudKVStoreRedisBackupPolicy_classic
--- PASS: TestAccAlicloudKVStoreRedisBackupPolicy_classic (266.80s)
=== RUN   TestAccAlicloudKVStoreRedisBackupPolicy_vpc
--- PASS: TestAccAlicloudKVStoreRedisBackupPolicy_vpc (355.55s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	878.709s
```
> Fix modify kvstore policy not working bug

- CHANGELOG.md
- alicloud/resource_alicloud_kvstore_backup_policy.go
- alicloud/resource_alicloud_pvtz_zone_attachment.go
- alicloud/resource_alicloud_pvtz_zone_record.go
- alicloud/service_alicloud_pvtz.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudPvtzZoneRecord -timeout=240m
--- PASS: TestAccAlicloudPvtzZoneRecordsDataSource_basic (20.49s)
--- PASS: TestAccAlicloudPvtzZoneRecordsDataSource_empty (14.34s)
--- PASS: TestAccAlicloudPvtzZoneRecord_importBasic (9.38s)
--- PASS: TestAccAlicloudPvtzZoneRecord_Basic (3.44s)
--- PASS: TestAccAlicloudPvtzZoneRecord_updateRr (5.05s)
--- PASS: TestAccAlicloudPvtzZoneRecord_updateType (5.50s)
=== RUN …
```
> Fix pvtz record Zone.NotExists error when deleting record

- CHANGELOG.md
- alicloud/resource_alicloud_db_account.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDBAccount -timeout=600m
=== RUN   TestAccAlicloudDBAccountPrivilege_import
--- PASS: TestAccAlicloudDBAccountPrivilege_import (268.59s)
--- PASS: TestAccAlicloudDBAccount_import (592.81s)
=== RUN   TestAccAlicloudDBAccountPrivilege_basic
--- PASS: TestAccAlicloudDBAccountPrivilege_basic (304.38s)
=== RUN   TestAccAlicloudDBAccount_mysql
--- PASS: TestAccAlicloudDBAccount_mysql (606.12s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	1771.975s
```
> Modify db account returning update to read after creating

- CHANGELOG.md
- alicloud/data_source_alicloud_security_group_rules_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSecurityGroupRulesDataSourceWithNic_Type -timeout=240m
=== RUN   TestAccAlicloudSecurityGroupRulesDataSourceWithNic_Type
--- PASS: TestAccAlicloudSecurityGroupRulesDataSourceWithNic_Type (8.53s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	8.587s
```
> Improve security group rule testcase for classic

- CHANGELOG.md
- alicloud/common.go
- alicloud/data_source_alicloud_instance_types.go
- alicloud/data_source_alicloud_instance_types_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudInstanceTypes -timeout=240m
--- PASS: TestAccAlicloudInstanceTypesDataSource_basic (18.65s)
=== RUN   TestAccAlicloudInstanceTypesDataSource_gpu
--- PASS: TestAccAlicloudInstanceTypesDataSource_gpu (4.08s)
=== RUN   TestAccAlicloudInstanceTypesDataSource_empty
--- PASS: TestAccAlicloudInstanceTypesDataSource_empty (10.98s)
=== RUN   TestAccAlicloudInstanceTypesDataSource_k8sSpec
--- PASS: TestAccAlicloudInstanceTypesDataSource_k8sSpec (27.22s)
=== RUN   TestAccAlicloudInstanceTypesDataSource_k8sFamily
--- PASS: TestAccAlicloudInstanceTypesDataSource_k8sFamily (9.96s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	70.937s
```
> Datasource instance_types supports filter results and used to create kuberneters

- alicloud/data_source_alicloud_vpn_connections.go
- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_kubernetes_test.go
- vendor/github.com/denverdino/aliyungo/cs/clusters.go
- vendor/vendor.json
- website/docs/r/cs_kubernetes.html.markdown
User CA has been tested.
* Generate a CA cert pair.
* Use CA cert to sign a client cert pair.
* Use user_ca's path to create a k8s cluster.
* Try connect to the k8s cluster using client cert signed.
```bash
echo '{"CN":"CA","key":{"algo":"rsa","size":2048}}' \
| cfssl gencert -initca - \
| cfssljson -bare ca -
echo '{"signing":{"default":{"expiry":"438000h","usages":["signing","key encipherment","server auth","client auth"]}}}' > ca-config.json
export ADDRESS=
export NAME=kubernetes-admin
echo '{"CN":"'$NAME'","O": "system:masters","hosts":[""],"key":{"algo":"rsa","size":2048}}' | \
cfssl gencert -config=ca-config.json -ca=ca.pem -ca-key=ca-key.pem -hostname="$ADDRESS" - | \
cfssljson -bare $NAME
resource "alicloud_cs_kubernetes" "k8s" {
...
user_ca = "/tmp/ca.pem"
}
terraform apply
curl …
```
> k8s support user_ca

- alicloud/data_source_alicloud_cen_region_route_entries_test.go
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCenRegionRouteEntriesDataSource -timeout=300m
=== RUN   TestAccAlicloudCenRegionRouteEntriesDataSource_basic
--- PASS: TestAccAlicloudCenRegionRouteEntriesDataSource_basic (32.17s)
=== RUN   TestAccAlicloudCenRegionRouteEntriesDataSource_empty
--- PASS: TestAccAlicloudCenRegionRouteEntriesDataSource_empty (1.03s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	33.257s
> Update testcases for cen region domain route entries.

- CHANGELOG.md
- alicloud/import_alicloud_api_gateway_vpc_test.go
- alicloud/resource_alicloud_api_gateway_vpc_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudApigatewayVpc -timeout=240m
=== RUN   TestAccAlicloudApigatewayVpc_importBasic
--- PASS: TestAccAlicloudApigatewayVpc_importBasic (143.89s)
=== RUN   TestAccAlicloudApigatewayVpc_basic
--- PASS: TestAccAlicloudApigatewayVpc_basic (156.17s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	300.123s
```
> Improve api_gateway_vpc_access testcases

- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_db_instance_test.go
- alicloud/service_alicloud_rds.go
- website/docs/r/db_instance.html.markdown
```
/usr/local/Cellar/go/1.11.1/libexec/bin/go test -c -o /private/var/folders/tt/t72n_q9s77l82s54_c_73rsc0000gn/T/___TestAccAlicloudDBInstance_parameter_in_github_com_terraform_providers_terraform_provider_alicloud_alicloud github.com/terraform-providers/terraform-provider-alicloud/alicloud #gosetup
/usr/local/Cellar/go/1.11.1/libexec/bin/go tool test2json -t /private/var/folders/tt/t72n_q9s77l82s54_c_73rsc0000gn/T/___TestAccAlicloudDBInstance_parameter_in_github_com_terraform_providers_terraform_provider_alicloud_alicloud -test.v -test.run ^TestAccAlicloudDBInstance_parameter$ #gosetup
=== RUN   TestAccAlicloudDBInstance_parameter
--- PASS: TestAccAlicloudDBInstance_parameter (205.55s) …
```
> Add attribute parameters to resource alicloud_db_instance

- alicloud/import_alicloud_db_readonly_instance_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_db_readonly_instance.go
- alicloud/resource_alicloud_db_readonly_instance_test.go
- alicloud/service_alicloud_rds.go
- website/alicloud.erb
- website/docs/r/db_readonly_instance.html.markdown
```
/usr/local/Cellar/go/1.11.1/libexec/bin/go test -c -o /private/var/folders/tt/t72n_q9s77l82s54_c_73rsc0000gn/T/___TestAccAlicloudDBReadonlyInstance_vpc_in_github_com_terraform_providers_terraform_provider_alicloud_alicloud github.com/terraform-providers/terraform-provider-alicloud/alicloud #gosetup
/usr/local/Cellar/go/1.11.1/libexec/bin/go tool test2json -t /private/var/folders/tt/t72n_q9s77l82s54_c_73rsc0000gn/T/___TestAccAlicloudDBReadonlyInstance_vpc_in_github_com_terraform_providers_terraform_provider_alicloud_alicloud -test.v -test.run ^TestAccAlicloudDBReadonlyInstance_vpc$ #gosetup
=== RUN   TestAccAlicloudDBReadonlyInstance_vpc
--- PASS: TestAccAlicloudDBReadonlyInstance_vpc …
```
> Add new resource alicloud_db_readonly_instance

- CHANGELOG.md
- alicloud/import_alicloud_dns_record_test.go
- alicloud/resource_alicloud_dns_record.go
- alicloud/resource_alicloud_dns_record_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDnsRecord -timeout=240m
=== RUN   TestAccAlicloudDnsRecordsDataSource_host_record_regex
--- PASS: TestAccAlicloudDnsRecordsDataSource_host_record_regex (4.94s)
=== RUN   TestAccAlicloudDnsRecordsDataSource_type
--- PASS: TestAccAlicloudDnsRecordsDataSource_type (5.24s)
=== RUN   TestAccAlicloudDnsRecordsDataSource_value_regex
--- PASS: TestAccAlicloudDnsRecordsDataSource_value_regex (5.22s)
=== RUN   TestAccAlicloudDnsRecordsDataSource_line
--- PASS: TestAccAlicloudDnsRecordsDataSource_line (5.07s)
=== RUN   TestAccAlicloudDnsRecordsDataSource_status
--- PASS: TestAccAlicloudDnsRecordsDataSource_status (5.51s)
=== RUN   TestAccAlicloudDnsRecordsDataSource_is_locked
--- PASS: TestAccAlicloudDnsRecordsDataSource_is_locked (4.88s)
=== …
```
> Fix dns record ttl setting error and update bug

- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_db_instance_test.go
- alicloud/resource_alicloud_db_readonly_instance.go
- alicloud/resource_alicloud_db_readonly_instance_test.go
- alicloud/service_alicloud_rds.go
- website/docs/r/db_instance.html.markdown
- website/docs/r/db_readonly_instance.html.markdown
We found that terraform can not find any diff when we just modify the value of parameter, because the diff strategy of schema.SetType only compare the hash of each element.
This PR fix it by add value to hash.
```
/usr/local/Cellar/go/1.11.1/libexec/bin/go test -c -o /private/var/folders/tt/t72n_q9s77l82s54_c_73rsc0000gn/T/___TestAccAlicloudDBInstance_parameter_in_github_com_terraform_providers_terraform_provider_alicloud_alicloud github.com/terraform-providers/terraform-provider-alicloud/alicloud #gosetup
/usr/local/Cellar/go/1.11.1/libexec/bin/go tool test2json -t /private/var/folders/tt/t72n_q9s77l82s54_c_73rsc0000gn/T/___TestAccAlicloudDBInstance_parameter_in_github_com_terraform_provi …
```
> fix rds parameter update issue

- alicloud/import_alicloud_cs_managed_kubernetes_test.go
Solve issue
```
=== RUN   TestAccAlicloudCSManagedKubernetes_import
--- FAIL: TestAccAlicloudCSManagedKubernetes_import (577.24s)
testing.go:434: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
(map[string]string) {
}
(map[string]string) (len=1) {
(string) (len=20) "slb_internet_enabled": (string) (len=5) "false"
}
```
> fix import managed kubernetes test

- alicloud/resource_alicloud_db_readonly_instance.go
- alicloud/resource_alicloud_db_readonly_instance_test.go
fix #775 
```
/usr/local/Cellar/go/1.11.1/libexec/bin/go test -c -o /private/var/folders/tt/t72n_q9s77l82s54_c_73rsc0000gn/T/___TestAccAlicloudDBReadonlyInstance_updateInstanceName_in_github_com_terraform_providers_terraform_provider_alicloud_alicloud github.com/terraform-providers/terraform-provider-alicloud/alicloud #gosetup
/usr/local/Cellar/go/1.11.1/libexec/bin/go tool test2json -t /private/var/folders/tt/t72n_q9s77l82s54_c_73rsc0000gn/T/___TestAccAlicloudDBReadonlyInstance_updateInstanceName_in_github_com_terraform_providers_terraform_provider_alicloud_alicloud -test.v -test.run ^TestAccAlicloudDBReadonlyInstance_updateInstanceName$ #gosetup
=== RUN …
```
> fix rds readonly instance name update issue

- CHANGELOG.md
- alicloud/resource_alicloud_instance.go
```
TF_ACC=1 go test -v ./alicloud -run=TestAccAlicloudDiskAttachment --timeout=600m
=== RUN   TestAccAlicloudDiskAttachment
--- PASS: TestAccAlicloudDiskAttachment (166.18s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     166.244s
```
```
TF_ACC=1 go test -v ./alicloud -run=TestAccAlicloudInstance_vpc --timeout=600m
=== RUN   TestAccAlicloudInstance_vpc
--- PASS: TestAccAlicloudInstance_vpc (151.48s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     151.526s
```
> fix volume_tags diff bug when running testcases

- alicloud/data_source_alicloud_cs_kubernetes_clusters.go
- alicloud/data_source_alicloud_cs_kubernetes_clusters_test.go
- alicloud/provider.go
- vendor/github.com/denverdino/aliyungo/cs/clusters.go
- vendor/vendor.json
- website/alicloud.erb
- website/docs/d/cs_kubernetes_clusters.html.markdown
Note: 
* Function csKubernetesClusterDescriptionAttributes is rewritten from alicloud/resource_alicloud_cs_kubernetes.go:583 resourceAlicloudCSKubernetesRead.
* The `connections` field now get data from `/cluster/CLUSTER_ID/endpoints` API.
* Tests was passed under different filter combinations.
> add kubernetes cluster data source

- alicloud/data_source_alicloud_cs_kubernetes_clusters.go
- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_managed_kubernetes.go
- vendor/github.com/denverdino/aliyungo/cs/clusters.go
- vendor/vendor.json
When a cluster is creating, it will not return most values, including bool values like `PublicSLB`, `MasterAutoRenew`, it will throw a parse panic in sdk.
So if we use `alicloud_cs_kubernetes_clusters` against creating clusters, terraform will throw error out.
This is related to changes in sdk, see https://github.com/denverdino/aliyungo/pull/328
> change bool to *bool in parameters of k8s clusters

- alicloud/resource_alicloud_ess_attachment_test.go
- alicloud/service_alicloud_ess.go
=== RUN   TestAccAlicloudEssAlarm_import
--- PASS: TestAccAlicloudEssAlarm_import (46.11s)
--- PASS: TestAccAlicloudEssAttachment_import (102.39s)
=== RUN   TestAccAlicloudEssLifecycleHook_import
--- PASS: TestAccAlicloudEssLifecycleHook_import (36.95s)
--- PASS: TestAccAlicloudEssScalingGroup_importBasic (41.64s)
--- PASS: TestAccAlicloudEssSchedule_importBasic (37.93s)
--- PASS: TestAccAlicloudEssAlarm_basic (45.39s)
=== RUN   TestAccAlicloudEssAlarm_with_dimension
--- PASS: TestAccAlicloudEssAlarm_with_dimension (47.06s)
=== RUN   TestAccAlicloudEssAlarm_update
--- PASS: TestAccAlicloudEssAlarm_update …
> Bugfix: destroying alicloud_ess_attachment timeout.

- alicloud/resource_alicloud_db_instance.go
- website/docs/r/db_instance.html.markdown
RDS auto-renewal option is only available when instance charge type is prepaid,
and the test will fail at the sweep when the test finish
so I deleted the code of the test as you said.
> RDS auto-renewal option

- alicloud/data_source_alicloud_cs_kubernetes_clusters.go
- vendor/github.com/denverdino/aliyungo/cs/clusters.go
- vendor/vendor.json
fixed following error, one is related to the https://github.com/denverdino/aliyungo/pull/329
```
=== RUN   TestAccAlicloudCSKubernetesClustersDataSource_AutoVpc
--- FAIL: TestAccAlicloudCSKubernetesClustersDataSource_AutoVpc (1159.01s)
testing.go:434: Step 0 error: Check failed: Check 4/15 error: data.alicloud_cs_kubernetes_clusters.k8s_clusters: Attribute 'clusters.0.worker_numbers.#' expected "1", got "0"
=== RUN   TestAccAlicloudCSKubernetes_import
--- FAIL: TestAccAlicloudCSKubernetes_import (1179.20s)
testing.go:434: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
(map[string]string) {
}
(map[string]string) (len=1) {
(string) (len=20) "slb_internet_enabled": (string) (len=4) "true"
}
```
> fix kubernetes data resource ut and import error

- alicloud/data_source_alicloud_nas_access_groups.go
- alicloud/data_source_alicloud_nas_access_groups_test.go
- alicloud/import_alicloud_nas_access_group_test.go
- alicloud/import_alicloud_nas_access_rule_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_nas_access_group_test.go
- alicloud/resource_alicloud_nas_access_rule_test.go
- website/alicloud.erb
- website/docs/d/nas_access_groups.html.markdown
=== RUN   TestAccAlicloudNasAccessGroupDataSource_all
--- PASS: TestAccAlicloudNasAccessGroupDataSource_all (1.26s)
=== RUN   TestAccAlicloudNasAccessGroupDataSource_type
--- PASS: TestAccAlicloudNasAccessGroupDataSource_type (0.90s)
=== RUN   TestAccAlicloudNasAccessGroupDataSource_description
--- PASS: TestAccAlicloudNasAccessGroupDataSource_description (0.89s)
=== RUN   TestAccAlicloudNasAccessGroupDataSource_empty
--- PASS: TestAccAlicloudNasAccessGroupDataSource_empty (0.44s)
PASS
=== RUN   TestAccAlicloudNas_AccessRule_basic
--- PASS: TestAccAlicloudNas_AccessRule_basic (1.68s)
=== RUN   TestAccAlicloudNas_AccessRule_update
--- PASS: TestAccAlicloudNas_AccessRule_update (2.27s)
PASS
> feat(nas): add datasource access groups

- CHANGELOG.md
- alicloud/common.go
- alicloud/errors.go
- alicloud/resource_alicloud_instance.go
- alicloud/resource_alicloud_security_group.go
- alicloud/resource_alicloud_security_group_rule.go
- alicloud/resource_alicloud_security_group_test.go
- alicloud/service_alicloud_ecs.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSecurityGroup -timeout=240m
=== RUN   TestAccAlicloudSecurityGroupRulesDataSourceWithDirection
--- PASS: TestAccAlicloudSecurityGroupRulesDataSourceWithDirection (20.94s)
=== RUN   TestAccAlicloudSecurityGroupRulesDataSourceWithGroupId
--- PASS: TestAccAlicloudSecurityGroupRulesDataSourceWithGroupId (24.03s)
=== RUN   TestAccAlicloudSecurityGroupRulesDataSourceWithNic_Type
--- PASS: TestAccAlicloudSecurityGroupRulesDataSourceWithNic_Type (9.65s)
=== RUN   TestAccAlicloudSecurityGroupRulesDataSourceWithPolicy
--- PASS: TestAccAlicloudSecurityGroupRulesDataSourceWithPolicy (20.10s)
=== RUN   TestAccAlicloudSecurityGroupRulesDataSourceWithIp_Protocol
--- PASS: TestAccAlicloudSecurityGroupRulesDataSourceWithIp_Protocol (20.62s)
=== RUN …
```
> Add waiting method to ensure the security group status is ok

- CHANGELOG.md
- alicloud/data_source_alicloud_dns_domains.go
- alicloud/data_source_alicloud_dns_groups.go
- alicloud/data_source_alicloud_dns_records.go
- alicloud/data_source_alicloud_dns_records_test.go
- alicloud/resource_alicloud_dns.go
- alicloud/resource_alicloud_dns_group.go
- alicloud/resource_alicloud_dns_record.go
- alicloud/resource_alicloud_slb_test.go
- alicloud/service_alicloud_dns.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDns -timeout=240m
=== RUN   TestAccAlicloudDnsDomainsDataSource_ali_domain
--- PASS: TestAccAlicloudDnsDomainsDataSource_ali_domain (5.96s)
=== RUN   TestAccAlicloudDnsDomainsDataSource_group_name_regex
--- PASS: TestAccAlicloudDnsDomainsDataSource_group_name_regex (5.62s)
=== RUN   TestAccAlicloudDnsDomainsDataSource_instance_id
--- PASS: TestAccAlicloudDnsDomainsDataSource_instance_id (5.69s)
=== RUN   TestAccAlicloudDnsDomainsDataSource_version_code
--- PASS: TestAccAlicloudDnsDomainsDataSource_version_code (5.93s)
=== RUN   TestAccAlicloudDnsDomainsDataSource_all
--- PASS: TestAccAlicloudDnsDomainsDataSource_all (4.43s)
=== RUN   TestAccAlicloudDnsGroupsDataSource_nameregexAll
--- PASS: …
```
> Make dns resource code more standard

- alicloud/resource_alicloud_db_instance_test.go
```
/usr/local/Cellar/go/1.11.1/libexec/bin/go test -c -o /private/var/folders/tt/t72n_q9s77l82s54_c_73rsc0000gn/T/___TestAccAlicloudDBInstance_CreateWithParameter_in_github_com_terraform_providers_terraform_provider_alicloud_alicloud github.com/terraform-providers/terraform-provider-alicloud/alicloud #gosetup
/usr/local/Cellar/go/1.11.1/libexec/bin/go tool test2json -t /private/var/folders/tt/t72n_q9s77l82s54_c_73rsc0000gn/T/___TestAccAlicloudDBInstance_CreateWithParameter_in_github_com_terraform_providers_terraform_provider_alicloud_alicloud -test.v -test.run ^TestAccAlicloudDBInstance_CreateWithParameter$ #gosetup
=== RUN   TestAccAlicloudDBInstance_CreateWithParameter
--- PASS: …
```
> fix rds instance parameter test case issue

- CHANGELOG.md
- alicloud/errors.go
- alicloud/import_alicloud_db_connection_test.go
- alicloud/resource_alicloud_db_connection.go
- alicloud/resource_alicloud_db_connection_test.go
- alicloud/service_alicloud_ecs.go
- alicloud/service_alicloud_rds.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDBConnection -timeout=240m
=== RUN   TestAccAlicloudDBConnection_import
--- PASS: TestAccAlicloudDBConnection_import (332.07s)
=== RUN   TestAccAlicloudDBConnection_basic
--- PASS: TestAccAlicloudDBConnection_basic (675.54s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	1007.673s
```
> Make db_connection resource code more standard

- CHANGELOG.md
- alicloud/common.go
- alicloud/data_source_alicloud_actiontrail.go
- alicloud/data_source_alicloud_actiontrail_test.go
- alicloud/data_source_alicloud_zones.go
- alicloud/data_source_alicloud_zones_test.go
- alicloud/resource_alicloud_slb_test.go
- website/alicloud.erb
- website/docs/d/actiontrails.html.markdown
- website/docs/d/zones.html.markdown
- website/docs/r/fc_function.html.markdown
- website/docs/r/fc_service.html.markdown
- website/docs/r/fc_trigger.html.markdown
- website/docs/r/slb.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudZones -timeout=240m
--- PASS: TestAccAlicloudZonesDataSource_basic (4.86s)
--- PASS: TestAccAlicloudZonesDataSource_filter (7.02s)
--- PASS: TestAccAlicloudZonesDataSource_unitRegion (4.69s)
--- PASS: TestAccAlicloudZonesDataSource_multiZone (1.91s)
=== RUN   TestAccAlicloudZonesDataSource_chargeType
--- PASS: TestAccAlicloudZonesDataSource_chargeType (2.30s)
=== RUN   TestAccAlicloudZonesDataSource_slb
--- PASS: TestAccAlicloudZonesDataSource_slb (6.31s)
=== RUN   TestAccAlicloudZonesDataSource_enable_details
--- PASS: …
```
> Add  for alicloud_zones and support retrieving slb slave zones

- alicloud/data_source_alicloud_common_bandwidth_package_test.go
- alicloud/data_source_alicloud_common_bandwidth_packages.go
- alicloud/provider.go
- alicloud/service_alicloud_vpc.go
- website/alicloud.erb
- website/docs/d/common_bandwidth_packages.html.markdown
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCommonBandwidthPackagesDataSource -timeout=300m
=== RUN   TestAccAlicloudCommonBandwidthPackagesDataSource
--- PASS: TestAccAlicloudCommonBandwidthPackagesDataSource (8.32s)
=== RUN   TestAccAlicloudCommonBandwidthPackagesDataSourceEmpty
--- PASS: TestAccAlicloudCommonBandwidthPackagesDataSourceEmpty (2.97s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	11.348s
> Add Common Bandwidth Packages Datasource

- alicloud/data_source_alicloud_route_tables.go
- alicloud/data_source_alicloud_route_tables_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/route_tables.html.markdown
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRouteTablesDataSource -timeout=300m
=== RUN   TestAccAlicloudRouteTablesDataSourceBasic
--- PASS: TestAccAlicloudRouteTablesDataSourceBasic (20.29s)
=== RUN   TestAccAlicloudRouteTablesDataSourceNameRegex
--- PASS: TestAccAlicloudRouteTablesDataSourceNameRegex (19.99s)
=== RUN   TestAccAlicloudRouteTablesDataSourceIds
--- PASS: TestAccAlicloudRouteTablesDataSourceIds (19.36s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	59.688s
> Add Route Tables Datasource

- alicloud/resource_alicloud_cen_instance.go
- alicloud/service_alicloud_cen.go
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCenInstance
=== RUN   TestAccAlicloudCenInstancesDataSource_cen_id
--- PASS: TestAccAlicloudCenInstancesDataSource_cen_id (12.05s)
=== RUN   TestAccAlicloudCenInstancesDataSource_name_regex
--- PASS: TestAccAlicloudCenInstancesDataSource_name_regex (18.75s)
=== RUN   TestAccAlicloudCenInstancesDataSource_multi_cen_ids
--- PASS: TestAccAlicloudCenInstancesDataSource_multi_cen_ids (29.72s)
=== RUN   TestAccAlicloudCenInstancesDataSource_empty
--- PASS: TestAccAlicloudCenInstancesDataSource_empty (4.09s)
=== RUN   TestAccAlicloudCenInstanceAttachment_importBasic
--- PASS: TestAccAlicloudCenInstanceAttachment_importBasic (47.11s)
=== RUN   TestAccAlicloudCenInstance_importBasic
--- PASS: TestAccAlicloudCenInstance_importBasic (10.53s)
=== …
> return after the instance deleted when destroy the resource cen instance

- CHANGELOG.md
- alicloud/common.go
- alicloud/errors.go
- alicloud/resource_alicloud_cen_instance.go
- alicloud/service_alicloud_cen.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCen -timeout=240m
--- PASS: TestAccAlicloudCenBandwidthLimitsDataSource_instance_id (111.49s)
=== RUN   TestAccAlicloudCenBandwidthLimitsDataSource_empty
--- PASS: TestAccAlicloudCenBandwidthLimitsDataSource_empty (1.32s)
=== RUN   TestAccAlicloudCenBandwidthPackagesDataSource_instance_id
--- PASS: TestAccAlicloudCenBandwidthPackagesDataSource_instance_id (16.57s)
=== RUN   TestAccAlicloudCenBandwidthPackagesDataSource_bandwidth_package_nameRegex
--- PASS: TestAccAlicloudCenBandwidthPackagesDataSource_bandwidth_package_nameRegex (10.98s)
=== RUN   TestAccAlicloudCenBandwidthPackagesDataSource_multi_bandwith_packages
--- PASS: …
```
> Add wait method for cen instance

- CHANGELOG.md
- alicloud/resource_alicloud_disk.go
- alicloud/resource_alicloud_disk_attachment.go
- alicloud/service_alicloud_cen.go
- alicloud/service_alicloud_ecs.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudDisk  -timeout=240m
=== RUN   TestAccAlicloudDisksDataSource_ids
--- PASS: TestAccAlicloudDisksDataSource_ids (68.14s)
=== RUN   TestAccAlicloudDisksDataSource_name_regex
--- PASS: TestAccAlicloudDisksDataSource_name_regex (69.21s)
=== RUN   TestAccAlicloudDisksDataSource_type
--- PASS: TestAccAlicloudDisksDataSource_type (67.16s)
=== RUN   TestAccAlicloudDisksDataSource_category
--- PASS: TestAccAlicloudDisksDataSource_category (67.33s)
=== RUN   TestAccAlicloudDisksDataSource_encrypted
--- PASS: TestAccAlicloudDisksDataSource_encrypted (72.10s)
=== RUN   TestAccAlicloudDisksDataSource_instance_id
--- PASS: TestAccAlicloudDisksDataSource_instance_id (192.65s)
=== RUN   TestAccAlicloudDisksDataSource_tags
--- PASS: …
```
> Add wait method for disk and disk attachment

- alicloud/data_source_alicloud_route_entries.go
- alicloud/data_source_alicloud_route_entries_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/route_entries.html.markdown
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudRouteEntries -timeout=300m
=== RUN   TestAccAlicloudRouteEntriesDataSourceBasic
--- PASS: TestAccAlicloudRouteEntriesDataSourceBasic (158.16s)
=== RUN   TestAccAlicloudRouteEntriesDataSourceRouteEntryType
--- PASS: TestAccAlicloudRouteEntriesDataSourceRouteEntryType (161.10s)
=== RUN   TestAccAlicloudRouteEntriesDataSourceCidrBlock
--- PASS: TestAccAlicloudRouteEntriesDataSourceCidrBlock (155.18s)
=== RUN   TestAccAlicloudRouteEntriesDataSourceInstanceId
--- PASS: TestAccAlicloudRouteEntriesDataSourceInstanceId (160.87s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	635.366s
> Add Route Entries Datasource​

- CHANGELOG.md
- alicloud/resource_alicloud_ram_user.go
- alicloud/resource_alicloud_ram_user_test.go
- alicloud/service_alicloud_ram.go
- website/docs/d/ram_users.html.markdown
- website/docs/r/ram_user.html.markdown
=== RUN   TestAccAlicloudRamUser_basic
--- PASS: TestAccAlicloudRamUser_basic (3.70s)
PASS
=== RUN   TestAccAlicloudRamUsersDataSource_for_group
--- PASS: TestAccAlicloudRamUsersDataSource_for_group (4.49s)
=== RUN   TestAccAlicloudRamUsersDataSource_for_policy
--- PASS: TestAccAlicloudRamUsersDataSource_for_policy (4.52s)
=== RUN   TestAccAlicloudRamUsersDataSource_for_all
--- PASS: TestAccAlicloudRamUsersDataSource_for_all (0.67s)
=== RUN   TestAccAlicloudRamUsersDataSource_user_name_regex
--- PASS: TestAccAlicloudRamUsersDataSource_user_name_regex (2.08s)
=== RUN   TestAccAlicloudRamUsersDataSource_empty
--- PASS: TestAccAlicloudRamUsersDataSource_empty (0.70s)
PASS
> set userId as d.Id() rather than userName

- alicloud/data_source_alicloud_nat_gateways.go
- alicloud/data_source_alicloud_nat_gateways_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/nat_gateways.html.markdown
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudNatGatewaysDataSource -timeout=300m
=== RUN   TestAccAlicloudNatGatewaysDataSourceBasic
--- PASS: TestAccAlicloudNatGatewaysDataSourceBasic (41.30s)
=== RUN   TestAccAlicloudNatGatewaysDataSourceNameRegex
--- PASS: TestAccAlicloudNatGatewaysDataSourceNameRegex (39.30s)
=== RUN   TestAccAlicloudNatGatewaysDataSourceIds
--- PASS: TestAccAlicloudNatGatewaysDataSourceIds (38.40s)
=== RUN   TestAccAlicloudNatGatewaysDataSourceVpcId
--- PASS: TestAccAlicloudNatGatewaysDataSourceVpcId (36.99s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	156.053s
> Add Nat Gateways Datasource

- alicloud/data_source_alicloud_cen_bandwidth_limits_test.go
- alicloud/data_source_alicloud_cen_bandwidth_packages_test.go
- alicloud/import_alicloud_cen_bandwidth_limit_test.go
- alicloud/import_alicloud_cen_bandwidth_package_attachment_test.go
- alicloud/import_alicloud_cen_bandwidth_package_test.go
- alicloud/resource_alicloud_cen_bandwidth_limit_test.go
- alicloud/resource_alicloud_cen_bandwidth_package_attachment_test.go
- alicloud/resource_alicloud_cen_bandwidth_package_test.go
$TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudCenBandwidth
--- SKIP: TestAccAlicloudCenBandwidthLimitsDataSource_instance_id (0.00s)
provider_test.go:60: Skipping unsupported account type International-Site. It only supports Domestic-Site.
=== RUN   TestAccAlicloudCenBandwidthLimitsDataSource_empty
--- SKIP: TestAccAlicloudCenBandwidthLimitsDataSource_empty (0.00s)
provider_test.go:60: Skipping unsupported account type International-Site. It only supports Domestic-Site.
=== RUN   TestAccAlicloudCenBandwidthPackagesDataSource_instance_id
--- SKIP: TestAccAlicloudCenBandwidthPackagesDataSource_instance_id (0.00s)
provider_test.go:60: Skipping unsupported account type International-Site. It only supports Domestic-Site. …
> Skipping bandwidth package related test for international site account

- alicloud/data_source_alicloud_snat_entries.go
- alicloud/data_source_alicloud_snat_entries_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/snat_entries.html.markdown
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSnatEntriesDataSource -timeout=300m
=== RUN   TestAccAlicloudSnatEntriesDataSourceBasic
--- PASS: TestAccAlicloudSnatEntriesDataSourceBasic (51.74s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	51.808s
> Add Snat Entries Datasource

- CHANGELOG.md
- alicloud/data_source_alicloud_forward_entries.go
- alicloud/data_source_alicloud_forward_entries_test.go
- alicloud/provider.go
- website/alicloud.erb
- website/docs/d/common_bandwidth_packages.html.markdown
- website/docs/d/forward_entries.html.markdown
- website/docs/d/nat_gateways.html.markdown
- website/docs/d/route_entries.html.markdown
- website/docs/d/route_tables.html.markdown
- website/docs/d/snat_entries.html.markdown
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudForwardEntriesDataSource -timeout=300m
=== RUN   TestAccAlicloudForwardEntriesDataSourceBasic
--- PASS: TestAccAlicloudForwardEntriesDataSourceBasic (53.35s)
=== RUN   TestAccAlicloudForwardEntriesDataSourceIds
--- PASS: TestAccAlicloudForwardEntriesDataSourceIds (52.97s)
=== RUN   TestAccAlicloudForwardEntriesDataSourceExternalIp
--- PASS: TestAccAlicloudForwardEntriesDataSourceExternalIp (65.96s)
=== RUN   TestAccAlicloudForwardEntriesDataSourceInternalIp
--- PASS: TestAccAlicloudForwardEntriesDataSourceInternalIp (54.25s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	226.581s
> Add Forward Entries Datasource

- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_db_instance_test.go
- alicloud/service_alicloud_rds.go
- website/docs/r/db_instance.html.markdown
Unit test:
go test -run TestAccAlicloudDBInstanceMonitor_vpc -v -timeout 9999s                                                                                                                                                     
=== RUN   TestAccAlicloudDBInstanceMonitor_vpc
--- PASS: TestAccAlicloudDBInstanceMonitor_vpc (116.99s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	117.058s
> added DB instance monitor provider

- CHANGELOG.md
- alicloud/resource_alicloud_oss_bucket.go
- website/docs/r/oss_bucket.html.markdown
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudOss -timeout=240m
--- PASS: TestAccAlicloudOssBucketObjectsDataSource_basic (20.37s)
=== RUN   TestAccAlicloudOssBucketObjectsDataSource_filterByPrefix
--- PASS: TestAccAlicloudOssBucketObjectsDataSource_filterByPrefix (21.10s)
=== RUN   TestAccAlicloudOssBucketObjectsDataSource_empty
--- PASS: TestAccAlicloudOssBucketObjectsDataSource_empty (17.10s)
--- PASS: TestAccAlicloudOssBucketsDataSource_basic (25.77s)
--- PASS: TestAccAlicloudOssBucketsDataSource_full (40.94s)
=== RUN   TestAccAlicloudOssBucketsDataSource_empty
--- PASS: TestAccAlicloudOssBucketsDataSource_empty …
```
> Deprecate bucket  logging_isenabled and fix referer_config diff bug

- alicloud/connectivity/regions.go
- alicloud/resource_alicloud_mongodb_instance_test.go
update mongodb instance test case multiAZ
test in "cn-beijing" region result :
=== RUN   TestAccAlicloudMongoDBInstance_import
--- PASS: TestAccAlicloudMongoDBInstance_import (364.96s)
=== RUN   TestAccAlicloudMongoDBInstance_classic
--- PASS: TestAccAlicloudMongoDBInstance_classic (1150.53s)
=== RUN   TestAccAlicloudMongoDBInstance_vpc
--- PASS: TestAccAlicloudMongoDBInstance_vpc (894.80s)
=== RUN   TestAccAlicloudMongoDBInstance_multiAZ
--- PASS: TestAccAlicloudMongoDBInstance_multiAZ (1291.16s)
=== RUN   TestAccAlicloudMongoDBInstance_multi_instance
--- PASS: TestAccAlicloudMongoDBInstance_multi_instance (614.82s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     4316.311s
> update mongodb instance test case multiAZ

- alicloud/errors.go
- alicloud/resource_alicloud_eip.go
- alicloud/resource_alicloud_vswitch.go
MacBook-Pro-2:terraform-provider-alicloud jince$ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEIP -timeout=300m
=== RUN   TestAccAlicloudEIPsDataSource
--- PASS: TestAccAlicloudEIPsDataSource (4.11s)
=== RUN   TestAccAlicloudEIPsDataSourceIPAddresses
--- PASS: TestAccAlicloudEIPsDataSourceIPAddresses (3.64s)
=== RUN   TestAccAlicloudEIPsDataSourceBoth
--- PASS: TestAccAlicloudEIPsDataSourceBoth (3.92s)
=== RUN   TestAccAlicloudEIPsDataSourceEmpty
--- PASS: TestAccAlicloudEIPsDataSourceEmpty (0.50s)
=== RUN   TestAccAlicloudEIP_importBasic
--- PASS: TestAccAlicloudEIP_importBasic (1.96s)
--- PASS: TestAccAlicloudEIPAssociation (182.12s)
=== RUN   TestAccAlicloudEIPAssociation_slb
--- PASS: TestAccAlicloudEIPAssociation_slb (36.05s)
=== RUN …
> Fix Eip And VSwitch Token

- alicloud/resource_alicloud_vpc.go
Add new `resource_group_id` parameter, creating VPC for the specific resource group.
example:
```provider "alicloud" {}
resource "alicloud_vpc" "vpc" {
name       = "example-vpc"
cidr_block = "192.168.0.0/16"
resource_group_id = "rg-[resource-group-id]"
}```
> `resource group` support for creating new VPC

- alicloud/extension_mongodb.go
- alicloud/import_alicloud_mongodb_sharding_instance_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_mongodb_instance_test.go
- alicloud/resource_alicloud_mongodb_sharding_instance.go
- alicloud/resource_alicloud_mongodb_sharding_instance_test.go
- alicloud/resource_alicloud_vswitch_test.go
- alicloud/service_alicloud_mongodb.go
- website/alicloud.erb
- website/docs/r/mongodb_sharding_instance.html.markdown
add MongoDB sharding instance support
the test result:
=== RUN   TestAccAlicloudMongoDBShardingInstance_import
--- PASS: TestAccAlicloudMongoDBShardingInstance_import (781.59s)
=== RUN   TestAccAlicloudMongoDBShardingInstance_classic
--- PASS: TestAccAlicloudMongoDBShardingInstance_classic (1081.40s)
=== RUN   TestAccAlicloudMongoDBShardingInstance_vpc
--- PASS: TestAccAlicloudMongoDBShardingInstance_vpc (1115.70s)
=== RUN   TestAccAlicloudMongoDBShardingInstance_multi_instance
--- PASS: TestAccAlicloudMongoDBShardingInstance_multi_instance (1122.78s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     4101.500s
> add mongodb sharding instance support

- alicloud/resource_alicloud_db_backup_policy.go
- website/docs/r/db_backup_policy.html.markdown
1. if log_retention_period doesn't input, it defaults to 0. To string will be "0", that will get error code `InvalidLogBackupRetentionPeriod.Malformed`.
2. when log_backup doesn't input and PGDB instance is a single node instance, (basic edition instance doesn't support log_backup ), there will still have diff after terraform apply operation.
the test case run result :
--- PASS: TestAccAlicloudDBBackupPolicy_update (137.89s)
PASS
> fixed DB log backup policy bug when the log_retention_period does not input.

- alicloud/errors.go
- alicloud/service_alicloud_elasticsearch.go
Received the new error code "CssCheckUpdowngradeError" and ignored it when SDK retried to fetch api.
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudElasticsearchInstance_upgrade -timeout=300m
=== RUN   TestAccAlicloudElasticsearchInstance_upgrade
--- PASS: TestAccAlicloudElasticsearchInstance_upgrade (6888.74s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud 6888.789s
> Modified the error code returned when timeout of upgrading instance.

- alicloud/data_source_alicloud_db_instances.go
- alicloud/import_alicloud_db_backup_policy_test.go
- alicloud/resource_alicloud_db_backup_policy_test.go
improve rds db backup policy test case
test result:
Fri Apr 26 17:20:53 CST 2019 === RUN   TestAccAlicloudDBBackupPolicy_import
Fri Apr 26 17:22:15 CST 2019 --- PASS: TestAccAlicloudDBBackupPolicy_import (81.35s)
Fri Apr 26 17:22:15 CST 2019 === RUN   TestAccAlicloudDBBackupPolicy_mysql
Fri Apr 26 17:24:12 CST 2019 --- PASS: TestAccAlicloudDBBackupPolicy_mysql (117.29s)
Fri Apr 26 17:24:12 CST 2019 === RUN   TestAccAlicloudDBBackupPolicy_pgdb_high_edition
Fri Apr 26 17:29:27 CST 2019 --- PASS: TestAccAlicloudDBBackupPolicy_pgdb_high_edition (315.32s)
Fri Apr 26 17:29:27 CST 2019 === RUN   TestAccAlicloudDBBackupPolicy_pgdb_basic_edition
Fri Apr 26 17:34:34 CST 2019 --- PASS: TestAccAlicloudDBBackupPolicy_pgdb_basic_edition (306.99s)
Fri Apr 26 17:34:34 CST 2019 === RUN …
> improve db backup policy test case

- alicloud/data_source_alicloud_db_instances_test.go
rds datasource test case remove connection mode check.
the parameter `connection_mode` has not stable default value. It's `Standard` at `cn-hangzhou` zone , but at `ap-south-1 ` zone it is `Safe`.
the test result:
2019/05/08 
--- PASS: TestAccAlicloudDBInstancesDataSource (117.40s)
PASS
> rds datasource test case remove connection mode check

- alicloud/resource_alicloud_mongodb_sharding_instance.go
- alicloud/resource_alicloud_mongodb_sharding_instance_test.go
- alicloud/service_alicloud_mongodb.go
- website/docs/r/mongodb_sharding_instance.html.markdown
mongodb sharding instance add backup policy support. 
the test result:
Wed May  8 16:31:41 CST 2019 === RUN   TestAccAlicloudMongoDBShardingInstance_classic
Wed May  8 16:47:58 CST 2019 --- PASS: TestAccAlicloudMongoDBShardingInstance_classic (977.16s)
Wed May  8 16:47:58 CST 2019 === RUN   TestAccAlicloudMongoDBShardingInstance_vpc
Wed May  8 17:07:10 CST 2019 --- PASS: TestAccAlicloudMongoDBShardingInstance_vpc (1151.77s)
Wed May  8 17:07:10 CST 2019 === RUN   TestAccAlicloudMongoDBShardingInstance_multi_instance
Wed May  8 17:25:49 CST 2019 --- PASS: TestAccAlicloudMongoDBShardingInstance_multi_instance (1118.62s)
> mongodb sharding instance add backup policy support

- website/docs/r/slb.html.markdown
> add note for SLB that intl account does not support  creating PrePaid instance

- alicloud/resource_alicloud_cs_swarm_test.go
- alicloud/resource_alicloud_instance.go
- alicloud/resource_alicloud_instance_test.go
- alicloud/resource_alicloud_ots_table.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudInstance -timeout=240m
--- PASS: TestAccAlicloudInstanceTypesDataSource_basic (3.37s)
=== RUN   TestAccAlicloudInstanceTypesDataSource_gpu
--- PASS: TestAccAlicloudInstanceTypesDataSource_gpu (4.12s)
=== RUN   TestAccAlicloudInstanceTypesDataSource_empty
--- PASS: TestAccAlicloudInstanceTypesDataSource_empty (1.34s)
=== RUN   TestAccAlicloudInstanceTypesDataSource_k8sSpec
--- PASS: TestAccAlicloudInstanceTypesDataSource_k8sSpec (3.51s)
=== RUN   TestAccAlicloudInstanceTypesDataSource_k8sFamily
--- PASS: TestAccAlicloudInstanceTypesDataSource_k8sFamily (1.35s)
=== RUN   TestAccAlicloudInstancesDataSourceBasic
--- PASS: TestAccAlicloudInstancesDataSourceBasic (251.37s)
=== RUN …
```
> change ecs instance instance_charge_type modifying position

- website/docs/r/mongodb_instance.html.markdown
- website/docs/r/mongodb_sharding_instance.html.markdown
the mongo instance's parameter `backup_time` default to a random time, like "23:00Z-24:00Z".
> update mongodb instance resource docment.

- alicloud/resource_alicloud_mongodb_instance.go
- alicloud/resource_alicloud_mongodb_instance_test.go
- alicloud/resource_alicloud_mongodb_sharding_instance.go
- alicloud/resource_alicloud_mongodb_sharding_instance_test.go
- alicloud/service_alicloud_mongodb.go
fix reset account_password don't work
the test result:
Mon May 27 19:50:20 CST 2019 === RUN   TestAccAlicloudMongoDBInstance_classic
Mon May 27 20:01:44 CST 2019 --- PASS: TestAccAlicloudMongoDBInstance_classic (683.47s)
Mon May 27 20:01:44 CST 2019 === RUN   TestAccAlicloudMongoDBInstance_vpc
Mon May 27 20:24:39 CST 2019 --- PASS: TestAccAlicloudMongoDBInstance_vpc (1375.41s)
Mon May 27 20:24:39 CST 2019 === RUN   TestAccAlicloudMongoDBInstance_multiAZ
Mon May 27 20:33:34 CST 2019 --- PASS: TestAccAlicloudMongoDBInstance_multiAZ (534.72s)
Mon May 27 20:33:34 CST 2019 === RUN   TestAccAlicloudMongoDBInstance_multi_instance
Mon May 27 20:54:46 CST 2019 --- PASS: TestAccAlicloudMongoDBInstance_multi_instance (1272.18s)
Tue May 28 18:24:22 CST 2019 === RUN …
> fix reset account_password don't work

- alicloud/resource_alicloud_cms_alarm.go
- alicloud/resource_alicloud_cms_alarm_test.go
- alicloud/service_alicloud_cms.go
- website/docs/r/cms_alarm.html.markdown
This adds webhook support for CMS alarms by using the attribute `webhook`.
Unit tests have been accordingly extended. All pass:
```
$ go test -run TestAccAlicloudCmsAlarm -v -timeout 9999s                                                                                                                                                                     === RUN   TestAccAlicloudCmsAlarm_import
--- PASS: TestAccAlicloudCmsAlarm_import (10.02s)
=== RUN   TestAccAlicloudCmsAlarm_basic
--- PASS: TestAccAlicloudCmsAlarm_basic (6.71s)
=== RUN   TestAccAlicloudCmsAlarm_update
--- PASS: TestAccAlicloudCmsAlarm_update (12.64s)
=== RUN   TestAccAlicloudCmsAlarm_disable
--- PASS: TestAccAlicloudCmsAlarm_disable (7.15s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud …
```
> added webhook support for alarms

- alicloud/connectivity/config.go
- alicloud/provider.go
- alicloud/resource_alicloud_ram_account_password_policy.go
- alicloud/validators.go
- website/docs/index.html.markdown
This PR resolves issue #1068 
It adds `assume_role` inside provider block:
```hcl
provider "alicloud" {
assume_role {
role_arn = "acs:ram::ACCOUNT_ID:role/ROLE_NAME"
}
}
```
If provided with a role ARN, Terraform will attempt to assume this role using the supplied credentials.
> Add support for assume_role in provider block

- alicloud/resource_alicloud_ess_scalingconfiguration.go
- alicloud/resource_alicloud_ess_scalingconfiguration_test.go
--- PASS: TestAccAlicloudEssScalingConfiguration_basic (82.71s)
=== RUN   TestAccAlicloudEssScalingConfiguration_SystemDisk
--- PASS: TestAccAlicloudEssScalingConfiguration_SystemDisk (75.33s)
--- PASS: TestAccAlicloudEssScalingConfiguration_multiConfig (86.38s)
=== RUN   TestAccAlicloudEssScalingConfiguration_active
--- PASS: TestAccAlicloudEssScalingConfiguration_active (77.38s)
=== RUN   TestAccAlicloudEssScalingConfiguration_disable
--- PASS: TestAccAlicloudEssScalingConfiguration_disable (74.96s)
=== RUN   TestAccAlicloudEssScalingConfiguration_modify
--- PASS: TestAccAlicloudEssScalingConfiguration_modify (127.61s)
=== RUN …
> 修复scalingConfiguration传入base64的user_data时，和describe返回的信息不一致

- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_cs_managed_kubernetes.go
This PR will fix the issue addressed in #1281 .
OpenAPI has changed two fields in newly-created managed kubernetes cluster's describe API
* VSwitchID -> WorkerVSwitchIds
* WorkerInstanceType -> WorkerInstanceTypes
Now the terraform plugin is unable to fetch a correct VSwitchID and WorkerInstanceType for newly-created managed kubernetes clusters. The container service team is now working on the new field to replace, for now, we suppress the diff if OpenAPI return empty values for these two fields.
Workaround before this pr is released:
* comment out `worker_instance_types` and `vswitch_ids` in users' terraform template.
* take care when applying any existing cluster's template.
```bash
xh4n3@xh4n3:~/ops/terraform-managed% terraform apply
alicloud_cs_managed_kubernetes.k8s: Refreshing …
```
> temp fix no value returned by cs openapi

- alicloud/resource_alicloud_ess_scalinggroup.go
- alicloud/resource_alicloud_ess_scalinggroup_test.go
- website/docs/r/ess_scaling_group.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEssScalingGroup -timeout=300m
--- PASS: TestAccAlicloudEssScalingGroup_importBasic (29.57s)
--- PASS: TestAccAlicloudEssScalingGroup_basic (69.37s)
--- PASS: TestAccAlicloudEssScalingGroup_vpc (64.09s)
--- PASS: TestAccAlicloudEssScalingGroup_slb (100.58s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     263.676s
> Support attach & detach operation for loadbalancers and dbinstances.

- .travis.yml
- GNUmakefile
Since go module has been used, this PR is to propose to remove installing `govendor` packages and running `govendor status` command in CI.
Signed-off-by: imjoey <majunjiev@gmail.com>
> Remove govendor commands in CI

- CHANGELOG.md
- alicloud/resource_alicloud_oss_bucket.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudOss -timeout=240m
--- PASS: TestAccAlicloudOssBucketObjectsDataSource_basic (13.97s)
=== RUN   TestAccAlicloudOssBucketObjectsDataSource_versioning
--- SKIP: TestAccAlicloudOssBucketObjectsDataSource_versioning (0.00s)
provider_test.go:90: Skipping unsupported region cn-beijing. Supported regions: [ap-south-1].
--- PASS: TestAccAlicloudOssBucketsDataSource_basic (14.45s)
=== RUN   TestAccAlicloudOssBucketsDataSource_sserule
--- PASS: TestAccAlicloudOssBucketsDataSource_sserule (9.17s)
=== RUN   TestAccAlicloudOssBucketsDataSource_versioning
--- SKIP: TestAccAlicloudOssBucketsDataSource_versioning (0.00s)
provider_test.go:90: …
```
> fix(oss_bucket): fix oss bucket deleting timeout error

- website/docs/d/nas_mount_targets.html.markdown
- website/docs/d/ons_instances.html.markdown
- website/docs/r/network_interface_attachment.html.markdown
- website/docs/r/oss_bucket.html.markdown
- website/docs/r/pvtz_zone_record.html.markdown
- website/docs/r/ram_group_membership.html.markdown
- website/docs/r/slb_acl.html.markdown
The previous PR-#1415 formatted plenty of HCL codes in docs. With the release of v1.52.0, I found that some of inline HCL codes were not formatted yet. 
After some digs on it, I figured it out that the tool I built has two limitations, which may cause the codes failed formatted:
1. It works only when the HCL code are valid; (This is a feature to avoid meaningless formatting.)
2. Due to a upstream issue https://github.com/russross/blackfriday/issues/423 , my tool cannot precisely parse the markdown file with CRLF line endings (mostly in Windows format);
Changes proposed in this PR to resolve the failures caused by the limitations above:
* Set `\n` as the line ending in `r/nas_mount_targets.html.markdown` and `r/oss_bucket.html.markdown` instead of `\r\n`
* Fix the code in …
> improve(docs): Reformat abnormal inline HCL code in docs

- alicloud/resource_alicloud_db_instance.go
- alicloud/service_alicloud_rds.go
- website/docs/r/db_instance.html.markdown
tf文件设置一秒时，超时
tf文件设置正常时间，或者不设置，apply成功
> improve(rds): db_instance resource supports timeouts setting.

- alicloud/data_source_alicloud_cs_managed_kubernetes_clusters.go
- alicloud/data_source_alicloud_cs_managed_kubernetes_clusters_test.go
- alicloud/diff_suppress_funcs.go
- alicloud/resource_alicloud_cs_managed_kubernetes.go
- alicloud/resource_alicloud_cs_managed_kubernetes_test.go
- go.mod
- go.sum
- vendor/github.com/denverdino/aliyungo/cs/clusters.go
- vendor/github.com/denverdino/aliyungo/ecs/disks.go
- vendor/github.com/denverdino/aliyungo/ecs/router_interface.go
- vendor/github.com/denverdino/aliyungo/ecs/vpcs.go
- vendor/github.com/denverdino/aliyungo/util/encoding.go
- vendor/modules.txt
- website/docs/d/cs_managed_kubernetes_clusters.html.markdown
- website/docs/r/cs_managed_kubernetes.html.markdown
Container Service's API has changed, DescribeCluster API will no longer return cluster details in `Parameter` field.
This pr:
1. removes code which uses this Parameter field, a lot of output fields were deleted
2. add multiple az support for managed kubernetes
3. add `force_update` field to let user make sure when he/she is changing `worker_instance_types` or `vswitch_ids`
> remove empty fields in managed k8s, add force_update, add multiple az support

- alicloud/data_source_alicloud_instance_types.go
- examples/build-lnmp/main.tf
- website/docs/index.html.markdown
To avoid the error:
---
terraform 0.12checklist
In Terraform 0.12, resource names must start with a letter. To fix this, rename the resource in the configuration and then use `terraform state mv` to mirror that name change in the state.
---
I did the following:
```
git grep 2c4g | awk -F':' '{print $1}' | xargs sed -i '' 's/2c4g/c2g4/g'
```
> Rename resource name that is not start with a letter

- alicloud/data_source_alicloud_ons_groups_test.go
- alicloud/resource_alicloud_ons_group_test.go
fix the create group error in testcase
the reason of creating group failure is that the length of groupid is too long.
> fix(ons): fix the create group error in testcase

- alicloud/data_source_alicloud_dns_records.go
- alicloud/resource_alicloud_dns_record.go
- website/docs/d/dns_records.html.markdown
- website/docs/r/dns_record.html.markdown
Update below:
> According to [this](https://help.aliyun.com/document_detail/29807.html?spm=a2c4g.11186623.2.16.86ef10960KSKAG#h2-u57FAu7840u7EBFu8DEF1) doc, there are multiple routing rules missed in [alicloud_dns_record](https://www.terraform.io/docs/providers/alicloud/r/dns_record.html#routing) resource, such like:
> 
> drpeng
> btvn
> ...
> It would be great if we complete the routing types list.
> Add missing routing rules for alicloud_dns_record

- alicloud/resource_alicloud_ram_policy.go
According to the documentation, you can set `force = true` to resources the resource can be deleted more easily. However, if you want to set it for an existing resource that you don't want to delete yet, an error occurs:
```
Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_ram_policy.go:143: Resource AssumePowerUserRoleProduction CreatePolicyVersion Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
SDK.ServerError
ErrorCode: MissingParameter
Recommend: 
RequestId: 733B529F-1C31-40DE-8E9A-11107C28FE17
Message: Parameter PolicyDocument is required.
```
The PolicyDocument request parameter is not set currently in `buildAlicloudRamPolicyUpdateArgs()` starting from line 336 in resource_alicloud_ram_policy.go. This PR ensures that it is always set, also if you didn't change the …
> Always set PolicyDocument for RAM policy update

- alicloud/data_source_alicloud_dns_resolution_lines.go
- alicloud/data_source_alicloud_dns_resolution_lines_test.go
- alicloud/provider.go
- website/docs/d/dns_resolution_lines.html.markdown
- website/docs/r/dns_record.html.markdown
Because there must return back some support lines after inputing any arbitrary values of  domain_name, user_client_ip and lang, these variables can not be an only filter for fakeConfig, so cancelling corresponding fakeConfigs.
Test Result : 
=== RUN   TestAccAlicloudDnsDomainsDataSource
--- PASS: TestAccAlicloudDnsDomainsDataSource (98.85s)
=== RUN   TestAccAlicloudDnsGroupsDataSource
--- PASS: TestAccAlicloudDnsGroupsDataSource (34.49s)
=== RUN   TestAccAlicloudDnsRecordsDataSource
--- PASS: TestAccAlicloudDnsRecordsDataSource (130.03s)
=== RUN   TestAccAlicloudDnsSupportLinesDataSource
--- PASS: TestAccAlicloudDnsSupportLinesDataSource (79.37s)
=== RUN   TestAccAlicloudDnsGroup_basic
--- PASS: TestAccAlicloudDnsGroup_basic (13.33s)
=== RUN   TestAccAlicloudDnsRecord_basic
--- PASS: …
> add data_source_alicloud_support_lines

- alicloud/data_source_alicloud_route_tables.go
- alicloud/data_source_alicloud_route_tables_test.go
- website/docs/d/route_tables.html.markdown
Test Result: 
go test -v ./alicloud -run=TestAccAlicloudRoute -timeout=300m
=== RUN   TestAccAlicloudRouteEntriesDataSourceBasic
--- PASS: TestAccAlicloudRouteEntriesDataSourceBasic (152.50s)
=== RUN   TestAccAlicloudRouteTablesDataSourceBasic
--- PASS: TestAccAlicloudRouteTablesDataSourceBasic (47.08s)
=== RUN   TestAccAlicloudRouterInterfacesDataSourceBasic
--- PASS: TestAccAlicloudRouterInterfacesDataSourceBasic (113.18s)
=== RUN   TestAccAlicloudRouteEntryInstance
--- PASS: TestAccAlicloudRouteEntryInstance (114.98s)
=== RUN   TestAccAlicloudRouteEntryInterface
--- PASS: TestAccAlicloudRouteEntryInterface (31.29s)
=== RUN   TestAccAlicloudRouteEntryNatGateway
--- PASS: TestAccAlicloudRouteEntryNatGateway (51.01s)
=== RUN   TestAccAlicloudRouteEntryMulti
--- PASS: …
> Add resource_group_id to data_source_alicloud_route_tables

- alicloud/resource_alicloud_ess_scalingconfiguration.go
- alicloud/resource_alicloud_ess_scalingconfiguration_test.go
- website/docs/r/ess_scaling_configuration.html.markdown
Add password to resource_alicloud_ess_scalingconfiguration(CreateScalingConfiguration: https://help.aliyun.com/document_detail/106455.html), the corresponding data source method do not support password checking(DescribeScalingConfigurations: https://help.aliyun.com/document_detail/106456.html)
Test result: 
go test -v ./alicloud -run=TestAccAlicloudEssScaling -timeout=300m
--- PASS: TestAccAlicloudEssScalingconfigurationsDataSource (77.26s)
--- PASS: TestAccAlicloudEssScalinggroupsDataSource (61.29s)
--- PASS: TestAccAlicloudEssScalingrulesDataSource (112.80s)
=== RUN   TestAccAlicloudEssScalingConfigurationUpdate
--- PASS: …
> Add password to resource_alicloud_ess_scalingconfiguration

- alicloud/data_source_alicloud_slb_acls.go
- alicloud/data_source_alicloud_slb_acls_test.go
- alicloud/data_source_alicloud_slb_ca_certificates.go
- alicloud/data_source_alicloud_slb_ca_certificates_test.go
- alicloud/data_source_alicloud_slbs.go
- alicloud/data_source_alicloud_slbs_test.go
- alicloud/data_source_alicloud_vpcs.go
- alicloud/data_source_alicloud_vpcs_test.go
- alicloud/data_source_alicloud_vswitches.go
- alicloud/data_source_alicloud_vswitches_test.go
- website/docs/d/slb_acls.html.markdown
- website/docs/d/slb_ca_certificates.html.markdown
- website/docs/d/slbs.html.markdown
- website/docs/d/vpcs.html.markdown
- website/docs/d/vswitches.html.markdown
Test Result:
1. 
go test -v ./alicloud -run=TestAccAlicloudVpcs -timeout=300m
=== RUN   TestAccAlicloudVpcsDataSourceBasic
--- PASS: TestAccAlicloudVpcsDataSourceBasic (86.32s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     88.243s
2.
go test -v ./alicloud -run=TestAccAlicloudVSwitches -timeout=300m
=== RUN   TestAccAlicloudVSwitchesDataSourceBasic
--- PASS: TestAccAlicloudVSwitchesDataSourceBasic (160.57s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     162.522s
3, 
go test -v ./alicloud -run=TestAccAlicloudSlbs -timeout=300m
=== RUN   TestAccAlicloudSlbsDataSource
--- PASS: TestAccAlicloudSlbsDataSource (212.64s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     214.600s
4. 
go …
> Add resource_group_id to 5 data_datasources

- alicloud/data_source_alicloud_kvstore_instance_classes_test.go
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudKVStoreInstanceClasses -timeout=1200m
=== RUN   TestAccAlicloudKVStoreInstanceClasses
--- PASS: TestAccAlicloudKVStoreInstanceClasses (158.92s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud     158.985s
```
> improve(kvstore_instance_classess): improve test case error caused by no stock

- alicloud/data_source_alicloud_cs_serverless_kubernetes_clusters.go
- alicloud/resource_alicloud_cs_serverless_kubernetes.go
Container Service endpoint `/clusters` does not return information about whether or not a private zone was configured for the cluster. Currently, if a cluster is created in Terraform with the `private_zone` property set to `true`, every deploy will cause a new cluster to be created as Golang booleans default to `false` and that property has `ForceNew` set to `true`.
Resolves #1866
> Do not assume `private_zone` is returned from API

- alicloud/resource_alicloud_mongodb_instance.go
fixes #1928 
This PR adds `replica_set_name` to the outputs for `alicloud_mongodb_instance`. Without this output it's not possible to connect to the mongodb instance in a lot of clients.
> adding replica_set_name to output from alicloud_mongodb_instance

- alicloud/resource_alicloud_cdn_domain_new.go
`okServerCertificate` is always `true` since it was set in [`resourceAlicloudCdnDomainReadNew`](https://github.com/terraform-providers/terraform-provider-alicloud/blob/ed309f497fc2414c39f7f957ddca10f4dd81ddfe/alicloud/resource_alicloud_cdn_domain_new.go#L288):
```
config[0] = map[string]interface{}{
"server_certificate":        certInfo.ServerCertificate,
"server_certificate_status": serverCertificateStatus,
"cert_name":                 certInfo.CertName,
"cert_type":                 certInfo.CertType,
}
```
If I understand the API right, I should be able to provide these configurations in HCL and the apply should still works:
```
resource "alicloud_cdn_domain_new" "foobar" {
domain_name = "foo.example.com"
cdn_type    = "web"
scope       = "domestic"
sources {
content = …
```
> fix(cdn_domain_new): constant timeout waiting for server cert

- alicloud/resource_alicloud_kms_ciphertext_test.go
- ci/pipeline.yml
- ci/tasks/run.sh
```
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudKmsCiphertext_ -timeout=1200m=== RUN   TestAccAlicloudKmsCiphertext_basic
=== PAUSE TestAccAlicloudKmsCiphertext_basic
=== RUN   TestAccAlicloudKmsCiphertext_validate
=== PAUSE TestAccAlicloudKmsCiphertext_validate
=== RUN   TestAccAlicloudKmsCiphertext_validate_withContext
=== PAUSE TestAccAlicloudKmsCiphertext_validate_withContext
=== CONT  TestAccAlicloudKmsCiphertext_basic
=== CONT  TestAccAlicloudKmsCiphertext_validate_withContext
=== CONT  TestAccAlicloudKmsCiphertext_validate
--- PASS: TestAccAlicloudKmsCiphertext_basic (1.96s)
--- PASS: TestAccAlicloudKmsCiphertext_validate (2.50s)
--- PASS: TestAccAlicloudKmsCiphertext_validate_withContext (2.64s)
PASS
ok      github.com/terraform-providers/terraform-provider-alicloud/alicloud …
```
> fix(kms): correct test case errors

- alicloud/resource_alicloud_ssl_vpn_client_cert.go
- alicloud/resource_alicloud_ssl_vpn_client_cert_test.go
- website/docs/r/ssl_vpn_client_cert.html.markdown
Added additional outputs to the `alicloud_ssl_vpn_client_cert` resource. They were already available on the API result, but weren't passed to the terraform resource outputs.
> add output to ssl vpn client cert

- alicloud/resource_alicloud_elasticsearch_instance.go
- alicloud/service_alicloud_elasticsearch.go
- website/docs/r/elasticsearch.html.markdown
1. basic
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudElasticsearchInstance_basic -timeout=300m
=== RUN   TestAccAlicloudElasticsearchInstance_basic
--- PASS: TestAccAlicloudElasticsearchInstance_basic (12203.07s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	12203.148s
2. multizone
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudElasticsearchInstance_multizone -timeout=300m
=== RUN   TestAccAlicloudElasticsearchInstance_multizone
--- PASS: TestAccAlicloudElasticsearchInstance_multizone (1665.73s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	1665.793s
3. version
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudElasticsearchInstance_version -timeout=300m
=== RUN   TestAccAlicloudElasticsearchInstance_version
--- …
> improve(elasticsearch): resource support to renew a PrePaid instance

- alicloud/resource_alicloud_instance.go
- go.sum
Found a bug when trying to create new instance with more than one security groups.
It was always taking the first securityGroupId from the list.
Change to append all securityGroupId into a list.
> Fix creating instance with multiple security groups

- alicloud/data_source_alicloud_elasticsearch_instances.go
- alicloud/data_source_alicloud_elasticsearch_instances_test.go
- alicloud/service_alicloud_elasticsearch.go
- alicloud/tags.go
- website/docs/d/elasticsearch.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudElasticsearchDataSource --timeout=300m
^@=== RUN   TestAccAlicloudElasticsearchDataSource
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@--- PASS: TestAccAlicloudElasticsearchDataSource (1667.44s)
PASS
ok    github.com/terraform-providers/terraform-provider-alicloud/alicloud  1667.506s
> improve(elasticsearch): data_source support tags

- alicloud/resource_alicloud_cms_site_monitor.go
- alicloud/resource_alicloud_cms_site_monitor_test.go
- alicloud/service_alicloud_cms.go
- go.sum
- website/docs/r/cms_sitemonitor.html.markdown
This PR adds support for attribute `isp_cities` in site_monitor.
For example:
```
resource "alicloud_cms_sitemonitor" "basic" {
address = "http://www.alibabacloud.com"
task_name = "tf-testAccCmsSiteMonitor_basic"
task_type = "HTTP"
interval = 5
isp_cities {
city = "546"
isp = "465"
}  
}
```
> added support for isp_cities in site_monitor

- alicloud/resource_alicloud_kms_secret.go
So that it doesn't show up in Terraform diffs.
> alicloud_kms_secret: mark secret_data as sensitive

- website/docs/r/cs_serverless_kubernetes.html.markdown
* `private_zone` - (Optional, ForceNew) Whether to create internet  eip for API Server. Default to false.
Enable Privatezone if you need to use the service discovery feature within the serverless cluster
> private_zone has the wrong description

- alicloud/resource_alicloud_adb_cluster.go
- alicloud/resource_alicloud_adb_cluster_test.go
- website/docs/r/adb_cluster.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudAdbCluster -timeout=1200m
=== RUN   TestAccAlicloudAdbClustersDataSource
--- PASS: TestAccAlicloudAdbClustersDataSource (1273.06s)
=== RUN   TestAccAlicloudAdbCluster
--- PASS: TestAccAlicloudAdbCluster (3849.90s)
=== RUN   TestAccAlicloudAdbClusterMulti
--- PASS: TestAccAlicloudAdbClusterMulti (1341.36s)
PASS
ok  	github.com/terraform-providers/terraform-provider-alicloud/alicloud	6464.383s
> ADB support scale in/out

- alicloud/resource_alicloud_alikafka_topic.go
Fix the bug: When first create topic with tags, tags info will be ignored.
> Fix alikafka topic tag crate bug

- alicloud/resource_alicloud_cs_serverless_kubernetes.go
- examples/serverless-kubernetes/outputs.tf
origin code missed security_group_id's declaration so we cannot reference this attribute.
> add missing "security_group_id" attribute declaration to schema

- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_managed_kubernetes.go
- website/docs/r/cs_kubernetes.html.markdown
- website/docs/r/cs_managed_kubernetes.html.markdown
fixes #2567 
This adds the necessary fields to support of service_account_issuer and api_audiences that enables Service Account Token Volume Projection. Required a bump of the aliyungo SDK.
I'm not sure about some of the `vendor`changes to alibaba-cloud-sdk-go, I suspect that it wasn't properly updated during https://github.com/terraform-providers/terraform-provider-alicloud/commit/9d6b2611c35252f24c3a131edeca4f0cfc5d63e6
> Support service_account_issuer and api_audiences in alicloud_cs_kubernetes and alicloud_cs_managed_kubernetes

- alicloud/resource_alicloud_elasticsearch_instance.go
- alicloud/resource_alicloud_elasticsearch_instance_test.go
- alicloud/service_alicloud_elasticsearch.go
- examples/elasticsearch/main.tf
- examples/elasticsearch/variables.tf
- website/docs/r/elasticsearch.html.markdown
elasticsearch instance support configuration 'client node' and 'protocol'
--- PASS: TestAccAlicloudElasticsearchInstance_basic (19685.08s)
PASS
--- PASS: TestAccAlicloudElasticsearchInstance_encrypt_disk (3666.08s)
PASS
--- PASS: TestAccAlicloudElasticsearchInstance_multi (3159.57s)
PASS
--- PASS: TestAccAlicloudElasticsearchInstance_multizone (3639.55s)
PASS
--- PASS: TestAccAlicloudElasticsearchInstance_version (6113.09s)
PASS
--- PASS: TestAccAlicloudElasticsearchInstance_client_node (8049.87s)
PASS
--- PASS: TestAccAlicloudElasticsearchInstance_https (10580.06s)
PASS
> elasticsearch instance support configuration 'client node' and 'protocol'

- alicloud/resource_alicloud_cs_kubernetes.go
- alicloud/resource_alicloud_cs_kubernetes_node_pool.go
- go.mod
- go.sum
- vendor/github.com/denverdino/aliyungo/cs/node_pool.go
- vendor/github.com/denverdino/aliyungo/ecs/instance_types.go
- vendor/modules.txt
- website/docs/d/cs_managed_kubernetes_clusters.html.markdown
- website/docs/r/cs_kubernetes.html.markdown
- website/docs/r/cs_managed_kubernetes.html.markdown
- website/docs/r/cs_serverless_kubernetes.html.markdown
托管版集群创建完成后，connections信息只输出了service_domain。terraform.tfstate
"connections": {
"api_server_internet": "https://xx",
"api_server_intranet": "https://xx",
"master_public_ip": "xx",
"service_domain": "xx"
}
EnableAutoScaling 这个字段的修改，是因为SDK中字段修改了。
更新了下文档。
> fix the managed k8s does not display connections information

- alicloud/resource_alicloud_db_account.go
This is to fix https://github.com/aliyun/terraform-provider-alicloud/issues/3075
> fix var name for account type in alicloud_db_account 

- website/docs/guides/getting-account.html.md
The Japan site of Alibaba Cloud is deprecated. This PR removes information on creating a new account on the site.
I will provide you with a summary of relevant news releases:
> The Alibaba Cloud Japan (JP) site stopped registration on 2020-06-25. Customers residing in Japan are now accepted in the international site.
https://jp.alibabacloud.com/notice/account-stop-20200619?spm=a21mg.8121077.6051337650.2.36e53e13hoLn5V
> It's going to stop service on 2021-03-31, and existing customers of the JP site must apply for account migration to the international site by 2021-02-26. If the user doesn't migrate the account, all of the data on the JP site will become unavailable.
https://jp.alibabacloud.com/notice/account-migration-20200924?spm=a21mg.8121077.6051337650.1.36e53e13hoLn5V
> Remove Japan site

- alicloud/resource_alicloud_alikafka_sasl_acl.go
- alicloud/resource_alicloud_alikafka_topic.go
- alicloud/service_alicloud_alikafka.go
- website/docs/r/alikafka_topic.html.markdown
1. Synchronize to create kafka topic
2. Retry to create or delete resource if encounters the flow control
> resource/alicloud_alikafka_topic: Supports setting self-define create timeout. 

- alicloud/extension_cms.go
- alicloud/resource_alicloud_cms_alarm.go
The statistics's value in resource "alicloud_cms_alarm" should be allowed to set as Value,Sum,Count.
In some product such as [API Gateway](https://www.alibabacloud.com/help/doc-detail/164689.htm),[Kafka](https://www.alibabacloud.com/help/doc-detail/165126.htm), the statistics of metrics should not be "Average", "Minimum", "Maximum" or "ErrorCodeMaximum".
> resource/alicloud_cms?alarm: Adds statistics more valid values: Value, Sum, Count

- alicloud/resource_alicloud_kvstore_instance.go
The problem: can't refresh `auto_renew` field
The `AutoRenew` field in API response is type string:
```
2020-11-25T11:16:29.042+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.102.0+6.4421b545: *************** DescribeInstanceAutoRenewalAttribute Response *************** 
2020-11-25T11:16:29.042+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.102.0+6.4421b545: HTTP/1.1 200 OK
2020-11-25T11:16:29.042+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.102.0+6.4421b545: Access-Control-Max-Age: 172800
2020-11-25T11:16:29.042+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.102.0+6.4421b545: X-Acs-Request-Id: 53DBD88B-AD15-4096-93FF-5E957978B772
2020-11-25T11:16:29.042+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.102.0+6.4421b545: Content-Length: 224
2020-11-25T11:16:29.042+0800 …
```
> resource/alicloud_kvstore_instance: Converts auto_renew attribute to bool before saving

- alicloud/resource_alicloud_elasticsearch_instance.go
- alicloud/service_alicloud_elasticsearch.go
Fix:Close kibana public network was not applied at creation
> resource/alicloud_elasitcsearch_instance: Fixes the enable_kibana_private_network  is not effect error when the first creation.

- alicloud/data_source_alicloud_ess_scalingconfigurations.go
- alicloud/data_source_alicloud_ess_scalingconfigurations_test.go
- alicloud/resource_alicloud_ess_scalingconfiguration.go
- alicloud/resource_alicloud_ess_scalingconfiguration_test.go
- alicloud/service_alicloud_ess.go
- website/docs/d/ess_scaling_configurations.html.markdown
- website/docs/r/ess_scaling_configuration.html.markdown
ACC=1 go test ./alicloud -v -run=TestAccAlicloudEssScaling -timeout=300m
--- PASS: TestAccAlicloudEssScalingconfigurationsDataSource (89.40s)
--- PASS: TestAccAlicloudEssScalinggroupsDataSource (70.61s)
--- PASS: TestAccAlicloudEssScalingrulesDataSource (97.35s)
=== RUN   TestAccAlicloudEssScalingConfigurationUpdate
--- PASS: TestAccAlicloudEssScalingConfigurationUpdate (174.39s)
=== RUN   TestAccAlicloudEssScalingConfigurationMulti
--- PASS: TestAccAlicloudEssScalingConfigurationMulti (45.93s)
--- PASS: TestAccAlicloudEssScalingGroup_basic (102.94s)
=== RUN …
> resource/alicloud_ess_scalingconfiguration: Adds new attributes `performance_level` and `system_disk_performance_level` to support performance level

- alicloud/resource_alicloud_slb_listener.go
- alicloud/resource_alicloud_slb_listener_test.go
updated file:
- resource_alicloud_slb_listener.go
- resource_alicloud_slb_listener_test.go
> resource/alicloud_slb_listener: Fixes the default parameter when updating the specified parameter with SetLoadBalancerHTTPSListenerAttribute Method

- alicloud/resource_alicloud_route_table.go
Updated File:
- resource_alicloud_route_table.go
remove
resource/alicloud_slb_listener: Fixes the default parameter when updating the specified parameter with SetLoadBalancerHTTPSListenerAttribute Method (#3735)
> resource/alicloud_route_table: Removes  the specified expectedError into Retry Process with Delete Method

- website/docs/r/cms_alarm.html.markdown
Current [cms_alarm documentation](https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/cms_alarm) is not up to date with the code. In this PR I would like to add missing values for `statistics` parameter according to schema defined in `resource_alicloud_cms_alarm.go`
> docs/alicloud_cms_alarm: Adds missing values for cms_alarm statistics

- alicloud/data_source_alicloud_cen_transit_router_route_entries_test.go
- alicloud/data_source_alicloud_cen_transit_router_route_table_associations_test.go
- alicloud/data_source_alicloud_cen_transit_router_route_table_propagations_test.go
- alicloud/data_source_alicloud_cen_transit_router_vbr_attachments_test.go
- alicloud/data_source_alicloud_cen_vbr_health_checks_test.go
- alicloud/data_source_alicloud_express_connect_virtual_border_routers_test.go
- alicloud/resource_alicloud_amqp_virtual_host_test.go
- alicloud/resource_alicloud_cen_private_zone_test.go
- alicloud/resource_alicloud_cen_transit_router.go
- alicloud/resource_alicloud_cen_transit_router_route_entry_test.go
- alicloud/resource_alicloud_cen_transit_router_route_table_association_test.go
- alicloud/resource_alicloud_cen_transit_router_route_table_propagation_test.go
- alicloud/resource_alicloud_cen_transit_router_vbr_attachment_test.go
- alicloud/resource_alicloud_cen_vbr_health_check_test.go
> resource/alicloud_cen_transit_router: Fixes the ParameterInstanceId error when deleting the resource; Improves other testcases

- website/alicloud.erb
It had a repeated resource name
> website: Fixed the sidebar

- CHANGELOG.md
- alicloud/resource_alicloud_ess_scalingconfiguration.go
- website/docs/r/ess_scaling_configuration.html.markdown
=== RUN   TestAccAlicloudEssAlarmsDataSource
--- PASS: TestAccAlicloudEssAlarmsDataSource (120.67s)
=== RUN   TestAccAlicloudEssLifecycleHooksDataSource
--- PASS: TestAccAlicloudEssLifecycleHooksDataSource (70.88s)
=== RUN   TestAccAlicloudEssNotificationsDataSource
--- PASS: TestAccAlicloudEssNotificationsDataSource (52.87s)
--- PASS: TestAccAlicloudEssScalingconfigurationsDataSource (86.10s)
--- PASS: TestAccAlicloudEssScalinggroupsDataSource (69.97s)
--- PASS: TestAccAlicloudEssScalingrulesDataSource (93.81s)
=== RUN   TestAccAlicloudEssScheduledtasksDataSource
--- PASS: TestAccAlicloudEssScheduledtasksDataSource (93.22s)
=== …
> resource/alicloud_ess_scalingconfiguration: Adds new attribute resource_group_id to support set resource group

- CHANGELOG.md
- alicloud/data_source_alicloud_ess_scalingconfigurations.go
- alicloud/data_source_alicloud_ess_scalingconfigurations_test.go
- alicloud/resource_alicloud_ess_scaling_configuration.go
- alicloud/resource_alicloud_ess_scaling_configuration_test.go
- alicloud/service_alicloud_ess.go
- website/docs/d/ess_scaling_configurations.html.markdown
- website/docs/r/ess_scaling_configuration.html.markdown
--- PASS: TestAccAlicloudEssScalingconfigurationsDataSource (81.92s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  83.627s
--- PASS: TestAccAlicloudEssScalingconfigurationsDataSource (83.38s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  85.091s
> alicloud_ess_scalingconfiguration: Adds new attributes spot_strategy and spot_price_limit

- alicloud/resource_alicloud_bastionhost_instance.go
- alicloud/resource_alicloud_snat_entry.go
- alicloud/resource_alicloud_snat_entry_test.go
- alicloud/resource_alicloud_yundun_dbaudit_instance.go
- website/docs/r/snat_entry.html.markdown
> bug/alicloud_snat_entry: Corrected field `source_vswitch_id`, `source_cidr`  to `Computed`

- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_ecp_instance_types_test.go
- alicloud/data_source_alicloud_ecp_instances_test.go
- alicloud/data_source_alicloud_ecp_zones_test.go
- alicloud/resource_alicloud_ecp_instance.go
- alicloud/resource_alicloud_ecp_instance_test.go
- alicloud/resource_alicloud_gpdb_elastic_instance.go
- alicloud/resource_alicloud_gpdb_elastic_instance_test.go
- alicloud/service_alicloud_gpdb.go
- website/docs/r/gpdb_elastic_instance.html.markdown
…eters `db_instance_category`, `encryption_type`, `encryption_key`, `tags`.
> resource/alicloud_gpdb_elastic_instance: Add support for output parameters `db_instance_category`, `encryption_type`, `encryption_key`, `tags`.

- CHANGELOG.md
- alicloud/data_source_alicloud_ess_scalinggroups.go
- alicloud/data_source_alicloud_ess_scalinggroups_test.go
- alicloud/resource_alicloud_ess_scaling_group.go
- alicloud/resource_alicloud_ess_scaling_group_test.go
- alicloud/service_alicloud_ess.go
- website/docs/d/ess_scaling_groups.html.markdown
- website/docs/r/ess_scaling_group.html.markdown
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudEssScalingGroup -timeout=300m
=== RUN   TestAccAlicloudEssScalingGroupsDataSource
--- PASS: TestAccAlicloudEssScalingGroupsDataSource (79.53s)
--- PASS: TestAccAlicloudEssScalingGroup_basic (114.51s)
=== RUN   TestAccAlicloudEssScalingGroup_launchTemplateIdAndTags
--- PASS: TestAccAlicloudEssScalingGroup_launchTemplateIdAndTags (58.19s)
=== RUN   TestAccAlicloudEssScalingGroup_costoptimized
--- PASS: TestAccAlicloudEssScalingGroup_costoptimized (92.29s)
--- PASS: TestAccAlicloudEssScalingGroup_vpc (91.56s)
--- PASS: TestAccAlicloudEssScalingGroup_slb (127.41s)
PASS
ok …
> resource/alicloud_ess_scaling_group: Add support for new parameter `tags`

- CHANGELOG.md
- alicloud/provider.go
- alicloud/resource_alicloud_ess_eci_scaling_configuration.go
- alicloud/resource_alicloud_ess_eci_scaling_configuration_test.go
- alicloud/resource_alicloud_ess_scaling_group.go
- alicloud/resource_alicloud_ess_scaling_group_test.go
- alicloud/service_alicloud_ess.go
- website/docs/r/ess_eci_scaling_configuration.html.markdown
- website/docs/r/ess_scaling_group.html.markdown
=== RUN   TestAccAlicloudEssAlarmsDataSource
--- PASS: TestAccAlicloudEssAlarmsDataSource (144.03s)
=== RUN   TestAccAlicloudEssLifecycleHooksDataSource
--- PASS: TestAccAlicloudEssLifecycleHooksDataSource (76.78s)
=== RUN   TestAccAlicloudEssNotificationsDataSource
--- PASS: TestAccAlicloudEssNotificationsDataSource (58.46s)
--- PASS: TestAccAlicloudEssScalingconfigurationsDataSource (100.20s)
=== RUN   TestAccAlicloudEssScalingGroupsDataSource
--- PASS: TestAccAlicloudEssScalingGroupsDataSource (85.78s)
=== RUN   TestAccAlicloudEssScheduledtasksDataSource
--- PASS: TestAccAlicloudEssScheduledtasksDataSource (108.77s)
=== RUN   TestAccAlicloudEssAlarmBasic
--- PASS: TestAccAlicloudEssAlarmBasic (178.03s)
=== RUN …
> **New Resource:** `alicloud_ess_eci_scaling_configuration`

- alicloud/resource_alicloud_resource_manager_shared_resource.go
- alicloud/resource_alicloud_resource_manager_shared_resource_test.go
- website/docs/r/resource_manager_shared_resource.html.markdown
resource/alicloud_resource_manager_shared_resource: The `resource_type` attribute supports the option of `ROSTemplate` and `ServiceCatalogPortfolio`.
> resource/alicloud_resource_manager_shared_resource: The `resource_type` attribute supports the option of `ROSTemplate` and `ServiceCatalogPortfolio`.

- alicloud/connectivity/client.go
- alicloud/connectivity/config.go
- alicloud/connectivity/regions.go
- alicloud/data_source_alicloud_schedulerx_namespaces.go
- alicloud/data_source_alicloud_schedulerx_namespaces_test.go
- alicloud/provider.go
- alicloud/resource_alicloud_schedulerx_namespace.go
- alicloud/resource_alicloud_schedulerx_namespace_test.go
- alicloud/service_alicloud_schedulerx2.go
- website/docs/d/schedulerx_namespaces.html.markdown
- website/docs/r/schedulerx_namespace.html.markdown
New Datasource `alicloud_schedulerx_namespaces`
> New Resource `alicloud_schedulerx_namespace` New Datasource `alicloud_schedulerx_namespaces`

- website/alicloud.erb
- website/docs/d/config_delivery_channels.html.markdown
- website/docs/r/config_delivery_channel.html.markdown
doc/config_delivery_channels: Add `DEPRECATED` identity;
docs_website: Remove the link address of the `alicloud_cdn_domain`.
> doc/config_delivery_channels: Add `DEPRECATED` identity; docs_website: Remove the link address of the `alicloud_cdn_domain`.

- website/docs/d/cs_kubernetes_version.html.markdown
Error: Unsupported argument
on main.tf line 6, in data "alicloud_cs_kubernetes_version" "default":
6:   version = "1.22.3-aliyun.1"
An argument named "version" is not expected here.
> doc/cs_kubernetes_version: fix doc field error

- alicloud/resource_alicloud_polardb_global_database_network.go
- website/docs/r/polardb_global_database_network.html.markdown
resource/alicloud_polardb_global_database_network: Enlarges the default waiting timeout for deleting the PolarDB Global Database Network.
> resource/alicloud_polardb_global_database_network: Enlarges the default waiting timeout for deleting the PolarDB Global Database Network.

- alicloud/resource_alicloud_lindorm_instance.go
- alicloud/resource_alicloud_lindorm_instance_test.go
- website/docs/r/lindorm_instance.html.markdown
resource/alicloud_lindorm_instance: Field 'time_serires_engine_specification' deprecated and instead by 'time_series_engine_specification'.
> resource/alicloud_lindorm_instance: Field 'time_serires_engine_specification' deprecated and instead by 'time_series_engine_specification'.

- alicloud/data_source_alicloud_alb_system_security_policies.go
- alicloud/data_source_alicloud_alb_system_security_policies_test.go
- alicloud/provider.go
- go.sum
- vendor/github.com/alibabacloud-go/tea-utils/LICENSE
- website/docs/d/alb_system_security_policies.html.markdown
This PR is to add a new `datasource` named `alicloud_alb_system_security_policies` to fetch system security policies of ALB.
Fix issue: https://github.com/aliyun/terraform-provider-alicloud/issues/5304
> new data source alicloud_alb_system_security_policies

- alicloud/data_source_alicloud_alb_system_security_policies_test.go
This PR is to fix the following issue for acc test of alb system security policies.
`
testing.go:635: Step 0 error: config is invalid: Invalid reference: A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
`
> testcase: fix issue for acc test of alb system security policies

- alicloud/resource_alicloud_cen_transit_router_vpc_attachment.go
- alicloud/resource_alicloud_cen_transit_router_vpc_attachment_test.go
- website/docs/r/cen_transit_router_vpc_attachment.html.markdown
resource/alicloud_cen_transit_router_vpc_attachment: Removes the field `zone_mappings` forceNew and supports modifying it online.
> resource/alicloud_cen_transit_router_vpc_attachment: Removes the field `zone_mappings` forceNew and supports modifying it online.

- alicloud/resource_alicloud_vpn_gateway_vpn_attachment.go
resource/alicloud_vpn_gateway_vpn_attachment: Fix error ModifyVpnAttachmentAttribute Api missing RegionId parameters.
> resource/alicloud_vpn_gateway_vpn_attachment: Fix error ModifyVpnAttachmentAttribute Api missing RegionId parameters.

- alicloud/data_source_alicloud_instance_types.go
Ref: https://help.aliyun.com/document_detail/25620.html
> 说明 支持模糊匹配，如某规格的GPU类型为NVIDIA V100，输入NVIDIA也可查询到该规格信息。
Translate
> NOTE: fuzzy matching is supported, e.g. argument "NVIDIA" will match those ecs instance types with GPU "NVIDIA V100"
> data/alicloud_instance_types: substring match for gpu_spec

- alicloud/resource_alicloud_resource_manager_shared_resource.go
- alicloud/resource_alicloud_resource_manager_shared_resource_test.go
- website/docs/r/resource_manager_shared_resource.html.markdown
resource/alicloud_resource_manager_shared_resource: The `resource_type` attribute supports the option of `PrefixList` and `Image`.
> resource/alicloud_resource_manager_shared_resource: The `resource_type` attribute supports the option of `PrefixList` and `Image`.

- alicloud/data_source_alicloud_cloud_firewall_vpc_firewall_cens_test.go
- alicloud/resource_alicloud_cloud_firewall_vpc_firewall_cen.go
- alicloud/resource_alicloud_cloud_firewall_vpc_firewall_cen_test.go
resource/alicloud_cloud_firewall_vpc_firewall_cen: Field `vpc_region` add `ForceNew` setting and add constraints to the test.
> resource/alicloud_cloud_firewall_vpc_firewall_cen: Field `vpc_region` add `ForceNew` setting and add constraints to the test.

- alicloud/resource_alicloud_alb_server_group.go
- alicloud/resource_alicloud_alb_server_group_test.go
- website/docs/r/alb_server_group.html.markdown
resource/alicloud_alb_server_group: Support new attribute `remote_ip_enabled`; Add optional `Ip` and `Fc` for `server_type`.
> resource/alicloud_alb_server_group: Support new attribute `remote_ip_enabled`; Add optional `Ip` and `Fc` for `server_type`.

- alicloud/resource_alicloud_alb_rule.go
- website/docs/r/alb_rule.html.markdown
resource/alicloud_alb_rule: Fix errors when the `weight` attribute is not configured.
> resource/alicloud_alb_rule: Fix errors when the `weight` attribute is not configured.

- alicloud/resource_alicloud_resource_manager_shared_resource.go
- website/docs/r/resource_manager_shared_resource.html.markdown
resource/alicloud_resource_manager_shared_resource: The resource_type attribute supports the option of `PublicIpAddressPool`.
> resource/alicloud_resource_manager_shared_resource: The resource_type attribute supports the option of `PublicIpAddressPool`.

- alicloud/resource_alicloud_ots_instance.go
``` bash
ᐅ TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudOtsInstance_ -timeout=100m
=== RUN   TestAccAlicloudOtsInstance_basic
--- PASS: TestAccAlicloudOtsInstance_basic (514.82s)
=== RUN   TestAccAlicloudOtsInstance_multi
--- PASS: TestAccAlicloudOtsInstance_multi (509.63s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  1026.578s
```
The error report before the modification, the parameter inspection exception is reported, and it needs to wait for 10m：
```go 
alicloud_ots_instance.default: Still destroying... [id=tf-test, 9m40s elapsed]
alicloud_ots_instance.default: Still destroying... [id=tf-test, **9m50s elapsed**]
╷
│ Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_ots_instance.go:224: Resource tf-test DeleteInstance Failed!!! [SDK …
```
> resource/alicloud_ots_instance: Fixes the 10min slow return of ValidationFailed for ots instance delete.

- alicloud/resource_alicloud_route_entry.go
- website/docs/r/vswitch.html.markdown
resource/alicloud_route_entry: Adds retry for `IncorrectStatus.VpcPeer` error when creating.
doc/vswitch: Add an example of creating a cidr switch.
> resource/alicloud_route_entry: Adds retry for `IncorrectStatus.VpcPeer` error when creating.  doc/vswitch: Add an example of creating a cidr switch.

- alicloud/resource_alicloud_mongodb_instance.go
- alicloud/resource_alicloud_mongodb_instance_test.go
- alicloud/service_alicloud_mongodb.go
- website/docs/r/mongodb_instance.html.markdown
resource/alicloud_mongodb_instance: Support new attribute `readonly_replicas`, `storage_type`, `hidden_zone_id`, `secondary_zone_id`.
> resource/alicloud_mongodb_instance: Support new attribute `readonly_replicas`, `storage_type`, `hidden_zone_id`, `secondary_zone_id`.

- alicloud/resource_alicloud_lindorm_instance.go
- alicloud/resource_alicloud_lindorm_instance_test.go
- website/docs/r/lindorm_instance.html.markdown
> resource/alicloud_lindorm_instance: Fixes the upgrading core_single_storage does not work bug; Enlarges the update default timeout to 180 mins

- alicloud/resource_alicloud_alikafka_instance.go
- alicloud/resource_alicloud_alikafka_instance_test.go
- website/docs/r/alikafka_instance.html.markdown
resource/alicloud_alikafka_instance: Support new attribute `io_max_spec`.
> resource/alicloud_alikafka_instance: Support new attribute `io_max_spec`.

- alicloud/resource_alicloud_nlb_server_group_server_attachment.go
resource/alicloud_nlb_server_group_server_attachment:  Add retry error code `IncorrectStatus.serverGroup`  when deleting.
> resource/alicloud_nlb_server_group_server_attachment:  Add retry error code `IncorrectStatus.serverGroup`  when deleting.

- alicloud/resource_alicloud_nlb_server_group.go
resource/alicloud_nlb_server_group: setting the attribute http_check_method to computed, Fix an error with empty http_check_method attribute.
> resource/alicloud_nlb_server_group: setting the attribute http_check_method to computed, Fix an error with empty http_check_method attribute.

- alicloud/resource_alicloud_vpc_peer_connection.go
> resource/alicloud_vpc_peer_connection: Fixes the ResourceNotFound.InstanceId error when destroying it

- alicloud/connectivity/client.go
- alicloud/connectivity/endpoint.go
- alicloud/resource_alicloud_ots_instance.go
- alicloud/resource_alicloud_ots_instance_test.go
- alicloud/service_alicloud_ots.go
OTS Upgrade api from 2017 to 2020(by roa tea-rpc client): `CreateInstance`, `UpdateInstance`, `DeleteInstance`.
Resource Acc
``` bash
(base) ~/GolandProjects/terraform-provider-alicloud ᐅ GODEBUG=asyncpreemptoff=1 TF_ACC=1 go test ./alicloud -v -run='TestAccAlicloudOtsInstance_basic' -timeout=100m 
=== RUN   TestAccAlicloudOtsInstance_basic
--- PASS: TestAccAlicloudOtsInstance_basic (518.50s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  530.663s
```
Data Acc
``` bash
~/GolandProjects/terraform-provider-alicloud ᐅ GODEBUG=asyncpreemptoff=1 TF_ACC=1 go test ./alicloud -v -run='TestAccAlicloudOtsInstancesDataSource' -timeout=100m
=== RUN   TestAccAlicloudOtsInstancesDataSource
--- PASS: TestAccAlicloudOtsInstancesDataSource (551.05s)
PASS
ok …
```
> resource/alicloud_ots_instance: Upgrade openapi version

- website/docs/d/click_house_regions.html.markdown
docs: fix typo in description of click_house_regions.
> docs: fix typo in description of click_house_regions.

- alicloud/resource_alicloud_ess_scaling_group.go
- alicloud/resource_alicloud_ess_scaling_group_test.go
> resource/alicloud_ess_scaling_group: Fixed weighted_capacity and spot_price_limit is null.

- alicloud/resource_alicloud_governance_account.go
- alicloud/resource_alicloud_governance_account_test.go
- examples/governance/main.tf
- examples/governance/outputs.tf
- examples/governance/variables.tf
- examples/governance/versions.tf
- website/docs/r/governance_account.html.markdown
resource/alicloud_governance_account: Supports a new argument default_domain_name.
> resource/alicloud_governance_account: Supports a new argument default_domain_name.

- alicloud/resource_alicloud_gpdb_db_instance_plan.go
- alicloud/resource_alicloud_gpdb_db_instance_plan_test.go
- alicloud/resource_alicloud_gpdb_instance.go
- alicloud/resource_alicloud_gpdb_instance_test.go
- alicloud/service_alicloud_gpdb.go
- website/docs/r/gpdb_db_instance_plan.html.markdown
- website/docs/r/gpdb_instance.html.markdown
resource/alicloud_gpdb_db_instance_plan: add new attribute scale_up, scale_down; resource/alicloud_gpdb_instance: add new attribute parameters.
> resource/alicloud_gpdb_db_instance_plan: add new attribute scale_up, scale_down; resource/alicloud_gpdb_instance: add new attribute parameters.

- alicloud/resource_alicloud_ess_scaling_configuration.go
- alicloud/resource_alicloud_ess_scaling_configuration_test.go
- website/docs/r/ess_scaling_configuration.html.markdown
> resource/alicloud_ess_scaling_configuration: add attribute custom_priorities.

- alicloud/connectivity/client.go
- alicloud/data_source_alicloud_kvstore_instances.go
- alicloud/resource_alicloud_kvstore_audit_log_config.go
- alicloud/resource_alicloud_kvstore_instance.go
- alicloud/resource_alicloud_kvstore_instance_test.go
- alicloud/resource_alicloud_redis_tair_instance.go
- alicloud/service_alicloud_r_kvstore.go
- alicloud/service_alicloud_redis_v2.go
- website/docs/d/kvstore_instances.html.markdown
> Redis: Improves the invoking redis api method and supports refreshing credential automatically

- alicloud/resource_alicloud_oss_bucket.go
- alicloud/resource_alicloud_oss_bucket_test.go
> resource/alicloud_oss_bucket: Fixes the panic error when not setting bucket name explicitly

- website/docs/r/ecs_network_interface.html.markdown
This helps clarify issue #7962
> docs: specify security group for alicloud_ecs_network_interface

- alicloud/resource_alicloud_db_instance.go
- alicloud/resource_alicloud_db_instance_test.go
- website/docs/r/db_instance.html.markdown
resource/alicloud_db_instance: add new attributes:bursting_enabled and modify sql_collector_config_value
> resource/alicloud_db_instance: add new attributes:bursting_enabled and modify sql_collector_config_value

- alicloud/resource_alicloud_cs_kubernetes_node_pool.go
- alicloud/resource_alicloud_cs_kubernetes_node_pool_test.go
- alicloud/service_alicloud_ack_v2.go
- website/docs/r/cs_kubernetes_node_pool.html.markdown
kubelet_configuration param: 
- cluster_dns
- container_log_max_workers
- container_log_monitor_interval
- cpu_cfs_quota, cpu_cfs_quota_period
- image_gc_high_threshold_percent
- image_gc_low_threshold_percent
- memory_manager_policy
- pod_pids_limit
- reserved_memory
- topology_manager_policy
- tracing
> resource/alicloud_cs_kubernetes_node_pool: support param ram_role_name; support kubelet_configuration params.

- alicloud/resource_alicloud_cloud_monitor_service_basic_public.go
- alicloud/service_alicloud_cloud_monitor_service_v2.go
> resource/alicloud_cloud_monitor_service_basic_public: Improves the invoking api method and supports refreshing credential automatically

- alicloud/data_source_alicloud_vpn_gateway_vco_routes.go
- alicloud/data_source_alicloud_vpn_gateway_vco_routes_test.go
- alicloud/data_source_alicloud_vpn_gateway_vpn_attachments.go
- alicloud/data_source_alicloud_vpn_gateways.go
- alicloud/data_source_alicloud_vpn_ipsec_servers.go
- alicloud/data_source_alicloud_vpn_ipsec_servers_test.go
- alicloud/data_source_alicloud_vpn_pbr_route_entries.go
- alicloud/data_source_alicloud_vpn_pbr_route_entries_test.go
- alicloud/resource_alicloud_nat_gateway.go
- alicloud/resource_alicloud_nat_gateway_test.go
- alicloud/resource_alicloud_vpn_gateway_vco_route.go
- alicloud/resource_alicloud_vpn_gateway_vpn_attachment.go
- alicloud/resource_alicloud_vpn_gateway_vpn_attachment_test.go
- alicloud/resource_alicloud_vpn_ipsec_server.go
- alicloud/resource_alicloud_vpn_ipsec_server_test.go
- alicloud/resource_alicloud_vpn_pbr_route_entry.go
- alicloud/resource_alicloud_vpn_pbr_route_entry_test.go
- alicloud/resource_alicloud_vpn_route_entry.go
- alicloud/service_alicloud_vpc.go
- website/docs/d/nat_gateways.html.markdown
- website/docs/d/vpn_gateway_vco_routes.html.markdown
- website/docs/d/vpn_gateway_vpn_attachments.html.markdown
- website/docs/d/vpn_gateways.html.markdown
- website/docs/d/vpn_ipsec_servers.html.markdown
> VpnGateway: Improves the invoking api method and supports refreshing credential automatically

- alicloud/resource_alicloud_fc_layer_version.go
**What's the problem?**
With the current version, a FC layer can be created with a local zipfile, but the plugin is unable to do any follow-up `terraform plan` or `terraform apply`. In my testing ,my custom layer was only 1.2 MB, but still exceeding the grpc maximum input limit. I think it's because the provider plugin is trying to compare the encoded base64 contents. For a zipfile, it's payload can be incredibly large...
Error message:
```
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: Plugin error
│
│   with module.ami-manager.alicloud_fc_layer_version.ecs_layer,
│   on ../../../core-alicloud-ami-manager/function.tf line 25, in resource "alicloud_fc_layer_version" "ecs_layer":
│   25: resource "alicloud_fc_layer_version" "ecs_layer" {
│
│ The …
```
> resource/alicloud_fc_layer_version: fix loading the file content instead of base64 encoded payload for uploading the zipfile

- alicloud/resource_alicloud_click_house_db_cluster.go
- alicloud/resource_alicloud_click_house_db_cluster_test.go
- website/docs/r/click_house_db_cluster.html.markdown
resource/alicloud_click_house_db_cluster: add support to open public connection.
> resource/alicloud_click_house_db_cluster: add support to open public connection.

- alicloud/resource_alicloud_click_house_db_cluster.go
- alicloud/resource_alicloud_click_house_db_cluster_test.go
- alicloud/service_alicloud_clickhouse.go
- website/docs/r/click_house_db_cluster.html.markdown
resource/alicloud_click_house_db_cluster: add support to creating cold storage.
> resource/alicloud_click_house_db_cluster: add support to creating cold storage.

- alicloud/resource_alicloud_mse_cluster.go
- alicloud/resource_alicloud_mse_cluster_test.go
- website/docs/r/mse_cluster.html.markdown
A version_code field has been added to identify the specific instance version. When version_code is LATEST, the system checks whether the instance is the latest version and plans an upgrade. If version_code is a specific version number, the system compares the version number to see if it has changed. If so, the system checks whether the instance is the latest version. If it meets the requirements, an upgrade is triggered.
MSE cluster resource restrictions only support upgrades to the latest version; upgrades to a specific version are not supported. The logic is the same as in the MSE console.
> resource/alicloud_mse_cluster: add resource version upgrade capability
